### ISSUE TITLE
Svelte Beta in VS Code broken when using `<Script>` component

### ISSUE THREAD

**Issue by elgertam** [sveltejs/language-tools#100]
**Describe the bug**
Our project has a component named `Script`. When we instantiate that component, VS Code shows dozens of errors from the Svelte lang server. Renaming the component to something like `MyScript` before instantiation removes all errors.

**To Reproduce**

1. Create the following files in a Svelte project:

`Script.svelte`:
```
<script>
  export let title = 'Working Draft';
  export let you = 'you';
</script>

<p>A film named {title} starring {you}</p>
```

`App.svelte`:
```
<script>
  import Script from './Script.svelte';

  let y = { x: 1, y: 0};
</script>

<h1>Film</h1>

<Script title="Svelte: The Documentary" you="Rich Harris" />
```

2. Open in VS Code w/ the Svelte Beta extension active

3. Observe errors in `App.svelte` in "Problems" pane (View -> Problems)

**Expected behavior**
I would expect the language server to recognize `<Script .../>` as a component and not a script tag, especially since the code compiles.

**Screenshots**

With `<Script ... />`:
![Screen Shot 2020-05-20 at 3 29 45 PM](https://user-images.githubusercontent.com/1118015/82489021-f09c8d00-9aae-11ea-905f-5552c9428275.png)

With `<MyScript ... />`:
![Screen Shot 2020-05-20 at 3 36 18 PM](https://user-images.githubusercontent.com/1118015/82489510-c6979a80-9aaf-11ea-906e-4b53bb949ab2.png)

**System (please complete the following information):**
 - OS: macOS
 - IDE: VSCode
 - Plugin: [Svelte Beta](https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode#review-details)

**Comment by dummdidumm** [comment]
Should be fixed now.
