### ISSUE TITLE
Incorrect typescript error when `<script context="module">` is present in file

### ISSUE THREAD

**Issue by maximedupre** [sveltejs/language-tools#101]
![Screen Shot 2020-05-20 at 7 48 44 PM](https://user-images.githubusercontent.com/5158181/82508433-0328bd80-9ad3-11ea-91b8-a77412d1ce86.png)

The typescript error disappears as soon as I comment out the `<script context="module">`:

![Screen Shot 2020-05-20 at 7 49 17 PM](https://user-images.githubusercontent.com/5158181/82508451-13d93380-9ad3-11ea-8e80-54194926512d.png)

Maybe related to #100

**Comment by jasonlyu123** [comment]
Currently it only looking for the topmost script's lang/text attribute. But we discussed before and think we should check all of them and take typescript as priority.

**Comment by dummdidumm** [comment]
If you add lang="typescript" to the module script, does the error disappear?

**Comment by maximedupre** [comment]
> If you add lang="typescript" to the module script, does the error disappear?

Yep, this workaround works!

**Comment by dummdidumm** [comment]
Fixed, should be available in about 12 hours. Note though that if you start using typescript in the `<script context="module">`-tag, you need to add `lang="ts"` to it. Else `svelte-preprocess` will not preprocess the code and svelte will throw an error.
