### ISSUE TITLE
Missing `svelte:fragment` vocabulary

### ISSUE THREAD

**Issue by lukeed** [sveltejs/language-tools#1012]
**Describe the bug**

The [`<svelte:fragment/>` tag](https://github.com/sveltejs/svelte/pull/4556) is not a member of the known internal `svelte` tags.

**To Reproduce**

Paste [tutorial contents](https://svelte.dev/tutorial/svelte-fragment) into VS Code

**Expected behavior**

Should be allowed/known.

**Screenshots**

<img width="623" alt="Screen Shot 2021-05-18 at 10 29 53 AM" src="https://user-images.githubusercontent.com/5855893/118697282-fdd48080-b7c3-11eb-9c88-826269d161c4.png">

**System (please complete the following information):**
 - OS: macOS 10.15.7
 - IDE: VS Code 1.51.1
 - Plugin/Package: Svelte for VSCode 102.8.0

**Comment by jasonlyu123** [comment]
Seems like you have an old version of the extension. The latest version requires vscode ^1.52.

**Comment by lukeed** [comment]
Thanks, that was it :) I set this machine up a couple weeks ago, so thought I was on latest of everything.
