### ISSUE TITLE
VSCode Extension: Errors/Warnings don't refresh (or are incorrect) if there is an unused CSS selector, when using PostCSS

### ISSUE THREAD

**Issue by danieldiekmeier** [sveltejs/language-tools#1019]
**Describe the bug**

I stumbled over a weird error, where the errors/warnings (aka the yellow and red squiggly lines in the editor) are not updated (or are incorrect), if I use `svelte-preprocess` with PostCSS and have an unused Selector in the CSS.

Screenshot so it's a bit clearer what I'm talking about:

<img src="https://user-images.githubusercontent.com/2098462/119243269-7b521500-bb65-11eb-8cd8-8daffd567c46.png" width="400">

My `svelte.config.js`:

```js
const preprocess = require('svelte-preprocess')

module.exports = {
  preprocess: preprocess({
    postcss: true,
  }),
}
```

Example component:

```svelte
<script>
  const a = 10
</script>

<div>{a}</div>

<style>
  .unused {
    background-color: red;
  }
</style>

```

The bug doesn't happen if I comment out `postcss: true`. I tried removing all my PostCSS plugins, but that didn't change the behavior. Additionally, I noticed that I don't actually get a warning for the unused CSS selector in VSCode at all. (I _do_ get it when I run `svelte-check`, so the basic functionality should be there?)

I hope I provided any relevant information here, but I'm glad to clarify anything that's unclear.

**To Reproduce**

- Configure `svelte-preprocess` with `postcss: true`
- In a Svelte file, use a `<style>` tag that contains at least one unused CSS selector
- Edit the rest of the file in a way that should produce a warning
- Thy typical helpful warnings and errors will not refresh, or they'll show an `Unexpected token` error in unexpected places

**Expected behavior**

- Errors and warnings should work in exactly the same way as they do when no unused selector appears in the `<style>` tag

**Screenshots**

<details>
<summary>Toggle, because they are pretty large</summary>

I start from this working example: Svelte can correctly identify that I did in fact define `a` before using it. It can also tell that the `div` is a used selector in this context.

![image](https://user-images.githubusercontent.com/2098462/119242697-6de65c00-bb60-11eb-8537-b8a7963c001f.png)

And if I change the variable name from `a` to `b`, it correctly warns me:

![image](https://user-images.githubusercontent.com/2098462/119242708-8a829400-bb60-11eb-9355-85ba538898b4.png)

If I then change the CSS selector to something that's not used in the component, it still warns me:

![image](https://user-images.githubusercontent.com/2098462/119242725-ac7c1680-bb60-11eb-9c40-d4d217ddbf6b.png)

But if I then change the variable name back from `b` to `a`, it _still warns me_:

![image](https://user-images.githubusercontent.com/2098462/119242739-c3bb0400-bb60-11eb-97b9-161afeb95292.png)

In fact, it will not correctly refresh the warnings/errors and be pretty confused, no matter what I do:

![image](https://user-images.githubusercontent.com/2098462/119242771-13013480-bb61-11eb-96b9-a9c495898afc.png)

</details>

**System**
 - OS: macOS 11.3.1
 - IDE: VSCode 1.56.2
 - Plugin/Package: Svelte for VSCode v104.12.2

**Comment by madupuis90** [comment]
I'm having the same problems. Random typescript errors that were only fixed when I commented my scss styles. 

![unknown](https://user-images.githubusercontent.com/76877179/119371569-92d3ef80-bc84-11eb-9d91-5f67229d7a33.png)

```
<style lang="scss">
  @import "bulma/bulma.sass";
</style>
```

**Comment by jasonlyu123** [comment]
The cause of this seems to be because some svelte diagnostics, like unused-export-let or css-unused-selector, can't be source mapped back to the original position. But there might be multiple causes of the source mapping issue. I think we can at least place it at the start of the file to avoid this specific problem.

**Comment by dummdidumm** [comment]
I can't reproduce this yet. What I see though is that because of `postcss: true`, the source maps are messed up (guess we can't do much there if no proper source map was provided). I don't get unmapped/negative lines through that though.

**Comment by jasonlyu123** [comment]
A preprocess without a source map might reproduce the problem I mentioned.

**Comment by dummdidumm** [comment]
Version 105 of the extension was released where I tried to be more robust about possibly invalid mappings. Please let me know if that fixed it or if the issue still persists.

**Comment by danieldiekmeier** [comment]
Looks good! The warning does show up now, and I can still edit the rest of the files as before. Thanks for looking into this!

![image](https://user-images.githubusercontent.com/2098462/119964371-6e8c5180-bfa9-11eb-8530-b7de53069127.png)

**Comment by madupuis90** [comment]
Version 105 seeems to fix my issue too. Thanks for the quick fix
