### ISSUE TITLE
Question: how to work with imports from virtual file

### ISSUE THREAD

**Issue by mvolfik** [sveltejs/language-tools#1020]
My SvelteKit app globally needs some data from markdown+front matter files stored in the repo. As these are static during the app runtime, I figured it would be easiest to include the compiled data as a virtual file with a simple [Vite plugin as per docs](https://vitejs.dev/guide/api-plugin.html#importing-a-virtual-file).

However, now VS code and `svelte-check` report errors, as they obviously don't find the file when I `import data from @virtual-file`

I'm not very versed with the JS tooling ecosystem, but I wonder if there's a way to teach the tools about what they should expect in the file. I'm using typescript if that would help with some shimming.

**System**
- OS: Ubuntu 20.04.1 LTS
- IDE: VS Code 1.56.2 with Svelte for VS Code 104.12.2
- svelte-check 1.5.4

_Also if there's a more idiomatic way to include the static data in the project I'm open to suggestions - so far I only saw [git-pod website](https://github.com/gitpod-io/website) working with markdown (shoutout to last Svelte Radio episode where I found out about it and about the idea of using the underlying Vite), but their way of using mdsvex unfortunately wouldn't work for me._

**Comment by mvolfik** [comment]
I figured it out - I added this in `tsconfig.json`:

```js
{
  // ...
  "paths": [
    // ...
    "@virtual-file": "src/@virtual-file"
  ]
}
```

And in `src/@virtual-file.d.ts` added the shims:
```ts
export const data: { foo: string };
```

Perhaps this helps someone one day. Thanks for the awesome work on Svelte everyone!

**Comment by dummdidumm** [comment]
The shorter way probably is to enhance your `global.d.ts` file and add

````ts
declare module "@virtual-file" {
   // whatever you need to have in that file. For example
  const data: { foo: string};
  export default data;
}
```
