### ISSUE TITLE
Clear the screen on svelte-check --watch reruns

### ISSUE THREAD

**Issue by thislooksfun** [sveltejs/language-tools#1025]
**Is your feature request related to a problem? Please describe.**
I need to run `svelte-check` to check if there are any errors in my ts code, but every time I save a file it just appends to the output of the previous run. This quickly fills up the terminal and also makes it hard to scan for remaining errors as I first have to figure out where on the screen the most recent run started. In contrast `tsc --watch --noEmit` (which is essentially the same thing but for .ts files) neatly displays *only* the most recent run, which means that it's easy to scan for remaining issues.

**Describe the solution you'd like**
I want `svelte-check --watch` to clear the screen before performing a run, like `tsc --watch` does.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dummdidumm** [comment]
For me `tsc` only clears the screen but it doesn't remove any previous messages. I also think that clearing previous runs isn't possible. We can make it start at the top of the terminal though (if that is what you meant by "clear the screen").
