### ISSUE TITLE
SVG `fillRule` attribute is not recognized

### ISSUE THREAD

**Issue by ebeloded** [sveltejs/language-tools#1034]
**Describe the bug**
If `svg` element has `fillRule` property, the following error appears:
```
Property 'fillrule` does not exist on type SVGProps<SVGSVGElement>
```
Note the lowercasing in the error message. The `fillRule` does exist on SVGAttrubutes interface, but for some reason the prop gets lowercased. Same doesn't happen for the `viewBox` attribute - it is recognized as is.

**To Reproduce**

```html
<svg fillRule="evenodd">
</svg>
```

**Expected behavior**
Expected to see no error

**Screenshots**
![image](https://user-images.githubusercontent.com/5859177/119929511-e194c880-bfa7-11eb-961c-b5a15d0d1e44.png)

**System (please complete the following information):**
 - OS: Mac OS
 - IDE: VSCode
 - Plugin/Package: svelte2tsx, I guess 
 
 **Workaround**
I don't know a workaround, but it would helpful to know if there is a way to use tsignore in Svelte templates

**Comment by dummdidumm** [comment]
The attribute is called `fill-rule`, we need to change that in the typings.
