### ISSUE TITLE
Changes to TypeScript definition files in linked modules not detected by Language Server

### ISSUE THREAD

**Issue by jstarmx** [sveltejs/language-tools#1037]
**Describe the bug**
Svelte Language Server does not pick up changes to TypeScript definition files in linked modules without being restarted.

**To Reproduce**
1. Clone this repo: https://github.com/jstarmx/svelte-typescript-test
2. Follow setup instructions
3. Open `/app/src/App.svelte`
4. Open `/package/src/Alert.d.ts`
5. Change the type of `text` on line 4 from `string` to something else, e.g. `number`
6. Observe that the problems panel in VS Code does not show any errors
7. Restart Svelte Language Server
8. Observe that the problems panel now shows an error in `App.svelte`

**Expected behavior**
Problems panel to display the error without needing to restart Svelte Language Server

**System (please complete the following information):**
 - OS: macOS Big Sur 11.3.1
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode

**Additional context**
Happy to try to contribute a fix if you think it's do-able/worthwhile/actually an issue...

**Comment by dummdidumm** [comment]
There are two problems to this:
- File paths are not the same (case-sensitivity-wise), we need to normalize them
- If the service for a TS file is searched, it doesn't take into account existing services where the file is already present but where the file is not the child of that tsconfig. This means that `package/src/Alert.d.ts` is moved to another TS service. I think we need to change the update logic there to go through all existing services, too, and update them accordingly (99% of the time there will be only one).

**Comment by jstarmx** [comment]
@dummdidumm thanks for looking into this so quickly, that's fantastic 👍

**Comment by fkling** [comment]
Just wanted to note that I experienced the same problem in **neovim** (it works fine in VSCode). I was able to get it to work by configuring the lsp client to use the repo root as root directory. Something like

```lua
    require('lspconfig').svelte.setup {
      capabilities = capabilities,
      on_attach = on_attach,
      settings = servers.svelte,
      root_dir = require('lspconfig').util.find_git_ancestor
    }
```

I'm not familiar with all the lsp stuff to know why it works for other clients (e.g. tsserver) and other environments (e.g. vscode) but not in this case by default 🤷🏻‍♂️

**Comment by jasonlyu123** [comment]
That's tracked in #1415. And the reason is that we only have a directory file watcher, and the tsserver has watchers for individual files. It might consume more system resources, so I am hesitant if we should add that. As for VSCode, the LSP process starts in the workspace root. It doesn't open two processes because there are two `package.json`.

**Comment by fkling** [comment]
Thank you @jasonlyu123, I didn't find that issue!
