### ISSUE TITLE
Excludes not properly used with --tsconfig

### ISSUE THREAD

**Issue by thislooksfun** [sveltejs/language-tools#1038]
**Describe the bug**
When using `svelte-check --tsconfig ./tsconfig.json` some files in my `node_modules` are checked as well. This does not happen if I leave off the `--tsconfig` option or if I run `tsc --noEmit`.

**To Reproduce**

I haven't 100% worked out a minimal example, but you can see it here in the 'validate' step of [this run](https://github.com/thislooksfun/ecs/runs/2702289240?check_suite_focus=true), which was executing from thislooksfun/ecs@a10d678e99847a4d7328d936499e3215a9eec78b.

**Expected behavior**
I expect that my node_modules will be fully ignored, as specified in my tsconfig.

**Screenshots**
N/A

**System (please complete the following information):**
 - OS: N/A
 - IDE: N/A
 - Plugin/Package: svelte-check

**Additional context**
N/A

**Comment by dummdidumm** [comment]
Having a file on the exclude list doesn't exclude it, if it is imported through a file from the include/file list, which is the case here. The diagnostic shouldn't show up though because `skipLibCheck` is `true` and this is a `d.ts` file.
