### ISSUE TITLE
VS Code Extension CSS Diagnostic Setting not respected

### ISSUE THREAD

**Issue by alexanderniebuhr** [sveltejs/language-tools#1039]
**Describe the bug**
Using custom css syntax VS Code Extension throws error `svelte(css-syntax-error)`, with extension setting set to: `"svelte.plugin.css.diagnostics.enable": false`
```
{
	"resource": "/c:/.../tests/assets/input/windi/case-03.svelte",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "css-syntax-error",
	"severity": 8,
	"message": "Semicolon or block is expected\n\nIf you expect this syntax to work, here are some suggestions: \nIf you use less/SCSS with `svelte-preprocess`, did you add `lang=\"scss\"`/`lang=\"less\"` to you `style` tag? If you use SCSS, it may be necessary to add the path to your NODE runtime to the setting `svelte.language-server.runtime`, or use `sass` instead of `node-sass`. \nDid you setup a `svelte.config.js`? \nSee https://github.com/sveltejs/language-tools/tree/master/docs#using-with-preprocessors for more info.",
	"source": "svelte",
	"startLineNumber": 11,
	"startColumn": 28,
	"endLineNumber": 11,
	"endColumn": 28
}
```

**To Reproduce**
note: it is not scss or sass syntax. It is custom syntax
```svelte
<style>
  .custom {
    background: green;
  }
  :global(.me) {
    background: yellow;
  }
  a {
    @apply text-black hover:text-emerald-400;
  }
  :global(div) {
    @apply bg-light-800 dark:bg-dark-600;
  }
</style>

```

**Expected behavior**
`"svelte.plugin.css.diagnostics.enable": false` should disable error & warnings for wrong css syntax

**Screenshots**
![image](https://user-images.githubusercontent.com/45965090/120213220-3dbf4d00-c233-11eb-929e-7c3ef39af946.png)

**System (please complete the following information):**
 - OS: Windows
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode 105.0.0
 - 
**Additional context**
not sure, but I might guess of regression here. Since it worked in the past.

**Comment by dummdidumm** [comment]
This is expected behavior. The warning you are getting is not from CSS, but from the Svelte compiler who fails while trying to compile the file to provide diagnostics. I agree though that this is confusing since the error is still about CSS. The problem likely is that you don't tell the language tools how to preprocess the styles (you need a `svelte.config.js` for that, more in that [here](https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/in-general.md)). You can also choose to completely turn off Svelte compiler diagnostics, too, by turning off `svelte.plugin.svelte.diagnostics.enable`

**Comment by alexanderniebuhr** [comment]
@dummdidumm I have an svelte.config.js and it is not working correctly....

**Comment by alexanderniebuhr** [comment]
ok found the issue.. it somehow did not worked correctly with `sequential-preprocessor`
I think I can remove that for my project..

**Comment by dummdidumm** [comment]
There are many things going on at once in this preprocess config. I guess that `windi` is responsible for doing the style transformation. Does the error occur if you apply only this preprocessor? Like

```js
import { windi } from 'svelte-windicss-preprocess'

export default {
  preprocess: windi({
      silent: false,
      configPath: "windi.config.js",
      devTools: {
        enabled: false
      }
    })
}
```

**Comment by alexanderniebuhr** [comment]
no. as said earlier. It seems that the order get's confused on my preprocessors.. Thanks for the hint
