### ISSUE TITLE
Support glob/pattern for --ignore option

### ISSUE THREAD

**Issue by visma-sorinbroscaru** [sveltejs/language-tools#1047]
**Is your feature request related to a problem? Please describe.**

Provide the ability to ignore files based on GLOB like pattern. 
This will help ignore svelte file I use to either run tests ( jest ) or showcase stories inside storybook;
Ideally, I would also like to have the possibility to ignore based on patterns

**Describe the solution you'd like**
Idealy
```bash
svelte-check --ignore "**/__stories__,dist,build,**/__tests__"
```

**Describe alternatives you've considered**
```javascript
// validate.js
let glob = require('glob');

glob('**/src/**/__stories__', function (err, files) {
    files = files.map(f => f.replace('src/', ''));

    let validateJob;
    exit = () => {if (validateJob) validateJob.kill(0); }

    validateJob = require("child_process").spawn(
        "npm",
        [
            "run",
            "val",
            "--",
            "--workspace",
            "src",
            "--diagnostic-sources",
            "\"js,svelte,css\"",
            "--ignore",
            files.join(',')
        ],
        {
            stdio: ["ignore", "inherit", "inherit"],
            shell: true,
            cwd: require('path').resolve(__dirname, '..'),
        }
    );
});

```
And just run:
```bash
node ./validate.js
```

**Comment by dummdidumm** [comment]
If I create a folder `__stories__` and run the command you mention "Describe the solution you'd like" the file inside `__stories__` is filtered out for me.

**Comment by visma-sorinbroscaru** [comment]
Oh, I am actually surprised that it works. I initially tried ```svelte-check --ignore "__stories_,__tests__" --workspace src``` , and assumed it's not possible to use wildcards as the docs/readme.md states for the ignore option only the following: 
```Files/folders to ignore - relative to workspace root, comma-separated, inside quotes. Example: --ignore "dist,build"```

So, naturally, I assumed wildcards like **/ does not work.
I will close this.
