### ISSUE TITLE
Support autocompleted or aliased imports

### ISSUE THREAD

**Issue by jwrunner** [sveltejs/language-tools#105]
**Is your feature request related to a problem? Please describe.**
When adding or refactoring routed .svelte files in Sapper, it is quite tedious to use the correct import path for components. Is it "../components/View.svelte" or "../../components/View.svelte", etc...

**Describe the solution you'd like**
Auto component import: when I start typing `<View` into a .svelte file, I would like a tooltip offering to import matching component(s).
Additionally, when refactoring, I would like the editor to ask if I would like to update import paths as it does with Angular, for example.

**Describe alternatives you've considered**
An alternative would be to support the use of rollup-plugin-alias as seen in https://github.com/sveltecasts/010-rollup-alias/blob/master/rollup.config.js#L18 so that we can simply type `import View from "@components/View.svelte";` 
_Note that I'm using a simpler implementation of rollup-plugin-alias:_
```js
const aliases = alias({
	resolve: ['.jsx', '.js', '.tsx', '.ts', '.svelte'],
	entries: [
		{ find: '@components', replacement: `${__dirname}/src/components`},
		{ find: '@routes', replacement: `${__dirname}/src/routes`},
	]
})
```

And it would be even more awesome if BOTH could be supported. Thanks for the great work!

**Comment by jasonlyu123** [comment]
Lastest version of svelte beta support component auto import and import completion. But rename files and symbols still need some works. 
The route alias is also supported but you would have to configure it though tsconfig/jsconfig.json
you can check out https://code.visualstudio.com/docs/languages/jsconfig#_using-webpack-aliases for more info

**Comment by jwrunner** [comment]
Great to hear! Thanks. 

> But rename files and symbols still need some works

Should we close this or rename it to hone focus in on that feature?

**Comment by dummdidumm** [comment]
I would prefer to close this one and open one feature request for rename symbols and one for file renames/moves (I think these two are very different things to implement).

**Comment by dummdidumm** [comment]
Closing in favor of #110 and #111
