### ISSUE TITLE
Support VS Code Workspace Trust feature 

### ISSUE THREAD

**Issue by dummdidumm** [sveltejs/language-tools#1051]
The new VS Code version introduced "Workspace Trust". If someone doesn't trust a folder/workspace they have opened, VS Code only provides limited interaction with the code base. This includes extensions: They are turned off completely, if they don't implement some of the Workspace Trust APIs. Extension can provide a description of what subset of functionality should be enabled. More on that and a questionnaire which helps determining what to do here: https://github.com/microsoft/vscode/issues/120251 

I think what we need to do in Workspace Trust is:
- Disable loading the svelte.config.js, it could contain malicious code. If one is present, we should turn off running the diagnostics of the Svelte compiler as we can't know for sure how to preprocess the files.
- Don't load the user's version of prettier/svelte/svelte-preprocess (`importPackage.ts`) and instead use our own version of that
- check the built-in typescript extension of VS Code to see if they turn off something, and turn that off, too . Edit: [They turn of these settings](https://github.com/microsoft/vscode/blob/main/extensions/typescript-language-features/package.json#L16) which don't affect us
- investigate if we can reenable the ls-path and node executable setting to be workspace settings. If the user trusts the workspace, he likely also trusts the workspace settings

**Comment by dummdidumm** [comment]
Support added in #1086 . 
Not removing the the ls server path scope for now to ensure backwards compatibility. Lift that restriction and bump the minimum required VS Code version later.

**Comment by stephtr** [comment]
When are you planning to lift that restriction?

**Comment by acls** [comment]
@dummdidumm Would it be possible to remove the `"scope": "application"` restriction now?

**Comment by dummdidumm** [comment]
`"scope": "application"` is lifted now in favor of workspace trust
