### ISSUE TITLE
Svelte for VS Code 105.x.x is slow

### ISSUE THREAD

**Issue by moisesGarmendia** [sveltejs/language-tools#1055]
Hey guys, awesome plugin, worked fast for me before this upgrade (105.0.0 & 105.1.0)
Video to demonstrate:

https://user-images.githubusercontent.com/78880943/121925376-15872200-ccfa-11eb-8cdb-c53bd9dacf76.mp4

Hope you guys be aware of this, if this is only affecting me, nevermind it, thanks in advance

**Comment by dummdidumm** [comment]
Does this only affect the startup time and after it first works it's fast again or is it slow the whole time? Also I need a reproduction repo to investigate this.

**Comment by moisesGarmendia** [comment]
Hi, thanks for the reply, i thought that this was only at startup, but yesterday i gave 5min to VS code to run all stuff, and this delay continue, I have 4 extensions, (Svelte for VS Code, Tailwindcss Intellisense, Visual Studio Keymap and vscode-icons ), uninstall it all, and test one by one, but Svelte for VS Code was the one struggling, use Ctrl + Shift + P and look for `Show Running` (Development), to see startup time of the extension and took almost 200ms to start (nothing crazy)
![image](https://user-images.githubusercontent.com/78880943/121938779-79651700-cd09-11eb-8862-b999b3ef9016.png)

**Comment by dummdidumm** [comment]
Does this happen in all Svelte projects for you? Do you have any repository to share where the issue occurs? It's very well possible this is something related to your specific project, so if you could try to narrow it down or just point me to a repo that would be great.

**Comment by moigarm** [comment]
Sorry for the late reply, but i could not reproduce it with Svelte kit, at least using TS, in the project shown above, I'm using Routify, but with the template works fine, i'll be closing this issue tomorrow, maybe is something very strange with the settings but, works with version 104 and non 105 and above 😕

**Comment by jasonlyu123** [comment]
Just a wild guess. Can you try if disabling semantic tokens would make a difference? The config for it is  `svelte.plugin.typescript.semanticTokens.enable`

**Comment by moisesGarmendia** [comment]
Improved a bit but is unusable though
![image](https://user-images.githubusercontent.com/78880943/122414868-b0733c80-cf44-11eb-884e-77f8668aa240.png)
Thanks for the tip!
