### ISSUE TITLE
Unresolve custom property in window

### ISSUE THREAD

**Issue by vgpechenkin** [sveltejs/language-tools#1060]
**Describe the bug**
Plugin VS Code doesn't unresolve custom properties/methods in window

**To Reproduce**
I declare a custom property in global.d.ts
```
declare global {
    interface Window {
        prop: string;
    }
}

```
and I use it in svelte files

`let test: string = window.prop;`

I have an error:
`Property 'prop' does not exist on type 'Window & typeof globalThis'.`

**Screenshots**
![image](https://user-images.githubusercontent.com/1455274/122631748-86518400-d0d6-11eb-8976-b3d19ba36da2.png)

**System (please complete the following information):**
 - OS: Windows
 - IDE: VSCode
 - Plugin/Package: "Svelte for VSCode"

**Comment by jasonlyu123** [comment]
Removes declare global works for me:

```ts
interface Window {
    prop: string
}
```

I'm going to remove the bug label as this is more of a typescript declaration/config problem. And the declaration also doesn't work in typescript files.
