### ISSUE TITLE
[svelte-check] `--ignore` flag gets overwritten by `--tsconfig`

### ISSUE THREAD

**Issue by macmillen** [sveltejs/language-tools#1074]
**Describe the bug**
When i use both `--ignore` and `--tsconfig` flags in the `svelte-check` cli, the `--ignore` flag doesn't do anything anymore. It only works when I omit the `--tsconfig` flag.

**To Reproduce**
``` bash
yarn svelte-check --ignore "src" --tsconfig ./tsconfig.json
```

**Expected behavior**
If that's expected throw a warning or something to make the user aware. Otherwise it should work with both flags.

**Comment by dummdidumm** [comment]
It's expected, the tsconfig exclude setting should be used in that case. Throwing makes sense.

**Comment by dummdidumm** [comment]
In svelte-check, setting both will be an error
