### ISSUE TITLE
No way to define required properties (typescript)

### ISSUE THREAD

**Issue by xaviergonz** [sveltejs/language-tools#1076]
**Describe the bug**
There's no way currently to define a property as required in typescript.

**Logs**
N/A

**To Reproduce**

Test.svelte
```
<script lang="ts">
  export let reqName: string;
  export let optName: string | undefined;
</script>

<h1>Hello {reqName} {optName || "Doe"}!</h1>
```

App.svelte
```ts
<script lang="ts">
  import Test from "./Test.svelte";
</script>

<main>
  <Test /> <!-- this should complain that reqName is missing -->
</main>
```

**Expected behavior**
The compiler should complain that <Test> is missing "reqName", since `undefined` is not a valid value for the exported property.

**Stacktraces**
N/A

**Information about your Svelte project:**
Window 10, latest svelte, rollup

**Severity**
I think not being able to separate required properties from optional ones impacts the ability to do safe refactors. Also, since this would be a breaking change and the official TS support just got released I think it is better to tackle this soon rather than later (or else hide the breaking behaviour under a flag).

**Comment by dummdidumm** [comment]
With the latest version of the Svelte for VS Code extension and `svelte-check` props are marked as required if not initialized. For generics see #442

**Comment by Lootwig** [comment]
Is this IDE specific? typescript strict mode is turned on for me, but I do not get any warnings/errors regarding required props inside IntelliJ or in `npm run dev`'s output.

**Comment by gianmarco27** [comment]
Same for me

**Comment by dummdidumm** [comment]
The intellij plugin is independent of this and maintained by someone else. `npm run dev` won't show any errors, use the `svelte-check` npm package for this
