### ISSUE TITLE
On any event passthrough (on:*) shows syntax error

### ISSUE THREAD

**Issue by danbulant** [sveltejs/language-tools#1096]
**Describe the bug**
Svelte has undocumented (which is weird, given I saw it used in few bigger projects, like svelte MUI) feature that allows all events from a single element to be passed through, by writing `on:*`.

**To Reproduce**
Simply trying to use it will result in syntax error.
```svelte
<input type="text" on:*>
```
Should pass all it's events to the parent component (and does that in browser svelte. Svelte SSR simply ignores it).

**Expected behavior**
It should be treated as valid syntax, although auto completion of events would suffer. Best case would result in the parser infering the events it can pass.

**Screenshots**
![image](https://user-images.githubusercontent.com/30036876/125613232-280e85e1-06ca-4cd0-a3be-1eb8660876a7.png)

**System:**
 - OS: Manjaro (linux)
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode

**Comment by dummdidumm** [comment]
This is not an undocumented feature, this is a feature that is requested but not implemented yet. See https://github.com/sveltejs/svelte/issues/2837 fore more.

**Comment by danbulant** [comment]
I'm using latest npm version of svelte and it works there. And smelte is
using it a lot in their components (even those half a year old). Maybe they
did add it based on the issue, but didn't talk about it?

>

**Comment by dummdidumm** [comment]
I see it in their code, but it most likely is related to some preprocessor. It definitely isn't implemented in Svelte core, just try it out yourself in the REPL, you will see it won't bubble events.

**Comment by danbulant** [comment]
Yup, you're right. It doesn't work, but also doesn't show any errors.
What's weird is I don't see any preprocessor in their codebase, and it does
work for me locally without using preprocessors (using routify ts
template), so that's why I raised the issue.

>

**Comment by dummdidumm** [comment]
That's strange indeed ... maybe ask on their end how they achieve that? Having more context who uses this in what circumstances will help my understanding of this issue and possibly try to find a solution to this.
