### ISSUE TITLE
Unexpected error: Declaration or statement expected

### ISSUE THREAD

**Issue by ebeloded** [sveltejs/language-tools#1097]
**Describe the bug**
Svelte-check reports an error for the following code:
```ts
<script lang="ts">
import { readable } from 'svelte/store'
const uid = readable('')
const getWorkspaces = (uid: string) => readable([uid])

$: workspaces = getWorkspaces($uid)// Error: "Declaration or statement expected"

$: console.log({ workspaces: $workspaces })
</script>

```

This is a regression introduced in svelte-check 2.2 as it doesn't appear with svelte-check 2.1.
Adding a semicolon at the end of the line hides the issue:

```ts
$: workspaces = getWorkspaces($uid); // with semicolon error goes away
```

**Screenshots**
![image](https://user-images.githubusercontent.com/5859177/125710905-24c0bab5-620e-4efa-bcf1-122b9b1e46f4.png)

**System (please complete the following information):**
 - OS: [Mac OS]
 - IDE: [VSCode]
 - Plugin/Package: ["Svelte for VSCode", `svelte-check`]

**Comment by dummdidumm** [comment]
As a workaround you can add a semicolon at the end (`;`)
