### ISSUE TITLE
Support rename in Svelte files

### ISSUE THREAD

**Issue by dummdidumm** [sveltejs/language-tools#110]
**Is your feature request related to a problem? Please describe.**
Currently, I cannot do rename refactorings in svelte files.

**Describe the solution you'd like**
Allow rename refactorings inside svelte files to work so that
- I can change prop names and all dependent files get updated
- I can change variables/functions inside svelte files
- I can change variables/functions outside in js/ts files and if they are used inside svelte files, those are updated aswell

**Additional context**
I started prototyping this. Renames of variables/functions inside svelte files can be implemented quickly. 

However implementing prop renames requires changes to `svelte2tsx`. It seems that right now there is no mapping from `export let X` to the generated jsx-prop. 

Another problem is that when you do a rename inside ts/js, the language server does not pick that up because he is only registered to react to changes of svelte files. To fix that, it would need to register for js/ts files, too, which requires some work to differ between svelte and ts/js documents and not for example run diagnostics of the `HTMLPlugin` on js/ts files. Maybe this could come as a second step, after renaming inside svelte files works.

**Comment by dummdidumm** [comment]
Rename so far now works for:
- Variables inside a svelte file's script tag
- Component props, but they can only be renamed inside the component which exports the prop

It does not yet work for:
- Component props if you want to rename the prop but are in another file which uses that component
- Generally attributes/bindings inside the template cannot be renamed when you want to trigger the rename in said template. Works inside script tag though.

**Comment by imekachi** [comment]
There is another scenario, where a svelte file imports a variable from another file (.js, .ts)
and you rename that variable in other file, it doesn't update variable imported in .svelte

I think it has something to do with referencing variables, because it cannot find reference from .svelte file as well
![image](https://user-images.githubusercontent.com/5445243/115429944-1c2f7680-a22e-11eb-9677-a303e8ab98a9.png)

**Comment by dummdidumm** [comment]
To support this we need to write a TypeScript plugin, which is tracked in #580

**Comment by dummdidumm** [comment]
There exists a TypeScript plugin now which comes packaged with the VS Code extension and which you need to enable [through the settings](https://github.com/sveltejs/language-tools/tree/master/packages/svelte-vscode#svelteenable-ts-plugin). It also is [available standalone as a npm package](https://www.npmjs.com/package/typescript-svelte-plugin) if you need to use it outside of VS Code.
The plugin fixes the issue of renaming stuff inside TS/JS files and updating Svelte files, too.

**Comment by imekachi** [comment]
I can confirm that every works now (in VS Code with the plugin)
- renaming from other file types
- finding references from other file types

Thank you @dummdidumm
