### ISSUE TITLE
Support rename/move of Svelte files

### ISSUE THREAD

**Issue by dummdidumm** [sveltejs/language-tools#111]
**Is your feature request related to a problem? Please describe.**
Right now renaming/moving svelte files does not update the imports in other svelte files.

**Describe the solution you'd like**
Renaming/moving svelte files should update the imports in other svelte files.

**Additional context**
I dug around the language server protocol a little but found no event that says "file X moved from A to B" or "file X was renamed to Y". Instead, `onDidCloseTextDocument` and `onDidOpenTextDocument` events fire, and also the `onCodeAction` event is invoked with the new file path and a range with start/end of 0. One could infer a file rename/move from these events, if they appear shortly after each other, but I'm not sure if this is a hack or the only possible solution. If someone knows more about this, please comment.

**Comment by jasonlyu123** [comment]
I found vscode's typescript features is using workspace API which doesn't seem to be accessible in the language server. So we can't just copy their solution. And with the structure of this repo, it will be quite difficult to done it on the client.

There is some issue in [language-server-protocol](https://github.com/microsoft/language-server-protocol) about proposals of rename file. I think we could have some workaround and update later to fit the protocol.

There are two additional solutions:
1. Sent a custom request or command to pipe the workspace event to the language server. [Dart Code](https://github.com/Dart-Code/Dart-Code/commit/48104dd5770e46ca1a6baad55fdbfd4fdeaad0b3) seems to use this solution.
2. use onWatchFileChanges to detect rename. file rename would trigger a create and remove change in the same request. But I can't make it watch directory.

**Comment by dummdidumm** [comment]
Thanks for finding those things out!

I tried out the `workspace.onDidRenameFiles` event a little and it seems that would fit our needs. As you said, we could translate that event into a command that is sent to the language server and handle the rest there. Inside `TypescriptPlugin` we then should be able to let the ts language service handle this by calling `getEditsForFileRename`.
