### ISSUE TITLE
Launch server through bash

### ISSUE THREAD

**Issue by maxime-pigeon** [sveltejs/language-tools#1111]
**Is your feature request related to a problem? Please describe.**
I might have missed this, but there seems to be no way to launch the server through bash once the language server is installed globally.

**Describe the solution you'd like**
Bash command to launch server.

**Additional context**
I'm using BBedit, which looks in my `$PATH` and needs a command to start the language server

**Comment by jasonlyu123** [comment]
You can try the `svelteserver` command with the `--stdio` flag

**Comment by maxime-pigeon** [comment]
Thanks, that worked.
