### ISSUE TITLE
Improved validation of empty or malformed `svelte.config.js`

### ISSUE THREAD

**Issue by benmccann** [sveltejs/language-tools#1115]
**Is your feature request related to a problem? Please describe.**

SvelteKit had an empty `svelte.config.js` in one of its test projects. It gave the error message:

```
│ Error while loading config
│ TypeError: Cannot read property 'compilerOptions' of undefined
```

**Describe the solution you'd like**

It'd be nice if it checked if the `config` existed before trying to read `compilerOptions` off it:

https://github.com/sveltejs/language-tools/blob/7abeef43e997d1187e239f6d1d99253332b7f5bf/packages/language-server/src/lib/documents/configLoader.ts#L159

It'd also be nice if it printed the path to the `svelte.config.js` in the error. SvelteKit had tons of them in various test projects, so it took a little while to track down

**Additional context**
See https://github.com/sveltejs/kit/issues/1988

**Comment by dummdidumm** [comment]
The error message should be better now.
