### ISSUE TITLE
linting of scss and compilation times

### ISSUE THREAD

**Issue by basaran** [sveltejs/language-tools#1117]
Thank you for the great package. I recently started using svelte and everything has been working smoothly so far on my Sublimetext setup. Actually, it's working too well and it's almost giving me a problem.

I have this large SCSS import from svelte-carbon-components inside `__layout.svelte`:

```
<style lang="scss" global>
    @import "carbon-components/scss/globals/scss/_theme.scss";

    $carbon--theme: map-merge(
        $carbon--theme--g10,
        (
            interactive-01: green,
        )
    );
    @include carbon--theme();

    $feature-flags: (
        ui-shell: true,
        grid-columns-16: true,
    );
    $css--font-face: true;
    $css--plex: true;

    @import "carbon-components/scss/globals/scss/css--font-face";
    @import "carbon-components/scss/globals/grid/grid";
    @import "carbon-components/scss/globals/scss/styles.scss";
</style>
```

The issue is, as soon I open any svelte file, not necessarily the `__layout.svelte`, the LSP node process cpu utilization spikes up. I'm suspecting it's compiling it internally, and during this time other functions of the LSP times out (i.e code formatting).

Would there be a way to make LSP-svelte ignore compilation of certain imports? I tried .eslintignore but probably didn't do it right. Thank you.

**Comment by jasonlyu123** [comment]
Currently, we run the svelte compiler to show the diagnostic. For the compiler to understand scss, The preprocess is also needed. Unless you can found a way to have a different preprocess config in the editor environment, I don't think there's a way to skip compilation without disabling the svelte diagnostic feature. 

The scss compilation of `carbon-components` took a long time, I tried it before. Personally, I would suggest you move the scss to a separate file, have a separate compilation step, and import the compiled CSS. It might also save you some time starting the dev server.

**Comment by basaran** [comment]
Thank you very much for your insights, moving the scss to a separate file and recompiling it was I had done too. But you know situations like this,  `is there a better way` keeps bugging you deep inside long after, so I figured I should ask)

Do you think the compilation could be disabled with `.eslintignore`  if I don't use the LSP-svelte but use LSP-eslint with svelte plugins along with prettier?

**Comment by jasonlyu123** [comment]
The linting error is presented in both eslint and svelte-lanugauge-server. You'll have to disable both. But svelte-language-server doesn't support disabling diagnosis on specific files.

If you have eslint setup you can disable the svelte diagnostics from the language server with the `svelte.plugin.svelte.diagnostics.enable` config and rely on eslint for the same diagnostics. Then you disable eslint for a specific file to resolve the problem.

**Comment by basaran** [comment]
Thank you, I think there is enough information in the issue report if anybody else encounters the same problem in the future. Closing.
