### ISSUE TITLE
Disable formatting line

### ISSUE THREAD

**Issue by OJFord** [sveltejs/language-tools#1122]
**Is your feature request related to a problem? Please describe.**
```js
let foo = dedent`
  whitespace is significant and yes this is a long ${interpolated} line but I'd really like it not to be broken
  
  something
  
  else
`;
```

From what I've seen I think it preserves significant whitespace, but it ends up breaking the point of using something like `dedent`, becoming e.g.:
```js
let foo = dedent`
  whitespace is significant and yes this is a long ${
  interpolated
} line but I'd really like it not to be broken
  
  something
  
  else
`;
```

**Describe the solution you'd like**
Something like `// no-format` or whatever to indicate it shouldn't be changed.

**Describe alternatives you've considered**
Breaking it up into multiple short enough variables that it can be composed together...

**Additional context**

**Comment by jasonlyu123** [comment]
You can try using `// prettier-ignore`

**Comment by OJFord** [comment]
Thanks, that does sort it. I didn't know prettier was used under the hood, so I didn't know to look at those docs for an ignore/disable comment-statement.

(I see it _is_ mentioned https://github.com/sveltejs/language-tools/tree/master/packages/language-server, I just missed it. Wasn't expecting/looking for it I suppose, just looking for a list of comments like `// svelte: whatever` so when I didn't see them thought it wasn't supported.)

Thanks!
