### ISSUE TITLE
emitDts fails for interfaces and classes defined in script tag

### ISSUE THREAD

**Issue by bluwy** [sveltejs/language-tools#1126]
**Describe the bug**
If an interface or class is defined in the script tag, and is indirectly exported, e.g. `export let foo: BarInterface`, emitDts fails silently and outputs no respective file.

This is because the generated `dts` mode tsx by `svelte2tsx` is something like this:

```tsx
import { SvelteComponentTyped } from "svelte"

function render() {

  interface Hello {
    world: string
  }

   let foo: Hello
;
return { props: {foo: foo} as {foo: Hello}, slots: {}, getters: {}, events: {} }}
const __propDef = __sveltets_1_with_any_event(render());
export type InputProps = typeof __propDef.props;
export type InputEvents = typeof __propDef.events;
export type InputSlots = typeof __propDef.slots;

export default class Input extends SvelteComponentTyped<InputProps, InputEvents, InputSlots> {
}
```

Note the interface is in the `render()` function. Typescript will throw an error (e.g. `Return type of exported function has or is using private name 'Hello'.`) as the interface is scoped but it's being exported. See [example typescript playground](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABACwKYBt1wBQEpEDeAUIojGFKgE7ACGEqiAEhloSaYgO5xXoAmALkQBnKFXIBzDgF8iHCOloiRiAGJw4hOR3SooiWsJaYtAXkLdeA4QHJatW4jmk9BgEaILYVF3Wa8eVIqfRAqJAJEAAcqOCiRYUjaABpETxlnIhkgA) showing the error.

However, if you're using normal `type`s, e.g. `type Foo = {}`, it'll work. [Example typescript playground](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABACwKYBt1wBQEpEDeAUIolAJ4AOqiAEhlogLyGIDucATugCYBciAM5ROMMAHNEAXyIlE6VFEQBDAfUxxmrDt36IA5MuX7ps0p0UhOSAokqc4lQQNvLppqUA).

It's also important to note that this happens in `declaration: true` for tsconfig only.

**To Reproduce**

Clone https://github.com/bluwy/emit-dts-interface-repro, and follow steps in readme

**Expected behavior**
Generate types for Svelte components that have interfaces or classes in the script tag. Or specifically, `svelte2tsx` should extract these types out of the `render()` function for the dts-mode tsx output.

**Screenshots**
n/a

**System (please complete the following information):**
 - OS: Ubuntu 21.04
 - IDE: VSCode
 - Plugin/Package: svelte2tsx

**Additional context**
It doesn't seem easy to extract the types. Maybe a different dts mode output is needed?

**Comment by jasonlyu123** [comment]
Yes. it's not easy to extract the types. We'll have to check if the type is referencing any local variable or type. So I don't know if that's something we want to do. I personally more prefer to just throw an error and suggesting moving the interface to the `context="module"` or a separate file.

**Comment by bluwy** [comment]
I'm fine if we can report the error in the meantime so it's clearer to the end-user. Though in the long term, I hope we can not have to worry about this caveat.

**Comment by dummdidumm** [comment]
Mhm this is bad. The proposed enhanced typings for props/events/slots relies on interfaces (`$$Props` / `$$Slots` / `$$Events` ) to be defined within the instance script.
A possible solution would be to traverse the top level TS AST of the instance script only and check for interfaces, and move them out of the render function, but only if there's no interface with the same name in the module script.

**Comment by dummdidumm** [comment]
Tinkered with it a little, and moving the interfaces might not be suitable for all situations. TS allows us to do all kinds of weird shit, like
```typescript
const A = 'asd';
interface B { [A]: boolean }
```
which would break when moving the interface out of the function.
In case of `$$Props` etc we additionally have to check if `type T = $$Generics` declarations are referenced and transform the interface accordingly.

Maybe it's better to transform interface declarations into type declarations.

**Comment by dummdidumm** [comment]
This should work for interfaces now. I didn't add a transformation for classes, but that's "works as designed" for now, so I'm closing this.
