### ISSUE TITLE
'HTMLElement' is not defined

### ISSUE THREAD

**Issue by techniq** [sveltejs/language-tools#1135]
**Describe the bug**
In a fresh SvelteKit project, I get a warning on the terminal as well as within `VSCode` indicating 'HTMLElement' is not defined.  The default `tsconfig.json` has `"lib": ["es2020", "DOM"]` defined so I'm not sure where else [HTMLElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement) should be defined since it's a global on `window`.

<img width="751" alt="CleanShot 2021-08-12 at 09 17 24@2x" src="https://user-images.githubusercontent.com/177476/129203528-754a1eca-200a-4273-b757-7236b1e999ed.png">

What's even more interesting is on an older SvelteKit templated project, I still receive this warning, but the intellisense has details about `HTMLElement`

<img width="970" alt="CleanShot 2021-08-12 at 08 55 31@2x" src="https://user-images.githubusercontent.com/177476/129201314-c5fb7793-512a-44f6-ae86-0a2796cc515b.png">

**Additional context**
`devDependencies` in `package.json` 
```json
	"devDependencies": {
		"@sveltejs/kit": "next",
		"prettier": "~2.2.1",
		"prettier-plugin-svelte": "^2.2.0",
		"svelte": "^3.34.0",
		"svelte-check": "^2.0.0",
		"svelte-preprocess": "^4.0.0",
		"tslib": "^2.0.0",
		"typescript": "^4.0.0"
	},
```

`tsconfig.json`
```js
{
	"compilerOptions": {
		"moduleResolution": "node",
		"module": "es2020",
		"lib": ["es2020", "DOM"],
		"target": "es2019",
		/**
			svelte-preprocess cannot figure out whether you have a value or a type, so tell TypeScript
			to enforce using \`import type\` instead of \`import\` for Types.
			*/
		"importsNotUsedAsValues": "error",
		"isolatedModules": true,
		"resolveJsonModule": true,
		/**
			To have warnings/errors of the Svelte compiler at the correct position,
			enable source maps by default.
			*/
		"sourceMap": true,
		"esModuleInterop": true,
		"skipLibCheck": true,
		"forceConsistentCasingInFileNames": true,
		"baseUrl": ".",
		"allowJs": true,
		"checkJs": true,
		"paths": {
			"$lib": ["src/lib"],
			"$lib/*": ["src/lib/*"]
		}
	},
	"include": ["src/**/*.d.ts", "src/**/*.js", "src/**/*.ts", "src/**/*.svelte"]
}
```

**Comment by techniq** [comment]
After a little more research, it appears the warning only shows when in the markup (i.e. not in `<script>`).

<img width="459" alt="CleanShot 2021-08-12 at 15 52 43@2x" src="https://user-images.githubusercontent.com/177476/129260620-56cd3de5-c08a-4df8-839c-9fdb5c8ed660.png">

**Comment by jasonlyu123** [comment]
This is a svelte compiler issue, not a typescript issue. The same warning is also present in the repl.

**Comment by techniq** [comment]
@jasonlyu123 thanks, I had not realized that.  I'll search the svelte issues / open one over there.

<img width="729" alt="CleanShot 2021-08-13 at 07 14 04@2x" src="https://user-images.githubusercontent.com/177476/129349197-cfe6cd03-3f95-4bf9-b515-f1680005f1db.png">

**Comment by techniq** [comment]
I couldn't an existing issue, so I opened https://github.com/sveltejs/svelte/issues/6643.  Linking here in case someone follows my same path.
