### ISSUE TITLE
svelte-vscode: Support the auto-subscription syntax in .ts files

### ISSUE THREAD

**Issue by ngryman** [sveltejs/language-tools#1137]
**Is your feature request related to a problem? Please describe.**

The auto-subscription compiles fine for `.ts` files. However, VSCode complains that the variable doesn't exist.

The following code:

```ts
export const foo = writable('foo');

export function setFoo(value: string) {
  $foo = value;
}
```

results in the following error in VSCode:

```
Cannot find name '$foo'. Did you mean 'foo'?
ts(2552)
```

I assume this is because the language that VScode detects for `.ts` files is vanilla "Typescript". Switching to the "Svelte" language, that `svelte-vscode` brings, is not an option as it expects the Typescript code to be wrapped by a `<script>` tag.

**Describe the solution you'd like**

It would be great to support Svelte syntaxes in `.ts` files, so code ergonomics is on par with `.svelte` files.

VScode comes with a "Typescript React" language to support JSX. `svelte-code` could have the same approach to support Svelte-specific syntaxes such as auto-subscriptions in `.ts` files. It could come with a new "Typescript Svelte" language for example.

**Describe alternatives you've considered**

Alternatively, we can use the `store#set|update|subscribe` and `get` functions. But as mentioned above, it offers a different experience than in `.svelte` files.

**Additional context**

My settings:
* Extension version: `v105.3.4`
* Settings: `"svelte.enable-ts-plugin": true`

**Comment by Mlocik97** [comment]
you can use derivation for this? I don't understand why would someone want to do it this way.

**Comment by dummdidumm** [comment]
The auto subscription functionality can only be used within Svelte files.
