### ISSUE TITLE
Svelte for VS Code extension crushes react project

### ISSUE THREAD

**Issue by florianGierlichs** [sveltejs/language-tools#1149]
**Describe the bug**
After installing the Svelte for VS Code extension in my editor to work on a svelte project, a different project written in react and typescript completely crushes and throws ts error all over the place:
```
Type '() => svelte.JSX.Element' is not assignable to type 'FC<{}>'.
  Type 'Element' is not assignable to type 'ReactElement<any, any> | null'.
    Type 'Element' is missing the following properties from type 'ReactElement<any, any>': type, props, key
```

literally every .tsx file throw errors, the project worked flawlessly before installing the svelte extension.

The only way I found so far, is to disable the extension every time I'm not working on a svelte project, which sucks, you know.

**To Reproduce**

Open a react-ts project with the svelte extension in VSCode i guess.

**Expected behavior**
svelte extension doesn't influence non-svelte projects

**Screenshots**
![image](https://user-images.githubusercontent.com/58342773/131106390-e059e208-8646-4d2b-9861-abd21876e7be.png)

![image](https://user-images.githubusercontent.com/58342773/131106439-7d8640da-c9f9-42a5-af83-505559508a3f.png)

**System (please complete the following information):**
 - OS: MAC OS
 - IDE: VSCode
 - Plugin/Package: "Svelte for VSCode"

**Comment by maykefreitas** [comment]
I'm having the same problem in a monorepo containing svelte and react projects.

**Comment by maykefreitas** [comment]
It backs to work if I disable the Svelte extension. Looks that somehow the extension is injecting the `svelte-jsx.d.ts` file.

**Comment by dummdidumm** [comment]
Could you check if the problem persists with the latest release of the Svelte extension (105.4.2) ?

**Comment by jasonlyu123** [comment]
Wondering if the tsserver reuses the same language service for both the react project and the svelte project. Can you try if adding a `jsconfig.json` to the svelte project root solved the problem?

Here's an example `jsconfig`:

```json
{
    "include": ["src/**/*.d.ts", "src/**/*.js", "src/**/*.svelte"]
}

```

**Comment by dummdidumm** [comment]
The most recent versions of the extension and `svelte-check` contain a new transformation behind a flag which should fix this issue. You can try out the new transformation using

- "Svelte for VS Code" version 105.11.1 and setting svelte.plugin.svelte.useNewTransformation to true
- svelte-check version 2.4.0 with the --use-new-transformation flag.

Please try it out, more info in #1352
