### ISSUE TITLE
Language server in VS Code extension crashes on initialisation

### ISSUE THREAD

**Issue by smlsvnssn** [sveltejs/language-tools#1150]
**Describe the bug**
Language server crashes with the following error:
```
[Info  - 6:28:23 PM] Connection to server got closed. Server will restart.
(node:21630) ExperimentalWarning: The ESM module loader is experimental.
internal/modules/cjs/loader.js:461
  const e = new Error(`Package exports for '${basePath}' do not define a ` +
            ^

Error: Package exports for '/Users/samuel/.vscode/extensions/svelte.svelte-vscode-105.3.5/node_modules/svelte' do not define a valid './compiler' target
    at resolveExportsTarget (internal/modules/cjs/loader.js:461:13)
    at resolveExports (internal/modules/cjs/loader.js:394:16)
    at Function.Module._findPath (internal/modules/cjs/loader.js:493:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:27)
    at Module._load (internal/modules/cjs/loader.js:737:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:899:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/samuel/.vscode/extensions/svelte.svelte-vscode-105.3.5/node_modules/svelte2tsx/index.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:1014:30) {
  code: 'MODULE_NOT_FOUND'
}
[Error - 6:28:24 PM] Connection to server got closed. Server will not be restarted.

```
**To Reproduce**
For me, just opening a svelte file in vs code. I have uninstalled other extensions, tried to update node packages, and whatnot.

**Expected behavior**
Working emmet and code completion.

**System (please complete the following information):**
 - OS: os x big sur
 - IDE: vs code
 - Plugin/Package: Svelte for VSCode

**Comment by dummdidumm** [comment]
Did you change any extension settings, for example defined a path to the node runtime? Which extension version do you have installed?

**Comment by smlsvnssn** [comment]
Not that I'm aware of... I run v105.3.5.

**Comment by dummdidumm** [comment]
Which version of VS Code do you have installed?
For me the error sounds like the extension is running on an older/buggy Node version which does not fully support ESM and then crashes at an import.

**Comment by smlsvnssn** [comment]
I run vs code v1.52.1, and Node.js v14.15.4. I'll try updating node and see what happens.

**Comment by dummdidumm** [comment]
If you didn't adjust settings, the language server will be started with the version that VS Code provides, which is Node 12.x I believe (you can check through Help->About). The VS Code version is outdated (from last November), are you able to update to the latest and check if that solves the issue?

**Comment by smlsvnssn** [comment]
Seems I had some strange auto-updating issue with vs code, hence the old version. I have updated now, but the svelte plugin doesn't run. When I open a .svelte file, nothing happens. No errors in the output, and the runtime status for the extension looks like this: 
![image](https://user-images.githubusercontent.com/3297282/131323729-e281b960-0bd2-4f19-94aa-7f80d8d376d1.png)

**Comment by smlsvnssn** [comment]
Deleted the extension source files, reinstalled, and it seems to be working now. Thanks for the help, much appreciated!

**Comment by dummdidumm** [comment]
👍
