### ISSUE TITLE
Allow multiple event handler (on: directive)

### ISSUE THREAD

**Issue by jasonlyu123** [sveltejs/language-tools#118]
**Describe the bug**
Not exactly a bug but an unexpected typescript error. Two `on:` directive could serve different purposes, they are not redundant. For example, one could have no value and used to forward events, while the other is used to mutate component state. Or yet another with a modifier like `once`.
This could be transformed differently to make ts happy or just filter out the error.

**To Reproduce**
```svelte
<script lang="typescript">
  let changeHandler = () => {}
</script>

<input on:change on:change={changeHandler}>
```

**Expected behavior**
No errors

**Screenshots**
![圖片](https://user-images.githubusercontent.com/36730922/82966413-59c75780-9ffd-11ea-8d07-6f267d5d3e7c.png)

**System (please complete the following information):**
 - Plugin/Package: 
"Svelte Beta", `svelte2tsx`

**Comment by dummdidumm** [comment]
Mhm I think we need to swallow the error somehow.

**Comment by jasonlyu123** [comment]
Kind of related to this. When `strictNullChecks` is enabled, `on:` directive with no value would have another typescript error.
![圖片](https://user-images.githubusercontent.com/36730922/83086715-1da9fa80-a0c2-11ea-9730-1282e160d409.png)
