### ISSUE TITLE
Usinc VSCode I cannot see hints in IDE like I see them in console

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/language-tools#1180]
I'm using VSCode and `Svelte for VS Code@v105.4.0` for a new `SvelteKit@1.0.0-next.169` but I cannot see hints in IDE like when I launch `svelte-check --tsconfig ./tsconfig.json` in console.

Why?

**Comment by dummdidumm** [comment]
Please be more specific. What hints?

**Comment by frederikhors** [comment]
> Please be more specific. What hints?

Sorry. Something like: `Parameter implicitly has an 'any' type, but a better type may be inferred from usage.`.

**Comment by frederikhors** [comment]
I read that answer. Can we enable it in some way today?

**Comment by frederikhors** [comment]
Is very annoying to found out that hints on `prebuild` or `prepublish` script.

**Comment by dummdidumm** [comment]
"Something like" -> please post a code snippet that reproduces this for you.

If that code snippet has a white/gray squiggly below it in your IDE -> that's the hint. And as the answer in the link says, there's no way to enable that in VS Code.

**Comment by frederikhors** [comment]
> there's no way to enable that in VS Code

Thanks.
