### ISSUE TITLE
TS-Plugin: problems with properly recongnizing types

### ISSUE THREAD

**Issue by Chaostheorie** [sveltejs/language-tools#1181]
I have  a problem with the typescript part of the svelte extension. It's not properly recognizing types in an `instanceof` statement even though the code not only compiles but is also valid AFAIK. See below for an MRE.

## MRE

```svelte
<script lang="ts">
	export type FieldLocation = [number, number, number];
        export type Coordinate = [number, number];

	export let coordinates: Coordinate;
	export let id: FieldLocation | number;
	$: idLabel = () => {
                // in both statements below:
                // 'FieldLocation' only refers to a type, but is being used as a value here.ts (2693)
		if (id instanceof FieldLocation) {
			return id.join('-');
                // 'number' only refers to a type, but is being used as a value here.ts (2693)
		} else if (id instanceof number) {
			return id.toString();
		}
	};
	export let label: string = 'node';
	export let fill = 'transparent';
	export let stroke = 'transparent';
	export let strokeWidth = 5;
	export let r = 0;

	let className = '';
	export { className as class };
</script>

{#if id}
	<circle
		cx={coordinates[0]}
		class={className}
		cy={coordinates[1]}
		{r}
		{fill}
		{stroke}
		id={`${label}-${idLabel}`}
		data-id={idLabel}
		style="stroke-width: {strokeWidth};"
	/>
{:else}
	<circle
		cx={coordinates[0]}
		class={className}
		cy={coordinates[1]}
		{r}
		{fill}
		{stroke}
		id={label}
		style="stroke-width: {strokeWidth};"
	/>
{/if}
```

## OS Infos

- VSCodium 1.60.0 / e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff / x64
- Svelte Plugin: v105.4.0 (TS enabled: Yes)
- Host:  Parrot OS 4.11 x86_64

**Comment by dummdidumm** [comment]
Both these errors are correct. `FieldLocation` and `number` are both types, so they don't exist at runtime.

`FieldLocation` needs to be something that exists at runtime, for example a class, and to check if something is a number you do `typeof foo === 'number'`.

**Comment by Chaostheorie** [comment]
@dummdidumm thank you for the help. I didn't know that `instanceof` was handling types this way. Sorry for the unnecessary issue then
