### ISSUE TITLE
Incompatibility with Neovim's built-in LSP on svelte2tsx parser error

### ISSUE THREAD

**Issue by charbelnicolas** [sveltejs/language-tools#1182]
**Describe the bug**

I'm not sure if you will accept this as a bug since I'm not using it with VS code but on Neovim when using the svelte language server with the built-in LSP I get glitchy behavior on imports.

I have reported the bug in neovim's repository [BUG](https://github.com/neovim/neovim/issues/15805) already and it seems that the svelte language server is off-spec since this only happens with svelte files. No issues at all when using typescript and javascript imports though.

**To Reproduce**

Please check the [ISSUE](https://github.com/neovim/neovim/issues/15805) at neovim's repository.

**Expected behavior**

When using imports I shouldn't get any freezes or errors.

**Screenshots**

Please check the [video](https://github.com/neovim/neovim/issues/15805) at neovim's repository.

**System (please complete the following information):**

 - OS: Arch Linux
 - IDE: Neovim 0.6dev (happens on stable release too)
 - Plugin/Package: `svelte-language-server`

**Additional context**

Here is what one of the neovim devs had to say about this issue:

"_The language server is sending a nil value for the line number in its diagnostics. I'll let someone from the LSP team weigh in on this, but I believe this is off-spec behavior and if so the responsibility for fixing it lies with the language server._"

Hopefully someone can find the issue.

**Comment by jasonlyu123** [comment]
There are two problems here. One is there's a runtime error in the transformation. And the diagnostics related to the error having a NaN line number in javascript, thus stringifying as null.

**Comment by charbelnicolas** [comment]
Thanks for the quick fix @jasonlyu123!

I have not been able to test it though since the [NPM PACKAGE](https://www.npmjs.com/package/svelte-language-server) seems outdated and I have no idea what I'm supposed to do to get the same 'svelte-language-server' folder just as the NPM package does.

Am I suppose to run a TS script to compile? (Sorry, I've never used typescript and the whole LSP thing is alien to me too)

**Comment by dummdidumm** [comment]
The "Fixed" label means "we fixed this on master, but it's not released yet". So as soon as this issue gets closed, you'll be able to download the new version from NPM.

**Comment by charbelnicolas** [comment]
Yep, I can understand that... So I've tried building the svelte-language-server with the readme instructions and I don't get any new folders with a build or anything, so I guess I will have to wait until the NPM package gets updated. Thanks.

**Comment by charbelnicolas** [comment]
I managed to hack the svelte-language-server npm package with the updated files, it now works!

How can I get the same build and output as the npm package from this repo? The yarn commands do build the new files but other than that I don't know how to proceed from there.

Any help is appreciated :P
