### ISSUE TITLE
Typescript async false error (condition will always return true)

### ISSUE THREAD

**Issue by CryptoCashCashoo** [sveltejs/language-tools#1188]
**Describe the bug**
Requires Typescript.

Nesting non-overlapping conditions triggers error compilations. For example:
`if(num == 1){
    if(num == 2)
        conosole.log("this doesn't pass the check")
}
`

but this can be potentially false in async environments: if there's an await between the two if conditions, the value could be  modified by an external source.

**To Reproduce**
Minimal:
``` svelte
<script lang="typescript">
    function sleep(ms) {  
        return new Promise((resolve) => setTimeout(resolve, ms));  
    }  

    let value = false;  

    async function check() {
        if (value == false) {
            await sleep(10000);
            if (value == true) console.log("Ups, you pressed the button while I was sleeping.");
        }
    }
    check();

</script>

<button on:click={() => (value = !value)}>PressMe</button>
```

**Workaround**
As a workaround, you could encapsulate the condition that fails in a new function.

**Expected behavior**
Any of this:
1. In async environments don't show this error.
2. In async environments, Decrease the error from error to warning level.
3. Decrease the general error "this condition will always..." from error to warning level.

**System**
 - OS: Linux
 - IDE: VSCode
 - Plugin/Package: `svelte-check`

**Comment by dummdidumm** [comment]
This is an issue with TypeScript's control flow, not related to Svelte. If you copy the contents inside your script tag into a `.ts` file you get the same result.
