### ISSUE TITLE
Use project's svelte compiler for extension, fallback to extension's compiler, if not avaiable

### ISSUE THREAD

**Issue by Mlocik97** [sveltejs/language-tools#1199]
Today, we use extension's compiler, that means, when someone create project, and in package.json they have `"svelte": "^3.38.3", but extension internally use version `^3.41.0`, preview in editor gives different result, than is real compiled code. So there is idea of using project's svelte compiler for creating preview of compiled code, so it's in sync with version that project use, and fallback to version shipped with extension, when project's one is not avaiable.

![Snímka obrazovky z 2021-10-09 23-19-46](https://user-images.githubusercontent.com/34808350/136674051-7969898c-7f88-4a48-9062-10e7d8315b69.png)

In screenshot You can see, preview from extension use v3.42.2 even tho there is installed v 3.40.0 in project.

**Comment by dummdidumm** [comment]
This should already be the case. According to that screenshot, a version higher or equal to 3.40 should get installed. The actually installed version can be seen in your package-lock.json (or pnpm lock file or whatever package manager you use). I expect 3.42.2 to appear there.
