### ISSUE TITLE
Svelte Extension crashing on startup of VSCode (insiders / macOS 11.2 / M1)

### ISSUE THREAD

**Issue by arxpoetica** [sveltejs/language-tools#1204]
NOTE: This bug is similar to https://github.com/sveltejs/language-tools/issues/794, only not on an M1 machine. If you'd prefer to continue on that ticket, can close this one and discuss over there.

**Describe the bug**
Upon starting vscode the error 'The svelte server crashed 5 times in the last 3 minutes..."
Stack trace at bottom.

**To Reproduce**

Happens on starting up VS Code on a Mac with Svelte for VS Code versions 104.9.0+ (doesn't happen on 104.8.0)

**Expected behavior**
No VS Code error.

**Screenshots**
![image](https://user-images.githubusercontent.com/111424/137604943-ce3368e5-e94b-471e-a493-8620a07bb03d.png)

**System (please complete the following information):**
 - OS: macOS 11.2.3 (20D91)
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode v104.9.0+

**Additional context**

Logs:

https://gist.github.com/arxpoetica/2689f3d0a83ba6aad95a647beca23d9a

**Comment by arxpoetica** [comment]
Sure. Just to be clear (maybe I wasn't in the description above) I am **not** on an M1 machine; I'm on Intel. I'll look into what you were talking about.

**Comment by arxpoetica** [comment]
Okay, yeah, super odd. Fixing that file fixed this. Closing.

**Comment by dummdidumm** [comment]
What was that file content when it crashed? A minimum reproducible would be great, as I want to look into this because ideally the language server wouldn't crash here.
