### ISSUE TITLE
Question: how to lint Svelte/Typescript files, or: can svelte-check be used with a preprossor?

### ISSUE THREAD

**Issue by rondonjon** [sveltejs/language-tools#121]
Luckily the VS Code plugin for svelte seems to handle my .svelte files without problems although I am using a [preprocessor](https://github.com/sveltejs/svelte-preprocess) to handle script sections with Typescript.

I am now struggling to set up a CLI task that could do the same kind of linting inside a CI pipeline. Any ideas?

The eslint-plugin-svelte3 is no option because it doesn't yet [support preprocessors](https://github.com/sveltejs/eslint-plugin-svelte3/issues/10).

I thought I might be able to get similar results to VS Code by running `svelte-check` manually, but that didn't work; I guess (if svelte-check is used at all by the plugin?) that the preprocessing is handled outside.

Piping the files through the preprocessor first doesn't seem to work either as `svelte-check` doesn't seem to take input from `stdin`.

What else could I try?

**Comment by rondonjon** [comment]
Sorry, found the solution myself.
I had attributed my `<script>` sections with `lang="ts"` as shown in some tutorials.
After changing the attribution to `type="typescript"`, `svelte-check` processed the files as expected.

**Comment by dummdidumm** [comment]
Glad to hear that 😃 

PS: Guybrush Threepwood!
