### ISSUE TITLE
Go to References - to where the component is used

### ISSUE THREAD

**Issue by lukaszpolowczyk** [sveltejs/language-tools#1210]
**Is your feature request related to a problem? Please describe.**
I have an active tab open with a `*.svelte` component file in VSCode.
I want to jump to all uses of this component.

**Describe the solution you'd like**.
With the tab with the `*.svelte` component file open in VSCode:
* right-click in any empty line of the file
* choose "Go to References" (or the special menuitem "Go to References for this svelte component")
* jumps to each use of this component (of course it bypasses the `import from` sections - it only shows the places of use).

Another option: Menuitem in the context menu of the `*.svelte` file in Expoler and in the context menu of the tab with the `*.svelte` file.

**Describe alternatives you've considered**.
Searching via search engine (Ctrl+Shift+F) and typing component name.
This is less convenient because you have to type it manually, and because it also searches the `import from` section and any other place with the same name as the component, but it should bypass those sections.

**Comment by Jojoshua** [comment]
This is exactly the feature I am needing as well. Anything I can do to help?

**Comment by Blankeos** [comment]
Found: 
🪟 Ctrl (🍏 CMD ) + Shift + P: `Svelte: Find Component References`
