### ISSUE TITLE
"css.completion.completePropertyWithSemicolon"  is not working in svelte file

### ISSUE THREAD

**Issue by easyfrog** [sveltejs/language-tools#1219]
I want prevent auto semicolon in css or styles of svelte file.

I find some configs:

```
 "css.completion.completePropertyWithSemicolon": false,
 "less.completion.completePropertyWithSemicolon": false,
 "scss.completion.completePropertyWithSemicolon": false,
```
But these are all not working with svelte file. the css or styles also has a `auto semicolon` at the end.

<img width="298" alt="image" src="https://user-images.githubusercontent.com/10724325/139192179-c3f177f2-fda1-401b-8f84-0badf5ef2880.png">

and `svelte.plugin.css***` does not has a config with the `semicolon`

**Comment by dummdidumm** [comment]
The VS Code css/less/scss settings are now forwarded to the Svelte extension
