### ISSUE TITLE
Inconsistent warnings between compilation and VSCode using global SCSS

### ISSUE THREAD

**Issue by jtlapp** [sveltejs/language-tools#1225]
**Describe the bug**
Inconsistent warnings between compilation and VSCode. Specifically, the compiler is not complaining about unused CSS selectors when I globally import the bootstrap SCSS, while VSCode is.

This issue is related to #457, but that issue focuses on ignoring such notices, while this issue focuses on consistency between tools.

**To Reproduce**
Install bootstrap and postcss:

```
yarn add bootstrap
yarn add --dev postcss
```

Add the following code (using the appropriate relative path):

```svelte
<style lang="scss" global>
  $primary: rgba(255, 191, 72, 0.938);
  @import '../node_modules/bootstrap/scss/bootstrap';
</style>
```

**Expected behavior**
VSCode and the compiler should emit the same warnings. I honestly don't know whether the compiler should emit warnings here, but I'd rather it didn't (as things stand), because I want to rely on Svelte to prune unused selectors from bootstrap.

**Screenshots**

Warnings:

![Screen Shot 2021-11-02 at 11 50 09](https://user-images.githubusercontent.com/138133/139909680-fb3349df-2929-43ee-9da0-a4e9f20b709e.png)

No warnings:

![Screen Shot 2021-11-02 at 11 51 45](https://user-images.githubusercontent.com/138133/139909888-c5ecb17a-77be-49f1-978f-8cd632e97303.png)

(I'm using Svelte with Electron.)

**System (please complete the following information):**
 - OS: Mac OS 10.15.5
 - IDE: VSCode 1.61.2
 - Plugin/Package: Svelte for VSCode

**Additional context**
Rollup with Electron:

![Screen Shot 2021-11-02 at 11 59 07](https://user-images.githubusercontent.com/138133/139911425-81af5c96-b034-45eb-925c-8e61ffc48f7d.png)

**Comment by jtlapp** [comment]
UPDATE: I just did a fresh installation of the repo on another computer, and no warnings show in VSCode either. So this must be a cache inconsistency somewhere?

**Comment by jasonlyu123** [comment]
It's probably just the language server doesn't detect that you installed postcss. As the global style feature of svelte-preprocess requires postcss to work. It should be working once you restart the editor or [restart the language server](https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/scss-less.md#4-restart-the-svelte-language-server)

The second issue is unrelated, it probably has something to do with how svelte-preprocess process the global selector.

**Comment by jtlapp** [comment]
@jasonlyu123, thank you, you were right. Restarting the editor made the problem go away on the first computer. I'll hit the preprocess folks up for help on the other problem. The compiler emits those warnings too.
