### ISSUE TITLE
Svelte extension broken in VSCode 1.62

### ISSUE THREAD

**Issue by PuruVJ** [sveltejs/language-tools#1230]
**Describe the bug**
VSCode just updated to 1.62 and svelte extension broke. I'm getting errors in every svelte file regarding all the imports. When I close the file and reopen, the errors go away. But when I edit something in the file, all the errors come back.

**To Reproduce**

- Update VSCode to 1.62
- Open a .svelte file with imports

**Expected behavior**

There should be no errors

**Screenshots**
![image](https://user-images.githubusercontent.com/47742487/140479901-cc9267e4-a524-46ac-94dd-8a7a10852b5f.png)

**System (please complete the following information):**
 - OS: Windows
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode official extension

**Comment by PuruVJ** [comment]
NVM, it was a TypeScript issue that came out of nowhere 😅😅

Setting `lib` in tsconfig fixed it

**Comment by PuruVJ** [comment]
Lol it didn't, it's back.

**Comment by PuruVJ** [comment]
Another extension was breaking it. Fixed now 😅

**Comment by dummdidumm** [comment]
Which extension was it?

**Comment by PuruVJ** [comment]
Svelte for VSCode Web by @asafamr 
It was running locally
