### ISSUE TITLE
Type is not assignable to type 'SvelteInputProps' and 'HTMLFormElement

### ISSUE THREAD

**Issue by raghurambachu** [sveltejs/language-tools#1249]
Bug Description
I have defined a custom event called update. Now this I am using it on the ``<form>`` element. 

```
<form {disabled} on:update={({ detail }) => {
		values = detail;
		dispatch('update', values);
	}}
>
</form>
```

I am getting this error on hover of form element

```
Type '{ 
    onsubmit: undefined; 
    class: string;
    disabled: boolean; 
    onupdate: ({ detail }: { detail: any; }) => void; 
}'  is not assignable to type 'HTMLProps<HTMLFormElement>'.
```

To solve this issue I have created a index.d.ts file which contains the below code

```
declare namespace svelte.JSX {
	interface HTMLProps<HTMLFormElement> {
		update?: () => {};
	}
}
```

Now this resolves the above typescript warning that  I was getting. But now this has led to issue on ``<input>`` element elsewhere. 
```
<input
	bind:value={someCode}
        otherprops
/>
```

The error is as below

```
Type '{ 
    value: string; 
    type: string; 
    onfocus: () => boolean;
    onblur: () => boolean; 
    onkeydown: (e: any) => void; 
    onkeyup: () => void;
    onclick: () => void; 
    maxlength: number; 
    style: string; 
    class: string; 
    inputmode: string; 
}'  is not assignable to type 'SvelteInputProps'.
  Property 'value' does not exist on type 'SvelteInputProps'. 
```

I have nowhere modified the  'SvelteInputProps'. I am not able to figure out the issue. 

Things I have tried:
 I felt that in index.d.ts  using  the below code
   ```
declare namespace svelte.JSX {
	interface HTMLProps<HTMLFormElement> {
		update?: () => {};
	}
   }
```

 has replaced/overwritten the original interface HTMLProps<HTMLFormElement> . So I created a new interface which contained the event update and made the original HTMLProps<HTMLFormElement> extend the newly created interface. The code of the newly created interface is below

```
declare namespace svelte.JSX {
	interface UpdatedHTMLFormElement<HTMLFormElement> {
		update?: ({ detail }: { detail: any }) => void;
	}
	interface HTMLProps<HTMLFormElement> extends UpdatedHTMLFormElement<HTMLFormElement> {}
}
```

Even this does'nt work out. Could anyone please help me understand what I am missing. If anything else is required from my side please let me know.

**Comment by dummdidumm** [comment]
Do the instructions in https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/typescript.md#im-using-an-attributeevent-on-a-dom-element-and-it-throws-a-type-error help?

**Comment by dummdidumm** [comment]
@raghurambachu you gave my comment a thumbs up - so did the instructions indeed help and your issue is resolved?

**Comment by raghurambachu** [comment]
Sorry for late reply, yeah above instruction has helped me resolve the issue.
