### ISSUE TITLE
Red underlined script tag when using $$props

### ISSUE THREAD

**Issue by galkatz373** [sveltejs/language-tools#125]
**Describe the bug**
Whenever I use $$props, the opening script tag underlines red and says: "Type annotations can only be used in TypeScript files".

**To Reproduce**
![image](https://user-images.githubusercontent.com/2151890/83154654-0f330180-a109-11ea-95ae-6dc9130fbd4c.png)
![image](https://user-images.githubusercontent.com/2151890/83154701-207c0e00-a109-11ea-802e-7893dd2535c5.png)

**Expected behavior**
No Error to occur

**System (please complete the following information):**
 - OS: Windows 10
 - IDE: VSCode
 - Plugin/Package: Svelte Beta

**Additional context**
Didn't use svelte.config.js or any special VSCode configurations

**Comment by dummdidumm** [comment]
Duplicate to #104

**Comment by jasonlyu123** [comment]
Probably fixed in 99.0.28
