### ISSUE TITLE
Diagnostic shown in the wrong place when no script tag

### ISSUE THREAD

**Issue by jvanderen1** [sveltejs/language-tools#1250]
**Describe the bug**
I am getting an error about one of my TailwindCSS class names in VSCode:

**To Reproduce**
See screenshot below

**Expected behavior**
No error should be appearing.

**Screenshots**

<img width="1008" alt="Screen Shot 2021-11-25 at 1 32 33 PM" src="https://user-images.githubusercontent.com/22926257/143501516-5ec1da22-904c-467e-9532-9097d90851f8.png">

**System (please complete the following information):**
 - OS: macOS
 - IDE: VSCode
 - Plugin/Package: "Svelte for VSCode"

**Comment by jasonlyu123** [comment]
Can't reproduce with the code in the screenshot. It's likely caused by another code that is not in the screenshot. Please provide a reproducible in text form or a repository. Thanks.

**Comment by jvanderen1** [comment]
Apologies if it's a lot to sift through, but here is my repository: https://github.com/jvanderen1/jvanderen1.github.io

The issue is appearing under `jvanderen1.github.io/src/routes/_ContactForm.svelte`

**Comment by jasonlyu123** [comment]
So the actual problem is with the value of the `accessKey` input. The error is shown in the wrong place when there's no script tag.

**Comment by jvanderen1** [comment]
Oh interesting! I'll be sure to add that, but is there another open issue for errors showing up in incorrect places?
