### ISSUE TITLE
Auto-closing quotes doesn't work on backticks (editor.autoClosingQuotes)

### ISSUE THREAD

**Issue by alexvng** [sveltejs/language-tools#1251]
When editing a regular `.js` file, typing the backtick symbol `` ` `` will insert a second one for convenience, assuming the setting `editor.autoClosingQuotes` is set to `languageDefined` or `always`.

While editing a `.svelte` file using this extension, backticks are never auto-closed, even if `editor.autoClosingQuotes` is set to `always`.

Please let me know if there's a way to configure this that I've missed.

Version info:
- Svelte for VS Code: v105.5.3
- VSCode: 1.62.3

**Comment by dummdidumm** [comment]
Probably needs adjustmend in https://github.com/sveltejs/language-tools/blob/master/packages/svelte-vscode/language-configuration.json
