### ISSUE TITLE
Typescript cannot see prop types with tsconfig JSX setting as "react"

### ISSUE THREAD

**Issue by petemill** [sveltejs/language-tools#1256]
**Describe the bug**
Typescript is unable to see the Type for Props when tsconfig.json has `compilerOptions.jsx` set to `"react"`. The use case is a single webpack bundle which has mixed react and svelte. It doesn't seem possible (at least conveniently so) to have two separate tsconfig.json projects, whilst also being able to import from one to another and resolve the issue both for IDE and the webpack build.

**To Reproduce**
Minimal reproduction repo at https://github.com/petemill/reproduce-svelte-types-react-jsx

```svelte
<!-- src/App.svelte -->
<script lang="ts">
	export let name: string;
</script>

<main>
	<h1>Hello {name}!</h1>
</main>
```

```ts
// src/main.ts
import SvelteApp from './App.svelte'

const app = new SvelteApp({
	target: document.body,
	props: {
		name: 4
	}
})
```

**tsconfig.json**
_note `jsx` property_
```json
{
		"compilerOptions": {
			"moduleResolution": "node",
			"target": "es2017",
			"importsNotUsedAsValues": "error",
			"isolatedModules": true,
			"sourceMap": true,
			"types": ["svelte"],
			"jsx": "react",
			"strict": false,
			"esModuleInterop": true,
			"skipLibCheck": true,
			"forceConsistentCasingInFileNames": true
		},	
	"include": ["src/**/*", "src/node_modules/**/*"],
	"exclude": ["node_modules/*", "__sapper__/*", "static/*"]
	}
```

For example a code snippet that is treated in a way you don't expect.

**Expected behavior**
Typescript should error with `Type 'number' is not assignable to type 'string'`. This is the case if `compilerOptions.jsx` is changed to `"preserve"`.

![image](https://user-images.githubusercontent.com/741836/144174602-b375d55b-cd40-4bc3-91b1-df89c83f94e6.png)

**System (please complete the following information):**
 - OS: macOS
 - IDE: VSCode
 - Plugin/Package: "Svelte for VSCode"

**Comment by dummdidumm** [comment]
The reason is that we internally use JSX to represent a Svelte file's types to Typescript. There's currently a rewrite ongoing to get rid of this and other limitations. No ETA on that.

**Comment by petemill** [comment]
> The reason is that we internally use JSX to represent a Svelte file's types to Typescript. There's currently a rewrite ongoing to get rid of this and other limitations. No ETA on that.

@dummdidumm thanks for the info. Is there an issue for that, or any other way to track progress and help out?

**Comment by dummdidumm** [comment]
This is the PR that contains the rewrite: #1237 . Not much to do for now other than wait on this until it lands and then help out beta-test it.

**Comment by dummdidumm** [comment]
The most recent versions of the extension and `svelte-check` contain a new transformation behind a flag which should fix this issue. You can try out the new transformation using

- "Svelte for VS Code" version 105.11.1 and setting svelte.plugin.svelte.useNewTransformation to true
- svelte-check version 2.4.0 with the --use-new-transformation flag.

Please try it out, more info in #1352
