### ISSUE TITLE
Form events are not specific enough

### ISSUE THREAD

**Issue by mjarr** [sveltejs/language-tools#1257]
**Describe the bug**
The events described in `svelte-jsx.d.ts` as "Form Events" are defined as handled by `FormEventHandler`, which types the `Event` parameter of the handler with the generic `Event` interface.

**To Reproduce**
Try to handle the `input` event with a handler typing the `Event` property as `InputEvent`.

```html
<script lang="ts">
function handleInput(event: InputEvent) {}
</script>

<input type="text" on:input={handleInput} />
```

**Expected behavior**
Typescript doesn't complain.

**Reality**
```
Type '(event: InputEvent) => void' is not assignable to type 'FormEventHandler<HTMLInputElement>'.
  Types of parameters 'event' and 'event' are incompatible.
    Type 'Event & { currentTarget: EventTarget & HTMLInputElement; }' is not assignable to type 'InputEvent'.ts(2322)
(JSX attribute) svelte.JSX.DOMAttributes<HTMLInputElement>.oninput?: svelte.JSX.FormEventHandler<HTMLInputElement> | undefined
```

**Additional context**
`oninput` and `onbeforeinput` should supply an `InputEvent`. `onsubmit` should supply a `SubmitEvent`.

**Comment by jasonlyu123** [comment]
Typescript's `lib.dom.d.ts` definition also uses `Event` with `input` event and `submit` event. 
You can see https://github.com/microsoft/TypeScript/issues/39925#issuecomment-669550088 for the reasoning for the input event. I think we'll stick with typescript's definition. 

On the other hand, typescript uses `InputEvent` for `beforeinput` so I think we can change that.

**Comment by mjarr** [comment]
Looks like I haven't researched the topic enough. Sorry about noise.
`input` is a pretty old event, so when I read the MDN page it didn't occur to me that the `InputEvent` interface may not be standarized yet. Typescript's decision is understandable.

Aligning with Typescript in regard to `beforeinput` is definitely a good idea.

**Comment by jasonlyu123** [comment]
This doesn't age well XD. Typescript updated their submit event definition to use SubmitEvent in typescript 4.5.
