### ISSUE TITLE
Allow configuration of default script language

### ISSUE THREAD

**Issue by devmattrick** [sveltejs/language-tools#1262]
**Is your feature request related to a problem? Please describe.**
Right now, when auto-importing a component, it just defaults to adding a "vanilla" JS script tag. I do all of my work in Svelte in TypeScript so I need to go back and add a `lang="ts"` to the script tag.

**Describe the solution you'd like**
It'd be awesome if there was a way to configure the default script language in the plugin's configuration. This would simply just add `lang="<lang>"` to the generated script tag when a component is imported. This could in theory be extended to other cases where script and even style tags are generated.

**Describe alternatives you've considered**
Could always just do it the way I'm doing now but this would definitely be a small productivity boost.

**Additional context**
I'd be willing to help out with this one if this is a change that you like 😄

**Comment by jasonlyu123** [comment]
I think It would a nice addition. If you like to work on this. Follow the instruction in the [README](https://github.com/sveltejs/language-tools#development) to set up the dev environment. You can find the config list in ls-config, package.json for svelte-vscode, and the README for language-server. The script tag generation is in the CompletionProvider.
