### ISSUE TITLE
Small Intellisense issue

### ISSUE THREAD

**Issue by JonasFocke01** [sveltejs/language-tools#1263]
### Describe the problem

Custom events on custom components work like a charm, but wont show up in intellisense
`<NewAppointment
				on:save={() => console.log('Tree')}
				on:startPoll{() => console.log('Forest')}
			/>`
when i press 'ctrl+space', build-in events show up, like on:submit, but custom events, like on:startPoll in this example, wont show up.
This would make teamwork more intuitive. 

### Describe the proposed solution

I would like to see the events.

### Alternatives considered

none

### Importance

would make my life easier

**Comment by dummdidumm** [comment]
Could you provide more details? From the description it's not clear to me what the exact issue is. Is it with Dom elements or components, and which events exactly? Please provide some steps to reproduce this.

**Comment by JonasFocke01** [comment]
Im trying this in vscode.
I have a custom Component like this:
`<script>
	import { createEventDispatcher } from 'svelte';

	const dispatch = createEventDispatcher();
</script>

<button
	on:click={() => dispatch('Tree')}
>
	Tree
</button>
<button
	on:click={() => dispatch('Forest')}
>
	Forest
</button>`

When I import this into another script, i can attach the events 'Tree' and 'Forest' like other events from the Component like this:
`<script>
	import Component from './Component.svelte'
</script>

<Component on:tree={() => console.log('Event1')} on:forest={() => console.log('Event2')} />`
It works like a charm. But when i press 'ctrl+space' in vscode, intellisense only shows the predefined method 'on:submit':
![image](https://user-images.githubusercontent.com/48436748/144717967-a61cf685-a4b8-4d2a-802e-e01012ea0e85.png)
Am I doing this wrong?

**Comment by JonasFocke01** [comment]
nvm, it seems vscode hat an issue, now it works fine
