### ISSUE TITLE
Diagnostic message "Stores must be declared at the top level of the component" gives invalid line number

### ISSUE THREAD

**Issue by rgossiaux** [sveltejs/language-tools#1271]
**Describe the bug**
The diagnostic message `Stores must be declared at the top level of the component` comes with a line number of -1, which is invalid: https://microsoft.github.io/language-server-protocol/specification#position This breaks diagnostics in my editor. 

**To Reproduce**
Here is a minimal file that repros this for me:
```
<script lang="ts">
    import { writable } from "svelte/store";

    let foo = writable("value");
    function bar() {
        let bar = foo;
        console.log($bar);
    }
</script>
```

**Expected behavior**
The line number should ideally be the line number of the underlying problem, but at the very least (if this is an upstream svelte problem) it should be validated to be non-negative, eg setting it to 0.

**Screenshots**

**System (please complete the following information):**
 - OS: Mac OS 12.0
 - IDE: Neovim
 - Plugin/Package: svelte-language-server 0.14.13

**Comment by jasonlyu123** [comment]
Did you disable sourcemap for preprocessing by any means? It seems like this diagnostic can't be mapped back to its source.

**Comment by rgossiaux** [comment]
Not as far as I know but I'm happy to run any kind of check on my end. This is the only diagnostic that has a problem--everything else works correctly.

**Comment by rgossiaux** [comment]
I installed VSCode to rule out anything specific to my neovim setup. I installed the svelte extension, opened up a fresh directory, made a new file, and pasted in the code in my report. While I'm not sure how to debug the underlying LSP like I am with nvim, it looks like it's broken here as well: as long as this error is in the file, the problems elsewhere in the file don't update. You can insert gibberish into the file and it will only suddenly be flagged as a problem once you remove the console.log($bar) line or otherwise fix that error.

Additionally I ran into a second diagnostic where this happens: `illegal-global`, with message `$ is an illegal variable name`. It's also sending a line of -1. If I typo $: as $; I run into this. For example:
```
<script lang="ts">
    $;
</script>
```

If I add a second line with gibberish like `asldkfq;`, nothing appears in VSCode. Only once I change `$;` to `$:` (for example) does something show up.

Finally it looks like this is related to the `lang="ts"` designation. If I remove that then everything works correctly (both in neovim and in VSCode).

**Comment by jasonlyu123** [comment]
Did you have a `tsconfig.json` or `jsconfig.json`? From my debugging, it seems like the svelte-preprocess we're bundling doesn't quite work when there isn't either of them. The forced sourcemap option we passed also doesn't work. We might have to consider bumping the version. 

If you do have a `tsconfig`/`jsconfig` make sure you enable [compilerOptions.sourceMap](https://www.typescriptlang.org/tsconfig#sourceMap). This should make fix the underlying problem.

**Comment by rgossiaux** [comment]
Aha, you're right. I added a tsconfig.json (extending the @tsconfig/svelte config) and these diagnostics work now. Thanks! That fixes my problem, though I still consider this a bug--if the language server runs into problems like this it should fail more gracefully than sending invalid diagnostics.

**Comment by dummdidumm** [comment]
> Did you have a `tsconfig.json` or `jsconfig.json`? From my debugging, it seems like the version of the svelte-preprocess we're bundling doesn't quite work when there isn't either of them. The forced sourcemap option we passed also doesn't work. We might have to consider bumping the version.

Does a version bump help us, or is this something that's still a problem inside `svelte-preprocess`? Or is it just a configuration problem on our end? Maybe we need to pass `sourceMap: true` as well?

```javascript
        return {
            preprocess: sveltePreprocess({
                sourceMap: true, //<<-- add this line
                // 4.x does not have transpileOnly anymore, but if the user has version 3.x
                // in his repo, that one is loaded instead, for which we still need this.
                typescript: <any>{
                    transpileOnly: true,
                    compilerOptions: { sourceMap: true, inlineSourceMap: false }
                }
            })
        };
```

**Comment by jasonlyu123** [comment]
> Does a version bump help us

It's fixed in https://github.com/sveltejs/svelte-preprocess/pull/407

> though I still consider this a bug--if the language server runs into problems like this it should fail more gracefully than sending invalid diagnostic

Yeah we also should fix the line number.
