### ISSUE TITLE
svelte-check: unused label (dollar sign)

### ISSUE THREAD

**Issue by rondonjon** [sveltejs/language-tools#128]
I am using the dollar symbol in some of my .svelte files as documented here:

https://svelte.dev/docs#3_$_marks_a_statement_as_reactive

`svelte-check` raises errors about these symbols as follows:

```
File : /home/.........svelte
Warn : Unused label. (ts)
Line: 15, Character: 2
,
  };

  $: {
```

Being part of the Svelte specification, these symbols should IMO not be reported.

**Comment by Conduitry** [comment]
Transferring this issue to the language-tools repo, as the source for svelte-check lives in https://github.com/sveltejs/language-tools/tree/master/packages/svelte-check

(The published npm package should probably have repository/homepage fields in its package.json though.)
