### ISSUE TITLE
ts-module does not work from node_modules

### ISSUE THREAD

**Issue by yababay** [sveltejs/language-tools#1290]
Hi, developers of ts-plugin for Svelte.

I import my own library in a svelte-module as

```
import D3LinearChart from '../lib/D3LinearChart'
```
It works fine for me. But when I try to import the same library from node_modules, I have the following error:

```
import D3LinearChart from '@yababay67/d3-adapter'
```

```
4: import { D3Axes, getAxis } from './D3Axes'
5: 
6: abstract class D3BareChart {
            ^
7: 
8:     public static d3 = d3
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (/home/blah-blah/node_modules/rollup/dist/shared/rollup.js:158:30)
```

How can I setup my build process?

**Comment by dummdidumm** [comment]
Please provide a more detailed reproduction, ideally a reproduction repository, else we can't help you.

**Comment by yababay** [comment]
Hi, Simon, thank you for reply. The reproduction repository is:

https://github.com/yababay/ts-svelte-plugin-question.git

Repository of the library:

https://github.com/yababay/d3-adapter

Npm-package:

https://www.npmjs.com/package/@yababay67/d3-adapter

**Comment by dummdidumm** [comment]
Two issues:
1. You write `import D3LinearChart from '@yababay67/d3-adapter';` but your library doesn't have a default export, it should be `import { D3LinearChart } from '@yababay67/d3-adapter';`
2. You don't transpile your library to JavaScript - the TypeScript sources end up untouched in the published package. Either publish a JavaScript package (better approach in my opinion), or adjust your `tsconfig.json` in your project to also include the files in your TypeScript package (else that will be ignored).

Closing as this is no bug in language-tools.

**Comment by yababay** [comment]
Thanks, Simon. I'm newbie in ts yet, so your advice are very helpful to me.
