### ISSUE TITLE
I get the hint "declared but value is never read" on an #each loop where I just use the index 

### ISSUE THREAD

**Issue by 205g0** [sveltejs/language-tools#1295]
**Is your feature request related to a problem? Please describe.**
Sometimes I use each loops where I just need its index. If there were a for loop I could use this over the length of an array.

**Describe the solution you'd like**
Either tsserver gets that it's ok just to use the index...

**Describe alternatives you've considered**
...or your change `#each`'s API and allow usage without `as ...`

**Comment by jasonlyu123** [comment]
If you prefix the variable name with an underscore the hint should go away, the same as function parameters.

**Comment by 205g0** [comment]
Thanks, wasn't aware of this, nice. I also just found out that `as {}` does the trick as well. I close now, however, allowing `#each` without `as ...` would be an elegant solution in the long term. So nothing crucial or important but yeah.

**Comment by 205g0** [comment]
btw, is this underscore prefix a TS or Svelte thing?

**Comment by jasonlyu123** [comment]
Ts, We transform each block into a callback function under the hoods, that's why it's the same.
