### ISSUE TITLE
Consider switching from chalk to picocolors

### ISSUE THREAD

**Issue by benmccann** [sveltejs/language-tools#1299]
**Is your feature request related to a problem? Please describe.**
Work is ongoing to minimize Vite size. Assuming https://github.com/vitejs/vite/pull/6277 is merged, then Vite will be standardized on picocolors

**Describe the solution you'd like**
It would probably make sense for us to standardize on picocolors to match Vite

**Describe alternatives you've considered**
If there is a reason to continue using chalk we may want to chime in on the Vite PR. However, I'm not aware of any such reasons

**Additional context**
`svelte-check` currently uses `chalk`: https://github.com/sveltejs/language-tools/blob/c978ee14602a338679e5f3bef62b9828e25d55c2/packages/svelte-check/package.json#L22

**Comment by dummdidumm** [comment]
I don't think there's any reason to using chalk specifically, so I'm fine with switching the dependency.
