### ISSUE TITLE
Use the same color tags as HTML for svelte tags

### ISSUE THREAD

**Issue by endigma** [sveltejs/language-tools#1304]
**Is your feature request related to a problem? Please describe.**
In `.svetle` files with the language set to `Svelte` the syntax highlighting is not in-line with HTML on some themes.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/34945114/147611566-f910a369-0624-4fea-bdf5-0115abc47643.png)

(tags are mtk16 instead of mtk1)

**Additional context**

How it looks currently:
![image](https://user-images.githubusercontent.com/34945114/147611630-818cbdd8-68bb-4676-9c22-10b3c6306608.png)

in some themes this isn't an issue, not sure what the difference is

**Comment by Monkatraz** [comment]
I suspect this isn't really fixable, because what's happening is that some themes are specifically coloring HTML tags by name. This is a bad idea, and this shows why lol.

Svelte's grammar generally has the exact same scopes that HTML uses, except with `*.svelte` instead of `*.html`.

**Comment by endigma** [comment]
I fixed this on the theme, entity.tag.something had no color set
