### ISSUE TITLE
Type checking doesn't handle let: props in element directives

### ISSUE THREAD

**Issue by JustinVoitel** [sveltejs/language-tools#1306]
**Describe the bug**
When using `let:` props in any directive on the same element, e.g:
```svelte
<Outer>
   <!-- we assume Outer passes the prop value to the slot 
        and Inner does forward on:click -->
   <Inner 
      let:value 
      on:click={e=>console.log(value)} 
   />
</Outer
```
..the code does compile and works as expected, but the Language Server tells me it cannot find the prop (in this case `value`)

**To Reproduce**
1. copy the [3 files](https://svelte.dev/repl/82ae40ca2a624a75b648f7f16ab28070?version=3.44.3)  in any Svelte Project using the Language Server
2. Check in the console that its working despite showing an error

**Expected behavior**
To show no error when using let: props in element directives

**Screenshots**
<img width="683" alt="Screenshot 2021-12-29 at 21 31 03" src="https://user-images.githubusercontent.com/30449535/147701128-4bd0c1f8-0914-4707-8665-087d5e60b190.png">

**System (please complete the following information):**
 - OS: MacOS 12.1
 - IDE: VSCode v1.63.2
 - Plugin/Package: Svelte for VSCode v105.8.0

**Comment by jasonlyu123** [comment]
I assume your problem is with the named slot one in the REPL link. The default slot one in the screenshot and the issue description doesn't seem to work. The svelte compiler would also show a variable not declared error in the REPL.

**Comment by dummdidumm** [comment]
I think this will be fixed as part of the rewrite so I'm hesitant to fix this in the "old" version.

**Comment by dummdidumm** [comment]
This is fixed as part of the new transformation. See #1352  for more info on how to enable it. It's in beta state, so if you have any feedback unrelated to the issue right here please post that in #1352 . Thank you.
