### ISSUE TITLE
svelte:window event handlers don't have the exact type

### ISSUE THREAD

**Issue by wyozi** [sveltejs/language-tools#132]
**Describe the bug**
The event callback parameter for `<svelte:window>` has `Event` type instead of something more specific like `MouseEvent`. Also happens for `<svelte:body>`

**To Reproduce**

```
<svelte:body
  on:mousemove={(e) => e.clientX} />
```
results in `Property 'clientX' does not exist on type 'Event'.ts(2339)` (because `e` is an `Event`)

**Expected behavior**

No error.

**Comment by dummdidumm** [comment]
@halfnelson these are the jsx typings, right? Anything we can do about this except going through all of the events by hand and narrowing their types?
