### ISSUE TITLE
Unexpected formatting of <button> & <label>

### ISSUE THREAD

**Issue by klequis** [sveltejs/language-tools#1324]
**Describe the bug**

I'm seeing some odd formatting when using Svelte for VS Code for button & label. It may be happening with other elements as well but I have not observed that as yet.

If I enter the below on one line (or any other way)
```svelte
<button type="submit" disabled={!name} class="btn btn__primary btn__lg">Add</button>
```
It gets formatted as
```svelte
<button type="submit" disabled={!name} class="btn btn__primary btn__lg"
  >Add</button
>
```

**To Reproduce**

Past
```svelte
<button type="submit" disabled={!name} class="btn btn__primary btn__lg">
  Add
</button>
```
and/or
```svelte
<label for="todo-{todo.id}" class="todo-label">New name for '{todo.name}'</label>
```
Into a `.svelte` file and save to initiate formatting.

**Expected behavior**

Have the line breaks at more commonly expected places such as 

```svelte
<button 
  type="submit" 
  disabled={!name} class="btn btn__primary btn__lg"
>
  Add
</button>
```

**Screenshots**

**System (please complete the following information):**
 - OS: Ubuntu 21.10
 - IDE: VS Code v1.63.2
 - Plugin/Package: Svelte for VS Code v1.63.2

**Additional context**

Here is the issue in context of my code.
```svelte
<form
  on:submit|preventDefault={addTodo}
  on:keydown={e => e.key === 'Escape' && onCancel()}
>
  <h2 class="label-wrapper">
    <label for="todo-0" class="label__lg">What needs to be done?</label>
  </h2>
  <input
    bind:value={name}
    bind:this={nameEl}
    use:selectOnFocus
    type="text"
    id="todo-0"
    autoComplete="off"
    class="input input__lg"
  />
  <button type="submit" disabled={!name} class="btn btn__primary btn__lg"
    >Add</button
  >
</form>

<div class="form-group">
  <label for="todo-{todo.id}" class="todo-label"
    >New name for '{todo.name}'</label
  >
  <input
    bind:value={name}
    bind:this={nameEl}
    use:selectOnFocus
    type="text"
    id="todo-{todo.id}"
    autoComplete="off"
    class="todo-text"
  />
</div>
```

**Comment by jasonlyu123** [comment]
This is the correct behaviour. As button and label are inline elements. it's whitespace sensitive. 

```html
<button>a</button>
```
```html
<button>
  a
</buton>
```

These two are not the same. You can read more in the [docs of prettier-plugin-svelte](https://github.com/sveltejs/prettier-plugin-svelte#svelte-bracket-new-line)
