### ISSUE TITLE
Property 'webkitdirectory' does not exist on type 'SvelteInputProps'

### ISSUE THREAD

**Issue by hadisajjadi** [sveltejs/language-tools#1328]
**Describe the bug**
I'm getting the following typescript error on an `input` element with `type="file"`
`Property 'webkitdirectory' does not exist on type 'SvelteInputProps'`

**To Reproduce**
```
<script lang="ts">
	let directory = "";
</script>

<input type="file" webkitdirectory bind:value={directory} />
```

**Expected behavior**
no error, webkitdirectory is a valid property.

**Comment by dummdidumm** [comment]
[According to mdn](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitdirectory) it's a non-standard attribute with possibly varying implementation and no plans on standardizing it. The [React JSX typings](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts) don't include it. I therefore think it shouldn't be added to our types. You can however enhance the typings yourself, read more here: https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/typescript.md#im-using-an-attributeevent-on-a-dom-element-and-it-throws-a-type-error
