### ISSUE TITLE
Add support for new @const tag

### ISSUE THREAD

**Issue by dimfeld** [sveltejs/language-tools#1330]
Right now the extension doesn't like if you use the `@const` tag added in the latest Svelte release, especially in `svelte2tsx` I think.

I'll work on adding support on Wednesday or Thursday if nobody else gets to it first. Looks like a rather small change that can be mostly based on the existing `@html` tag support.

**Comment by dimfeld** [comment]
Will be fixed by #1072

**Comment by dummdidumm** [comment]
Closing as duplicate of #1067
