### ISSUE TITLE
svelte-check reports an error when a store is used as the value of a style directive

### ISSUE THREAD

**Issue by sea-grass** [sveltejs/language-tools#1334]
**Describe the bug**

When a store is used as the value of a style directive, svelte-check reports `Error: Identifier expected.` despite it being fully functional.

**To Reproduce**

Please see [the REPL](https://svelte.dev/repl/5ae0912d40c24fc2a1cf069b40e86121?version=3.46.1) to see the following snippet in action:

```svelte
<script>
	import { writable } from 'svelte/store';
	const color = writable('red');
</script>

<h1 style:color={$color}>Hello!</h1>
```

We end up with the following error (followed by a cascade of errors) after running `svelte-check`:

```sh
.../App.svelte:6:18
Error: Identifier expected. (js)

<h1 style:color={$color}>Hello!</h1>
```

**Expected behavior**

svelte-check shouldn't report an error for the style directive `style:color={$color}`.

**Screenshots**

n/a

**System (please complete the following information):**
 - OS: Mac
 - IDE: n/a
 - Plugin/Package: `svelte-check@2.3.0`

**Additional context**

Let me know if you require any additional info. Thanks!

**Comment by ghostdevv** [comment]
Have you tried updating your dependencies?

**Comment by sea-grass** [comment]
Ah, my bad, I should have tried that first. That was the issue! I updated all my svelte-related dependencies with `npx npm-check-updates -u '/svelte/'` and ran svelte-check again to see that it works as expected. Thanks!

**Comment by ghostdevv** [comment]
np!
