### ISSUE TITLE
TypeScript inlay hints

### ISSUE THREAD

**Issue by blaumeise20** [sveltejs/language-tools#1336]
**Is your feature request related to a problem? Please describe.**
VSCode added inlay hints a while ago. The problem is that svelte doesn't show them in script tags.

**Describe the solution you'd like**
Show inlay hints like in normal JS/TS files.

**Comment by jasonlyu123** [comment]
I think we'll wait until the API is finalized and ships in the Language Server Protocol. Currently, it seems like the API is still in the proposed stage in vscode.

**Comment by dummdidumm** [comment]
LSP 3.17 has support for inlay hints https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_inlayHint

**Comment by LeoDog896** [comment]
TypeScript now has [inlay hints](https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/)

**Comment by insilications** [comment]
Has the API been finalized in LSP?

**Comment by jasonlyu123** [comment]
Yes. And the feature we want to prioritize is also done. We'll do it soon.
