### ISSUE TITLE
svelte-vscode: can't disable diagnostics (error with postcss-nesting)

### ISSUE THREAD

**Issue by boojum** [sveltejs/language-tools#1339]
**Describe the bug**
Disabling diagnostics with `"svelte.plugin.css.diagnostics.enable": false"` does not work. While using [PostCSS Language Support](https://marketplace.visualstudio.com/items?itemName=csstools.postcss) I'm still receiving error:
```
Identifier is expected

If you expect this syntax to work, here are some suggestions: 
If you use less/SCSS with `svelte-preprocess`, did you add `lang="scss"`/`lang="less"` to your `style` tag? If you use SCSS, it may be necessary to add the path to your NODE runtime to the setting `svelte.language-server.runtime`, or use `sass` instead of `node-sass`. 
Did you setup a `svelte.config.js`? 
See https://github.com/sveltejs/language-tools/tree/master/docs#using-with-preprocessors for more info.svelte(css-syntax-error)
```

**To Reproduce**

1. Install [Svelte for VS Code](https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode).
2. Install [PostCSS Language Support](https://marketplace.visualstudio.com/items?itemName=csstools.postcss).
3. install `postcss` and `postcss-nesting` 
4. `postcss.config.cjs`:
```
module.exports = {
  plugins: [
    require('postcss-nesting')
  ]
}
```
5. Install and configure `svelte-preprocess`:
```
// svelte.config.js
import cloudflare from '@sveltejs/adapter-cloudflare'
import preprocess from 'svelte-preprocess'

/** @type {import('@sveltejs/kit').Config} */
const config = {
  preprocess: preprocess({ postcss: true }),
  kit: {
    adapter: cloudflare(),
    target: '#svelte',
  },
}

export default config
```
6. Configure VS Code:
```
// settings.json
{
  // disable vscode native linting in favour of stylelint
  "css.validate": false,
  "less.validate": false,
  "scss.validate": false,

  // disable svelte native linting in favour of stylelint
  "svelte.plugin.css.diagnostics.enable": false,

  "stylelint.validate": [
    "css",
    "scss",
    "postcss",
    "svelte"
  ],

  "emmet.includeLanguages": { "postcss": "css" },

  "svelte.enable-ts-plugin": true,
}
```

Following snipped will cause the aforementioned error:
```
<div>
  <p>foo</p>
</div>

<style lang="postcss">
  div {
    & p {
      background-color: red;
    }
  }
</style>
```
**Expected behavior**
Diagnostics provided by Svelte Vs Code extension are disabled and do not interfere with `postcss`.

**System (please complete the following information):**
 - OS: Ubuntu 21.10
 - IDE: VS Code 1.63.2
 - Plugin/Package: Svelte for VSCode

**Comment by dummdidumm** [comment]
These errors come from the Svelte compiler and you can disable them through `"svelte.plugin.svelte.diagnostics.enable": false`. I'm not sure though why preprocessing doesn't work properly in this case.

**Comment by boojum** [comment]
`"svelte.plugin.svelte.diagnostics.enable": false` indeed got rid of the warning, cheers for the tip!
