### ISSUE TITLE
Allow numbers in `style:` directive

### ISSUE THREAD

**Issue by PuruVJ** [sveltejs/language-tools#1342]
**Is your feature request related to a problem? Please describe.**
In `style:` directive syntax, you can't pass a number. Svelte's VSCode extension errors out when you attempt something like `style:z-index={someNumericalValue}`, so you have to apply hacks like `style:z-index={someNumericalValue + ''}` to coerce it into a string, which looks really ugly.

**Describe the solution you'd like**
I recommend language-tools don't error out when value passed is a number, as that is a valid value for properties like z-index, width, height, block-*, top, bottom, inset, opacity, and many more, including all the CSS Variables `style:--opacity={someNumber}`.

This would work because we know JS coerces numbers into strings when needed, so svelte core itself doesn't need to be changed

**Describe alternatives you've considered**
Not do anything

**Comment by dummdidumm** [comment]
I tend to agree with this request. I doubt that many people would pass a wrong value type by accident, so the benefits outweigh the type correctness in this case. We could possibly add a list of style props that would be ok with a number but that feels like bloating the bundle size.

**Comment by PuruVJ** [comment]
Why not allow for any value? 🤔

**Comment by Tymek** [comment]
Template literal looks marginally better ```style:z-index={`${someNumericalValue}`}```. What's the disadvantage of allowing numbers everywhere? TS will not check for example if a CSS unit is correct ~~`3REMS`~~ 🤔

**Comment by PuruVJ** [comment]
Thank you so much for this Simon 🙇
