### ISSUE TITLE
Support for the static asset handling syntax from vite

### ISSUE THREAD

**Issue by akkie** [sveltejs/language-tools#1343]
I'm not sure if this is a problem with language-tools or something else. But I have no idea where I should start first.

Vite supports [static handling](https://vitejs.dev/guide/assets.html) with imports and a query like syntax.

```
import bgSplash from '$static/img/bg-splash.jpg?webp';
```

Currently, the vscode extension cannot handle it and shows an error:
Cannot find module '$static/img/bg-splash.jpg?webp' or its corresponding type declarations.

Is there anything I can do to handle that without an error? Maybe some configuration option?

**Comment by jasonlyu123** [comment]
Vite has typedef for query mentioned in the docs. Like `?raw` and `?url`. In that case, just add the `vite/client` to the [types](https://www.typescriptlang.org/tsconfig#types) section in the tsconfig.json/jsconfig.json. Or using the `/// <reference type="vite/client" />` [directive](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html#-reference-types-). Svelte-kit has included this by default. 

But I didn't see this `?webp` query in the docs. I also try this in a svelte kit app. It doesn't seem to do anything. The file loaded in the browser is still whatever the file originally is. Am I missing something? Is it something you can customize? 

Either way, If you are sure this isn't wrong, You can reference the [typedef in vite](https://github.com/vitejs/vite/blob/main/packages/vite/client.d.ts#L188) and add it yourself. Put this in a `.d.ts` file and make sure it's [included](https://www.typescriptlang.org/tsconfig#include) in your jsconfig.json/tsconfig.json

**Comment by akkie** [comment]
@jasonlyu123 Thanks for your answer. The import directives comes from https://github.com/JonasKruckenberg/imagetools/tree/main/packages/vite

**Comment by andyliuhaowen** [comment]
Adding `/// <reference types="vite/client" />` to `.d.ts` did solve it for imports without the `webp` directive.

Importing with the `webp` directive still errors:
`Cannot find module '../images/sample.png&webp' or its corresponding type declarations.ts(2307)`

@akkie Does it work for you with the `webp` directive? If so, is there anything additional you had to do to resolve it?

**Comment by dummdidumm** [comment]
You need to add a module typing similar to the ones in [this file](https://github.com/vitejs/vite/blob/main/packages/vite/client.d.ts#L188) with `*&webp`
