### ISSUE TITLE
Generics don't work properly when passing down slot props

### ISSUE THREAD

**Issue by aradalvand** [sveltejs/language-tools#1344]
Consider the following components:
`Form.svelte`:

```svelte
<script lang="ts">
    type TValues = $$Generic;

    export let values: TValues;

    type Errors<T> = {
        [K in keyof T]: string;
    };

    let errors: Errors<TValues>;
</script>

<form>
    <slot {errors} />
</form>
```

`SpecialForm.svelte`:

```svelte
<script lang="ts">
    import Form from './Form.svelte';

    type TValues = $$Generic;

    export let values: TValues;
</script>

<Form
    {values}
    let:errors
>
    <slot {errors} />
</Form>
```

`App.svelte`:

```svelte
<script lang="ts">
    import SpecialForm from './SpecialForm.svelte';

    let values: {
        firstName: string;
        lastName: string;
    };
</script>

<SpecialForm
    {values}
    let:errors
>
    {errors.firstName}
</SpecialForm>

```

In the last component (`App.svelte`), the slot prop `errors` doesn't have the right type, it's of type `Errors<unknown>` even though the generic type is properly detected for `values`.
![image](https://user-images.githubusercontent.com/26527405/150644043-7b60c0ed-4253-49bd-b961-15f58125f5ba.png)

I have quite a few components that have this kind of relationship, and generics are not working as expected currently, so I'd appreciate it if you fix this. Thank you.

**Comment by AradAral** [comment]
@dummdidumm Don't mean to hurry anyone, but can you confirm this please? Doesn't matter if it's not fixed immediately. I just want to know I'm not the one making some mistake.
Thank you.

**Comment by AradAral** [comment]
I'm still waiting for a response

**Comment by dummdidumm** [comment]
Every issue you open is the most pressing you currently have. It's not like maintainers are idle and jump on every post you create. We will eventually get to answering these, and adding passive aggressive posts that are essentialy just elaborate "bump"s isn't helping. Locking and limiting the conversation on this issue, other people who have the same problem, please thank @AradAral for that.

**Comment by dummdidumm** [comment]
Closing since Svelte 5 replaces slots with snippets and render tags, which don't have this problem (because you're required to type it properly)
