### ISSUE TITLE
Markup incorrectly parsed after <style global> SCSS flag

### ISSUE THREAD

**Issue by Egnus** [sveltejs/language-tools#136]
**Describe the bug**
HTML Svelte interpolated code with comparisons `{condition === 2}` starts to make the rest of the file to be wrongly parsed after <style> tag if 'global' flag is provided at the end of the style tag for SCSS preprocessors.
_This does not affect builds and the **same svelte.config is both used for rollup and for vscode with the preprocessor**._
**To Reproduce**
1. The order of the Svelte file has to be `script - style - markup`.
2. Style **has to use `global` preprocessor flag attribute after any other attrib** like `<style src="./path.scss" global>`
3. In the markup, inside interpolated Svelte code ({expressions}) there should be a boolean comparison (this is the only case I found but there might be more) like `{x === 2}`.

Minimal reproducible example:
```svelte
<script>let whatever = 1; /* it does not matter */</script>
<style src="./aFile.scss" global> // <-- 'global' has to be last
{whatever === 1} // <-- last '}' will give you error, then almost any other not native html code
```

**Expected behavior**
Nothing should be prompted unless it is a real error.

**Screenshots**
![Screenshot 2020-05-29 at 13 37 47](https://user-images.githubusercontent.com/8260475/83257286-57f3c480-a1b4-11ea-9590-58d875fae806.png)

**System (please complete the following information):**
 - OS: Mojave. Mac
 - IDE: VSCode
 - Plugin/Package: only "Svelte Beta" (No "Svelte" or "Svelte Type Check" or similar)

**WORKAROUND**
I found out that if `global` is set just before the `src=""` attribute, the compiler will work. 
This clarifies that this issue is, in fact, from the language-tool, perhaps as a conflict with other built-in plugins from VSCode

```svelte
<script>let whatever = 1; /* it does not matter */</script>
<style global src="./aFile.scss">
{whatever === 1} // This works
```

**Comment by jasonlyu123** [comment]
This is because the transformation behind the scenes mistakenly takes the === as the end of the global attribute. Thank you for the report.

**Comment by dummdidumm** [comment]
So this is another case where our regex-parser fails? Maybe we could refactor it [as proposed here](https://github.com/sveltejs/language-tools/issues/143#issuecomment-636440478) and then fix both these issues at once.

**Comment by jasonlyu123** [comment]
This one is in `svelte2tsx`, this line:
https://github.com/sveltejs/language-tools/blob/aae23ef15861310a8b45f091f928db541740df1e/packages/svelte2tsx/src/htmlxparser.ts#L54

**Comment by Egnus** [comment]
yeah, it seems that that code doesn't take into consideration `true` implicit attributes.

**Comment by Egnus** [comment]
how can i see is this is added in the current version? is it auto-deployed when merged? At this moment it still shows the error

**Comment by dummdidumm** [comment]
It is autodeployed nightly, in about 8 hours.

**Comment by Egnus** [comment]
I am afraid it still does not work. Updated & restarted all before testing, nothing relevant in the Output -> Svelte either
![Screenshot 2020-06-03 at 11 27 51](https://user-images.githubusercontent.com/8260475/83620347-7cbdb280-a58d-11ea-87b1-bbe03785a516.png)

**Comment by jasonlyu123** [comment]
language-server and svelte-vscode seem to be released with the version of `svelte2tsx` released a day ago. So the fix hasn't been released yet.

**Comment by dummdidumm** [comment]
Oh, we definetely should somehow order the releases during the deploy then. @orta can we somehow change this so that it's "deploy svelte2tsx to npm first, then svelte-language-server, then svelte-check, then deploy svelte-vscode to marketplace", so that the `yarn install` that is done in svelte-vscode before publishing already gets the latest version?

**Comment by Egnus** [comment]
I have tried to push some changes as a PR but it seems that the project is locked and I does not admit branches and PRs.

I just did to changes to reorder the build in any case. Still today the vscode extension fails on this and I can see it seems that is failing the deployments for the last 3 or 4 days.

**Comment by dummdidumm** [comment]
Deployment: orta will look into it, he has made an issue to track it.
PRs: you should definitely be able to do PRs. You need to fork the repo for that.

**Comment by Egnus** [comment]
Fixed in the last deployed version 🙇 👍
