### ISSUE TITLE
Type checking does not carry across spreading `...$$restProps`

### ISSUE THREAD

**Issue by rgossiaux** [sveltejs/language-tools#1363]
**Describe the bug**
If a component `A` spreads its `$$restProps` to some child component `B`, and `B` has some typed prop `foo`, then any `foo` which is passed to `A` should be checked against the type specified in `B`. For example, if `B` specifies that `foo` is a string, then `<A foo={console.log}>` should give a type error. Right now it does not.

For that matter, you can also just pass invalid props to `A` which don't actually exist on `A` or `B`, and no error will be thrown.

I can imagine why this could get complicated, but it'd still be really nice if it worked. I ran into this trying to make some TypeScript improvements in `svelte-headlessui`

**To Reproduce**
I created a repo for ease of illustration: https://github.com/rgossiaux/svelte-prop-spread-ts

**Expected behavior**
See repo

**Screenshots**
N/A

**System (please complete the following information):**
 - Plugin/Package: `svelte-check` v2.4.1

**Comment by dummdidumm** [comment]
The component could be used in many different circumstances, so it's not clear statically what `$$restProps` actually contains. The whole idea of `$$restProps` is to allow dynamic behavior at runtime, which can't be statically analysed and therefore can't be typed. We won't add whole-app-analysation to check all possible values of `$$restProps`, therefore closing this.

**Comment by dummdidumm** [comment]
You want the type of `$$restProps` to be different depending on whether I pass it to component A or component B. But TypeScript does not analyze type control flow this way. The type definitions are top down. You can't pass something to a function and change the value of the parameter depending on where you pass it to, it's the other way around.

**Comment by rgossiaux** [comment]
You're right, that makes sense. Thanks for the explanation.
