### ISSUE TITLE
svelte-language-server v0.14 raises error in web browser

### ISSUE THREAD

**Issue by wangjia184** [sveltejs/language-tools#1365]
**Describe the bug**
Using svelte-language-server  in web browser.
Version 0.13.9 works fine; if changing to v0.14.0+ it raises an error in web browser. Please check screenshot below

**To Reproduce**
Source code is [here](https://github.com/wangjia184/monaco-svelte/tree/upgrade_version).
Open [package.json](https://github.com/wangjia184/monaco-svelte/blob/upgrade_version/package.json),  find the following line

```
"svelte-language-server": "^0.13.9",
```

Replace it with following line
```
"svelte-language-server": "^0.14.0",
```

Then `npm install` and build the project and refresh the index.html,  the error raises.

**Expected behavior**

This error shouldn't occur in v14+

**Screenshots**

![image](https://user-images.githubusercontent.com/2765840/152336057-ef48775e-83e6-4b3d-a2fb-8296d7ff7b43.png)
![image](https://user-images.githubusercontent.com/2765840/152336115-8e8fb834-ca2d-42cf-b3d5-974f3c4fc585.png)

**Additional context**
Using svelte language server in web browser

**Comment by dummdidumm** [comment]
Please open such issues at https://github.com/asafamr/monaco-svelte where you forked the repo from. Usage in the browser is not a supported scenario right now, they language server is intended to be used with NodeJS, and we make no guarantees that updates break any shims that make it work in the browser.
We will some day revisit this in the context of #1190
