### ISSUE TITLE
Add support for component documentation

### ISSUE THREAD

**Issue by blaumeise20** [sveltejs/language-tools#1368]
I would like to have a way to define documentation/description for a component that gets shown in hover information.
Something like JSDoc:
```html
<!---
  -- This component is used to handle clicks on link elements.
  -- Adds custom routing to the site.
  --->
```
You would have to put this as the first thing in the component.

**Comment by ignatiusmb** [comment]
Have you seen https://github.com/sveltejs/language-tools/tree/master/docs#documenting-components?

**Comment by dummdidumm** [comment]
Thanks @ignatiusmb for pointing out, this is the way to do that.

**Comment by blaumeise20** [comment]
Oh, thanks, no I didn't see this.
