### ISSUE TITLE
Control flow does not work for uninitialized exported props in script tag

### ISSUE THREAD

**Issue by dummdidumm** [sveltejs/language-tools#1370]
**Describe the bug**
Control flow does not work for uninitialized but exported props

**To Reproduce**
```svelte
<script lang="ts">
    type Test =
        | { type: 'TypeA'; uniqueToA: string }
        | { type: 'TypeB'; uniqueToB: string };

    export let test: Test;

    // works
    console.log(test.type);
    
    // doesn't work
    if (test.type == 'TypeA') {
        console.log(test.uniqueToA);
    }

    // works
    $: if (test.type == 'TypeA') {
        console.log(test.uniqueToA);
    }
</script>

<!-- works -->
{#if test.type == 'TypeA'}
    {test.uniqueToA}
{/if}
```

**Expected behavior**
Control flow should work in all cases

**System (please complete the following information):**
 - OS: -
 - IDE: VS Code
 - Plugin/Package: svelte2tsx/language-server

**Additional context**
Possible solution: Initialize the variable in the generated code (AFAIK we do that for booleans already).

Maybe the solution here helps with #1335, but could very well not be the case.

**Comment by jasonlyu123** [comment]
Initializing it would also help #1201. I tried it before. But the sourcemap would cause the completion to be calculated at the end of the generated code. Causing global identifiers completion instead of type completion. Which hurts the experience.
