### ISSUE TITLE
Formatting does not work anymore if svelte template contains the new `{@const ...}` tag

### ISSUE THREAD

**Issue by bttger** [sveltejs/language-tools#1374]
## **Describe the bug**
The formatter stops working when using the `{@const ...}` tag in a svelte template. I use it with the auto-format on save feature of VSCode and I think it still runs but it just doesn't do anything because it doesn't recognize the new tag which got released just recently.

## **To Reproduce**
The following code snippet won't get auto-formatted. Only if you remove line 2, the formatter works again and correctly formats the space between the `{:else}` and `false`.
```svelte
{#each [true, false] as entry}
{@const isDone = entry}
	{#if isDone}
		true
	{:else}
		
    false
	{/if}
{/each}
```

## **Expected behavior**
I expect the formatter to work ordinary.

## **System (please complete the following information):**
 - OS: Linux
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode (v105.11.3), Prettier, ESLint

VSCode Specs:
Version: 1.62.0
Commit: b3318bc0524af3d74034b8bb8a64df0ccf35549a
Date: 2021-11-07T19:37:13.664Z
Electron: 13.6.3
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.13.19-2

**Comment by dummdidumm** [comment]
My guess is that you have `prettier-plugin-svelte` inside your `package.json` and didn't update to the latest version there which contains support for const and style tags. Background: when there's a `prettier-plugin-svelte` package inside your project, that one is used instead of the one built-in.

**Comment by bttger** [comment]
@dummdidumm Thank you, a simple `npm up` fixed it. I was using Svelte Kit and I didn't know about the outdated `prettier-plugin-svelte` version in my dev dependencies.
