### ISSUE TITLE
Use prettier-plugin-tailwindcss to format css classes

### ISSUE THREAD

**Issue by garlandcrow** [sveltejs/language-tools#1376]
So I have a working version of this by adding `prettier-plugin-tailwindcss` as a dep to the `svelte-vscode` package and then looking for a `tailwind.config.js` file in the VSCode workspace when formatting a svelte file to selectively use either the `prettier-plugin-tailwindcss` or `prettier-plugin-svelte` to format. I am not sure what the desired solution is by the community/maintainers. But I can submit a PR if this sounds like what people want.

**Comment by garlandcrow** [comment]
I guess there also should be an opt-in setting for this since some tailwind users probably don't want the formatting.

**Comment by ambiguous48** [comment]
Relevant:
> https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/31
We've bundled the `prettier-plugin-svelte` directly into `prettier-plugin-tailwindcss`, so if you'd like to use this plugin with Svelte, just uninstall `prettier-plugin-svelte` and everything should work as expected.

That's what I did and now `svelte.svelte-vscode` is also successfully sorting my css classes.

**Comment by dummdidumm** [comment]
Closing this. As pointed out in the comment above, Tailwind bundles this Svelte plugin, so use the Tailwind plugin instead. Tell VS Code to format Svelte files with the Prettier extension (install it if you haven't), and then npm install the Tailwind plugin into your node_modules instead of the Svelte plugin.

**Comment by beeb** [comment]
For anyone stumbling upon this, here is what I had to do to make it work (using pnpm but not sure if relevant).

1. In project devDependencies, add both `prettier-plugin-svelte` and `prettier-plugin-tailwindcss`
2. In `.prettierrc`, have this, but no `plugins` key (autoload should work):

```json
{
	"pluginSearchDirs": ["."],
	"overrides": [{ "files": "*.svelte", "options": { "parser": "svelte" } }],
}
```
3. In VSCode settings:

```json
{
    "[svelte]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
     },
    "prettier.documentSelectors": ["**/*.svelte"]
}
```

**Comment by tobiaswutz** [comment]
not working for me :/

**Comment by Dibbyo456** [comment]
> For anyone stumbling upon this, here is what I had to do to make it work (using pnpm but not sure if relevant).
> 
>     1. In project devDependencies, add both `prettier-plugin-svelte` and `prettier-plugin-tailwindcss`
> 
>     2. In `.prettierrc`, have this, but no `plugins` key (autoload should work):
> 
> 
> ```json
> {
> 	"pluginSearchDirs": ["."],
> 	"overrides": [{ "files": "*.svelte", "options": { "parser": "svelte" } }],
> }
> ```
> 
>     3. In VSCode settings:
> 
> 
> ```json
> {
>     "[svelte]": {
>         "editor.defaultFormatter": "esbenp.prettier-vscode"
>      },
>     "prettier.documentSelectors": ["**/*.svelte"]
> }
> ```

It worked but I had to reload window.

**Comment by beeb** [comment]
> not working for me :/

You might want to try disabling the pluginSearchDirs and specifying both plugins manually, with tailwind coming last:
https://github.com/tailwindlabs/prettier-plugin-tailwindcss#compatibility-with-other-prettier-plugins

**Comment by shamscorner** [comment]
> For anyone stumbling upon this, here is what I had to do to make it work (using pnpm but not sure if relevant).
> 
> 1. In project devDependencies, add both `prettier-plugin-svelte` and `prettier-plugin-tailwindcss`
> 2. In `.prettierrc`, have this, but no `plugins` key (autoload should work):
> 
> ```json
> {
> 	"pluginSearchDirs": ["."],
> 	"overrides": [{ "files": "*.svelte", "options": { "parser": "svelte" } }],
> }
> ```
> 
> 3. In VSCode settings:
> 
> ```json
> {
>     "[svelte]": {
>         "editor.defaultFormatter": "esbenp.prettier-vscode"
>      },
>     "prettier.documentSelectors": ["**/*.svelte"]
> }
> ```

Only adding the vscode settings should solve the issue. No need to remove the `plugins` array and the `pluginSearchDirs`.

Here is my `.prettierrc` according to Tailwind Docs:

```json
{
	"useTabs": true,
	"singleQuote": true,
	"trailingComma": "none",
	"printWidth": 80,
	"plugins": ["prettier-plugin-svelte", "prettier-plugin-tailwindcss"],
	"pluginSearchDirs": false,
	"overrides": [{ "files": "*.svelte", "options": { "parser": "svelte" } }]
}
```

Here are my full vscode settings under `.vscode/settings.json` project folder:

```json
{
	"editor.formatOnSave": true,
	"editor.defaultFormatter": "esbenp.prettier-vscode",
	"[svelte]": {
		"editor.defaultFormatter": "esbenp.prettier-vscode"
	},
	"prettier.documentSelectors": ["**/*.svelte"],
	"eslint.validate": ["javascript", "typescript", "svelte"],
	"files.associations": {
		"*.css": "tailwindcss"
	},
	"editor.quickSuggestions": {
		"strings": true
	}
}
```

**Comment by opensas** [comment]
I guess I must be missing something rather obvious, but I'm following the docs and I can get ti to work

I created this question at [SO](https://stackoverflow.com/questions/76460716/how-to-use-prettier-plugin-svelte-with-prettier-plugin-tailwindcss?noredirect=1#comment134819763_76460716) with the detailed steps, but basically I cannot get prettier to format svelte files, I get a  I get a "Extension 'Prettier - Code Formatter' is configured as formatter but it cannot format 'Svelte' files` error

And If I use the `svelte.svelte-vscode` as formatter classes don't get sorted.

I created this repo for testing, you can open it with pgitpod](https://gitpod.io/#https://github.com/opensas/svelte-prettier-tailwindcss), just open `src/routes/+page.svelte`, press F1, type `format document` and you'll get:

![image](https://github.com/sveltejs/language-tools/assets/481687/f4253da3-5465-419e-8cae-af0923538b95)

**Comment by opensas** [comment]
btw, I just noticed that vscode reports the following:

```shell
["INFO" - 12:25:46 AM] Extension Name: esbenp.prettier-vscode.
["INFO" - 12:25:46 AM] Extension Version: 9.13.0.
["INFO" - 12:25:46 AM] Attempted to determine module path from package.json
["ERROR" - 12:25:46 AM] Failed to load module. If you have prettier or plugins referenced in package.json, ensure you have run `npm install`
["ERROR" - 12:25:46 AM] Cannot read properties of undefined (reading 'uid')
TypeError: Cannot read properties of undefined (reading 'uid')
	at Object.statSync (/ide/node_modules/graceful-fs/polyfills.js:313:17)
	at p (/workspace/.vscode-remote/extensions/esbenp.prettier-vscode-9.13.0-universal/dist/extension.js:1:35221)
	at L (/workspace/.vscode-remote/extensions/esbenp.prettier-vscode-9.13.0-universal/dist/extension.js:1:37052)
	at /workspace/.vscode-remote/extensions/esbenp.prettier-vscode-9.13.0-universal/dist/extension.js:1:36677
	at Function.e.exports [as sync] (/workspace/.vscode-remote/extensions/esbenp.prettier-vscode-9.13.0-universal/dist/extension.js:1:36723)
	at t.ModuleResolver.findPkg (/workspace/.vscode-remote/extensions/esbenp.prettier-vscode-9.13.0-universal/dist/extension.js:1:7297)
	at t.ModuleResolver.getPrettierInstance (/workspace/.vscode-remote/extensions/esbenp.prettier-vscode-9.13.0-universal/dist/extension.js:1:3251)
	at t.default.handleActiveTextEditorChanged (/workspace/.vscode-remote/extensions/esbenp.prettier-vscode-9.13.0-universal/dist/extension.js:1:9781)
	at t.default.handleActiveTextEditorChangedSync (/workspace/.vscode-remote/extensions/esbenp.prettier-vscode-9.13.0-universal/dist/extension.js:1:9383)
	at t.default.registerDisposables (/workspace/.vscode-remote/extensions/esbenp.prettier-vscode-9.13.0-universal/dist/extension.js:1:12226)
	at /workspace/.vscode-remote/extensions/esbenp.prettier-vscode-9.13.0-universal/dist/extension.js:1:77896
```

**Comment by dimitri-vs** [comment]
This is closed but figured I would share what ended up working for me.

The svelte plugin was seemingly working and the tailwindcss plugin was also working on .html files, but not on .svelte files.

I was able to finally get the classes to sort with the setup below and testing using the `npx prettier --write "./src/lib/test.svelte"` command.

In `package.json` > `devDependencies` I have:
```
    "prettier": "2.8.8",
    "prettier-plugin-svelte": "2.10.1",
    "prettier-plugin-tailwindcss": "0.4.0",
```

In `.prettierrc.cjs` I have:
```
module.exports = {
    // ...
    plugins: [
        require('prettier-plugin-svelte'),
        require('prettier-plugin-tailwindcss')
    ],
    overrides: [{ files: '*.svelte', options: { parser: 'svelte' } }],
};
```

For `settings.json` I didn't have to change anything.

**Comment by Ryazbeck** [comment]
Here's how I got it to work with svelte and typescript

```
npm i --dev prettier@^3.1.0 eslint@^8.52.0 prettier-eslint@^16.1.2 @typescript-eslint/parser@^5.0.1 typescript@^4.4.4
```

`.prettier.rc`:
```
  "plugins": [
    "prettier-plugin-svelte",
    "prettier-plugin-organize-imports",
    "prettier-plugin-tailwindcss"
  ],
```

`settings.json`:
```
{
  "[svelte]": {
    "editor.defaultFormatter": "svelte.svelte-vscode"
  },
  "editor.formatOnSave": true,
  "svelte.enable-ts-plugin": true
}
```
