### ISSUE TITLE
Error Install or Update :  Corrupt ZIP,...., record signature not found

### ISSUE THREAD

**Issue by kadevland** [sveltejs/language-tools#1383]
When i try to update or install plugin i have 

[error] Corrupt ZIP: end of central directory record signature not found: Invalid: Corrupt ZIP: end of central directory record signature not found

**Comment by kadevland** [comment]
Plugin for vscode
https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode 
link to plugin itself
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/svelte/vsextensions/svelte-vscode/105.11.4/vspackage

**Comment by dummdidumm** [comment]
I can't reproduce it, installing it works for me. This sounds like a problem with VS Code. We had several hickups with it after publishing recently, wondering what's this about.

**Comment by dummdidumm** [comment]
We released a new version, does the error persist with that new version?

**Comment by dummdidumm** [comment]
Closing due to no response, not reproducible.

**Comment by Jay-Hombal** [comment]
Corrupt ZIP: end of central directory record signature not found: Invalid: Corrupt ZIP: end of central directory record signature not found

I got the same issue today running 1.72 vscode
