### ISSUE TITLE
VS Code falsely highlighting the global attribute as an error

### ISSUE THREAD

**Issue by gurbindersingh** [sveltejs/language-tools#1386]
**Describe the bug**
VS Code shows a `Property 'global' does not exist on type 'HTMLProps<HTMLStyleElement>'` error when there is not whitespace between the opening and closing `style` tag.

**To Reproduce**
Add `<style global></style>` to a Svelte component.

**Expected behavior**
For the error not to occur.

**Screenshots**
No whitespace:
![image](https://user-images.githubusercontent.com/26441580/153714993-ad4d9b1d-e3aa-4799-82e1-8150af807ce9.png)

With a space:
![image](https://user-images.githubusercontent.com/26441580/153714998-09dd7f97-d3b8-401e-9bc0-86216ad5a7e1.png)

With a newline
![image](https://user-images.githubusercontent.com/26441580/153715001-60d79591-52cf-4636-8121-7ff7084c23c3.png)

**System (please complete the following information):**
 - OS: Windows 10
 - IDE: VS Code

```
Version: 1.64.2 (user setup)
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:28.252Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
```

 - Plugin/Package:
```
Name: Svelte for VS Code
Id: svelte.svelte-vscode
Description: Svelte language support for VS Code
Version: 105.11.4
Publisher: Svelte
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode
```

**Comment by dummdidumm** [comment]
This is fixed in the experimental new transformation. See https://github.com/sveltejs/language-tools/issues/1352 for more info on how to enable it. And if you have other feedback with the transformation please post in https://github.com/sveltejs/language-tools/issues/1352.
