### ISSUE TITLE
Typescript: Allow setting not inferable generic type parameters

### ISSUE THREAD

**Issue by r-Larch** [sveltejs/language-tools#1389]
## **Is your feature request related to a problem? Please describe.**
Imagine you have a component where at least one generic type parameter can not be inferred from $$props.

Example of failing type inference:
> type `T` of `MyList<T>` can not be inferred correctly
> because of that properties `foo` and `bar` show some error: `Property 'foo' does not exist on type 'unknown'.`
```html
// App.svelte
<script lang="ts">
  import List, { MyList } from "./List.svelte";

  class MyType {
    constructor(public foo: number, public bar: string) {}
  }

  const list = new MyList<MyType>();
  list.array.push(new MyType(1, "A"));
  list.array.push(new MyType(2, "B"));
  list.array.push(new MyType(3, "C"));
</script>

<List {list} let:item>
  foo:{item.foo} bar:{item.bar}
             ^ Property 'foo' does not exist on type 'unknown'.
</List>
```

```html
// List.svelte
<script lang="ts" context="module">
  export class MyList<T = any> {
    array: T[] = [];
  }
</script>

<script lang="ts">
  type T = $$Generic;
  type TList = $$Generic<MyList<T>>;

  export let list: TList;
</script>

<div class="my-list">
  {#each list.array as item}
    <div class="my-item">
      <slot {item} />
    </div>
  {/each}
</div>
```

## **Describe the solution you'd like**
I would like to be able to explicitly set generic type parameters to the desired type.

Example of explicitly setting a generic type
> type `T` of `<List {list}>` can not be inferred correctly
> so it should be possible to add `T={MyType}` to provide the missing type information
```diff
// App.svelte
<script lang="ts">
  import List, { MyList } from "./List.svelte";

  class MyType {
    constructor(public foo: number, public bar: string) {}
  }

  const list = new MyList<MyType>();
  list.array.push(new MyType(1, "A"));
  list.array.push(new MyType(2, "B"));
  list.array.push(new MyType(3, "C"));
</script>

-<List {list} let:item>
+<List {list} T={MyType} let:item>
  foo:{item.foo} bar:{item.bar}
             ^ Property 'foo' does not exist on type 'unknown'.
</List>
```

# **Additional context**
I was able to archive the desired functionality by doing the following:
1. Adding a property to `List.svelte` with name `T` and type `new (...args) => T` _(constructor of type T)_
2. Setting the new property to the constructor of my type, eg. `T={MyType}`

**Example (works partially):**

```html
// App.svelte
<script lang="ts">
  import List, { MyList } from "./List.svelte";

  class MyType {
    constructor(public foo: number, public bar: string) {}
  }

  const list = new MyList<MyType>();
  list.array.push(new MyType(1, "A"));
  list.array.push(new MyType(2, "B"));
  list.array.push(new MyType(3, "C"));
</script>

<List {list} T={MyType} let:item>
  foo:{item.foo} bar:{item.bar}
</List>
```

```html
// List.svelte
<script lang="ts" context="module">
  export class MyList<T = any> {
    array: T[] = [];
  }
</script>

<script lang="ts">
  type T = $$Generic;
  type TList = $$Generic<MyList<T>>;

  export let list: TList;

  // used to supply a generic type argument
  export const T: new (...args) => T = null;
</script>

<div class="my-list">
  {#each list.array as item}
    <div class="my-item">
      <slot {item} />
    </div>
  {/each}
</div>
```

This works as long as type `T` has a constructor. 
If type `T` is an interface type or some other generic type composition, 
then my solution fails.

**Example:**
1. Define MyType as `interface MyType { foo: number; bar: string; }`:
2. You get the following: `'MyType' only refers to a type, but is being used as a value here.`

**Comment by dummdidumm** [comment]
The following will make it work:

```svelte
<script lang="ts">
  type List = $$Generic<MyList<any>>;
  type Item = $$Generic<List extends MyList<infer T> ? T : never>;
  interface $$Slots {
    default: { item: Item }
  }
  // ..
</script>
```
This feels a little backwards at first but you would have to do the same with "regular" TypeScript function generics in order to make TypeScript correctly infer the type.

Since there's a solution to this problem, I don't think that this feature is necessary. It would also be against the convention that TypeScript syntax is purely additive and restricted to script contents (and possibly mustache tags later on).

**Comment by r-Larch** [comment]
Hi @dummdidumm,

thanks for the reply.
This solves the issue.

**Comment by r-Larch** [comment]
Are there any specific docs about typescript generics in svelte?
The only documentation I found was this [RFC - TypeScript: Typing Props/Events/Slots + Generics](https://github.com/dummdidumm/rfcs/blob/ts-typedefs-within-svelte-components/text/ts-typing-props-slots-events.md)

I ask because I would be open to adding the solution to any documentation.

**Comment by dummdidumm** [comment]
Right now there isn't. Since this is still experimental and since there's no place on the official Svelte docs to put such things yet, I'd rather not document it yet. Once the RFC is accepted and stable, docs will surely be added, and things like this should be in there.
