### ISSUE TITLE
Extension error when using PostCSS in a parent/child project structure

### ISSUE THREAD

**Issue by chrislentz** [sveltejs/language-tools#1394]
**Describe the bug**
In my project, I open VS Code at the project root, but then have a sub-folder for my Golang API (./core) and another sub-folder for my Svelte Kit web interface (./wi). I have been trying to get Tailwind CSS working and have followed the Svelte Preprocessor documentation. 

In the "VS Code > Output > Svelte" tab, I am getting the following error anytime I try to use `<style lang="postcss">`: `Cannot read property 'config' of undefined`. The project compiles fine but the extension output shows the error.

I suspect it is something related to the fact that I open VS Code in a parent directory to my Svelte project.

**To Reproduce**
I have setup a bare bones example project that reproduces this error: https://github.com/chrislentz/svelte-tailwind-example

**Expected behavior**
I would expect my `<style lang="postcss">` to be able to handle standard Tailwind CSS syntax like `@apply md:text-green-800;`.

**Screenshots**
<img width="774" alt="CleanShot 2022-02-19 at 21 56 27@2x" src="https://user-images.githubusercontent.com/428312/154826578-665fc0b0-b6e3-4d92-9f50-2eb40f1c0a4d.png">

**System (please complete the following information):**
 - OS: macOS 12.1
 - IDE: VS Code
 - Plugin/Package: "dbaeumer.vscode-eslint", "esbenp.prettier-vscode", "bradlc.vscode-tailwindcss", "svelte.svelte-vscode"

**Comment by jasonlyu123** [comment]
Solved in the discord thread. Sum up for someone from the future:
1. The postcss `configFilePath`  should be resolved to an absolute path. 
2. Tailwindcss only loads the config with relative path. So it also has to be explicitly specified in the postcss config.
```ts
const autoprefixer = require('autoprefixer')
const path = require('path')
const tailwindcss = require('tailwindcss')

module.exports = {
  plugins: [
    tailwindcss(path.resolve(__dirname, './postcss.config.cjs')),
    autoprefixer
  ]
}
```
3. There is a syntax error in the style tag.
 
 The problem with 1 and 2 is that extension and the build is in a different `process.cwd`

**Comment by chrislentz** [comment]
@jasonlyu123 Thank you again for your help. Just to confirm, 1 and 3 are non-issues related to this thread.

For 1, the `configFilePath` relative path I feature in the example project works. but it does work with the absolute path as well. 

For 3, the syntax error was resolved prior to this thread.

Just wanted to clarify as to not confuse future viewers. The only necessary fix was 2, which I reflected in my example project here: https://github.com/chrislentz/svelte-tailwind-example/commit/a1a96704a6023b9b48ad20743324bfe106edbda5

**Comment by chrislentz** [comment]
@jasonlyu123 I also wanted to clarify that there is a typo in the syntax above under #2. You are linking the `postcss.config.cjs` to itself. It should be `tailwind.config.cjs`.

```js
const autoprefixer = require('autoprefixer')
const path = require('path')
const tailwindcss = require('tailwindcss')

module.exports = {
  plugins: [
    tailwindcss(path.resolve(__dirname, './tailwind.config.cjs')),
    autoprefixer
  ]
}
```
