### ISSUE TITLE
Comment and Uncomment shortcut no longer work in Script Tags in VS Code

### ISSUE THREAD

**Issue by kwangure** [sveltejs/language-tools#1397]
**Describe the bug**
The shortcuts `Ctrl+K Ctrl+C` and `Ctrl+K Ctrl+U` which are tied to the commands  "Add Line Comment" and "Remove Line Comment" respectively do not work within the `<script></script>` tags in Svelte files. They comment in/out lines fine within the markup and style sections.

**To Reproduce**
Press the chord `Ctrl+K Ctrl+U` while the cursor is focused in the script tag of a file. The shortcut hint section at the bottom of VS Code shows "'`Ctrl+K Ctrl+U`' is not a command". The same command works fine in the markup and style sections of a Svelte file.

**System (please complete the following information):**
 - OS:  Windows
 - IDE: VSCode
 - Plugin/Package: "Svelte for VSCode"

**Additional context**
I was unable to uncomment a large block I commented a few days ago which leads me to think the bug was introduced recently.

**Comment by jasonlyu123** [comment]
I don't think there're changes related to this. And I can use the comment shortcut without a problem. Can you provide a reproducible where it doesn't work as expected? As code text or a repository instead of screenshot Thanks

**Comment by kwangure** [comment]
Interesting. It seems to work fine for all but one specific file. It fails even when I move to clean copy of VS Code with only Svelte for VS Code and default settings/keybindings. Either way, seems like a non-critical edge case. Not worth the time. 👀 Closing.
