### ISSUE TITLE
Unable to declare non-function class members in TypeScript

### ISSUE THREAD

**Issue by jtlapp** [sveltejs/language-tools#1398]
**Describe the bug**
It appears that classes cannot declare non-function members within .svelte files.

**To Reproduce**

VSCode shows a red squiggle under the `r` in `member`:

```ts
<script lang="ts" context="module">
  export class Foo {
    member: string; // (property) Foo.member: string \n Unexpected token

    constructor() {
      this.member = 'foo';
    }
  }
</script>
```

The problem also occurs without `context="module"` and exporting the class.

I also get this error in rollup:

```
rollup v2.64.0
bundles src/frontend/main.ts → public/build/bundle.js...
[!] (plugin svelte) ParseError: Unexpected token
src/frontend/api/app_event_api.svelte
1: <script lang="ts" context="module">export class Foo {
2:     member;
             ^
```

I've written thousands of lines of TypeScript in svelte, but this is the first time I attempted to do this. Most of my classes are in .ts files. I can't move the class I need to a .ts file because it must import from .svelte components in a way that won't get pulled in when using `import type`. (Update: I resolved the unrelated `import type` issue by creating a `.d.ts` file with `declare module '*.svelte'`.)

UPDATE: I'm working around the problem by using module-scoped variables.

**System (please complete the following information):**
 - OS: MacOS 10.15.5
 - IDE: VSCode
 - Plugin/Package: @rollup/plugin-typescript, but VSCode reports the error too

**Comment by dummdidumm** [comment]
I can't reproduce this given the code snippet. Can you give more details on your setup, ideally a minimum reproduction repo?

**Comment by jtlapp** [comment]
Okay, I can't get to this right away, but if you'd like to do some spot checks:

- Here's [the repo in which this is happening](https://github.com/ut-entomology/spectool) (it's built with Electron)
- Here's [the svelte/frontend portion of this repo](https://github.com/ut-entomology/spectool/tree/main/src/frontend) (with its own config)
- Here's [the svelte file that emitted this error](https://github.com/ut-entomology/spectool/blob/main/src/frontend/api/app_event_api.svelte)

**Comment by jasonlyu123** [comment]
The is because typescript transpile the class field to es2022 class field if you set the target to esnext or es2022. And the class field is not supported by the svelte complier. See https://github.com/sveltejs/svelte/issues/6900

**Comment by jtlapp** [comment]
@jasonlyu123, thanks for saving me the effort of having to find a minimal reproducible repo. Changing the target to ES2021 does indeed solve the problem for me.

It's not clear to me whether this is a typescript tooling problem or a svelte problem. In any case, I'm closing this issue because it's already logged in the svelte repo. Feel free to reopen if you feel it belongs here.
