### ISSUE TITLE
svelteIndentScriptAndStyle setting not honored

### ISSUE THREAD

**Issue by thdoan** [sveltejs/language-tools#1400]
**Describe the bug**
I have `"svelte.plugin.svelte.format.config.svelteIndentScriptAndStyle": false,` and no `.prettierrc` file in my project, but when I select "Format Document" the code inside `<script>` is still indented.

**To Reproduce**
1. Set `svelteIndentScriptAndStyle` to false (uncheck option)
2. Add something like this inside a .svelte file:
```
<script>
let a;
</script>
```
3. Open Command Palette and select "Format Document"

**Expected behavior**
Text inside `<script>` should not be indented.

**System (please complete the following information):**
 - OS: Windows
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode

**Comment by jasonlyu123** [comment]
A prettier config file could be in [other forms](https://prettier.io/docs/en/configuration.html) too. Could you check if you have it in other forms? If not, please provide a reproducible repository. I can't reproduce it with the step you provide.
