### ISSUE TITLE
Better props type checking when using `$$props`

### ISSUE THREAD

**Issue by WilHall** [sveltejs/language-tools#1403]
**Describe the bug**
When passing an undefined prop to a Svelte component which internally references `$$props`, no type error is reported by `svelte-check` for the passing of the undefined prop.

**To Reproduce**

`TestComponent.svelte`:
```svelte
<script lang="ts">
  export let text: string
</script>

<p class={$$props.class}>{text}</p>
```

`TestPage.svelte`:
```svelte
<script lang="ts">
  import TestComponent from "./TestComponent.svelte"
</script>

<TestComponent text="Content" thisPropDoesNotExist="Thing" />
```

`svelte-check` reports:
```
svelte-check found 0 errors, 0 warnings, and 0 hints
```

**Expected behavior**

I would expect the behavior to be the same as in the following example where `TestComponent.svelte` does not reference `$$props`:

`TestComponent.svelte`:
```svelte
<script lang="ts">
  export let text: string
</script>

<p>{text}</p>
```

`TestPage.svelte`:
```svelte
<script lang="ts">
  import TestComponent from "./TestComponent.svelte"
</script>

<TestComponent text="Content" thisPropDoesNotExist="Thing" />
```

`svelte-check` reports:
```
TestPage.svelte:5:31
Error: Type '{ text: string; thisPropDoesNotExist: string; }' is not assignable to type 'IntrinsicAttributes & { text: string; }'.
  Property 'thisPropDoesNotExist' does not exist on type 'IntrinsicAttributes & { text: string; }'. (ts)

<TestComponent text="Content" thisPropDoesNotExist="Thing"/>


====================================
svelte-check found 1 error, 0 warnings, and 0 hints
error Command failed with exit code 1.
```

**Screenshots**
If applicable, add screenshots to help explain your problem. We prefer copy-pasteable code snippets over screenshots of code snippets.

**System (please complete the following information):**
 - OS: macOS 12.2
 - IDE: vim 8.2
 - Plugin/Package: `svelte-check@2.4.5`

**Comment by dummdidumm** [comment]
Using `$$props` in your code means that you "expect the unexpected", or rather, you are ok with accepting props besides the ones explicitly defined. In your specific case we maybe could determine that there's no possible prop besides text and class, but this can't be determined for other cases in a reliable way - so right now using `$$props` loosens type checking so that anything's accepted.

**Comment by WilHall** [comment]
@dummdidumm

> so right now using $$props loosens type checking so that anything's accepted.

I thought something like that might have been the case. Makes sense!

I was surprised by the behavior initially and didn't see any mention of it in docs or existing issues, so figured it was worth raising.

Thanks for the response 🙂 I agree it would make a nice enhancement for simple cases like in my example to be able to determine what is used from `$$props`.

**Comment by ivanhofer** [comment]
@WilHall you could use the experimental `$$Props` feature gain back typesafety:
https://github.com/ivanhofer/sveltekit-typescript-showcase/blob/main/src/01-props/06-%24%24Props/Component.svelte

**Comment by dummdidumm** [comment]
Closing since Svelte 5 removes `$$props` etc with the `$props()` rune which allows for more explicit control over these situations
