### ISSUE TITLE
Disable hint/warnings in ts files

### ISSUE THREAD

**Issue by mar-sousa** [sveltejs/language-tools#1406]
**Is your feature request related to a problem? Please describe.**
It is frustrating that we cannot ignore specific hints or warnings for .ts files when using --tsconfig 

**Describe the solution you'd like**
I think it would be very useful to have something like /* tslint:disable */ or // tslint:disable-next-line for warnings and hints

**Comment by dummdidumm** [comment]
Which hints/warnings are you talking about, and where in the code (script, markup) do they appear? Could you give an example?

**Comment by mar-sousa** [comment]
When I run svelte-check with --tsconfig I get an hint.
Hint: This constructor function may be converted to a class declaration. 
            var MyError = (function() {
                function MyError(message) {
                    if (this instanceof MyError) {

I would like to mute it, like when we use // tslint:disable-next-line. Unfortunately, I cannot change this part of the code

**Comment by dummdidumm** [comment]
You can tell `svelte-check` the threshold for messages: `--threshold warning` will not show hints, `--threshold error` will also not show warnings.
