### ISSUE TITLE
Can't find stylesheet to import when using prependData

### ISSUE THREAD

**Issue by MoritzKronberger** [sveltejs/language-tools#1409]
**Describe the bug**
When adding a `main.scss` stylesheet to all components using `prependData` in a Vite + Svelte project, Svelte for Vscode shows `Error: Can't find stylesheet to import.` for all `<style lang="scss">` tags, although the stylesheet is found and loaded correctly when building the app.

**To Reproduce**
The `prependData` was added both in `svelte.config.js` and `vite.config.ts`:

```js
// svelte.config.js
import sveltePreprocess from 'svelte-preprocess'

const preprocess = {
  scss: {
    prependData: '@use "src/assets/css/main" as *;',
  },
}

export default {
  preprocess: sveltePreprocess(preprocess)
}
```

```js
// vite.config.ts
import { defineConfig } from 'vite'
import { svelte } from '@sveltejs/vite-plugin-svelte'
import sveltePreprocess from 'svelte-preprocess'

const preprocess = {
  scss: {
    prependData: '@use "src/assets/css/main" as *;',
  },
}

export default defineConfig({
  plugins: [svelte({preprocess: sveltePreprocess(preprocess)})]
})
```
In a component this will result in `Error: Can't find stylesheet to import.` on the style tag:
```svelte
<style lang="scss">
  // mixin font is defined in src/assets/css/_main.scss
  .login-form h1 {
    @include font(main, large);
  }
</style>
```
If the preprocess is removed from `svelte.config.js` the app still compiles correctly and the error changes to `Undefined mixin.` in the component.

**Expected behavior**
When a scss stylesheet is added using prependData it should be recognized by Svelte for Vscode.

**System (please complete the following information):**
 - OS:  Windows
 - IDE: VSCode, Atom
 - Plugin: "Svelte for VSCode"

**Comment by jasonlyu123** [comment]
This sounds like the `src/assets/css/_main.scss` could not be found in the current directory of the language server. If your svelte project isn't in the vscode workspace root. You need to do some adjustments as the language server is running in a different `process.cwd`. If this isn't the case, Please provide a reproducible in a repository form.

**Comment by MoritzKronberger** [comment]
Thanks a lot, opening the svelte project in the workspace root solved the problem.

**Comment by ktjd123** [comment]
@jasonlyu123 Hi, What adjustment can I make to not open as project root and make this work?

since I'm using another backend for my project, project folder is $root/frontend (svelte). And I'd like to look at both backend and frontend code at the same time.

looking at settings of vscode's extensions seems it doesn't have options for that and when running npm run build for svelte, no error or warning comes out for this problem.

Thank you.

**Comment by jasonlyu123** [comment]
Something similar to path handling here: https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/scss-less.md#scss-cant-find-stylesheet-when-using-prependdata. Replace the preprocess config with what you're using

**Comment by ktjd123** [comment]
Thank you for your kind reply.

I'm using vite for my scss import. 

So I changed `vite.config.ts` as said in the link.

```
import { sveltekit } from "@sveltejs/kit/vite";
import { defineConfig } from "vite";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

export default defineConfig({
	plugins: [sveltekit()],
	css: {
		preprocessorOptions: {
			scss: {
				additionalData: `@import '${join(
					__dirname,
					"src/styles/utils.scss"
				).replace(/\\/g, "/")}';`,
			},
		},
	},
});
```

The `utils.scss` seems to be successfully imported at scss, svelte file but vscode(extension) gives me error, 

```
Error in referenced file

Error: Undefined mixin.
  ╷
5 │         @include color();
  │         ^^^^^^^^^^^^^^^^
  ╵
  frontend/src/routes/+page.svelte.vite-preprocess.scss 5:3  root stylesheetsvelte(style)
```
.

But svelte build works fine and when running as dev, when I check from browser, everything works fine.

Let me know if I should open a separate issue with this.

Thank you.
