### ISSUE TITLE
Improved support for VSCode #region code folding in html sections

### ISSUE THREAD

**Issue by axwalker** [sveltejs/language-tools#1411]
**Is your feature request related to a problem? Please describe.**
[Region folding was added](https://github.com/sveltejs/language-tools/commit/ec47e72bbaa7e776e23a73775a2622b0f7f26931) for Svelte files but from what I can tell it only works for JS comments, eg `//#region`. This works fine within the `<script>` tag but is problematic within the html section of a Svelte component. You can still use `//#region` there but then that actually gets rendered in your HTML because it's not an HTML comment.

**Describe the solution you'd like**
Also support regions defined with html comments: eg `<!--#region-->`/`<!--#endregion-->`

**Additional context**
Related closed issue: #525

**Comment by dummdidumm** [comment]
Seems vs code implemented it for html in this commit https://github.com/microsoft/vscode/commit/4f9f4ebb9f092a74f453e3873f4e338f861ed25d, maybe we can do something similar
