### ISSUE TITLE
Missing video element attribute "disableRemotePlayback"

### ISSUE THREAD

**Issue by Mon0Man** [sveltejs/language-tools#1414]
"disableRemotePlayback" attribute for video element is missing, https://docs.w3cub.com/html/element/video#attr-disableremoteplayback

![158677547-f94f1c00-e4a9-423b-8783-f838f6488e3f](https://user-images.githubusercontent.com/86112502/158717638-e462377d-3299-44df-bcfb-373b2c368951.png)

**Comment by jasonlyu123** [comment]
This is an experimental attribute according to the [mdn](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#attr-disableremoteplayback) and it's not present on the [spec](https://html.spec.whatwg.org/multipage/media.html#the-video-element). So I think we won't add this until it's more standard. You can however enhance the typings yourself, read more here: https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/typescript.md#im-using-an-attributeevent-on-a-dom-element-and-it-throws-a-type-error
