### ISSUE TITLE
Type 'boolean' is not assignable to type 'false'.

### ISSUE THREAD

**Issue by zwergius** [sveltejs/language-tools#1421]
In a component I declare a pros as follows:
` 
export let disabled = false
`

I would expect the type to be "trivially inferred" from boolean

svelte-check flags this as an error:
Type 'boolean' is not assignable to type 'false'.

Error goes away if I explicitly do:

` 
export let disabled: boolean = false
`

**Comment by dummdidumm** [comment]
Which version of `svelte-check` are you using? I cannot reproduce this using the latest version.

**Comment by zwergius** [comment]
Hey,

I was sure I was on latest as I had just updated all deps, but turns out I was on a wrong branch.

Sorry about that!
