### ISSUE TITLE
Tool for creating svelte file extension 

### ISSUE THREAD

**Issue by Jojoshua** [sveltejs/language-tools#1426]
The svelte file extension is long, hard to spell, and requires thinking. 

Would there be room for the official plugin to implement a shortcut to create a svelte file and perhaps even with options like a predefined template (such as set lang if using typescript)?

**Comment by jasonlyu123** [comment]
Don't know if this fits into the official extension. It's hard to create a very customizable feature that makes everyone happy as everyone has their preference. I think it's more suitable for another extension, or a node.js script that you can also create yourself. The easiest way is to create a file system watcher for your custom file extension, It automatically renames the file extension to `.svelte`. And populate the file with your desired snippet. 

For example, with vscode API, You can listen to `workspace.onDidCreateFiles` and rename the added file with `workspace.appEdit`
https://code.visualstudio.com/api/references/vscode-api#workspace

With node.js you can use `fs.watch` or other popular file watcher library. And use fs.rename and fs.writeFile.

**Comment by Jojoshua** [comment]
Thank you for the insight @jasonlyu123, I will look into that.

**Comment by Jojoshua** [comment]
@jasonlyu123 I just finished creating and publishing this tool. Can pass this along to others who've had the same frustration.

https://marketplace.visualstudio.com/items?itemName=jojoshua.auto-rename-file
