### ISSUE TITLE
The extension doesn't treat <script lang="ts"> like a TypeScript script and throws errors in index.svelte

### ISSUE THREAD

**Issue by len0xx** [sveltejs/language-tools#1430]
Basically, when I have switched my SvelteKit project from JS to TS, I have found a weird bug. Typing works everywhere just fine when I mark the script tag with `lang="ts"` attribute. But in the `index.svelte` it highlights the errors like it is not a TypeScript, but a JS file.
It just doesnt let me do anything related to TS. Says it's not allowed in .js file even though the script is marked with `lang="ts"`
When I run the application itself it throws no error in both the console and the browser. Everything works just fine

**System:**
 - OS: MacOS 12 (ARM version)
 - IDE: VSCode
 - Plugin/Package: "Svelte for VSCode"
 
<img width="514" alt="image" src="https://user-images.githubusercontent.com/21990466/162041615-d438e008-3323-40fa-9e8d-da6b9b638dd6.png">
<img width="755" alt="image" src="https://user-images.githubusercontent.com/21990466/162041660-ea706207-1b2d-4053-b0c3-2a372d37d521.png">

**Comment by jasonlyu123** [comment]
We need more info to be able to help you. Please provide a copied-pasteable reproducible. You can try providing a minimal reproducible by deleting some code and seeing if the problem persists. It's also helpful to check if there are errors logged in the output channel. It's near the integrated terminal, chose svelte in the dropdown.

**Comment by len0xx** [comment]
So I started to create a demo repository and found out the reason why the error showed up.
You can check this repository:
[https://github.com/len0xx/svelte-ext-bug](https://github.com/len0xx/svelte-ext-bug)

I have an `if` statement inside of my svelte file. And if the closing tag has no whitespaces like so: `{/if}` then the extension supposes its a JS file for some reason. But as soon as I put the whitespaces there like this: `{ /if }`, the error disappears and everything is fine.

**Comment by dummdidumm** [comment]
Thanks, can reproduce it. It seems it's due to the if-block, it's written as `{ #if showPreloader }` which for some reason crashes it. If you remove the first space and write `{#if showPreloader }`, it works. Need to investigate why, but it definetly is an edge case.
