### ISSUE TITLE
Sevltekit template doesn't work with this extention

### ISSUE THREAD

**Issue by JeffWScott** [sveltejs/language-tools#1440]
### Describe the bug

![image](https://user-images.githubusercontent.com/4855017/162627594-5622b955-2b34-4966-973e-de74719e3c8c.png)

As you can see from the image I have the Svelte extension installed but it has issues with Svelte syntax.

### Reproduction

install sveltekit template
install VS code
open sveltekit template dir in VScode
open src/lib/Header.svelte

### Expected behaviour

I wouldn't expect any syntax to be error highlighted

### System Info

- OS: OAX
- IDE: VSCode

### Which package is the issue about?

Svelte for VS Code

### Additional Information, eg. Screenshots
I added this to my settings.json.
I have no other Svelte extensions installed

![image](https://user-images.githubusercontent.com/4855017/162627736-1f63ca66-ce56-42e1-8c5f-73e785efb6e0.png)

**Comment by jasonlyu123** [comment]
The version of the extension you are using is pretty old. Make sure you update your VS Code version to at least 1.52.0 to install the latest version of the svelte extension.

**Comment by JeffWScott** [comment]
Troubleshooting

1) Uninstalled Svelte for VS Code
2) Verified no other Svelte Extensions are installed.
3) Disabled all other Extensions
4) Restarted VSCode
5) Reinstalled Svelte for VS Code
6) **Still same issue...**

**Comment by JeffWScott** [comment]
@jasonlyu123 

Good suggestion, but you closed the issue too soon.  

I updated VSCODE and no change.

![image](https://user-images.githubusercontent.com/4855017/162628302-c6e113d0-d443-4801-b1bb-131a1e2f9c0c.png)

**Comment by dummdidumm** [comment]
Which version of vs code did you install? You can see that at help->about AFAIK
