### ISSUE TITLE
Cannot disable svelte-check error

### ISSUE THREAD

**Issue by aklajnert** [sveltejs/language-tools#1454]
### Describe the bug

I'm exporting the package version in vite configuration:
```js
vite: {
  define: {
    __version__: JSON.stringify(process.env.npm_package_version)
  }
}
```

This is later used in the component as below:
```html
<script lang="ts">
	// eslint-disable-next-line no-undef
	const version = __version__;
</script>
<div>{version}</div>
```

ESLint is fine with it, but `svelte-check` complains:
```
Error: Cannot find name '__version__'. (ts)
        // eslint-disable-next-line no-undef
        const version = __version__;
</script>
```

I've tried to put `// svelte-ignore no-undef` (and a bunch of variations), but it doesn't do anything.

### Reproduction

Define a variable in `svelte.config.js`:
```js
vite: {
  define: {
    __version__: JSON.stringify(process.env.npm_package_version)
  }
}
```

Use it in the component as below:
```html
<script lang="ts">
	// eslint-disable-next-line no-undef
	const version = __version__;
</script>
<div>{version}</div>
```

Run `svelte-check`

### Expected behaviour

The most ideal behavior would be to respect ESLint setting so my code wouldn't be littered with except comments. If that's not possible, I'd need a way to turn off the error for this particular line.

### System Info

- OS: MacOS / Linux (docker)
- IDE: PyCharm

### Which package is the issue about?

svelte-check

**Comment by jasonlyu123** [comment]
The error is coming from typescript. You can add this to a `.d.ts` file. And make sure that the file is [included](https://www.typescriptlang.org/tsconfig#include) in your tsconfig.
```ts
declare const __version__: string;
```

**Comment by aklajnert** [comment]
Thanks, it works. But why the `svelte-ignore` comments don't work here?

**Comment by jasonlyu123** [comment]
svelte-ignore comment only disables warnings from the svelte compiler. VSCode would show the diagnostic source after the message. for example svelte(a11y-missing-content). You can distinguish where diagnostic is comping with it.

**Comment by aklajnert** [comment]
Thanks, I think I got it.
