### ISSUE TITLE
help gettting syntax highlight to work in Neovim within script tag for typescript

### ISSUE THREAD

**Issue by drio** [sveltejs/language-tools#1458]
Problem: I am using neovim v0.7.0 and I am trying to get LSP to work for my svelte projects. I follow the instructions in the `server_configurations.txt` docs:

```sh
$ npm install -g svelte-language-server
```
and then from within my neovim config:

```lua 
require'lspconfig'.svelte.setup{}
```
Everything works correctly with the exception of syntax highlighting for typescript within `<script>` tags:

<img width="475" alt="Screen Shot 2022-04-22 at 7 55 02 AM" src="https://user-images.githubusercontent.com/17954/164709596-bee4b37a-3540-4467-8600-1139e2baf66f.png">

I follow the [debugging instructions](https://github.com/neovim/nvim-lspconfig#debugging) from the lsp-config project:

1. `:LspInfo` shows the svelte LSP server has been loaded:

<img width="493" alt="Screen Shot 2022-04-22 at 7 57 56 AM" src="https://user-images.githubusercontent.com/17954/164709960-463eb0aa-5efc-41c1-83fe-b64d99549574.png">

2. I add the debugging options to neovim's lsp client after loading a svelte file with the `<script lang="ts">` on it.

```lua
vim.lsp.set_log_level("debug")
vim.cmd('e'..vim.lsp.get_log_path())
```

3. Then I load the lsp client logs:

```
22248 [START][2022-04-22 07:59:40] LSP logging initiated
22249 [ERROR][2022-04-22 07:59:44] .../vim/lsp/rpc.lua:420>-"rpc">"svelteserver">-"stderr">-"Initialize language server at  file:///Users/drio/dev/github.com/drio/sk-canonical-app\n"
22250 [ERROR][2022-04-22 07:59:44] .../vim/lsp/rpc.lua:420>-"rpc">"svelteserver">-"stderr">-"Initialize new ts service at  /Users/drio/dev/github.com/drio/sk-canonical-app/tsconfig.json\n"
22251 [ERROR][2022-04-22 07:59:44] .../vim/lsp/rpc.lua:420>-"rpc">"svelteserver">-"stderr">-"Trying to load configs for /Users/drio/dev/github.com/drio/sk-canonical-app\n"
22252 [ERROR][2022-04-22 07:59:44] .../vim/lsp/rpc.lua:420>-"rpc">"svelteserver">-"stderr">-"Loaded config at  /Users/drio/dev/github.com/drio/sk-canonical-app/svelte.config.js\n"
22253 [ERROR][2022-04-22 07:59:44] .../vim/lsp/rpc.lua:420>-"rpc">"svelteserver">-"stderr">-"SnapshotManager File Statistics:\nProject files: 6\nSvelte files: 3\nFrom node_modules: 0\nTotal: 6\n"
22254 [ERROR][2022-04-22 07:59:45] .../vim/lsp/rpc.lua:420>-"rpc">"svelteserver">-"stderr">-"Using Svelte v3.47.0 from /Users/drio/dev/github.com/drio/sk-canonical-app/node_modules/svelte/compiler\n"
22255 [ERROR][2022-04-22 07:59:46] .../vim/lsp/rpc.lua:420>-"rpc">"svelteserver">-"stderr">-"Using Svelte v3.47.0 from /Users/drio/dev/github.com/drio/sk-canonical-app/node_modules/svelte/compiler\n"
22256 [ERROR][2022-04-22 07:59:46] .../vim/lsp/rpc.lua:420>-"rpc">"svelteserver">-"stderr">-"Using Svelte v3.47.0 from /Users/drio/dev/github.com/drio/sk-canonical-app/node_modules/svelte/compiler\n"
22257 [ERROR][2022-04-22 07:59:46] .../vim/lsp/rpc.lua:420>-"rpc">"svelteserver">-"stderr">-"Using Svelte v3.47.0 from /Users/drio/dev/github.com/drio/sk-canonical-app/node_modules/svelte/compiler\n"
```

But I don't see anything revealing. Do you have any idea what may be happening here?

Thank you.

**Comment by jasonlyu123** [comment]
LSP doesn't come with syntax highlight. There are only semantic tokens which are aimed to enhance syntax-highlight with typing information. 

You can checkout https://github.com/leafOfTree/vim-svelte-plugin and https://github.com/evanleck/vim-svelte for syntax highlight.

**Comment by acidnik** [comment]
For those who came from google, if you are using `nvim-treesitter` (you most likely are), try this:
```
:TSInstall svelte
:TSInstall typescript
```
