### ISSUE TITLE
Cannot find module '$lib/...' or '$app/...' from language server for .svelte files in default configuration of sveltekit

### ISSUE THREAD

**Issue by groovy9** [sveltejs/language-tools#1459]
### Describe the bug

In a fresh install of sveltekit with demo app and typescript, LSP works fine out of the box except for imports from the $ aliases in .svelte files.  

These throw a diagnostic such as `Cannot find module '$lib/Counter.svelte' or its corresponding type declarations` and jump to definition does not work for those imported symbols.

These diagnostics disappear if I replace $lib or $app with absolute paths and jump to definition starts working.

These diagnostics DO NOT happen in .ts files, where jump to definition works fine for symbols imported from $app, for example (see src/lib/form.ts in the demo app).

### Reproduction

I'm using a fresh install of Node 16.14.2 LTS straight from the node main page tarball.  Fresh global installs of `svelte-language-server`, `typescript-language-server` and `typescript`.  Using the Helix editor which has a native LSP client, using the default config that automatically finds `svelteserver` for `.svelte` files and `typescript-language-server` for `.js` and `.ts` files.  

I set up a new sveltekit project as per instructions on sveltekit main page answering yes for typescript and demo app and no for everything else.  Cd to app dir, `npm install`, `npm run dev -- --open`.  No changes made to anything.

Edit a .svelte file from the app root dir: `hx src/routes/index.svelte`

As soon as the language server loads, LSP features start working fine but it throws a diagnostic for the line `import Counter from '$lib/Counter.svelte';` that reads: `Cannot find module '$lib/Counter.svelte' or its corresponding type declarations` and jump to definition does not work for that symbol (works fine otherwise for everything else in the same file).

The about.svelte page does the same thing for `import { browser, dev } from '$app/env'; `.  

### Expected behaviour

No diagnostic, jump to definition works.

### System Info

- OS: Debian 11
- IDE: Helix

### Which package is the issue about?

language-server

**Comment by groovy9** [comment]
This was either a problem specifically with the demo app or I messed something up myself, as I'm not currently having this bug after starting with a blank sveltekit app.  Closing.

**Comment by SoundAsleep192** [comment]
In your case it was probably just a lag of VSCode
However it can also happen if you didn't have any `$lib` references initially (say you chose barebones instead of demo app at setup). What you would need to do in that case is simply run `npm run prepare` (`yarn prepare`, etc.) so the framework generates aliases automatically. You can see it in file `.svelte-kit/tsconfig.json`

**Comment by khaki32** [comment]
Restarting VSCode worked, nevermind.

**Comment by sliiiced** [comment]
I ran into the same problem using Helix-editor turns out it is because svelte language server could not find the root? of the project.
Two ways to fix it:

`git init` at root of the project, seems **.git** is used to find the root.

The other way:
Set the svelte language roots property to include "package.json"  in `~/.helix/config/languages.toml`, and the problem went away.

`[[language]]`
`name = "svelte"`
`roots = ["package.json"]`

Don't know if helix needs a PR or not.

**Comment by dustincleveland** [comment]
I encountered this issue early on in an empty svelte-kit app. `npm run prepare` just told me that I had a missing script. Instead, I just needed to manually add the following to `.svelte-kit/tsconfig.json`:

```
"paths": {
  "$lib": [
      "src/lib"
  ],
  "$lib/*": [
      "src/lib/*"
  ]
},
```

**Comment by jasonlyu123** [comment]
prepare script has been removed from the template 

https://github.com/sveltejs/kit/blob/master/packages/create-svelte/CHANGELOG.md#200-next152

It would also be generated when you started the dev server. Or you can add the script back just don't name it as `prepare`. it was removed for a reason.

**Comment by ngould** [comment]
I got to the same answer as @dustincleveland, although worth clarifying that `"paths"` needs to be under `compilerOptions`. E.g., 

```
{
  "compilerOptions": {
    ...,
    "paths": {
      "$lib/*": ["src/lib/*"],
      ...
    },
}
```

**Comment by papiro** [comment]
Unfortunately, I'm having the same issue 😿 but all my boxes are checked. `tsconfig` contains the path aliases (auto-generated so no chance of human error). Got the Svelte extension freshly installed. Have restarted VSCode like 10 times :(.
<img width="851" alt="image" src="https://user-images.githubusercontent.com/8143236/185517113-a7202637-2a1b-4700-aeb7-9046a7af54b4.png">

**Comment by jasonlyu123** [comment]
Can you provide a reproduction? We need more info to be able to help you.

**Comment by papiro** [comment]
https://github.com/papiro/svelte-repro

you can see in `routes/+page.svelte` I am trying to import from `$lib/foo` and vscode has no idea what that is.

I've disabled all extensions except for "Svelte for VS Code v105.21.0" and Vim.

using VSCode:
Version: 1.70.2
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:38:59.695Z (2 days ago)
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 20.6.0

**Comment by jasonlyu123** [comment]
Wild guess, did you modify the tsconfig? The `paths` config would override the extended config. svelte kit would warn you if that happens.

**Comment by papiro** [comment]
hehe - just discovered that the root `tsconfig.json` was completely missing. 🤦‍♂️

**Comment by Scouterdev** [comment]
tsconfig.json
and remove **"baseUrl": "./src",**

**Comment by ubay1** [comment]
in svelte.config.js

kit: {
  alias: { 'lib/*': './src/routes/lib/*' }
}

**Comment by SleepingForge** [comment]
Had missing `$lib` in tsconfig.json.
Svelte added everything by itself after I ran `npm run check`.

**Comment by raphaelsiz** [comment]
I tried editing my tsconfig.json, but every time I run `npm run dev` it changes it back to `"paths":{}`. How do I prevent this?

**Comment by graphicagenda** [comment]
> 

same here, trying to figure out how to reintroduce `$lib` alias into a skeleton project

**Comment by nzaero** [comment]
hi
I do not understand anything anymore, I mean, using turborepo, having a ui lib, in a package using $lib, having or not the good config in package.json so I can cmd+click from app source code and go to the lib source code. I mean, where should we config alias, in sveltekit or in tsconfig ? Should I use Vitepreprocess or Svelte-preprocess and why we have anyway a vite.config.js. Does Vite pre-process or pre-bundling takes precessedance over svelte preprocessing ? What is the recomended way to configure ths module and target in tsconfig (esnext, bundler... ?) What is the relation with the "module:" fileld in package.json and the module I configure in tsconfig. Why do we have configuration for eslint with extension eslint.cjs, and some configuration fore vite.config.js and/or vite.config.ts ? At the end, this $lib, I think, we cannot use it in the lib of a ui component, because it is not resolved by the app then... I am using turborepo, everything is 10xspaguetti now

**Comment by nzaero** [comment]
I am sorry for the off topic, but in the same misunderstanding spaguetti stuff beatifull tecnologies offers us, why in a svelte stater lib (npm create svelte@latest my-app), we have a starter and a index.js file in the lib folder saying (// Reexport your entry components here). But there is not an exemple, with at least a component, so the demo goes a little bit forward. But well, at the end, how should I design my lib, does the index.js should be in the lib folder or at the root of the src package, or at the root where package.json stands. I mean I do not understand, why at the end, in the dist folder, the index.js is at the root, there is some magic, maybe done by svelte-package doing that. So first, where should be the recomended location of the index.js exporting all the components ? If I use the starter named with-svelte, of turborepo, there is not a svelte.conf.js or a tsconfig.js file to configure the aliases, so I do not understand that, at the end, we should not configure path aliases in our lib components, is that right ? And finally, I do not get clear what is the pipeline, if I use aliases in tsconfig.js, vite.config.ts and svelte.config.ts. Which are the priorities among them ?

**Comment by rodrigez000** [comment]
I'm trying to npm build a sveltekit website in order to deploy it, but all I get is a dist folder with an empty index.js with the line //Reexport your entry components here. Any suggestions?

**Comment by teixeirah-eth** [comment]
Problem still happening nowadays. I just did a `npm create svelte@latest myapp` choosing a skeleton project with typescript and the $lib folder couldn't be found. I got it working by modifying the following files:
`svelte.config.js`
```js
import adapter from '@sveltejs/adapter-auto';
import { vitePreprocess } from '@sveltejs/kit/vite';

const config = {
	preprocess: vitePreprocess(),
	kit: {
		adapter: adapter(),
            files: {
                lib: './src/routes/lib/'
            }
	}
};
export default config;
```
And `tsconfig.json`:
```js
{
    "extends": "./.svelte-kit/tsconfig.json",
    "compilerOptions": {
         <default options here>
        "paths": {
            "$lib": [
                "./src/routes/lib"
            ],
            "$lib/*": [
                "./src/routes/lib/*"
            ]
        }
    }
}
```

**Comment by JustMrMendez** [comment]
> ```js
> 
> ```

this worked, but my i always have the lib folder inside src/ not in routes thanks

**Comment by mass8326** [comment]
The ambient `$app` module wasn't detecting for me when setting up SvelteKit in a pre-existing Tauri project.

Deleting the `include` setting in my root `tsconfig.json` fixed the problem.

Inheriting from `.svelte-kit/tsconfig.json` as much as possible seems to be what is needed for SvelteKit to work as expected.

If you still want to customize your tsconfig.json:
- `./$types` needs `.svelte-kit/types/**/$types.d.ts` to be in the `include` array
- `$app` needs `vite.config.ts` to be in the `include` array
- `$env` needs `.svelte-kit/ambient.d.ts` to be in the `include` array
- `$lib` needs to be [properly configured](https://www.typescriptlang.org/tsconfig#paths) in your `compilerOptions.paths` setting

**Comment by JoshJarabek7** [comment]
This does not seem to work when using ViteDevServer. Not sure if this is a Vite problem or what. Vite is fine when not using the ViteDevServer, but if it's implemented, it has not idea what "$lib" is.

Anybody have any idea?

**Comment by lewisjr** [comment]
> The ambient `$app` module wasn't detecting for me when setting up SvelteKit in a pre-existing Tauri project.
> 
> Deleting the `include` setting in my root `tsconfig.json` fixed the problem.
> 
> Inheriting from `.svelte-kit/tsconfig.json` as much as possible seems to be what is needed for SvelteKit to work as expected.
> 
> If you still want to customize your tsconfig.json:
> 
> * `./$types` needs `.svelte-kit/types/**/$types.d.ts` to be in the `include` array
> * `$app` needs `vite.config.ts` to be in the `include` array
> * `$env` needs `.svelte-kit/ambient.d.ts` to be in the `include` array
> * `$lib` needs to be [properly configured](https://www.typescriptlang.org/tsconfig#paths) in your `compilerOptions.paths` setting

@mass8326 This saved me, I was losing my mind trying to find the solution to this because I could not find the $app import not showing up and I had indeed copied my `tsconfig.json` from my tauri app.

Can the svelte team please update the docs? The generated comments in `tsconfig.json` from `create svelte` state:

```ts
// Path aliases are handled by https://kit.svelte.dev/docs/configuration#alias
//
// If you want to overwrite includes/excludes, make sure to copy over the relevant includes/excludes
// from the referenced tsconfig.json - TypeScript does not merge them in
```

but the docs at the link **DO NOT** include the stated "referenced tsconfig.json". At least as of Oct 15 2023.

**Comment by laneme** [comment]
Re-running `pnpm i` worked for me after doing a `rm node_modules .svelte-kit -rf`.
It added the `$lib` alias automatically.

**Comment by mskocik** [comment]
This is related somehow to using typescript... When I tried to google something, I found if I add `moduleResolution` to `tsconfing.json` it disappears.

![image](https://github.com/sveltejs/language-tools/assets/25513620/45c736f8-2168-4346-b9a8-3e6df8079a7a)

I have no idea if it breaks something else or not. But it seems it's related more to TS, not the lib itself. And if it's related to the lib, help is needed.

**Comment by alexander-mart** [comment]
My SvelteKit version was:
```package.json
		"@sveltejs/kit": "^2.5.0",
```

### How i solved:
`./tsconfig.json`
```diff
{
	"extends": "./.svelte-kit/tsconfig.json",
	"compilerOptions": {
		"paths": {
+			"$lib": ["./src/lib"],
+			"$lib/*": ["./src/lib/*"],
+			"$utils": ["./src/lib/utils"],
+			"$utils/*": ["./src/lib/utils/*"],
+			"$components": ["./src/lib/components"],
+			"$components/*": ["./src/lib/components/*"],
		},
```

`./tsconfig.json`
```diff
-		"moduleResolution": "nodenext",
+		"moduleResolution": "bundler",

```

**Comment by rcalimlim** [comment]
### helix users:

> I ran into the same problem using Helix-editor turns out it is because svelte language server could not find the root? of the project. Two ways to fix it:
> 
> `git init` at root of the project, seems **.git** is used to find the root.

This is the easiest/fastest way that I fixed this issue. It does seem that an initialized git repo needs to exist before installing everything.

Steps I used to fix this issue locally:
1. in the root folder of your repo (where `package.json` is) run: `git init .`
3. delete `node_modules` and `.svelte-kit` folders
4. reinstall node modules (`npm i`, `yarn i`, `pnpm i`, etc.)
5. confirm issue is resolved

**Comment by joshualonsakoavnet** [comment]
> The ambient `$app` module wasn't detecting for me when setting up SvelteKit in a pre-existing Tauri project.
> 
> Deleting the `include` setting in my root `tsconfig.json` fixed the problem.
> 
> Inheriting from `.svelte-kit/tsconfig.json` as much as possible seems to be what is needed for SvelteKit to work as expected.
> 
> If you still want to customize your tsconfig.json:
> 
> * `./$types` needs `.svelte-kit/types/**/$types.d.ts` to be in the `include` array
> * `$app` needs `vite.config.ts` to be in the `include` array
> * `$env` needs `.svelte-kit/ambient.d.ts` to be in the `include` array
> * `$lib` needs to be [properly configured](https://www.typescriptlang.org/tsconfig#paths) in your `compilerOptions.paths` setting

THANK YOU! This was the one for me, I'm not sure why that worked but I'm glad it did!

**Comment by tarekfb** [comment]
My fix wasnt listed here.

Delete the `paths` property from root `tsconfig.json`, under `compilerOptions`:

**Comment by 5argon** [comment]
For my case, the new Svelte lib template came with tsconfig `"moduleResolution": "NodeNext",`. Changing it to `"moduleResolution": "node",` makes `$lib` works.

**Comment by simlate** [comment]
> Problem still happening nowadays. I just did a `npm create svelte@latest myapp` choosing a skeleton project with typescript and the $lib folder couldn't be found. I got it working by modifying the following files: `svelte.config.js`


Same thing just happened to me.
Turned out, I've forgot to use `lang="ts"` on the script tag. So instead of:

```html
<script>
  //import StdWindow from "$lib/windows/StdWindow.svelte"; // works
  import { StdWindow } from "$lib/index.js"; // doesn't work, $lib not found
</script>
```

It was as simple this:

```html
<script lang="ts">
  //import StdWindow from "$lib/windows/StdWindow.svelte"; // works
  import { StdWindow } from "$lib/index.js"; // works
</script>
```

**Comment by memark** [comment]
My key to solving this problem was this sentence in root `tsconfig.json`:
```
  // Path aliases are handled by https://kit.svelte.dev/docs/configuration#alias
  // except $lib which is handled by https://kit.svelte.dev/docs/configuration#files
```
which correctly led me to adding this
```js
kit: {
  files: {
    "lib": "src/lib"
  }
}
```

That solved the problem for me.
to `svelte.config.js`.

Problem solved!

**Comment by shinokada** [comment]
Deleting the include in tsconfig.json solved it for me.
