### ISSUE TITLE
Type inference of store not working for custom stores (specifically, overmind-svelte)

### ISSUE THREAD

**Issue by abirtley** [sveltejs/language-tools#1462]
### Describe the bug

When using overmind-svelte, if you `import { state } from '$lib/store`, intellisense understands its type. However, if you then try to access `$state`, you lose type inference and all the assistance that intellisense would otherwise provide. Instead of having full type information, `$state` shows up as `any`.

This problem does not seem to affect simple native stores, eg those created by `readable`.

### Reproduction

```ts
  // state and actions are from overmind, using overmind-svelte
  import { state, actions } from '$lib/store';
  
  // State is the type definition of the state object
  import type { State } from '$lib/store';

  // nativeStore is as follows: export const nativeStore = readable(10);
  import { nativeStore } from '$lib/store';

  $: stateWithTypingInformation = ($state as State).newGameWizard;
  $: stateWithoutTypingInformation = $state.newGameWizard;
  $: x = $nativeStore;
```

Hovering over `stateWithTypingInformation`:

<img width="477" alt="image" src="https://user-images.githubusercontent.com/19584280/165225113-4ab9ac00-3880-4c9e-8eed-80c74ac0fd30.png">

Hovering over `stateWithoutTypingInformation`:

<img width="473" alt="image" src="https://user-images.githubusercontent.com/19584280/165225136-9e4fa6a9-82d3-4264-9210-7a1db1fd537e.png">

Hovering over `$nativeStore`:

<img width="477" alt="image" src="https://user-images.githubusercontent.com/19584280/165225052-6cc5ff7d-bff4-48d0-a75a-6ed1865febf4.png">

Hovering over `import { state } from '$lib/store';` shows the full type as expected, it's only when you try to access via `$state` (with the `$`) that you lose type information. But of course, you have to access via `$` for reactivity.

### Expected behaviour

Even when using overmind-svelte, you should be able to access `$state` and not lose the type information that is associated with `state`.

### System Info

- OS: MacOS BigSur (11.6.4)
- IDE: VSCode (1.66.0)
- VSCode Extension:
```
Released on
27/03/2020, 10:27:53
Last updated
14/04/2022, 20:52:53
Identifier
svelte.svelte-vscode
```

### Which package is the issue about?

Svelte for VS Code

**Comment by jasonlyu123** [comment]
Can you provide the custom store definition? Your store needs to implement the svelte store's interface for the language-server to infer the value type.

**Comment by jasonlyu123** [comment]
I am assuming you're using the `createMixin` function exported by the module. And export the state and actions from the result. In that case, You'll have to type the result on your own. Or ask the author to provide a more precise type definition. The module's type definition typed the state property as any.  We can't infer the typing from it.

**Comment by abirtley** [comment]
Hi @jasonlyu123 , apologies I forgot that I had already tried to type the result but didn't include it in the issue description 🤦 . Here is a minimal set of files that will demonstrate the issue. I suspect the issue may be in the type `ContextForSvelte` that I created in order to try to type the result.

The files below show in **incorrect implementation** of `ContextForSvelte`, which reproduces the error encountered above. I will post another comment showing how to fix it.

**lib/overmind/index.ts**

```ts
import type { IContext } from 'overmind';

export type State = {
  counter: number;
};

const state: State = {
  counter: 0,
};

export const config = {
  state,
};

export type Context = IContext<typeof config>;
```

**lib/state.ts**

```ts
import { createOvermind } from 'overmind';
import { createMixin } from 'overmind-svelte';
import { config } from '$lib/overmind';
import type { Context } from '$lib/overmind';

type ContextForSvelte = Context & {
  state: {
    subscribe: (subscription: (value: any) => void) => () => void;
    set?: (value: any) => void;
  };
};

const overmind = createOvermind(config);
const storeMixin = createMixin(overmind) as ContextForSvelte;

export const state = storeMixin.state;
export type { State } from '$lib/overmind';
```

**routes/test.svelte**

```ts
<script lang="ts">
  import { state } from '$lib/store';
  import type { State } from '$lib/store';

  $: counter = $state.counter;
  $: counterWithType = ($state as State).counter;
</script>

{counter.toUpperCase()}
{counterWithType.toUpperCase()}
```

**Screenshot of test.svelte in VS Code**

Notice that `counterWithType.toUpperCase` is flagged as an error, but `counter.toUpperCase` is not.

<img width="411" alt="image" src="https://user-images.githubusercontent.com/19584280/165420902-c939367a-b00f-4d16-a718-951224a38e5e.png">

**Comment by abirtley** [comment]
I fixed this issue by changing the `ContextForSvelte` so that the subscribe function accepts a `value` of the type of your state:

```ts
import type { Context, State } from '$lib/overmind';

type ContextForSvelte = Context & {
  state: {
// DELETE:     subscribe: (subscription: (value: any) => void) => () => void;
// and replace with:
    subscribe: (subscription: (value: State) => void) => () => void;
    set?: (value: any) => void;
  };
};
```

You then get intellisense working in VS Code as expected:

<img width="407" alt="image" src="https://user-images.githubusercontent.com/19584280/165422751-a8876e37-5952-4fc9-8045-30c939d2aa4f.png">
