### ISSUE TITLE
Consider becoming a verified publisher

### ISSUE THREAD

**Issue by isidorn** [sveltejs/language-tools#1463]
### Description

Hi VS Code PM here 👋

It would be great if you verify your extension author https://marketplace.visualstudio.com/publishers/svelte

### Proposed solution

More about this process can be found here https://code.visualstudio.com/api/working-with-extensions/publishing-extension#verify-a-publisher

Let me know if I can help in any way.

**Comment by dummdidumm** [comment]
Steps taken and request sent!

**Comment by isidorn** [comment]
@dummdidumm awesome, thanks a lot 👏

**Comment by dummdidumm** [comment]
Domain was verified 👍

**Comment by isidorn** [comment]
Awesome 👏 

![Screenshot 2022-05-03 at 14 05 27](https://user-images.githubusercontent.com/1926584/166449591-0b1ec3ce-f931-4bec-ba3e-ebadc564f1c5.png)
