### ISSUE TITLE
Possible to exclude `.svelte-kit` folder from `svelte-check`?

### ISSUE THREAD

**Issue by SwiftWinds** [sveltejs/language-tools#1469]
`svelte-kit` keeps reporting errors in the `.svelte-kit` folder, which contains generated files not part of my source code, so they shouldn't matter:

<img width="572" alt="image" src="https://user-images.githubusercontent.com/12981958/166418308-b790769e-8b52-48d4-9ff9-4c9eb2167113.png">

I tried adding `".svelte-kit/*"` to my `exclude` array in my `tsconfig.json`, then making `svelte-check` use my `tsconfig.json` with `--tsconfig ./tsconfig.json`, but it still doesn't exclude it. Am I doing something wrong here?

**Comment by jasonlyu123** [comment]
I can't reproduce this with a newly created svelte-kit project can you provide a reproduction?

**Comment by SwiftWinds** [comment]
Weird. The error went away after working on the project some more. I'll close this then and reopen it if it ever comes back. Thank ya :)

**Comment by eXodes** [comment]
@jasonlyu123 Hi, I'm not sure if this is the wrong way to do it, but I experience this issue and I created a reproduction for it [here](https://github.com/eXodes/svelte-check-generated-files-repro) from fresh setup.

Steps to reproduce:
1. Run `npm run check:watch` in one of the terminal tabs
2. Run `npm run dev` in another terminal tab
3. `svelte-check` terminal will show the generated files error

**Why is this an issue?** 
Sometimes I would need to restart `dev` when compiling/reloading new dependencies for the project.
