### ISSUE TITLE
@const can be inside an if block as well

### ISSUE THREAD

**Issue by stephane-vanraes** [sveltejs/language-tools#1470]
### Describe the bug

Since Svelte 3.48 `@const` is allowed to be inside an `#if` as well, the extension however still complains about this.

![image](https://user-images.githubusercontent.com/13446670/166422777-81693054-dfa6-4a81-b0bc-b0e5282ec26f.png)

### Reproduction

```
{#if true}
  {@const test = 123}
{/if}
```

### Expected behaviour

Code above is not marked as an error.

### System Info

- OS: [Windows]
- IDE: [VSCode]
- Svelte for Vs Code: [v105.16.0]

### Which package is the issue about?

Svelte for VS Code

**Comment by lacherogwu** [comment]
Same here 😄
<img width="1631" alt="Screen Shot 2022-05-03 at 10 52 26" src="https://user-images.githubusercontent.com/49835614/166428128-28b0b65f-bcac-4fa5-a9b0-1f07afa2416d.png">

**Comment by stephane-vanraes** [comment]
I suppose this is just a matter of bumping the svelte version in the extension.

**Comment by jasonlyu123** [comment]
We might need some time with this one. It's tricky to implement this into the svelte2tsx transformation for type check.

**Comment by dummdidumm** [comment]
I guess this is easier for the new transformation. Should we only implement it for that one, which also will give us more users for it, which should help get more feedback before switching?

**Comment by dummdidumm** [comment]
Turns out this already works without modifications for the new transformation 👍

**Comment by jasonlyu123** [comment]
I have some ideas about how to do this in the old transformation but haven't finished it yet. I can add a PR later. Don't have to wait for it though I also think we can get the new transformation supported first.
