### ISSUE TITLE
Guard for non-nullish value nested in store is reset after `#each`

### ISSUE THREAD

**Issue by fehnomenal** [sveltejs/language-tools#1475]
### Describe the bug

Strange title I know...

Minimum reproducible example is:

![image](https://user-images.githubusercontent.com/9959940/167240736-bd861657-3e91-4e5b-9892-f1a5f42fcd74.png)

The error only occurs when using a store that contains an object with a field that is optional or `| null` or `| undefined` and this field is an object.
After `#each`ing over the `foo` strings (or even writing `{#each [$data.item.foo] as str}` when having only a `string`) the type safety of `$data.item` is reset and I get an error like in the screenshot. This is even the case when testing like `{#if $data?.item?.foo}`.

Without the `each` I get no error.

### Reproduction

```svelte
<script lang="ts">
  import type { Readable } from 'svelte/store';

  let data: Readable<{
    item?: {
      foo: string[];
    };
  }>;
</script>

{#if $data?.item}
  {#each $data.item.foo as str}
    <li>{str}</li>
  {/each}

  <pre>{JSON.stringify($data.item.foo)}</pre>
{/if}
```

### Expected behaviour

Well, typescript should know that the value is still non-nuliish.

### System Info

- OS: NixOS
- IDE: VSCodium with official extension Svelte for VS Code (both latest version)

### Which package is the issue about?

svelte2tsx

### Additional Information, eg. Screenshots

I'm not sure if the problem is with `svelte2tsx` and I don't know how to verify this.

The problem seems related to #1341

**Comment by jasonlyu123** [comment]
I can't reproduce this on both VSCode and VSCodium. What exactly is the version of  Svelte for VS Code and VSCodium you're using? The latest version is 105.16.0 which works with VSCode 1.52.0 or later. If you're indeed in the latest version can you provide a reproduction in a repository form?

**Comment by fehnomenal** [comment]
Extension is at v105.16.0

VSCodium (I noticed there was a new release yesterday):
```
Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-13T00:16:29.523Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.15.34
```

Do you have `"strict": true` in your `tsconfig.json`? Only with `true` I get these errors...

I will try to reproduce it in a simple repo.

**Comment by jasonlyu123** [comment]
Ah, It seems to only happen in the new transformation.

**Comment by dummdidumm** [comment]
I played around with this a little, this looks like a TypeScript bug to me. Minimum reproducible in a TS file:

```ts
let foo = null;
let bar: { a?: { b?: string } } = null as any;

if ((foo, bar)?.a?.b) {
	(foo, bar).a.b;
	for (const a of []) {
	}
	(foo, bar).a.b;
}
```
