### ISSUE TITLE
VS Code: configuration not found when using monorepo / yarn workspaces

### ISSUE THREAD

**Issue by rondonjon** [sveltejs/language-tools#148]
**Describe the bug**

The VS Code plugin doesn't find the `svelte.config.js` config file if the project is configured as a monorepo and the Svelte preprocessor is only used by one of the contained packages.

**Expected behavior**

I have a monorepo with yarn workspaces, i.e. there is a node_modules folder on the top level, but there are also several subprojects in `packages/` which each have their own node_modules, config files, etc.

One of my packages is a frontend with .svelte files. The svelte-preprocessor is configured inside `packages/frontend/svelte.config.js`. The Svelte implementation is inside `packages/frontend/src`.

I would expect the VS Code plugin to find the package-specific svelte preprocessor configuration and use it.

**Actual Behaviour**

Instead, the plugin seems to search only on the monorepo / root level. Since there is no such config file, it assumes that no preprocessors are needed, and displays errors in the most of the script sections.

**Additional Context**

The idea of a monorepo however is to hoist only shared modules and configs and to leave subproject-specific files (like a svelte.config.js) inside the respective package folders.

To resolve the issue, I think the plugin should rather "search" for the nearest config, starting from the source folder of the current .svelte file, and then ascend until it finds one or reaches the top of the folder structure.

**Comment by dummdidumm** [comment]
From what do you infer that the `svelte.config.js` is not found? The plugin already works like you describe the solution, so it tries to find the nearest `svelte.config.js` starting from the given file.

**Comment by rondonjon** [comment]
@dummdidumm because I am getting these errors in the VS Code editor if there is only a svelte.config.js in the subpackage folder ...

![image](https://user-images.githubusercontent.com/8258823/83487208-e618c500-a4aa-11ea-8c2f-b8ab4dc43f4f.png)

> Unexpected token. If you expect this syntax to work, here are some suggestions: If you use typescript with `svelte-preprocessor`, did you add `lang="typescript"` to your `script` tag? Did you setup a `svelte.config.js`? See https://github.com/sveltejs/language-tools/tree/master/packages/svelte-vscode#using-with-preprocessors for more info.svelte(parse-error)

... and the errors disappear after duplicating that config in the monorepo root folder and relaunching VS Code.

The original error can be restored by deleting the duplicated svelte.config.js from the monorepo root and relaunching VS Code once more.

**Comment by dummdidumm** [comment]
Could you look into Output->Svelte and paste the contents of that? I added some more logging which hopefully shows some insights.

**Comment by rondonjon** [comment]
```
Initialize language server at  /home/user/some-unrelated-project                      <---- ???
Initialize new ts service at  
Trying to load config for /home/user/monorepo/packages/frontend/src/components/charts/Chart.svelte
Found config at  /home/user/monorepo/packages/frontend/svelte.config.js
Using Svelte v3.23.0 from /home/eon/portfolio-viewer/node_modules/svelte/compiler
Using Svelte v3.23.0 from /home/eon/portfolio-viewer/node_modules/svelte/compiler
```

**Comment by rondonjon** [comment]
Here my `svelte.config.js` btw.

```
const sveltePreprocess = require("svelte-preprocess");

module.exports = {
  preprocess: sveltePreprocess()
};
```

Tried `node svelte.config.js` in the terminal to ensure that the dependencies resolve well; no errors.

**Comment by joelmukuthu** [comment]
Hi @rondonjon, as far as I know the `svelte.config.js` file has to be at the root of the project ([ref](https://github.com/sveltejs/language-tools/tree/27aa787c6882a25a2c287415e39387bde0857c5c/packages/svelte-vscode#generic-setup))

**Comment by rondonjon** [comment]
@joelmukuthu, it is at the root of a project.

**Comment by dummdidumm** [comment]
Could you provide a minimum sample repo that reproduces the error for you?

**Comment by joelmukuthu** [comment]
My understanding is that the root of the project is the `monorepo` directory, which contains the root `package.json` and `node_modules`. So the file would be at `/home/user/monorepo/svelte.config.js` as opposed to `/home/user/monorepo/packages/frontend/svelte.config.js`. 

That said, if the plugin does resolve the config file in the `packages/frontend/` directory, maybe that's also meant to work (or is a bug), in which case something needs to be updated (docs or code). I just wanted to pitch in in case you were blocked.

**Comment by dummdidumm** [comment]
@rondonjon does the issue still exist? Could you provide a minimum sample repo that reproduces the error for you?

**Comment by rondonjon** [comment]
@dummdidumm, sorry, I have given up on this and moved the svelte.config.js into the frontend folder to get unblocked.
