### ISSUE TITLE
Indentation on format always defaults to 2 spaces

### ISSUE THREAD

**Issue by gbkwiatt** [sveltejs/language-tools#1493]
### Describe the bug

No matter what I set in settings User/Remote/Workspace or even `.editorconfig`
When I trigger auto format - it always formats `.svelte` files with 2 spaces instead of 4 like I want to. 

When manually tabbing - vscode sees 4 spaces correctly and inserts them on tab. 

### Reproduction

Prettier not installed. 
Settings in all json files 
```json
"editor.tabSize": 4,
"editor.detectIndentation": false,
"[svelte]": {
  "editor.defaultFormatter": "svelte.svelte-vscode",
  "editor.tabSize": 4,
  "editor.detectIndentation": false,
}
```
`.editorconfig`
```bash
[{*.js, *.json, *.cjs, *.svelte, *.ts}]
indent_size = 4
```

### Expected behaviour

on Save or on format document - it should use 4 spaces as per settings

### System Info

- OS: Windows
- IDE:  Vscode insiders

### Which package is the issue about?

Svelte for VS Code

**Comment by jasonlyu123** [comment]
Did you happen to have any of this prettier config? https://prettier.io/docs/en/configuration.html

If there isn't a prettier config and the pettier extension is disabled, I can't reproduce this.

**Comment by gbkwiatt** [comment]
No, I even uninstalled prettier all together from vscode(extension).
No prettier config files anywhere.

**Comment by gbkwiatt** [comment]
It seems like it started working for some reason. Classic. Thank you anyway

**Comment by gbkwiatt** [comment]
Actually - I've noticed that there is 1 file that formats correctly and other file in same directory formats with 2 spaces. Why is that ?

**Comment by dummdidumm** [comment]
Could you provide a repository that reproduces the issue?

**Comment by gbkwiatt** [comment]
Unfortunately I cannot. It's private one. I honestly tried everything by now, Installed prettier back and tried to add some settings. but it just always ignores that tabSize/tabWidth never had such a issue with any of the other files like js/vue.
Is there any way to debug what settings are taken into account when formatting ?

**Comment by dummdidumm** [comment]
https://github.com/sveltejs/language-tools/blob/44d2d65132616143cff5124cd0914832494dd513/packages/language-server/src/plugins/svelte/SveltePlugin.ts#L78
This is where the config is loaded. It checks for various prettier config styles, falling back to the tabsize you set when no such config is found. There is no way to debug it from the published extension, but you could run the extension in debug mode after cloning this repo and following the setup instructions in the main readme.

**Comment by dummdidumm** [comment]
Closing due to lack of reproduction and inactivity.

**Comment by ahkelly** [comment]
This is actually still an issue. It is not honoring the vs code default settings. Using the Create route shortcut it defaults the files created to 4 spaces when my vs code settings is 2. If I create the file manually the 2 spaces default is honored.
