### ISSUE TITLE
Svelte extension does not syntax highlight in GitHub Codespaces

### ISSUE THREAD

**Issue by LoganTann** [sveltejs/language-tools#1498]
### Describe the bug

In github codespaces, the svelte extension does not highlight svelte files

### Reproduction

Create a blank github codespaces project

Create a svelte kit project : https://kit.svelte.dev/docs/introduction#getting-started

Use the following options : 
```
✔ Which Svelte app template? › SvelteKit demo app
✔ Add type checking? › TypeScript
✔ Add ESLint for code linting? … Yes
✔ Add Prettier for code formatting? … Yes
✔ Add Playwright for browser testing? … No
```

Search the svelte extension in the editor's marketplace and install it

open a `.svelte` file

### Expected behaviour

The code should have colors.

### System Info

- OS: Windows / Firefox 100 (Ubuntu in the remote machine)
- IDE: Vscode - Github Codespaces

### Which package is the issue about?

Svelte for VS Code

### Additional Information, eg. Screenshots

![image](https://user-images.githubusercontent.com/28659185/170514850-ccd8b352-0849-46bc-8c49-2c14c1cc7f6c.png)

**Comment by Jojoshua** [comment]
https://marketplace.visualstudio.com/items?itemName=asafamr.svelte-web helpful?

**Comment by LoganTann** [comment]
Perfect, works as expected !

Thanks for the help 😊

**Comment by jasonlyu123** [comment]
Seem like you're referring to the web extension. The official status is tracked at https://github.com/sveltejs/language-tools/issues/1190. We do want to make the extension work in the browser someday.

**Comment by Jojoshua** [comment]
@jasonlyu123 Have you seen anything out there of an attempt to support svelte in the monaco editor grammar?https://microsoft.github.io/monaco-editor/monarch.html
