### ISSUE TITLE
@const with left shift causes issue in VSCode

### ISSUE THREAD

**Issue by mwhebert** [sveltejs/language-tools#1499]
### Describe the bug

In VSCode the file contents below will cause an error stating: "Type annotations can only be used in TypeScript files.js(8010)" even though the script tag includes lang="ts".  This will show up on the "type" declaration  "export let labels: string[];" line where "string[]" will have the red squiggle line below it.

Moving the "left shift" out of the @const and calling it in a function works around the issue. 
ex:  {@const mask = doShift(1,indx)}

I assume it has to do with parsing inside the "html" section the "<" is causing the issue.  

The file will compile and work, this seems to be just an issue with the plugin.

### Reproduction
```
<script lang="ts">
  export let labels: string[];
</script>

<div>
  {#each labels as label, indx}
    {@const mask = 1 << indx}
    <div>
      <span>{label} {mask}</span>
    </div>
  {/each}
</div>
```

### Expected behaviour

I would assume no error displayed under the "string[]" type declaration.

### System Info

OS: [Windows 11]
IDE: [VSCode 1.67.2]

Svelte for VS Code: v105.16.1

### Which package is the issue about?

Svelte for VS Code

### Additional Information, eg. Screenshots

![image](https://user-images.githubusercontent.com/12010963/170744447-adda0100-ec31-4886-95d7-274e0d1c8da7.png)

**Comment by dummdidumm** [comment]
This is probably working as expected with the new transformation, so I'm hesitant to fix it for the (not much longer) old transformation.
