### ISSUE TITLE
File name 'asd/src/components/Board.svelte' differs from already included file name 'asd/src/components/board.svelte' only in casing

### ISSUE THREAD

**Issue by TeamDman** [sveltejs/language-tools#1503]
### Describe the bug

Importing a file I changed the naming on from lowercase to uppercase flags an error even though the name is accurate. The code still works, no error in console, just in vscode

### Reproduction

1. create a file `board.svelte`
2. import it somewhere
3. rename it to `Board.svelte`
4. update your import
5. still get error 

I think I had the dev server running while I did this if that's relevant

### Expected behaviour

no error

### System Info

- OS: windows
- IDE: vscode 1.67.2
- Name: Svelte for VS Code
Id: svelte.svelte-vscode
Description: Svelte language support for VS Code
Version: 105.16.1
Publisher: Svelte
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode

### Which package is the issue about?

Svelte for VS Code

### Additional Information, eg. Screenshots

![image](https://user-images.githubusercontent.com/9356891/170847808-f3b2df08-b156-4372-b748-60362761b6ae.png)

![image](https://user-images.githubusercontent.com/9356891/170847819-8cca26be-df09-4166-a0a9-540e08c4b2dc.png)

restarted vscode and the dev server a few times, error still present

**Comment by jasonlyu123** [comment]
It's likely there is still place where it's still in the old casing. 

You can 

1. check if it's still the old casing in the file system. 
2. Try rename it in git. https://stackoverflow.com/a/20907647
3. Close all tab in the VSCode and restart.

**Comment by TeamDman** [comment]
Looks like closing all the tabs before the restart was enough, thanks!
