### ISSUE TITLE
When using SvelteKit in a VSCode workspace, using the `prependData` method causes errors in the editor only

### ISSUE THREAD

**Issue by d3rpp** [sveltejs/language-tools#1507]
### Describe the bug

I'm writing a SvelteKit application that is contained within a folder in a part of a VSCode workspace.

These errors pop up in all svelte files tagged with `lang="scss"`

![image](https://user-images.githubusercontent.com/45675641/171317670-b1fc4e96-7a05-455e-980a-bbb3625edf61.png)

### Reproduction

I've setup `svelte-preprocess` to prepend the data `'@import "src/global.scss";'` to all `scss` style fields

```js
{
	scss: {
		prependData: '@import "src/global.scss";'
	}
}
```
Which compiles fine, the variables in the global file are replicated and placed in the correct spot, however, The error is popping up on the editor

### Expected behaviour

No Error messages should pop up as it is working as expected

### System Info

- OS: Windows 11
- IDE: VSCode

### Which package is the issue about?

Svelte for VS Code

### Additional Information, eg. Screenshots

I believe this only affects projects within VSCode workspaces since I have another codebase that is unaffected by this issue that is not in any way contained within a VSCode workspace.

# Screenshots

## The `src` folder
![image](https://user-images.githubusercontent.com/45675641/171318339-e1ee0846-1924-4779-b421-0c0c620ded29.png)

**Comment by d3rpp** [comment]
I'd just like to add as well, that I did restart the extension host multiple times to ensure that wasn't the issue.

and the code over at https://gitlab.com/d3rpp/dev has a similar feature but with `src/_common.scss` without issues (It doesn't use a VSCode Workspace)

**Comment by jasonlyu123** [comment]
This is probably not a bug on our side. As when you open a VSCode workspace or open the editor in a monorepo root. The `process.cwd` won't be the same as your build process. You need to resolve the path to an absolute path with `import.meta.url` or `__filename`

**Comment by d3rpp** [comment]
> This is probably not a bug on our side. As when you open a VSCode workspace or open the editor in a monorepo root. The `process.cwd` won't be the same as your build process. You need to resolve the path to an absolute path with `import.meta.url` or `__filename`

unfortunately, to my knowledge, neither of these are possible in stylesheets :/

**Comment by jasonlyu123** [comment]
What I mean is to set up prepend with the resolved path in your `svelte.config.js` 

```
	scss: {
		prependData: `@import "${resolvedPathToGlobalScss}";`
	}
```

**Comment by d3rpp** [comment]
> What I mean is to set up prepend with the resolved path in your `svelte.config.js`
> 
> ```
> 	scss: {
> 		prependData: `@import "${resolvedPathToGlobalScss}";`
> 	}
> ```

Oh, of course, my apologies; thanks for that one
