### ISSUE TITLE
Import statements moved to context="module" on save

### ISSUE THREAD

**Issue by billmcknight1953** [sveltejs/language-tools#1508]
When I save a file that has both  an ordinary <script language="ts"> tag, and a <script context="module" language="ts"> tag,  all the import statements are moved to the script context="module" tag.  If I disable the Svelte for VS Code plugin, the save operation doesn't move the import statements.  Can I disable this move operation without disabling the Svelte for VS Code plugin?

I am using version v.105.16.1

**Comment by dummdidumm** [comment]
Out of curiousity: Why is that a problem for you? It doesn't make a difference where the import appears, it works either way.

**Comment by billmcknight1953** [comment]
If it makes no difference where the import statements exist, then I will close this request

**Comment by billmcknight1953** [comment]
If it makes no difference then I will close this request
