### ISSUE TITLE
Support for code loaded from external script src tag

### ISSUE THREAD

**Issue by grbd** [sveltejs/language-tools#1511]
I'm fairly new to svelte, but one of the tricks I noticed that works
is that you can place the code for a svelte component into a seperate file such as

example1.svelte
```svelte
<script lang="ts" src="./example1.svelte.ts"></script>

<button class="btn" on:click={handleClick}>
	clicks2: {count}
</button>
```

example1.svelte.ts
```ts
let count = 0;
	
export function handleClick() {
    count += 2;
}
```

This seems to build and work fine similar to the way vue supports placing the template and code into separate files for separation of concerns.
you can also nest the files in the file explorer with something like this
```json
    "explorer.fileNesting.patterns": {
        "*.svelte": "${capture}.svelte.ts, ${capture}.svelte.js, ${capture}.svelte.css, ${capture}.svelte.scss"
    },
```

However it looks like the svelte extension for vscode doesn't like it all that much
It complains about the count property and handleClick function not being defined

Also for the script tag I noticed the extension doesn't support self closing tags yet
but I think that's related to https://github.com/sveltejs/language-tools/issues/299
```svelte
# Works ok
<script lang="ts" src="./example1.svelte.ts"></script>
# Complains about a missing end tag
<script lang="ts" src="./example1.svelte.ts" />
```

I had a rumage through the settings but couldn't find anything related to the above.

**Comment by dummdidumm** [comment]
Duplicate of #936

**Comment by grbd** [comment]
ah sorry I did search for an existing issue but missed that one
