### ISSUE TITLE
"Unknown  at rule @apply" when using Tailwind / Windi directives

### ISSUE THREAD

**Issue by knpwrs** [sveltejs/language-tools#1512]
Both the LSP and `svelte-check` have a warning when using `@apply` from tailwind / windi:

<img width="464" alt="image" src="https://user-images.githubusercontent.com/174864/172033648-65c38a80-c669-4738-98ea-9a1356b7a11a.png">

```
> svelte-check --tsconfig ./tsconfig.json


====================================
Loading svelte-check in workspace: ...
Getting Svelte diagnostics...

/.../src/routes/about.svelte:47:5
Warn: Unknown at rule @apply (css)
  h1 {
    @apply text-red-500 uppercase;
  }
```

Is there a way to turn off `unknownAtRules` for `svelte-check` and the svelte lsp? I found this solution for vue/vetur: https://github.com/tailwindlabs/tailwindcss/discussions/5258#discussioncomment-1979394

**Comment by knpwrs** [comment]
I managed to fix this by following the directions at https://github.com/sveltejs/language-tools/blob/5a6eba15918a556e2bcb04638c313ac9dd03212c/docs/preprocessors/other-css-preprocessors.md via https://github.com/sveltejs/language-tools/issues/515:

1. Setup `sveltePreprocess` with `sveltePreprocess({ postcss: true })`
2. Install `postcss-load-config` as a `devDependency`
3. Create `postcss.config.cjs` with `module.exports = {};`
4. Add `lang="postcss"` to relevant style blocks

**Comment by mshamaseen** [comment]
@knpwrs I don't think that is a solution but just a workaround. I want to use `scss` as the language and get benefit from its features.
