### ISSUE TITLE
Watch tsconfig extends for changes

### ISSUE THREAD

**Issue by dummdidumm** [sveltejs/language-tools#1529]
### Description

In SvelteKit, a generated tsconfig lives in `.svelte-kit/tsconfig.json`. This file doesn't exist initially (before you run dev or prepare for the first time) so you see errors in your code. These go away once the extended tsconfig exists, but we don't watch for changes like this, so people have to restart the language server in order to see that.

The quick fix is to handle this specific case, but it would be great if we could generalize this to watch tsconfig files that others extend from and react to changes there.

### Proposed solution

Dig into the TS code and see how they do it, and see if this can be applied at our code, too.

**Comment by jasonlyu123** [comment]
There are two ways I can find to get the extended config file path. 

1. The `configFile` property in `compilerOptions` have the extended config files info. But it's internal. 
2. Or we could leverage the `extendedConfigCache` parameter that can be passed into `parseJsonConfigFileContent`. If we implement the cache, typescript would cache the extended config files into it. 

After we obtain the config file paths, we can watch the files and restart the typescript language service. I think we could use `ts.sys.watchFile` for it. VSCode default to not watching files that are in the gitignore and there's probably not a lot of tsconfig to watch. 

If we are watching the extended config files in the server. We could also change to watch the main tsconfig in the server. It could probably improve the performance a bit.

**Comment by dummdidumm** [comment]
Option 2 sounds good! From the map we get the paths to watch and we also can compare the new config to the old to not restart when the content is the same - I like it! Do you want to implement this or shall I do it?

**Comment by jasonlyu123** [comment]
I can try to implement it this week
