### ISSUE TITLE
Autocomplete for external libraries 

### ISSUE THREAD

**Issue by galkatz373** [sveltejs/language-tools#153]
**Is your feature request related to a problem? Please describe.**
Right now when I use the core svelte functions, like onMount, afterUpdate, etc.. I get really nice autocomplete options, but if I install external library, those options don't exist.
It would be nice to have them working with external libraries as well.

**Additional context**
With core svelte functions: 
![withsvelte](https://user-images.githubusercontent.com/2151890/83506924-787f8f80-a4d0-11ea-91e2-0a8435b12b92.png)

With external library:
![external](https://user-images.githubusercontent.com/2151890/83506938-7ddcda00-a4d0-11ea-898b-a833d01bb72b.png)

**Comment by jasonlyu123** [comment]
Do you got completion if you import the same module in a js file?

**Comment by galkatz373** [comment]
> Do you got completion if you import the same module in a js file?

yes

**Comment by orta** [comment]
This could be the automatic type acquisition in JS, and you need to include `@types` in TS?

**Comment by jasonlyu123** [comment]
I tired with the library in your screenshot. To me, it behaves the same in the svelte file and js file. Do you have jsconfig.json or tsconfig.json in your workspace?

As for what @orta mentions, the svelte language server doesn't support [automatic type acquisition](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_typings-and-automatic-type-acquisition)

**Comment by galkatz373** [comment]
> I tired with the library in your screenshot. To me, it behaves the same in the svelte file and js file. Do you have jsconfig.json or tsconfig.json in your workspace?
> 
> As for what @orta mentions, the svelte language server doesn't support [automatic type acquisition](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_typings-and-automatic-type-acquisition)

I have the default svelte template from svelte.dev, so no jsconfig or tsconfig.
I also tried the routify starter pack, and got the same result.

**Comment by jasonlyu123** [comment]
For some reason I haven't figure out, it will work if you at least have an empty `jsconfig.json`.  Maybe you could add an empty one until I find a solution to this.

**Comment by dummdidumm** [comment]
Fix available in about 16 hours.
