### ISSUE TITLE
Renaming variable name from "ts" file in VSCode breaks "svelte" file's codes.

### ISSUE THREAD

**Issue by humbleCoder1990** [sveltejs/language-tools#1539]
### Describe the bug

https://user-images.githubusercontent.com/87828192/175884373-52807e21-278e-452b-a356-e128c79a2a16.mov

### Reproduction

1. Create a "writable" variable called "foo", then export it.
2. Import this variable inside svelte file.
3. Use this variable with $ directive like $foo.length or class:foo={$foo}
5. Rename variable to "koo" using "Rename symbol" feature of VSCode

The result is like

"$foo.length" => "$koollength" instead "$koo.length"
"class:foo={$foo} => "class:foo={$koo" (losing right bracket...)

### Expected behaviour

I'm really afraid to rename any variable using in ".svelte"

### System Info

Lastest MacOS, Lastest VScode 

### Which package is the issue about?

Svelte for VS Code extension

**Comment by PeytonHanel** [comment]
I'm having this problem but I'm having a very hard time reproducing it in a codebase I can push publicly
