### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Zaid-maker** [sveltejs/language-tools#1540]
- Issue Type: `Performance`
- Extension Name: `svelte-vscode`
- Extension Version: `105.18.1`
- OS Version: `Windows_NT x64 10.0.18363`
- VS Code version: `1.69.0-insider`

[svelte.svelte-vscode-unresponsive.cpuprofile.txt](https://github.com/sveltejs/language-tools/files/9019696/svelte.svelte-vscode-unresponsive.cpuprofile.txt)

**Comment by jasonlyu123** [comment]
Not sure what can we do with this cpuprofile. I didn't see anything to do with our code. Can I ask why did you get the conclusion that the extension is the problem? And what were you doing when the problems appear?

**Comment by Zaid-maker** [comment]
> Not sure what can we do with this cpuprofile. I didn't see anything to do with our code. Can I ask why did you get the conclusion that the extension is the problem? And what were you doing when the problems appear?

I was building my first Web app in svelte and I need syntax highlighting for the code so I got recommended with this extension and suddenly when I restart my editor it told me that this extension has some error so I click on show error and it prompts me to create a issue.

**Comment by jasonlyu123** [comment]
Can you reproduce the error? We need to know what exactly is the error to be able to help you.
