### ISSUE TITLE
Consider updating the Typescript target?

### ISSUE THREAD

**Issue by matthewmueller** [sveltejs/language-tools#155]
Currently the language server targets ES5: https://github.com/sveltejs/language-tools/blob/master/packages/language-server/tsconfig.json#L3

This includes all sorts of interesting code to deal with async/await. Can we assume that the editor is using a sufficiently modern node.js?

**Update** Sorry this should be a feature, not a bug.

**Comment by dummdidumm** [comment]
@orta anything that speaks again bumping this to ES2018? Even Node 10 supports almost everything of that (https://node.green/#ES2018).

**Comment by orta** [comment]
Yeah, that's fine 👍  (plus you've find out pretty quickly if it's wrong, given that everyone has the same vscode build basically)

**Comment by orta** [comment]
Use https://github.com/tsconfig/bases#node-12-tsconfigjson
