### ISSUE TITLE
Arranged imports from code actions misses space in-between

### ISSUE THREAD

**Issue by CrendKing** [sveltejs/language-tools#1579]
### Describe the bug

When I use the "Organize Imports" code action on a svelte file, the items in the braces is only delimited by `,`, not `, `.

### Reproduction

1. `import { a, b, d, c } from './Foobar.svelte'`
2. Right click -> Source Action -> Organize Imports
3. It becomes `import { a,b,c,d } from './Foobar.svelte'`

### Expected behaviour

`import { a, b, c, d } from './Foobar.svelte'`

### System Info

- OS: Windows 11
- IDE: VSCode 1.17.0

### Which package is the issue about?

Svelte for VS Code extension

**Comment by ZerdoX-x** [comment]
I guess it should somehow preserve formatting, rather than placing spaces.
Otherwise after this issue being fixed some other guy would open issue about unwanted spaces after executing "Organize imports".

**Comment by CrendKing** [comment]
I saw this repo ([e.g.](https://github.com/sveltejs/language-tools/blob/master/packages/typescript-plugin/src/svelte-sys.ts)) uses space in its imports all the time, so I thought it's some kind of coding style convention in Typescript. To me, it's much more difficult to distinguish each name without the space. But if that's not universally accepted standard, then I guess either won't fix this, or provide a config to satisfy everyone.
