### ISSUE TITLE
await ',' expected. js(1005)

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/language-tools#158]
**What does this mean?**

![image](https://user-images.githubusercontent.com/41120635/83662137-6af90100-a5c7-11ea-82ad-11c215a9e537.png)

Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
Plugin/Package: Svelte Beta 99.0.33 in VSCode

**Comment by dummdidumm** [comment]
Cannot reproduce from your snippet. Can you post the complete contents of the file?

**Comment by jasonlyu123** [comment]
I can reproduce it in the current version but not debug build of master.  Maybe it's fixed somehow as a side effect by #154?

**Comment by dummdidumm** [comment]
Yeah maybe. @frederikhors could you try again in about 24 hours?

**Comment by dummdidumm** [comment]
Ok the error still appears, and it's because for some reason `svelte2tsx` is stuck at and old version, I think the last one before the update to the await was released. Seems like `svelte2tsx` npm publish stopped working? Maybe that's the reason, because `svelte` is now at a newer version, but `svelte2tsx` is at an old version. @orta could you check?

**Comment by orta** [comment]
interesting, the deploys should be using the built version from the repo

**Comment by dummdidumm** [comment]
Looked at the release dates of the npm packages of `svelte2tsx` and `language-server` as well as the Svelte Beta extension. Seems like everything stopped deploying 4 days ago. Last deploy of all of them is June 3rd.

**Comment by jasonlyu123** [comment]
Maybe the ci environment's node version needed to be changed to node 12? 
The log logged fail because of syntax errors in build and test

**Comment by dummdidumm** [comment]
Oh that could indeed be a possible solution. I did bump to es2018 lately. I will push it to 12.x (new LTS).

**Comment by dummdidumm** [comment]
Fixed.

**Comment by PatrickG** [comment]
Im getting this this error when using `this` and `bind:this` attributes on a `svelte:component` element.

```
<script>
  let component;
  let instance;
</script>

<svelte:component this={component} bind:this={instance} />
```

**Comment by dummdidumm** [comment]
Could you open a separate issue for this? Seems like an unrelated problem.

**Comment by frederikhors** [comment]
@PatrickG I have no problem with your code.

**Comment by PatrickG** [comment]
I've created a [new issue](https://github.com/sveltejs/language-tools/issues/192)
