### ISSUE TITLE
[Question] svelte-check: how do I ignore deprecation hints?

### ISSUE THREAD

**Issue by ZerdoX-x** [sveltejs/language-tools#1581]
Usecase:
I am aware that x feature is deprecated and I don't want to see hint about it as I am using deprecated feature only for backwards compatibility.

Code example:
```js
// https://erikmartinjordan.com/navigator-platform-deprecated-alternative
const platform = navigator?.userAgentData?.platform || navigator?.platform;
```

**Comment by dummdidumm** [comment]
We rely on TypeScript to show these kinds of intellisense, and AFAIK there is no way to turn that off - sorry, nothing we can do here, so closing this.
