### ISSUE TITLE
auto-import imports are wrong

### ISSUE THREAD

**Issue by IzKuipers** [sveltejs/language-tools#1588]
### Describe the bug

When using VSCode auto-import with Svelte files, the imports start with `src/` (e.g. `src/lib/Path/To/File.svelte` instead of using relative paths (e.g. `../../Path/To/File.svelte`).

IntelliSense does not acknowledge the issue and assumes everything is working as it should. Vite on the other hand can't find the file you imported because the import path starts with `src/`.

I've been told this behavior is like this because of SvelteKit intergration, but I'm not using SvelteKit.

### Reproduction

In a Svelte file, try referring a function, and importing it using auto-completion or auto-import in Visual Studio Code.

The result is an import statement that looks like this:
```ts
import SomeSvelteFile from "src/lib/Path/To/File.svelte";
```
The `src/lib` should not be there, it should be using `../` instead.

### Expected behaviour

When using auto-import to import anything in Svelte files, I expect the paths to use `../` instead of starting the path at `src/`. When it uses  `src/` in the import path Vite will error out saying the file could not be found.

### System Info

- OS: Windows 10 Pro 21H2 (OS Build 19044.1889)
- IDE: Visual Studio Code 1.70.0
- Dependencies: Vite 3.0.2, normal svelte ^3.49.0

VSCode About Box:
```
Version: 1.70.0 (user setup)
Commit: 6d9b74a70ca9c7733b29f0456fd8195364076dda
Date: 2022-08-10T06:08:33.64 (4 days ago)
Electron: 18.3.5
Node.js: 16.13.2
V8: 10.0.139.14-electron-0
OS: Windows_NT x64 10.0.19044
```

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

code suggestions shows the `src/lib/` path:
![Code suggestions](https://user-images.githubusercontent.com/76709090/184551554-2517ca4a-e67b-46c2-97b3-b7cc433eef11.png)

VSCode uses that _wrong_ path:
![Import statement](https://user-images.githubusercontent.com/76709090/184551565-22323fb8-4c3f-4a33-8f11-9da422855ed9.png)

Meanwhile Vite is not happy about it:
![image](https://user-images.githubusercontent.com/76709090/184551680-d54ed952-374b-4d62-b9be-7374d819f607.png)

**Comment by dummdidumm** [comment]
How does your tsconfig look like. I guess there's a `baseUrl` property in there, which triggers this behavior. From typescript's standpoint that import is therefore correct.

**Comment by IzKuipers** [comment]
My `tsconfig.json` file is unmodified since it's creation using `yarn create vite .`. Here it is:

![image](https://user-images.githubusercontent.com/76709090/184552349-fbc98009-0b48-49cd-a0e6-8789367dc334.png)

**Comment by jasonlyu123** [comment]
Did you have a `typescript.preferences.importModuleSpecifier` or `typescript.preferences.importModuleSpecifier` config set to `non-relative`? If so it would use the `paths` config in your tsconfig or a relative path to the `basUrl`. It doesn't seem like you have any `paths` config so it would always use the latter. 

> I've been told this behavior is like this because of SvelteKit intergration

Sometimes a svelte kit project does would have `src/...` auto import but it probably isn't related to your problem.

**Comment by dummdidumm** [comment]
The culprit is `"baseUrl": "."`. As I said previously, this makes TypeScript believe that imports starting with `src` are valid. Remove it and the auto imports will be correct.
