### ISSUE TITLE
Wierd word wrapping at 80 columns

### ISSUE THREAD

**Issue by mgholam** [sveltejs/language-tools#1599]
### Describe the bug

I have the following line in the svelte template, which is more than 80 columns, and it breaks the line at strange places
```svelte
      <button class="button-primary" style="margin-top:20px;" on:click={submit}
        >Send</button
      >
```
I have played around with 
```js
    "editor.wordWrap": "wordWrapColumn",
    "editor.wordWrapColumn": 120,
    "editor.wrappingStrategy": "advanced",
```
but it persists

### Reproduction

Just paste the above code

### Expected behaviour

Something like the following at least:
```svelte
      <button class="button-primary" style="margin-top:20px;" on:click={submit}>
        Send
      </button>
```

### System Info

- OS: linux
- IDE: VSCode

### Which package is the issue about?

Svelte for VS Code extension

**Comment by dummdidumm** [comment]
The extension is using prettier for formatting the code using https://github.com/sveltejs/prettier-plugin-svelte . You can look into its readme to see how to configure this. Your case would be `printWidth: 120` in a `.prettierrc` file. That readme also explains the word wrapping behavior around tags and how to disable it.

**Comment by mgholam** [comment]
I'm building with `vite` and there is no `prettier` in the node modules folder.
```
{
  "name": "timesheet-app",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "devDependencies": {
    "@sveltejs/vite-plugin-svelte": "^1.0.1",
    "svelte": "^3.49.0",
    "vite": "^3.0.7"
  }
}
```

**Comment by dummdidumm** [comment]
The extension bundles prettier and prettier-plugin-svelte, so that it doesn't need it to be present in the `package.json` (but it will use the one in there, if it exists).

**Comment by mgholam** [comment]
Thanks a lot. As a note for others, the following `.prettierrc` file worked and produces the expected output:
```json
{
"printWidth": 80,
"htmlWhitespaceSensitivity":"ignore"
}
```
