### ISSUE TITLE
Property 'fetchpriority' does not exist on type 'HTMLProps<HTMLImageElement>'

### ISSUE THREAD

**Issue by The-Noah** [sveltejs/language-tools#1600]
I'm using the `fetchpriority` property on an `<img>` tag and it is causing svelte-check to error.

```svelte
Error: Type '{ src: string; alt: string; fetchpriority: string; }' is not assignable to type 'HTMLProps<HTMLImageElement>'.
  Property 'fetchPriority' does not exist on type 'HTMLProps<HTMLImageElement>'. (ts)
    <img src={utils.getAvatarURL(profile)} alt={profile.username} fetchpriority="high" />
```

MDN source: https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/fetchPriority

**Comment by jasonlyu123** [comment]
According to MDN, This is an experimental attribute with poor browser compatibility. I think we will add this later. In the meanwhile, you can add a typedef to enhance it. Read more here: https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/typescript.md#im-using-an-attributeevent-on-a-dom-element-and-it-throws-a-type-error

Do keep in mind that we'll have a new way to enhance typing in the coming weeks. I'll add an update then.

**Comment by effulgentsia** [comment]
Chrome and Safari now support it. Thank you for the link in the above comment, which looks like the contents in there were updated in late 2022 as promised. That seems like a reasonable way to use `fetchpriority` until this issue is fixed.

**Comment by jasonlyu123** [comment]
The type for `fetchpriority` is added in [svelte 4.2.10](https://github.com/sveltejs/svelte/releases/tag/svelte%404.2.10). Update your local svelte version to the latest should solve it. But if you're still using Svelte 3 and prefer to update later, you'll have to enhance the type with the method linked above. The types of elements are moved to the svelte core and are no longer tracked in language tools.
