### ISSUE TITLE
Support Typescript casting/assertion

### ISSUE THREAD

**Issue by Jojoshua** [sveltejs/language-tools#1603]
### Description

There are several times where you need to cast a property inside the svelte template to get rid of TypeScript errors, but doing this inside the svelte template doesn't work.

Examples:
`{#if x == y  AS someType}`

`bind:this="{myArray[field.id as string]}"`

`bind:this="{myArray[<string>field.id]}"`

### Proposed solution

I would like to have some support for casting/assertion preferably with the **as** operator

### Alternatives

Ignore typescript errors per single line but this doesn't work in the svelte template either

**Comment by dummdidumm** [comment]
This needs https://github.com/sveltejs/svelte/issues/4701 to land first

**Comment by dummdidumm** [comment]
TS is supported in the template in Svelte 5
