### ISSUE TITLE
Every HTML element in .svelte files is marked as error

### ISSUE THREAD

**Issue by miloraczkowski** [sveltejs/language-tools#1610]
### Describe the bug

Today when I opened VS code editor started marking every HTML element in .svelte files as error. Looks like issue with Svelte for VS code extention because this error doesn't occur in any shape or form in files diffriend then .svelte files.

When I hover over HTML elements editor shows errors like:

`Argument of type '"div"' is not assignable to parameter of type 'null | undefined'.ts(2345)`

`Argument of type '"svg"' is not assignable to parameter of type 'null | undefined'.ts(2345)`

![VS Code Svelte Bug 30 08 2022](https://user-images.githubusercontent.com/73033104/187311838-87463290-ba7c-4b87-8c3f-aded64b110e7.png)

And so on. This bug occured out of nowhere, everything was working fine when I was working on my project yesterday. I'm using official Svelte extension, not the old one and I have no other Svelte related extentions enabled.

### Reproduction

Just opened VS code and bug happened out of nowhere. It occures in every .svelte file that has HTML in it.

### Expected behaviour

HTML elements should not be market as errors in .svelte files.

### System Info

Windows 10
VS code 1.70.2
Node 16.15.0
NPM 8.15.1
Svelte ^3.44.0
Svelte for VS Code 105.22.0

**Comment by jasonlyu123** [comment]
Sorry about the inconvenience. The release missed a new type definition file. Fixed in 105.22.1
