### ISSUE TITLE
webpack plugin fro type checking 

### ISSUE THREAD

**Issue by pociej** [sveltejs/language-tools#1612]
Im trying to build project using  svelte with typescript and build it with webpack. Problem I met is that Im unable to catch the typescript error on webpack level. Of course VSC highlights the errors, but what I want to achieve is to force webpack not to build if there is typescript error in `.svelte` file. https://github.com/sveltejs/svelte-loader/issues/211 here we see recommendation to use `svelte-check` but as far as iIudnerstand this is cli. Isn't there webpack plugin that allows catching errors during build ?

**Comment by dummdidumm** [comment]
There is not, and there will be none. Run `svelte-check` as a step prior to your build step (for example `svelte-check --tsconfig ./tsconfig.json && cross-env NODE_ENV=production webpack` and you should be fine.

**Comment by pociej** [comment]
@dummdidumm sure I can, and I will do but this is sounds a bit scary. Look you have `.svelte` and `.ts` files in you project. I think it is natural to have single source of truth and you can just run `webpack-cli (or any builder you want) --someFlags` and don't care for separate type checking for svelte and .ts files. Also, I dont understand one more thing. Svelte is able to compile `.svelte` files with `lang="ts"` why not catch the errors on compilation ? Because of speed?

**Comment by dummdidumm** [comment]
Today, many tools like Vite or the Svelte compiler separate type checking from building/compiling. It's not about a single source of truth, it's about separation of concerns. You can use `svelte-check` to check your Svelte _and_ your TypeScript files by the way, see its `tsconfig` option which you can use like `svelte-check --tsconfig ./tsconfig.json`

**Comment by pociej** [comment]
@dummdidumm great that makes perfect sense. My mind was sticked to structure where I have to keep and pass tsconfig separately to webpack (ts) and svelte-check (.svelte).
