### ISSUE TITLE
udate peerDependency svelte to latest

### ISSUE THREAD

**Issue by cbaarendse** [sveltejs/language-tools#1614]
In a project I work with Meteor & Svelte & Typescript. To flag any type issues I use svelte-check. 
The peerDependency 'svelte' in svelte-check has a version of 3.24.0, while Svelte is already on 3.49. I need to downgrade my Svelte version to 3.24.0 to keep things working. 
Is there any chance the peerDependency 'svelte' can be updated?

**Comment by dummdidumm** [comment]
The peerDependency is set to `^3.24.0` which means "you can use 3.24 or higher". Could you clarify why it doesn't work for you then?
