### ISSUE TITLE
Types for the module

### ISSUE THREAD

**Issue by lukaszpolowczyk** [sveltejs/language-tools#1615]
### Description

Can language-tools provide types to module properties?

The idea is to detect a file with such a name, and then automatically add types to them:
![obraz](https://user-images.githubusercontent.com/16800535/187975910-63b3f77a-b2ee-461e-b20d-5a45f529e22d.png)

Surely it is possible to recognize, for example, the `manifest.json` file from Web Extensions, and then all the properties of the json file have types.
Is it possible to do this for a file that is a module?

---

Now for the `load` function, the types need to be added by adding them visibly, in the module file.

The question is, does TypeScript/language-server/VSCode give such possibilities?
Or will it give such possibilities in the future?

### Proposed solution

Detecting modules by name, and adding their types.

**Comment by dummdidumm** [comment]
This isn't possible. You can only type global variables with ambient type definitions, everything else needs a proper type import to be scoped to a specific type.

**Comment by lukaszpolowczyk** [comment]
@dummdidumm Is this a good practice?:

![obraz](https://user-images.githubusercontent.com/16800535/187979611-e03c5cfa-3ef7-4a92-bb7a-9ec9c11ce085.png)

**Comment by dummdidumm** [comment]
Well it's the only possible way if you want to type this. In this specific case I wouldn't bother adding types since they are primitives (booleans and strings)

**Comment by lukaszpolowczyk** [comment]
@dummdidumm I know, but it's with the idea that when someone first sees the code, they'll know what it's for, and that it's only for something.
(In theory, I'd like something like `/** @type {import('@sveltejs/kit').Prerender */`, which would primarily say what it's for, and that it's not like my exported variable, but something related to SvelteKit.

But it would be better if the prompts generated themselves, not that you have to add them in a visible way.
I know it's not very important, but it's a shame that it can't be done.
