### ISSUE TITLE
JSDoc `@typedef` and import in component tag script

### ISSUE THREAD

**Issue by lukaszpolowczyk** [sveltejs/language-tools#1618]
### Describe the bug

This code works well (no `import`):

```svelte
<script>
  export /** @type {string} */ let symbol;
  /**
  * @typedef { [string,string] } Baa
  */
  
  /** @param {Baa} baa */
  const fromBaa = (baa)=>`${baa[0]}${symbol}${baa[1]}`;
</script>
```

It also works well (`import` only before `@typedef`):

```svelte
<script>
  export /** @type {string} */ let symbol;
  import '';
  /**
  * @typedef { [string,string] } Baa
  */
  
  /** @param {Baa} baa */
  const fromBaa = (baa)=>`${baa[0]}${symbol}${baa[1]}`;
</script>
```

And it works well, too (`import` before and after `@typedef):

```svelte
<script>
  export /** @type {string} */ let symbol;
  import '';
  /**
  * @typedef { [string,string] } Baa
  */
  import '';
  
  /** @param {Baa} baa */
  const fromBaa = (baa)=>`${baa[0]}${symbol}${baa[1]}`;
</script>
```

**But this code is working wrong** (`import` only before `@typedef):

```svelte
<script>
  export /** @type {string} */ let symbol;
  /**
  * @typedef { [string,string] } Baa
  */
  import '';
  
  /** @param {Baa} baa */
  const fromBaa = (baa)=>`${baa[0]}${symbol}${baa[1]}`;
</script>
```

This error:

```
Cannot find name 'Baa'.js(2304)
```

Conclusion:  
You can't use `typedef` at the beginning of the `script` tag when there is some `import` after it.

### Reproduction

Just use the code from the example, and use in some component in SvelteKit.

### Expected behaviour

Please fix this to be able to use `typedef` etc. JSDoc, already at the beginning of the `script` tag.

### System Info

- OS: Arch Linux
- IDE: VSCode

### Which package is the issue about?

svelte-check

**Comment by jasonlyu123** [comment]
Just a side note unrelated to the root problem. Your JSDoc should be before the `export` keyword. It only works because of how we transform code behind the scene. And I can't guarantee it won't change in the future. It also doesn't work in a normal js file.

**Comment by lukaszpolowczyk** [comment]
> Your JSDoc should be before the export keyword. It only works because of how we transform code behind the scene.

@jasonlyu123 This JSDoc code was generated by the quick fix -> Infer type function:

https://user-images.githubusercontent.com/16800535/188414934-7094443a-7df6-4788-b673-9d9441cc20e3.mp4

In js file Infer type prompts correctly:

https://user-images.githubusercontent.com/16800535/188416489-4fd8f46f-22d8-4ad4-b93a-abcaeb026247.mp4

Is it you that needs/can/should fix it?

This should be a separate issue?

**Comment by lukaszpolowczyk** [comment]
@jasonlyu123 In VSCode everything works very well, VSCode Problems Panel does not display any errors, no error hints.

But when using `svelte-check`, it returns errors, as if this fix is not there at all for `svelte-check`.

This is completely separate, and you need to make a fix also for `svelte-check`?

**Comment by dummdidumm** [comment]
I forgot to do a release for `svelte-check` which includes this change, will do that today.
