### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ABSTRAC7ION** [sveltejs/language-tools#1624]
- Issue Type: `Performance`
- Extension Name: `svelte-vscode`
- Extension Version: `105.22.1`
- OS Version: `Windows_NT x64 10.0.18363`
- VS Code version: `1.71.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/barho/AppData/Local/Temp/svelte.svelte-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by jasonlyu123** [comment]
Please provide more information like what are doing when the performance issue happens. Otherwise, we can not help you.

**Comment by jasonlyu123** [comment]
I am going to close this. If you have a problem with performance, Please open the issue with GitHub instead of VSCode UI. You need to follow the issue template and provide actual information that we can use to find the problem.
