### ISSUE TITLE
moving a `.svelte` file incorrectly updates relative imports

### ISSUE THREAD

**Issue by s3812497** [sveltejs/language-tools#1625]
### Describe the bug

Whenever I move a `.svelte` file, any import that uses a relative path such as `./$types` (which is common in sveltekit) gets automatically updated to something incorrect.

Currently, there is no option to turn off automatic import updates, when moving a `.svelte` file, to avoid this problem.

Ideally, there would be options for `prompt`, `always`, and `never` similar to the TypeScript extension setting `typescript.updateImportsOnFileMove.enabled`.

### Reproduction

Before moving from `src/routes/a/b`:
<img width="631" alt="CleanShot 2022-09-07 at 22 27 29@2x" src="https://user-images.githubusercontent.com/54401897/188903748-d8a420a4-66b9-4fa6-ab3e-5df48ad50846.png">

After moving to `src/routes/b`:
<img width="941" alt="CleanShot 2022-09-07 at 22 28 42@2x" src="https://user-images.githubusercontent.com/54401897/188904032-82fb2285-89c9-4fd9-a20e-18ef412a16ff.png">

### Expected behaviour

It should either resolve to the correct relative path, or not change it at all (if updating is disabled).

<img width="943" alt="CleanShot 2022-09-07 at 22 31 56@2x" src="https://user-images.githubusercontent.com/54401897/188904741-70cc75ee-d168-4c4b-b471-fe97fb3e63c6.png">

I don't think there's a way to keep SvelteKit generated types as `'./$types'` as it doesn't exist until the types are generated again.

### System Info

- OS: macOS Monterey 12.5.1 (21G83)
- IDE: VSCode

**Comment by dummdidumm** [comment]
For `./$types`: Strictly speaking this is the correct behavior - the import is updated to the previous location. In this specific case though it's undesired because you of course want to continue referencing the relative `./$types`. Not sure if we can find a good way to make this work reliably, it's probably a heuristic.

For the other import: This indeed looks like a wrong import update

**Comment by williamviktorsson** [comment]
Perhaps related.. I experience an inconsistency when accepting import suggestions. Is it possible to always suggest ActionData/PageData and other similar imports to always suggest `'./$types' ` rather than `.svelte-kit/types/src/.../$types'` :-) ?

**Comment by williamviktorsson** [comment]
> This is unrelated, please open a new issue for that with more details. We implemented something for autocompletion to address this already, but maybe it has some rough edges.

Thank you. Will do if I can figure out in what cases it happens.

**Comment by s3812497** [comment]
> Perhaps related.. I experience an inconsistency when accepting import suggestions. Is it possible for ActionData/PageData and other similar imports to always suggest `'./$types' ` rather than `.svelte-kit/types/src/.../$types'` :-) ?

I have opened a PR for that here https://github.com/sveltejs/kit/pull/6642
