### ISSUE TITLE
Svelte Bracket New Line is being ignored

### ISSUE THREAD

**Issue by moalamri** [sveltejs/language-tools#1634]
### Describe the bug

The extension formatter will ignore this option even if there's no formatter extension installed or any prettier configuration file.
I have disabled all extensions except for this one. Also pretty sure there's no editor's formatter or any sort of prettier config file in the project.

### Reproduction

Use the extension's formatter

### Expected behaviour

To respect the configuration settings

### System Info

- OS: Windows 10 (11)
- IDE: VSCode

### Which package is the issue about?

Svelte for VS Code extension

**Comment by dummdidumm** [comment]
Can't reproduce this. Make sure that there's no config file above the workspace you have opened (Prettier takes those into account, too) and also that there's no other config file that Prettier uses (like `.editorconfig`). It may also be that this only doesn't work for specific tags, in which case this hints at the whitespace sensitivity gotcha: https://github.com/sveltejs/prettier-plugin-svelte#svelte-bracket-new-line
