### ISSUE TITLE
chroma-js methods not detected in VS Code

### ISSUE THREAD

**Issue by ianengelbrecht** [sveltejs/language-tools#1635]
### Describe the bug

After `import chroma from 'chroma-js'` in a .svelte file in VS code, intellisense doesn't give me the methods that should be available on `chroma`, e.g. scale, etc. The code still runs fine if I use the chroma methods. 

### Reproduction

Add `import chroma from 'chroma-js'` in the script tag in a .svelte file. Then type `chroma.` to see the list of options. Here, .scale and other methods of chroma are not available. 

### Expected behaviour

Expected to see the methods on chroma. For the full list of methods see [the chroma docs](http://vis4.net/chromajs/)

### System Info

- OS: [Windows]
- IDE: [VSCode]

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

I don't know whether this an issue with the Svelte VS Code extension, or with chroma-js itself. I've posted an issue there too, with a screenshot of what I see in VS Code intellisense, see [https://github.com/gka/chroma.js/issues/261](https://github.com/gka/chroma.js/issues/261)

**Comment by jasonlyu123** [comment]
They didn't provide TypeScript definition files. And we didn't support automatic type acquisition like VSCode's TypeScript/JavaScript support. So this is the expected behaviour. You'll have to install `@types/chroma-js` to get IntelliSense,
