### ISSUE TITLE
Cannot overwrite across a split point

### ISSUE THREAD

**Issue by len0xx** [sveltejs/language-tools#1638]
### Describe the bug

I get this error `Cannot overwrite across a split point ts(-1)` in just a few .svelte files.
This issue is probably relevant to extension version 106.0.0. Because when I use 105.22.1 (the last one before 106.0.0) the problem doesn't occur. And I'm pretty sure there's nothing wrong with my TypeScript or code in the file in general.
![image](https://user-images.githubusercontent.com/21990466/190407433-7560ee2f-ce4e-417d-8752-9c612f115ddc.png)

### Reproduction

To reproduce you can use this code:
```html
<script lang="ts">
    import { Button, AjaxForm } from '$components'
    let success = false
    let errorText = ''
    const handleSuccess = () => success = true
    const handleError = (event: CustomEvent) => errorText = event.detail.error
</script>

<div class="white-block authorization-block">
    <h2>Log in to your accound</h2>
    <AjaxForm action="/api/auth/login" method="POST" on:success={ handleSuccess } on:error={ handleError }>
        { #if success }
            <p class="success">You're successfully logged in!</p>
        { :else if errorText }
            <p class="error">{ errorText }</p>
        {/if }
        <label for="email">Email:</label><br>
        <input class="form-control" type="email" name="email" required><br>
        <label for="password">Password:</label><br>
        <input class="form-control" type="password" name="password" required><br>
        <div class="align-center">
            <Button variant="primary">Log in</Button>
        </div>
    </AjaxForm>
</div>
```

HOWEVER If you remove these lines:
```svelte
{ #if success }
    <p transition:slide={{ duration: 200 }} class="success">You're successfully logged in!</p>
{ :else if errorText }
    <p transition:slide={{ duration: 200 }} class="error">{ errorText }</p>
{/if }
```

Then the error doesn't show up any more. And I have noticed this issue occurs because of { if/else } blocks in other files as well.

### Expected behaviour

I expect it to be no errors in this file. Because everything is correct: both for svelte part and the typescript one.

### System Info

- OS: macOS 12.5.1
- CPU: M1 Pro (aarch64)
- IDE: VSCode 1.71.0

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

![IMAGE 2022-09-15 17:51:25](https://user-images.githubusercontent.com/21990466/190408269-154ae100-83ce-45ba-b685-5a9606d08fe3.jpg)

**Comment by mjadobson** [comment]
I'm getting this same error with the following file contents:

```svelte
<script lang="ts">
  let posts = [];
</script>

{#each posts.map(function (a) {}) as post}
  {post}
{/each}
```

Removing the arguments from the function def or using an arrow function stops the error.
