### ISSUE TITLE
Imported function definitions are not shown in Sublime Text LSP

### ISSUE THREAD

**Issue by ehzro3** [sveltejs/language-tools#1651]
### Describe the bug

I'm working on Svelte with Sublime Text 4 and LSP plugins. And `import { foo } from 'module'` in a `*.svelte` file doesn't get the definition. It works fine when the function is local to the `*.svelte` or imported between `*.js` files.

<img width="434" alt="Screen_Shot_2022-09-20_at_23 29 06" src="https://user-images.githubusercontent.com/40330010/191519166-17cb98dc-2753-4f58-ae67-012f3a5e193a.png">
<img width="528" alt="Screen_Shot_2022-09-20_at_23 29 23" src="https://user-images.githubusercontent.com/40330010/191519170-a1fe053c-9d88-4eb9-bd3a-cc147373b5f3.png">

### Reproduction

# Sublime Text 4 plugins

- LSP
- LSP-svelte
  - Contains `svelte-language-server`

# Relevant `devDependencies`

- "@sveltejs/adapter-node": "^1.0.0-next.88",
- "@sveltejs/kit": "next",
- "svelte": "^3.48.0",
- "svelte-preprocess": "^4.10.7",
- "vite": "^3.1.0-beta.1"

### Expected behaviour

I get the definition: JSDoc and function body in declaration, when I hover cursor on them.

### System Info

- OS: MacOS Monterey 12.6 (21G115)
- IDE: Sublime Text 4126

### Which package is the issue about?

svelte-language-server

**Comment by jasonlyu123** [comment]
I think it's more likely this is some config problem or an external module can't be found instead of a bug on our side. If you add a // @ts-check comment at the top of the script tag. Like 
```svelte
<script>
// @ts-check

// ... rest of your code
</script>
```

Would there be any errors?

**Comment by ehzro3** [comment]
> ```svelte
> // @ts-check
> ```

Yes, it says `Cannot find module '$lib/utils` or its corresponding type declarations.`
The error resolves and definition appears with `/Users/taro/feder/src/lib/utils.js`.
But it persists with `/src/lib/utils.js`

What configuration should I do? I tried `jsconfig.json` but no luck.

**Comment by jasonlyu123** [comment]
What does your jsconfig.json look like? svelte kit should already set up the config for you.

**Comment by ehzro3** [comment]
You are right, getting `jsconfig.json` right solved everthing. I think I messed up `"extends": "./.svelte-kit/tsconfig.json"` oneday.

I copy/pasted the config from a new Svelte project and not it works fine, Thanks @jasonlyu123 !
