### ISSUE TITLE
Semicolon or block is expected tailwind

### ISSUE THREAD

**Issue by lacherogwu** [sveltejs/language-tools#1658]
### Describe the bug

I am getting an error when I try to add semicolon in the `<style>` tag
seems like VSCode can't read the `svelte.config.js` file

I'm using tailwindcss and I've tried to implement all from this doc [other-css-preprocessors](https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/other-css-preprocessors.md)

if the project is in the root workspace, everything works perfectly.
the issue occurs only if a sveltekit project is in a subdirectory.

<img width="1024" alt="Screen Shot 2022-09-22 at 16 24 39" src="https://user-images.githubusercontent.com/49835614/191795143-c43c49e5-73c0-4712-8d50-966054b60f22.png">

### Reproduction

1. Open VSCode anywhere
2. `npm create svelte`
3. When it prompts you to set a directory name, just give it some name
4. Which Svelte app template? Sveleton project 😄
5. Any settings are okay
6. `cd $DIR`
7. Install [Tailwind CSS](https://github.com/svelte-add/tailwindcss)
8. `npm i`
9. Write in any component a `<style>` tag with `@apply sm:text-red` or any tailwindclass with semicolon

### Expected behaviour

Error should not be presented

### System Info

- OS: MacOs
- IDE: VSCode

### Additional Information, eg. Screenshots

![image](https://user-images.githubusercontent.com/49835614/191797427-2cde22a2-f377-4f65-8fa2-fda7f002f649.png)
<img width="1024" alt="Screen Shot 2022-09-22 at 16 24 39" src="https://user-images.githubusercontent.com/49835614/191797451-15e7aa4f-91d4-45ff-b95a-404c12a45f43.png">

**Comment by jasonlyu123** [comment]
What exact config from the docs did you try? I didn't see any of it in your reproduction steps. You should be able to fix the error if you follow the docs.

**Comment by lacherogwu** [comment]
I have tried to implement the following
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/49835614/191902818-b61fe70f-b066-47aa-9530-eb69c4d07603.png">
But it didn't solve the issue,

the reproductions steps are very clear, you can try on your PC and I'm pretty sure you will experience the same

**Comment by jasonlyu123** [comment]
Did you follow the postcss docs? Both are needed.

**Comment by lacherogwu** [comment]
I didn't do that, my bad 🙃

thanks for your help, it solved my my issue!
