### ISSUE TITLE
SvelteKit commands should only be shown in SvelteKit projects

### ISSUE THREAD

**Issue by tony-sull** [sveltejs/language-tools#1664]
### Describe the bug

The new `SvelteKit: Create route` menus are being shown in every VS Code project when the Svelte for VS Code plugin is enabled.  Any chance this can be scoped down to only show when in a SvelteKit project, maybe by checking for a `svelte.config.js` file?

### Reproduction

Open any project in VS Code, make sure the Svelte for VS Code extension is enabled, and right click on a directory in the project explorer

### Expected behaviour

I'd expect the SvelteKit-specific menus to only show when a SvelteKit project is open

I'd really expect this in a separate VS Code extension since it is specific to SvelteKit rather than Svelte, but I'm sure that would lead to a pile of refactoring work or code duplication 🤷 

### System Info

- OS: OS X
- IDE: VS Code

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

<img width="600" alt="Screen Shot 2022-09-27 at 3 06 33 PM" src="https://user-images.githubusercontent.com/15836226/192627522-14a6902e-09e0-4609-b6a5-e2943d5d7f84.png">

**Comment by tony-sull** [comment]
Looks like the plugin adds commands to the Command Palette and TypeScript's autocomplete as well, it'd be ideal to see this only added conditionally in a SvelteKit project

Command Palette opened in a non-SvelteKit project
<img width="735" alt="Screen Shot 2022-09-27 at 3 28 20 PM" src="https://user-images.githubusercontent.com/15836226/192631319-202b3258-8450-48cc-8a3f-7e25cbaf99fa.png">

Auto-complete in Astro frontmatter (happens in any Typescript code)
<img width="968" alt="Screen Shot 2022-09-27 at 3 29 33 PM" src="https://user-images.githubusercontent.com/15836226/192631460-dcbd082b-6839-4395-89bf-34f6f558696d.png">

**Comment by dummdidumm** [comment]
I'm not sure this is possible. AFAIK VS Code only makes it possible to provide these things through the static package.json, so there's no way to dynamically turn it on or off.
I also think it's not too much of a problem. There are already hundreds of snippets/completions and commands, a few more don't change that. The only thing that _could_ get annoying is the menu entry.

**Comment by tony-sull** [comment]
It may very well be a limitation of the VS Code extension API, I'm not sure if it has any kind of filtering or enable/disable features for extension commands.  The menu entry is the most obvious one that at least for me is a bit annoying.

I'm totally fine if this issue needs to be closed as won't or can't fix, just thought it was worth feedback here :+1:

In most cases this can be avoided by only enabling the Svelte extension in SvelteKit projects, that might cover most people if the expectation is that Svelte is mainly used with SvelteKit these days

**Comment by r-thomson** [comment]
Does VSCode make it possible to enable/disable context menu items via a user setting? I don’t mind having the SvelteKit commands always in the command palette, but I’d definitely remove the “SvelteKit Files” context menu item if I had the option.
