### ISSUE TITLE
Postcss plugins not applied in validation when postcss-load-config is used by svelte.config.js

### ISSUE THREAD

**Issue by madeleineostoja** [sveltejs/language-tools#1668]
### Describe the bug

Some time ago `svelte.config.js` got support to just set `{ postcss: true } ` in `preprocess()` and use `postcss-load-config` to automatically load the user's `postcss.config.js`. This works great for compilation, but it seems language tools doesn't pickup on the PostCSS config, and features that work and are validated correctly when given plugins directly (eg: nesting, custom media) throw syntax errors when using automatic config loading in `svelte.config.js`.

The easy fix is to explicitly import the postcss config for `svelte.config.js` instead of relying on `postcss-load-config`, but in my particular case that breaks because I import a JSON file in my postcss config (for custom media queries) and `svelte.config.js` throws errors about not being able to parse JSON imports.

### Reproduction

1. Create a `postcss.config.js` with some plugins that are easy to validate for/against, eg: nesting and custom media
2. Create a `svelte.config.js` with `preprocess({ postcss: true })`
3. Compile code and see that it works
4. Open a file with postcss features in VS Code, see that it throws syntax errors

### Expected behaviour

Langauge tools should be able to load postcss config from a file like `svelte.config.js` does

### System Info

- OS: macOS
- IDE: VSCode

Latest versions of all

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

<img width="849" alt="Screen Shot 2022-09-30 at 2 04 28 PM" src="https://user-images.githubusercontent.com/6374876/193168093-e2db324d-7119-43eb-abeb-57f0751c1a67.png">

**Comment by jasonlyu123** [comment]
If your `svelte.config.js` isn't at the workspace root. Check the [docs](https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/other-css-preprocessors.md#postcss). Otherwise. Please provide a reproduction.

**Comment by madeleineostoja** [comment]
My bad! I am working in a monorepo and missed the `configFilePath` requirement
