### ISSUE TITLE
SCSS `@import` fails to resolve when project is not at root of workspace

### ISSUE THREAD

**Issue by j-tai** [sveltejs/language-tools#1670]
### Describe the bug

In a Sass stylesheet, `@import` fails to resolve when the Svelte app is not at the root of the VSCode workspace.

This code compiles perfectly fine, but displays an error in VSCode:
![image](https://user-images.githubusercontent.com/45131430/193490997-89932f57-5f8a-4901-abb6-11ceb6217d57.png)

### Reproduction

1. `mkdir repro && cd repro`
2. `npm create vite@latest` - set the project name to `foo` - select variant TypeScript
3. `cd foo && npm install -D sass @carbon/colors`
4. Open the `repro` directory (not `foo`) in VSCode
5. Paste the following code into any svelte file

```html
<p>Hello world</p>

<style lang="scss">
    @import '@carbon/colors';

    p {
        color: $red-40;
    }
</style>
```

### Expected behaviour

An error should not be displayed, because the code compiles successfully.

### System Info

- OS: Pop!_OS 22.04 LTS
- IDE: VSCodium 1.71.2

**Comment by jasonlyu123** [comment]
The language server process starts with a [working directory](https://en.wikipedia.org/wiki/Working_directory) where you open your editor. Which is different from your build. And the automatic search only applies to the root of the working directory. You will need to configure it with an absolute path for it to work. 

```js
//svelte.config.js
import sveltePreprocess from 'svelte-preprocess'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'
const __dirname = dirname(fileURLToPath(import.meta.url))

export default {
  // Consult https://github.com/sveltejs/svelte-preprocess
  // for more information about preprocessors
  preprocess: sveltePreprocess({
    scss: {
      includePaths: [
        join(__dirname, 'node_modules')
      ]
    }
  })
}
```

**Comment by j-tai** [comment]
@jasonlyu123 Thanks for the answer. I am wondering, why do I need to configure this? Why can't the Svelte plugin just start the language server in the correct directory?

**Comment by jasonlyu123** [comment]
There is only one language server process per editor window. If you don't want this behaviour you can open your editor in the subdirectory.

**Comment by j-tai** [comment]
If the language server is running in the wrong directory, then I am surprised that it works at all. How is it able to find `svelte.config.js`? How is it able to resolve JS imports? Everything seems to work fine *except* for Sass imports.

If having the app in a subdirectory is **unsupported** (and it just accidentally happens to work 99% of the time), then it would be good to notify the user. Maybe add warning message or something.

If it is supported, then I don't think I should have to configure this.

**Comment by jasonlyu123** [comment]
It's not "in the wrong directory". These preprocess are usually expected to be called in a working directory same as the `package.json`. So it would only check the relative path instead of traversing the file system. But a relative path is resolved relative to the working directory. So it sometimes needed to be configured to an absolute path.

The main problem you're facing is that we read a user config. But the config doesn't work in a subdirectory and the config is passed into svelte-preprocess. Even if we want to add a fallback, we can't. It isn't visible outside of the svelte-preprocess. 

I am not saying it's not supported. I am just saying if you don't want to configure anything. You can just open it in a subdirectory.

**Comment by dummdidumm** [comment]
It feels like this topic has come up very often in the past few weeks. We can't do anything about it but document it, which we already did, but maybe also explain in more detail (like you just did) why in some details section. Would safe us the trouble of having to reiterate this time and time again and instead just post a link to that explanation.
