### ISSUE TITLE
Possible literal values are not completed unless using `{'...'}` syntax when using `$$restProps`

### ISSUE THREAD

**Issue by brunnerh** [sveltejs/language-tools#1671]
### Describe the bug

Component props may have type information that restricts the values to a certain set of literals, commonly strings or numbers.
Currently these values are only completed when using curly bracket notation if the component uses `$$restProps`.

### Reproduction

Define a prop with a union type of strings, e.g.:

```typescript
export let alignItems: AlignItems = 'normal';
```
```typescript
// (type is simplified for the example)
export type AlignItems =
	'normal' | 'stretch' | 'baseline' |
	'center' | 'start' | 'end' |
	'self-start' | 'self-end' |
	'flex-start' | 'flex-end';
```
```svelte
<div style:display="flex"
	style:align-items={alignItems}
	{...$$restProps}>
	<slot />
</div>
```
```

Open code completion on the property when using `"..."`:

```svelte
<Component alignItems="|">...</Component>
```

![image](https://user-images.githubusercontent.com/834235/193735263-306281ef-7e1f-4de8-989c-543397f861ea.png)

### Expected behaviour

Auto complete shows possible string values when using `prop="..."` as it does when using `prop={'...'}`.

![image](https://user-images.githubusercontent.com/834235/193735051-f99338ba-aba1-436b-8296-7ebf3b5c9d45.png)

### System Info

- OS: Windows 10, 64bit
- IDE: VSCode

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

It will not complete values but still tell you when a value is wrong:
![image](https://user-images.githubusercontent.com/834235/193735718-72cae0c7-080b-4d89-a230-496aa62f89e7.png)

**Comment by jasonlyu123** [comment]
This only happens in the old (jsx) transformation, So I am taking the opportunity to gather feedback about the new transformation. Is there any reason you chose to go back to the old transformation?  Or did you just want to play it safe and deal with the change later? Would appreciate feedback about the new transformation.

**Comment by brunnerh** [comment]
@jasonlyu123 Looks like I turned off the new transform in this particular workspace quite a while ago; unfortunately I cannot tell you why. Maybe there were some issues or I just wanted to defer the switch at the time.

I now removed the setting and will report any problems I run into.
