### ISSUE TITLE
HTMLAttributes are the same for all elements

### ISSUE THREAD

**Issue by fallaciousreasoning** [sveltejs/language-tools#1673]
### Describe the bug

The type definitions in [svelte-jsx.d.ts](https://github.com/sveltejs/language-tools/blob/6509e3b77438ea091d435a12985d8deb462e1946/packages/svelte2tsx/svelte-jsx.d.ts#L655) for HTMLAttributes are the same for all elements.

### Reproduction

```svelte
<button open href="https://example.com">Foo</button> <!-- In React, this would result in some type errors, as href & open are not attributes of button -->
``` 

In Svelte this compiles fine.

### Expected behaviour

There should be a type error, saying something to the effect that button doesn't have an `href` or an `open` property.

### System Info

- OS: Linux
- IDE: VSCode

### Which package is the issue about?

svelte2tsx

### Additional Information, eg. Screenshots

Svelte
![image](https://user-images.githubusercontent.com/7678024/193921267-99ef8079-d92a-4ab8-9375-3c8d75f910a3.png)

React (only the first bad prop is highlighted at the moment, for some reason, I've attached the screenshot in both orders)
![image](https://user-images.githubusercontent.com/7678024/193921689-e7347e4b-7843-42ff-8232-b4e53971ebad.png)
![image](https://user-images.githubusercontent.com/7678024/193921729-ed03726f-85ad-46e6-86f0-2c491db73967.png)

**Note:** I think fixing this would be a breaking change, as we'd being making previously valid Svelte code invalid.

**Comment by dummdidumm** [comment]
If you switch to the new transformation you'll have attributes scoped per tag - see #1352 for more info.

**Comment by fallaciousreasoning** [comment]
So I've been playing around with the new transformation - the correct types are available when you're creating an element
![image](https://user-images.githubusercontent.com/7678024/198129632-ceb02a44-72cf-488d-ad1c-d69329417412.png)

But there is no way to use those types without importing them from `svelte2tsx/svelte-html-do-not-use`, which doesn't seem ideal.

Intellisense for a svelte button:
![image](https://user-images.githubusercontent.com/7678024/198129265-d5f04e11-2e44-4839-82e4-d28fb9e022d4.png)

However, this is what I actually want:
![image](https://user-images.githubusercontent.com/7678024/198130045-fbc64d5f-7113-44c5-8160-466aabd808ab.png)

I want to be able to extend the types of the default elements - currently however, the default element types are hidden.

**Comment by dummdidumm** [comment]
As of Svelte 3.55 you can import these from `svelte/elements`:

```ts
import type { HTMLButtonAttributes } from 'svelte/elements';

// ...
```
