### ISSUE TITLE
(meta) add husky git commit hook to lint on commit?

### ISSUE THREAD

**Issue by sw-yx** [sveltejs/language-tools#168]
**Is your feature request related to a problem? Please describe.**
i noticed the linting rules here are applied on PR - maybe better to catch them at commit time?

**Describe the solution you'd like**
use husky?

**Describe alternatives you've considered**
do nothing, possibly waste roundtrip time on PRs that fail linting

**Comment by ryanatkn** [comment]
This was discussed in #39 and it has some links to similar discussions in the Svelte repo.

**Comment by sw-yx** [comment]
ah hmm. so the ruling was no? that discussion didnt seemed inconclusive for commit hooks

**Comment by dummdidumm** [comment]
Yes, we decided against it, because the main repo also decided against it.
