### ISSUE TITLE
Prettier does not work on .svelte files

### ISSUE THREAD

**Issue by seonicklaus** [sveltejs/language-tools#1687]
### Describe the bug

I can't seem to get prettier to format my svelte codes unless I add the file associations which I was told to remove.

Without file association:
![No Prettier Settings](https://user-images.githubusercontent.com/78959887/196236320-ad2a6706-2ab8-4fbd-88c6-92007f02b221.png)
![No Prettier](https://user-images.githubusercontent.com/78959887/196236625-ea6ef741-37e7-48dd-9276-3eadd309f0fd.png)

I've checked the extension, I'm using Svelte for VS Code. I tried disabling other Svelte-related extensions as well but the issue still persist. How can I make this extension work as it is intended?

My other Svelte-related extensions are:
- Svelte 3 Snippets
- Svelte Intellisense

### Reproduction

As stated above.

### Expected behaviour

Would expect to work as inteded.

### System Info

- Windows 11
- VS Code

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

settings.json
``` settings.json
{
  "editor.formatOnPaste": true,
  "emmet.includeLanguages": {
    "javascript": "javascriptreact"
  },
  "prettier.jsxSingleQuote": true,
  "editor.autoClosingQuotes": "always",
  "editor.autoClosingOvertype": "always",
  "files.autoSave": "onFocusChange",
  "editor.wordWrap": "on",
  "prettier.endOfLine": "auto",
  "prettier.bracketSameLine": true,
  "prettier.tabWidth": 2,
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "javascript.updateImportsOnFileMove.enabled": "always",
  "editor.fontLigatures": true,
  "editor.fontFamily": "'GoMono NF','Fira Code', Consolas, 'Courier New', monospace",
  "editor.fontSize": 13,
  "workbench.editorAssociations": {
    "*.ipynb": "jupyter-notebook"
  },
  "notebook.cellToolbarLocation": {
    "default": "right",
    "jupyter-notebook": "left"
  },
  "workbench.colorTheme": "Atom One Dark",
  "python.defaultInterpreterPath": "/usr/bin/python3.10",
  "go.toolsManagement.autoUpdate": true,
  "terminal.integrated.defaultProfile.windows": "Git Bash",
  "workbench.iconTheme": "material-icon-theme",
  "bracket-pair-colorizer-2.depreciation-notice": false,
  "editor.tabSize": 2,
  "css.lint.unknownAtRules": "ignore",
  "kite.showWelcomeNotificationOnStartup": false,
  "editor.formatOnSave": true,
  "svelte.enable-ts-plugin": true,
  "svelte.plugin.svelte.note-new-transformation": false,
  "[svelte]": {
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "svelte.svelte-vscode"
  },
  "svelte.plugin.svelte.format.config.singleQuote": true,
  "svelte.plugin.svelte.enable": true
}
```
.prettierrc
```
{ 
	"useTabs": true,
	"singleQuote": true,
	"trailingComma": "none",
	"printWidth": 100,
	"plugins": ["prettier-plugin-svelte"],
	"pluginSearchDirs": ["."],
	"overrides": [{ "files": "*.svelte", "options": { "parser": "svelte" } }]
}

```

**Comment by dummdidumm** [comment]
Please provide more information about your project (are you using SvelteKit or sth else, which package manager are you using, is this a monorepo, etc), or ideally a minimum reproducible, the given description isn't enough to know what's happening.

**Comment by seonicklaus** [comment]
This is the demo project that I was asked to choose when I created the SvelteKit project, and I use the npm package manager. I did nothing else other than npm installing after creating the project.

**Comment by seonicklaus** [comment]
It looks like the project itself has to be one of my workspaces in order for prettier to work.
