### ISSUE TITLE
Don't format paragraphe html markup (<p></p>)

### ISSUE THREAD

**Issue by PlopTheReal** [sveltejs/language-tools#1696]
Is there is a way to prevent auto formatting of `<p></p>`?
It breaks the formating when css rule `white-space: break-spaces;` is used.

**Comment by dummdidumm** [comment]
Formatting is done with Prettier.

Use the `prettier-ignore` comment pragma for cases like this
```html
<!-- prettier-ignore -->
<p>...</p>
```
If you use that rule everywhere, consider adjusting this option https://prettier.io/docs/en/options.html#html-whitespace-sensitivity
