### ISSUE TITLE
Imports does not work

### ISSUE THREAD

**Issue by FarhanAliRaza** [sveltejs/language-tools#1700]
### Describe the bug

I created a new project with cli with ts and prettier.
When i start writing my component it auto imports but not according to lib folder it imports from import Nav from "src/lib/components/Nav.svelte";
that gives an error. 
but when i alt + click it takes me to the definition of a component.
When i correct the error by importing it form $lib/components/Nav.svelte .
Now app works fine but alt + click does not take me to the definition and also import statement has an red line under it .

### Reproduction

I created this repo for reprodcution [Repo](https://github.com/FarhanAliRaza/bug-reproduction-for-svelte-extension)
reproduction

### Expected behaviour

It should import according to lib folder.
alt + click should take me to the defination of the component.

### System Info

- OS:Ubuntu 22
- IDE: VS Code

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

![Screenshot from 2022-10-21 20-26-49](https://user-images.githubusercontent.com/62690310/197233692-f41c2c51-4f6c-43db-afee-072cb1bdd78d.png)

**Comment by dummdidumm** [comment]
That's very strange. I can't reproduce this given the repo. I'm using Windows and the latest version of VS Code + the extension. The `src/components/Nav.svelte` import being an error is due to https://github.com/sveltejs/kit/issues/5351 but `$lib/components/Nav.svelte` should work (and does for me).

**Comment by FarhanAliRaza** [comment]
i also figured these issues are with ts version of project.
I recreated the project with jsdocs.
Now it works as expected.
