### ISSUE TITLE
Use of discriminated unions for `$$Props` requires an additional "buffer" / dummy type

### ISSUE THREAD

**Issue by kelvindecosta** [sveltejs/language-tools#1702]
### Describe the bug

**When using discriminated unions for component prop types requires an additional dummy type to be defined.**

I have a use case that involves props being mutually exclusive.
I've decided to use discriminated unions for this purpose.

This is because direct use of the union causes errors.

### Reproduction

```ts
interface BaseAnimal {
  name: string;
  type: string;
}

interface Cat extends BaseAnimal {
  type: 'CAT';
  purrs: boolean;
}

interface Dog extends BaseAnimal {
  type: 'DOG';
  barks: boolean;
  }

type $$Props = Cat | Dog;

// This works:
// type Animal = Cat | Dog | Mouse;
// type $$Props = Animal;

export let name: $$Props['name'];
export let type: $$Props['type'];

export let purrs: 'CAT' extends typeof type ? Cat['purrs'] : never;
export let barks: 'DOG' extends typeof type ? Dog['barks'] : never;
```

Here's the error message:

```
Argument of type '$$Props' is not assignable to parameter of type '{ name: string; type: "CAT" | "DOG"; purrs: boolean; barks: boolean; }'.
  Property 'barks' is missing in type 'Cat' but required in type '{ name: string; type: "CAT" | "DOG"; purrs: boolean; barks: boolean; }'.ts(2345)
```

### Expected behaviour

The dummy type shouldn't be required.

### System Info

- OS: Linux
- IDE: VSCode

### Additional Information, eg. Screenshots

Alternatively, I'm open to other ways to write components that accept mutually exclusive props.

Any response is appreciated! Thank you for your time!

**Comment by jasonlyu123** [comment]
The `$$Props` should match the props implementation. We treat props without an initializer as required. And both of your `purrs` and `barks` don't have an initializer. That is why you must have `barks`. If I declare the `purrs` and `barks` as
```ts
export let purrs: boolean | undefined = undefined;
export let barks: : boolean | undefined = undefined;
```

The error goes away.

But I don't know how to achieve want. It's hard to find a solution for control flow to narrow the type of variable other than what you're checking. The easiest way I can think of is to just have an object props

```ts
export let animal: Cat | Dog;
```

**Comment by kelvindecosta** [comment]
Thank you for the reply!

I now understand the implementation better.
I think I'll take your suggestion to use an object prop rather than define a prop for each attribute.
