### ISSUE TITLE
folding range support

### ISSUE THREAD

**Issue by BigBoulard** [sveltejs/language-tools#1704]
Hi guys,

In a Svelte file, when params of a function are not on the same line, I can't fold the whole function. I can instead only fold the function params. 

```javascript
async function lambda(
    param1,
    param2,
    param3
  ) {
	const a = 1;
	const b = 2;
}
```

becomes

```javascript
async function lambda(
  ) {
  const a = 1;
  const b = 2;
}
```
instead of

```javascript
async function lambda() {}
```
Unlike `.svelte` files, it works perfectly on `.js` ones.

**Comment by jasonlyu123** [comment]
We'll need to implement the folding range feature for this. The current one is an indent-based solution provided by VSCode. 

Haven't tried it yet. But I am not sure if the result would be great given we have some limitations with our current approach for typescript features. We might not be able to calculate the folding range when there are syntax errors in the markup. Not sure if this would cause the folded range suddenly expand. If it did it is worse than not being able to fold a function.
