### ISSUE TITLE
`svelte-check`: `--threshold warning` still reports hints, except if `output` is set to `machine`

### ISSUE THREAD

**Issue by HEYGUL** [sveltejs/language-tools#1705]
### Describe the bug

While trying to get a report from `svelte-check` containing only warnings and errors, I found at first that the command always reports errors, warnings and hints.
Using `--threshold warning` option seems to have no effect.
After playing a bit with the command line, I finally found that specifying `--output machine` in addition to `--threshold warning` does not report hints.

### Reproduction

In https://github.com/SocialGouv/carnet-de-bord/tree/master/app.
Run 
```
svelte-check  --tsconfig ./tsconfig.json --threshold warning
```

Checking that no hints are reported fails:
```
[...]
Hint: Parameter 'event' implicitly has an 'any' type, but a better type may be inferred from usage. (ts)

====================================
svelte-check found 0 errors, 13 warnings, and 123 hints
```

### Expected behaviour

No line starting with `Hint`.
Report summary does not count any hints.

### System Info

- OS: macos Ventura 13.0
- IDE: vim 

### Which package is the issue about?

svelte-check

**Comment by dummdidumm** [comment]
I can't reproduce this given the description. Can you provide a reproduction repository?

**Comment by HEYGUL** [comment]
I am not able to reproduce it with latest version.
