### ISSUE TITLE
Hovering over components should show more info in hover documentation

### ISSUE THREAD

**Issue by PeytonHanel** [sveltejs/language-tools#1717]
### Description

When I hover over a component it doesn't show any documentation on props, slots, etc. For example, I have this code:

```
<!-- 
  @component
  
  A full height, 1/3 screen width frame with an image as a background meant to draw
  in the user's attention. Hovering over this slightly zooms in the image and animates
  in text and a button.
 -->

<script lang="ts">

  export let title = "Title"

  export let text = "Title"

  export let buttonText = "Title"

  export let backgroundImg

  /** Href is for the button. */
  export let href = '/'

  /**
   * A string containing a numerical value with a css unit (e.g. 100px) that
   * represents a distance to shrink the height by. This is useful if you want
   * to accommodate for a fixed header.
   */
  export let shortenBy = '84px'
</script>

<main class='h-[calc(100vh) - {shortenBy}] w-1/3 bg-slate-500'>
  <slot name='test'></slot>
</main>
```

But the hover docs (VSCode) don't show anything other than the top level documentation.

![image](https://user-images.githubusercontent.com/26446761/200659407-52b4b2c4-e8de-4548-81bf-95ee54e31605.png)

### Proposed solution

Show everything about the component in the documentation when hovering. This would make it easier to see at a glance without having to read the component code, and also prevents me from writing it out at the very top.

For example, the hover could display each prop with associated doc comment, including slots and anything else a developer might need to know about a component. For example:

```
(alias) class Preview
import Preview
A full height, 1/3 screen width frame with an image as a background meant to draw in the user's attention. Hovering over this slightly zooms in the image and animates in text and a button.

Props
title: string
text: string
buttonText: string
backgroundImg: any
href: string - Href is for button
shortenBy - A string containing a numerical value with a css unit (e.g. 100px) that represents a distance to shrink the height by. This is useful if you want to accommodate for a fixed header.

@slot test
```

### Alternatives

I'm open to ideas.

**Comment by jasonlyu123** [comment]
Essentially https://github.com/sveltejs/language-tools/issues/1308. I am closing this in favour of it.

**Comment by PeytonHanel** [comment]
Thank you, I didn't see that.
