### ISSUE TITLE
Incorrect error when using named slot variable name incorrectly: Element implicitly has an 'any' type because ...

### ISSUE THREAD

**Issue by qlp** [sveltejs/language-tools#1718]
### Describe the bug

Using a component with a named slot and declaring the variable on the tag (not in the slot), results in an unclear Error. This resulted in an invalid bug report: https://github.com/sveltejs/svelte/issues/8007

The Component:
```
<script lang="ts">
    export let items: number[];
</script>
{#each items as i}
    <slot name="item" it={i}/>
{/each}
```

The component using the component (uncomment the last line to 'fix' the Error)

```
<TestSum
        items={[1, 2, 3]}
        let:it={i}>
    <span slot="item">{i}</span>
</TestSum>
<!-- this 'solves' the check error -->
<!-- {#if false}{#each [] as _}&nbsp;{/each}{/if} -->
```

### Reproduction

- create svelte app
- add the components as described in the description
- run `npm run check`

See https://github.com/qlp/svelte-bug : I've only added the `src/lib` folder.

Output of running `check`:

```
$ npm run check

> svelte-bug@0.0.1 check
> svelte-kit sync && svelte-check --tsconfig ./tsconfig.json


====================================
Loading svelte-check in workspace: /Users/jpruijs/git/svelte-bug/svelte-bug
Getting Svelte diagnostics...

/Users/jpruijs/git/svelte-bug/svelte-bug/src/lib/ImportingComponentWithWarning.svelte:7:17
Error: Element implicitly has an 'any' type because expression of type '"default"' can't be used to index type '{ item: { it: number; }; }'.
  Property 'default' does not exist on type '{ item: { it: number; }; }'. (ts)
        items={[1, 2, 3]}
        let:it={i}>
    <span slot="item">{i}</span>
```

### Expected behaviour

Error that explains that slot variable declaration should be in the `slot` tag.

### System Info

System:
    OS: macOS 12.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 80.94 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.10.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
  Browsers:
    Brave Browser: 107.1.45.118
    Chrome: 107.0.5304.87
    Edge: 107.0.1418.35
    Firefox: 106.0.5
    Safari: 16.1
  npmPackages:
    svelte: ^3.44.0 => 3.52.0

### Which package is the issue about?

svelte-check

**Comment by brunnerh** [comment]
@dummdidumm It is already known that the declaration should be on the `slot` (see original issue).
The idea of this issue was to possibly improve the error message. E.g. if the property exists on a named slot, show an example of moving the declaration there rather than the generic type-based error.

**Comment by dummdidumm** [comment]
Oh I see, reopening then - although I'm not sure how we can reliably detect this error.

**Comment by dummdidumm** [comment]
Closing since Svelte 5 replaces slots with snippets
