### ISSUE TITLE
When I use nested syntax in postcss, I will report an error.

### ISSUE THREAD

**Issue by joker77877** [sveltejs/language-tools#1720]
### Describe the bug

When I use nested syntax in postcss, I will report an error.
![image](https://user-images.githubusercontent.com/62642184/201564968-d1257482-a84f-4154-a2f3-afce7b3c8b69.png)
![image](https://user-images.githubusercontent.com/62642184/201564989-b3bc1555-e4ac-40ee-8e25-8c831e6bd8bd.png)
![image](https://user-images.githubusercontent.com/62642184/201565269-65cda593-95b8-4652-9dce-bf0a7f3d849a.png)

### Reproduction

https://github.com/joker77877/vite-svelte-ts

### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 31.68 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
    Watchman: 2022.09.05.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 107.0.5304.110
    Safari: 15.6.1
  npmPackages:
    svelte: ^3.46.0 => 3.53.1
```

### Severity

annoyance

**Comment by jasonlyu123** [comment]
I can't reproduce it with your reproduction. Did you run `pnpm i` in the VSCode integrated terminal? In that case, you should [restart the language server](https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/in-general.md#restart-the-svelte-language-server) after the installation.

**Comment by adamansky** [comment]
@joker77877 Try replace `import` with `required` in your svelte.config.js

```diff
-import sveltePreprocess from 'svelte-preprocess';
+const sveltePreprocess = require('svelte-preprocess');
```
It helped me.

According to https://github.com/coc-extensions/coc-svelte/blob/master/docs/preprocessors/other-css-preprocessors.md#postcss

**Comment by jasonlyu123** [comment]
Closing due to inactive and not reproducible.
