### ISSUE TITLE
Linting error for undefined `svelte:component` `on:click`

### ISSUE THREAD

**Issue by brandonmcconnell** [sveltejs/language-tools#1723]
## Describe the bug

I'm seeing a linting error when attempting to use an `undefined` value for a `svelte:component`'s `on:click` event handler. This should no longer be the case since https://github.com/sveltejs/svelte/pull/7863 was merged.

## Reproduction

```svelte
<svelte:component
  this={SomeComponent}
  on:click={undefined}
/>
```

## Expected behaviour

No error should be present

## System Info

⭐ Running Svelte for VS Code v106.2.0

<details><summary><strong>OS:</strong> macOS Monterey Version: 12.6 (21G115)</summary>
<pre>Model Name: MacBook Pro
Model Identifier: MacBookPro18,3
Chip: Apple M1 Pro
Total Number of Cores: 10 (8 performance and 2 efficiency)
Memory: 32 GB
System Firmware Version: 7459.141.1
OS Loader Version: 7459.141.1
Serial Number (system): M79X4Y4THX
Hardware UUID: 0E903CE4-3816-5A32-8AB1-6F0825AB9217
Provisioning UDID: 00006000-0010591C2606801E
Activation Lock Status: Disabled</pre></details>

<details><summary><strong>IDE:</strong> VSCode Version: 1.71.2 (Universal)</summary>
<pre>Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:05:37.721Z (3 wks ago)
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No</pre></details>

## Additional Information, eg. Screenshots

![screenshot of TSLint error](https://user-images.githubusercontent.com/5913254/202024351-751e689e-ece6-4b95-9bfb-158c98781e11.png)

**Comment by dummdidumm** [comment]
We need to cut a new release of the extension so the Svelte version inside our language-server is bumped.

**Comment by felbsn** [comment]
maybe related ? #1750

**Comment by dummdidumm** [comment]
This is unrelated - the issue here was fixed through the latest release
