### ISSUE TITLE
`svelte-check` does not check for errors in imported `.ts` files

### ISSUE THREAD

**Issue by DetachHead** [sveltejs/language-tools#1724]
### Describe the bug

when importing a `.ts` file from a `.svelte` file, errors in the `.ts` file are not reported

### Reproduction

```ts
// foo.ts
export const foo: string = 1
```
```svelte
<script lang="ts">
    import { foo } from './foo'

    foo
</script>
```
```
> svelte-check

====================================
Loading svelte-check in workspace: c:\project
Getting Svelte diagnostics...

====================================
svelte-check found 0 errors, 0 warnings, and 0 hints
```

### Expected behaviour

error in `foo.ts` since `1` is not a valid `string`

### System Info

- OS: windows 10
- IDE: vscode

### Which package is the issue about?

svelte-check

**Comment by dummdidumm** [comment]
To get errors from TypeScript files / all files related to your project, you need to call `svelte-check` with the `--tsconfig` option: `svelte-check --tsconfig ./tsconfig.json` is likely what you want.

**Comment by DetachHead** [comment]
@dummdidumm thanks

i think by default it should look for a `tsconfig.json` in the project root though, like `tsc` does. seems very sus to not do any type checking by default...

**Comment by KotlinIsland** [comment]
@DetachHead That should be raised as a separate issue.

**Comment by dummdidumm** [comment]
It's planned for `svelte-check` version 3 to do just that (would be a breaking change so it only lands in next major)
