### ISSUE TITLE
TypeScript spell check suggesting generated variable for undeclared component

### ISSUE THREAD

**Issue by jasonlyu123** [sveltejs/language-tools#1726]
### Describe the bug

This only happens in the new transformation because the suggested variable only exists to check if the variable is a valid component. This seems to be related to how similar the generated variable is to the original component name. So the longer the name of the component, the lower the percentage of the prefix and suffix. 

### Reproduction

```svelte
<script lang="ts"></script>

<MyLongComponent />
```

### Expected behaviour

1. The error should be "Cannot find name 'MyLongComponent'" but is "Cannot find name 'MyLongComponent'. Did you mean '$$_MyLongComponent0C' ?". 
2. The quick fix for it should be to import a component with the same name but it's "Change spelling to $$_MyLongComponent0C"

### System Info

- OS: Windows
- IDE: VSCode

### Which package is the issue about?

svelte2tsx svelte-language-server

**Comment by jasonlyu123** [comment]
It seems like if we suffix the name with an equal amount characters of nonsense. like `$$_MyLongComponent0C$$$$$$$$$$$$$$$$`. TypeScript would stop saying it's a misspelling of the generated variable 😅

**Comment by dummdidumm** [comment]
mhm that's unfortunate. Alternative I can think of:
- change the name completely to something like `$$_1_0` where `1` is taking out of some componentname->number map (`{ MyLongComponent: 1, ... }`)?

**Comment by jasonlyu123** [comment]
Reverse the name works. I also tried repeating the name twice to `MyLongComponetMyLongComponent` which also works. Which one do you prefer?

**Comment by dummdidumm** [comment]
I vote for reversing
