### ISSUE TITLE
"go to definition" on `.svelte` files in vscode goes to compiled `.d.ts` files instead of source code when library has declaration maps

### ISSUE THREAD

**Issue by DetachHead** [sveltejs/language-tools#1732]
### Describe the bug

when a library is published with [declaration maps](https://www.typescriptlang.org/tsconfig#declarationMap), ctrl+clicking on its symbols should take you to the source code instead of the compiled `*.d.ts` files like it does in typescript

### Reproduction

1. create a `.svelte` file importing something from a package that has declaration maps (eg. `@detachhead/ts-helpers`)
    ```svelte
    <script lang="ts">
        import { cast } from '@detachhead/ts-helpers/dist/utilityFunctions/misc'
    </script>
    ```
2. ctrl+click the `cast` function, incorrectly navigates to `misc.d.ts`
   ![image](https://user-images.githubusercontent.com/57028336/203711561-6f1799a9-129c-4ad6-a869-6761ab37174a.png)
3. create a `.ts` file with the same import
    ```ts
    import { cast } from '@detachhead/ts-helpers/dist/utilityFunctions/misc'
    ```
4. ctrl+click the `cast` function, correctly navigates to `misc.ts`
    ![image](https://user-images.githubusercontent.com/57028336/203711454-8baa4dcd-d472-4b97-a9d9-d158e70b50d8.png)

### Expected behaviour

navigates to `misc.ts` instead of `misc.d.ts`

### System Info

- OS: windows 10
- IDE: vscode

### Which package is the issue about?

Svelte for VS Code extension

**Comment by dummdidumm** [comment]
This is the same behavior within TypeScript code, I'm not sure what you mean by "like it does in typescript". If there's a `d.ts` file next to a `.js` file and they have the same name, TypeScript will always navigate to the `d.ts` file. Furthermore, if a library provides type definitions, those are used for providing the intellisense, and consequently TypeScript will go to those definitions instead of the source code.

Do you mean the "go to source definition" command?

**Comment by DetachHead** [comment]
In `.ts` files when importing packages compiled with the `declarationMap` compiler option and its source code is included in the package, then "go to definition" will go to the source code instead of its declaration in its `.d.ts` file. To see an example of what I mean, install `@detachhead/ts-helpers` and import something from it

**Comment by jasonlyu123** [comment]
Changed the label to `enhancement` because typescript map the definition in the tsserver layer. We'll have to adopt the code that handles the mapping to our codebase to make it happen.

**Comment by DetachHead** [comment]
should we raise an issue on typescript to make those APIs public? i'd be happy to raise it, but i'm unfamiliar with the APIs.

**Comment by minrelp** [comment]
I think this is all about working with sourcemap.
Files that have sourcemap have `//# sourceMappingURL=` at the end, which either contains inlined sourcemap or points to the map file.
We can read and feed the sourcemap to this library [source-map](https://github.com/mozilla/source-map) to get the real location.
