### ISSUE TITLE
VSCode extension hides errors from non-Svelte projects if Svelte is in parent folder

### ISSUE THREAD

**Issue by probablykasper** [sveltejs/language-tools#1733]
### Describe the bug

Using the Svelte VSCode plugin with `"svelte.enable-ts-plugin": true` hides some errors from non-Svelte projects when Svelte is installed in a parent directory. The plugin seems to cause `lib.dom.d.ts` to be globally available, even where it shouldn't.

I have a Cloudflare Workers project where global types are provided by `@cloudflare/workers-types`. With these types, the global `Request` type does not have certain properties like `cache`, `mode`, `integrity` and `credentials`. If I include one of these properties, `tsc` gives me an error - However, no error shows up in VSCode, and in fact intellisense is suggesting these properties.

### Reproduction

https://github.com/probablykasper/workers-libdom-bug

### Expected behaviour

Properties like `Request.cache` should not be available

### System Info

- OS: macOS
- IDE: VSCode

### Which package is the issue about?

Svelte for VS Code extension

**Comment by jasonlyu123** [comment]
We did reference `dom` lib in one of our type definition files. It'll be loaded if the typescript plugin is enabled in the project. In this case, the parent directory has the svelte installed. So we can require `svelte` in the child directory. 

Ideally, we don't need to enable the plugin in your worker project but I am not sure how to reliably detect that. If we can't find a way to detect maybe we can remove the `dom` reference? Though I am not sure if this would count as breaking changes.

**Comment by dummdidumm** [comment]
It's probably the `/// <reference lib="dom" />` at the top of `svelte-jsx.d.ts` . I also thought about removing that, but yes it would be a breaking change, and I'm not sure of the breaks it may cause. For example, if you're just looking at an isolated Svelte file without a tsconfig.json nearby, the dom typings would not be referenced anywhere, and you would probably get all kinds of weird errors.

**Comment by dummdidumm** [comment]
Looked at this again; if we would remove the dom reference, you would get a sea of errors in your Svelte files because the worker types are lacking all the HTML element types. 
React has [this neat workaround](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/global.d.ts) for supporting multiple environments with a graceful fallback. But given that we don't have these problems (yet), since Svelte Native is working fine with lib dom being present, and since this bug isn't fixable without introducing a sea of other errors, I don't see the need to act on this right now.

**Comment by probablykasper** [comment]
Are you sure it would cause errors if the parent folder specifies libdom in the tsconfig?

**Comment by dummdidumm** [comment]
Stupid me, this only relates to the TypeScript plugin, for which we can do sth similar what we do for the ambient module declarations and remove it on the fly. The TypeScript plugin doesn't care if the content of a Svelte file is all red because those diagnostics never show up in that context.
