### ISSUE TITLE
"JSDoc types may be moved to TypeScript types." false positive on javascript code in typescript component

### ISSUE THREAD

**Issue by DetachHead** [sveltejs/language-tools#1734]
### Describe the bug

if a component has a `<script lang="ts">` tag in it, `svelte-check` incorrectly assumes jsdoc types within svelte code can be converted to typescript, where typescript is not supported. (see https://github.com/sveltejs/svelte/issues/4701)

also related: #1452

### Reproduction

```svelte
<script lang="ts"></script>

{() => {
    /** @type {string} */
    const a = 1 // JSDoc types may be moved to TypeScript types. ts(80004)
}}
```

### Expected behaviour

no hint

### System Info

- OS: windows 10
- IDE: vscode

### Which package is the issue about?

svelte-check

### Additional Information, eg. Screenshots

![image](https://user-images.githubusercontent.com/57028336/203912342-1fc125d8-ce51-462c-bc16-8268710c9a77.png)

**Comment by KotlinIsland** [comment]
@DetachHead Could you include the contents of `types.ts` so we can understand what's going on here?

**Comment by KotlinIsland** [comment]
I don't think we can fix this with the current solution, as the whole svelte component is compiled into a single ts file, so there is no way for ts to know which part of the file is js and which part is ts.

**Comment by dummdidumm** [comment]
Svelte 5 allows types in the template, therefore closing
