### ISSUE TITLE
commit character enhancement

### ISSUE THREAD

**Issue by DetachHead** [sveltejs/language-tools#1737]
### Describe the bug

when autocomplete suggestions appear, they are automatically accepted as i type, even when i don't press `tab` or `enter` on any of the suggestons. this is extremely annoying and makes working on svelte projects incredibly frustrating.

it only happens in `.svelte` files, but not `.ts` or `.js` files

### Reproduction

1. start with
    ```svelte
    <script lang="ts">
        const foo = [] as [string, string][]

        foo.map
    </script>
    ```
2. with the caret on the end of `foo.map`, type the following keys: `([key,`

### Expected behaviour

autocomplete suggestions appear after typing `key`, but disappear after typing `,` without changing the code

### System Info

- OS: windows 10
- IDE: vscode

### Which package is the issue about?

Svelte for VS Code extension

### `.svelte` file

![g;hlkdflghjldkfgnjhlkdjfn](https://user-images.githubusercontent.com/57028336/204440427-7257d9b2-5774-4377-a574-56261edbd0e1.gif)

### `.ts` file

![djflkhnkjldfgnhnflkjghn](https://user-images.githubusercontent.com/57028336/204440626-9e102cf6-9376-4b34-a71f-1312b329e8de.gif)

**Comment by jasonlyu123** [comment]
This is not a bug but a VSCode feature called commit character. You can turn it off with `editor.acceptSuggestionOnCommitCharacter` if don't like it.

**Comment by jasonlyu123** [comment]
VSCode changed the commit-character choice in the ts/js extension a while ago. We could consider making it consistent with ts/js though.

**Comment by DetachHead** [comment]
@jasonlyu123 it seems more like the feature is not working correctly in `.svelte` files. i've never had this issue with that feature enabled in any other language. imo this behaviour is incredibly frustrating to deal with and it shouldn't do this by default

**Comment by jasonlyu123** [comment]
We won't remove it but we could make it more consistent with ts/js. And maybe remove it in some place where it's more likely to trigger it by mistake.

**Comment by jasonlyu123** [comment]
They also skip commit-character if the `isNewIdentifierLocation` from `CompletionInfo` is `true`. That might be the reason for the inconsistency in this case. We didn't touch the commit character logic since the start of `language-tools` so we didn't adopt the enhancement logic made in VSCode for a while

**Comment by dummdidumm** [comment]
Ah you're right - thanks! Will add that to the PR, this will be fixed then.

**Comment by DetachHead** [comment]
works good now, thanks!
