### ISSUE TITLE
Prompt when Svelte is installed : "There is no formatter for 'svelte' files installed." 

### ISSUE THREAD

**Issue by 2234839** [sveltejs/language-tools#175]
**Describe the bug**
Prompt when Svelte is installed : "There is no formatter for 'svelte' files installed." 
Svelte Bate doesn't seem to be working at all

**To Reproduce**
1. install Svelte Bate
2. formatter 

**Expected behavior**
normal operation

**Screenshots**

![图片](https://user-images.githubusercontent.com/28727933/83985809-25dd2200-a96d-11ea-8eaa-1767abb6059b.png)

**System (please complete the following information):**

Version: 1.46.0-insider (system setup)
Commit: b1ef2bf05f90dd0e6438782411ab84756f97d8f1
Date: 2020-06-05T12:30:13.870Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

 - OS: Windows
 - IDE: VSCode
 - Plugin/Package: Svelte Beta

**Comment by jasonlyu123** [comment]
It's not just formating is down but nearly all the features. For some reason 99.0.34 doesn't open language-server at all. You can revert to 99.0.33.

**Comment by 2234839** [comment]
> 
> 
> It's not just formating is down but nearly all the features. For some reason 99.0.34 doesn't open language-server at all. You can revert to 99.0.33.

That's the reason. Thank you very much.

**Comment by dummdidumm** [comment]
See #174 for more info.

**Comment by frederikhors** [comment]
Same here.

**Comment by dummdidumm** [comment]
Deploy is fixed.
