### ISSUE TITLE
exported component functions can be undefined

### ISSUE THREAD

**Issue by felbsn** [sveltejs/language-tools#1750]
### Describe the bug

last update cause this behavior, exported function types defined as can be undefined.

### Reproduction

using exported function with component reference & wait for linting error

### Expected behaviour

exported functions shouldn't typed as undefined

### System Info

- OS: Linux Pop!_OS 22.04 LTS
- IDE: VSCode 1.73.1
- Svelte for VS Code: v106.3.0

### Additional Information, eg. Screenshots

![image](https://user-images.githubusercontent.com/24987495/204984491-b019f39f-c721-403f-95a9-31048b6c16ad.png)

**Comment by brunnerh** [comment]
@dummdidumm When packaging a component library project with SvelteKit it also generates `.d.ts` files which have `| undefined` getters. Is that the same piece of code/should a separate issue be opened for that in `sveltejs/kit`?

**Comment by dummdidumm** [comment]
they use the same code path, so this should be fixed aswell. Could you give an example where you expect `| undefined` to be omitted?

**Comment by brunnerh** [comment]
I updated my dependencies in two different projects, the one using Yarn works correctly now while the one using NPM still outputs `| undefined`, even though the lock files seem to both reference the latest versions of everything. 🤔

Probably just an issue on my end then.

My use case is a component with various instance functions to allow more imperative interactions, e.g.:

```svelte
<script lang="ts">
	export let messages: string[] = [];

	export function clear() {
		messages = [];
	}
	export function add(message: string) {
		messages = [...messages, message];
	}
</script>

{#each messages as message}
	<div class="message">{message}</div>
{/each}
```

The correct generated types:
```ts
import { SvelteComponentTyped } from "svelte";
declare const __propDef: {
    props: {
        messages?: string[] | undefined;
        clear?: (() => void) | undefined;
        add?: ((message: string) => void) | undefined;
    };
    events: {
        [evt: string]: CustomEvent<any>;
    };
    slots: {};
};
export type MessagesProps = typeof __propDef.props;
export type MessagesEvents = typeof __propDef.events;
export type MessagesSlots = typeof __propDef.slots;
export default class Messages extends SvelteComponentTyped<MessagesProps, MessagesEvents, MessagesSlots> {
    get clear(): () => void;
    get add(): (message: string) => void;
}
export {};
```

The faulty ones:
```ts
import { SvelteComponentTyped } from "svelte";
declare const __propDef: {
    props: {
        messages?: string[] | undefined;
        clear?: (() => void) | undefined;
        add?: ((message: string) => void) | undefined;
    };
    events: {
        [evt: string]: CustomEvent<any>;
    };
    slots: {};
};
export type MessagesProps = typeof __propDef.props;
export type MessagesEvents = typeof __propDef.events;
export type MessagesSlots = typeof __propDef.slots;
export default class Messages extends SvelteComponentTyped<MessagesProps, MessagesEvents, MessagesSlots> {
    get clear(): (() => void) | undefined;
    get add(): ((message: string) => void) | undefined;
}
export {};
```
