### ISSUE TITLE
Compatibility with JS/TS files

### ISSUE THREAD

**Issue by ALANVF** [sveltejs/language-tools#1756]
### Description

I'm trying to create a [Svelte template](https://replit.com/@theangryepicbanana/Svelte) for Replit, complete with LSP. Unfortunately, this Svelte language server doesn't support normal JS/TS files, so we'd have to run 2 language servers (tsc and svelte) at once, which maxes out the repl's memory (currently, we have tsc disabled since svelte is more important for this project template)

### Proposed solution

Since Svelte LSP is based on tsc, would it be possible to also detect JS/TS as well as Svelte files and provide intellisense accordingly? This way, we are only running 1 language server which helps reduce memory usage.

**Comment by jasonlyu123** [comment]
Not sure if we want to commit to this. We currently use TypeScript's language service API for language features, a lower-level API. TypeScript's tsserver uses that under the hood too. But it has a lot going on outside of the language service layer. We can't use the code there. That means even if we ever do that. The features/stability would not match TypeScript's offering.

**Comment by ALANVF** [comment]
That's fine then, we'll just figure out another solution later
