### ISSUE TITLE
Error with component typedef doesn't have event

### ISSUE THREAD

**Issue by jasonlyu123** [sveltejs/language-tools#1767]
### Describe the bug

There'll be a type check error when the Component type definition extends `SvelteCopmonentTyped<{}, {}, {}>` in strict mode. Not sure if we should count it as a bug because it's possible to avoid it in the userland. 

The error is

```
Argument of type 'typeof Component' is not assignable to parameter of type 'ConstructorOfATypedSvelteComponent'.
  Types of construct signatures are incompatible.
    Type 'new (options: IComponentOptions<{}>) => Component' is not assignable to type 'new (args: { target: any; props?: any; }) => ATypedSvelteComponent'.
      Construct signature return types 'Component' and 'ATypedSvelteComponent' are incompatible.
        The types of '$on' are incompatible between these types.
          Type '<K extends never>(type: K, callback: (e: {}[K]) => void) => () => void' is not assignable to type '(event: string, handler: ((e: any) => any) | null | undefined) => () => void'.
            Types of parameters 'callback' and 'handler' are incompatible.
              Type '((e: any) => any) | null | undefined' is not assignable to type '(e: never) => void'.
                Type 'undefined' is not assignable to type '(e: never) => void'.
...
```

### Reproduction

```svelte
<script lang="ts">
    import { SvelteComponentTyped } from "svelte";

    class Component extends SvelteComponentTyped<{}, {}, {}>{}
</script>

<Component></Component>

```

### Expected behaviour

no error.

### System Info

- OS: Windows
- IDE: VSCode

### Which package is the issue about?

Svelte for VS Code extension

**Comment by dummdidumm** [comment]
I can't reproduce this. I know that earlier versions of Svelte had the `| undefined | null` missing, which could explain this - although I always thought that for type checking, the Svelte version that is bundled with the extension was used.

**Comment by jasonlyu123** [comment]
Yeah. Indeed it doesn't happen in the latest svelte version  That was weird. I thought I am crazy when I can't reproduce it in the typescript playground. So we fixed it with some unrelated changes 😆. Still worth the effort for the visibility.

**Comment by jasonlyu123** [comment]
Closing since svelte-check now requires a later version that doesn't have this problem. If you encounter this you can update svelte to `3.51` or later.
