### ISSUE TITLE
Command: jump to parent component

### ISSUE THREAD

**Issue by AntoineBalaine** [sveltejs/language-tools#1775]
Hello,

I’m looking for a command to jump to the parent of a component. 

In the case of deeply-nested hierarchies, having the ability to jump to parent is very valuable, as it allows to walk trees up and down at the punch of a keystroke. Currently, it’s possible in Svelte to go down, but not up.

Is there a way around this?

**Comment by jasonlyu123** [comment]
If you right-click on a svelte file or right-click on the tab of a svelte file. There are two commands:

1. Svelte: Find Component References
This one shows all the references for the component class. import, value and type usage

2  Svelte: Find File References 
This one shows all the places where the component is imported

**Comment by dummdidumm** [comment]
@jasonlyu123 lists the two commands you can use to go "upwards". There cannot be a more specific command, because in the context of one component we can't know to which component that uses it you want to "jump" to. Therefore closing this.

**Comment by AntoineBalaine** [comment]
>     1. Svelte: Find Component References
>        This one shows all the references for the component class. import, value and type usage

This is exactly what I needed, thank you very much!
