### ISSUE TITLE
no error on invalid bound in `$$Generic`

### ISSUE THREAD

**Issue by DetachHead** [sveltejs/language-tools#1778]
### Describe the bug

there's no error when specifying an invalid bound on `$$Generic`

### Reproduction

```svelte
<script lang="ts">
    type T = $$Generic<asdf> // no error
</script>
```

### Expected behaviour

error because `asdf` does not exist

### System Info

- OS: windows 10
- IDE: vscode

### Which package is the issue about?

svelte-check

**Comment by dummdidumm** [comment]
Reason for this is that we currently completely remove the original string during transformation. To have the error persisted, we would need to move it, which is hard in this place (the render function).

**Comment by dummdidumm** [comment]
Closing since the `generics` attribute is the way to do generics now, and `$$Generics` is deprecated
