### ISSUE TITLE
<video controlsList="nodownload nofullscreen"> is not allowed by controlsList type definition

### ISSUE THREAD

**Issue by iva2k** [sveltejs/language-tools#1781]
### Describe the bug

Valid HTML code:
```js
// +page.svelte
<video controlsList="nodownload nofullscreen">
```
Throws TypeScript error:
> Type 'string' is not assignable to type '"nodownload" | "nofullscreen" | "noremoteplayback" | "noplaybackrate" | undefined. ts(2322)

Expected the string combining multiple - 2 or more of the allowed values to be valid and not throw any errors.

Per <https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/controlsList>:
>HTMLMediaElement.controlsList
The controlsList property of the [HTMLMediaElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement) interface returns a DOMTokenList that helps the user agent select what controls to show on the media element whenever the user agent shows its own set of controls. The DOMTokenList takes one or more of three possible values: nodownload, nofullscreen, and noremoteplayback.

[DOMTokenList](https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList) is:
> The DOMTokenList interface represents a set of space-separated tokens. 

### Reproduction

```js
// +page.svelte
<video controlsList="nodownload nofullscreen">
```

### System Info

```shell
svelte/next
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
Should be fixed with the new transformation which is the default in VS Code for a while now and the default for `svelte-check` version 3 which was just released
