### ISSUE TITLE
 WARN  deprecated sourcemap-codec@1.4.8

### ISSUE THREAD

**Issue by Valexr** [sveltejs/language-tools#1783]
### Describe the bug

Please use @jridgewell/sourcemap-codec instead

### Reproduction

`pnpm up`

### Expected behaviour

Please use @jridgewell/sourcemap-codec instead

### System Info

System:
    OS: macOS 13.2
    CPU: (8) arm64 Apple M2
    Memory: 95.53 MB / 8.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 19.3.0 - /opt/homebrew/bin/node
    npm: 9.2.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox Developer Edition: 109.0
    Safari: 16.2

### Which package is the issue about?

svelte2tsx

**Comment by dummdidumm** [comment]
We can only do this if we bump magic-string, which we should do for `svelte-check` version 3

**Comment by dummdidumm** [comment]
Closing as this will be done as part of the work for version 3; the remaining instances of sourcemap-codec cannot be removed due to dev dependencies we rely on.

**Comment by Valexr** [comment]
Why removing 🤷🏻‍♂️ just use other version 

`@jridgewell/sourcemap-codec`

**Comment by fredguest** [comment]
@dummdidumm fyi the warning still gets thrown when npm installing a sveltekit app because of the same deprecated dependency through the sorcery package. 

```
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead

app@0.0.1
└─┬ svelte-preprocess@5.0.0
  └─┬ sorcery@0.10.0
    └── sourcemap-codec@1.4.8
```
