### ISSUE TITLE
Respect editor.autoIndent with VSCode in script and style tag and in {expression} in SvelteJS

### ISSUE THREAD

**Issue by lukaszpolowczyk** [sveltejs/language-tools#1784]
### Describe the bug

Please file this issue against the Svelte extension. They own the basic language support for `.svelte` files and should investigate this issue 

If they believe they are doing everything correctly and that the root cause is with VS Code, they can file an issue against us with more information about the problem

_Originally posted by @mjbvz in https://github.com/microsoft/vscode/issues/160553#issuecomment-1355531466_
      

### Reproduction

Here https://github.com/microsoft/vscode/issues/160553#issue-1368226020

### Expected behaviour

As above

### System Info

- OS: Arch Linux
- IDE: VSCode

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

Based on these two issues:

https://github.com/sveltejs/language-tools/issues/1619

https://github.com/sveltejs/language-tools/issues/1607

**Comment by jasonlyu123** [comment]
The original issue is still open. Let's track it in the original issue.
