### ISSUE TITLE
SvelteJS {expression} in svelte-markup in svelte file - the last item in {expression} behaves as if there is already AFTER {expression}, which there shouldn't be

### ISSUE THREAD

**Issue by lukaszpolowczyk** [sveltejs/language-tools#1785]
### Describe the bug

As here - https://github.com/microsoft/vscode/issues/160549

This problem is said to have been solved on the VSCode side.
Can you make the extension to Svelte work already too?

**EDIT**: I guess this is only available in VSCode Insiders, or only in the January/February 2023 VSCode.
So I guess I was in a hurry, but I don't know.
**EDIT2**: In VSCode Insider, this error still occurs. Version:
```
Version: 1.75.0-insider
Commit: edc432e920c3ec2c2af5e8a99b8e4b782633d298
Date: 2022-12-16T05:25:08.913Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 6.0.8-arch1-1
Sandboxed: Yes
```

### Reproduction

As above.

### Expected behaviour

As above.

### System Info

- OS: Arch Linux
- IDE: VSCode

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

Based on these two issues:

https://github.com/sveltejs/language-tools/issues/1619

https://github.com/sveltejs/language-tools/issues/1607

**Comment by jasonlyu123** [comment]
The original issue is still open. Let's track it in the original issue.

**Comment by lukaszpolowczyk** [comment]
@jasonlyu123 I no longer remember which is for what, I got lost, a little mixed up (by me).
