### ISSUE TITLE
Clean up docs / version

### ISSUE THREAD

**Issue by dummdidumm** [sveltejs/language-tools#18]
- Fix links (some have the old github links)
- Agree on a new initial version (0.0.1?)
- Clear changelog

**Comment by orta** [comment]
Yeah, I think this makes sense 

Maybe 0.5.0 as a version? It's new to us and usable (it's already the most popular one)  so it at least feels like we're building on top of something

**Comment by orta** [comment]
I set it to 0.5.0 in #20
