### ISSUE TITLE
Console output listing the errors and warning is missing a space character

### ISSUE THREAD

**Issue by foochris** [sveltejs/language-tools#1808]
### Describe the bug

A space is missing between `and` and the number of warnings:

```
====================================
svelte-check found 11 errors and0 warnings
 ELIFECYCLE  Command failed with exit code 1.
```

### Reproduction

```
$ svelte-kit sync && svelte-check --tsconfig ./tsconfig.json
```

### Expected behaviour

```
====================================
svelte-check found 11 errors and 0 warnings
 ELIFECYCLE  Command failed with exit code 1.
```

### System Info

- OS: macOS 12.6
- IDE: VSCode

### Which package is the issue about?

svelte-check

### Additional Information, eg. Screenshots

https://github.com/sveltejs/language-tools/blob/b76259086c4bcd8005f1451b3249cef65f1015da/packages/svelte-check/src/writers.ts#L104

Should be:

```
`${errorCount} ${errorCount === 1 ? 'error' : 'errors'} and `,
```

**Comment by Khalil-Ullah-Hafeez** [comment]
I would like to work on this issue. Can you assign this to me?

**Comment by dummdidumm** [comment]
Go for it!
