### ISSUE TITLE
Extension not working if the working directory is nested.

### ISSUE THREAD

**Issue by akashlama1998-icloud** [sveltejs/language-tools#1820]
### Describe the bug

I have a project structure like:-
```
project
|-firmware
|-web
|-project.code-workspace
```
where web is the sveltekit project and firmware is a platformio esp32doit-devkit-v1 project. When I open the web folder by itself and enable the svelte extension formats my code just fine. But opening it in the VSCode workspace or even opening my root project folder directly in VSCode, the extension seems format my code.

### Reproduction

Make a root project directory and in VSCode open Platform IO Home, then create a new esp32doit-devkit-v1 project inside the root folder. After that in the root folder create a sveltekit project. Then open the root folder in VSCode (platformio and svelte both plugins are enabled). 

### Expected behaviour

Svelte extension to work (format my code) regardless the project is in root or nested inside.

### System Info

- OS: [e.g. Windows 11]
- IDE: [e.g. VSCode]

### Which package is the issue about?

Svelte for VS Code extension

**Comment by jasonlyu123** [comment]
Do you have a `.prettierrc` file? If so check if you have `plugins: [prettier-plugin-svelte]` in it. You can try to remove it to see if it helps. Otherwise, We need more info to be able to help you. Please provide reproduction in a repository form.

**Comment by akashlama1998-icloud** [comment]
My `.prettierrc` is inside `project/web/.prettierrc` and it looks something like:-

```json
{
        "useTabs": true,
        "singleQuote": true,
        "trailingComma": "none",
        "printWidth": 100,
        "plugins": ["prettier-plugin-svelte"],
        "pluginSearchDirs": ["."],
        "overrides": [{ "files": "*.svelte", "options": { "parser": "svelte" } }]
}
```

**Comment by akashlama1998-icloud** [comment]
My .prettierrc is inside project/web/.prettierrc and it looks something like:-
```json
{
  "useTabs": true,
  "singleQuote": true,
  "trailingComma": "none",
  "printWidth": 100,
  "plugins": ["prettier-plugin-svelte"],
  "pluginSearchDirs": ["."],
  "overrides": [{ "files": "*.svelte", "options": { "parser": "svelte" } }]
}
```

**Comment by jasonlyu123** [comment]
Does it work after you removed the `"plugins": ["prettier-plugin-svelte"]` config and then restart the editor?

**Comment by akashlama1998-icloud** [comment]
It totally did 🤯. Thank you. Closing this issue. Love the svelte community.

**Comment by mroobert** [comment]
@jasonlyu123 but why is this conflict present? why removing this plugin will make the formatting work?

**Comment by jasonlyu123** [comment]
The plugin config loads the plugin installed in the node_modues. At the time it was because you don't have the plugin installed but still specify the config. But we added some error handling  for this specfic case and still provided a fallback prettier-plugin-svelte. If it's still happening, it might be other conflicts and we'll need a reproduction to know.
