### ISSUE TITLE
VSCode: Runtime path does not update alongside node version

### ISSUE THREAD

**Issue by Blade67** [sveltejs/language-tools#1822]
### Describe the bug

The path to the currently active runtime does not update when updating node version. (tested with nvm)
This leads to issues when using new node features while the selected node version is out-of-date. One such issue is:
```
Error in svelte.config.js

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'stream' imported from e:\myproject\node_modules\@sveltejs\kit\src\exports\node\polyfills.js
```

### Reproduction

Use nvm (or any other version manager) and switch to an old node version (ie. 14), set the runtime path to it (this happens automatically when installing the VSCode Svelte extension) then update node via nvm. You will see that the runtime path will not update or warn the user.

### Expected behaviour

A warning that there is a version mismatch or auto-update to the current one on every re-launch of VSCode **unless specified otherwise**.

### System Info

- OS: Windows
- IDE: VSCode

### Which package is the issue about?

Svelte for VS Code extension

**Comment by dummdidumm** [comment]
What do you mean by "set the runtime path to it"?

**Comment by cdcarson** [comment]
I had the exact same error for all .svelte files. I can't reproduce, but I suspect that it has to do with a stale `.svelte-kit`. Deleting the `.svelte-kit` folder and rebuilding it fixed the problem for me. I was working an a machine that I use to code once or twice a week, so the last time `.svelte-kit` had been built was before the recent updates to  SvelteKit.

**Comment by dummdidumm** [comment]
I don't understand what "runtime path" means in relation to the Svelte extension. If the node runtime isn't explicitly set by the user, the version that's provided through VS Code is used.
