### ISSUE TITLE
svelte-check --watch does not pick up changes in .tsx files

### ISSUE THREAD

**Issue by odinhb** [sveltejs/language-tools#1827]
A while ago I replaced `tsc` with `svelte-check` in my project, because I wanted to use svelte + typescript. However, before adding svelte we had used .tsx files.

I just noticed that `.tsx` files aren't really typechecked anymore when running `svelte-check --watch`. (compared to back when I was using `tsc --watch`.

I can see that in svelte-check's source code: https://github.com/sveltejs/language-tools/blob/84c7463def79e88550aa12074830ed7d7945e1ee/packages/svelte-check/src/index.ts#L101
we just kinda ignore `.tsx` files.

Is there a reason why `.tsx` is not listed here? My guess is that before the recent refactoring away from using tsx internally, having `.tsx` files in your project would have just not worked anyway.

**Comment by dummdidumm** [comment]
No reason, I just didn't think of that case where someone would mix both in the same project. For what are you using these `.tsx` files? Is this a React project that incrementally adopts Svelte?

**Comment by odinhb** [comment]
It is a rails project with a long history. We are incrementally adopting svelte but before we decided what component framework to use we were just using the [vhtml](https://www.npmjs.com/package/vhtml) package which lets you treat jsx/tsx syntax as a string.

It is a little nicer to work with than this type of legacy code:

```js
let html = `<div class="whatever>`;
html += `<p>some content</p>`;
html += `</div>`;
el.innerHTML = html;
// also imagine that this goes on for 100s of lines
```

which becomes

```js
import h from 'vhtml';

el.innerHTML = (
  <div class="whatever">
    <p>some content</p>
  </div>
);
```

**Comment by odinhb** [comment]
Would you like me to send a pull request?

**Comment by dummdidumm** [comment]
Sure!

**Comment by odinhb** [comment]
I've run into this error with svelte-check now:

```
Error: Argument of type 'typeof LabeledSpinner__SvelteComponent_' is not assignable to parameter of type 'ConstructorOfATypedSvelteComponent'.
  Type 'LabeledSpinner__SvelteComponent_' is missing the following properties from type 'ATypedSvelteComponent': $$prop_def, $$events_def, $$slot_def, $on

Possible causes:
- You use the instance type of a component where you should use the constructor type
- Type definitions are missing for this Svelte Component. If you are using Svelte 3.31+, use SvelteComponentTyped to add a definition:
  import type { SvelteComponentTyped } from "svelte";
  class ComponentName extends SvelteComponentTyped<{propertyName: string;}> {} (ts)
  {#if !$fetched}
    <Spinner>                                                                                                                                
      {I18n.t(`loading`)}    
```

And I've no clue what is causing this to suddenly be a problem.

**Comment by dummdidumm** [comment]
Sounds unreleated, please open a new issue with a reproduction.

**Comment by odinhb** [comment]
I can't figure out how to reproduce the error but I've backported my changes to an older version of svelte-check on my fork.
