### ISSUE TITLE
Slot prop type narrowing is lost in parent component

### ISSUE THREAD

**Issue by brunnerh** [sveltejs/language-tools#1832]
### Describe the bug

In a component template `{#if}` removes `null` and `undefined` from the type of a variable. If this variable is then passed into a slot, the removal of these types is not reflected in the parent component where the slot property is used.

### Reproduction

```svelte
<!-- Component.svelte -->
<script lang="ts">
  export let value: string | null | undefined;
</script>

{#if value}
  <slot {value} /> <!-- Type of value is correct here: string -->
{/if}
```
```svelte
<script lang="ts">
  import Component from './Component.svelte';
  const value = 'Hello';
</script>

<Component value={value} let:value>
  {value[0]} <!-- Error here as value is typed `string | null | undefined` -->
</Component>
```

### Expected behaviour

Type of slot prop is narrowed correctly.

### System Info

- OS: Windows 10, 64bit
- IDE: VSCode

### Which package is the issue about?

- Svelte for VS Code extension
- svelte-check

**Comment by jasonlyu123** [comment]
Similar to #1344. Fixing this is going to be hard because it'll need a more complex generated code for typescript to infer. I think we might not fix it anytime soon. You can consider using the `$$Slots` interfaces for explicit typing.

**Comment by dummdidumm** [comment]
Closing since Svelte 5 replaces slots with snippets and render tags, which don't have this problem (because you're required to type it properly)
