### ISSUE TITLE
Support rome tools for formatting

### ISSUE THREAD

**Issue by itsezc** [sveltejs/language-tools#1834]
### Description

Currently only prettier and editorconfig are supported for formatting, but [Rome](https://rome.tools/) is an equally apt tool for this and used by many and as such it would be great if the VSCode extension were to support this.

### Proposed solution

Add Rome tools for formatting settings for the Svelte VSCode extension

**Comment by jasonlyu123** [comment]
Don't think this is even possible. The HTML support and CSS support are all just plans. And there isn't any plugin system for you to add custom language support. Even if both issues are resolved I'll say this would better be a community effort and published as a separate extension.

**Comment by dummdidumm** [comment]
Closing as there isn't any Svelte (not even HTML) support from them, and if they add that, they surely have a VS Code extension which you can switch to as the default formatter for Svelte files, so nothing to do on our side.
