### ISSUE TITLE
TypeScript: priority of typings seems wrong

### ISSUE THREAD

**Issue by bugproof** [sveltejs/language-tools#1836]
### Describe the bug
When passing through props from e.g. `<li>` element

https://github.com/sveltejs/svelte/blob/7e6acbece31fbd68e2c07e37f3c849c405eb6983/elements/index.d.ts#L796-L798
```ts
export interface HTMLLiAttributes extends HTMLAttributes<HTMLLIElement> {
	value?: string | string[] | number | undefined | null;
}
```

it doesn't seem to be possible to override the default typing for `value` e.g. consider this component that defaults to rendering as  `<li>` element 

https://github.com/rgossiaux/svelte-headlessui/blob/master/src/lib/components/listbox/ListboxOption.svelte#L7

the value there expects `unknown` type but when you try to assign any/unknown type you get an error because index.d.ts typing takes precendence.

### Reproduction

The easiest way to reproduce is to use headless ui fork for Svelte: https://svelte-headlessui.goss.io/docs/listbox and copy paste the basic example.

### Expected behaviour

It shouldn't give typescript error

### System Info

- OS: Windows
- IDE: VSCode

### Which package is the issue about?

None

### Additional Information, eg. Screenshots

https://github.com/sveltejs/svelte/pull/7649

![image](https://user-images.githubusercontent.com/3116731/213189421-cf77551c-f520-4f7b-8ff0-c037157f1d3a.png)

**Comment by dummdidumm** [comment]
This is a problem with the typings of that library. Doing `& { value: unknown }` doesn't cast that value to `unknown`; in general when something should be overwritten,  `Omit<.., 'value'> & { value: .. }` should be used

https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgILIN4ChnIG5wA2ArhAFzIDOYUoA5gNxYC+WWYAngA4oBCyAXkwES5KjXrNkAMmFFSFYiADWIAPYB3EMyZYEakNWQAjCvyEYRC5DVKssQA
