### ISSUE TITLE
The code completion did not work as expected

### ISSUE THREAD

**Issue by BERADQ** [sveltejs/language-tools#1837]
### Describe the bug

Code intelligence for nested syntax in inline Postcss indicates a language error, the problem is in the second line of the nest, and the language is recognized as HTML
![img](https://user-images.githubusercontent.com/78293733/213408897-fbf0e77a-f05a-4dcb-b31c-21255b2ddff2.png)

### Reproduction

```HTML
<style lang="postcss">
	html {
		& body {
			width: 100px;
			//This is where bugs come in
		}
	}
</style>
```

### Expected behaviour

Inline Postcss smart completion needs to be displayed correctly

### System Info

- OS: Windows 11
- IDE: VSCode 1.74.3

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

![image](https://user-images.githubusercontent.com/78293733/213410150-1d9d660e-270c-4ed9-99cb-3f36010c3f6d.png)

**Comment by jasonlyu123** [comment]
We don't support completion in postcss because we rely on the upstream vscode-css-languageService for CSS support. And it doesn't support postcss nor does it support CSS nesting.
