### ISSUE TITLE
`$lib` instead of `./` for component autocomplete?

### ISSUE THREAD

**Issue by dsm-72** [sveltejs/language-tools#1838]
### Description

Can we have svelte kit use `$lib` instead of `.` for autocompletion?

### Proposed solution

As stated above

**Comment by gyurielf** [comment]
It would be nice!

**Comment by jasonlyu123** [comment]
You can set the "typescript.preferences.importModuleSpecifier" and the "javascript.preferences.importModuleSpecifier" config to "non-relative" or "project-relative"

**Comment by gyurielf** [comment]
> Where and how?

Inside your project, `.vscode` folder > `settings.json`.

E.g:
```
{
    "tailwindCSS.rootFontSize": 14,
    "typescript.preferences.importModuleSpecifier": "non-relative"
}
```

**Comment by dsm-72** [comment]
@gyurielf now it uses `/` rather than `$lib`

**Comment by gyurielf** [comment]
For me, it works well this config. (I tried out today)

**Comment by dsm-72** [comment]
Huh, I just tried it and I am getting `/` any ideas?

**Comment by jasonlyu123** [comment]
@dsm-72 Did you get this `/` completion import statement completion like `import page`?

**Comment by dsm-72** [comment]
@jasonlyu123  no. As stated it isn’t using $lib

**Comment by jasonlyu123** [comment]
What I mean is does the completion always suggest `/` instead of `$lib` or does it only happens in this kind of completion

```svelte
<script>
import pa
</script>
```

**Comment by dsm-72** [comment]
Always

**Comment by jasonlyu123** [comment]
Can you provide a reproduction repository? I can only reproduce it in the case I mentioned.

**Comment by dsm-72** [comment]
@jasonlyu123  I literally just use SvelteKit to make a black project, create a component A and component B under lib and then try the autocomplete 😅

**Comment by dsm-72** [comment]
@jasonlyu123 Thank you for your help. I don't know if it is important completion. As stated it is literally just a blank SvelteKit project with two components under lib. Do you really want me to make a repo for that?

**Comment by jasonlyu123** [comment]
It's "import statement completion". Meaning it's the completion when you write the import statement. So it will trigger when you typed `import` followed by an identifier.

Yes. PLEASE provide a repo. We won't make any process if we can't understand each other. Let the code do the talking.
