### ISSUE TITLE
Is there a way to exclude files from the component autocompletion ?

### ISSUE THREAD

**Issue by gyurielf** [sveltejs/language-tools#1840]
Hey!

Is there a way to exclude e.g. `*.stories.svelte` files from the component autocomplete ?
I didn't find any info about this in the docs.

Thanks!

**Comment by dummdidumm** [comment]
There's https://devblogs.microsoft.com/typescript/announcing-typescript-4-8/#exclude-specific-files-from-auto-imports which should do the job
