### ISSUE TITLE
Wrong imports listed in VSCode auto imports list

### ISSUE THREAD

**Issue by ebeloded** [sveltejs/language-tools#1846]
### Describe the bug

When using the auto-imports feature in VSCode, the suggested imports include `svelte`, `svelte/internal`, `svelte/types/runtime/internal`, and `svelte/types/runtime/internal/lifecycle`.

![CleanShot 2023-01-25 at 20 01 09@2x](https://user-images.githubusercontent.com/5859177/214570558-402d3706-56d8-4565-a00e-b0f1657e53ef.png)

Other than `svelte` import suggestions point types not from my workspace, but from the VSCode extension
![CleanShot 2023-01-25 at 20 04 51@2x](https://user-images.githubusercontent.com/5859177/214570881-5631ae49-fca3-492e-906e-0e1da0b347c1.png)

### Reproduction

1. In latest version of VSCode start a new SvelteKit project
2. Type one of Svelte's functions, such as `setContext`
3. Init quick fix with CMD + .

### Expected behaviour

I expect there to be just `svelte`

### System Info

- OS: Mac OS
- IDE: VSCode 1.74.3

### Which package is the issue about?

Svelte for VS Code extension

**Comment by harshmandan** [comment]
+1. Whenever I try to import `onMount`/`onDestroy` functions using intelli-sense, the import is added from the path `svelte/types/runtime/internal/lifecycle`

**Comment by ebeloded** [comment]
From this [description](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#smarter-auto-imports) about the workings of TypeScript auto-imports, my understanding is that TypeScript the suggestions should include options from my package.json/node_modules. I posted it as a bug here because somehow TypeScript intellisence picks up the types from the VSCode Svelte extension, which is not the expected behavior. Any idea why those are included?

**Comment by ebeloded** [comment]
I don't know if anything can be done in the VSCode extension to prevent this from happening, but it turns out that VSCode has a setting that helps filter out unwanted import suggestions.
Add this to your settings.json:
```json
{
  "typescript.preferences.autoImportFileExcludePatterns": [
    "internal", "runtime"
  ]
}
```
I wish I knew this before. The incorrect auto-imports were creating unnecessary friction, as I could never rely on them for svelte functions.

@dummdidumm please feel free to close this if settings adjustment is the way to go. Or maybe this issue belongs in svelte repo: when the Svelte extension is disabled, when I ask for suggestions in a `.ts` file, I get the undesired import suggestions.
