### ISSUE TITLE
svelte.config.js can not be loaded in WSL 2

### ISSUE THREAD

**Issue by Fubuchi** [sveltejs/language-tools#185]
**Describe the bug**
svelte.config.js can not be loaded in WSL 2

**To Reproduce**
Crate a new project using `npx degit sveltejs/template hello-world`
Go to the root folder and add a svelte.config.js file.
=> svelte.config.js  can not be loaded and this is logged in the output:
![image](https://user-images.githubusercontent.com/42483897/84416151-06c8e380-ac3e-11ea-90da-23d0c185f002.png)

**Expected behavior**
 svelte.config.js should be loaded

**System (please complete the following information):**
 - OS: WSL2 - Fedora Remix
 - IDE: VSCode
 - Plugin/Package: "Svelte Beta"

**Additional analysis**
I tried to create a project in Windows and svelte.config.js was loaded without problem. I notice that the line `Trying to load config for` in windows contain the full path to App.svelte, not only `/src/App.svelte` in WSL.

Then, I tried to modify this function a bit: https://github.com/sveltejs/language-tools/blob/master/packages/language-server/src/plugins/svelte/SveltePlugin.ts#L151

```
const result = await explorer.search('/home/poi-poi/dev/svelte/hello-world' + document.getFilePath() || '');
```

Surprisingly, svelte.config.js was loaded!
![image](https://user-images.githubusercontent.com/42483897/84416972-26acd700-ac3f-11ea-8db2-de205e637948.png)

**Comment by jasonlyu123** [comment]
So you have problem loading in a project created in wsl, and have no problem when it's created in windows, while both of them are opened in wsl remote?

**Comment by jasonlyu123** [comment]
This is weird. the document uri received in the server is literally `file:///src/App.svelte`

**Comment by Fubuchi** [comment]
The windows one is opened from windows, not WSL. It turn out that I forgot to run `npm i` before I use the language server. After running `npm i`, I have the same behavior on windows and WSL:

- After restarting language server of the first time I open the project, the config file can not be loaded.
- After I edit and save App.svelte , the config is load correctly.
- Only config file with content inside can be loaded, empty config file can't be. (make sense, but I think the log should be more intuitive)
=> Are these behaviors bug or they are working as designed?

Please refer to this video: https://www.dropbox.com/s/nun5uzptzffbiho/svelte.config.swf
(Sorry for the swf format, I use Jing free edition to record, so no options to output as mp4). You can open it using IE or if you are not using windows, you can download the [flash projector](https://www.adobe.com/support/flashplayer/debug_downloads.html) from adobe

**Comment by jasonlyu123** [comment]
I try to log the document uri (i.e. identifier of what file should be opened) received in the language-server. For some reason, it'll log `file:///src/App.svelte` once. So that why the output log `trying to find config for /src/App.svelte`
As for config, this is handle by cosmiconfig so I don't know what we could do about it.

**Comment by Fubuchi** [comment]
After delete node_modules and run npm intstall again. Everything work fine, no more strange log `trying to find config for /src/App.svelte` , config is loaded at the first time I open the project.

Not sure if there is anything to do with cosmiconfig .
