### ISSUE TITLE
Error: " Argument of type '{ "sveltekit:prefetch":boolean...  does not exist in type 'HTMLProps<"a", HTMLAttributes<any>>'.ts"

### ISSUE THREAD

**Issue by sandikodev** [sveltejs/language-tools#1850]
i got some HTMLAttributes undefined that's tell me typedef of sveltekit:prefetch does not exist

```
Argument of type '{ "sveltekit:prefetch": boolean; href: string; class: string; "aria-label": string; }' is not assignable to parameter of type 'HTMLProps<"a", HTMLAttributes<any>>'.
  Object literal may only specify known properties, and '"sveltekit:prefetch"' does not exist in type 'HTMLProps<"a", HTMLAttributes<any>>'.ts(4)
```

here's my little snippet
```
<script lang="ts">
	// boring stuff here
</script>
<a sveltekit:prefetch href="/" class="{linkClass}" aria-label="{'Footer home link'}">Home</a>
```

but if i change `sveltekit:prefetch` with `sapper:prefetch`
```
<a sapper:prefetch href="/" class="{linkClass}" aria-label="{'Footer home link'}">Home</a>
```

which in case i'am not using sapper anymore...,
here's i'am came from `https://kit.svelte.dev`
```
npm create svelte@latest my-app
cd my-app
npm install
npm run dev -- --open
```
and this is my vscode-ext which i currently used
```
svelte.svelte-vscode
ardenivanov.svelte-intellisense
fivethree.vscode-svelte-snippets
```
anybody can help or suggest what the best way to resolv ?
thanks everyone

**Comment by dummdidumm** [comment]
Yes that's correct. The names are `data-sveltekit-X` now, you can find all of them at https://kit.svelte.dev/docs/link-options . Closing because the beta types are no longer supported
