### ISSUE TITLE
a11y-click-events-have-key-events false positive

### ISSUE THREAD

**Issue by OJFord** [sveltejs/language-tools#1856]
### Describe the bug

I don't think it's always _possible_ nevermind suitable to handle key events on the same component as the clickable element.

In such cases, we get a false positive for `a11y-click-events-have-key-events`.

### Reproduction

This is an excerpt from a PDF previewing component, which has a left/right button on each side of the screen, or alternatively _does_ accept left/right keypresses:

```svelte
<svelte:window on:keydown={handleKey} />

<Document file={docUrl} on:loadsuccess={(ev) => (doc = ev.detail)}>
  <div>
    <Page {scale} num={pageNumber} />

    {#if !atBeginning}
      <span
        class="page-turn-btn page-turn-left"
        on:click={() => handleKey({
          key: "ArrowLeft",
        })}
      >
        <Icon icon={faArrowLeft} />
      </span>
    {/if}

    {#if !atEnd}
      <span
        class="page-turn-btn page-turn-right"
        on:click={() => handleKey({
          key: "ArrowRight",
        })}
      >
        <Icon icon={faArrowRight} />
      </span>
    {/if}
  </div>
</Document>
```

### Expected behaviour

No error `a11y-click-events-have-key-events`.

### System Info

- OS: [e.g. Windows] linux
- IDE: [e.g. VSCode, Atom] vim

### Which package is the issue about?

svelte-check

**Comment by jasonlyu123** [comment]
In complex cases like this. You can use the svelte-ignore comment to suppress it. `<!-- svelte-ignore a11y-click-events-have-key-events -->`
