### ISSUE TITLE
path completion doesn't suggest directories/files under '$lib'

### ISSUE THREAD

**Issue by hare0319** [sveltejs/language-tools#1859]
### Describe the bug

After recently update of vscode, when type import statement in a `*.ts` file or script section of `*.svelte` file, auto completion suggestion won't show choices for `$lib`. Even if manually typed `$lib\` the suggestion won't show potential sub folders or files.

But the imported module or components can be correctly recognised and used.

### Reproduction

1. Initiate a svelte demo project and move the `Counter.svelte` component to the `src/lib` directory.
2. In `stc/routes/+page.svelte`, replace original importing statement with `import Counter from '$lib/Counter.svelte'`. It can be found that `$lib` won't list in suggestions when input in the import statement. And even if `$lib` is inserted manually, `Counter.svelte` won't show.
3. Start the server, the page is correctly rendered with **Counter** component.

### Expected behaviour

When type in the import statement, the auto completion suggestion provide options related to `$lib`.

### System Info

- OS: Windows 11 (10.0.22621) with WSL 2
- IDE: vscode
  - Version: 1.75.0 (user setup)
  - Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
  - Date: 2023-02-01T15:23:45.584Z
  - Electron: 19.1.9
  - Chromium: 102.0.5005.194
  - Node.js: 16.14.2
  - V8: 10.2.154.23-electron.0
  - OS: Windows_NT x64 10.0.22621
  - Sandboxed: No

### Which package is the issue about?

Svelte for VS Code extension

**Comment by jasonlyu123** [comment]
I suppose you mean this kind of completion:

```ts
import {} from '$lib/|' /**trigger where the `|` is*/
```

This seems to be because SvelteKit now generates a `tsconfig.json` without `baseUrl` to mitigate some auto-import issues. But it seems like this feature won't work without a `baseUrl`
