### ISSUE TITLE
`$env/dynamic/public` not found under route when its path starts with a dot `.`

### ISSUE THREAD

**Issue by LaurentTreguier** [sveltejs/language-tools#1861]
### Describe the bug

In Visual Studio Code, when editing a file and importing something like `$env/dynamic/public` in a SvelteKit project, the extension does not recognise the module and shows the error `ts(2307)`, saying that the module cannot be found.

The issue seems to happen when a directory in the SvelteKit route starts with a `.`, such as `.well-known` for example. A file named `aaa/+server.ts` will not trigger the issue, but `.aaa/+server.ts` will. The issue only appears specifically when the folder name starts with the dot; having one in the middle or at the end (`aaa.aaa` or `aaa.`) don't seem to pose any problem.

This happens even if the project itself runs fine with `npm run dev`, with all routes producing their expected respective results.

### Reproduction

- Clone the repository at https://github.com/fyreplace/fyreplace-web (in which I am seeing the issue)
- Open the workspace in VSCode
- Open the file `src/routes/.well-known/apple-app-site-association/+server.ts`

### Expected behaviour

SvelteKit modules such as `$env/dynamic/public` should be properly recognised by the extension as long as SvelteKit itself is happy with it.

### System Info

- OS: macOS 13.2
- IDE: VSCode

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

I am putting `Svelte for VS Code extension` as the package this issue is about, since I'm experiencing this issue in VSCode; but I'm guessing the problem might as well be in the language server instead.

**Comment by jasonlyu123** [comment]
This is not related to the svelte language server or Svelte for VSCode, but to how TypeScript parses the `tsconfig.include` pattern. I dig into their source and found this comment.

```ts
const filesMatcher: WildcardMatcher = {
    /**
     * Matches any single directory segment unless it is the last segment and a .min.js file
     * Breakdown:
     *  [^./]                   # matches everything up to the first . character (excluding directory separators)
     *  (\\.(?!min\\.js$))?     # matches . characters but not if they are part of the .min.js file extension
     */
    singleAsteriskRegexFragment: "([^./]|(\\.(?!min\\.js$))?)*",
    /**
     * Regex for the ** wildcard. Matches any number of subdirectories. When used for including
     * files or directories, does not match subdirectories that start with a . character
     */
    doubleAsteriskRegexFragment: `(/${implicitExcludePathRegexPattern}[^/.][^/]*)*?`,
    replaceWildcardCharacter: match => replaceWildcardCharacter(match, filesMatcher.singleAsteriskRegexFragment)
};

```
https://github.com/microsoft/TypeScript/blob/1dc5b28b94b4a63f735a42d6497d538434d69b66/src/compiler/utilities.ts#L8382-L8396

They seem to intentionally ignore the directories that start with `.` while parsing `**`. But you can work around it by explicitly specifying. Add the following config in your `svelte.config.js` 

```diff
/** @type {import('@sveltejs/kit').Config} */
const config = {
  preprocess: vitePreprocess(),
  kit: {
    adapter: process.env.DOCKER ? nodeAdapter({ precompress: true }) : autoAdapter(),
+    typescript: {
+      config(config) {
+        config.include.push('../src/routes/.well-known/**/*.ts')
+
+        return config;
+      }
    }
  }
};
```

**Comment by LaurentTreguier** [comment]
I see, this workaround works perfectly; thank you!
