### ISSUE TITLE
Augmenting the language server's types for Svelte components

### ISSUE THREAD

**Issue by plushdohn** [sveltejs/language-tools#1866]
I'm writing a Rollup plugin which uses a set of custom attributes in Svelte components (similar to the `css` prop for [emotion](https://emotion.sh/docs/css-prop))

The idea is something like:
```svelte
<div css="something..." />
```

This works in JS, but I can't manage to augment the HTML elements types so that the language server doesn't yell at me.

Here's what I tried:
```typescript
import "svelte/elements";

declare module "svelte/elements" {
  export interface HTMLAttributes {
    css?: string;
  }
}
```
and
```typescript
import "svelte-check";

declare namespace svelteHTML {
  type HTMLProps = {
    css?: string;
  };
}
```

But none of them work. Is this even possible from the outside? Or does the language server use its own internal definitions for Svelte components? Thanks for your time.

**Comment by dummdidumm** [comment]
https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/typescript.md#im-using-an-attributeevent-on-a-dom-element-and-it-throws-a-type-error should help you
