### ISSUE TITLE
Availability on VSCode Online

### ISSUE THREAD

**Issue by avi12** [sveltejs/language-tools#1870]
### Description

I wish to be able to open up Svelte files with colorization on VSCode Online

### Proposed solution

Add the  support
It's much easier for me to navigate an IDE-like environment than GitHub

### Additional Information, eg. Screenshots

![image](https://user-images.githubusercontent.com/6422804/218827357-147d6281-78c2-4225-98a3-0a41ed50767b.png)

**Comment by jasonlyu123** [comment]
Duplicate of #1190
