### ISSUE TITLE
Component constructor sometimes expects no arguments.

### ISSUE THREAD

**Issue by rallets** [sveltejs/language-tools#1875]
Hi, I need to create a Component instance via Typescript, but VS Code complains about the arguments `Expected 0 arguments, but got 1.ts(2554)`.

Example:
```ts
const component: SvelteComponent & ComponentX;
const component = new ComponentX({
			props: {
				content: content,
			},
			target: document.body,
		});
```

hence I need to use `//@ts-ignore`.
There is any way to get rid of this nuance?
I know there is a Typescript type-safe work in progress, and used part of it (about events), but I struggled to find documentation for this specific issue.

Thank you

**Comment by rallets** [comment]
@jasonlyu123 in my case it's not related to TS server/transitive error, it just complains all the time 😁. 
Maybe I'm missing some definitions in the component itself? 
PS. The instance creation is from a custom action, but I don't think should matter.

The component is defined without any special care about typings:
```ts
<script lang="ts">
	export let content = '';
	[...]
</script>
```

**Comment by jasonlyu123** [comment]
Did you instantiate it in a ts/js file or a svelte file? What does the file content look like?

**Comment by rallets** [comment]
@jasonlyu123 it's a custom action, so I use a ts file.

The code is pretty similar to this, I just remove code which I think it should not matter:
```ts
import type { SvelteComponent } from 'svelte';
import ComponentX from '../components/ComponentX.svelte';

export function customaction(element: HTMLElement, content: string) {
	let componentX: SvelteComponent & ComponentX;

	function click(_: MouseEvent) {
		// error is in the next line
		componentX = new ComponentX({
			props: {
				content: content,
			},
			target: document.body,
		});
	}

	element.addEventListener('click', click);

	return {
		update: (content: string) => {
			tooltipComponent.content = content;
		},
		destroy() {
			element.removeEventListener('click', click);
		},
	};
}

```

**Comment by jasonlyu123** [comment]
I can't reproduce with your reproduction. So let's assume it's similar to what I saw before. The instantiation part seems right, so it should be a bug somewhere.

**Comment by rallets** [comment]
@jasonlyu123 tks for looking into this issue. I will try to reproduce the error in a repo with my same (and a little weird) setup/pipeline and I will let you know.

**Comment by rallets** [comment]
@jasonlyu123 I prepared a minimal repro. There is more stuff than needed because we use Svelte inside Razor Views, but it doesn't matter for this issue. I tried to remove as much stuff as possible, but keeping the original idea, so the bug was still there. Let me know if you need more help from my side.

Open VS Code in the folder `/src/`
In my VS Code the mentioned error is still visible in `src\App\shared\actions\uibtooltip.ts`

I'm not sure if you could be interested - or maybe it is related to this same issue - but there is also a `test` complaining about a Svelte component in `App\__tests__\Comp.svelte.test.ts` using '@testing-library/svelte'.
`Argument of type 'typeof Comp__SvelteComponent_' is not assignable to parameter of type 'Constructor<SvelteComponentDev>'.ts(2769)`

Thanks

**Comment by rallets** [comment]
@jasonlyu123 the repo is [here](https://github.com/rallets/svelte-repro-1875)

**Comment by jasonlyu123** [comment]
Your tsconfig.svelte.json is not loaded by TypeScript. And TSServer seems to lazy load some files in this situation, causing our shim files not to be loaded. We'll fix that, but in your case, you should separate your project to use two `tsconfig.json` so the config file can be loaded for the editor. TSServer only accepts config files named `tsconfig.json` or `jsconfig.json`.

**Comment by rallets** [comment]
tks @jasonlyu123 for the feedback, and sorry for the delay, I have been busy in the last few weeks.
I will take a look to possible alternative config solutions in my project.
