### ISSUE TITLE
Write out the number of files with problems alongside the error and warning count

### ISSUE THREAD

**Issue by ryanatkn** [sveltejs/language-tools#1879]
### Description

Currently when svelte-check finds errors, it writes out the diagnostics like this:

```
svelte-check found 38 errors and 0 warnings
```

It would be helpful to also include the number of files containing errors or warnings.

### Proposed solution

Including the file count could look like:

```
svelte-check found 38 errors and 0 warnings in 3 files
```

This commit has an example implementation: https://github.com/ryanatkn/language-tools/commit/19c11880bebc99bffefe64b48dcf13b169fbaf4d

I'd be happy to open a PR and make any changes.

### Alternatives

Keep the existing behavior, it's a minor thing.

**Comment by dummdidumm** [comment]
example implementation looks good to me! Feel free to open a PR for this - also remember to update the README (there's a part about the machine readable output)

**Comment by ryanatkn** [comment]
Thank you!
