### ISSUE TITLE
Await then without variable

### ISSUE THREAD

**Issue by PatrickG** [sveltejs/language-tools#188]
**Describe the bug**
I'm getting the error `Cannot read property 'end' of null` when using the {:then} without a variable.

**To Reproduce**
```html
<script>
  let promise;
</script>

{#await promise}
  Loading...
{:then}
  Loaded!
{/await}
```

**Expected behavior**
No error.

**Screenshots**
![image](https://user-images.githubusercontent.com/196478/84578581-dc566200-adc6-11ea-9bde-40da4e13991f.png)

**Additional context**
Output:
```
Error walking node  {
  start: 35,
  end: 83,
  type: 'AwaitBlock',
  expression: Node {
    type: 'Identifier',
    start: 43,
    end: 50,
    loc: SourceLocation { start: [Position], end: [Position] },
    name: 'promise'
  },
  value: null,
  error: null,
  pending: {
    start: 51,
    end: 61,
    type: 'PendingBlock',
    children: [ [Object] ],
    skip: false
  },
  then: {
    start: 61,
    end: 75,
    type: 'ThenBlock',
    children: [ [Object] ],
    skip: false
  },
  catch: {
    start: null,
    end: null,
    type: 'CatchBlock',
    children: [],
    skip: true
  }
}
```

**Comment by sw-yx** [comment]
nice one. i put out a request for first time contributors as this is a good first issue. happy to help whoever tries to tackle this.

**Comment by skippednote** [comment]
Hey there 👋
I've started looking into this and have raised a pull request #189.

**Comment by dummdidumm** [comment]
Thanks @skippednote ! Fix should be available in about 12 hours.
