### ISSUE TITLE
Svelte snippets in vscode extension don't work

### ISSUE THREAD

**Issue by FreHu** [sveltejs/language-tools#1883]
### Describe the bug

The snippets defined in `svelte-vscode/snippets/svelte.json` can't be invoked because they have no defined prefix. 
There are also js and ts snippets which do work.

Your snippet file:
```json
{
    "if": {
        "body": ["{#if ${1:condition}}", "\t$TM_SELECTED_TEXT$0", "{/if}"],
        "description": "if block"
    },
    "await": {
        "body": ["{#await ${1:promise}}", "\t$TM_SELECTED_TEXT$0", "{/await}"],
        "description": "await block"
    },
    "await then shorthand": {
        "body": ["{#await ${1:promise} then $2}", "\t$TM_SELECTED_TEXT$0", "{/await}"],
        "description": "await block without pending state"
    },
    "each": {
        "body": ["{#each ${1:array} as ${2:item}}", "\t$TM_SELECTED_TEXT$0", "{/each}"],
        "description": "each block"
    },
    "key": {
        "body": ["{#key ${1:key}}", "\t$TM_SELECTED_TEXT$0", "{/key}"],
        "description": "key block"
    }
}
```
Correctly defined snippet file
```json
{
    "if": {
        "prefix": "s-if",
        "body": ["{#if ${1:condition}}", "\t$TM_SELECTED_TEXT$0", "{/if}"],
        "description": "if block"
    },
    "await": {
        "prefix": "s-await",
        "body": ["{#await ${1:promise}}", "\t$TM_SELECTED_TEXT$0", "{/await}"],
        "description": "await block"
    },
    "await then shorthand": {
        "prefix": "s-await-then",
        "body": ["{#await ${1:promise} then $2}", "\t$TM_SELECTED_TEXT$0", "{/await}"],
        "description": "await block without pending state"
    },
    "each": {
        "prefix": "s-each",
        "body": ["{#each ${1:array} as ${2:item}}", "\t$TM_SELECTED_TEXT$0", "{/each}"],
        "description": "each block"
    },
    "key": {
        "prefix": "s-key",
        "body": ["{#key ${1:key}}", "\t$TM_SELECTED_TEXT$0", "{/key}"],
        "description": "key block"
    }
}
```
I'm not submitting a PR because I know there is a different plugin which has more snippets. It's possible you want to add more yourselves, use different prefixes or remove these snippets altogether.

### Reproduction

![image](https://user-images.githubusercontent.com/5097067/220163055-946d9fe7-05a7-474a-b56f-0042f9412dc3.png)

### Expected behaviour

I can show that my version works by modifying my local extension and reloading the window.
![image](https://user-images.githubusercontent.com/5097067/220163060-fd2ffd5c-e04d-45e5-a10f-614d60a564ea.png)

### System Info

- OS: Windows
- IDE: VSCode

### Which package is the issue about?

Svelte for VS Code extension

**Comment by gtm-nayan** [comment]
The prefixes for these snippets were deliberately omitted to avoid duplication with the more context-aware autocompletion. 

The snippets from the extension are mostly just intended for use with the `insert snippet` command to wrap them around existing code.

**Comment by FreHu** [comment]
I see, `insert snippet` indeed works without the prefixes. As this is by design, I'm closing the issue.
