### ISSUE TITLE
Props are not completed until component tag is closed

### ISSUE THREAD

**Issue by brunnerh** [sveltejs/language-tools#1884]
### Describe the bug

In VS Code, props are not completed until the tag is closed.
This is a bit inconvenient as it does not match the typical order of operations, which for me at least is:
- `<ComponentName`
- Possibly auto-import the component
- Set various properties
- `>`

### Reproduction

- Add a component file `component.svelte`
  ```svelte
  <script>
    export let value;
  </script>
  {value}
  ```
- Import and write `<Component val` in another file
- Check completions

### Expected behaviour

Property `value` is suggested and nothing else.

### System Info

- OS: Windows 10, 64bit
- IDE: VSCode

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

Open:
![image](https://user-images.githubusercontent.com/834235/220206560-d4ed9c28-43c2-4ac2-862e-16cc5c8eb1d1.png)

Closed:
![image](https://user-images.githubusercontent.com/834235/220206657-0e5998db-6ec6-4ab0-b106-0314bbf3a2fc.png)

**Comment by jasonlyu123** [comment]
This is a limation we have. See https://github.com/sveltejs/language-tools/issues/1302#issuecomment-1002358234 for the reason
