### ISSUE TITLE
css container query support

### ISSUE THREAD

**Issue by raythurnevoid** [sveltejs/language-tools#1888]
### Describe the bug

![image](https://user-images.githubusercontent.com/53383860/220332819-0ba34005-063c-46dd-b64b-38a14a096bf3.png)

A warning is raised when using the `container` CSS property: `Unknown property: 'container'`

![image](https://user-images.githubusercontent.com/53383860/220333031-74980bb9-7424-4af4-9011-d6e7ba9086e1.png)

### Reproduction

Use the "container" css property.

### Expected behaviour

To not show a warning.

### System Info

  System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 9 4900H with Radeon Graphics
    Memory: 17.99 GB / 31.42 GB
  Binaries:
    Node: 18.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1265.0), Chromium (110.0.1587.49)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/kit: ^1.7.2 => 1.7.2
    @sveltejs/package: ^2.0.1 => 2.0.1
    svelte: ^3.55.1 => 3.55.1
    vite: ^4.1.2 => 4.1.2

### Which package is the issue about?

Svelte for VS Code extension

**Comment by gtm-nayan** [comment]
@raythurnevoid Please check whether this issue also occurs in your editor in a plain `.css` file.

**Comment by raythurnevoid** [comment]
> @raythurnevoid Please check whether this issue also occurs in your editor in a plain `.css` file.

It does, looks like a vscode CSS linter issue

**Comment by jorri11** [comment]
I get a warning on this when running svelte-check, would that indicate it is not only an issue in vscode?
