### ISSUE TITLE
Typescript compilerOptions.path broken in svelte-check, working in VScode.

### ISSUE THREAD

**Issue by tobeqz** [sveltejs/language-tools#1908]
### Describe the bug

When I try to use typescript import aliases like "@lib/x/y/z", the project runs, builds and has no warnings in VScode. However, when I run svelte-check on it or try to edit the project using neovim (with [svelte-language-server](https://www.npmjs.com/package/svelte-language-server)) it gives me an error:
```
Cannot find module '@lib/Counter.svelte' or its corresponding type declarations. (ts)
  import svelteLogo from './assets/svelte.svg'
  import Counter from '@lib/Counter.svelte'
 ```

### Reproduction

See [https://github.com/tobeqz/svelte-lsp-bug](https://github.com/tobeqz/svelte-lsp-bug)

1. Create a new project using `npm init vite`, enable TypeScript
2. Edit the vite.config.ts, tsconfig.json and tsconfig.node.json to set up the @lib path alias (for specifics see the linked github repo)
3. Run svelte-check on the project and open the project in VScode with the svelte 3 extension.

It should work fine in VScode and be broken in svelte-check and svelte-language-server.

### Expected behaviour

svelte-check and the svelte-language-server should not be complaining, since the project builds just fine.

### System Info

- OS: Arch Linux
- IDE: NeoVim (lspconfig + svelte-language-server), VScode (Svelte 3 extension v107.1.2)

### Which package is the issue about?

svelte-check and svelte-language-server

**Comment by jasonlyu123** [comment]
```diff
    "paths": {
-        "@lib/*": ["src/lib"]
+       "@lib/*": ["src/lib/*"]
    }
```
