### ISSUE TITLE
Not much help with ts code within the html of svelte files

### ISSUE THREAD

**Issue by stemaDev** [sveltejs/language-tools#1916]
I've been using svelte for a year now, using typescript, vscode and this as a plugin. It's working great apart from one part:
**Code completion, code navigation, hover type info is not available in the html too much.** 
If I'm putting code into curly braces (either it's an if, each or just a simple value to insert), I rarely get code completion (sometimes I get it if I type the first character, cancel completion and reactivate it), there's no info when I hover over it (eg. type), can't navigate to a variable or the definition of a prop, no "right click -> find all references" (I mean there is, but it's not finding anything). Is this a configuration issue, as I was searching a lot before opening this ticket here.

Svelte for VS Code v107.1.2 (but it's been like this for around year for me, never worked)

Everything comes up for code completion, except for the variable created just above, also when I want to use it's properties. No hover information of what type it is, and when I ctrl+click it, it's not navigating anywhere.
![image](https://user-images.githubusercontent.com/43641170/222884664-426c4b9b-7146-4ad7-955a-f1578d97a6fb.png)
![image](https://user-images.githubusercontent.com/43641170/222884668-a3b18657-a346-462a-b7d4-a5bbf8f770f6.png)
![image](https://user-images.githubusercontent.com/43641170/222884678-8a854dad-33d1-4bbd-ba02-c5fbedb5b7c6.png)

Please help, it would make my life much easier. Thank You!

**Comment by jasonlyu123** [comment]
We need a reproduction to tell what is the exact problem. But in general, we have some limitations with our current approach. You can see #83 for more info. It won't be fixed anytime soon. But It should work fine If you don't use any custom preprocessor that introduces custom syntax and if you don't have any syntax errors in the template.
