### ISSUE TITLE
svelte-check errors on valid HTML <meta http-equiv>

### ISSUE THREAD

**Issue by vekunz** [sveltejs/language-tools#1917]
### Describe the bug

I am building a static site with SvelteKit (with static-adapter and csr=false). On the root route `/` I have no content and want the page to redirect directly to a language specific route `/de`. Therefore I have added a little snippet to the `+page.svelte` so that the browser should redirect directly to the sub-page. See the reproduction snippet down below.

The problem now is the `svelte-check` command. The command shows this error:
```
...\src\routes\+page.svelte:7:9
Error: Argument of type '{ "http-equiv": string; content: string; }' is not assignable to parameter of type 'HTMLProps<"meta", HTMLAttributes<any>>'.
  Object literal may only specify known properties, and '"http-equiv"' does not exist in type 'HTMLProps<"meta", HTMLAttributes<any>>'. (ts)
<svelte:head>
  <meta http-equiv="refresh" content="0; URL=/{Object.keys(data.languages)[0]}" />
</svelte:head>

```

### Reproduction

```svelte
<script lang="ts">
  import type { PageData } from './$types';
  export let data: PageData;
</script>

<svelte:head>
  <meta http-equiv="refresh" content="0; URL=/{Object.keys(data.languages)[0]}" />
</svelte:head>
```

### Expected behaviour

`svelte-check` should not complain about `<meta http-equiv>`.

### System Info

- svelte-check: 3.0.4
- svelte: 3.55.1
- sveltekit: 1.9.3

- OS: Windows 10
- IDE: WebStorm

### Which package is the issue about?

svelte-check

**Comment by dummdidumm** [comment]
This will be fixed by installing the next version of Svelte once it's released.
