### ISSUE TITLE
svelte:component with this and bind:this

### ISSUE THREAD

**Issue by PatrickG** [sveltejs/language-tools#192]
**Describe the bug**
I'm getting multiple errors when using `svelte:component` with `this` and `bind:this` attribute (Screenshots).
If I only use `this` the errors disappear.

**To Reproduce**
```html
<script>
  let component;
  let instance;
</script>

<svelte:component this={component} bind:this={instance} />
```

**Expected behavior**
No errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/196478/84600434-7d9df080-ae79-11ea-83cd-0726bcb73919.png)
![image](https://user-images.githubusercontent.com/196478/84600447-90b0c080-ae79-11ea-8d58-f5f7f2d202ef.png)

**System (please complete the following information):**
 - OS: Windows 10
 - IDE: VSCode
 - Plugin/Package: Svelte Beta 99.0.42

**Additional context**
The version of `svelte2tsx` in `vscode/extensions/svelte.svelte-vscode-99.0.42/node_modules/svelte2tsx/package.json` is `0.1.27`.
Shouldn't it be `0.1.4`?
![image](https://user-images.githubusercontent.com/196478/84600675-6a8c2000-ae7b-11ea-9c39-0f1e8b5e5159.png)

**Comment by jasonlyu123** [comment]
The problem is because of the processing of `bind:this` does not taken` svelte:component` into account. Honestly, I don't know what this binding could do lol.

As for `sveltetsx`'s version. the version in the reop doesn't get updated when released.

**Comment by jasonlyu123** [comment]
I got what it could do now. This problem itself isn't a complex one to be fixed. But like bind:this on component this would come with some caveat.
