### ISSUE TITLE
Importing HTMLFormAttributes and extending it in IntrinsicElements

### ISSUE THREAD

**Issue by wvhulle** [sveltejs/language-tools#1923]
### Description

Currently, it is not possible to write a file `form.d.ts` with the contents 
```
import { type HTMLFormAttributes } from 'svelte/elements';

declare global{ 
declare namespace svelteHTML {
	interface IntrinsicElements {
		form: HTMLFormAttributes & {
			'on:changeValue'?: (event: CustomEvent) => void;
			'on:allValid'?: (event: CustomEvent) => void;
		};
	}
}
}
```
Typescript says that form is already defined in svelte and it cannot be extended. If I drop the import, I can drop the global and typings are picked up by typescript, however, I cannot use the import anymore. How can I extend the form typings while keeping the imports?

### Proposed solution

I would like the user-provided svelteHTML.IntrinsicElements to extend the internal svelteHTML.IntrinsicElements, even when types are imported and the user-provided version contains imports.

### Alternatives

Use inline type import `import('svelte/elements').HTMLFormAttributes`.

### Additional Information, eg. Screenshots

Typescript 5.1, Svelte 3.55.1.

**Comment by jasonlyu123** [comment]
In svelte 4.2, you can use `declare module 'svelte/elements'` to enhance the attributes of a specific element 
https://svelte.dev/docs/typescript#enhancing-built-in-dom-types
