### ISSUE TITLE
shorthand class directive not working for props

### ISSUE THREAD

**Issue by cchyung** [sveltejs/language-tools#1925]
### Describe the bug

Getting an unused export property warning when using a prop with a class shorthand directive.

### Reproduction

Create a component with a boolean prop.  Use with shorthand class directive:

```ts
<script lang="ts">
    export let show: boolean = true
</script>

<div class:show={'show'} class='hidden'/>
```

### Expected behaviour

Shouldn't show me this warning

### System Info

- OS: macOS
- IDE: VSCode

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

<img width="817" alt="Screen Shot 2023-03-09 at 10 49 25 AM" src="https://user-images.githubusercontent.com/13970443/224078088-1482c181-3dec-4045-b649-ce9de4487e83.png">
<img width="739" alt="Screen Shot 2023-03-09 at 10 49 23 AM" src="https://user-images.githubusercontent.com/13970443/224078124-6ea793ad-a33b-41f2-b3f4-354c18019604.png">

**Comment by jasonlyu123** [comment]
```diff
<script lang="ts">
    export let show: boolean = true
</script>

-<div class:show={'show'} class='hidden'/>
+<div class:show={show} class='hidden'/>
```
