### ISSUE TITLE
Autocompletion doesn't work anymore in typescript files

### ISSUE THREAD

**Issue by Olyno** [sveltejs/language-tools#1930]
### Describe the bug

Following [the discussion on Discord](https://discord.com/channels/457912077277855764/1083794445641728040), it looks like the new versions of the extension break autocomplete: **107.2.1** and **107.2.2**

### Reproduction

Create a new Svelte kit project, add a server route, and tada, try to use autocomplete.

### Expected behaviour

It should autocomplete ``fetch`` in the below example.

### System Info

- OS: Linux
- IDE: Vscode

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

![See here: https://cdn.discordapp.com/attachments/1083794445641728040/1083794445813686322/Record_select-area_20230310174911.gif](https://cdn.discordapp.com/attachments/1083794445641728040/1083794445813686322/Record_select-area_20230310174911.gif)

**Comment by thelinuxlich** [comment]
Can confirm this bug

**Comment by alumpe** [comment]
Can confirm the bug for WSL2 on Windows 10. Normal .ts files have no issue, it is just + prefixed sk files.

**Comment by dummdidumm** [comment]
This is hopefully fixed with version 107.2.3.

**Comment by vnphanquang** [comment]
Sorry, is it me or did we all the type inference in for `*LoadEvent` (as shown in https://svelte.dev/blog/zero-config-type-safety)?

![20230311_095728](https://user-images.githubusercontent.com/25895844/224461392-5a5243d8-e6bb-4a1f-b7ad-aa40cd27e303.png)

Env Info

- OS: linux (ubuntu 22)
- VSCode v1.76.1
- Svelte Extension v107.2.3

Tested in project bootstrap with `create-svelte@latest`, all latest dependencies:

```json
{
	"@sveltejs/adapter-auto": "^2.0.0",
	"@sveltejs/kit": "^1.11.0",
	"eslint": "^8.36.0",
	"svelte": "^3.56.0",
	"svelte-check": "^3.1.2",
	"tslib": "^2.5.0",
	"typescript": "^4.9.5",
	"vite": "^4.1.4",
}
```

Dev server was running; VsCode was reloaded, no luck still.

**Comment by ghostdevv** [comment]
@vnphanquang You need to give that function a type
```ts
import type { PageServerLoad } from './$types';
 
export const load = (async (event) => {
}) satisfies PageServerLoad;
```

**Comment by vnphanquang** [comment]
@ghostdevv yeah, that has been the way, but not anymore (supposedly) in latest tooling support as shown in https://svelte.dev/blog/zero-config-type-safety though

**Comment by ghostdevv** [comment]
Ah, missed that - awesome! I'm not sure why it wouldn't work in that case :pray:

**Comment by jasonlyu123** [comment]
Did you have [svelte.enable-ts-plugin](https://github.com/sveltejs/language-tools/blob/master/packages/svelte-vscode/README.md#svelteenable-ts-plugin) enable?

**Comment by vnphanquang** [comment]
@jasonlyu123 yeah it's been on for me the whole time.

```json
{
    "svelte.enable-ts-plugin": true
}
```

All other options under `svelte.*` are left to default.

Not that it's helpful, but it did work for me for a split second after I opened vscode, but then not any more after that for any `load` function (while it's still okay for `data` in `+page`).

**Comment by jasonlyu123** [comment]
The plugin may be enabled for a small window before the API we use turns it off. You can check if it is on in your user config but off in your workspace config. If it isn't the case, open another issue with reproduction. It is likely a separate issue.

**Comment by vnphanquang** [comment]
Understood, thanks for the instruction. No workspace config in my case indeed. I'm gonna give it some time before opening another issue, maybe it's something from my setup i've not taken into account.
