### ISSUE TITLE
VSCode Svelte extension causes incorrect auto imports

### ISSUE THREAD

**Issue by zerosym** [sveltejs/language-tools#1945]
### Describe the bug

With the Svelte extension enabled any SvelteKit associated .ts file that the extension has purview of such as +page.ts, +layout.ts, etc. ends up with incorrect auto imports suggested.  For example, typing `z` suggests `node_modules/zod/lib/index` which, when selected, does not result in an import being added to the file.  Disabling the extension and reverting to the default typescript experience results in the expected behavior -- `import { z } from 'zod'`.  Typescript blocks in .svelte files do not suffer from this issue either.

### Reproduction

1. Create a new SvelteKit app with typescript
2. Attempt to import a node module within a +layout.server.ts file and observe the suggested import

### Expected behaviour

Node modules should be properly imported automatically, as with the Svelte extension disabled.

### System Info

- OS: MacOS
- IDE: VSCode

### Which package is the issue about?

Svelte for VS Code extension

**Comment by zerosym** [comment]
Well, I just tried again with a cleaner setup:

### Steps
1. Created a new vscode profile with no settings changed and the only non-default extension installed being Svelte.
2. npm create svelte@latest svelte-test  (using Sveltekit demo app, Typescript options)
3. npm i
4. Open src/routes/sverdle/+page.server.ts
5. Type the letter `h`


### With extension enabled:
![extension](https://user-images.githubusercontent.com/20721797/226145132-05add468-876c-4ad5-94a5-de38900a1850.png)

Selecting the handle_promise option
![extension import](https://user-images.githubusercontent.com/20721797/226145283-d9302b23-f263-47c8-9d3d-60ceb24d0e6f.png)

### After disabling Svelte extension:
![no extension](https://user-images.githubusercontent.com/20721797/226145142-c089f831-de3c-4158-9748-9eaf33a91fab.png)

Selecting the handle_promise option
![no extension import](https://user-images.githubusercontent.com/20721797/226145274-f6128ac0-e9f1-4a7a-8260-9af67482216f.png)





#### VSCode Info:

Version: 1.76.2
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:53:46.528Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: No

**Comment by dummdidumm** [comment]
Super strange - for me it looks like screenshot 2 in both cases (I'm on Windows though)

**Comment by zerosym** [comment]
I tried it with just plain javascript and still have the issue.  Additionally when I try to import from another file that's in the same directory the import path ends up being a weird concatenation of enough relative directory traversals to reach root with the absolute path to the file. 

Instead of ```import { a } from './somefile'``` it ends up being something like ```import { a } from '../../../../users/someuser/project/src/somefile'```

**Comment by dummdidumm** [comment]
Does the same happen in a `foo.ts` file (not a file with special meaning to SvelteKit)? Does the same happen if you diable the TypeScript plugin that comes with the Svelte for VS Code extension (setting is `"svelte.enable-ts-plugin"`)?

**Comment by zerosym** [comment]
Only +page, +server, etc. files are affected.  Normal .ts files and even script blocks within .svelte files are fine.  Still have issues with the `enable-ts-plugin` disabled.  Aliased imports work fine even in the SvelteKit special files, e.g. typing `dev` properly suggests and imports from `$app/environment`.

**Comment by jasonlyu123** [comment]
I can't reproduce it in WSL Ubuntu either. The difference between the module label is that we proxy TSServer's language service in the `page.xxx.ts` for auto typing. Our proxy doesn't have some caching (internal API) like TSServer. But from my testing, the auto import would still be correct even if the module label is "wrong". Does this still happen if you disable all the extensions? In VSCode 1.72, you can create an empty profile to disable and restore all the extensions easily.

**Comment by jasonlyu123** [comment]
Find the reproduction.

1. npm create svelte@latest Capital  or create under a directory with any capital letter
2. npm i
3. Open src/routes/sverdle/+page.server.ts
4. Type the letter h

This problem seems to be with inconsistent case sensitivity default in TypeScript's codebase.

**Comment by zerosym** [comment]
I made a mistake with my earlier comment of the `svelte.enable-ts-plugin` setting not doing anything -- turning it off does seem to fix the issue.

**Comment by jasonlyu123** [comment]
> Also on MacOS the users directory is capitalized /Users/username so that could explain the issue on Macs?

Yes. That's also why there is `import { a } from '../../../../users/someuser/project/src/somefile'`. In Windows, the Users directory is also in `/Users` We probably just both don't store our projects there. Ubuntu is case-sensitive, so it's probably not possible to reproduce it there. There'll be other weird problems though since there's inconsistency with default case-sensitivity.
