### ISSUE TITLE
Show lint error when rendering objects in HTML

### ISSUE THREAD

**Issue by probablykasper** [sveltejs/language-tools#1948]
### Description

Some time ago, I updated a value from a string to an object. I didn't update the code everywhere to handle that, so the website was showing `[object object]`.

### Proposed solution

I think people rarely want `[object object]` showing up, so showing lint errors when this happens would be very useful

**Comment by dummdidumm** [comment]
I think it's impossible to do this - we can't just warn on an object because we don't know whether or not `toString()` will return just `[object object]` or something that's actually readable (you could have a class there which implements `toString` to show something meaningful). Therefore closing.
