### ISSUE TITLE
`svelte-check` should fail when no files are checked

### ISSUE THREAD

**Issue by DetachHead** [sveltejs/language-tools#1952]
### Description

`tsc` fails if no files were checked:
```
> tsc
error TS18003: No inputs were found in config file 'C:/project/tsconfig.json'. Specified 'include' paths were '[]' and 'exclude' paths were '[]'.


Found 1 error.
```
however `svelte-check` does not:
```
> svelte-check --tsconfig .\src\tsconfig.json
Debugger attached.

====================================
Loading svelte-check in workspace: c:\project
Getting Svelte diagnostics...

====================================
svelte-check found 0 errors and 0 warnings in 0 files
```

### Proposed solution

fail if there were no files checked, as this almost certainly means there's an issue with your config

**Comment by gustavojms** [comment]
Hey, i'm willing to take this implementation, can it be assigned to me? Also it will be helpful if possible to specify all files that need to be changed to make this enhancement.

**Comment by dummdidumm** [comment]
Sure, go ahead! Change is likely scoped to inside `getDiagnostics` within `packages/svelte-check/src/index.ts`
