### ISSUE TITLE
JS/TS language service crashes

### ISSUE THREAD

**Issue by Ballig** [sveltejs/language-tools#1956]
### Describe the bug

When more than one Typescript file is opened then the JS/TS language service immediately crashes 5 times until VS Code disables it:

`The JS/TS language service immediately crashed 5 times. The service will not be restarted. This may be caused by a plugin contributed by one of these extensions: svelte.svelte-vscode. Please try disabling these extensions before filing an issue against VS Code.`

### Reproduction

Having more than one Typescript file open.

### Expected behaviour

The TS/JS language service to continue working.

### System Info

- OS: Windows_NT x64 10.0.19044
- IDE: VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
Extension version: 107.2.5

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

![svelte-ss1](https://user-images.githubusercontent.com/7276642/227149307-8bddbecf-9fe3-4597-b910-b59edbae39c6.PNG)
![svelte-ss2](https://user-images.githubusercontent.com/7276642/227149339-c0c6b255-1069-4e66-8eaa-a6bcbc1e6308.PNG)

**Comment by jasonlyu123** [comment]
Can you provide the log file listed in the TypeScript output?

**Comment by dummdidumm** [comment]
Strange, that log stop right after it says it's about to load the TypeScript plugin. What happens if you set `"svelte.enable-ts-plugin": false` in your VSCode settings? This should turn off the TypeScript plugin which should help in diagnosing whether or not it's related to something during its setup, or if the whole plugin is somehow corrupted on disk. If it keeps happening with the TS plugin turned off, does this error go away when you disable the Svelte extension completely?

**Comment by Ballig** [comment]
I still get the JS/TS language service immediately crashing 5 times (when opening a second TS file) after turning the Enable TS Plugin option off (and restarting VS Code). The error does go away when disabling the Svelte extension completely.

**Comment by dummdidumm** [comment]
Interesting - this sounds to me like the installation is corrupted in some way. Does manually deleting the extension from disk and then reinstalling it help? Alternatively, does manually deleting the extension and then manually downloading and installing it from https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode help?

**Comment by Ballig** [comment]
I manually deleted the extension from disk and then reinstalled it from within VS Code - JS/TS language service still crashed.

I manually deleted the extension from disk and downloaded the VSIX file and used "Install from VSIX" to install it - JS/TS language service still crashed.

**Comment by dummdidumm** [comment]
Not gonna lie, I'm alsmost out of ideas at this point 😓 I'm also on Windows 10 with the same VS Code / extension version and don't experience this. Things you could try:
- disable all other extensions except the Svelte extension to see that it's not some weird extension interop issue
- reinstall VS Code (yeah, I know ... sucks)

**Comment by Ballig** [comment]
I don't have any other extensions installed. I have also tried using the Visual Studio Code - Insiders installation. The only difference with that is that the JS/TS language service continually crashes rather than being disabled after crashing 5 times. I have also tried with the "JavaScript and TypeScript Nightly" extension installed to see if it's a Typescript version issue.

**Comment by jasonlyu123** [comment]
I am guessing it might be TSServer running out of memory. Among all the things I tried, this is the only way I can get the tsserver to crash with a typescript plugin. Can you provide your tsconfig/jsonfig?

**Comment by Ballig** [comment]
tsconfig for this project (added the 'txt' extension so github would accept it):
[tsconfig.json.txt](https://github.com/sveltejs/language-tools/files/11049466/tsconfig.json.txt)

**Comment by jasonlyu123** [comment]
It seems like the exception thrown in `languageServiceHost.getScriptSnapshot` would probably crash TSServer as well. Either way, it might be project related. And we'll need a reproduction repository in that case.

**Comment by Ballig** [comment]
I just created a brand new Svelte project (barebones with Typescript syntax), then in VS Code (with all formerly opened files closed) opened `app.d.ts` from the `src` directory and created a new file in `routes` called `+page.server.ts` (which was blank) and opened it in VS Code, and the JS/TS language service crashed.

**Comment by Ballig** [comment]
An update on this - if I use VS Code's `Explorer` mode to open the base Svelte project folder (where the tsconfig file is located) and open Typescript files through there, then I can have multiple files open and the language service doesn't crash. I'm new to this IDE but I assume this is how VS Code is meant to be used, and when files are being opened individually rather than by using `Open Folder` then either the Svelte extension or VS Code can't handle it (noting that the crash only happens when the Svelte extension is trying to provide Svelte-specific Typescript intellisense).

If this is expected behaviour then this issue can probably be closed, and this is the solution for anyone having the same issue in the future who searches the web for this endlessly like I did.

**Comment by Ballig** [comment]
Yes, that's correct.

**Comment by dummdidumm** [comment]
Thanks - I can reproduce it that way.

**Comment by dummdidumm** [comment]
Seems to have slipped in through #1910 - if I comment out `project.addRoot(scriptInfo);` it no longer crashes. It crashes at some debug assertion within the TS server where it's looking up the number of roots and some inferredProject status.

**Comment by Ballig** [comment]
Glad you were able to identify it!

**Comment by jasonlyu123** [comment]
Both should work since projectRootPath isn't fast in #1875 (where you opened a workspace without a tsconfig.json). Maybe it's better, at least for now, to use `(project as any).projectRootPath` to check. Since we haven't checked what other exceptions would be thrown in other types of `Project`.

**Comment by mrgharabaghi** [comment]
Same issue for me with `Svelte for VS Code v107.2.5`.

![p](https://user-images.githubusercontent.com/40915667/229191491-4a0efea1-c2d3-40b4-a312-6f46116fce27.jpg)

Steps:
1. Completely close the VS Code.
2. Open `a.js` (Double click on the file) with VS Code.
3. Open `b.js` (Double click on the file) with VS Code.
4. Crash happens (JS/TS language service).

`a.js`
```js
setTimeout(() => {
    await new Promise();
}, 1000);
```

`b.js`
```js
setTimeout(() => {
    await new Promise();
}, 1000);
```

**Comment by mrgharabaghi** [comment]
@dummdidumm
