### ISSUE TITLE
event types not recognized when `createEventDispatcher` is assigned to a different variable

### ISSUE THREAD

**Issue by DetachHead** [sveltejs/language-tools#1961]
### Describe the bug

if `createEventDispatcher` is assigned to a different variable and that variable is called, the event types are not recognized.

### `a.svelte`
```svelte
<script lang="ts" strictEvents>
    import { createEventDispatcher } from 'svelte'

    const foo = createEventDispatcher
    const dispatch = foo<{ a: string }>()

    dispatch('a')
</script>
```
### `b.svelte`
```svelte
<script lang="ts" strictEvents>
    import A from './a.svelte'
</script>

<A on:a={() => {}} /> <!-- Argument of type 'string' is not assignable to parameter of type 'never'. -->
```

### Expected behaviour

no error

### System Info

- OS: windows 10
- IDE: vscode

### Which package is the issue about?

svelte-check

### Additional Information, eg. Screenshots

very low priority imo, as i can't think of a valid use case for writing code like that

**Comment by dummdidumm** [comment]
#1388 and this probably have the same underlying issue

**Comment by jasonlyu123** [comment]
This is because we tracked the dispatcher by name and didn't check if it got assigned to another variable. So it's not related to #1388. Maybe we shouldn't support this since it's an edge case that might have no use case. Checking this might mean we also have to check these cases. Not sure if this is worth the effort. 

```ts
    import { createEventDispatcher } from 'svelte'

    const foo = createEventDispatcher
    const bar = foo
    const dispatch = bar<{ a: string }>

    dispatch('a')
```

and 

```ts
    import { createEventDispatcher } from 'svelte'

    const foo = createEventDispatcher
    
    const dispatch1 = foo<{ a: string}>()
    const dispatch2 = createEventDispatcher<{ b: string }>()

    dispatch1('a')
```

**Comment by dummdidumm** [comment]
Yeah probably not worth the effort at this point.

**Comment by dummdidumm** [comment]
Svelte 5 deprecated `createEventDispatcher`, therefore closing
