### ISSUE TITLE
`strictEvents` event dispatchers can be called without providing a value when the event key is not optional

### ISSUE THREAD

**Issue by DetachHead** [sveltejs/language-tools#1966]
### Describe the bug

if a key in an event dispatcher type is required, it can be dispatched without a value, causing the `CustomEvent.detail` to be `null` at runtime when typescript does not say it's nullable

### `a.svelte`
```svelte
<script lang="ts" strictEvents>
    import { createEventDispatcher } from 'svelte'

    const dispatch = createEventDispatcher<{ a: number }>()
</script>

<button on:click={() => dispatch('a')}>asdf</button>
```
### `b.svelte`
```svelte
<script lang="ts" strictEvents>
    import A from './a.svelte'
</script>

<A
    on:a={(e) => {
        // no typescript error, crashes at runtime
        console.log(e.detail.toString())
    }}
/>
```

### Expected behaviour

the function created by `createEventDispatcher` should require the `detail` argument when the `EventKey` type is required.

the updated function signature could look something like this:
```ts
type RequiredKeys<T> = Exclude<{
    [K in keyof T]-?: undefined extends T[K] ? never : K;
}[keyof T], keyof {}>

type OptionalKeys<T> = Exclude<keyof T, RequiredKeys<T>>

declare function createEventDispatcher<EventMap extends {} = any>(): {
    <EventKey extends RequiredKeys<EventMap>>(type: EventKey, detail: EventMap[EventKey], options?: DispatchOptions): boolean;
    <EventKey extends OptionalKeys<EventMap>>(type: EventKey, detail?: EventMap[EventKey], options?: DispatchOptions): boolean;
}
```
[playground](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&allowUnreachableCode=true&allowUnusedLabels=true&noUnusedLocals=true&target=99&jsx=0&isolatedModules=true&useUnknownInCatchVariables=true&exactOptionalPropertyTypes=false&noFallthroughCasesInSwitch=true&noImplicitOverride=true&noPropertyAccessFromIndexSignature=true&suppressImplicitAnyIndexErrors=false#code/JYOwLgpgTgZghgYwgAgCLAM4Ac5gQCwHksxgB7EDZAb2QF8AoBsATyxQCUIBHAV2CgQAJgGkILDAB4AKgD5kAXmQBRAB4IANryERJ1BskPIA2iOShkAa3FkYyaQF0AtAH4AXMl4gdMUMOQQqpDeVNKmDsguyCAQAG7QyB4iANwMdMbWLLb2DgA0VjZ21HSyTKzsyMSkFHAaYhIy8kpqmtq6mdnS+Vx8AsL1UnKlDDqacILIMF4I1SDICIK4EMrx4OjYuATQkisQ4ACycFgBQXtCVMWKyHAgLLIAFACUHvpGyDurYPUnwefIPfxBKJxFJdgcjrIHuUIB4wV9xPkdGA4MANLDPocsMY4fU8sgyCRyJR3GhMDg8ERCRQMM9kAAjMhkDQQG6pN4fPbwlg-M5UKpE2oDDngrCQ+7Q9Gc+qIiDI1EkuGY7GfXH5AmzDAk9bkgj86m0hlMlkgVKMBgIalgZBCMmbfBXBYsyBw7V27a0OAkjBgKCgADm+TpHm9vpAfvoD0eTBtGwp9wA5HB449kAB6VPRMgBKBQMhQZAYUBIQxwcxUdUCjQjW1xxPx-Lx5NpjMgLPQXNQaM1ggJulN9PZjv0iAIOC8DAoOll5CCXpA6uxnvxvsN-stts5vNAA)

### System Info

- OS: windows 10
- IDE: vscode

### Which package is the issue about?

svelte-check

**Comment by jasonlyu123** [comment]
See upstream PR https://github.com/sveltejs/svelte/pull/7224

**Comment by jasonlyu123** [comment]
Fixed in svelte 4
