### ISSUE TITLE
Error when no content is in the script

### ISSUE THREAD

**Issue by jasonlyu123** [sveltejs/language-tools#197]
**Describe the bug**
Error when no content is in the script,

error logged:

Notification handler 'textDocument/didChange' failed with message: Cannot read property 'startOffset' of undefined
```
TypeError: Cannot read property 'startOffset' of undefined
(C:\Projects\language-tools\packages\language-server\dist\src\lib\documents\utils.js:102:28)
    at SvelteDocumentSnapshot.get scriptKind [as scriptKind] (C:\Projects\language-tools\packages\language-server\dist\src\plugins\typescript\DocumentSnapshot.js:105:92)
    at Object.updateDocument (C:\Projects\language-tools\packages\language-server\dist\src\plugins\typescript\service.js:87:67)
...
```

**To Reproduce**
```svelte
<script></script>
```

**Expected behavior**
no error

**System (please complete the following information):**
 - Plugin/Package: `svelte-language-server`,

**Comment by sw-yx** [comment]
i'll put out a call for this one

**Comment by NicoCevallos** [comment]
I tried to reproduce the issue but I couldn't. But I could get this issue that can be solve adding a new line
![image](https://user-images.githubusercontent.com/10197397/84815538-8e6d7400-afe9-11ea-8deb-8cb102e60303.png)
Anyways you would be able to create a `.svelte` file without a `script` tag.
Also, could you provide more info? VS Code version, Svelte Beta extension version, etc.
And if you could provide a little repo showing the issue, it would be better to understand the scenario and test it easily.

**Comment by jasonlyu123** [comment]
It's same error. Although it is simple to get away with, it still needs to be fixed.
