### ISSUE TITLE
svelte-language-server fails to infer function type for load method in +server.ts page

### ISSUE THREAD

**Issue by flmng0** [sveltejs/language-tools#1971]
### Describe the bug

In `+page.ts` and `+page.server.ts` files, the type for `load` events does not get inferred.

According to https://svelte.dev/blog/zero-config-type-safety , I should not need to explicitly type the parameter of the exported load function in said files.

### Reproduction

Create any API route, e.g `src/routes/+page.server.ts`, and add a load function to the file, like below:

```typescript
export async function load(event) { // ERROR: Parameter 'event' implicitly has an 'any' type.
  const { fetch } = event;

  const response = await fetch(/* ... */);

  return await response.json();
}
```

### Expected behaviour

The type of the `event` parameter in the function below should be inferred.

```typescript
export async function load(event) {
  const { fetch } = event; // <-- type of fetch should be automatically inferred.

  // ...
}
```

### System Info

- OS: Fedora 37
- IDE: NeoVim using Mason and svelte-language-server@0.15.8

### Which package is the issue about?

svelte-language-server

**Comment by flmng0** [comment]
I forgot to mention, but all works fine if I explicitly type the `event` parameter, e.g with `PageLoadEvent`, but this is specifically called out in the blog post as not being necessary anymore.

**Comment by dummdidumm** [comment]
Did you install and enable the TypeScript plugin? If you're not using VS Code, you need to set it up manually: https://www.npmjs.com/package/typescript-svelte-plugin

**Comment by flmng0** [comment]
Hi @dummdidumm , I have now installed the plugin and it works properly now.

Where was this documented? I was really struggling for it to be such a simple fix 😅

**Comment by dummdidumm** [comment]
This paragraph in the blog post is mentioning it (but not linking to it, probably should):

> To use this feature with VS Code install the latest version of the Svelte for VS Code extension. For other IDEs, use the latest versions of the Svelte language server and the Svelte TypeScript plugin. Beyond the editor, our command line tool svelte-check also knows how to add these annotations since version 3.1.1.

**Comment by flmng0** [comment]
Thank you for your help. I'll close this, but I think this should be more clearly documented, as the name for the plugin isn't mentioned either.

Good work though, I'm loving the new experience!
