### ISSUE TITLE
Slow Intellisense after Update to VSCode v1.77.x

### ISSUE THREAD

**Issue by KiddoV** [sveltejs/language-tools#1984]
### Describe the bug

Not sure what happen but the Svelte Intellisense is extremely slow after I update the VSCode:

``*.svelte`` file example:

![svelte-slow](https://user-images.githubusercontent.com/28552977/231504379-7f0c6ddf-a826-4928-934e-31863cd73055.gif)

``*.ts`` file example

![ts-not-slow](https://user-images.githubusercontent.com/28552977/231504548-c6d747bf-dc4f-48ec-aac1-56c0c7fe1126.gif)

As you can see, with ``svelte`` file it took over 5 secs for VSCode to know it is the wrong syntax, on the other hands, ``ts`` file only took ~1 sec.

### Reproduction

See above!

### Expected behaviour

Faster response when typing...

### System Info

- OS: Windows 10
- IDE: VSCode v1.77.x

### Which package is the issue about?

Svelte for VS Code extension

**Comment by jasonlyu123** [comment]
Does this happen when you disable all other extensions? You can create an empty setting profile and only install the Svelte extension.

**Comment by KiddoV** [comment]
This still happen when I disabled all other extensions and only use ``Svelte ext``.

I tried on a different projects/repo. Looks like it is faster somehow.

**Comment by jasonlyu123** [comment]
No idea. Can you try these to narrow it down more?
- If you have a custom preprocess config, try to remove it and see if it helps
- Check if the "include" and "exclude" in your tsconfig.json include any generated files.
- 1. Enable "svelte.language-server.debug": true 
  2. Go to the output channel, choose Svelte in the top-right dropdown, and see what is logged. 
- Checking if you imported a large library or a large JSON file. If so, try to remove it and restart the language server.

**Comment by LFan2333** [comment]
can second this, revert back to 107.0.0 make mine work again,

The latest version simply didn't work, at all. even with CTRL+SPACE, (brings out a loading option that will stuck forever)

Weirdly, when I was on the latest version, in the first few seconds of opening VS Code intellisense was working, but it will fail very soon and then stop completely.

windows 10 Pro 1909
vs code 1.77.3

buggy version: Svelte for VS Code 107.3.0
last working version: Svelte for VS Code 107.2.5

Hope this helps

**Comment by jasonlyu123** [comment]
It might have something to do with TypeScript 5.0 or the fix-all quick-fix. But we still need a reproduction to know what the problem is. TypeScript 5.0 has a lot of changes. We cannot find the problem by just looking at the git diff. 

I can't reproduce it with a large file. I created a 2000 lines file, and it's still pretty responsive. It might have something to do with the content of that file instead. Could you try commenting out some of the code to narrow the problem?

**Comment by WoodyWoodsta** [comment]
This is an issue for me even on VSCode 1.78.2, vscode-svelte v107.4.3. Will try to reproduce when I have time.

**Comment by gl-aagostino** [comment]
Related? Mine language servers are just endlessly crashing 

![image](https://github.com/sveltejs/language-tools/assets/96190420/a9e90a15-336e-4af9-8030-5d87a17e8dc8)

**Comment by KiddoV** [comment]
Any update on this?
Downgrade to Svelte for VS Code: ``v107.2.5`` seem to fix the issue for me, but still, we always want to use the newest version.

**Comment by WoodyWoodsta** [comment]
Possibly related: https://github.com/tailwindlabs/tailwindcss-intellisense/issues/755#issuecomment-1594675718

**Comment by jasonlyu123** [comment]
We won't be able to help you if we can't reproduce the problem.

**Comment by KiddoV** [comment]
> We won't be able to help you if we can't reproduce the problem.

This will be hard to re-produce, as the issues only occur in random ``*.svelte`` files.

**Comment by KiddoV** [comment]
> Possibly related: [tailwindlabs/tailwindcss-intellisense#755 (comment)](https://github.com/tailwindlabs/tailwindcss-intellisense/issues/755#issuecomment-1594675718)

Tried disable ``Tailwind CSS IntelliSense``, but still having the problem.

**Comment by WoodyWoodsta** [comment]
The more important point was that there was a potential fix for the underlying cause in VScode 1.80 https://github.com/microsoft/vscode/issues/184926#issuecomment-1594190928

**Comment by KiddoV** [comment]
VS Code 1.80.0 has just been released, and I have updated my version. However, the issue I was experiencing still persists.

**Comment by Hunnnn77** [comment]
even in same svelte file with less code, emmet/css/tailwind are fast, only js/ts realated things for svelte (declaration something in script tag / using func,var from script, html attribute svelte specific syntax) are laggy. comparing tsx file, i think svelte lang server seems slower than.

**Comment by jasonlyu123** [comment]
[108.1.0](https://github.com/sveltejs/language-tools/releases/tag/extensions-108.1.0) improves the performance of files with big html. Does this address the problem you all have? 

If not, sorry for repeating it. Please provide a reproduction. You don't have to submit the problematic repository. You can check for things in common for files with performance problems or try removing stuff from those files to narrow down the problem. 

As a last resort, you can provide a CPU profile so we can at least know where the bottleneck is. 
To do so, you can follow the steps:

1. Set the "svelte.language-server.port": config to 9222.
2. Restart your editor and open a svelte file.
3. Open Chrome or Edge and type chrome://inspect. Wait a bit. There should be a svelte language server, and you can inspect
4. After you click the inspect link, a dev tool will open. You can record a CPU profile in the performance tab

**Comment by MiraiSubject** [comment]
In my case the cause of the slow IntelliSense was the addition of `"svelte-google-materialdesign-icons": "^0.8.3"` this exports all of its components for the icons and makes autocomplete very slow to load. I am also using `svelte-fa` for fontawesome icons that we are using. I guess for now I will settle on one of these which is the more sensible choice anyway.  

I have included a CPU profile of how long it takes to load with this package added: [CPU-20240101T203600.cpuprofile](https://github.com/sveltejs/language-tools/files/13805693/CPU-20240101T203600.cpuprofile)


Here is the profiler with `svelte-google-materialdesign-icons` removed: [CPU-20240101T204056-after.cpuprofile](https://github.com/sveltejs/language-tools/files/13805698/CPU-20240101T204056-after.cpuprofile)

**Comment by sekoyo** [comment]
I'm disappointed in the perf in Svelte 5 too. Things are noticeably sluggish on an M1 Max Pro even in a simple .svelte file. Shame!
