### ISSUE TITLE
svelte-check: Crashing while getting TypeScript diagnostics. Better error message needed.

### ISSUE THREAD

**Issue by eunukasiko** [sveltejs/language-tools#1985]
I get only this output from `svelte-check --output machine`

```
1681387004452 START "/home/user/app"
1681387010843 FAILURE "Debug Failure."
```

How do I figure out what's causing the failure?

**Comment by eunukasiko** [comment]
The crash occurs within `...lang.getSuggestionDiagnostics(file.fileName),`. Can we add some graceful handling of this function crashing?

https://github.com/sveltejs/language-tools/blob/d5b29f07923504b527af36f1eb96e59b7d0a891e/packages/language-server/src/svelte-check.ts#L231

**Comment by jasonlyu123** [comment]
That is an error thrown by TypeScript for unexpected behaviour or state. Not from our code. From the stack trace, I guess this is TypeScript 5.0.4. And has something to do with the module specifier having ".ts" in it. Please check if you have that and provide a reproduction.

**Comment by eunukasiko** [comment]
The problem was caused by a file that imports from another Svelte library. Adding `"allowImportingTsExtensions": true,` to tsconfig.json stopped the crashing.

**Comment by dummdidumm** [comment]
Please provide a reproduction so we can investigate if this is a bug on our side or not.

**Comment by dummdidumm** [comment]
Closing as inactive and lack of reproduction.
