### ISSUE TITLE
Copilot doesn't use related files for suggestions

### ISSUE THREAD

**Issue by stylehouse** [sveltejs/language-tools#1987]
Type: <b>Bug</b>

Here's a small repro. I have this in VSCode.

in a Svelte project, in src/lib/St.ts:

    export function detection(s) {
        let typ = {}
        if (s.such) typ.A = 1
        if (s.else) typ.B = 1
        return typ
    }

in src/routes/Code.svelte:

    import {detection}  from '$lib/St'
    let typ = detection({such:1})
    if (typ.

Then it seems to know nothing about typ.A|B
If you define detection() in Code.svelte it does suggest good.
Unrelated to the $lib alias (using ../lib/St also doesn't work).
It also seems unrelated to Svelte: I get bad completions even in Steez.ts, importing from './lib/St'.
I am new to the js world, my intuition from here is that vite (part of Svelte) may be complicating things (I know not how), but I would expect that the Svelte for VS Code plugin would know how to present that to Copilot.

What is limiting its view? https://github.com/orgs/community/discussions/13617 says "Just files adjacent to the current file in the ide." but that still doesn't do it (if I place St.ts and Steez.ts tabs next to each other?).

This is also reported|posted in https://github.com/orgs/community/discussions/46246 but expect you will have better answers.

Thanks.

Extension version: 107.3.0
VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:57:21.103Z)
OS version: Linux x64 5.19.0-38-generic snap
Modes:
Sandboxed: Yes

**Comment by jasonlyu123** [comment]
I can't find any documentation where an extension can provide language context to Github Copilot. This is probably out of the scope of the Svelte for VSCode extension. If you find related documentation, let us know and we can see what we can do.
