### ISSUE TITLE
Suggestions not working in `#each` statement after inserting a dot

### ISSUE THREAD

**Issue by YummYume** [sveltejs/language-tools#1990]
### Describe the bug

When using a `#each` statement and accessing an object's properties, the suggestions will stop working after inserting a dot. See the video below for a better explanation :

https://user-images.githubusercontent.com/61044908/233153418-44ca9a39-9d0c-4278-8f46-eb298dd7a546.mp4

Intellisense is not working as expected after inserting a dot. But if I delete a letter or use CTRL + Space, I get my suggestion `testArray` as expected. I tested this in multiple scenarios and on a clean editor and it does it too.

What seems weird to me is that this only happens with `#each` statements, `#if`, `#key` and so on are fine. This is more of an annoyance than anything, I am just very used to having my suggestions after inserting a dot.

### Reproduction

Using the following code : 

```svelte
<script lang="ts">
    const testObj = {
        testArray: [1, 2, 3],
    };
</script>

{#each testObj as array}
    {array}
{/each}
```

After inserting a dot, VSCode will not suggest `testArray`.

### Expected behaviour

I would expect to get the usually suggested properties of my object.

### System Info

- OS: Kubuntu 22.04
- IDE:
  - VSCode
  - Version: 1.77.3
  - Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
  - Date: 2023-04-12T09:16:52.732Z
  - Electron: 19.1.11
  - Chromium: 102.0.5005.196
  - Node.js: 16.14.2
  - V8: 10.2.154.26-electron.0
  - OS: Linux x64 5.15.0-69-generic
  - Sandboxed: No

### Which package is the issue about?

Svelte for VS Code extension

**Comment by jasonlyu123** [comment]
This is a limation we have. See https://github.com/sveltejs/language-tools/issues/1302#issuecomment-1002358234 for the reason. We have a workaround for property access but not for this specific situation. Becuase our workaround might have problems in this case.

**Comment by YummYume** [comment]
Hi @jasonlyu123, thanks for clarifying things. I suppose since it's a limitation, this can be closed and will (hopefully) be fixed somewhere in the future.

**Comment by Skycweb** [comment]
I also encountered the same problem

**Comment by bugproof** [comment]
It also doesn't work inside of each... :(
