### ISSUE TITLE
Get launch.json to work for vscode extension from the root of the repo

### ISSUE THREAD

**Issue by orta** [sveltejs/language-tools#2]
Right now you need to `cd` to that sub-folder to get that working.

**Comment by jasonlyu123** [comment]
Have you done this? I have tried to do this already yesterday.

**Comment by orta** [comment]
Nope, not done this!

**Comment by jasonlyu123** [comment]
ok, I'll make a PR for it

**Comment by orta** [comment]
Fixed by #7
