### ISSUE TITLE
My component emits the warning `Components is not defined svelte(missing-declaration)`

### ISSUE THREAD

**Issue by XLearner** [sveltejs/language-tools#2002]
I have created a Test.svelte component and imported it into App.svelte. Then my vscode emits the following warning:

![image](https://user-images.githubusercontent.com/26158725/236420045-f319df3b-1732-40de-83b3-6f7d1930fb8e.png)

And when I remove the attribute of `lang="ts"`, this warning vanishes.

Does anyone know the reason? 🙏🏻

**Comment by XLearner** [comment]
And if the 'lang="ts"' is removed, the TypeScript syntax will no longer work.

**Comment by jasonlyu123** [comment]
Can you provide your `svelte.config.js`? It might have something to do with your preprocess config.

**Comment by XLearner** [comment]
> 

It seems the problem of the `Svelte for VS Code` extension. I find this issue have done when updating this extension to the latest versions. Thanks.

**Comment by joelmukuthu** [comment]
I was able to reproduce this, in my case it occurs if I configure `compilerOptions.module` as `commonjs` in tsconfig.json -- which doesn't for Svelte/TS. I'm not sure if the error message could be improved though..

**Comment by dummdidumm** [comment]
CLosing as inactive and lack of reproduction.
