### ISSUE TITLE
Running svelte-check on files changed in a Pull Request

### ISSUE THREAD

**Issue by andyasberry** [sveltejs/language-tools#2017]
Hello! Thanks for all the work here!

I am trying to implement a workflow in GitHub Actions to serve as a pull request check for any failures from `svelte-check` relative to files changed (and line numbers).

I feel that others in the community may benefit from it, if it can be implemented correctly.

Would it be a good idea to share a snippet, example, or gist of the workflow, once it is complete?

We have a project that already has a lot of errors, and we want to prevent more from being introduced. Here is what I'm trying:

* use existing actions from the community to detect files and line numbers changed in a pull request
* wrap the svelte-check in a try/catch within github-scripts action
* parse the output from svelte-check
* use the parsed output from svelte-check to compare against files and line numbers changed/added/etc.
* if there is a match, fail the workflow, else it passes
* hopefully show some helpful output to the pull request author

Please let me know what you think! Thanks again!

**Comment by jasonlyu123** [comment]
Only checking changed files won't catch all the new errors. For example, If you change the parameters of a function, all the current usage of the function might have a type check error. So You may need to store the previous diagnostics somewhere and use those to compare. But the location might change because of new codes. Making the comparison much more complex. I don't know if that is worth the effort. Maybe it's easier to add `@ts-expected-error` and a TODO comment so you can gradually fix them later.

**Comment by andyasberry** [comment]
> The proposal to only check specific came up previously and we closed it with the same reasoning - it's not possible to know which files are affected by the changes without constructing a module graph, at which point you already did the bulk of the type checking work.
> 
> I'm not really sure what the request here is - do you want to add something to `svelte-check` or is this just informational that you want to do this and want feedback on it?

For now, this is more informational. I believe I have it almost working, including for new files, etc.

Once I can get it working, I'd be happy to share and you can include a recipe in your docs, if you like.

In the GitHub workflow, the process is basically:

* wrap the `svelte-check --output machine` in a try/catch, so that it doesn't fail
* pipe the output into a variable
* get the files changed/added/removed, along with line numbers, using [this action](https://github.com/tj-actions/changed-files) for files, and [this action](https://github.com/Equip-Collaboration/diff-line-numbers) for lines changed
* compare the output from `svelte-check` with what's changed, and if there is an overlap, we have an error, else no new errors have been added

**Comment by jasonlyu123** [comment]
I am not sure if you understand what we meant. Considering this:

```ts
// foo.ts
export function foo() {}
```

```ts
// bar.ts
import { foo } from './foo';

function bar() {
   foo()
}
```

If you add a parameter to `foo`. 

```diff
// foo.ts
-export function foo() {}
+export function foo(name: string) {}
```

The changed file only has `foo.ts`, but there is a new error in `bar.ts` because the `foo` function now requires one parameter. If you only fail when changed locations have an error, this error won't be caught.

**Comment by andyasberry** [comment]
> I am not sure if you understand what we meant. Considering this:
> 
> ```ts
> // foo.ts
> export function foo() {}
> ```
> 
> ```ts
> // bar.ts
> import { foo } from './foo';
> 
> function bar() {
>    foo()
> }
> ```
> 
> If you add a parameter to `foo`.
> 
> ```diff
> // foo.ts
> -export function foo() {}
> +export function foo(name: string) {}
> ```
> 
> The changed file only has `foo.ts`, but there is a new error in `bar.ts` because the `foo` function now requires one parameter. If you only fail when changed locations have an error, this error won't be caught.

You're right. Please forgive my ignorance 🙏 . I've read this in the docs for now, and it made sense in those contexts, but it didn't "click" for me with what I'm trying to do until reading this explanation. Sorry!

Our project started without enforcing `svelte-check`, and I need to somehow stop the "bleeding", or at least slow it down drastically. 

There is a [GitHub Action for this with TypeScript](https://github.com/Arhia/action-check-typescript) that has worked well for us, so I believe this can be achieved, even if the results aren't perfect. I believe we can use the same approach that they are to detect new errors/warnings:

> - Builds your PR, then run tsc to detect errors 
> - Compare ts errors in base branch and in PR branch to detect new errors
> - Doesn't upload anything or rely on centralized storage

If you're interested, I can provide an update once I get something working, or hit a dead-end. Otherwise, please feel free to close this Issue.

Thanks again so much for your patience and help!!

**Comment by andyasberry** [comment]
Wanted to provide an update here, in case anyone is interested:

![Screenshot 2023-07-05 at 11 37 10 AM](https://github.com/sveltejs/language-tools/assets/4965259/99a454cd-800b-4cab-ada4-ce0bfff4b3db)

While not perfect at this time, this has been working well for our team to prevent new errors/warnings.

We are thinking of creating a GitHub Action that can be used by anyone in the community that feels it is useful.
