### ISSUE TITLE
Cannot find namespace 'svelteHTML' error toggled on and off by svelte-kit sync

### ISSUE THREAD

**Issue by connerdassen** [sveltejs/language-tools#2018]
### Describe the bug

When trying to use the svelteHTML namespace I noticed I occasionally got this error:
 `Cannot find namespace 'svelteHTML' .ts(2503)`

However, the project built normally and `svelte-check` didn't report any errors.
After investigating, I noticed that the error went away and was reintroduced with every run of `svelte-check`

### Reproduction

1. `npm create svelte@latest my-app`
    - Select `Skeleton project`, `Yes, using TypeScript syntax`,  no additional options
2. `cd my-app`
3. `pnpm install`
4. Create `src/test.ts` 
    - Write `type Test = svelteHTML.HTMLAttributes;`

At this point, you may or may not get the error  `Cannot find namespace 'svelteHTML'  .ts(2503)`.
Running `npx svelte-kit sync` toggles the error on / off every time I run it: 

https://github.com/sveltejs/language-tools/assets/33068114/f1612cd8-c8b1-4f5b-a019-a0a722ce5d75

### Expected behaviour

svelteHTML is defined

### System Info

- OS: Windows
- IDE: VSCode 
- Svelte for VSCode: v107.4.3

### Which package is the issue about?

Svelte for VS Code extension

**Comment by connerdassen** [comment]
`npm run dev` which runs `vite dev --port 3000 --open` also toggles the error just like `npx svelte-kit sync`...
`npm run build` toggles the error twice, first when `vite build` runs and then again when `npm run package` runs

**Comment by jasonlyu123** [comment]
We found a compatibility issue with the [IntelliCode](https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode) extension. Do you have this installed? I want to make sure that the problem we found is the same as yours. If not, can you check what other extension might have caused the problem?  You can clone a new settings profile from the existing one, so it's easier to revert after testing.

**Comment by cmjoseph07** [comment]
@jasonlyu123 
This seems to have resolved my issue. If I uninstall the extension and run vitest I am not running into this error anymore. Thank you so much for reaching out to me on this!!

**Comment by connerdassen** [comment]
@jasonlyu123 sorry for the late response, disabling IntelliCode did indeed fix it

**Comment by rutinerad** [comment]
For anyone else who has this issue, simply restarting VSCode can help.
