### ISSUE TITLE
`ReferenceError: fetch is not defined`, when fetch in config

### ISSUE THREAD

**Issue by iTechTomekK** [sveltejs/language-tools#2025]
### Describe the bug

Since node 18, fetch is available by default, and I am using it in my svelte.config.js. 
But because vscode extension think fetch is not defined, I have that annoying error on all my svelte file
![image](https://github.com/sveltejs/language-tools/assets/118443980/6b7732e2-4e21-49cb-89f7-c7a494f171a6)

```
Error in svelte.config.js

ReferenceError: fetch is not defined
```

### Reproduction

Simply add `fetch()` to your config 

### Expected behaviour

add fetch available in node 18

### System Info

- OS: Linux
- IDE: Vscode

### Which package is the issue about?

Svelte for VS Code extension

**Comment by jasonlyu123** [comment]
Svelte VSCode extension uses the node.js version bundled by VSCode by default. You can config it through the [svelte.language-server.runtime](https://github.com/sveltejs/language-tools/tree/master/packages/svelte-vscode#sveltelanguage-serverruntime) setting. Or you can just change it to `globalThis.fetch?.()` if the fetched result isn't important for the language server.
