### ISSUE TITLE
The extension doesn't recognize well some imported components in ts/js scripts.

### ISSUE THREAD

**Issue by PoolFlamingo** [sveltejs/language-tools#2049]
### Describe the bug

After the last vscode update, the extension seems to not recognize some imported Svelte components in ts/js scripts. Sometimes they are fixed, but when I create or modify a svelte file, these errors appear again and it doesn't recognize the generated svelte class. These components in principle are well built and do not present any problems.

### Reproduction

Steps to have the possibility of being able to reproduce this error:

1. Create an electron project with svelte and ts with `npm create @quick-start/electron`.
2. Follow the steps specified by the terminal.
3. Create a .svelte file and add html and js/ts code.
4. From the renderer.ts file, instantiate the svelte component in the body of the document.

### Expected behaviour

All these steps sometimes generate class identification errors, making work annoying.

### System Info

- OS: [e.g. Windows]
- IDE: [e.g. VSCode, Atom]

### Additional Information, eg. Screenshots

![image](https://github.com/sveltejs/language-tools/assets/57965866/fa364be8-4049-4d50-a97b-a047163bfed4)
![image](https://github.com/sveltejs/language-tools/assets/57965866/7d06e727-4758-4d3e-8ad7-f227a4ae089b)

**Comment by jasonlyu123** [comment]
I can't reproduce the error you're seeing. If I have the typescript plugin(`svelte.enable-ts-plugin`) enabled. It work as expected. If I disable it, there'll be an error with cannot find the module. It's completely different from the situation in your screenshot. 

Do you have the typescript plugin enabled? If not, Can you try enabling it and see if it fixes the problem? If you do have it enabled, I suspect another extension might cause the problem. Can you try to disable all other extensions to see if the problem persists?  You can use VSCode's settings profile feature to create an empty profile. That way, it would be easier to roll back once you test it.

**Comment by PoolFlamingo** [comment]
No, the typescript extension is enabled and works correctly. In fact, when I disable vscode's svelte extension, this error goes away and it recognizes the class, but with some limitations. However, currently, the errors have disappeared (even with the extension activated), but they can appear again as it happened to me yesterday.

**Comment by jasonlyu123** [comment]
When I typescript plugin I didn't mean the typescript extension. But a plugin for the typescript extension. The config to enable it is `svelte.enable-ts-plugin`. Another extension can also provide a plugin for the typescript extension. And the problem might be a conflict between the typescript plugins.
