### ISSUE TITLE
`$$Generic`/`generics` discriminated union arrays not resolved correctly

### ISSUE THREAD

**Issue by Not-Jayden** [sveltejs/language-tools#2059]
### Describe the bug

When assigning an array of discriminated unions to a component using a prop typed to a generic, the generic only resolves as the first type in the discriminated union, rather than the entire union. This seems to be the case for both `$$Generic<>` and the `generics` attribute.

### Reproduction

Items.svelte
```svelte
<script lang="ts">
  type Item = $$Generic;

  export let items: Array<Item>;
</script>
```

App.svelte
```svelte
<script lang="ts">
  import Items from "./Items.svelte";

  type Fizz = {
    type: "fizz";
    value: string;
  };

  type Buzz = {
    type: "buzz";
    value: number;
  };

  type FizzBuzz = Fizz[] | Buzz[];
  const items: FizzBuzz = [];
</script>

<main>
  <Items {items} />
</main>
```

trying to assign `items` as a prop to the `<Items />` component gives the following type error:
```
Type 'FizzBuzz' is not assignable to type 'Fizz[]'.
  Type 'Buzz[]' is not assignable to type 'Fizz[]'.
    Type 'Buzz' is not assignable to type 'Fizz'.
      Types of property 'type' are incompatible.
        Type '"buzz"' is not assignable to type '"fizz"'.ts(2322)
```

### Expected behaviour

The `items` prop type should resolve to `Fizz[] | Buzz[]` to match the type of the items array assigned to it, rather than just `Fizz[]`.

### System Info

- OS: Mac
- IDE: VSCode

### Which package is the issue about?

svelte-check

**Comment by jasonlyu123** [comment]
This is the same behaviour in TypeScript files. I don't know why that is. Guess the constructor got expanded to 2 signatures because `Fizz[]` and `Buzz[]` is incompatible. Given this is the same behaviour in TypeScript files. I am going to close this. You can go search in the TypeScript repo to see if there is already an issue with this and see if there is another explanation. 

```ts
class Items<T> {
    constructor(options: { props: { items: T[] } }) {}
}

  type Fizz = {
    type: "fizz";
    value: string;
  };

  type Buzz = {
    type: "buzz";
    value: number;
  };

  type FizzBuzz = Fizz[] | Buzz[];
  const items: FizzBuzz = [];

new Items({ props: { items } })
// 
```

https://www.typescriptlang.org/play?#code/MYGwhgzhAECSAuBTAthAPAFQHzQN4ChojpgB7AOwngCcBXYeU6gClIAd4BLCiALj2htq7PgM5JU-DAG0AutAC+igJR4F+dYWjwAnm0TQAYpwBeJ6AF48Worv38ARADNTJhwG4b0AG5gQtRH4qak5yAHNPIgVPLTsDACFaM0trYm09QOgHACMkt0jiX39M8lpkbMRqAuj8WIyjV0Tkq2MzOWgAH2gmkzkCskp4aHEUUVaTHpS+2vJEAHc4CQhmXEFhNlFVkdRFFXwgA

**Comment by jasonlyu123** [comment]
Actually, It works if you change it to 

```svelte
<script lang="ts">
    type Items = $$Generic<any[]>;
  
    export let items: Items;
</script>
```

**Comment by Not-Jayden** [comment]
Ah my bad. Idid have an attempt at reproducing in pure TS but clearly didn't do it right. Thanks a lot for making the reproduction! 

I had played around with making `items` a `$$Generic<unknown[]>`, which does work for fixing the items prop type, but then ran into a second issue with trying to use slot prop types with the let:

e.g.
Items.svelte
```
<script lang="ts">
  type Items = $$Generic<unknown[]>;

  export let items: Items;
</script>

{#each items as item}
  <slot {item} />
{/each}
```
App.svelte
```
<script lang="ts">
  import Items from "./Items.svelte";

  type Fizz = {
    type: "fizz";
    value: string;
  };

  type Buzz = {
    type: "buzz";
    value: number;
  };

  type FizzBuzz = Fizz[] | Buzz[];
  const items: FizzBuzz = [];
</script>

<main>
  <Items {items} let:item />
</main>
```

`item` in `<Items {items} let:item />` is typed as `unknown` rather than being inferred from `FizzBuzz`. I can use a user defined type guard but it's definitely not ideal.

**Comment by Not-Jayden** [comment]
Actually I figured out a gross workaround.

```sveltec
<script lang="ts">
  type Items = $$Generic<unknown[]>;
  type Item = (typeof items)[number];

  export let items: Items;

  let itemsDuplicate: Item[];
  $: itemsDuplicate = items;
</script>

{#each itemsDuplicate as item}
  <slot {item} />
{/each}
```
