### ISSUE TITLE
Wrong colors in .svelte file after HTML comment

### ISSUE THREAD

**Issue by hull90** [sveltejs/language-tools#2061]
### Describe the bug

If I add a HTML comment line in the markup section of a .svelte file then all the lines after the comment are colored like comments (green in my case).
![image](https://github.com/sveltejs/language-tools/assets/30906507/4582f234-4db5-45fd-9982-180d7e60573c)

If I remove the final space from the comment, then everything is correct.
![image](https://github.com/sveltejs/language-tools/assets/30906507/3625b69c-a40a-404e-aeb5-48284b97eb10)

### Reproduction

Add a HTML comment in the markup section of a .svelte file 
`<!-- comment here -->` 

### Expected behaviour

All the subsequent lines are correctly colored

### System Info

- OS: Windows 11
- IDE: VSCode 1.79.2
- Svelte for VS Code  v107.5.1 

### Which package is the issue about?

Svelte for VS Code extension

**Comment by jasonlyu123** [comment]
I don't know if this is your font being weird or something. Why is the HTML comment start an arrow instead of `<`? Can you provide the full code of the document? The problem might have something to do with the code outside of your screenshot.

**Comment by hull90** [comment]
Thanks for help,
the "arrow instead of `<` " is just the font ligatures (I use 'JetBrains Mono' font) 

![image](https://github.com/sveltejs/language-tools/assets/30906507/1fc88d49-60bd-4b6a-a61a-77cb18e1a25b)


I disabled ligatures in the vscode settings, but the issue seems to persist. 
Here is a full +page.svelte content 

with the final space in the HTML comment
![image](https://github.com/sveltejs/language-tools/assets/30906507/b2da9454-d7ba-4b00-9296-f57da073a989)


without the final space 
![image](https://github.com/sveltejs/language-tools/assets/30906507/cd8e53c2-7aa3-44c4-8460-aaebf4d98341)

**Comment by jasonlyu123** [comment]
I still can't reproduce it. Another extension might cause it. Can you disable all other extensions with the setting profile and see if the problem persists?

**Comment by hull90** [comment]
You are right, it is some other extension, even if I couldn't figure out which one. I disabled all other extensions, then enabled only Svelte extension and the syntax highlighting was correct. Then I started enabling the other extensions one by one, but wasn't able to reproduce the problem again, maybe it depends on the order in which extensions are enabled. 
Anyways, problem fixed, thanks
