### ISSUE TITLE
Question: how to use SvelteComponentTyped for 3rd party libraries that do not provide typings

### ISSUE THREAD

**Issue by rallets** [sveltejs/language-tools#2063]
Hi, I'm trying to use an external Svelte component [simple-svelte-autocomplete](https://github.com/pstanoev/simple-svelte-autocomplete) that does not expose typings (and don't want to).

It would be nice to be able to use it in a strongly-typed way and get also VS Code intellisense, but I'm struggling to understand the usage of `SvelteComponentTyped ` and I'm not able to find complete examples.

What I did:
1- used the external component in `App/component.svelte`

2- import the component via `import AutoComplete from 'simple-svelte-autocomplete';` 

3A- provide a typing `simple-svelte-autocomplete.d.ts`
```
declare module 'simple-svelte-autocomplete' {
    import { SvelteComponentTyped } from 'svelte';

    export interface AutoCompleteProps
        extends svelte.JSX.HTMLAttributes<HTMLElementTagNameMap['div']> {
        items: Item[];
        // ...
    }

    export interface AutoCompleteEvents {
        onChange: (value: Item) => void
    }

    export class AutoComplete extends SvelteComponentTyped<AutoCompleteProps, AutoCompleteEvents> { }
}
```
3B- I tried also another way, inspired by [this](https://github.com/carbon-design-system/sveld) (`simple-svelte-autocomplete.d.ts`)
```
import type { SvelteComponentTyped } from 'svelte';

export interface AutoCompleteProps extends svelte.JSX.HTMLAttributes<HTMLElementTagNameMap['div']> {
         items: Item[];
}

export class AutoComplete extends SvelteComponentTyped<
        AutoCompleteProps,
        { onChange: (value: Item) => void},
        { default: {} }
    > { }
```

but I cannot get the import and the component definition without errors in VS Code. 
The build can however generate valid typescript/javascript, so it's more an issue from a DX prospective.

Any tips?

I have a github repo [here](https://github.com/rallets/svelte-component-typed-repro).

_NB. The repro setup is a bit weird because it has been extracted from a bigger project that is used to migrate an AngularJs application to Svelte._

**Comment by dummdidumm** [comment]
3A is almost right, you need to do `export default class ..` because you import it as a default import, not as a named import.

**Comment by rallets** [comment]
thank you @dummdidumm for the tip.
It still doesn't work as expected, as the import
```
import AutoComplete from 'simple-svelte-autocomplete';
``` 
raises an error (in VS Code)

```
Could not find a declaration file for module 'simple-svelte-autocomplete'. '/src/node_modules/simple-svelte-autocomplete/dist/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/simple-svelte-autocomplete` if it exists or add a new declaration (.d.ts) file containing `declare module 'simple-svelte-autocomplete';`ts(7016)
```

It takes a while to start to show the errors, not sure why... it looks like I need to edit the file to wake up the compiler 🤔

Then I would also be able to add generic support to the type definition, so for example items could be of type `items:T[]` and onChange could be `(value: T) => void`. Is it possible? But maybe this is another question...

**Comment by rallets** [comment]
@dummdidumm aha, thanks, now it works fine. I can get intellisense support, and errors if a type is not correct in some attributes declared with string, boolean, etc.
I need to use `any` as type for the attribute `items`.... do you know any way to specify a type and use it between parameters?

**Comment by dummdidumm** [comment]
import `Item` within the `declare module` scope you already imported `SvelteCompentTyped` and use it

**Comment by rallets** [comment]
@dummdidumm sorry I explain myself poorly, and switched contexts. 
What I would like to achieve is a "generic" typing, based on the consumer object type. But I'm not sure it could be possible.

In this example, I would like to do something like
```
type Item {
  id: number,
  description: string,
};
let items: Item[] = [];

function handleOnChange(item: Item) {
  // ...
}

<AutoComplete items="{items}" onChange="{(item) => handleOnChange(item)}" />
```
where `item` is of the same type of `items`. AutoComplete itself doesn't know about the typings.

A kind of (pseudo code)
```
 <AutoComplete<Item> items="{items}" onChange="{(item) => handleOnChange(item)}" />
```

In the way you suggested (and I did in my first attempt to show my initial problem) I have to use a type *inside* AutoComplete (`simple-svelte-autocomplete.d.ts`).
Currently I need to augment AutoComplete with `any` in the typings, but then it became a bit cumbersome to write the event handler, as Svelte doesn't allow me to force the type to what I want, as example I cannot write
```
<AutoComplete items="{items}" onChange="{(item: Item) => handleOnChange(item)}" />
```
because the extension says it's invalid code (it complains about the extra `: Item`)

**Comment by dummdidumm** [comment]
You have to use a generic and pass that to your props. Like

```ts
export interface AutoCompleteProps<Item> {
  item: Item[];
  onChange: (item: Item) => void;
  // ...
}

export class AutoComplete<Item> extends SvelteComponentTyped<AutoCompleteProps<Item>> {}
```

**Comment by rallets** [comment]
@dummdidumm thanks, it's not exactly was I looking for, but it's better than nothing. Thanks for your support.
