### ISSUE TITLE
Slow update-import with declarationMap 

### ISSUE THREAD

**Issue by jasonlyu123** [sveltejs/language-tools#2065]
### Describe the bug

Update import takes a very long time if a library has declaration maps. For example, svelte 4

### Reproduction

Our update import test running with Svelte 4

### Expected behaviour

It should be fast enough. 

### System Info

- OS: [e.g. Windows]
- IDE: [e.g. VSCode, Atom]

**Comment by FedericoBiccheddu** [comment]
FYI, this happens even with Svelte 3.
