### ISSUE TITLE
What can I do to speed up TypeScript linting in Svelte files?

### ISSUE THREAD

**Issue by thdoan** [sveltejs/language-tools#2076]
Hi, new developer here (coming from Vue). For the most part I have enjoyed the transition to Svelte, and the learning curve was not as daunting as I feared. However, there is one major pain point that I hope someone can help me mitigate: the TypeScript linting speed. Seriously, it's gotten so bad that I no longer enjoy coding Svelte projects in VS Code :-(.

I would type a little and have to wait up to several _minutes_ for the linting process to finish while the red squigglies jump around (very distracting btw), and my .svelte files are not massive by any means. Here's an example I just recorded of me typing a console.log statement in a script about 800 lines long:

![Code_OBYpXYbo9N](https://github.com/sveltejs/language-tools/assets/4110567/c268b6ec-7320-4813-ba86-50ccefe17253)

There should only be the three sidePanel errors and nothing else. Why is it so sluggish in processing this document? Is the culprit Svelte for VS Code, or maybe some other extension? Is there anything I can do to speed it up? As you can see in the gif above, it's too slow and painful for any real development right now unless I remove TypeScript from my project.

### My setup

Version: 1.79.2 (user setup)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:57:04.379Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (11.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
svelte-intellisense|ard|0.7.1
vscode-tailwindcss|bra|0.9.11
file-properties-viewer|bru|1.0.0
path-intellisense|chr|2.8.4
hex-to-rgba|dak|1.0.0
vscode-eslint|dba|2.4.2
gitlens|eam|14.0.1
vscode-ts-whitespace-converter|joh|1.2.1
l13-diff|L13|1.3.2
vscode-json-validate|rio|1.4.3
svelte-vscode|sve|107.6.0
sort-lines|Tyr|1.10.1
remove-empty-lines|use|1.0.1
</details>

**Comment by dummdidumm** [comment]
Is it possible to share the repository in full by any chance (also privately if you want) so we can look into it?

What happens if you disable all extensions but `svelte-vscode`? Is it faster then?

**Comment by thdoan** [comment]
I was forced to do a reboot to install some Windows updates, and after that the speed is OK again. I'm not sure how it got to be so laggy but maybe over time it can get like that. In any case, I'm going to close this.
