### ISSUE TITLE
The classes in `<style global>` should either be checked if unused in the entire code base or not at all (by svelte-check)

### ISSUE THREAD

**Issue by 205g0** [sveltejs/language-tools#2080]
### Describe the bug

I've read some other issues but not sure it's exactly the use caase I'm looking at, example:
```svelte
// +layout.svelte
...
<style global>
  html {
    font-size: 100%;
  }
  .my-link {
    color: blue;
  }
</style>
```

svelte-check throws  many _Hint: Unused CSS selector ..._  which also spams the build logs but hey I use them

### Reproduction

Just copy and past the snippet above.

### Expected behaviour

Just throw nothing, one shouldn't put gazillions of classes into `<style global>` but for a few classes it's godsent.

### System Info

svelte-check@3.4.4

### Which package is the issue about?

svelte-check

### Additional Information, eg. Screenshots

Not sure how the linitng in VS Code is related, so if VSC pulls them from svelte-check. However, I can live with them being in VSC but as said, not really the ones by svelte-check

**Comment by dummdidumm** [comment]
What's your project setup? Where is the preprocessor defined that handles `<style global>`?

**Comment by 205g0** [comment]
Thanks, I have `vitePreprocess`, the default of create svelte@latest (as skeleton app and with TS).

**Comment by 205g0** [comment]
Sorry, it's not the default, just realized that I've added it because of Tailwind

**Comment by 205g0** [comment]
Sorry again, no _it's_ the default which was preinstalled by create svelte@latest.

**Comment by dummdidumm** [comment]
`vitePreprocess` is not capable of dealing with `<style global>`, you need to use [svelte-preprocess](https://github.com/sveltejs/svelte-preprocess#global-style) instead for this - so the warning is correct.

**Comment by 205g0** [comment]
ok, thanks
