### ISSUE TITLE
typescript intelisense not working when install Svelte for VS Code

### ISSUE THREAD

**Issue by mieaw** [sveltejs/language-tools#2086]
### Describe the bug

typescript intelisense not working when install Svelte for VS Code

### Reproduction

just install the extension and typescript intelisense not working when install Svelte for VS Code

### Expected behaviour

when hover on this variable for example 'nUser ' show me the type:

 const nUser = await db.insert(usersTable).values({
      first_name: first_name.toString(),
      last_name: last_name.toString(),
      email: email.toString(),
      password: hash,
    });

### System Info

- OS: Windows
- IDE: VSCode

### Which package is the issue about?

Svelte for VS Code extension

**Comment by uptimizer-prolife** [comment]
with extension Svelte for VS Code v107.7.0:


![image](https://github.com/sveltejs/language-tools/assets/133277280/65b86c2a-a880-4119-8617-f10910d072ba)

**Comment by uptimizer-prolife** [comment]
Without the extension:


![image](https://github.com/sveltejs/language-tools/assets/133277280/213669a1-8a9f-4e94-9e20-6ecd0b1e7d9d)

**Comment by jasonlyu123** [comment]
Please provide a reproduction in text format or a repository. Also, are you using the typescript nightly extension?

**Comment by ala-garbaa-pro** [comment]
I think in order to make TypeScript work with Svelte for the VS Code extension, you need to uninstall the 'JavaScript and TypeScript Nightly' extension (https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next).

**Comment by uptimizer-prolife** [comment]
yes I deleted the Nightly extension and now everything going ok
