### ISSUE TITLE
code whisperer not working with svelte project

### ISSUE THREAD

**Issue by mieaw** [sveltejs/language-tools#2088]
### Describe the bug

code whisperer not working with svelte project

### Reproduction

just use code whisperer with svelte project

### Expected behaviour

some auto suggest or code completion maybe will be cool 

### System Info

- OS: Windows
- IDE: VSCode

**Comment by mieaw** [comment]
Any alternative tested very well?

**Comment by jasonlyu123** [comment]
It's mentioned in their docs that they only support "Python, Java, JavaScript, TypeScript, C#, Go, Rust, PHP, Ruby, Kotlin, C, C++, Shell scripting, SQL and Scala". There is nothing we can do about it. If you want Svelte to be supported, you'll need to ask Amazon.
