### ISSUE TITLE
VS Code shows Typescript error for key in #each block, which is assumed to be a string 

### ISSUE THREAD

**Issue by RossAddinall** [sveltejs/language-tools#2093]
### Describe the bug

In the following code, I am defining a type called ```Things``` which has optional keys and declaring an instance (is that the right word) of ```Things``` called ```things```.  In the markup, I iterate over the keys in ```things``` and call a function which takes the key as an argument.  The function is defined as requiring a ```keyof Things```.  The ```#each``` block iterates over the keys of ```things``` and yet I get an error on the line:
```
<button on:click={ () => runCommand(thing) }>{thing}</button>
```
of the form:
```
Argument of type 'string' is not assignable to parameter of type 'keyof Things'.ts(2345)
```
Clearly, the only type that ```thing``` can be is a key of Things, yet VS Code is assuming it to be a string.  What did I do wrong?  Can this be made easier to use?

```typescript
<script lang='ts'>
  // Imports
  type Things = {
    'First'?: string,
    'Second'?: string
  }
  
  // Declarations
  let things: Things = {};

  // Functions
  const runCommand = ( (thing: keyof Things) => {
      console.log('thing:', thing);
    }
  )

  // Dependencies
</script>

<style></style>

{#each Object.keys(things) as thing}
  <button on:click={ () => runCommand(thing) }>{thing}</button>
{/each}
```

### Reproduction

Minimal example: 
```typescript
<script lang='ts'>
  // Imports
  type Things = {
    'First'?: string,
    'Second'?: string
  }
  
  // Declarations
  let things: Things = {};

  // Functions
  const runCommand = ( (thing: keyof Things) => {
      console.log('thing:', thing);
    }
  )

  // Dependencies
</script>

<style></style>

{#each Object.keys(things) as thing}
  <button on:click={ () => runCommand(thing) }>{thing}</button>
{/each}
```

### Expected behaviour

I didn't expect a problem with this, what can I do to correct?

### System Info

- OS: Windows 10 (Version 22H2 (OS Build 19045.3086)
- IDE: VS Code Version 1.80.0

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

![image](https://github.com/sveltejs/language-tools/assets/8624070/ac7bad94-343d-4401-9c59-365681dbb7c2)

**Comment by jasonlyu123** [comment]
This is the correct behaviour and in line with what TypeScript does. `Object.keys` always return `string[]`. I think the reason for this is that you can assign `{
    First: '',
    Second: '',
    Third: ''
}` to `Thing`. In that case it will make `Object.keys` return something that isn't `keyof Things`

https://www.typescriptlang.org/play?#code/FAFwngDgpgBAKgCwJYDsDmBnGBeGBvYGImAcgDEkAnDEEgfgC4YbLU0AaQ4kgZSgGMA9igAm9JizbAAvsGAAbKCBgBDJojZZcBYjArUQTEiU66+Q0UZIy5FmjADWUMFpgB5AEYArASAB0Ti4AFCoAlFwwAPSRMAB6dEA

If you're sure it only contains `keyof Things` you can safely type assert it in the script tag.

```svelte
<script lang="ts">
$: keys = Object.keys(things) as keyof Things
</script>
```

**Comment by RossAddinall** [comment]
@jasonlyu123 Thanks for the quick reply.

I could indeed do:
```
let things: Things = { First: '', Second: '', Third: '' };
```
but then this error is generated:
```
Type '{ First: string; Second: string; Third: string; }' is not assignable to type 'Things'.
  Object literal may only specify known properties, and 'Third' does not exist in type 'Things'.ts(2322)
```

It looks like the type assertion in the script tag is the way to go to get a clean file.
Thanks.
