### ISSUE TITLE
Extending the `SvelteHTMLElements` interface with custom web components

### ISSUE THREAD

**Issue by Rajaniraiyn** [sveltejs/language-tools#2096]
### Describe the bug

I am having couple of custom webcomponets (`cds-design`) along with their type declarations. I tried to use the IDE intellisence features by extending the base `SvelteHTMLElements` interface as below

```ts
import type { HTMLAttributes } from "svelte/elements"
import type Alert from 'cds-design/types/src/components/alert';
import type Avatar from 'cds-design/types/src/components/avatar';
import type Badge from 'cds-design/types/src/components/badge';
import type Button from 'cds-design/types/src/components/button';
import type Check from 'cds-design/types/src/components/check';
import type Input from 'cds-design/types/src/components/input';
import type Progress from 'cds-design/types/src/components/progress';
import type Slider from 'cds-design/types/src/components/slider';
import type Toggle from 'cds-design/types/src/components/toggle';

declare global {
	declare interface SvelteHTMLElements {
		"cds-alert": HTMLAttributes<Alert>
		"cds-avatar": HTMLAttributes<Avatar>
		"cds-badge": HTMLAttributes<Badge>
		"cds-button": HTMLAttributes<Button>
		"cds-check": HTMLAttributes<Check>
		"cds-input": HTMLAttributes<Input>
		"cds-progress": HTMLAttributes<Progress>
		"cds-slider": HTMLAttributes<Slider>
		"cds-toggle": HTMLAttributes<Toggle>
	}
}
```
If I use any of these above web components I would get proper types checking and IDE auto completions in my svelte files but it is not behaving on that way.
While checking the type definitions for native elements in svelte components those typings are from `svelte.svelte-vscode` extension which is using `svelte/elements` internally but not taking the local type declarations.

Is there any way to achieve the desired IDE Intellisence, Auto Completions and Typechecking for the custom elements within svelte components?

**Note:** This is possible to all JSX based frameworks/libraries

### Reproduction

```ts
import type { HTMLAttributes } from "svelte/elements"
import type Alert from 'cds-design/types/src/components/alert';
import type Avatar from 'cds-design/types/src/components/avatar';
import type Badge from 'cds-design/types/src/components/badge';
import type Button from 'cds-design/types/src/components/button';
import type Check from 'cds-design/types/src/components/check';
import type Input from 'cds-design/types/src/components/input';
import type Progress from 'cds-design/types/src/components/progress';
import type Slider from 'cds-design/types/src/components/slider';
import type Toggle from 'cds-design/types/src/components/toggle';

declare global {
	declare interface SvelteHTMLElements {
		"cds-alert": HTMLAttributes<Alert>
		"cds-avatar": HTMLAttributes<Avatar>
		"cds-badge": HTMLAttributes<Badge>
		"cds-button": HTMLAttributes<Button>
		"cds-check": HTMLAttributes<Check>
		"cds-input": HTMLAttributes<Input>
		"cds-progress": HTMLAttributes<Progress>
		"cds-slider": HTMLAttributes<Slider>
		"cds-toggle": HTMLAttributes<Toggle>
	}
}
```

```svelte
<cds-avatar src="https://example.com/my_super_profile_pic.png" />
```

### Expected behaviour

There must be a way to extend `SvelteHTMLElements` to include custom elements within the source code to avail IDE Intellisence features like auto completions and type checking

### System Info

- OS: MacOS
- IDE: VSCode

### Which package is the issue about?

Svelte for VS Code extension, svelte-language-server, svelte2tsx, svelte-check

### Additional Information, eg. Screenshots

https://github.com/sveltejs/language-tools/assets/72294760/6506a380-9e30-41b1-9b67-1876b3567a33

**Comment by jasonlyu123** [comment]
Enhancing `svelte/elements` is now possible. And if you want to enhance it through a global interface, It's under the `svelteHTML` namespace. 

https://svelte.dev/docs/typescript#enhancing-built-in-dom-types
