### ISSUE TITLE
Only with scss: The file cannot because script or style require a preprocessor ...

### ISSUE THREAD

**Issue by rondonjon** [sveltejs/language-tools#210]
**Describe the bug**

Not sure if this is a problem in `svelte-preprocess` or in the VS Code plugin, sorry in advance if I posted this in the wrong repo.

I have several .svelte files with Typescript in them which raise no errors, neither in VS Code nor during the CLI build.

Only if I also have a scss style section in them, I get an error.

![image](https://user-images.githubusercontent.com/8258823/83139278-65de1280-a0ec-11ea-8f89-963a76fe7030.png)

Funny observation: the error message vanishes in VS Code when I change the type to `css`, but that is obviously no solution for the build.

**Additional context**

sass is installed via `package.json`:

```
"node-sass": "^4.13.1",
```

The `.svelte` file:

```
<script lang="typescript">
  import { Color } from "../../Color";
  ...
</script>

<style lang="scss">
  .color-swatch {
  ...
</style>

...
```

My `svelte.config.js`:

```
const sveltePreprocess = require("svelte-preprocess");

module.exports = {
  preprocess: sveltePreprocess()
};
```

**Comment by dummdidumm** [comment]
Did you follow the [instructions for SCSS](https://github.com/sveltejs/language-tools/blob/master/packages/svelte-vscode/docs/preprocessors/scss.md)? Especially the last point (setting node path) might be what you need to do.
