### ISSUE TITLE
Shows error which is not

### ISSUE THREAD

**Issue by EpsilonKu** [sveltejs/language-tools#2114]
### Describe the bug

I have variables inside `/assets/js/scripts.bundle.js`. And I imported them inside `app.html` like this:
```html
    <script src="/assets/plugins/global/plugins.bundle.js"></script>
    <script src="/assets/js/scripts.bundle.js"></script>
```
but when I use it inside any `*.svelte` is shows that variable does not exist. 
Of course it works without when I run project.

### Reproduction

I have variable `KTMenu` inside of js. But it shows that there is no variable like that. 

### Expected behaviour

no  error

### System Info

- OS: Arch Linux (latest today patch)
- IDE: neovim, vscode (tried both same error)

### Which package is the issue about?

svelte-language-server

### Additional Information, eg. Screenshots

![image](https://github.com/sveltejs/language-tools/assets/63652620/9aa2c34d-e0a7-404c-83ba-4ee4939a020d)

**Comment by dummdidumm** [comment]
This isn't related to Svelte specifically. You need to tell TypeScript that these types exist by providing ambient type definitions. In short: Create a `d.ts` file, make sure it's picked up by you `tsconfig.json`, and add ambient declaration ins there, like
```ts
declare interface X { .. }
declare function y(): void;
declare namespace KTMenu {
  function createInstances(...);
}
```
