### ISSUE TITLE
Module not found error when using TypeScript import with aliases like $app or $lib in Emacs (svelte-ls)

### ISSUE THREAD

**Issue by remogatto** [sveltejs/language-tools#2123]
### Describe the bug

I'm getting a "cannot find module" error when importing TypeScript modules using aliases like $app or $lib in Emacs with svelte-ls.

### Reproduction

```bash
npm create svelte@latest myapp # Select "SvelteKit demo app", "Yes, using TypeScript syntax" and no additional options
cd myapp
npm install
npm run dev # close the server with Ctrl-C
emacs src/routes/sverdle/+page.svelte
```
Then I'm getting the following errors from Emacs:

* on line 3: "Cannot find module '$app/forms' or its corresponding type declarations."
* on line 4: "Cannot find module './$types' or its corresponding type declarations."

### Expected behaviour

Emacs should not return errors.

### System Info

- OS: ArchLinux
- IDE: Emacs 29.1
- svelte-language-server 0.15.16

### Which package is the issue about?

svelte-language-server

## Relevant parts of my init.el

(package-initialize)

(require 'package)
(add-to-list 'package-archives
  '("melpa" . "https://melpa.org/packages/") t)

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   '(yasnippet-snippets yasnippet lsp-tailwindcss web-mode typescript-mode notmuch all-the-icons flycheck lsp-ui csv-mode go-mode company lsp-mode markdown-mode material-theme)))

;;; LSP

(require 'lsp-mode)
(add-hook 'web-mode-hook #'lsp-deferred)
(add-hook 'typescript-mode-hook #'lsp-deferred)

;; web-mode

(add-to-list 'auto-mode-alist '("\\.svelte\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.html?\\'" . web-mode))

## Screenshots from Emacs

![Emacs](https://github.com/sveltejs/language-tools/assets/22067/d594d585-f7c1-46f2-bfa8-31981e89f6f1)

**Comment by jasonlyu123** [comment]
Can you open a directory instead of a single file in Emacs? If so, you need to open the directory where the `tsconfig.json` is.

**Comment by remogatto** [comment]
I'm not sure I fully understand what you mean by "opening a directory in Emacs", but I can update the issue with a further discovery that is likely related to the location of files within folders. Indeed, by creating a Foo.svelte file inside `src/` and importing a previously created `Bar.svelte` file in `src/lib/components` using the `$lib` alias, the language server *does not* return an error. On the contrary, if I try to import the same `Bar.svelte` file from `src/routes/Biz.svelte` the language server returns a "module not found" error. Here are the steps to reproduce the issue:

```bash
mkdir src/lib/components
```
The content of the `src/Foo.svelte` file is:

```svelte
<script lang="ts">
 import Bar from '$lib/components/Bar.svelte' // no import errors
</script>
<Bar></Bar>
```

The content of the `src/lib/components/Bar.svelte` file is:

```svelte
<p>Bar</p>
```

The content of the `src/routes/Biz.svelte` file is:

```svelte
<script lang="ts">
 import Bar from '$lib/components/Bar.svelte' // import error
</script>
<Bar></Bar>
```

As you suggested, the issue I encountered may depend on the location of the files in relation to `tsconfig.json`, which in this case is located in the folder one level above `src`. Is this the expected behavior? Am I missing something? Thanks in advance.

**Comment by jasonlyu123** [comment]
Language servers usually work with a directory instead of a single file. i.e. workspace root. So you should be opening a directory instead of a single file. Neovim, for example, can't open a directory. It can only open files. So neovim LSP has a logic to search for files like package.json to determine where the workspace root should be. If it works sometimes, maybe there is a similar logic. 

We currently won't load the tsconfig.json outside the workspace root. So you need to check if you can open a directory instead of a file. If you can't, then you need to check if your language server client has a similar logic to search specific files to determine the workspace root. I am not familiar with Emacs, so I can't check how Emacs LSP works. Tried before, but I just can't get it to work.

**Comment by remogatto** [comment]
AFAIK the language server is triggered in Emacs on a file extension basis and not on a directory basis.  I tried to put the following `tsconfig.json` file inside `myapp/src/` and the aliases are resolved correctly. 

```json
{
        "extends": "../.svelte-kit/tsconfig.json",
        "compilerOptions": {
                "allowJs": true,
                "checkJs": true,
                "esModuleInterop": true,
                "forceConsistentCasingInFileNames": true,
                "resolveJsonModule": true,
                "skipLibCheck": true,
                "sourceMap": true,
                "strict": true
        }
        // Path aliases are handled by https://kit.svelte.dev/docs/configuration#alias
        //
        // If you want to overwrite includes/excludes, make sure to copy over the relevant includes/excludes
        // from the referenced tsconfig.json - TypeScript does not merge them in
}
```
From what I understand, to make the language server work correctly with Emacs, it is necessary to create a `tsconfig.json` file that extends the configuration in `.svelte-kit/tsconfig.json` into any subfolders containing source code that uses aliases to resolve paths. However, I guess this is not the expected behavior. Where do you suggest I open an issue to report the problem? Thanks.

**Comment by jasonlyu123** [comment]
From my understanding of reading issues and code in lsp-mode, It seems like there'll be a prompt to choose root when opening the first time. Maybe your root has been set to the src directory? There is a command `M-x lsp-workspace-folders-add/remove` suggested in https://github.com/emacs-lsp/lsp-mode/issues/3357 to change root.

**Comment by remogatto** [comment]
Great! You pointed me in the right direction. After opening the svelte file with Emacs I executed:

```
M-x
lsp-workspace-remove-all-folders
```

followed by:

```
M-x
lsp-workspace-folders-add
```

adding as root folder the one that contains `tsconfig.json` file. Then, after restarting Emacs, the aliases are resolved correctly. I'm closing the issue, thank you!
