### ISSUE TITLE
Integrate with `svelte-preprocess-alien`

### ISSUE THREAD

**Issue by chientrm** [sveltejs/language-tools#2129]
### Description

[svelte-preprocess-alien](https://github.com/chientrm/svelte-preprocess-alien) allow you to replace the reactivity alien dollar sign with your favorite alien string.

Example:
```html
<script lang="ts">
  🐸🐸🐸: mine = $page.url.searchParams.get('mine');
</script>
```

### Proposed solution

Add new settings `svelte.alien` which is the desired alien string.

Example:

```json
// .vscode/settings.json
{
  "svelte.alien": "🐸🐸🐸"
}
```

**Comment by dummdidumm** [comment]
This sounds like a fun preprocessor, but we're not going to add support for it in language tools.
