### ISSUE TITLE
Question: How to use svelteHTML to override HTMLInputAttributes

### ISSUE THREAD

**Issue by rallets** [sveltejs/language-tools#2136]
Hi, as the attribute `readonly` has no meaning with some input types (ex. `checkbox`, and others) I would like to remove the ability to set them and hence get an error in VS Code if by mistake has been set.

for example:
```
<input type="checkbox" readonly="{true}" />
```
VS Code should mark `readonly` as invalid.

I tried with a custom `typings.d.ts`:
```
declare namespace svelteHTML {
  interface HTMLInputCheckboxAttributes {
    type: 'checkbox';
    'readonly': void;
  }

  interface HTMLInputAttributes extends HTMLAttributes<HTMLInputElement>, HTMLInputCheckboxAttributes { }
}
```
Should this be possible? Any tips?

Thanks

**Comment by ghostdevv** [comment]
I'm not sure how to narrow this correctly based on the checkbox type, but I do believe you need to use `svelte/elements`:

```ts
declare module 'svelte/elements' {
    interface HTMLInputAttributes {
        test: boolean;
    }
}

export {}
```

**Comment by rallets** [comment]
@dummdidumm tks for the explanation, I learn a lot every time from you.
