### ISSUE TITLE
Supports union types in props and reactive statement

### ISSUE THREAD

**Issue by jasonlyu123** [sveltejs/language-tools#214]
**Is your feature request related to a problem? Please describe.**
The following code will have a typescript error due to typescript's control flow analysis.
But this is very useful when it comes to a select-wrapper component.
```svelte
<script lang="typescript">
  export let value: string | number = '';

  if (typeof value === 'number') {
    console.log(value.toFixed())
  }

</script>

<select bind:value={value}></select>
```

**Describe the solution you'd like**
In the `svelte2tsx`, the `props` and reactive statement `$: {  }` needs to be taken out of the control flow context maybe by wrapping it with a callback like this:

```ts
declare function __sveltets_invalidate<T>(getValue: () => T): T

/*export*/ let value: string | number = __sveltets_invalidate(() => '')

let b: 'A' | 'B' = 'A';

() => {
$: {
    console.log(b)
}
}
```

**Additional context**
![圖片](https://user-images.githubusercontent.com/36730922/85215731-49fa2380-b3af-11ea-9bbf-39c028a3ddbb.png)

**Comment by dummdidumm** [comment]
Good idea with the invalidate-wrapper around props. Maybe we don't even need to add another wrapper to reactive statements then? Or are there any cases where this will throw control flow errors?

**Comment by jasonlyu123** [comment]
change the `export let` to `let` and wrap the statement in `$: {}` will have the same error

```svelte
<script lang="typescript">
  let value: string | number = '';

  $: {
    if (typeof value === 'number') {
      console.log(value.toFixed())
    }
  }
</script>
```

**Comment by dummdidumm** [comment]
Ah, did not think about that. Thanks!

**Comment by jasonlyu123** [comment]
The function callback for props won't work lol. Needs to find another way.

**Comment by jasonlyu123** [comment]
By the way, this wrapping can be used in $: variable if we change the first $: label to let like we discussed earlier in the overall strategy thread. Because its type is depending on another `let`. So it would works.

**Comment by jasonlyu123** [comment]
Another problem, this union type props will also have a type of number in the exported prop def because of the same reason

**Comment by jasonlyu123** [comment]
```ts
export let someProps : string | number = ''
```

To 
```ts
declare function __sveltets__invalidateWithDefault<T>(getValue: () => T | undefined): T;

let someProps: string | number = ''
someProps = __sveltets__invalidateWithDefault(() => someProps);

```

This works, but kind of hacky

**Comment by PatrickG** [comment]
```ts
export let test: string | number = '' as any;
```
works

**Comment by jasonlyu123** [comment]
@PatrickG's solution is better. but both approach would make the props has an undefined type. 
```ts
export let test: string | number | undefined = '' as any;
test // test is shouldn't be undefined here
```

**Comment by dummdidumm** [comment]
Can you get the types from the typescript AST somehow and use that to construct it? Or use some kind of AST traversal/Regex to get the type definition (everything after `:` and before `=`) and then put it behind it: `export let test: string | number = '' as string | number`.

**Comment by PatrickG** [comment]
> @PatrickG's solution is better. but both approach would make the props has an undefined type.
> 
> ```ts
> export let test: string | number | undefined = '' as any;
> test // test is shouldn't be undefined here
> ```

for me test is `string | number`. Not `undefined`.
![image](https://user-images.githubusercontent.com/196478/85939316-87613280-b914-11ea-8f19-c0a41601e06d.png)

**Comment by jasonlyu123** [comment]
[playground example](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAG2PGwDOMBccNQJYB2A5nAD5wECuAtgEbBRlyUEAmwAZocK3ALxwA5ILgBDNGIIBPANwAoVBjgB6ZXEXw8EtAAsIlBKwKD49Zm07deOhsCA)
It would only be `undefined` if `strictNullChecks` is enabled (`strict: true` also enable it)

**Comment by PatrickG** [comment]
> [playground example](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAG2PGwDOMBccNQJYB2A5nAD5wECuAtgEbBRlyUEAmwAZocK3ALxwA5ILgBDNGIIBPANwAoVBjgB6ZXEXw8EtAAsIlBKwKD49Zm07deOhsCA)
> It'll be `undefined` if `strictNullChecks` is enabled (`strict: true` also enable it)

Then it will be `string | number | undefined`. Where is the problem?

**Comment by jasonlyu123** [comment]
Because it can't be `undefined` when your default value is not `undefined`. I want to eliminate that so that users don't have to do an unnecessary null check to suppress the `undefined` error.

**Comment by PatrickG** [comment]
If you add `| undefined` to the type, of course it can be undefined and you should check that it is not undefined when you try to invoke a method.

```html
<!-- Component.svelte -->
<script lang="ts">
  export let test: string | undefined = '' as any; // `string | undefined` means it can be undefined.

  test.toUpperCase(); // not safe - because `test` can be `undefined`

  test?.toUpperCase(); // safe
</script>

<!-- Other component -->
<script>
  import Component from './Component.svelte';
</script>

<Componen test={undefined} />
```

**Comment by jasonlyu123** [comment]
because svelte compiler compile it to 
```js
let { test = '' } = $$props
```
so test can't be `undefined` even if you explicitly pass undefined as props. It can't be undefined until you re-assign it to `undefined`

Maybe it would be too complex or impossible to do what I intend to do. And It might be just an edge case that few people would use.

**Comment by PatrickG** [comment]
It still can be undefined if you pass a variable.
https://svelte.dev/repl/hello-world?version=3.23.2

**Comment by jasonlyu123** [comment]
Then it's reactive statement that's possibly `undefined`? Maybe we should just do reactive and require user to explicitly cast the type of default value.

**Comment by jasonlyu123** [comment]
```ts
export let a: string | number | undefined = '' as string | number
```
Casting can work. but in js it won't have undefined type in a function 

```js
    /**@type { string | number | undefined }*/
    let name = /**@type {string | number} */ ("world"),
        world = '';

    name

    function a() {
        name
    }
```
[js playground example](https://www.typescriptlang.org/play?strictNullChecks=true&useJavaScript=true#code/PTACBcGcFoGMAsCmsDWAoNAzArgO1uAJYD2uABAE6K4AmiFAFAJRkDeaZnZwAVDxAE8ADojZlI4CoVwBzMgB8yubAFsARvQVk8dTNMQ0yAXx7AOXADaJwSgIYrRAXm59BIthKmyty9fSNkpmQMAEQA7sQUFjQhTAA05lxcEVGGzgDk6QDcGEm49oi5XDj4RKRktsxsiUl2DjVGaEZAA)

**Comment by jasonlyu123** [comment]
> Instead of checking for undefined in the type here, I think we can use VariableDeclaration.initializer here
good point! It can differentiate optional props and possibly undefined

**Comment by PatrickG** [comment]
That is what i mean, with the optional props: https://github.com/PatrickG/language-tools/commit/c5f00f75df74c8e3dcfc9842dad4256b9d4f29f2

And with the `as any` after the initalizer, vscode no longer things `export let test: string | number = '';` is a string. https://github.com/PatrickG/language-tools/commit/7f630bbf7d66a037590384d3e2a7f8b7314b622c

**Comment by jasonlyu123** [comment]
I think the first one is ok! 
Another cons of `as any` is that It would not get type-check. So maybe it needs to be cast to whatever user has defined. 
```ts
let a: string | number = true as any;
```
Also, the casting needs to be done through `jsdoc` in js. I have tried that today.
About the undefined problem, I give up on it. Since we can't found a generic function that can do the trick. We could only manually check if its initializer is undefined but not if a variable passed in as the initializer is undefined. The false negatives seem to be more important.

**Comment by PatrickG** [comment]
> I think the first one is ok!
> Another cons of `as any` is that It would not get type-check. So maybe it needs to be cast to whatever user has defined.
> 
> ```ts
> let a: string | number = true as any;
> ```

Oh, right.
What about this:
```ts
declare function initializer<T>(value: T): any;
let test: string | number = initializer<string | number>('');
test; // string | number

let test: string | number = initializer<string | number>(true); // error because `true` is not `string` or `number`
```

let test: string | number = ((x: string | number): any => x)(true);

> Also, the casting needs to be done through `jsdoc` in js. I have tried that today.

I've not looked into the jsdoc stuff yet

**Comment by jasonlyu123** [comment]
update: there is another way to do `as any` 
```ts
export let a: number | string = '1',
  b = a;
```
to
```ts
declare function __sveltets_any(dummy: any): any;

let a: number | string = '1'
a = __sveltets_any(a);
let b = a;
```
No type-assertion needed and the initializer got type-check. So that this would show typing error:
```ts
export let a: ISomeInterface = {};
export let b: string | number = true;
```

**Comment by PatrickG** [comment]
I had the re-assignment in my mind too, but wanted to prevent it, because I think it is harder to do^^
Do you implement this?

**Comment by jasonlyu123** [comment]
Yes. I have implemented it reassign [here](https://github.com/jasonlyu123/language-tools/tree/union-type) but still need some works in cleanup and test.
[Another one](https://github.com/jasonlyu123/language-tools/tree/reactive-assignment) is focusing on $: variable

**Comment by dummdidumm** [comment]
@jasonlyu123 is everything the issue was about fixed by your PR? (asking for whether or not I can close this)

**Comment by jasonlyu123** [comment]
Yeah. Thanks
