### ISSUE TITLE
v4.2.0 regression with svelte.config.js onwarn

### ISSUE THREAD

**Issue by thdoan** [sveltejs/language-tools#2149]
### Describe the bug

I just upgraded from svelte 3.59.2 to 4.2.0 and noticed a regression issue (since it was the only change)...

This was working as expected in v3.59.2 (warnings suppressed):

```
import sveltePreprocess from 'svelte-preprocess';

export default {
  preprocess: sveltePreprocess(),
  onwarn: (warning, handler) => {
    if (warning.code.startsWith('a11y-')) {
      return;
    }
    handler(warning);
  },
};
```

After upgrading to v4.2.0, the code above no longer works and warnings are still shown in VS Code.

### Reproduction

1. Add code above to `svelte.config.js`
2. Update `package.json`: `"svelte": "^4.2.0",`
3. `npm install`
4. Reload VS Code

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 16.24 GB / 31.95 GB
  Binaries:
    Node: 16.20.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.6 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (116.0.1938.69)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    svelte: ^3.59.2 => 3.59.2
```

### Severity

annoyance

**Comment by jasonlyu123** [comment]
Yeah. It doesn't hide the warning for me in your repo using Svelte 3. The way to hide it in the Svelte VSCode is `svelte.plugin.svelte.compilerWarnings`. We never implemented `onwarn` support. So it probably is something else that hides it.

**Comment by thdoan** [comment]
Ah, I see. Well, thanks for checking anyway ^^.

**Comment by jasonlyu123** [comment]
To be clear. I don't think it's vite-plugin-svelte either. vite-plugin-svelte is for your dev server and build, which has nothing to do with your editor. Maybe another extension intercepts the warning and hides it? Maybe it's a new rule that only Svelte 4 has? Or maybe it's from eslint?

**Comment by thdoan** [comment]
Yeah, that's my point actually -- with so many plugins, it's hard to know where to go to get help or submit issues, from whom, etc.. However, I observed one thing though: I can reproduce it on my system using just the [svelte-vite-starter](https://github.com/thdoan/svelte-vite-starter) repo with only the Svelte VS Code extension installed. Looking in `package.json`, this suggests either VS Code or one or more of these packages are not playing well with Svelte 4.2.0:

```
  "devDependencies": {
    "@sveltejs/vite-plugin-svelte": "^2.4.5",
    "@tsconfig/svelte": "^5.0.2",
    "svelte": "^3.59.2",
    "svelte-preprocess": "^5.0.4",
    "typescript": "^5.2.2",
    "vite": "^4.4.9"
  }
```

I will explore getting rid of  `svelte.config.js` and using `svelte.plugin.svelte.compilerWarnings` since the only code I see in there is the `onwarn` code.

**Comment by barsv** [comment]
I faced a similar issue after upgrading from Svelte 4 to Svelte 5 and to vite 6.

Initially, I tried using onwarn in svelte.config.js, but it didn't work. 
I solved the problem by utilizing onwarn in vite.config.ts instead. 

Here's an example of how it looks in my setup:

```
export default defineConfig({
  plugins: [
    svelte({
      onwarn: (warning, handler) => {
        if (warning.code.startsWith('a11y-')) {
          return;
        }
        handler(warning);
      },
    }),
  ],
});
```
