### ISSUE TITLE
Errors in `app.d.ts` are not checked and/or detected

### ISSUE THREAD

**Issue by 205g0** [sveltejs/language-tools#2151]
### Describe the bug

Pretty much the title and it happens always after refactorings because app.dt.s isn't refactored

### Reproduction

Try a broken import, e.g. `import { nonsense ) from '$lib/lol'`.

FWIW, I have below `declare global { ... }` wrapping `declare namespace App`.

### Expected behaviour

squiggle line below the broken import

### System Info

- OS: WSL2 with Ubuntu 22.04
- IDE: VS Code

**Comment by jasonlyu123** [comment]
You probably have [skipLibCheck](https://www.typescriptlang.org/tsconfig#skipLibCheck) enabled. SvelteKit has it by default.  Enabling it might cause typescript to spend a lot more time checking `.d.ts` files inside your node_modules when running `tsc` or `svelte-check`.  And there isn't an option to disable lib check only for node_modules. You can enable it while you're making sure the file doesn't have an error and disable it when you're done.

**Comment by jasonlyu123** [comment]
Actually, You can rename it to app.ts and it'll be checked. You won't normally need to write stuff in `app.d.ts` that needs to be written with declaration file syntax anyway.

**Comment by 205g0** [comment]
Ok, sounds like a plan, however I couldn't rewrite `app.d.ts` to `app.ts` without gazillions of type error throughout my codebase or eslint driving nuts in app.ts

I checked a few sources how to migrate from declare to without and asked ChatGPT but it doesn't look trivial or I need more time...

**Comment by 205g0** [comment]
following works with tsserver as `app.ts` but not eslint ('ES2015 module syntax is preferred over namespaces.eslint') and I still need declare:

```ts
declare global {
  namespace App {
    interface Locals {
       ...
    }
    ...
  }

  namespace svelteHTML {
    interface HTMLAttributes {
      ....
    }
  }
}
```

**Comment by 205g0** [comment]
this works with eslint but not with tsserver which shows tons of errors:

**Comment by jasonlyu123** [comment]
You can disable the namespace rule for that file or per line since it has to be like this. Or add `app.ts` to `.eslintignore`

**Comment by dummdidumm** [comment]
`app.d.ts` types defines the contract that both the handle hook and its usage locations need to adhere to - that way made more sense to use compared to infering it from the hook. It's also next to impossible to infer the type because it's not returned from the handle hook.

Closing as the questions have been answered.
