### ISSUE TITLE
LSP false error `Cannot use 'x' as a store. 'x' needs to be an object with a subscribe method on it.`

### ISSUE THREAD

**Issue by Skylli202** [sveltejs/language-tools#2158]
Hi,

> I do not know if this is a bug or intended / expected behavior that why I opened this issue as `Something else`. Please feel free to update it, as required.

Before hand, here is a reproduction repo [link](https://github.com/Skylli202/repro-cannot-use-x-as-store). The code of this reproduction comes from the Svelte Kit documentation about [State management/Using stores with context](https://kit.svelte.dev/docs/state-management#using-stores-with-context).

When you use the SvelteKit context API to store a `writable`, the LSP will display the following error `Cannot use 'x' as a store. 'x' needs to be an object with a subscribe method on it.` when ever you try to access the store data with the `$` syntax (`$x`).

![image](https://github.com/sveltejs/language-tools/assets/38432216/09da63e1-8a38-4587-aab7-e9554439ebb8)

> I am using Neovim, but I had this issue on `vscode` as well.

**Comment by Skylli202** [comment]
I do not know if that's how it is supposed to work or if it his is a workaround, but I could get rid of the error by forcing the return type of `getContext`.

```ts
const user = getContext<Writable<{ name: string }>>('user')

// ...
$user.name // no lsp error
```

If we are supposed to type it, maybe should I create an issue on the Svelte Kit documentation repo ? What do you think ?

**Comment by jasonlyu123** [comment]
It's impossible for `getContext` to infer the typing. So, you need to type it explicitly.

**Comment by Skylli202** [comment]
> It's impossible for `getContext` to infer the typing. So yes, you need to type it explicitly.

It makes sens thanks for the confirmation. But I was not sure because the LSP is also very smart and detect return type of loading function, so I thought that it could find where the `setContext` is called and with what.
