### ISSUE TITLE
[Proposal] Files under packages/ seem not to have been prettier-ed with prettier.rc of project root.

### ISSUE THREAD

**Issue by ryuta69** [sveltejs/language-tools#216]
## proposal
Is it nice to prettier files under packages?

## why it should
When contributing, old un-prettier-ed files will be modified by prettier.rc.

It shows many changing after pull request, that makes harder to review.

**Comment by dummdidumm** [comment]
We did discuss adding a pre-commit-hook (#39 ) but decided against it. So I think formatting everything is also not something we will do. Sorry :/

**Comment by ryuta69** [comment]
Sorry I didn't check that issue. Thank you and I close this.

**Comment by dummdidumm** [comment]
No problem :-)
