### ISSUE TITLE
TS errors in Svelte HTML template

### ISSUE THREAD

**Issue by cycle4passion** [sveltejs/language-tools#2163]
### Describe the bug

I am receiving TS errors in the template.

<img width="970" alt="Screenshot 2023-09-21 at 4 42 50 AM" src="https://github.com/sveltejs/language-tools/assets/6192217/e436be99-7272-4f53-8c1b-074c84bfb764">

This persists even when turning off ErrorLens extension.

### Reproduction

see screenshot

### Expected behaviour

As there is no TS available in Svelte template, errors should not be showing here. I cannot correct them.

### System Info

- OS: macOS Ventura 13.4.1 (c)
- IDE: VSCode

### Which package is the issue about?

Svelte for VS Code extension

**Comment by jasonlyu123** [comment]
It might be the HTML typing is not loaded correctly. But we'll need a reproduction to know precisely what happened. If this only happens to one file, can you provide a reproduction with the file content? If it's all the files, You can try to reinstall the extensions. And if the problem persists, please provide a reproduction repository.

**Comment by cycle4passion** [comment]
- It happen on many files.
- It persists beyond
> Restart Language Server
> Restart TS server
> nuke pnpm.lock and node_modules, with pnpm i
> Restarting VSCode
> Uninstalling Svelte for VS Code Extension, reinstall.

I tried on a clean minimal repoduction, and the errors do not show.
Here's a [repo](https://github.com/cycle4passion/my-skeleton-app)

**Comment by jasonlyu123** [comment]
The library melt-ui/svelte has a wrong type definition that overrides the element type definition. Can you open an issue on their repo?

**Comment by cycle4passion** [comment]
Thank you, [issue#558](https://github.com/melt-ui/melt-ui/issues/558) submitted on MeltUI repo.

**Comment by jasonlyu123** [comment]
Closing as the upstream issue is already fixed.
