### ISSUE TITLE
Svelte for VSCode : Language service keep crashing

### ISSUE THREAD

**Issue by D3FCR3W** [sveltejs/language-tools#2166]
### Describe the bug

I know this bug has been reported many times but I have this problem and despite trying all the fix in the bug report section, I can't get it works.

The language service keep crashing and nothing works except the formatter from the Svelte for VSCode extension.
No intellisense, no import, nothing to help me programming with this wonderfull framework.

I already manually deleted  the extensions after desinstalling it and reinstalling it.
I already updated to the latest version of node.
I deleted the `"files.associations": {"*.svelte": "html"  }`.
I disabled all others svelte extensions that was helping me with import, intellisense since the official extension does not works as intented.
Also I updated the [svelte.language-server.ls-runtime] path in the settings.json to the same path than the [svelte.language-server.ls-path] because that's what I understood I had to do to fix the problem.

I opened my project from a blank vscode windows using files => Open folder

### Reproduction

I don't know how to reproduce since it's not working from the very beginning of the projet after using the CLI
If you want more context or anything else related, I will reply.

Here is the error : 
SyntaxError: Invalid or unexpected token
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.18.0
[Error - 4:18:33 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:18:33 PM] The Svelte server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 4:18:33 PM] Svelte client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:18:33 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 

Here is my package.json :
`{
  "name": "project1",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "dev": "vite dev",
    "build": "vite build",
    "preview": "vite preview",
    "test": "npm run test:integration && npm run test:unit",
    "check": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json",
    "check:watch": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json --watch",
    "lint": "prettier --plugin-search-dir . --check . && eslint .",
    "format": "prettier --plugin-search-dir . --write .",
    "test:integration": "playwright test",
    "test:unit": "vitest"
  },
  "devDependencies": {
    "@iconify/svelte": "^3.1.4",
    "@playwright/test": "^1.38.1",
    "@skeletonlabs/skeleton": "2.0.0",
    "@skeletonlabs/tw-plugin": "0.1.0",
    "@sveltejs/adapter-auto": "^2.1.0",
    "@sveltejs/kit": "^1.25.0",
    "@tailwindcss/forms": "0.5.5",
    "@tailwindcss/typography": "0.5.9",
    "@types/node": "20.5.7",
    "@typescript-eslint/eslint-plugin": "^5.62.0",
    "@typescript-eslint/parser": "^5.62.0",
    "autoprefixer": "10.4.15",
    "eslint": "^8.50.0",
    "eslint-config-prettier": "^8.10.0",
    "eslint-plugin-svelte": "^2.33.2",
    "postcss": "8.4.28",
    "postcss-import": "^15.1.0",
    "postcss-nesting": "^12.0.1",
    "prettier": "^2.8.8",
    "prettier-plugin-svelte": "^2.10.1",
    "svelte": "^4.2.1",
    "svelte-check": "^3.5.2",
    "tailwindcss": "3.3.3",
    "tslib": "^2.6.2",
    "typescript": "^5.2.2",
    "vite": "^4.4.9",
    "vite-plugin-tailwind-purgecss": "0.1.3",
    "vitest": "^0.32.4"
  },
  "type": "module",
  "dependencies": {
    "@floating-ui/dom": "1.5.1",
    "highlight.js": "11.8.0"
  }
}`

### Expected behaviour

Svelte for VSCode extension should not crashed on startup

### System Info

- OS: [Windows]
- IDE: [VSCode]

### Which package is the issue about?

Svelte for VS Code extension

**Comment by jasonlyu123** [comment]
What is the version of your VSCode, and do you have the [svelte.language-server.runtime](https://github.com/sveltejs/language-tools/tree/master/packages/svelte-vscode#sveltelanguage-serverruntime) config or the [svelte.language-server.ls-path](https://github.com/sveltejs/language-tools/tree/master/packages/svelte-vscode#sveltelanguage-serverls-path) config?

**Comment by D3FCR3W** [comment]
I have the latest VSCode version and I had the [svelte.language-server.ls-path](https://github.com/sveltejs/language-tools/tree/master/packages/svelte-vscode#sveltelanguage-serverls-path) before.

I saw a reply from you about this parameter on an other issue but I think I didn't understand this part enough.

**Comment by jasonlyu123** [comment]
The [svelte.language-server.ls-path](https://github.com/sveltejs/language-tools/tree/master/packages/svelte-vscode#sveltelanguage-serverls-path) is the path to the language server "js" file. It's usually for debugging purposes or for overriding language server dependencies. You'll rarely need it. 

VSCode extension usually uses the node.js version bundled with VSCode. And [svelte.language-server.runtime](https://github.com/sveltejs/language-tools/tree/master/packages/svelte-vscode#sveltelanguage-serverruntime) is for using a locally installed node.js version. for example, `C:/Program Files/nodejs/node.exe` or `path/to/bin/node`. It is usually for preprocessing libraries with binary executables like node-sass. But since node-sass is deprecated, It's also rare that you will need it. 

Since they are rarely useful nowadays. Unless you know why you need those two configs, I suggest removing them.

**Comment by D3FCR3W** [comment]
You know what, I think it's working now, I just removed thoses parameters and voila.
My code is now full of lint error, colors everywhere, thank you very much ^^ (first time I thanks someone for that)
Thank you very much for your patience and your explanation !
