### ISSUE TITLE
textDocument/completion response incorrectly sets isIncomplete to true

### ISSUE THREAD

**Issue by Sorixelle** [sveltejs/language-tools#217]
**Describe the bug**
The [LSP specification](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_completion) says the following about the `isIncomplete` property on `textDocument/completion` responses:
> This list is not complete. Further typing should result in recomputing this list.

svelte-language-server is setting this property to true on responses, however seems to be sending a complete list of completions every time. VSCode seems to filter returned completions anyway, but some other clients don't, in particular [lsp-mode](https://github.com/emacs-lsp/lsp-mode) for Emacs. Because of this, the completion list is not narrowed, and the same (often very large, I observed 970 possible completions in a new sveltejs/template project) list of completions is sent every time a character is typed.

**To Reproduce**

1. Start a new Svelte template project (`npx degit sveltejs/template test-project`)
2. Enable verbose logging for the language server (in VSCode, this can be done by setting `svelte.trace.server` to `"verbose"`)
3. Open `src/App.svelte` and start typing something to trigger completions (eg. `console` in the `<script>` block)
4. View the LSP log (in VSCode, this can be done by pressing Ctrl+Shift+U and selecting "Svelte" in the dropdown)
5. Observe how responses to `textDocument/completion` are returning the same list for the same term, with `isIncomplete` set to `true`

**Expected behavior**
Either:

1. `isIncomplete` should be set to `false`, and the full list of completions should be set, or
2. `isIncomplete` should remain `true`, but the list of completions should be filtered based on what the user has typed.

The first solution is likely the easiest to implement.

**System (please complete the following information):**
 - OS: Ubuntu 18.04 (under WSL 2)
 - IDE: All IDEs with LSP client implementations that don't filter when `isIncomplete` is `true`, initially noticed on Emacs 28 with lsp-mode
 - Plugin/Package: `svelte-language-server`

**Additional context**
If you want to test this in Emacs, the `lsp-svelte` branch of [my fork of lsp-mode](https://github.com/Sorixelle/lsp-mode/tree/lsp-svelte) has support for the Svelte language server.

**Comment by dummdidumm** [comment]
[This is intended](https://github.com/sveltejs/language-tools/pull/145) because else the completion list is not refreshed in VSCode, giving wrong suggestions after coming from an error state. What I did not take into account was that filtering should be done by us then, because as you said, VSCode does it. So we should filter it ourselves.

**Comment by dummdidumm** [comment]
Fix available in about 11 hours.

**Comment by Sorixelle** [comment]
Apologies for not making it clearer, but the issue also affects autocomplete for HTML and CSS parts as well. They both appear to set `isIncomplete` to true in their responses as well, looking at logging output. Sorry if that caused any confusion earlier 😅

**Comment by dummdidumm** [comment]
No problem, I completely forgot about them / thought they would not set `isIncomplete`, but they did. Behaviour is fixed now hopefully. Fix available in about 14 hours.
