### ISSUE TITLE
Svelte-check ignores most or all warnings

### ISSUE THREAD

**Issue by kvnloughead** [sveltejs/language-tools#2172]
### Describe the bug

Hello, I am having issues with svelte-check. It's ignoring most or all TypeScript warnings. You can see the screenshot below, you can see there is a warning in the MoreActions.svelte file, but svelte-check isn't picking up on it. I'm just running `svelte-check -- --watch`, but I've tried using `--fail-on-warning` and `--threshold warning` too. I'm sure that the files are being watched, because if I break things more severely the errors are caught. See both screenshots. 

I've been following along with an [older set of tutorials on MDN](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Svelte_TypeScript), so I suppose that's related to the issue. I've had a few other issues and have had to make tweaks to the config or package versions, but for the most part it has gone smoothly and everything works. Except this.

 

### Reproduction

Clone the repo at https://github.com/kvnloughead/todo-svelte, and checkout the `refactor/typescript` branch. Install node modules and run `npm run dev`. Then run `npm run check` or `npm run check:watch`. Do this in vscode, with the svelte for vscode extension. Make some typescript warnings happen, and note that svelte-check doesn't catch them.

### Expected behaviour

Svelte-check should display output showing typescript compiler warnings when they exist in the watched files.

### System Info

- OS: Linux Mint 21.1 Cinnamon 5.6.8
- IDE: VSCode

### Additional Information, eg. Screenshots

![image](https://github.com/sveltejs/language-tools/assets/37159177/7171942d-3fcb-4522-a010-175af066810d)
![image](https://github.com/sveltejs/language-tools/assets/37159177/40223d54-a130-40b3-953f-de14527c370d)

tsconfig.json
```json
{
  "extends": "@tsconfig/svelte/tsconfig.json",

  "include": ["src/**/*"],
  "exclude": ["node_modules/*", "__sapper__/*", "public/*"],
  "compilerOptions": { "ignoreDeprecations": "5.0" }
}
```

package.json
```json
{
  "name": "svelte-app",
  "version": "1.0.0",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "rollup -c",
    "dev": "rollup -c -w",
    "start": "sirv public --host",
    "check": "svelte-check",
    "check:watch": "svelte-check '--watch'"
  },
  "devDependencies": {
    "@rollup/plugin-commonjs": "^24.0.0",
    "@rollup/plugin-node-resolve": "^15.0.0",
    "@rollup/plugin-terser": "^0.4.0",
    "@rollup/plugin-typescript": "^11.0.0",
    "@tsconfig/svelte": "^3.0.0",
    "rollup": "^3.15.0",
    "rollup-plugin-css-only": "^4.3.0",
    "rollup-plugin-livereload": "^2.0.0",
    "rollup-plugin-svelte": "^7.1.2",
    "svelte-check": "^3.5.2",
    "svelte-preprocess": "^5.0.0",
    "tslib": "^2.5.0",
    "typescript": "^5"
  },
  "dependencies": {
    "sirv-cli": "^2.0.0",
    "svelte": "^4.2.0"
  }
}
```

svelte.config.js
```js
import sveltePreprocess from 'svelte-preprocess';

export default {
  preprocess: sveltePreprocess()
};

```

**Comment by jasonlyu123** [comment]
These are "hints" instead of "warnings" which is no longer showing in svelte-check 3 to align with tsc.

**Comment by kvnloughead** [comment]
Oh! Well, you can see that I don't really know what I'm talking about. Thanks for the response, I'll tweak the compiler settings.
