### ISSUE TITLE
Fix repository links / check project names

### ISSUE THREAD

**Issue by rondonjon** [sveltejs/language-tools#218]
The most popular Svelte extension on the VS Code Marketplace is currently [JamesBirtles.svelte-vscode](https://marketplace.visualstudio.com/items?itemName=JamesBirtles.svelte-vscode).

Its GitHub link however points to a repo whose development has been discontinued in favor of the [official svelte language-tools](https://github.com/sveltejs/language-tools).

That one is also available on the Marketplace, but under the name of [Svelte Beta](https://github.com/sveltejs/language-tools), which clearly attracts less users (currently 3K installations), but at least it points to the new/official repository location.

Which extension is now the right one to install if I want the latest, stable state?

Suggestions:

If "Svelte Beta" has been forked off "Svelte" to become the "official" extensions, then the "Svelte Beta" is probably more advanced and better tested than the "Svelte" extension, so the names would be misleading and should be switched.

If on the other hand the "Svelte" extension on the VSCode marketplace is now actually getting built from the official repo, then the author name and Github link on the marketplace page are outdated and should be replaced to avoid further confusion.

**Comment by dummdidumm** [comment]
Duplicate to #77 . We are trying to get this confusion resolved.
