### ISSUE TITLE
Language server crash

### ISSUE THREAD

**Issue by hvuhsg** [sveltejs/language-tools#2180]
### Describe the bug

Extension version: 107.12.0 (but also happening for older versions)

Under runtime status in the extension I see that:

Activation Event:onLanguage:svelte
Activation Time:151ms

Pending response rejected since connection got disposed
Client is not running and can't be stopped. It's current state is: starting
Client is not running and can't be stopped. It's current state is: startFailed
Pending response rejected since connection got disposed
Client is not running and can't be stopped. It's current state is: startFailed
Client is not running and can't be stopped. It's current state is: startFailed
Client is not running and can't be stopped. It's current state is: startFailed

And the language server isn't responding

PS: tried restart and reinstall

### Reproduction

.

### Expected behaviour

Language server to run

### System Info

IDE: VSCode

$ uname -a
Linux yoyo-HP-EliteBook-840-G5 6.2.0-34-generic #34~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 13:12:03 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Which package is the issue about?

Svelte for VS Code extension

**Comment by jasonlyu123** [comment]
Do you have the svelte.language-server.runtime or the svelte.language-server.ls-path config?

If so, please read carefully what the description says. Most people encounter crashes because they mix up these two configs. Or set it to a non-existence path. Unless you know why you need the config, I recommend you remove them.

**Comment by hvuhsg** [comment]
Solved by removing the svelte language runtime path (thanks!)
