### ISSUE TITLE
Typescript language is throwing weird missing-declaration errors

### ISSUE THREAD

**Issue by elizeuangelo** [sveltejs/language-tools#2187]
### Describe the bug

Typescript seems to be a little bit bugged in my .svelte files:

I'm using "vitePreprocess" in my svelte.config.js and here are my tsconfig.json:
```
		"target": "ES2022",
		"module": "NodeNext",
		"moduleResolution": "NodeNext",
		"baseUrl": "src/",
		"declaration": true,
		"declarationDir": "lib",
		"strict": true,
		"skipLibCheck": true,
		"isolatedModules": true,
		"resolveJsonModule": true,
		"esModuleInterop": true,
		"jsx": "preserve",
		"allowJs": true,
		"checkJs": true,
		"noImplicitOverride": true,
```

### Reproduction

<script lang="ts">
	export let columns: 'single' | 'double' = 'single';
</script>

<main>
	{#if columns === 'double'}
		<slot name="left" />
		<slot name="right" class="right-side" />
	{:else}
		<slot />
	{/if}
</main>

### Expected behaviour

Not display missing-declaration on a prop.

### System Info

- OS: [e.g. Windows]
- IDE: [e.g. VSCode, Atom]

### Additional Information, eg. Screenshots

![image](https://github.com/sveltejs/language-tools/assets/56921633/56eb7e83-ef3e-42d1-af34-4bc44439bd94)

![image](https://github.com/sveltejs/language-tools/assets/56921633/35bebb33-df19-46b9-af23-b40a9de13607)

**Comment by jasonlyu123** [comment]
I can't reproduce this.  I guess your tsconfig.json might have not been picked up. You can try toggling some strict type-check options to see if it makes any type-check difference. If it does, Please provide a reproduction in a repository form.

**Comment by elizeuangelo** [comment]
I created a very small repo where this happens on VSCODE:

https://github.com/elizeuangelo/svelte-ext-bug

I started removing all configurations and files (even vite) and I noticed the primary problematic configuration causing the issue seems to be:
```
		"module": "NodeNext",
		"moduleResolution": "NodeNext"
```

**Comment by elizeuangelo** [comment]
I disabled all extensions with exception of:
![image](https://github.com/sveltejs/language-tools/assets/56921633/170569dd-9ffd-4e55-b358-643a0a491849)

**Comment by elizeuangelo** [comment]
When changing moduleResolution the extensions seems to crash a lot, at one time it did not crashed but it accused "svelte-preprocess" encountered a type error on my .svelte file.

**Comment by jasonlyu123** [comment]
The problem is likely to do with preprocessing. So please add the preprocess config to your reproduction.

**Comment by elizeuangelo** [comment]
You are actually right. It was a preprocessor issue.
I had a preprocessor in my vite.config.ts file but i did not knew It was a must to import it from svelte.config.js.

I moved the preprocessor config from vite.config.js to svelte.config.js and now its working fine.

Thank you

**Comment by jasonlyu123** [comment]
The problem is with nodenext and svelte-process. The TypeScript API svelte-preprocess won't read the package.json, so it won't be able to know if you're using `type=module`. Thus transpiring it to commonJs. In case anyone sees this in the future. unless you absolutely need `nodenext`, You should set it to `bundler` or `esnext`. And if you're using vite-preprocess make sure your preprocess config is in the svelte.config.js
