### ISSUE TITLE
Svelte VSCode Auto-complete gives the additional text

### ISSUE THREAD

**Issue by flyingduck92** [sveltejs/language-tools#2195]
### Describe the bug

importing component giving suffix __SvelteComponent_ 
example:  `import App__SvelteComponent_ from './App.svelte';`

### Reproduction

Typing `import ComponentName` then tab will produce  ComponentName with suffix __SvelteComponent_ 
example:  `import App__SvelteComponent_ from './App.svelte';`

### Expected behaviour

import App from './App.svelte'

### System Info

- OS: Windows 10
- IDE: VSCode 1.84.1

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

![image](https://github.com/sveltejs/language-tools/assets/14885417/16619316-abf5-4b18-abfc-f6675a6c9488)
![image](https://github.com/sveltejs/language-tools/assets/14885417/34fd4c65-58f0-4a53-9d16-1a3b6a0c2d0a)

**Comment by jasonlyu123** [comment]
Fixed the insert text part, but I can't reproduce the suffix in the label, so I suspect you may have some conflict with other typescript-plugins. Can you check if the suffix is still there if you disable all other extensions? You can create an empty setting profile so it's easier to switch back after you have done the testing.

**Comment by flyingduck92** [comment]
I already disabled `Javascript and Typescript Nightly` and this is what I got when `ctrl + space` , perhaps the next update of the extension will be fixed

![image](https://github.com/sveltejs/language-tools/assets/14885417/f97e5be3-cb6c-4988-8857-3685e1492639)

**Comment by shyakadavis** [comment]
Hi.

I wanted to offer some additional context on when/where this happens - at least for me.

It only happens in TS/JS files.

Say I have 3 components; `a.svelte`, `b.svelte`, & `c.svelte`, all located in my `src/lib/components` dir.

Now, if I create an `index.ts` file within `src/lib/components`, and try to export all my components from the same place, that's when the additional suffix is noticed.

i.e.

```ts
// src/lib/components/index.ts

import A__SvelteComponent_ from './a.svelte';
...
export {a, b, c}
```

Hope the additional context helps. 🙂

**Comment by amjadorfali** [comment]
I am handling this issue ATM if that's okay

**Comment by amjadorfali** [comment]
I tried to reproduce the issue by trying it on my machine on a personal project, and I was successful.
When I tried it using the local setup i forked from this repo, it worked as you expected it to work (Not adding `__SvelteComponent_` suffix 😄

**Comment by flyingduck92** [comment]
> I tried to reproduce the issue by trying it on my machine on a personal project, and I was successful. When I tried it using the local setup i forked from this repo, it worked as you expected it to work (Not adding `__SvelteComponent_` suffix) 😄

have you tried using vite?

**Comment by amjadorfali** [comment]
@flyingduck92 Yep I am using Vite in the project I was reproducing on
