### ISSUE TITLE
Property 'files' does not exist on type 'SvelteInputProps'

### ISSUE THREAD

**Issue by PatrickG** [sveltejs/language-tools#220]
**Describe the bug**
I'm getting the following typescript error on an `input` element with `type="file"`.
`Property 'files' does not exist on type 'SvelteInputProps'.`

**To Reproduce**
```html
<script>
  let files;
</script>

<input type="file" bind:files />
```

**Expected behavior**
No error.

**Comment by dummdidumm** [comment]
Fix available in about 22 hours.

**Comment by martingraf4** [comment]
Same problem, this time for the `focusout` event: `Property 'onfocusout' does
not exist on type 'SvelteInputProps'`. 

**To reproduce**

```svelte
<input on:focusout={() => {}} />
```

**Comment by dummdidumm** [comment]
Fix available soon. Next time please open a separate issue. The problem is that [this files](https://github.com/sveltejs/language-tools/blob/master/packages/svelte2tsx/svelte-jsx.d.ts) is incomplete.
