### ISSUE TITLE
Inconsistent Props completion in namespaced component

### ISSUE THREAD

**Issue by huntabyte** [sveltejs/language-tools#2202]
### Describe the bug

I'm noticing that the autocomplete works only if a known prop comes before you attempt to trigger Intellisense.

Here's an example of trying to trigger Intellisense before the prop:
![image](https://github.com/sveltejs/language-tools/assets/64506580/716203d6-759f-47c3-b116-30c0f7ae0d9b)
 
Then if you try to trigger Intellisense after the prop, the correct result is displayed:
![image](https://github.com/sveltejs/language-tools/assets/64506580/98dc8c3a-901c-4ca1-9f9c-12c42eca28a3)

But if you try to use an expression, it also breaks:
![CleanShot 2023-11-14 at 15 22 09@2x](https://github.com/sveltejs/language-tools/assets/64506580/369dd6ea-ed23-4ef6-82e4-04714e5673e5)

Without the expression, all good:
![CleanShot 2023-11-14 at 15 22 35@2x](https://github.com/sveltejs/language-tools/assets/64506580/a87e32bb-8992-465f-8919-7dd8938c8712)

### Reproduction

Create a component:

```svelte
<!-- button.svelte -->
<script lang="ts">
	export let label = "Open menu"
	export let disabled = false
</script>

<button {disabled} aria-label={name}>
	<slot />
</button>
```

Export it

```ts
// index.ts
import Root from './button.svelte'
export { Root }
```

Attempt to get Intellisense to work when using it:

```svelte
<script lang="ts">
	import * as Button from '$lib'
</script>

<Button.Root >
	Open
</Button.Root>
```

### Expected behaviour

Once a space has been inserted after the `.Root`, Intellisense should display the props.

### System Info

- OS: MacOS
- IDE: VSCode

**Comment by AdrianGonz97** [comment]
Thanks for the fix @jasonlyu123, it's very much appreciated! 😄 I cloned this repo to test out the changes and noticed 1 issue.

The prop completions don't show correctly when you trigger them when you're 1 space out. It seems like it only triggers when you're two spaces out, as shown here:

![gif](https://i.imgur.com/quJMy9H.gif) 

With that in mind, I've tested out all of the scenarios where it previously didn't work and they all seem to work now!

**Comment by jasonlyu123** [comment]
I can't reproduce it with the reproduction. Are you sure the build succeeded? Or maybe you have the `svelte.language-server.ls-path` config? Or maybe tsc incremental build glitched? I did encounter this when I pulled the commit. But worked after I forced tsc to do a clean build.

**Comment by AdrianGonz97** [comment]
@jasonlyu123 Aha, you're correct! After deleting the my local repo and recloning, building and testing again, it seems to be working now. Sorry about that!!

Everything looks to be working beautifully. 😄 Thanks for the help!
