### ISSUE TITLE
organize-imports does not work when there is a module script block

### ISSUE THREAD

**Issue by PatrickG** [sveltejs/language-tools#221]
**Describe the bug**
organize-imports does not work when there is a `<script context="module">` block

**To Reproduce**
```html
<script context="module">
  // do whatever
</script>

<script lang="ts">
  import B from './B';
  import A from './A';
</script>
```

**Expected behavior**
Imports should be organized in both `script` blocks.

**Comment by PatrickG** [comment]
I think the fix in #545 is not the best option.

When using functions - that are imported in the module script block - in reactive statements, svelte warns that the function is not reactive.
For example: `"listen" is declared in a module script and will not be reactive`.

The imports should stay in the script block in which they are defined, the imports should be sorted independent from each other.

**Comment by dummdidumm** [comment]
This sounds more like inconsistent behavior in Svelte itself. Svelte should throw the warning in both cases since it's an import.

**Comment by PatrickG** [comment]
You are right.

Related https://github.com/sveltejs/svelte/pull/5847 https://github.com/sveltejs/svelte/issues/5954
