### ISSUE TITLE
Svelte 5: Implicit children not detected correctly

### ISSUE THREAD

**Issue by eddiemcconkie** [sveltejs/language-tools#2211]
### Describe the bug

If I have a `Parent.svelte` component that has a `children` prop, passing children to the component implicitly (without the `{#snippet children()}` block) I get the error `Property 'children' is missing in type '{}' but required in type '{ children: () => void; }'.`
If I put the children inside a `{#snippet children()}` block then the error goes away

### Reproduction

[REPL](https://svelte-5-preview.vercel.app/#H4sIAAAAAAAAE42OTQqDMBCFrzIMBRVE91alvUH3TRdiYhvQJCSjUCR3rzZUoXTR5fd-eG_GTvbCYXGdUTWDwALPxmCK9DQruEn0JBZ2erTtqpSutdJQzRQjORhtCS6NFYqgs3qAKMsDZqEaHZkq872jymC_--1D9nyhNbLJy9igueyk4FiQHYVPt28h9Mc96Bt1rxiSYximtHIEM3wmwUMFB2O1ceWuFhAnUNUwacnB13Hy_X4-LSku7NaIE__r8s2_ALut3O1aAQAA) (Error won't show up in the REPL, you may need to copy it over to VS Code)

### Expected behaviour

Implicit children get detected correctly

### System Info

- OS: MacOS
- IDE: VSCode

### Additional Information, eg. Screenshots

<img width="822" alt="image" src="https://github.com/sveltejs/language-tools/assets/12902531/c0fd9db0-008d-4ec0-b891-14a5514af168">

---

Not directly related to the bug, but I'm wondering if Svelte is going to provide some sort of `Snippet` type helper. For the time being, I'm using this:

```ts
type Snippet<T extends any[] = []> = (...args: T) => void;

// No parameters
type Children = Snippet // becomes () => void
// Parameters
type Row = Snippet<[item: T]> // becomes (item: T) => void
```
It's not really shorter than just writing out the actual function type, but it makes it more obvious which props are snippets and which aren't when typing `$props`

**Comment by dummdidumm** [comment]
A snippet helper will be added in the next release: https://github.com/sveltejs/svelte/pull/9584

**Comment by eddiemcconkie** [comment]
@dummdidumm That's great! I didn't realize until now that snippets can't take more than one argument. Looks like my type helper was a little over-engineered 😅
