### ISSUE TITLE
typescript error when using multiple snippets

### ISSUE THREAD

**Issue by amit13k** [sveltejs/language-tools#2219]
### Describe the bug

When using multiple snippets, I am getting typescript errors like `',' expected.`.

### Reproduction

```svelte
<script lang="ts">
</script>

{#snippet snippet1(name)}
	<p>hello {name}!</p>
{/snippet}

{#snippet snippet2(name)}
	<p>hello {name}!</p>
{/snippet}

{#snippet snippet3()}
	<p>hello hello3!</p>
{/snippet}
```

The error appears before `{#snippet snippet2` and after `snippet3()`.

The error doesn't appear if there is no script tag.

### Expected behaviour

No typescript errors

### System Info

- OS: [MacOS]
- IDE: [VSCode]
- VSCode extension Svelte for VS Code v108.1.0

### Which package is the issue about?

Svelte for VS Code extension

**Comment by miunau** [comment]
@dummdidumm is there a reason why you added the `fixed` label? This seems to happen still for me. I've noticed that if I contain the multiple snippets inside a `<div>` tag (or other DOM element), the problem goes away.

**Comment by jasonlyu123** [comment]
"Fixed" but not closed means "Fixed in master branch. Pending production release. ". If you hover over the issue label you can see a description tooltip.
