### ISSUE TITLE
Missing ä, ü and ö in Component Elements

### ISSUE THREAD

**Issue by MoinJulian** [sveltejs/language-tools#2223]
### Describe the bug

If I want to Import an Component that includes an ä, ü or ö in the name, that letter just gets removed from the name

### Reproduction

Create an Component including one of the letters mentioned above and try to import it

### System Info

```shell
MacOs 14.1.1
VSCode
```

### Severity

annoyance

**Comment by jasonlyu123** [comment]
This is technically an invalid tag name, and it breaks some features. The vscode-html-langaugeservice parses the tag name as Begr. And the syntax highlight is wrong if you're using a theme without semantic tokens support. So, I think we'll leave it this way.  You can rename it with the rename symbol if you really want to. Just some features might not work as intended.

**Comment by MoinJulian** [comment]
Ok
