### ISSUE TITLE
svelte-check reports false positive for Container Query Length Units

### ISSUE THREAD

**Issue by vekunz** [sveltejs/language-tools#2224]
### Describe the bug

We use CSS containers in our code, but svelte-check breaks if we use [Container Query Length Units](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_container_queries#container_query_length_units) (cqw, cqh, ...) in our SCSS code.

We have this SCSS rule (the `var` has nothing to with the error):
```scss
width: calc(100cqw + 2 * var(--some-var));
```

`svelte-check` reports a syntax error at the last `)` (I've added the '^' because I cannot use colors here):
```
Error: } expected (scss)
        width: calc(100cqw + 2 * var(--some-var));
                                                ^
```

If I replace the `cqw` with for example `vw`, `svelte-check` reports no problems.

Edit: You don't even need `calc()`, just use these units anywhere.

### Reproduction

See above.

### Expected behaviour

svelte-check should not report any problems, because this is valid code.

### System Info

- OS: macOS Sonoma
- IDE: WebStorm

### Which package is the issue about?

svelte-check

### Additional Information, eg. Screenshots

This is completely blocking us currently, because we cannot deploy a feature while svelte-check is 'red'.

**Comment by dummdidumm** [comment]
This error comes from the css checker, for which we use `vscode-css-languageservice`. This is an upstream issue we can't do anything about, related issue here: https://github.com/microsoft/vscode-css-languageservice/issues/375

Until this is fixed, you can [configure the diagnostics sources](https://github.com/sveltejs/language-tools/tree/master/packages/svelte-check#args) and exclude `css` from the list (this removes all css syntax checks, but at least your build is green)
