### ISSUE TITLE
Svelte 5 @render not recognized

### ISSUE THREAD

**Issue by GimpMaster** [sveltejs/language-tools#2229]
### Describe the bug

The svelte 5 pre-release docs show a change to <slot> such that the new preferred way is to use 

`{@render children()}`

![image](https://github.com/sveltejs/language-tools/assets/7818200/b34adea5-2cf1-41fd-af56-e0c897fb596f)

However in Intelli J using 

"svelte-language-server": "^0.16.1",
"typescript-svelte-plugin": "0.3.36",

I get the error in the picture

### Reproduction

Create a project and try to use {@render tag}

### Expected behaviour

No error is given

### System Info

- OS: Windows, WSL2
- IDE: Phpstorm, Intelli J, Webstorm

### Which package is the issue about?

svelte-language-server

**Comment by dummdidumm** [comment]
The Svelte language server contains a change that adjusts this. My guess is this error is coming from the IntelliJ Svelte Plugin itself, which doesn't know about this yet.

**Comment by GimpMaster** [comment]
Ok. Thank you. I’ll create a ticket on YouTrack.
