### ISSUE TITLE
svelte-check reports 'text-wrap' as an "Unknown property"

### ISSUE THREAD

**Issue by shadow-identity** [sveltejs/language-tools#2231]
### Describe the bug

svelte-check reports false-positive warning on [`text-wrap` CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/text-wrap) usage 

### Reproduction

* Into any CSS block, add
`text-wrap: balance;`
* Run `svelte-check`

### Expected behaviour

No error/warning should be reported

### System Info

- OS: [e.g. macOS]
- IDE: [terminal]

### Which package is the issue about?

svelte-check

### Additional Information, eg. Screenshots

```
Getting Svelte diagnostics...

/Users/blah-blah/+page.svelte:79:13
Warn: Unknown property: 'text-wrap' (scss)
        :global(h4) {
            text-wrap: balance;
        }
```

**Comment by jasonlyu123** [comment]
This is supported in [svelte-check-3.6.2](https://github.com/sveltejs/language-tools/releases/tag/svelte-check-3.6.2). Please update the lastest version.
