### ISSUE TITLE
Completion for custom element tag name

### ISSUE THREAD

**Issue by break-stuff** [sveltejs/language-tools#2245]
### Description

There doesn't seem to way to extend the language tool for custom elements.

### Proposed solution

Vue and JSX templates have an interface that can be extended to include custom elements/web components. This would be a nice way for library authors to provide better type integration and descriptions within svelte templates.

**Comment by jasonlyu123** [comment]
Yes. There is .

https://svelte.dev/docs/typescript#enhancing-built-in-dom-types

**Comment by break-stuff** [comment]
Oh, this is fantastic! Thank you!

**Comment by break-stuff** [comment]
@jasonlyu123 do you have a working example of this? It doesn't seem to work in my sample app.

**Comment by dummdidumm** [comment]
Can you provide a link to that example app?

**Comment by break-stuff** [comment]
Yeah, here's a simple repo.

https://github.com/break-stuff/svelte-custom-elements-demo

**Comment by jasonlyu123** [comment]
It does work in your repo. Are you expecting to have completion for it as well?

**Comment by break-stuff** [comment]
Yes, I don't see any difference in having it vs not having it in my repo.

**Comment by jasonlyu123** [comment]
The difference is it will be type-check for the element.

**Comment by jasonlyu123** [comment]
There is another way to add custom tag name completion. It's only a local config, so it's not something library authors can leverage, but it's still a good workaround until we can figure out a way to provide the completion. 

https://github.com/microsoft/vscode-html-languageservice/blob/main/docs/customData.md

**Comment by break-stuff** [comment]
Yeah, I created a package to generate that, but it would be nice if devs would only have to set one thing for types and autocomplete.

https://www.npmjs.com/package/custom-element-vs-code-integration
