### ISSUE TITLE
Add better autocompletion for namespace components

### ISSUE THREAD

**Issue by kwangure** [sveltejs/language-tools#2247]
### Description

While writing compound components it's common to group them using name spaces.

Library:
```js
// select.js
export { default as Option } from "./option.svelte";
export { default as Root } from "./select.svelte";

// index.js
export * as Select from "./select.js";
```

Usage:
```svelte
<script>
	import { Select } from '$lib/components';
</script>

<Select.Root>
	<Select.Option>1</Select.Option>
	<Select.Option>2</Select.Option>
</Select.Root>
```

This issue is a request to better support namespace autocomplete for components like `Select`.

### Proposed solution

For example, when using the select component, autocompletion should suggest Root and Option as the only options in the output. ATM the autocompletion list is not even related to the relevant namespace component being typed out.

```svelte
<Select.Root>
	<!-- 
		Here `|` represents the position of the cursor. 
		Autocomplete should suggest `Option` and `Root` only 
	-->
	<Select.|
</Select.Root>
```

### Additional Information, eg. Screenshots

Autocompletion works fine in the `<script/>` but not in the markup section.

**Comment by jasonlyu123** [comment]
Duplicated of #776. This is a limitation we have.
