### ISSUE TITLE
Svelte 5: Typescript's non-null assertion operator doesn't work when passing direct props.

### ISSUE THREAD

**Issue by HighFunctioningSociopathSH** [sveltejs/language-tools#2248]
### Describe the bug

The non-null assertion operator or for short `(!)` doesn't work when passing direct props to a component.
Note that it works fine when used inside a callback passed as a prop.

### Reproduction

let's say we have the following simple component that expects a prop.
```svelte
<svelte:options runes />

<script lang="ts">
  import type { Snippet } from "svelte";
  let { string, children } = $props<{ string: string; children: Snippet }>();
  $inspect(string);
</script>

{@render children()}
```
And then in our page, we render it like so
```svelte
<svelte:options runes />
<script lang="ts">
	import SimpleComponent from "$components/test/test.svelte";
	let simpleString: string | undefined = $state("just some value");
</script>

<SimpleComponent string={simpleString!}>hello</SimpleComponent>
```
Now here typescript will tell us that simpleString can be undefined and thus not assignable to the string prop which is of type string only. But I know that simpleString has a default value so I want to use the non-null assertion operator but it doesn't seem to work in this specific case. It is simply ignored

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-12650H
    Memory: 6.09 GB / 15.63 GB
  Binaries:
    Node: 18.14.2 - C:\Program Files\nodejs\node.EXE
    npm: 9.7.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.91)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    svelte: ^5.0.0-next.29 => 5.0.0-next.29
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
Simplified version:

```svelte
<script lang="ts">
    import { SvelteComponent } from 'svelte';

	class SimpleComponent extends SvelteComponent<{ children?: any; string: string; }, any, any> {}
	let simpleString: string | undefined = 'hello' as any; 
</script>

<SimpleComponent string={simpleString!}>hello</SimpleComponent>
```

Not sure why this is happening, the generated output preserves the `!`, so it should work, and if I paste the generated output into a `.ts` file I see no error - strange.
