### ISSUE TITLE
Format on save not working as expected

### ISSUE THREAD

**Issue by limitlessloop** [sveltejs/language-tools#225]
**Describe the bug**
When a `.svelte` document is formatted on save the indentation does not change.

**To Reproduce**
1. Install Svelte Beta for VScode.
2. Open any `.svelte` file
3. Save (make sure "format on save" is enabled in VScode settings).

**Expected behavior**
I expect the code to be formatted on save.

**Screenshots**
An example of code not being formatted below.
<img width="312" alt="CleanShot 2020-06-24 at 12 17 15@2x" src="https://user-images.githubusercontent.com/5551/85546319-ae69ec80-b614-11ea-8990-984186b54658.png">

**System (please complete the following information):**
 - OS: Mac
 - IDE: VScode
 - Plugin/Package: Svelte Beta

**Additional context**
I'm using this with `.editorconfig`.

**Comment by dummdidumm** [comment]
Does this mean if you do formatting "by hand" (with the sortcut/command) the code is formatted? Or is it not formatted at all?

**Comment by limitlessloop** [comment]
I tried debugging it further. I tried including a `.prettierrc` config and installing Prettier and I was able to get something working. Since disabling Prettier and removing the `.prettierrc` config it no longer has the issue and it formats on save. My guess would be that even before formatting by hand wouldn't have worked.

I should uninstall VScode and try from scratch if I get time.

I'm not familiar with how formatting works, but I'm thinking about the following scenarios:

- Should it format without Prettier installed?
- Should it format without a `.prettierrc` config?
- Should it pick up configuration from `.editorconfig`? Currently, editor config works when `.prettierrc` is present`.

**Comment by dummdidumm** [comment]
- It should be able to format without Prettier installed
- It should format without a `.prettierrc` config
- It does currently not pick up configuration from `.editorconfig`, but this can be added.

Under the hood, formatting works like the following:
1. Try to resolve prettier. First search in user's node_modules, fall back to own version, if not present.
2. Try to find a configuration file. If none present, no problem, defaults are used.
3. Format file using `prettier-plugin-svelte`.

If you try to format but it does not format anything, could you look into Output->Svelte and see if there is anything suspicious (or just copy the log in here)?

**Comment by limitlessloop** [comment]
Thanks for clarifying those points. If I get chance I'll try re-installing VScode and trying to reproduce the issue.

**Comment by s0me0ther** [comment]
I do have the same error. The code does not get modified on save.\
This only occurs in `.svelte` files, other files will get auto-formatted on save.\
My Output->Svelte only prints the Line `Using Svelte v3.24.0 from ....`\
Output->Prettier keeps empty on `.svelte` files, but works as expected and fills output on other files (eg: js, ts, ..)

**Comment by dummdidumm** [comment]
Does it format if you explicitely invoke the "format" command, or does it not format at all?

**Comment by s0me0ther** [comment]
> Does it format if you explicitely invoke the "format" command, or does it not format at all?

If i force vs-code format (`ctr + shift + i`), it does format all files except *.svelte files.

**Comment by dummdidumm** [comment]
There is a setting `svelte.format.enable`, is it set to `true` in your settings?

You said that inside Output-Svelte, only `Using svelte ...` is shown, which means it does not even get to the formatting code. If it would, there should be `Using Prettier ...` in the output as well.

**Comment by s0me0ther** [comment]
> There is a setting `svelte.format.enable`, is it set to `true` in your settings?

Yes, this setting is true

> You said that inside Output-Svelte, only `Using svelte ...` is shown, which means it does not even get to the formatting code. If it would, there should be `Using Prettier ...` in the output as well.

It seems to me that IDE and console does not work with the same options / settings.

Yesterday i added the option to preprocess sass, which works nice, without any problems (via cli `webpack-dev-server --config config/webpack.config.js --progress`), but the IDE throws an error (Output Svelte):

```
Using Svelte v3.24.0 from /home/user/path/project/node_modules/svelte/compiler
Preprocessing failed
Error: Cannot find any of modules: sass,node-sass
    at Object.importAny (/home/user/path/project/node_modules/svelte-preprocess/dist/modules/importAny.js:29:15) {
  __source: 'Style'
}
```

Maybe this is related..

**Comment by dummdidumm** [comment]
I think this is an unrelated issue. You need to install either `sass` (recommended) or `node-sass`. [See here for more info](https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/scss-less.md).

**Comment by s0me0ther** [comment]
> I think this is an unrelated issue. You need to install either `sass` (recommended) or `node-sass`. [See here for more info](https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/scss-less.md).

Thanks for the link. I just added the node binary path into `svelte.language-server.runtime`, which resolves the none-sass error :zap:.

The settings `svelte.language-server.ls-path` and `svelte.language-server.port` are empty. All other settings like `svelte.plugin.typescript.enable` are enabled.

**Comment by dummdidumm** [comment]
Possible reason: https://github.com/sveltejs/prettier-plugin-svelte/issues/74#issuecomment-665831712

**Comment by dummdidumm** [comment]
@s0me0ther @limitlessloop could you check if this could be the cause of your problem? https://github.com/sveltejs/prettier-plugin-svelte/issues/74#issuecomment-665831712

**Comment by s0me0ther** [comment]
> @s0me0ther @limitlessloop could you check if this could be the cause of your problem? [sveltejs/prettier-plugin-svelte#74 (comment)](https://github.com/sveltejs/prettier-plugin-svelte/issues/74#issuecomment-665831712)

@dummdidumm , this works great for svelte files now, thank you!\
But, if i change the default formatter from `esbenp.prettier-vscode` to `svelte.svelte-vscode` i can **only** format svelte files :/.\
Is there a way to use different formatters on different filetypes?

**Comment by jasonlyu123** [comment]
Did you set the default to all the file type?

**Comment by s0me0ther** [comment]
> Did you set the default to all the file type?

Yes i did. I'm pretty new to VSCode..\
Now i use following Settings, which works like a charm:

```json
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "[svelte]": {
    "editor.defaultFormatter": "svelte.svelte-vscode"
  },
```

Thank you all for solving this Issue!
