### ISSUE TITLE
typescript-svelte-plugin breaks neovim native LSP

### ISSUE THREAD

**Issue by philippviereck** [sveltejs/language-tools#2251]
### Describe the bug

As soon as I add the `typescript-svelte-plugin` to my `tsconfig.json` the zero-effort typesafety features take effect as expected, but basic LSP features stop working for example, autocompletion does not suggest anything inside the `$lib/` folder anymore. Remove the plugin from `tsconfig.json` obviously removes the zero-effort typesafety and then autocomplete suggestions for `$lib/` exports also starts to work again as expected. 

I also added the path aliases and includes manually to my `tsconfig.json` this results in import statements for `$lib` working, but autocomplete is still not working properly.

For those that want both, I switched to `coc-svelte` there both work out of the box (Typescript language features and Svelte language features with zero-effort type safety

### Reproduction

add the `typescript-svelte-plugin` to your `tsconfig.json` with for example a LazyVim setup, create a `+server.ts` and some export in `lib/` and try to auto-import it from autocompletion.

### Expected behaviour

That typescript LSP features still work after adding `typescript-svelte-plugin` to `tsconfig.json`

### System Info

- OS: [macOS 14.2.1]
- IDE: [NeoVim v0.10.0-dev-2055+gbeca82721-Homebrew
Build type: Release
LuaJIT 2.1.1703358377]

**Comment by philippviereck** [comment]
The dev server is running and I don't know if this is a upstream issue maybe. I used LazyVim to reduce the likelyhood of my config being faulty but I had the same experience with my and other configs.

Here are some example video to illustrate more clearly what I mean:
# with plugin in `tsconfig` and native LSP
in the beginning I get the suggestion, but there's no auto-import or information when I confirm/select it

zero-effort type safety: ✅
autocomplete: ❌

https://github.com/sveltejs/language-tools/assets/105976309/cf7fd21e-e767-4f08-afad-81b998fed316

# no plugin and native LSP
zero-effort type safety: ❌ 
autocomplete: ✅

https://github.com/sveltejs/language-tools/assets/105976309/cfd24b05-1b0b-45d1-9005-c54c91818436

# no plugin extra plugin in `tsconfig` and`coc-svelte` (not native LSP)
this is the behaviour I expected with native LSP too

zero-effort type safety: ✅
autocomplete: ✅

https://github.com/sveltejs/language-tools/assets/105976309/4b38a485-665c-4760-99ec-cf93bb9dc3bb

(pls don't judge my vim skills)

**Comment by jasonlyu123** [comment]
I can reproduce the auto-import problem and found the issue. However, the import statement completion and the path completion for the module specifier both work for me. I think it is likely a config issue like the base config not being generated when you're testing. If this isn't the case can you provide a reproduction repository?

**Comment by philippviereck** [comment]
I re-tested, and couldn't reproduce issues with the import statement either.

**Comment by philippviereck** [comment]
Autoimport works now in `typescript-svelte-plugin 0.3.37` thank you <3
