### ISSUE TITLE
Find prop usages 

### ISSUE THREAD

**Issue by dummdidumm** [sveltejs/language-tools#2253]
### Describe the bug

Searching for references of a component prop at some point revealed the usage locations I believe, now it no longer does

### Reproduction

```
<script>
  export let foo = true; // do find references on foo
</script>
```
```
<script>
  import Sub from './sub.svelte';
</script>
<Sub foo={true} />
```

### Expected behaviour

should fine the parent prop usage

### System Info

irrelevant

### Which package is the issue about?

svelte-language-server

**Comment by dummdidumm** [comment]
Mhm I think this actually never worked, at least I don't see any code related to this that would've made it work. For Svelte runes mode we should look into supporting this - I have an idea how to do it.

**Comment by jasonlyu123** [comment]
Yeah. I don't remember it ever work. But we do have the support in rename-symbol, so we probably could reuse/copy some logic from there.
