### ISSUE TITLE
Typescript error with adjacent Snippets: `',' expected.ts(1005)`

### ISSUE THREAD

**Issue by adam-coster** [sveltejs/language-tools#2254]
### Describe the bug

When I define adjacent snippets, those after the first one get a non-breaking Typescript error on its initial `{ character: ',' expected.ts(1005)`.

This seems to be true no matter where I put the snippets (they can be separated by other content) and no matter what is inside the snippets.

The error is only visible in VSCode's dignostics.

### Reproduction

Drop the following into a `+page.svelte` SvelteKit file:

```html
{#snippet hello(world)}{/snippet}
{#snippet goodbye(world)}{/snippet}
{#snippet again(world)}{/snippet}
```

And see the following in VSCode:

![image](https://github.com/sveltejs/svelte/assets/28758057/a756025d-e3ed-4ef0-b3df-b74c0754c15f)

(The error does not appear in the REPL.)

I'm using Typescript 5.3.3 in my project. I tried downgrading all the way to 5.0.0 but the error persists.

### Logs

The error only appears in VSCode diagnostics -- it does not appear in any logs.

### System Info

```json
// deps
{
"svelte": "^5.0.0-next.32",
"@sveltejs/adapter-auto": "^3.1.0",
"@sveltejs/adapter-node": "2.1.1",
"@sveltejs/kit": "^2.2.1",
"@sveltejs/vite-plugin-svelte": "^3.0.1"
}
```

- Svelte for VS Code extension (latest)

VSCode info:

```
Version: 1.86.0-insider (user setup)
Commit: fb769554405bee9be16e21ceb0a496bd29126941
Date: 2024-01-09T09:57:14.563Z
Electron: 27.2.1
ElectronBuildId: 26149897
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22631
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
Already fixed by https://github.com/sveltejs/language-tools/commit/a2f86e10e50e563f5b09c136b0cf0c2756c988ae , release pending.
