### ISSUE TITLE
Symbols defined outside of the `.svelte` file being edited cannot be found in VSCode post extension v108.2.0

### ISSUE THREAD

**Issue by ktnyt** [sveltejs/language-tools#2260]
### Describe the bug

Symbols which are defined outside of the `.svelte` file that I'm currently working in cannot be found from within the `.svelte` file using the VSCode autocomplete feature.

### Reproduction

```ts:example.ts
export const THE_ANSWER = 42;
```

```svelte:Example.sevlte
<div>{THE_ANSWER}</div>
```

# In 108.1.0
![Kapture 2024-01-14 at 09 33 27](https://github.com/sveltejs/language-tools/assets/1581965/7cff4262-b9ff-44ca-8d13-f067c48aa02f)

# In 108.2.0
![Kapture 2024-01-14 at 09 32 22](https://github.com/sveltejs/language-tools/assets/1581965/28381a8c-2f86-48d1-b3a2-2f347a4a59bc)

### Expected behaviour

Autocompletion is consistent with prior extension versions.

### System Info

- OS: macOS Monterey Version 12.7.0
- IDE: VSCode 
  - Version: 1.85.1 (Universal)
  - Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
  - Date: 2023-12-13T09:48:06.308Z (1 mo ago)
  - Electron: 25.9.7
  - ElectronBuildId: 25551756
  - Chromium: 114.0.5735.289
  - Node.js: 18.15.0
  - V8: 11.4.183.29-electron.0
  - OS: Darwin arm64 21.6.0

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

Hello contributors. First of all I'd like to thank everyone for your effort in delivering an awesome ecosystem of development tools. I've only started working with Svelte in the last few months and it has absolutely been a wonderful experience.

As I was working on a project today I noticed that some symbols were not being found by the VSCode autocomplete feature. After searching for potential solutions and double checking if I had accidentally altered some essential settings, I came to a dead end and as a last resort suspected if any recent changes to the toolchain had anything to do with this issue. Realizing that the most recent Svelte extension version (as of writing) which is 108.2.0 was updated this morning (in JST) which is exactly when I started to experience issues.

I confirmed that installing 108.1.0 fixed the issue so I will use 108.1.0 for now.

**Comment by akb5566** [comment]
If you are using Sveltekit, 108.2.0 also cannot auto-import your custom components.

e.g. 
- You have a component named `UserList` in `$lib/components/UserList.svelte`
- You type `<Use />` in another svelte file, it won't auto-complete/auto-import `UserList` component for you like it used to.

Downgrade to 108.1.0 fix this problem.
