### ISSUE TITLE
Add support for typescript "Build-Free Editing with Project References"

### ISSUE THREAD

**Issue by mamidenn** [sveltejs/language-tools#2262]
### Description

In a monorepo with multiple typescript packages the typescript language server can automagically resolve imports between packages directly to the source file (presumably via in-memory transpilation). This means I don't have to build a package every time I change something in it in order to have those changes (at least the typings) reflected in the dependent packages.
Unfortunately this does not work when importing into `.svelte` files.

This is how it looks when I did not transpile `@module-resolution-repro/lib`:

![ts-lsp](https://github.com/sveltejs/language-tools/assets/4650305/caddfb5b-cba8-4b3a-8cf1-014d0e189ab0)
![svelte-ts-lsp](https://github.com/sveltejs/language-tools/assets/4650305/2064b6e2-15a4-437a-9e36-28b8f5af3e50)

Something appears to get lost in translation when the svelte language server uses the typescript language server 😞 .

### Proposed solution

Please look into whether it is possible to support this as it would make monorepos with mixed Svelte and typescript packages much more pleasant to work with. 

This is specifically *not* asking to support this for imports of `.svelte` files (I gather this would be way more involved). "Just" to enable imports of typescript modules *into* `.svelte` files to be resolved as the current typescript language server does it when importing into `.ts` files.

### Alternatives

Run `tsc -b -w` in referenced typescript packages.

### Additional Information, eg. Screenshots

- I have set up a repro repo here: [mamidenn/module-resolution-repro](https://github.com/mamidenn/module-resolution-repro)
- [Announcing TypeScript 3.7 RC - TypeScript > Build-Free Editing with Project References](https://devblogs.microsoft.com/typescript/announcing-typescript-3-7-rc/#build-free-editing-with-project-references)
- [For editing experience, use source instead of .d.ts files from project references by sheetalkamat · Pull Request #32028 · microsoft/TypeScript](https://github.com/microsoft/TypeScript/pull/32028)

**Comment by jasonlyu123** [comment]
Duplicated of #2148. Haven't figured out what is missing yet.

**Comment by jasonlyu123** [comment]
It's actually not entirely the same as #2148 but let's still track this there. Thanks for the reproduction!
