### ISSUE TITLE
 Incorrect Positioning of Svelte Warnings with TypeScript (lang="ts")

### ISSUE THREAD

**Issue by lab-do** [sveltejs/language-tools#2264]
### Describe the bug

When utilizing `lang="ts"` in the script tag of a Svelte component to incorporate TypeScript, the position of Svelte warnings is inaccurately displayed. The warnings seem to be positioned at the wrong place relative to the actual source code line that triggered the warning.

### Reproduction

- Create a Svelte component with TypeScript by adding `lang="ts"` to the script tag.
- Introduce a deliberate warning in the component to trigger Svelte warnings.

### Expected behaviour

The expected behavior is that the Svelte warning should be displayed at an appropriate and visually accurate position in the browser when using TypeScript (lang="ts"). The warning position should align with the actual source code line that triggered the warning.

### System Info

- OS: [e.g. linux arch]
- IDE: [VSCode, Neovim]

### Which package is the issue about?

svelte-language-server

### Additional Information, eg. Screenshots

[Screencast from 2024-01-20 10-08-16.webm](https://github.com/sveltejs/language-tools/assets/84672102/fea2fec9-528e-4052-9ca5-83a7c71543ed)

**Comment by jasonlyu123** [comment]
Can you provide your svelte.config.js?

**Comment by lab-do** [comment]
```js
import adapterVercel from "@sveltejs/adapter-vercel";
import adapterNode from "@sveltejs/adapter-node";
import { vitePreprocess } from "@sveltejs/vite-plugin-svelte";
import { preprocessMeltUI } from "@melt-ui/pp";
import sequence from "svelte-sequential-preprocessor";

/** @type {import('@sveltejs/kit').Config} */
const config = {
  // Consult https://kit.svelte.dev/docs/integrations#preprocessors
  // for more information about preprocessors
  preprocess: sequence([
    // ... other preprocessors
    vitePreprocess(),
    preprocessMeltUI(), // add to the end!
  ]),

  kit: {
    // adapter-auto only supports some environments, see https://kit.svelte.dev/docs/adapter-auto for a list.
    // If your environment is not supported or you settled on a specific environment, switch out the adapter.
    // See https://kit.svelte.dev/docs/adapters for more information about adapters.
    adapter: process.env.VERCEL
      ? adapterVercel({ runtime: "edge" })
      : adapterNode({ outDir: "build" }),
    serviceWorker: {
      register: false,
    },
    files: {
      serviceWorker: "src/sw.ts",
    },
    csrf: {
      checkOrigin: process.env.NODE_ENV === "production",
    },
    alias: {
      $lib: "./src/lib",
      $assets: "./src/assets",
    },
  },
};

export default config;
```

**Comment by lab-do** [comment]
It seems like the problem is linked to the preprocessor. When I tested it without the sequence preprocessor, the issue went away.
