### ISSUE TITLE
Unknown at rule @container if it is nested in SCSS context

### ISSUE THREAD

**Issue by shadow-identity** [sveltejs/language-tools#2265]
### Describe the bug

Svelte-check reports on nested `@container` rule inside of SCSS style sheet.

It does **not** report in CSS context or if the `@container` is not nested.

### Reproduction

```html
<style lang="scss">
    article {
        @container main (min-width: 80em) {
            grid-template-rows: 1fr;
        }
    }
</style>
```

Then run `svelte-check` and see this warning message: 
```
Warn: Unknown at rule @container (scss)

        @container main (min-width: 80em) {
            grid-template-rows: 1fr;
```

### Expected behaviour

No warning

### System Info

- OS: macOS
- IDE: IntelliJ Idea

### Which package is the issue about?

svelte-check

### Additional Information, eg. Screenshots

In my pnpm-lock.yaml: `svelte-check: version: 3.6.2(postcss@8.4.33)(sass@1.69.5)(svelte@4.2.1)`

**Comment by nonameolsson** [comment]
@shadow-identity Thank you for creating this issue! I have a hard time understanding why this problem happens. Could you help me understand it, and what would be needed to solve this bug? Thanks! 🙂

**Comment by jasonlyu123** [comment]
This happen because it is a new syntax and it isn't supported yet by upstream VSCode css language service.
