### ISSUE TITLE
Latest extension update throws : "Extension 'Svelte for VS Code' is configured as formatter but it cannot format 'Svelte'-files" and CTRL + Click a component does not transport to that component

### ISSUE THREAD

**Issue by MarArMar** [sveltejs/language-tools#2289]
### Describe the bug

"Extension 'Svelte for VS Code' is configured as formatter but it cannot format 'Svelte'-files"

Was working fine until lately

### Reproduction

- Create a svelte repo
- Install  'Svelte for VS Code' (svelte.svelte-vscode)
- Setup prettier with "[prettier-plugin-svelte](https://github.com/sveltejs/prettier-plugin-svelte))"
- Check that prettier is working fine on Typescript
- Try the VSCode formatting action in .svelte files
- See the error message

### Expected behaviour

Previously it worked fine, it stopped working after I updated it

### System Info

- OS: Windows 10
- IDE: VSCode 1.85.1

### Which package is the issue about?

Svelte for VS Code extension

**Comment by mattpilott** [comment]
I have this same issue, nothing fixes it, reboot, reinstall, downgrade cursor, it no longer formats on save, was working day before last
