### ISSUE TITLE
style tages gets moved on save - formatting issue

### ISSUE THREAD

**Issue by ImmanuelSamuel** [sveltejs/language-tools#229]
**Describe the bug**
Style tags are moved between script and html on save after code formatting.

**Expected behavior**
Ability to disable this in settings?

**System (please complete the following information):**
 - OS: Windows
 - IDE: VSCode
 - Plugin/Package: "Svelte Beta"

**Comment by jasonlyu123** [comment]
https://github.com/sveltejs/prettier-plugin-svelte#configure-for-vs-code-and-atom

**Comment by ImmanuelSamuel** [comment]
I have prettier and Svelte Beta installed (not sure if this is the issue because that repo said it is included in Unwritten\Svelte")

Prettier works on other files except Svelte. So was wondering if there is a way to enable Prettier for Svelte?

I have the following in .prettierrc
```
{
 "svelteSortOrder": "styles-scripts-markup",
 "svelteStrictMode": true,
 "svelteBracketNewLine": true,
 "svelteAllowShorthand": false
}
```

and settings.json
```
{
 "editor.defaultFormatter": "esbenp.prettier-vscode"
}
```

**Comment by ImmanuelSamuel** [comment]
uninstalled and reinstalled everything ... now it seems to work. maybe there there were other extensions causing errors?!
