### ISSUE TITLE
using "bundler" as moduleResolution breaks full path imports from node_modules

### ISSUE THREAD

**Issue by zaanposni** [sveltejs/language-tools#2295]
### Describe the bug

When using "bundler" as moduleResolution - as it is recommended with SvelteKit2 - Visual Studio Code cannot handle direct/relative imports of Svelte Components in node_modules.

### Reproduction

I have created a small repository to reproduce this scenario.
https://github.com/zaanposni/svelte-language-tools-vscode-bug/

1. Clone repo.
2. npm install in both applications.
3. View file `my-app/src/routes/+page.svelte` in VS Code with Svelte for VS Code Version `v108.2.2`.

You will see no error, this is due to [the fix I commited](https://github.com/zaanposni/svelte-language-tools-vscode-bug/commit/bf85de9ae48cdfff0745004138bc33ae3b465b75) as a possible workaround to this repository.
Either revert the last commit or change the moduleResolution to "bundler".

![image](https://github.com/sveltejs/language-tools/assets/24491035/40a950a0-c32a-40ed-a072-abf4c00b134c)
`Cannot find module 'my-package/PackageButton.svelte' or its corresponding type declarations.js(2307)`

### Expected behaviour

We expect VS Code to work with full path imports the same way it would work with imports of an index file. Furthermore, since the "bundler" option is recommended by SvelteKit2, we expect this to work with the language-tools as well.

### System Info

- OS: Windows 10 and Ubuntu 20
- IDE: VSCode 1.86.0 and WebStorms 2023.2.1
- Svelte for VS Code: v108.2.2

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

I know that the default way to create a package in Svelte is to use a index.js or index.ts file. It appears that most Svelte Open Source Projects do it this way (e.g. https://www.skeleton.dev/). However, we wanted to use direct imports for two reasons:
- no need to create and maintain a index file
- potentially faster and smaller compilation

One question I would like to ask is, is this even supported or recommended to do? What are the standards/best practices that we should use?

Interesting to add: Both the dev server as well as the production build work as intended with both settings. So this appears to be a language-tools issue.

**Comment by dummdidumm** [comment]
This doesn't work because exports need to match exactly, down to the file ending. Change it to this and it works:
```diff
  "exports": {
    "./*": {
-      "types": "./*",
+      "types": "./*.d.ts",
      "svelte": "./*"
    }
  },
```
