### ISSUE TITLE
LSP messaging - Neovim

### ISSUE THREAD

**Issue by acurrieclark** [sveltejs/language-tools#2302]
With Neovim, I have a function set up to organize my buffer imports which currently only works with typescript files. It sends a specific command to the LSPs attached to the current buffer.

```lua
local function organize_imports()
  local params = {
    command = '_typescript.organizeImports',
    arguments = { vim.api.nvim_buf_get_name(0) },
    title = '',
  }
  vim.lsp.buf.execute_command(params)
end
```

I have had a look in this repo to see if I can identify a similar command which I could issue to achieve the same thing in Svelte.
Could anyone give me any pointers?

**Comment by jasonlyu123** [comment]
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_codeAction

"Organize imports" is a standard code action kind. You can see if neovim has any built-in trigger mechanism. If not you can send a code action request with `CodeActionContext.only = [CodeActionKind.SourceOrganizeImports]`.

**Comment by acurrieclark** [comment]
Thank you for this. That pointed me in the right direction.

For anyone else looking for this, this is the lua command I ended up using:

```lua
vim.lsp.buf.code_action { context = { only = { 'source.organizeImports' } }, apply = true }
```
