### ISSUE TITLE
Snippet props are unusable in Svelte 69

### ISSUE THREAD

**Issue by adriandelgado** [sveltejs/language-tools#2303]
### Describe the bug

Trying to use any kind of snippet, including "children" fails to typecheck.
`svelte-check` says:
```
Error: This expression is not callable.
  Type 'Symbol & { _: "functions passed to {@render ...} tags must use the `Snippet` type imported from \"svelte\""; }' has no call signatures. (ts)
```
While `eslint` says:
```
0:0  error  Parsing error: Cannot read properties of undefined (reading 'length')
```

### Reproduction

```
pnpm create svelte snippet-bug
# skeleton project + typescript + eslint
pnpm install
# create any component with a snippet prop
```

Example component:
```svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  let { children } = $props<{ children: Snippet }>()
</script>

{@render children()}
```

### Expected behaviour

I expect the provided component to typecheck successfully.

### System Info

- OS: Linux (Pop OS)
- IDE: VSCode
- `eslint-plugin-svelte`: "2.36.0-next.6"
- `svelte-check`: "3.6.5"
- `svelte`: "5.0.0-next.69"

**Comment by dummdidumm** [comment]
Should be fixed in the latest release of the VS Code extension

**Comment by adriandelgado** [comment]
I don't think this issue should be closed yet. While it is true that the extension stopped reporting errors, `svelte-check` and `eslint` still give the same errors.

**Comment by dummdidumm** [comment]
New version of `svelte-check` was released

**Comment by eunukasiko** [comment]
Thank you, that fixed it
