### ISSUE TITLE
Svelte autocomplete is not working in version 108.3.1 of the vscode extension

### ISSUE THREAD

**Issue by madacol** [sveltejs/language-tools#2309]
### Describe the bug

Emmet abbreviations for html tags in .svelte files are not working in the vscode extension

This is a regression made in version `108.3.1` of the vscode extension

### Reproduction

- open a svelte file
- partially type an HTML tag so the intellisense triggers

### Expected behaviour

I expected this: (version 108.3.0)
![image](https://github.com/sveltejs/language-tools/assets/6379896/0aee78ed-c0a2-4ac6-adf2-8cb62d97922f)

Instead I get this:  (version 108.3.1)
![image](https://github.com/sveltejs/language-tools/assets/6379896/3464265b-e6e8-4ca7-aa7b-b5a7e32fa743)

### System Info

- OS: Linux
- IDE: VSCode

### Which package is the issue about?

Svelte for VS Code extension

**Comment by jasonlyu123** [comment]
Can't reproduce this. It's probably something else other than the emmet completion that is throwing an error. Can you check if there is any error logged in the output channel. You can opening it by the "Output: Show output channels" command in the command palette (Ctrl+P), and chose svelte.

**Comment by madacol** [comment]
Sorry, problem solved after OS reboot :confused: 

If it's worth anything there wasn't an Output channel for Svelte, and remember seeing some errors related to `svelte.check` in the Extension Host channel

**Comment by jasonlyu123** [comment]
That sounds like the language server crashed. If the problem happens consistently, feel free to add more info and preferably a reproduction repository.
