### ISSUE TITLE
Parentheses with comma operator in #if causes "Expression expected"

### ISSUE THREAD

**Issue by Th0rN13** [sveltejs/language-tools#231]
**Describe the bug**
Comma operator in parentheses causes the error "Expression expected"
I found it in `{#if }`, but there may be similar behavior in other places.
It not very usable, but can be used for debug

**To Reproduce**
```
{#if (true, false)}
  content
{/if}
```

**Expected behavior**
No error

**System (please complete the following information):**
 - OS: Windows
 - IDE: VSCode
 - Plugin/Package: Svelte Beta

**Comment by jasonlyu123** [comment]
Something the error is compile errors from svelte compiler. Do you found any problems like this but has no problems building? Both of these examples are not valid syntax.

**Comment by Th0rN13** [comment]
This is valid syntax, and compiles without errors, and works as expected

**Comment by jasonlyu123** [comment]
Do you mean any expression with parentheses and comma, like a function call?

**Comment by jasonlyu123** [comment]
Sorry I must have miss something when checking if it compiled eailer.

**Comment by Th0rN13** [comment]
> Do you mean any expression with parentheses and comma, like a function call?

No, i mean this syntax - [comma operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comma_Operator). I wrap condition in parentheses

If i use 
```
{#if prop === propCompare}
  content
{/if}
```
and want to temporarily change condition to true, but don't want fully remove condition, i use
```
{#if (prop === propCompare, true)}
  content
{/if}
```
This calculate conditions and use last operand in comma operator

Yes, i can use this without parentheses, like `{#if (prop === propCompare, true)}`, and it works good, but i use parentheses for visibility to me.

**Comment by jasonlyu123** [comment]
Thanks for pointing that out. Learned something. We must check this in various transformation in sveltetsx.

**Comment by jasonlyu123** [comment]
Await block also has this. but in both cases, the problem is not with comma but the extra parentheses

**Comment by arpitkalla** [comment]
Hey, I was looking into this issue and identified the problem was with `appendLeft`-ing the extra parenthesis as opposed to overwriting. I pointed it in the PR but my patch removes extra parenthesis around the guard. The "Expression expected" error should be removed, will test that out too.

**Comment by jasonlyu123** [comment]
https://github.com/sveltejs/language-tools/blob/1bcd66d91cbca1e462e48effcc034b66431fe657/packages/svelte2tsx/src/htmlxtojsx.ts#L503
https://github.com/sveltejs/language-tools/blob/1bcd66d91cbca1e462e48effcc034b66431fe657/packages/svelte2tsx/src/htmlxtojsx.ts#L87
These two also has similar problem
