### ISSUE TITLE
Typescript imports from modules are not re-evaluated when they change

### ISSUE THREAD

**Issue by rhoot** [sveltejs/language-tools#2311]
### Describe the bug

When importing a type from a module, changing that type requires restarting the language server for the change to be picked up.

### Reproduction

```sh
$ npm create vite@latest my-app -- --template svelte-ts
$ cd my-app
$ npm install
$ mkdir -p node_modules/some_module
$ pushd node_modules/some_module
$ npm init -y
$ popd
```

Open the editor and modify:

`node_modules/some_module/package.json`:
```json
{
    "main": "index.ts"
    ...
}
```

`node_modules/some_module/index.ts`:
```ts
export class Foo
{
    //bar = 5;
}
```

`src/App.svelte`:
```svelte
<script lang="ts">
    import { Foo } from "some_module";
    const foo = new Foo();
    //console.log(foo.bar);
```

Then uncomment both commented out lines. On the `console.log` line, the editor will say "Property `bar` does not exist on type `Foo`", despite that it was just uncommented.

### Expected behaviour

The editor does not show diagnostics saying "Property `bar` does not exist on type `Foo`".

### System Info

- OS: Linux
- IDE: neovim

### Which package is the issue about?

_svelte-language-server_

### Additional Information, eg. Screenshots

In my specific case the module is a symlink, from having `"some_module": "file:../some_module"` as dependency in `packages.json` and running `npm install`, and the link target is also in my workspace. So I'm not technically editing files inside `node_modules` (I'm not _that_ crazy). My folder setup is thus the slightly more sane:

```
.
├── my-app
│   ├── node_modules
│   │   └── some_module -> ../../some_module
│   ├── src
│   │   └── App.svelte
│   └── package.json
└── some_module
    ├── index.ts
    └── package.json
```

It reproes regardless of the link however.

I'm not sure if it's a problem with the language server or somewhere else in the chain, but I figured this was a good place to start.

**Comment by jasonlyu123** [comment]
We currently only watch node_modules in a limited way to avoid performance problems. But symlinked packages in a monorepo should be resolved to the source path. So although we didn't watch node_modules, your actual project structure should work. 

The problem is probably either #1415, where you can resolve with the `root_dir` config https://github.com/sveltejs/language-tools/issues/1415#issuecomment-1539724329

```lua
local root_pattern = require('lspconfig.util').root_pattern
lspconfig.svelte.setup {
    root_dir = root_pattern(".git")
}
```

Or #2008, where your file watch is not registered. To resolve this, you can either use neovim nightly or manually change your client capability:

``` lua
local lsp_capabilities = vim.lsp.protocol.make_client_capabilities() --or whatever your setup requires
lsp_capabilities.workspace.didChangeWatchedFiles.dynamicRegistration = true
lspconfig.svelte.setup {
    capabilities = lsp_capabilities,
}
```

**Comment by rhoot** [comment]
Thanks for the pointers! The problem appears to be both actually. Looking at those issues and the code linked in that comment you linked it makes sense that it's treating the dirs as roots due to `package.json`.

That said, unlike the comment you linked I don't have two instances of the language server running. The process tree looks identical with or without those config changes. Including all the command line arguments. That comment at least suggested there would be multiple processes involved. But maybe an "instance" can be something other than a process too? :shrug: 

Either way, applying both those fixes have worked, so thanks for your help!

![image](https://github.com/sveltejs/language-tools/assets/1258798/1c66842a-bd57-4f51-99a5-7db31acc2c9c)
