### ISSUE TITLE
Support for syntax highlighting in .mdx files

### ISSUE THREAD

**Issue by sillvva** [sveltejs/language-tools#2322]
### Description

Right now, syntax highlighting for svelte blocks in markdown does not apply to `.mdx` files, like it does for `.md` files.

![CleanShot 2024-03-23 at 13 11 37@2x](https://github.com/sveltejs/language-tools/assets/5138384/a4c448f5-fcea-4b6d-ba1b-e31728482724)

### Proposed solution

I would like for the syntax highlighting that applies to code blocks in `.md` files to also apply to the same blocks in `.mdx` files.

### Additional Information, eg. Screenshots

Other languages are working fine in `.mdx` files

![CleanShot 2024-03-23 at 13 15 20@2x](https://github.com/sveltejs/language-tools/assets/5138384/7dfa3f99-35b0-471d-b946-e6e0ba1c2da9)

**Comment by benkates** [comment]
+1 for this request, helpful in Storybook-based development

**Comment by benkates** [comment]
Thank you so much @jasonlyu123!
