### ISSUE TITLE
CompileError [ParseError]: Unexpected character '@'

### ISSUE THREAD

**Issue by nathanblair** [sveltejs/language-tools#2343]
### Describe the bug

Trying to use `{@render children()}` (not sure if it applies to rendering other named properties?) causes a compile/parsing error.

### Reproduction

1. Install VS Code
2. Install svelte extension
3. Below code should work to reproduce by saving in a `svelte` file
4. Investigate logs from svelte language server/extension

```
<script>
  const { children } = $props()
</script>

<footer>
  {@render children()}
</footer>
```

### Expected behaviour

Able to parse `render` statements and allow formatting of `.svelte` files

### System Info

- OS: M1 MBP
- IDE: VS Code
- VS Code Extension Version: 108.3.4

### Which package is the issue about?

Svelte for VS Code extension

### Additional Information, eg. Screenshots

```
CompileError [ParseError]: Unexpected character '@'
  2 |   /** @type {{ children: import("svelte").Snippet }}*/
  3 |   const { children } = $props()
> 4 | </script>
    |   ^
  5 |
  6 | <footer>
  7 |   {@render children()}

...
```

**Comment by mjadobson** [comment]
From: https://github.com/sveltejs/language-tools/issues/2338#issuecomment-2063782028

Svelte 5 syntax isn't supported out of the box currently. You need to install latest `prettier` and `prettier-plugin-svelte` in your project.

Run:
```
npm i --save-dev prettier-plugin-svelte prettier
```

Create a `.prettierrc` in project root:
```
{
    "plugins": ["prettier-plugin-svelte"],
    "overrides": [{ "files": "*.svelte", "options": { "parser": "svelte" } }]
}
```

**Comment by nathanblair** [comment]
The language tools would work with svelte 5 when 5 is formally released, presumably?
