### ISSUE TITLE
no outline in vscode

### ISSUE THREAD

**Issue by easyfrog** [sveltejs/language-tools#2353]
### Describe the bug

<img width="1105" alt="image" src="https://github.com/sveltejs/language-tools/assets/10724325/435b8b5d-c5aa-4b57-b77e-9424bd8df3a2">
No symbols found in document.

### Reproduction

create a template svelte project`

### Expected behaviour

has code outline.

### System Info

- OS: Mac os 13.6.6 (22G630)
- IDE: vscode Version: 1.88.1

**Comment by jasonlyu123** [comment]
Reopen since it is indeed somewhat unreliable in VSCode when the file is first opened but usually reappears when the file is updated.
