### ISSUE TITLE
Derived stores show types as any when using Svelte 5

### ISSUE THREAD

**Issue by CaptainCodeman** [sveltejs/language-tools#2359]
### Describe the bug

Store values and set, in a derived store, all become `any`. The code builds OK and shows the correct types within vs.code.

Possibly related: https://github.com/sveltejs/svelte/issues/8699

### Reproduction

```
Error: Parameter '$value' implicitly has an 'any' type. 
        return derived(store, ($value, set) => {

Error: Parameter 'set' implicitly has an 'any' type. 
        return derived(store, ($value, set) => {
```

### Expected behaviour

No warnings for typed code.

### System Info

- OS: Macos Sonoma 14.4.1
- IDE: VSCode
- svelte: ^5.0.0-next.120
- svelte-check: ^3.7.0

**Comment by jasonlyu123** [comment]
This is most likely something wrong with the type definition therefore closing in favour of https://github.com/sveltejs/svelte/issues/11415
