### ISSUE TITLE
Svelte VSCode doesn't register OnEnter Rules for indentation

### ISSUE THREAD

**Issue by b-fuze** [sveltejs/language-tools#236]
**Describe the bug**
The VSCode extension doesn't register OnEnter rules for auto indentation.

**To Reproduce**

Pressing enter with the cursor (`|`) here:
```html
<div>|</div>
```
Produces this
```html
<div>
|</div>
```

**Expected behavior**
Pressing enter with the cursor (`|`) here:
```html
<div>|</div>
```
Should produce this (assuming 2 space indentation setting)
```html
<div>
  |
</div>
```

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - IDE: VSCode
 - Plugin/Package: https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode

**Additional context**
I patched the extension copy pasting the code from the HTML extension snippet below and it fixed the problem.

https://github.com/microsoft/vscode/blob/04c36be045a94fee58e5f8992d3e3fd980294a84/extensions/html-language-features/client/src/htmlClient.ts#L209-L226

**Comment by dummdidumm** [comment]
If you already did a fix you are welcome to make a PR 😃

**Comment by dummdidumm** [comment]
Will be on Nightly in about 22 hours. Stable: tbd.
