### ISSUE TITLE
how to disable warning  has unused export property

### ISSUE THREAD

**Issue by craigcosmo** [sveltejs/language-tools#2362]
### Describe the bug

how to disable warning  has unused export property. I have a whole bunch of messy blue warning inside my terminal. can't see the data from console.log

### Reproduction

put export let data in a svelte file, and dont use it anywhere in the file

### Expected behaviour

should be able to turn of the warning

### System Info

mac os 17.
VScode latest

### Additional Information, eg. Screenshots

<img width="859" alt="CleanShot 2024-05-02 at 16 39 38" src="https://github.com/sveltejs/language-tools/assets/538657/780c1c95-f02d-4981-9c5b-235f44a6d799">

**Comment by craigcosmo** [comment]
do that in the entire project?

**Comment by jasonlyu123** [comment]
There might be warnings that make sense to disable project-wise but I don't think this is the one. If you have so many to the point you can't fix them. You're probably doing something wrong. 

Nonetheless, you can use the [svelte.plugin.svelte.compilerWarnings](https://github.com/sveltejs/language-tools/tree/master/packages/language-server#sveltepluginsveltecompilerwarnings) for the editor and the [onwarn](https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/config.md#onwarn) for the build.

**Comment by craigcosmo** [comment]
how do I config [svelte.plugin.svelte.compilerWarnings](https://github.com/sveltejs/language-tools/tree/master/packages/language-server#sveltepluginsveltecompilerwarnings) ?

**Comment by craigcosmo** [comment]
To disable almost all the blue warning in sveltekit, do this

open setting.json in vscode and add this

```json
"svelte.plugin.svelte.compilerWarnings": {
		"css-unused-selector": "ignore",
		"unused-export-let": "ignore",
		"a11y-aria-attributes": "ignore",
		"a11y-incorrect-aria-attribute-type": "ignore",
		"a11y-unknown-aria-attribute": "ignore",
		"a11y-hidden": "ignore",
		"a11y-autocomplete-valid": "ignore",
		"a11y-misplaced-role": "ignore",
		"a11y-no-static-element-interactions": "ignore",
		"a11y-unknown-role": "ignore",
		"a11y-no-abstract-role": "ignore",
		"svelte-ignore a11y-autofocus": "ignore",
		"a11y-no-redundant-roles": "ignore",
		"a11y-role-has-required-aria-props": "ignore",
		"a11y-accesskey": "ignore",
		"a11y-autofocus": "ignore",
		"a11y-misplaced-scope": "ignore",
		"a11y-positive-tabindex": "ignore",
		"a11y-invalid-attribute": "ignore",
		"a11y-missing-attribute": "ignore",
		"a11y-img-redundant-alt": "ignore",
		"a11y-label-has-associated-control": "ignore",
		"a11y-media-has-caption": "ignore",
		"a11y-distracting-elements": "ignore",
		"a11y-structure": "ignore",
		"a11y-mouse-events-have-key-events": "ignore",
		"a11y-missing-content": "ignore",
		"a11y-click-events-have-key-events": "ignore",
		"a11y-no-noninteractive-element-interactions": "ignore"
	},
```

Then open the svelte.config.js file and do this

```js
const config = {
	preprocess: vitePreprocess(),
	onwarn: (warning, handler) => {
		if (warning.code.startsWith('a11y-')) return
		if (warning.code === 'missing-exports-condition') return
		if (warning.code === 'a11y-no-static-element-interactions') return
		if (warning.code === 'svelte-ignore a11y-autofocus') return
		if (warning.code.startsWith('css-unused-selector')) return
		handler(warning)
	},
	kit: {
		adapter: adapter(),
	},
}
```

Add more rules you hate into those files/config.
