### ISSUE TITLE
Svelte 5: two TS quirks

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/language-tools#2365]
### Describe the bug

In Svelte 4 app I was using:

```svelte
{#each players || [] as player, i}
    <FormPlayer index={i} bind:player />
{/each}
```

Now with Svelte 5 I need to use:

```svelte
{#each players || [] as player, i}
    <FormPlayer index={i} bind:player={players[i]} />
{/each}
```

But now player is unused and I get the ts warning:

```
'player' is declared but its value is never read. ts(6133)
```

Plus, with the latter one I get another typscript warning:

```
'players' is possibly 'null' or 'undefined'. ts(18049)
```

even if I'm already inside an `{#each players}`.

**Comment by jasonlyu123** [comment]
> 'player' is declared but its value is never read. ts(6133)

```svelte
{#each players || [] as _, i}
    <FormPlayer index={i} bind:player={players[i]} />
{/each}
```

> 'players' is possibly 'null' or 'undefined'. ts(18049)

This is because TypeScript doesn't narrow the type like this. It's not something we can fix. You can move the `players || []` part to another derived/reactive variable so it'll always be not nullable.
