### ISSUE TITLE
Svelte 5: No error when passing the wrong type into a bindable property

### ISSUE THREAD

**Issue by wackbyte** [sveltejs/language-tools#2370]
### Describe the bug

svelte-check does not error when a value of the wrong type is passed into a bindable property.

### Reproduction

**`Test.svelte`**
```svelte
<script lang="ts">
    let {
        prop = $bindable(""),
    }: {
        prop?: string;
    } = $props();

    // errors will occur here if `prop` is used incorrectly
</script>
```

**`App.svelte`**
```svelte
<script lang="ts">
    import Test from "./Test.svelte";
</script>

<Test prop=1 />
<!-- no error here! -->
```

### System Info

```shell
System:
    OS: Linux 6.8 NixOS 24.05 (Uakari) 24.05 (Uakari)
    CPU: (12) x64 AMD Ryzen 5 3600X 6-Core Processor
    Memory: 8.48 GB / 15.56 GB
    Container: Yes
    Shell: 5.2.26 - /nix/store/h3bhzvz9ipglcybbcvkxvm4vg9lwvqg4-bash-5.2p26/bin/bash
Binaries:
    Node: 20.12.2 - /nix/store/71r8n7ckcpvav9qwshlr12hjd5nlchds-nodejs-20.12.2/bin/node
    npm: 10.5.0 - /nix/store/71r8n7ckcpvav9qwshlr12hjd5nlchds-nodejs-20.12.2/bin/npm
    pnpm: 8.15.5 - /nix/store/vcm0aysl9vsas3awwqdwwrh1r074qcnd-pnpm-8.15.5/bin/pnpm
npmPackages:
    svelte: 5.0.0-next.127 => 5.0.0-next.127
```

Using svelte-check 3.1.7.

### Severity

annoyance

**Comment by jasonlyu123** [comment]
This is expected. `prop=1` is equivalent to `prop="1"`  which "is" string. 

https://svelte-5-preview.vercel.app/#H4sIAAAAAAAACp2QwWrEMAxEf0WIHjYQNvSabLb0H3qrC5t1lNTgWEZyWpYl_944gdLSW30bzYz10B0H50mxfr1j6CbCGp9jxBLTLWahH-QTrVp5FpsnJ7XiYgLfhbE1mNTg2QRYn5siS4IX0gSD8AQGj1VWx_0Xg40Jp2rvr51VbNkoHNtHqM7rmol7NzjqsU4y01J-U-Xkf7A8JbjvfLBtghYeri703dXTwaDBosz2Uv-OPdWgSVwYm83NrTzWQ9FkcpMsB2VPR8_jIVPxsPWK7AJUFZAIi8Kn8x7Y2lngnYTADXDJwQs4hVmpBxcsi5BN_vbjPn-P8bZ8AUOrxSKuAQAA

**Comment by wackbyte** [comment]
Ah, looks like I forgot about unquoted attributes. Thank you!
