### ISSUE TITLE
Semantic token highlights entire $props() type annotation

### ISSUE THREAD

**Issue by max-got** [sveltejs/language-tools#2374]
### Describe the bug

Just a quick little syntax highlighting bug in a script tag:
Template literals aren't properly highlighted in $props() type declaration:

![initial_svelte_vs](https://github.com/sveltejs/language-tools/assets/64729700/440d5ff6-88b3-4ca0-a429-06f501eb9203)

As shown above, can be worked around with a separate type

### Reproduction

```
<script lang="ts">
	type Icon = `i-ph-${string}`;
	let { icon, iconType }: { icon: Icon; iconType: `i-ph-${string}` } = $props();
</script>
```

### Expected behaviour

<img width="935" alt="fixed_svelte_vs" src="https://github.com/sveltejs/language-tools/assets/64729700/00feba05-4eb3-4785-affb-be25de60672b">

### System Info

- IDE: VSCode
- Svelte for VS Code v108.4.1

### Which package is the issue about?

Svelte for VS Code extension

**Comment by paoloricciuti** [comment]
So i've investigated this a bit and the problem is that `svelte2tsx` generate this code for a component with `$props` like this

```svelte
<script lang="ts">
    const {foo}:{foo: string} = $props();
</script>

{foo}
```

```ts
///<reference types="svelte" />
;function render() {
;type $$ComponentProps = {foo: string};
    const {foo}:$$ComponentProps = $props();
;
async () => {

foo;
};
return { props: {} as any as $$ComponentProps, slots: {}, events: {} }}

export default class extends __sveltets_2_createSvelte2TsxComponent(__sveltets_2_partial(__sveltets_2_with_any_event(render()))) {
    constructor(options = __sveltets_2_runes_constructor(__sveltets_2_partial(__sveltets_2_with_any_event(render())))) { super(options); }
    $$bindings = __sveltets_$$bindings('');
}
```

the key point is that instead of having the inline type this line get's converted to
```ts
const {foo}:$$ComponentProps = $props();
```
when the language server map the tokens of this code to the original position `$$ComponentProps` get's correctly identified as a type alias (infact in the code looks like a single type alias).

This is the code responsible for the generation of that part

```ts
} else {
	// Create a virtual type alias for the unnamed generic and reuse it for the props return type
	// so that rename, find references etc works seamlessly across components
	this.$props.type = '$$ComponentProps';
	preprendStr(
		this.str,
		generic_arg.pos + this.astOffset,
		`;type ${this.$props.type} = `
	);
	this.str.appendLeft(generic_arg.end + this.astOffset, ';');
	this.str.move(
		generic_arg.pos + this.astOffset,
		generic_arg.end + this.astOffset,
		node.parent.pos + this.astOffset
	);
	this.str.appendRight(generic_arg.end + this.astOffset, this.$props.type);
}
```
and just by doing this
```diff
} else {
	// Create a virtual type alias for the unnamed generic and reuse it for the props return type
	// so that rename, find references etc works seamlessly across components
	this.$props.type = '$$ComponentProps';
	preprendStr(
		this.str,
		generic_arg.pos + this.astOffset,
		`;type ${this.$props.type} = `
	);
	this.str.appendLeft(generic_arg.end + this.astOffset, ';');
	this.str.move(
		generic_arg.pos + this.astOffset,
		generic_arg.end + this.astOffset,
		node.parent.pos + this.astOffset
	);
-	this.str.appendRight(generic_arg.end + this.astOffset, this.$props.type);
+	this.str.appendRight(generic_arg.end + this.astOffset, generic);
}
```
the problem is indeed fixed.

However this comment made me think that this might not be the right solution. I tried debugging the vscode extension and the rename seems to work across file but maybe i'm missing something?

I can open the PR with this fix but i think this will need to update a bunch of tests and again i feel like i'm missing something. Maybe there's a way to map the original position to the actual type instead of the alias?

**Comment by paoloricciuti** [comment]
[The sourcemaps seems to be correct](https://sokra.github.io/source-map-visualization/#base64,Ly8vPHJlZmVyZW5jZSB0eXBlcz0ic3ZlbHRlIiAvPgo7ZnVuY3Rpb24gcmVuZGVyKCkgewo7dHlwZSAkJENvbXBvbmVudFByb3BzID0ge2JhYmE6IHN0cmluZ307Clx0Y29uc3Qge2JhYmF9OiQkQ29tcG9uZW50UHJvcHMgPSAkcHJvcHMoKTsKOwphc3luYyAoKSA9PiB7CgpiYWJhO307CnJldHVybiB7IHByb3BzOiB7fSBhcyBhbnkgYXMgJCRDb21wb25lbnRQcm9wcywgc2xvdHM6IHt9LCBldmVudHM6IHt9IH19CgpleHBvcnQgZGVmYXVsdCBjbGFzcyBDb21wX19TdmVsdGVDb21wb25lbnRfIGV4dGVuZHMgX19zdmVsdGV0c18yX2NyZWF0ZVN2ZWx0ZTJUc3hDb21wb25lbnQoX19zdmVsdGV0c18yX3dpdGhfYW55X2V2ZW50KHJlbmRlcigpKSkgewogICAgY29uc3RydWN0b3Iob3B0aW9ucyA9IF9fc3ZlbHRldHNfMl9ydW5lc19jb25zdHJ1Y3RvcihfX3N2ZWx0ZXRzXzJfd2l0aF9hbnlfZXZlbnQocmVuZGVyKCkpKSkgeyBzdXBlcihvcHRpb25zKTsgfQogICAgJCRiaW5kaW5ncyA9IF9fc3ZlbHRldHNfJCRiaW5kaW5ncygnJyk7Cn0=,eyJ2ZXJzaW9uIjozLCJuYW1lcyI6W10sInNvdXJjZXMiOlsiZmlsZTovLy9jb21wLnN2ZWx0ZSJdLCJtYXBwaW5ncyI6IjtBQUFBLENBQUM7QUFDYSwwQkFBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxFQURUO0FBQ2xCLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsaUJBQWUsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUM7QUFDeEM7YUFBUzs7QUFFUixDQUFDLENBQUMsQ0FBQyxDQUFDIiwiZmlsZSI6ImV4YW1wbGUuanMifQ==,PHNjcmlwdCBsYW5nPSJ0cyI+Clx0Y29uc3Qge2JhYmF9OntiYWJhOiBzdHJpbmd9ID0gJHByb3BzKCk7Cjwvc2NyaXB0PgoKe2JhYmF9)

**Comment by jasonlyu123** [comment]
The problem is indeed because of the `$$ComponentProps` alias. You could probably surround the `this.$props.type` with the ignore-comment and check if another feature is affected. I can't think of a situation but if you find one we can consider another possible fix.

**Comment by dummdidumm** [comment]
I vaguely remember there being situations where the intellisense features didn't work properly if not extracting it into an interface. Maybe not all of it is covered with tests yet so it's best to test find references, go to definition, rename etc out manually before and after (and if there's a difference possibly add a regression test)

**Comment by paoloricciuti** [comment]
> I vaguely remember there being situations where the intellisense features didn't work properly if not extracting it into an interface. Maybe not all of it is covered with tests yet so it's best to test find references, go to definition, rename etc out manually before and after (and if there's a difference possibly add a regression test)

The PR the introduced it was because of find reference and tbf it make sense since without the type alias those are just two different types with the same shape.

I'll try again but I suspect the issue is there.

> The problem is indeed because of the `$$ComponentProps` alias. You could probably surround the `this.$props.type` with the ignore-comment and check if another feature is affected. I can't think of a situation but if you find one we can consider another possible fix.

Which of the `this.$props.type` are you referring to? Also from what I've seen it seems to actual map correctly to the position of the type but the type of token returned from typescript is interface.

**Comment by jasonlyu123** [comment]
> Which of the this.$props.type are you referring to?

this one in the code you referenced: 
```ts
this.str.appendRight(generic_arg.end + this.astOffset, this.$props.type)
```

> from what I've seen it seems to actual map correctly to the position of the type but the type of token returned from typescript is interface
I am not sure where you saw it being `interface` but it probably doesn't matter much. The problem is that the token doesn't actually exist in the source file so filtering it out should fix it.

**Comment by paoloricciuti** [comment]
Great it seems to work...opening a pr right now.

**Comment by paoloricciuti** [comment]
> The actual literal type is moved but can still mapped back to the original position. So the semantic tokens of the original literal type still exist. The `$$ComponentProps` one is generated and originally overlaps with the original type tokens. The whole range of the literal is marked as type because the generated `$$ComponentProps` is mapped to there
> 
> ```ts
> { icon: Icon; iconType: `i-ph-${string}` }
> ```
> 
> but within the range, there is also `icon` and `iconType` which is `property`, and `Icon` is `type`. [VSCode doesn't support overlap](https://github.com/microsoft/vscode-languageserver-node/blob/fc5ed68ccb69737a17b1c3c992b9831457b9dc4a/client/src/common/semanticTokens.ts#L100) so the inner ones probably got filtered out.

Ohhhhh yeah this makes total sense
