### ISSUE TITLE
feat: Please Consider registering this extension in openvsx the vendor neutral Marketplace

### ISSUE THREAD

**Issue by ddaza** [sveltejs/language-tools#238]
**Is your feature request related to a problem? Please describe.**

In the spirit of open source, there are some clones of VSCode that remove some MS tracking code, namely the most popular is: https://vscodium.com/

They have a lot of popular extensions on their vendor-neutral Marketplace, but Svelte is not one of them. 
This is the marketplace: https://open-vsx.org/

**Describe the solution you'd like**
Add support of the svelte extension into the open-vsx Marketplace. 
Here are the steps of how to do so: 
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension

**Describe alternatives you've considered**
n/a

**Additional context**

![tenor-214565924](https://user-images.githubusercontent.com/290254/85939645-de4b1580-b8dc-11ea-8e18-76da27d6e850.gif)

**Comment by orta** [comment]
Sure, want to add support to https://github.com/orta/monorepo-deploy-nightly and then we'll get it on here?

**Comment by ddaza** [comment]
https://github.com/orta/monorepo-deploy-nightly/pull/2

**Comment by orta** [comment]
This is all in and deployed, we'll see if it works tomorrow

**Comment by dummdidumm** [comment]
https://open-vsx.org/extension/svelte/svelte-vscode-nightly seems to have worked. Only the "everyone can publish to this"-banner at the top worries me a little, seems like you have to register to claim the namespace.

**Comment by ddaza** [comment]
You have to claim the namespace according to the docs

https://github.com/eclipse/openvsx/wiki/Namespace-Access#how-to-claim-a-namespace

**Comment by orta** [comment]
Requested

**Comment by dummdidumm** [comment]
Your request passed, the banner is gone. I just did a production deployment and it worked publishing it to the marketplace 😃 Link: https://open-vsx.org/extension/svelte/svelte-vscode
