### ISSUE TITLE
Cannot find name 'variable' when using a default value in a snippet

### ISSUE THREAD

**Issue by Keagel** [sveltejs/language-tools#2384]
### Describe the bug

A warning appears on variables assigned a default value within a snippet, indicating that the name cannot be found. The warning disappears if the default value is removed. The content of the default value doesn't change the warning, ie. `''` and `'foo'` all give the same warning - it doesn't come from it being an empty string.

The error is independent from the type of the variable - the warning remains even if the type is removed.

### Reproduction

Using [this repo](https://stackblitz.com/~/github.com/Keagel/svelte5-snippet-bug?file=src/routes/TextField.svelte), install the `Svelte for VS Code` extension and enable the Typescript plugin when prompted.

### Expected behaviour

There should be no warning.

### System Info

- IDE: VSCode
- Extension: Svelte for VS Code v108.5.0

### Which package is the issue about?

Svelte for VS Code extension

**Comment by dummdidumm** [comment]
Fixed in Svelte itself, update to the latest version and it should start to work
