### ISSUE TITLE
IDE Support for anchor positioning properties

### ISSUE THREAD

**Issue by ramiroaisen** [sveltejs/language-tools#2390]
### Describe the problem

Right now anchor positioning properties shows a warning of unknown css property in VSCode and probably any other IDE with support for svelte.

### Describe the proposed solution

As anchor positioning is available in stable Chrome and will be in other engines in brief, it would be nice to have support for its properties out of the box.

### Importance

nice to have

---

List of properties:
`anchor-name`
`offset-anchor`
`overflow-anchor`
`position-anchor`

maybe there more, note that a great part of the functionality extends the inset properties instead of creating new ones.

**Comment by dummdidumm** [comment]
We're using the VS Code CSS language service for these validations, so if that one gets support for this feature, we do, too. Right now this feature is still super new and only Chrome has implemented it yet, and only very very recently.
