### ISSUE TITLE
{@render ...} unknown

### ISSUE THREAD

**Issue by Dudek-AMS** [sveltejs/language-tools#2403]
### Describe the bug

![image](https://github.com/sveltejs/language-tools/assets/100142218/f7ffaa87-8e4d-484b-be78-3766a36b2d48)

### Reproduction

```html
<script lang="ts">
    let { children } = $props();
</script>



{@render children()}
```

### Expected behaviour

No Error

### System Info

- OS: Windows 11
- IDE: IntelliJ

Language Server: 0.16.10
Typescript Svelte Plugin 0.3.38
![image](https://github.com/sveltejs/language-tools/assets/100142218/28f29c97-6752-412f-8fca-4f31af2f44f3)

### Which package is the issue about?

svelte-language-server

**Comment by dummdidumm** [comment]
Is your project using Svelte 5? This error shouldn't be occuring assuming you use the latest language server and have wired it up in Intellij correctly.

**Comment by Dudek-AMS** [comment]
Yes its svelte 5. Its correctly setup in intellij and i just replaced the shipped language server with the latest version from local node modules

**Comment by jasonlyu123** [comment]
Can you check if the svelte2tsx in the node_modules of your custom language server is the latest version?

**Comment by Dudek-AMS** [comment]
peerDep was 0.7.8
ive updated manually to 0.7.10


same result

**Comment by Dudek-AMS** [comment]
```
//tsconfig.json
{
	"extends": "./.svelte-kit/tsconfig.json",
	"exclude": ["node_modules", ".svelte-kit", "build"],
	"compilerOptions": {
		"allowJs": true,
		"checkJs": true,
		"esModuleInterop": true,
		"forceConsistentCasingInFileNames": true,
		"resolveJsonModule": true,
		"skipLibCheck": true,
		"sourceMap": true,
		"strict": true,
		"moduleResolution": "bundler",
		"emitDecoratorMetadata": true,
		"experimentalDecorators": true,
		"strictPropertyInitialization": false
	}
	// Path aliases are handled by https://kit.svelte.dev/docs/configuration#alias
	// except $lib which is handled by https://kit.svelte.dev/docs/configuration#files
	//
	// If you want to overwrite includes/excludes, make sure to copy over the relevant includes/excludes
	// from the referenced tsconfig.json - TypeScript does not merge them in
}
```

I'm gonna try VSCode, but first need to install it.

**Comment by Dudek-AMS** [comment]
I can confirm, on EAP (2024.2) the snippet syntax work flawlessly
