### ISSUE TITLE
svelte@5.0.0-next.157 breaks svelte-check

### ISSUE THREAD

**Issue by lts20050703** [sveltejs/language-tools#2405]
### Describe the bug

svelte@5.0.0-next.157 breaks svelte-check (and intellisense)

When trying to run `svelte-check` errors such as the following will appear (as well as VSCodium will scream at me)

- Error: Cannot find name '$state'.ts(2304)
- Error: Cannot find name '$derived'.ts(2304)
- Error: Cannot find name '$effect'.ts(2304)
- ...

I'm not sure if this is a bug in svelte or the svelte-check tool needs to be updated, so feel free to close this one if it's a bug in svelte. (The other bug report: https://github.com/sveltejs/svelte/issues/12066)

### Reproduction

1. `npm install svelte@5.0.0-next.157`
2.
```svelte
<script>
let x = $state()
let y = $derived(x * 2)
$effect(() => {
  console.log("Mounted")
})
</script>
```

### Expected behaviour

No errors

### System Info

- OS: KDE Neon 6.0
- IDE: VSCodium 1.90.1
- Svelte for VSCode: 108.5.0
- svelte-check: 3.8.0

### Which package is the issue about?

svelte-check

**Comment by dummdidumm** [comment]
Fixed by https://github.com/sveltejs/language-tools/commit/026111228b5814a9109cc4d779d37fb02955fb8b
