### ISSUE TITLE
Bug: Preventing Valid Completion Requests

### ISSUE THREAD

**Issue by AravindPrabhs** [sveltejs/language-tools#2431]
https://github.com/sveltejs/language-tools/blob/027ab23e3e59939ad1f018a34ca5e0386cbaf829/packages/language-server/src/plugins/typescript/features/CompletionProvider.ts#L119

It seems like there is a typo in line 119 where `triggerKind` should be `triggerCharacter`
```typescript
const isCustomTriggerCharacter = triggerKind === vscode_languageserver_1.CompletionTriggerKind.TriggerCharacter;
// vs
const isCustomTriggerCharacter = triggerCharacter === vscode_languageserver_1.CompletionTriggerKind.TriggerCharacter;
```

**Comment by AravindPrabhs** [comment]
Adding more debug logs I realise this could just be down to a naming consistency between vscode-languageserver and the swift-language-server. However still unsure how that boolean captures the `isCustomTriggerCharacter` property.

**Comment by dummdidumm** [comment]
The code is correct. Note that the enum is named `CompletionTriggerKind`, which means it has to do with trigger kinds. And `TriggerCharacter` is one of these kinds, which is checked here.

**Comment by AravindPrabhs** [comment]
Ahhh ok that makes sense. So, where would the language server get ts completions while typing out an identifier ? These would be normal alphabet characters e.g. "y" that means the following is true `!validTriggerCharacter && !isJsDocTriggerCharacter && !isEventOrSlotLetTriggerCharacter`. So I expected some fault in `isCustomTriggerCharacter` but realising I am not fully understanding if this is the right place to get completions. 

I should've made it clearer on what I am looking into to. 
I am trying to debug why svelte-language-server inside Zed (the editor) provides no completions while typing inside the script tag. Switching the  isCustomTrigger to be false effectively brought my completions back.

**Comment by dummdidumm** [comment]
If the completion is incomplete, then the language server returns a corresponding boolean. The client should then retrigger with the trigger kind `TriggerForIncompleteCompletions`: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_completion

Maybe Zed is not supporting all of that or not implementing the spec correctly?

**Comment by jasonlyu123** [comment]
Not sure if it's strictly prohibited but trigger characters should be characters outside the typical characters. https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionOptions.

**Comment by AravindPrabhs** [comment]
Look at the RPC logs it comes back as complete e.g. {"jsonrpc":"2.0","id":16,"result":{"items":[],"isIncomplete":false}}
I guess because in the PluginHost you have
```typescript
 const completions = await Promise.all(this.plugins.map(async (plugin) => {
      const result = await this.tryExecutePlugin(plugin, 'getCompletions', [document, position, completionContext, cancellationToken], null);
      if (result) {
        return { result: result, plugin: plugin.__name };
      }
    })).then((completions) => completions.filter(utils_1.isNotNullOrUndefined));
```
where completions result in an empty array and so no plugin says the code is incomplete and so incomplete remains false. Looking at my plugins the only ones initialised are css, html and ts should there also be a JS one ?

**Comment by jasonlyu123** [comment]
`ts` also takes care of `js`. The problem should be the "y' trigger character. "y" isn't a trigger character. It should be `CompletionTriggerKind.Invoke` with a trigger character of undefined.

**Comment by AravindPrabhs** [comment]
thank you that help tracked down the bug and have submitted an issue to zed !
