### ISSUE TITLE
svelte-check reports warning for unary operation with reactive store

### ISSUE THREAD

**Issue by dkzlv** [sveltejs/language-tools#245]
**Describe the bug**
`svelte-check` reports a warning when using unary operation with a reactive store syntax.

**To Reproduce**
In my case `svelte-check` wasn't satisfied with this line:

```javascript
$: show404 = !ent && !$syncStatusStore;
```

I got the following error:

```
Warning - unrecognized UnaryExpression operator 53! 
                This is an edge case unaccounted for in svelte2tsx, please file an issue:
                https://github.com/sveltejs/language-tools/issues/new/choose
                 !$syncStatusStore
```

**Expected behavior**
No error or warning.

**System (please complete the following information):**
 - OS: Mac OS 10.15.3
 - IDE: VS Code
 - Plugin/Package: Svelte for VS Code ([the new official one](https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode))

**Comment by dummdidumm** [comment]
This is a false positive in [this if-clause](https://github.com/sveltejs/language-tools/blob/d1baf00b9ad1d17da2845c95bacaa51dcbddaafc/packages/svelte2tsx/src/svelte2tsx.ts#L118). `!$store` is an update-expression, too, but one which does not need special treatment, so the warning is wrong.
