### ISSUE TITLE
compilerOptions.warningFilter: triggers eslint errors

### ISSUE THREAD

**Issue by mustafa0x** [sveltejs/language-tools#2455]
In Svelte 5 you will be able to disable Svelte warnings through the new `warningFilter` compiler option:
```js
// svelte.config.js
export default {
  compilerOptions: {
    // disable all warnings coming from node_modules and all accessibility warnings
    warningFilter: (warning) => !warning.filename?.includes('node_modules') && !warning.code.startsWith('a11y')
  }
}
```

_Originally posted by @dummdidumm in https://github.com/sveltejs/language-tools/issues/650#issuecomment-2260462839_

---

this caused eslint to report `'$props' is not defined`

```js
    compilerOptions: {
        // disable specific accessibility warnings
        warningFilter: warning =>
            !warning.filename?.includes('node_modules') &&
            [
                'a11y_autofocus',
                'security_anchor_rel_noreferrer',
                'a11y_click_events_have_key_events',
                'a11y_no_static_element_interactions',
            ].includes(warning.code),
    },
```

**Comment by dummdidumm** [comment]
Please provide a reproduction repository

**Comment by mustafa0x** [comment]
https://github.com/mustafa0x/svkit-eslint-errors

```
$. pnpm exec eslint src

my-app/src/routes/+layout.svelte
  5:8   error  'a' is assigned a value but never used                         no-unused-vars
  5:13  error  '$props' is not defined                                        no-undef
  5:13  error  Cannot use rune without parentheses(rune_missing_parentheses)  svelte/valid-compile

✖ 3 problems (3 errors, 0 warnings)
```

and after removing `compilerOptions` from `svelte.config.js`, the `$props` error goes away.

**Comment by jasonlyu123** [comment]
This is an issue with [eslint-plugin-svelte](https://github.com/sveltejs/eslint-plugin-svelte). I can't transfer the issue so please reopen one in eslint-plugin-svelte and follow the issue template. The problem doesn't seem to be related to `warningFilter` but how the `compilerOptions` is handled. But it seems like the `warningFilter` is also being ignored even if it's configured in eslint.config.js. So you might need to open another feature request to support the `warningFilter` config.
