### ISSUE TITLE
Prevent major footgun with unstringifyable mustache tags

### ISSUE THREAD

**Issue by AlbertMarashi** [sveltejs/language-tools#2465]
### Description

The following is a major footgun and surface area for bugs.

```svelte
<script lang="ts">

let obj = { 
  a: bool
}
</script>
<a href="/foo/{obj}">...</a>
```
Will result in
```html
<a href="/foo/[object Object]">..</a>
```

Even in situations such as

```svelte
Hello { obj }
```
We get
```
Hello [object Object]
```

There's exactly zero times that I've desired this behavior & almost always a surface area for bugs when refactoring props, types and etc.

This can quite easily occur throughout projects during refactoring or even just developer oversight. We should prevent this from occurring.

I view this as a quite serious typing issue, with no easy apparent remedies.

### Proposed solution

Figuring out how to either
- prevent this from occurring through full-type information from linting tools
- making svelte2tsx / language tools capture these issues when using rules such as:
  - https://typescript-eslint.io/rules/restrict-template-expressions
  - https://typescript-eslint.io/rules/no-base-to-string

### Alternatives

Writing my own full-type information linter for svelte/sveltekit

**Comment by jasonlyu123** [comment]
I think you should focus on getting this in eslint. The check is brittle and can have a lot of false positives. So it should be configurable and "opt-in".

**Comment by AlbertMarashi** [comment]
> I think you should focus on getting this in eslint. The check is brittle and can have a lot of false positives. So it should be configurable and "opt-in".

This does exist in typescript-eslint in the various rules I mentioned, but for some reason the rules do not apply with Svelte mustache tags for whatever reason?

**Comment by dummdidumm** [comment]
We're not going to add such logic to language tools. It would either have to come from TypeScript (i.e. they add this as a new type check feature, and we automatically can make use of it then) or from the Svelte compiler (i.e. the compiler can analyze some common things).

That said, this is probably hard to ever get right completely, because you can't really know whether or not someone implemented a `toString` method.

**Comment by AlbertMarashi** [comment]
Sure, that makes sense.

On that note though:
> That said, this is probably hard to ever get right completely, because you can't really know whether or not someone implemented a toString method

This implements that desired behavior by using the type inference to determine whether a given type has a `.toString` and by default excludes the ones that result in stuff like `[object Object]`
https://typescript-eslint.io/rules/no-base-to-string/
