### ISSUE TITLE
Included override of `Process` type makes `svelte-check` fail

### ISSUE THREAD

**Issue by benmccann** [sveltejs/language-tools#2483]
### Describe the bug

I get the following with `svelte-check` version 4 in the SvelteKit repo:
```
====================================
Loading svelte-check in workspace: packages/kit/test/apps/embed
Getting Svelte diagnostics...

packages/kit/test/apps/embed/../../../../../node_modules/.pnpm/@types+node@18.19.48/node_modules/@types/node/globals.d.ts:43:9
Error: Subsequent variable declarations must have the same type.  Variable 'process' must be of type 'Process & { browser: boolean; }', but here has type 'Process'. 

    var process: NodeJS.Process;
    var console: Console;


packages/kit/test/apps/embed/../../../../../node_modules/.pnpm/@types+node@18.19.48/node_modules/@types/node/process.d.ts:5:13
Error: Subsequent variable declarations must have the same type.  Variable 'process' must be of type 'Process & { browser: boolean; }', but here has type 'Process'. 
    global {
        var process: NodeJS.Process;
        namespace NodeJS {


====================================
svelte-check found 2 errors and 0 warnings in 2 files
 ELIFECYCLE  Command failed with exit code 1.
````

This seems to be caused by code from this repo:
```
./node_modules/.pnpm/svelte-check@4.0.0_svelte@4.2.17_typescript@5.4.5/node_modules/svelte-check/dist/src/svelte-shims.d.ts:declare var process: NodeJS.Process & { browser: boolean }
./node_modules/.pnpm/svelte-check@4.0.0_svelte@4.2.17_typescript@5.4.5/node_modules/svelte-check/dist/src/svelte-shims-v4.d.ts:declare var process: NodeJS.Process & { browser: boolean }
./node_modules/.pnpm/svelte2tsx@0.7.6_svelte@4.2.17_typescript@5.4.5/node_modules/svelte2tsx/svelte-shims.d.ts:declare var process: NodeJS.Process & { browser: boolean }
./node_modules/.pnpm/svelte2tsx@0.7.6_svelte@4.2.17_typescript@5.4.5/node_modules/svelte2tsx/svelte-shims-v4.d.ts:declare var process: NodeJS.Process & { browser: boolean }
```

### Reproduction

See the branch https://github.com/sveltejs/kit/tree/svelte-check-4 from https://github.com/sveltejs/kit/pull/12646

### Expected behaviour

I can upgrade `svelte-check` to v4 without issue

### System Info

- OS: Linux
- IDE: N/A

### Which package is the issue about?

svelte-check

**Comment by dummdidumm** [comment]
This was always present (I never really noticed it until now, was added long before my time), I'm wondering why this fails now and did not earlier

**Comment by benmccann** [comment]
No, the Node types bump was a failed attempt at fixing the error. The error happens without that change

**Comment by jasonlyu123** [comment]
It's because `skipLibCheck` is forced before. We probably need to use declaration merging to enhance the type. 

```ts
declare namespace NodeJS {
	interface Process {
		browser: boolean
	}
}
```

Didn't catch this before otherwise I would want to remove it as part of breaking changes😅

**Comment by dummdidumm** [comment]
I'm pretty sure it's only there because of Svelte Native, and I'm totally fine with removing this in a bug fix, and retroactively add this as a breaking change

**Comment by jasonlyu123** [comment]
Seems like it's also a Webpack 4 thing. But this really doesn't seem to be needed in our shim file.
