### ISSUE TITLE
File output option

### ISSUE THREAD

**Issue by Cschlaefli** [sveltejs/language-tools#2487]
### Description

I'd like to be able to write the output the results of svelte-check run to a file during CI in order to allow [code climate reporting in gitlab](https://docs.gitlab.com/ee/ci/testing/code_quality.html)

### Proposed solution

Add a new --output option `gitlab`, and an associated FileWriter that writes to a json file with the gitlab format to the [writers](https://github.com/sveltejs/language-tools/blob/master/packages/svelte-check/src/writers.ts)

### Alternatives

Considered parsing the output of machine-verbose to a different format, but it'd be less work for me to just write the implementation into the svelte-check package.

### Additional Information, eg. Screenshots

Linking the [gitlab codeclimate ouput format](https://docs.gitlab.com/ee/ci/testing/code_quality.html#implement-a-custom-tool) for reference. 
May need to implement the fingerprinting property, but the rest of the information is basically there.

**Comment by dummdidumm** [comment]
Thank you for the suggestion, but we're not going to create another output format. The machine readable format is precisly so that you can then parse and format that into something else. Using shell commands it's also possible to write the result to disk. Therefore closing.
