### ISSUE TITLE
in imported array type variables, Invalid type infomation shown on hover, 

### ISSUE THREAD

**Issue by Dulanjala007** [sveltejs/language-tools#249]
when checking types via hover, imported array variable type shows up as object/any type
only in svelte script typescript tags 

// exported array variable
![Shot 0008](https://user-images.githubusercontent.com/16051361/86058201-22295080-ba7e-11ea-8dba-04008b03447b.png)

// imported in a normal ts file, and correct type showing on hover
![Shot 0010](https://user-images.githubusercontent.com/16051361/86058431-83512400-ba7e-11ea-86db-a6baa1935bbc.png)

// imported in a svelte typescript tag, and type showed as any
![Shot 0009](https://user-images.githubusercontent.com/16051361/86058311-50a72b80-ba7e-11ea-8d78-c5ead4db12f8.png)

**Comment by dummdidumm** [comment]
I cannot reproduce this. Could you specifiy the steps which reproduce it for you?

**Comment by Dulanjala007** [comment]
1. create a ts file which exports an array type variable.
2. import that variable in a svelte file, inside of a script tag (lang='ts')

when hovering over the imported variable, it should be like shown like this, no correct array type, just any...

![](https://user-images.githubusercontent.com/16051361/86058311-50a72b80-ba7e-11ea-8d78-c5ead4db12f8.png)

**Comment by Dulanjala007** [comment]
I
