### ISSUE TITLE
Bundled Svelte 4 types loaded in a Svelte 5 project and causing conflict

### ISSUE THREAD

**Issue by jethrolarson** [sveltejs/language-tools#2493]
### Describe the bug

See title and repro

Work around is to add the types to the callbacks manually but that skips typechecking so not ideal.

### Reproduction

```ts
  import { writable, type Writable } from 'svelte/store';
...
  let _curMessage: string;
  const currentMessage = writable<string>('');
  currentMessage.subscribe((cur) => (_curMessage = cur));
```

![image](https://github.com/user-attachments/assets/820092e7-6955-4b7a-9342-b6555cd03c57)

node_modules/svelte/src/store/shared/index.js:

![image](https://github.com/user-attachments/assets/00e0aaa0-3d1e-4c83-9678-ecddbd13df27)

### Logs

```shell
n/a vscode
```

### System Info

```shell
osx apple m1 Sonoma

VSCode
Version: 1.90.1 (Universal)
Commit: 611f9bfce64f25108829dd295f54a6894e87339d
Date: 2024-06-11T21:02:41.372Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 22.1.0
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
@jasonlyu123 do you have an idea why our bundled types are loaded? Is it because of our `d.ts` files in `svelte2tsx` which reference Svelte imports? I always had the impression that those are pointing back to the user's Svelte version.

**Comment by jasonlyu123** [comment]
It's like `require.resolve('svelte', '/path/to/shims.d.ts')` I think. Not sure if we can move the import to the generated code and pass it into the helper function as a parameter. Or if we could create a virtual module inside the user's node_modules to re-export from svelte.
