### ISSUE TITLE
"Unknown at rule @apply" when using Tailwind's directives only in SCSS styles

### ISSUE THREAD

**Issue by rklos** [sveltejs/language-tools#2497]
### Describe the bug

When I use Tailwind's directives in scss styles I get the "Unknown at rule @apply" warning in IDE and as a result of `svelte-check` command.
When I change the `lang` attribute of the style from `scss` to `sass` problem disappears.
In the end styles work in both cases, so the only problem is with the annoying warning.

Maybe related problem: https://github.com/sveltejs/language-tools/issues/1512.

### Reproduction

Warning with `scss` styles:
![CleanShot 2024-09-11 at 14 28 42](https://github.com/user-attachments/assets/a4bac84d-8e1a-400c-8c7a-5e872d6e592a)

No warning with `sass` styles:
![CleanShot 2024-09-11 at 14 13 54](https://github.com/user-attachments/assets/06297c4e-6ff7-4910-aff5-fb0cf03853d3)

`svelte.config.js`:
```js
import adapter from '@sveltejs/adapter-static';
import { sveltePreprocess } from 'svelte-preprocess';

/** @type {import('@sveltejs/kit').Config} */
const config = {
  preprocess: sveltePreprocess(),
  kit: {
    adapter: adapter(),
  },
};

export default config;
```

`tailwind.config.ts`:
```ts
import type { Config } from 'tailwindcss';

export default {
  content: [ './src/**/*.{html,js,svelte,ts}' ],
  theme: {
    extend: {},
  },
  plugins: [],
} as Config;
```

`postcss.config.js`:
```js
export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
```

### Expected behaviour

LSP and `svelte-check` should "see" tailwind's directives in components with `<style lang="scss"` as it is with `<style lang="sass"`.

### System Info

- OS: MacOS 14.6.1
- IDE: WebStorm 2024.2.1

### Which package is the issue about?

svelte-language-server, svelte-check

**Comment by jasonlyu123** [comment]
`apply` isn't standard scss. It's not supported by the upstream vscode-css-languageService. You'll have to either use `lang="postcss"`, where css diagnosis is skipped, or turn off css diagnostic completely.

https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/other-css-preprocessors.md#tailwindcss

**Comment by rklos** [comment]
@jasonlyu123 ok, but why sass works and why eg. Vue Language Server has no problem with Tailwind when you use scss?

**Comment by jasonlyu123** [comment]
Do you have the `css.customData` config? We could probably add the support for the config.

**Comment by rklos** [comment]
@jasonlyu123 I assume that you're talking about VSC config. Unluckily I'm using Webstorm and there is no possibility of such customisation.

**Comment by jasonlyu123** [comment]
A lot of our config is also implemented in the language server and also available in other editors. If we were to implement this. This would also be the case. Vue most likely also have this config. That would explain why it doesn't show the warning. If you didn't set it, It could also be possible that WebStorm has a different default for the config but that is out of our control, or maybe you're using the non-language-server version of vue support.

**Comment by tzezar** [comment]
is there any solution or workaround for this?
