### ISSUE TITLE
Autocomplete {#snippet _} when within a Component

### ISSUE THREAD

**Issue by pauldemarco** [sveltejs/language-tools#2499]
### Description

Here is a Component `Header` that takes a snippet `title` as a prop:
```ts
// Header.svelte
let {title}: {title: Snippet} = $props();
```
It is used like:
```svelte
<Header>
    {#snippet title()}
        ...
    {/snippet}
</Header>
```

### Proposed solution

It would be nice if the {#snippet _} could autocomplete for all snippets that the Component takes:

```svelte
<Header>
    {#snippet <Autocomplete shows all my snippet options>}
        ...
    {/snippet}
</Header>
```

**Comment by jasonlyu123** [comment]
There is autocomplete already but with a big caveat, it doesn't work when the name is empty because of https://github.com/sveltejs/language-tools/issues/1302#issuecomment-1002358234.
