### ISSUE TITLE
type of $state() initialized in constructor may be undefined

### ISSUE THREAD

**Issue by mrh1997** [sveltejs/language-tools#2501]
### Describe the bug

Typescript allows to initialize properties of objects during construction without getting their type being optionally undefined:

```typescript
class Cls {
   public prop: number;
   constructor() {
      this.prop = 3
   }
}
const neverUndefined: number = new Cls().prop;   // <- works as Cls().prop is of type "number"
```

But when prop is a $state() rune this is shown as error by the svelte language server:
```typescript
class Cls {
   public prop = $state<number>();
   constructor() {
      this.prop = 3
   }
}
const neverUndefined: number = new Cls().prop;   // <- is marked as invalid as Cls().prop might be of type "undefined"
```

### Reproduction

see above

### Expected behaviour

I expect that $state() is handled the same way as a normal variable: If it is initialized in the constructor it should be seen as non-undefined

### System Info

- OS: Windows 11
- IDE: PyCharm

### Which package is the issue about?

svelte-language-server, svelte-check

**Comment by dummdidumm** [comment]
This works as designed; if we were to make `$state<number>` return type `number`, you could forget to ever initialize it and get a runtime error. If you know what you're doing, you can do `$state<number>()!` or `$state() as number`.

Also see https://github.com/sveltejs/svelte/issues/12655
