### ISSUE TITLE
Type error: Expected 0 arguments, but got 1 on argument in children()

### ISSUE THREAD

**Issue by shinokada** [sveltejs/language-tools#2511]
### Describe the bug

Using VSCode with Svelte for VS Code and following the [doc](https://svelte-5-preview.vercel.app/docs/old-vs-new#passing-ui-content-to-a-component), I get "Expected 0 arguments, but got 1.". 

```
<!-- provider -->
<script lang="ts">
  import type { Snippet } from "svelte";
	let { children }: { children: Snippet } = $props();
</script>

<button>
	{@render children("some value")}
</button>
```

<img width="829" alt="image" src="https://github.com/user-attachments/assets/d95f78b2-78a5-482b-b04c-1ccee12d698a">

<img width="919" alt="image" src="https://github.com/user-attachments/assets/598ade61-9888-4fe3-8078-ea65b9c72dc0">

### Reproduction

The following code with using VSCode.

```
<!-- provider -->
<script lang="ts">
  import type { Snippet } from "svelte";
	let { children }: { children: Snippet } = $props();
</script>

<button>
	{@render children("some value")}
</button>
```

### Expected behaviour

It should not have any warning.

### System Info

- OS: macOS
- IDE: VS Code

### Which package is the issue about?

Svelte for VS Code extension

**Comment by jasonlyu123** [comment]
This is expected. `Snippet` meant `Snippet<[]>` which takes no argument what you want is `Snippet<[string]>` or `Snippet<[name: string]>`.

**Comment by shinokada** [comment]
Thank you for a quick reply.
