### ISSUE TITLE
Svelte 5: weird typescript behavior with component `bind:` attribute

### ISSUE THREAD

**Issue by KilDesu** [sveltejs/language-tools#2515]
### Describe the bug

After updating all packages versions, the `bind:` attribute behaves in a weird way.
Let's say you have a component generic `T extends string | number`, a component prop `value: T` and a variable `let variable = $state("hello")`.
If you try to `bind:value={variable}`, you get an error stating that `Type 'string | number' is not assignable to type 'string'. Type 'number' is not assignable to type 'string'.` even though if you hover over `value` in `bind:value={variable}` show that `value` has the type `string`.

### Reproduction

Easy reproduction:
- Clone [this repo](https://github.com/KilDesu/svelte5-bind-bug)
- Open the `src/routes/+page.svelte` file

More complex reproduction with additional error positioning bug:
- Clone [this repo](https://github.com/quaffui/quaff)
- Checkout to the `qlayout-refactors` branch
- Open the `src/routes/dev/+page.svelte` file

### Expected behaviour

No eslint errors

### System Info

- OS: MacOS and Windows
- IDE: VSCode

### Additional Information, eg. Screenshots

![error message](https://github.com/user-attachments/assets/b002c4b4-fe6a-4317-bd88-68fff1528472)
![inferred type of the value prop](https://github.com/user-attachments/assets/27306545-d5ba-4a35-b4fe-6bb9cf2d2550)

It gets even worse for more complex projects, the errors are not well positioned:
![weird error positioning](https://github.com/user-attachments/assets/f4ad17bd-7bc5-4dfd-84bc-61213e68d798)

**Comment by dummdidumm** [comment]
Probably related to #2494 / #2506 which are already fixed, release pending

**Comment by dummdidumm** [comment]
Closing as this is likely fixed in the latest version, please ping if that's not the case.
