### ISSUE TITLE
I need to restart svelte language server for autoimport to work in new svelte files

### ISSUE THREAD

**Issue by danielo515** [sveltejs/language-tools#2516]
### Describe the bug

When I create a new svelte component, using typescript as language, I always need to restart the svelte language server in order for automatic imports to work.
Previously it never happened, and just after the restart the automatic imports start to work again.

### Reproduction

1. Create a new svelte file
2. add a script of lang ts
3. type the name of a known typescript type/interface
4. you don't get autoimport suggestions, neither on code actions

### Expected behaviour

I want auto imports to work without having to restart svelte server.
I tried this with the minimum amount of extensions and the same problem happens.

### System Info

- OS: MAcOS
- IDE: VSCODE

**Comment by dummdidumm** [comment]
Possibly already fixed by #2488, release pending

**Comment by danielo515** [comment]
Can you please ping me when it is released?

**Comment by dummdidumm** [comment]
Released
