### ISSUE TITLE
<script module> seems to cause syntax-errors in svelteserver 0.17.0

### ISSUE THREAD

**Issue by merisbahti** [sveltejs/language-tools#2519]
### Describe the bug

After upgrading to latest svelte 5 beta, svelte-check is encouraging me to change my `<script context="module">` to `<script module>` but I get an error in my lsp
![image](https://github.com/user-attachments/assets/54fb0192-8d45-4e90-a918-240abd501d36)

### Reproduction

Using helix, with these settings:

```
[[language]]
name = "svelte"
language-servers = [ 
"svelteserver"
]
```

If I start with:
```svelte
<script context="module">
  export const contextKey = Symbol('stack-context');
</script>

<script lang="ts">
  console.log(contextKey);
</script>

<div>hello</div>
```

I get  no errors and it seems work file, but if I change it to `script module` like this:

```svelte
<script module>
  export const contextKey = Symbol('stack-context');
</script>

<script lang="ts">
  console.log(contextKey);
</script>

<div>hello</div>
```

the syntax breaks with lots of errors:
![image](https://github.com/user-attachments/assets/9cd2229f-e852-4dc4-9433-8c01c66da40d)

### Expected behaviour

I'd expect it to work just like `context="module"`

### System Info

- OS: Mac OS 15.0
- IDE: Helix (with svelteserver as lsp)

**Comment by jasonlyu123** [comment]
The language server is a node package. Can you try to remove its node_modules and reinstall it again? This sounds like your `svelte2tsx` is outdated.

**Comment by merisbahti** [comment]
Fixed by uninstalling `svelte-language-server` and then reinstalling it.
