### ISSUE TITLE
Svelte-check and VSCode extension errors regarding component types... How to declare them in Svelte 5?

### ISSUE THREAD

**Issue by charlie-roosen** [sveltejs/language-tools#2522]
Here is the way that I've been declaring components that I'm binding to a JavaScript reference via "bind:this":

```
<script lang="ts">
    import CloneWorkflowDialog from './dialogs/CloneWorkflowDialog.svelte';

   let cloneWorkflowDialog : CloneWorkflowDialog;   
</script>

<CloneWorkflowDialog bind:this={cloneWorkflowDialog}/>
```

With svelte-check 4.0.3, I'm getting new errors that are not flagged by 4.0.2:

```
c:\cr-bitbucket\RMP Platform Scala\w2e-svelte\svelteui\src\lib\components\workflow\WorkflowTitlePanel.svelte:102:30
Error: 'CloneWorkflowDialog' refers to a value, but is being used as a type here. Did you mean 'typeof CloneWorkflowDialog'? (ts)

   let cloneWorkflowDialog : CloneWorkflowDialog;
```

This is also being displayed as an error by "Svelte for VS Code" v109.0.2 and not by v108.6.1.

Is this a bug in the language tools, or has the idiom for declaring the types of components change?

**Comment by jrmajor** [comment]
It's probably related to #2517. I encountered a similar error and tried to add `typeof`, as suggested in the PR description, but got another error: `Type 'SvelteComponent<$$ComponentProps, { [evt: string]: CustomEvent<any>; }, {}> & { $$bindings?: "" | undefined; } & { setPhotoUri: (uri: string, source: string) => void; }' is not assignable to type '__sveltets_2_IsomorphicComponent<$$ComponentProps, { [evt: string]: CustomEvent<any>; }, {}, { setPhotoUri: (uri: string, source: string) => void; }, "">'`. In my case both components are using runes.

**Comment by wheeOs** [comment]
yep, I have the same issue. The VS Code extension complains, the check fails, but the app still runs and compiles

**Comment by wheeOs** [comment]
I did a rollback to `v109.0.1` for now, and keep it so until this gets fixed

**Comment by dummdidumm** [comment]
This works correctly. In Svelte 5, components are functions. The types reflect that, so the default export is a function now. To type "I expect an instance of this function", you now do this:

```diff
<script lang="ts">
    import CloneWorkflowDialog from './dialogs/CloneWorkflowDialog.svelte';

-   let cloneWorkflowDialog : CloneWorkflowDialog;
+   let cloneWorkflowDialog : ReturnType<typeof CloneWorkflowDialog>;
</script>

<CloneWorkflowDialog bind:this={cloneWorkflowDialog}/>
```

**Comment by bdmackie** [comment]
@dummdidumm they've been functions for most of the RC. Is it necessary for it to be that verbose? Sorry if this sounds ranty but this already felt tedious/noisy, especially when triggered by not being able to reference 'this' component, and this makes it even more boilerplatey IMO. At least glad I saw this as I was pulling my hair out why VS code went on fire with red squiggles after a version bump.

**Comment by ndom91** [comment]
@dummdidumm We just came across this issue in our project as well, and while it's great to have found the fix here. `svelte-check` still doesn't seem to be catching these, so what's causing errors in the editor via the LSP, is passing CI atm.

**Comment by PatrickG** [comment]
Is it possible for the language-tools to export the `typeof X` type as default? So that as a user you don't have to write it.
```ts
// virtual/transformed code for `SomeComponent.svelte`
function Component() { ... }
type Component = typeof Component;
export default Component;
```

```html
<script lang="ts">
  import SomeComponent from './SomeComponent.svelte';

  let instance: ReturnType<SomeComponent>;
  // or with https://github.com/sveltejs/svelte/pull/13441
  let instance: ComponentExports<SomeComponent>;
...
```

**Comment by dummdidumm** [comment]
I briefly thought about that, but the problem with that is that it would no work when you would declare the type by hand. And that could be very confusing ("why can I use the import as a type from a Svelte component, but if I declare a component using the `Component` type myself, I can't?")

**Comment by ptrxyz** [comment]
How does this work with generics? Consider this:

(1) A generic component like this:
```ts
<script lang="ts" generics="T extends { foo: string }">
    let { opt }: { opt: T } = $props()

    export function action(): T {
        // do stuff here
        return opt
    }
</script>
```

(2) Used like so:
```ts
<script lang="ts">
    import Comp from './comp.svelte'

    let instance: ReturnType<typeof Comp>

    const opt = {
        foo: 'bar',
        other: 1
    }

    function _callAction() {
        return instance.action().other    // this should not error if instance was properly typed.
    }
</script>

<Comp bind:this={instance} {opt}></Comp>
```

My problem is that I have no idea how to type `instance` to properly reflect that `opt` indeed has the `other` property. Somehow I have to add the generic parameter to `instance` to make it work, but I can't wrap my head around this to express it in Typescript.

Can anyone help?

**Comment by dummdidumm** [comment]
We're gonna implement the automatic `type Foo = ReturnType<typeof Foo>` trick within language tools so people don't run into this problem as often.

**Comment by newsve** [comment]
Skimmed the thread and apologies if I am wrong here but type checking broke from svelte 5.16 to 5.20.2, Or maybe I got something wrong.

I get following ts error: _Type 'Component<$$ComponentProps, {}, "">' does not satisfy the constraint 'SvelteComponent_1<any, any>'. Type 'Component<$$ComponentProps, {}, "">' is missing the following properties from type 'SvelteComponent_1<any, any>': $$, $$set, $destroy, $on, $setts(2344)_

on this line:
```ts
let compProps: Partial<ComponentProps<typeof SomeNormalComponentImport>> = {}
```
I tried to wrap `<typeof SomeNormalComponentImport>` with `ReturnType` but then I get: _Type '{ $on?(type: string, callback: (e: any) => void): () => void; $set?(props: Partial<$$ComponentProps>): void; }' does not satisfy the constraint 'SvelteComponent_1<any, any>'. Type '{ $on?(type: string, callback: (e: any) => void): () => void; $set?(props: Partial<$$ComponentProps>): void; }' is missing the following properties from type 'SvelteComponent_1<any, any>': $$, $$set, $destroyts(2344)_
