### ISSUE TITLE
Svelte 5: properly highlight `<component.dot.notation />`

### ISSUE THREAD

**Issue by dummdidumm** [sveltejs/language-tools#2525]
### Description

In Svelte 5 tags with a dot in it are counted as components. They should be highlighted as such from our textmate grammar.

### Proposed solution

adjust grammar

**Comment by paoloricciuti** [comment]
Uh this also reminded me: if you rename the symbol the component with dot notation is also left untouched.

```svelte
{#each components as component}
    <component.default />
{/each}
```

If I rename `component` `component.default` is not renamed, I don't know if fixing the grammar will also fix this
