### ISSUE TITLE
svelte-check reports errors on svelte-kit generated tsconfig.json

### ISSUE THREAD

**Issue by ProdanSergey** [sveltejs/language-tools#2532]
### Describe the bug

This spans over all versions since 4.0.0 and is not reproducible on 3.8.6 and lower.
The issue is reproducible both at local and CI (GitHub workflow).

### Prerequisites:

1. pnpm **v.9.10.0**
2. svelte-kit **v2.7.0**
3. typescript **v5.6.2**

### Log output:

> svelte-kit sync && svelte-check --tsconfig ./tsconfig.json

====================================
Loading svelte-check in workspace: /Users/...
Getting Svelte diagnostics...

/Users/.../.svelte-kit/tsconfig.json:33:3
Error: Unknown compiler option 'verbatimModuleSyntax'. 

/Users/.../.svelte-kit/tsconfig.json:40:23
Error: Argument for '--moduleResolution' option must be: 'node', 'classic', 'node16', 'nodenext'. 

### Config

~> .svelte-kit/tsconfig.json
```json
{
	"compilerOptions": {
		"paths": {
			"$lib": [
				"../src/lib"
			],
			"$lib/*": [
				"../src/lib/*"
			]
		},
		"rootDirs": [
			"..",
			"./types"
		],
		"verbatimModuleSyntax": true,
		"isolatedModules": true,
		"lib": [
			"esnext",
			"DOM",
			"DOM.Iterable"
		],
		"moduleResolution": "bundler",
		"module": "esnext",
		"noEmit": true,
		"target": "esnext"
	},
	"include": [
		"ambient.d.ts",
		"non-ambient.d.ts",
		"./types/**/$types.d.ts",
		"../vite.config.js",
		"../vite.config.ts",
		"../src/**/*.js",
		"../src/**/*.ts",
		"../src/**/*.svelte",
		"../tests/**/*.js",
		"../tests/**/*.ts",
		"../tests/**/*.svelte"
	],
	"exclude": [
		"../node_modules/**",
		"../src/service-worker.js",
		"../src/service-worker/**/*.js",
		"../src/service-worker.ts",
		"../src/service-worker/**/*.ts",
		"../src/service-worker.d.ts",
		"../src/service-worker/**/*.d.ts"
	]
}
```

~> ./tsconfig.json
```json
{
  "extends": "./.svelte-kit/tsconfig.json",
  "compilerOptions": {
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "strict": true,
    "allowJs": true,
    "checkJs": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  }
}
```

### Reproduction

1. install svelte-kit
2. install svelte-check >= v4
3. run: svelte-kit sync && svelte-check --tsconfig ./tsconfig.json
4. observe described error

### Expected behaviour

svelte-check v4.*.* does not report any error on svelte-kit generated tsconfig.json

### System Info

- OS: MacOS 15.0.1, Github Workflow
- IDE: VSCode

### Which package is the issue about?

svelte-check

**Comment by jasonlyu123** [comment]
Both `verbatimModuleSyntax` and `moduleResolution: bundler` were introduced in TypeScript 5.0. This sounds like you might have 2 different versions of TypeScript installed. SvelteKit sees TypeScript 5.6 so it generates tsconfig with new configs but svelte-check was using TypeScript 4.9 or older. 
Can you check if this is the case? If so, you'll need to fix that. You can try to uninstall svelte-check and install it again. Or remove node_modules and the lock file and reinstall everything. If this isn't the case, please provide a reproduction repository.

**Comment by ProdanSergey** [comment]
Good catch. This one for sure happened due to a monorepo setup. Thanks for providing support!
