### ISSUE TITLE
Css autocompletion is not working with some self-closing tags

### ISSUE THREAD

**Issue by madacol** [sveltejs/language-tools#254]
Issue Type: <b>Bug</b>

## Doesn't work
![image](https://user-images.githubusercontent.com/6379896/86189991-bd670800-bb08-11ea-805e-e0cb538a4f23.png)

## works
![image](https://user-images.githubusercontent.com/6379896/86190025-d53e8c00-bb08-11ea-9707-b18a453cea0b.png)

code:
```
<div>
    <i/>
</div>

<style>
    div {
        marg
    }
</style>
```

Extension version: 100.0.2
VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:08.304Z)
OS version: Linux x64 4.15.0-108-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3820 CPU @ 3.60GHz (8 x 3525)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.59GB (4.52GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by madacol** [comment]
Sorry, it seems `<i/>` is not standard html

It is not a **self closing tag**, so replacing with `<i></i>` works fine

**Comment by madacol** [comment]
Ok I just found another case.

There seems to be a general problem with some **self closing tags**

### Doesn't work
If the `Nested` component is rendered at the root level using **self closing tags**
![image](https://user-images.githubusercontent.com/6379896/86192295-d5da2100-bb0e-11ea-8a31-fa07addd6b8c.png)


### works
if the `Nested` component has a closing tag at root level, or is inside another html tag
![image](https://user-images.githubusercontent.com/6379896/86192480-4e40e200-bb0f-11ea-950f-3f5d1c511f05.png)

**Comment by dummdidumm** [comment]
The underlying issue is #194 , which is fixed on nightly builds already and will be deployed to prod soon.
