### ISSUE TITLE
Imports completion not always working since version 109.0.1

### ISSUE THREAD

**Issue by dennisvanderweide** [sveltejs/language-tools#2541]
### Describe the bug

In all versions >= 109.0.1 of the _Svelte for VS Code_ extension, I stopped getting suggestions for some imports.
Some packages still work while others never do. Sometimes for a brief moment after I reload my VS Code, I have some correct suggestions, but after this first time I always just get a "No suggestions.".

### Reproduction

I have a mono repo project with a SvelteKit app. This project runs in a Docker container using devcontainers.
When trying to import packages in a `.svelte` file, most of the time I get correct suggestions, but for some packages, in my case `@capacitor/haptics`, I don't. Other packages always work, this package never works.
After downgrading the _Svelte for VS Code_ extension to version <= 109.0.0 and restarting VS Code, I have no problems with imports anymore.

### Expected behaviour

I would expect imports to work for every package, just like they did before version 109.0.1.

### System Info

- OS: Linux 6.11.3 with Gnome 47 on Wayland
- IDE: VSCode 1.94.2 (problem is only on VS Code >= 1.82)
- Svelte for VS Code 109.1.0

### Which package is the issue about?

Svelte for VS Code extension

**Comment by jasonlyu123** [comment]
Can you provide a reproduction repository and more detail on what kind of import completion has the problem? I can't reproduce this.
![圖片](https://github.com/user-attachments/assets/1afbea73-dd2e-4f46-acf5-bdcfe1f56bfb)

**Comment by sebwib** [comment]
I have the same issue. Restarting svelte language server helps, for a while.
I can't provide a repo because it doesnt happen in small repos I have created. Can this be related to project size? Our project is very large
