### ISSUE TITLE
Formatting not working when {@render} is in document

### ISSUE THREAD

**Issue by sebwib** [sveltejs/language-tools#2542]
### Describe the bug

I use svelte 5.0.5, and the latest of all relevant packages.
I have selected "defaut formatter" to be Svelte for VS Code, version v109.1.0
If I create a +page.svelte file with this content:
```
<script lang="ts">
  let { children } = $props()
</script>

<div>
  <h1>
  </h1>
</div>
```

Then press save, it properly adds a ; to the end of the second line.
If I add this:
```
<script lang="ts">
  let { children } = $props()
</script>

<div>
  <h1>
    {@render children?.()}
  </h1>
</div>
```
It no longer adds the ;. Formatting fails when {@render children?.()} is included

### Reproduction

Described above

### Expected behaviour

Formatting should work when @render is used

### System Info

- OS: Mac OS
- IDE: VSCode

### Which package is the issue about?

Svelte for VS Code extension

**Comment by vincaslt** [comment]
Check https://github.com/sveltejs/language-tools/issues/2383 and https://github.com/sveltejs/language-tools/issues/2462#top

Basically, you'll need to update your `prettier` and `prettier-plugin-svelte` to latest versions, then create `.prettierrc` file in your root with:

```
{
  "plugins": ["prettier-plugin-svelte"],
  "overrides": [{ "files": "*.svelte", "options": { "parser": "svelte" } }]
}
```

**Comment by sebwib** [comment]
This did help, thank you!

I did find that issue but the link provided in that thread pointed to a 404
(https://github.com/sveltejs/kit/blob/main/packages/create-svelte/shared/%2Bprettier/.prettierrc)

This should be included in the official ReadMe on the homepage now that Svelte 5 is no longer a preview-package.
