### ISSUE TITLE
[BUG] IntelliSense fails with imported types using $props() - Svelte 5

### ISSUE THREAD

**Issue by roonie007** [sveltejs/language-tools#2549]
### Describe the bug

I've been experiencing a problem with IntelliSense when using Svelte's `$props` ( same problem on **VS Code** and **Webstorm** ).

When I import a type from `@nextui-org/theme` and use it as the props type for my component's attributes, IntelliSense doesn't work at all:

```svelte
<script lang="ts">
import type { ButtonVariantProps } from '@nextui-org/theme';

const someProps: ButtonVariantProps = $props();
</script>
```
![image](https://github.com/user-attachments/assets/b4ba3ab3-675d-4cc9-b7e8-c37203d43fa1)

---

If I extend it with a `Snippet`, for example, I only get the children prop:
```svelte
<script lang="ts">
import type { ButtonVariantProps } from '@nextui-org/theme';
import type { Snippet } from 'svelte';

interface Props extends ButtonVariantProps {
  children?: Snippet;
}

const someProps: Props = $props();
</script>
```

![image](https://github.com/user-attachments/assets/eb0e16e2-6f62-41db-bdb7-179e118a2655)

**But** when I start typing something for example **is** and press CTRL+Space to trigger the intellisense, it actually show the intellisense with words that contains **is**
![image](https://github.com/user-attachments/assets/72e81d30-27f3-4ee8-94de-53393b8e8b24)

---

However, if I just use one of its field types, it works:
```svelte
<script lang="ts">
import type { ButtonVariantProps } from '@nextui-org/theme';
import type { Snippet } from 'svelte';

interface Props {
  children?: Snippet;
  fullWidth?: ButtonVariantProps['fullWidth'];
}

const someProps: Props = $props();
</script>
```

![image](https://github.com/user-attachments/assets/3136e304-2103-4bca-8844-7626a70845ea)

---

I thought it might be a TypeScript issue, so I tried the non-working code in a simple TypeScript file, and everything works as expected:

![image](https://github.com/user-attachments/assets/c3b64f53-ad58-4d4f-bc19-6033bcba5c4f)

The fact that it's the same problem in VSCode and Webstorm, and it works with a simple typescript file, this leads me to believe the problem is specific to Svelte

### Reproduction

install the `@nextui-org/theme` module and create a component with the following code:
```svelte
<script lang="ts">
import type { ButtonVariantProps } from '@nextui-org/theme';

const someProps: ButtonVariantProps = $props();
</script>
```

Now try checking the attributes intelliSense when you use the component

### Expected behaviour

When using the component, IntelliSense should provide autocompletion and type suggestions based on the `ButtonVariantProps` type imported from `@nextui-org/theme`. All properties defined within `ButtonVariantProps` should be available in IntelliSense to enhance the development experience.

### System Info

```
  System:
    OS: Linux 5.15 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12600K
    Memory: 23.47 GB / 27.30 GB
    Container: Yes
    Shell: 5.2.21 - /bin/bash
  Binaries:
    Node: 22.9.0 - ~/.nvm/versions/node/v22.9.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v22.9.0/bin/yarn
    npm: 10.8.3 - ~/.nvm/versions/node/v22.9.0/bin/npm
    bun: 1.1.33 - ~/.bun/bin/bun
```

### Additional Information, eg. Screenshots

```
svelte: 5.0.0
typescript: 5.6.3
vite: 5.0.3
```

**Comment by garug** [comment]
Very good doc

**Comment by garug** [comment]
Very good doc, I noted `$props` works well on routing svelte components like `+page.svelte` but on isolated components on `$lib` no
