### ISSUE TITLE
Why is this line marked as error?

### ISSUE THREAD

**Issue by dm-de** [sveltejs/language-tools#2556]
### Describe the bug

```
<script>
	let { array = [] } = $props()
	let array2 = $derived(array.filter(i => !i.hidden))
</script>
```

In this short example, filter is marked red
'array' is of type 'unknown'.

For example, when I use next code in TS playground, it will not mark array or filter as error. Expected errors are $props() and i. But not arary or filter.

```
let { array = [] } = $props()
array.filter(i => !i.hidden) 
```

My configuration:
installed using Vite (fresh installation)
but not Svelte kit
just JS Svelte 5 (newest)
or even TS (no difference)
newest Svelte extension for VS code
newest VS Code update

Such error come up with Svelte 5 first (Svelte 4 show no errors).
I hoped all the time that this will be fixed with final v5.

I played with checkJS - or ts-nocheck.
But this will hide any error.

![sv3](https://github.com/user-attachments/assets/2ac1f8f7-1443-403d-8b91-2e4bd2477564)

### Reproduction

```
<script>
	let { array = [] } = $props()
	let array2 = $derived(array.filter(i => !i.hidden))
</script>
```

### Expected behaviour

no error

### System Info

- OS: Windows
- IDE: VSCode

### Which package is the issue about?

Svelte for VS Code extension

**Comment by dummdidumm** [comment]
You can't both strictly type check your code and expect no error in these positions. If you opt into more type checking, you have to provide the types, too. What we can do however is detect that you're creating an array-type fallback, and type that as `unknown[]`.

**Comment by dm-de** [comment]
is fixed now, but what can we do, to auto-remove such errors?

all properties of an array/object are unknown - but it is annoying
![sv5](https://github.com/user-attachments/assets/d118baad-f61b-4f3e-9557-59499581517d)

**Comment by dm-de** [comment]
I found other issue. This is not fixed:

![sv7](https://github.com/user-attachments/assets/9f1832f7-007b-4f06-9092-1db8bebb2bac)


```
<script>
	let {
		children,
	} = $props()
</script>

<div>
	{@render children?.()}
</div>
```


In my eyes, this line should also be error-free:

`{@render children()}`

**Comment by dm-de** [comment]
Here is another error. Possible same like previous.

![sv6](https://github.com/user-attachments/assets/337b831b-07b7-47de-af4c-abf8cd04024e)

I found one way to hide it with:
`ontoggle = ()=>{},`

Is it possible to make it error free without extra function?

**Comment by dm-de** [comment]
another classic example with error:

![sv8](https://github.com/user-attachments/assets/2eb0e0da-e44a-4fcd-9fd6-e7adcc57a34f)

**Comment by dm-de** [comment]
Is it OK, to post more of this here? Or should I open a new issue?
Next one is different that others.

{disabled} is marked wrongly.
Happen only with checkbox and only if here is bind:checked

Type 'unknown' is not assignable to type 'boolean'

![sv9](https://github.com/user-attachments/assets/8e60085b-5f7c-4b84-b5d1-c8f48a02bc16)

```
<script>
	let {
		disabled = false,
		value = $bindable(),
	} = $props()
</script>

<input
	type="checkbox"
	{disabled}
	bind:checked={value}
/>
```

**Comment by dm-de** [comment]
One more - object prop types not recognized

Type 'unknown' is not assignable to type 'string'

![sv10](https://github.com/user-attachments/assets/d050fcec-b7e9-45b6-bcbf-ce41722931da)

Parent:
```
<script>
	import Text from './t.svelte'
	let {
		i18 = {ok: 'OK', yes: 'Yes', no: 'No'},
	} = $props()
</script>
	
<Text text={i18.ok} />
```

Child:
```
<script>
	let { text = '' } = $props()
</script>

{text}
```

**Comment by dm-de** [comment]
one more with input FILE

Type '{}' is missing the following properties from type 'FileList': length, item,

![sv11](https://github.com/user-attachments/assets/5994cf4b-9794-44eb-b3bf-5983c84943f6)

```
<script>
	let {
		value = $bindable(),
	} = $props()
</script>


<input
	bind:files={value}
	type="file"
/>
```

**Comment by dm-de** [comment]
Big thanks to dummdidumm.
Svelte 5 is fun again.

I tested with 233 components.
No more errors. All above is fixed.
I close it. If I find something new, I will open new issue.
