### ISSUE TITLE
Svelte + Typescript: error on missing optional props

### ISSUE THREAD

**Issue by istudyatuni** [sveltejs/language-tools#2558]
### Describe the bug

When I write type for props, and later add default value for some fields, language server shows error

```
Property 's' is missing in type '{}' but required in type 'Props'
```

### Reproduction

Test.svelte:
```svelte
<script lang="ts" module>
    interface Props {
        s: string
    }
</script>

<script lang="ts">
    let { s = "a" }: Props = $props()
</script>

<div>{s}</div>

<style lang="scss"></style>
```

App.svelte:
```svelte
<script module>
	import Test from './Test.svelte'
</script>

<Test />
 ^^^^ error here

<style>
</style>
```

### Expected behaviour

No error

### System Info

- OS: NixOS
- IDE: Sublime Text + LSP + [LSP-svelte](https://github.com/sublimelsp/LSP-svelte)

### Which package is the issue about?

svelte-language-server

### Additional Information, eg. Screenshots

Compile is fine

**Comment by MotionlessTrain** [comment]
You need to mark it optional in the Prop interface. That is currently telling svelte that `s` is required

**Comment by istudyatuni** [comment]
Hmm, so I have to manually track of whether I forgot to set default value for optional prop. Sad

**Comment by dummdidumm** [comment]
As pointed out, this works as expected, the solution is to make `s` optional, i.e. `s?: string`
