### ISSUE TITLE
Config file for svelte-check

### ISSUE THREAD

**Issue by ptrxyz** [sveltejs/language-tools#2559]
### Description

Svelte check offers a few settings like settings a tsconfig file or ignoring error messages. Currently it is only possible to set those using the command line switches.

I suggest that svelte-check also looks for a config file in the workspace root for the following reason:
svelte-check is run by several tools, i.e. on the VSCode extension and the language server or ESlint when using the `svelte/valid-compile` rules. In addition, people use svelte-check in CI/CD workflows and run it manually using npx/npm or via scripts in the package.json.

If I would like certain warnings to always be disabled, I have to configure each tool individually -- this causes quite some overhead and sometimes is not even possible (i.e. ESlint's rule does not provide a way to ignore only some warnings, but only either ignore everything or nothing).

### Proposed solution

I suggest that svelte-check also looks for a file, let's say `svelte-check.config.json` or maybe a setting in `svelte.config.[cjs|mjs|ts]` that makes it possible to enable certain commonly used settings.
something like this would work:

```json
{
  "tsconfig": "./tsconfig.json"
  "compiler-warnings": {
    "a11y-label": "ignore"
  },
  ...
}
```

The schema could follow the schema from the `sv` CLI tool and we could load the before any manually passed config options are evaluated so that those take priority for backwards compatibility.

Loading order would be: default values --> load file if present --> overwrite with options manually passed to svelte-check.

### Alternatives

Maybe we could make the most important settings available through ENV variables like so:
```
SVELTE_CHECK_TSCONFIG="./tsconfig.json"
SVELTE_CHECK_COMPILER_WARNINGS="foo:ignore,bar:ignore"
SVELTE_CHECK_FAIL_ON_WARNINGS="true"
```

### Additional Information, eg. Screenshots

Just to outline the extend of the issue in a simple case:
To disable a single warning, you currently would do this:
- add a filter in your `svelte.config.js`
```js 
		warningFilter(w) {
			if (w.code.includes('foo')) return false
			if (w.code.includes('bar')) return false
			return true
		},
```

- edit `package.json` > `scripts` > `check` to include `--compiler-warnings "foo:ignore,bar:ignore"`
- remember when you run `sv check` manually, to also add all your rules: `--compiler-warnings "foo:ignore,bar:ignore"`
- open VS Code extensions -> workspace settings -> compiler options; edit all the warnings one-by-one.
![image](https://github.com/user-attachments/assets/6bb4e702-9cb8-467c-acb9-3a936bb4afea)
- if you have separate CI/CD configs, rinse and repeat...

**Comment by jasonlyu123** [comment]
`warningFilter` _is_ meant to be a way to unified suppress warnings. And svelte-check also supports this. You don't need to use `compiler-warnings` if you already filter it out in `warningFIilter`. For ESLint, ESLint doesn't run svelte-check under the hood. The warning is from the compiler itself. ESLint-plugin-svelte doesn't seem to support warningFIlter so you might have to open an issue there. But It does support the `onwarn` for vite-plugin-svelte with some extra config so it should be possible for eslint to support it. 

As for `--tsconfig` and `--fail-on-warnings`, these are not available in the language server so there isn't anything to reuse.

**Comment by ptrxyz** [comment]
I opened https://github.com/sveltejs/eslint-plugin-svelte/issues/905

btw, the `onwarn`-way of suppressing warning does not work anymore.

**Comment by dummdidumm** [comment]
You're correct - eslint is the only one left to support this compiler option, therefore closing
