### ISSUE TITLE
How to turn off lint error for unocss presetAttributify?

### ISSUE THREAD

**Issue by HuakunShen** [sveltejs/language-tools#2567]
![image](https://github.com/user-attachments/assets/37998437-86d5-4441-8e15-14e8143728d7)

I am trying to use unocss presetAttributify which uses tag attributes to set styling.
But the svelte extension always complain about it.
Is there a way to bypass the lint error?
Is the linting done with eslint and how to turn it off?

**Comment by jasonlyu123** [comment]
Put this in a ts/d.ts file in your project to enhance the type. (The example on their documentation is wrong 😅)

```ts
import type { AttributifyAttributes } from '@unocss/preset-attributify'

declare module 'svelte/elements' {
    interface HTMLAttributes<T> extends AttributifyAttributes {}
}
``

**Comment by HuakunShen** [comment]
Still
![image](https://github.com/user-attachments/assets/3b033317-ca89-4fb2-b8d6-58ff70004db9)

**Comment by jasonlyu123** [comment]
It should be included by your tsconfig.json so in the src directory.

**Comment by HuakunShen** [comment]
@jasonlyu123 Thank you so much! It's not complaining any more.
