### ISSUE TITLE
> ### Describe the bug

### ISSUE THREAD

**Issue by Rock1raw** [sveltejs/language-tools#2568]
> ### Describe the bug
> Hello, is this not possible in Svelte? Seems like the compiler is having a meltdown
> 
> ```ts
> import _Button from './Button.svelte';
> import ButtonLink from './ButtonLink.svelte';
> 
> const Button = Object.assign(_Button, {
>     Link: ButtonLink,
> });
> 
> export { UserButton };
> ```
> 
> Im getting this `d.ts` error when building in library mode
> 
> ```shell
> > svelte-clerk@0.1.10 package
> > svelte-kit sync && svelte-package && publint
> 
> d.ts type declaration files for the following files were likely not generated due to the following errors:
> /tmp/my-lib/src/lib/components/Button/index.ts
>   - Exported variable 'Button' has or is using name '$$__sveltets_2_IsomorphicComponent' from external module "/tmp/my-lib/src/lib/components/Button/Button.svelte" but cannot be named.
>   - Exported variable 'Button' has or is using name '$$__sveltets_2_IsomorphicComponent' from external module "/tmp/my-lib/src/lib/components/Button/ButtonLink.svelte" but cannot be named
> src/lib -> dist
> @sveltejs/package found the following issues while packaging your library:
> You are using SvelteKit-specific imports in your code, but you have not declared a dependency on `@sveltejs/kit` in your `package.json`. Add it to your `dependencies` or `peerDependencies`.
> ```
> 
> Sample usage in Svelte:
> 
> ```svelte
> <script>
> import { Button } from 'my-lib'
> </script>
> 
> <Button>
>     <Button.Link href="/somewhere" />
> </Button>
> ```
> 
> ### Reproduction
> 1. Create a SvelteKit app in library mode
> 2. Re-export a component like:
> 
> ```ts
> import Button from './Button.svelte';
> 
> export const RenamedButton = Button;
> ```
> 
>  3. Run `npm run build` and see the console output error about `d.ts`
> 
> ### Logs
> _No response_
> 
> ### System Info
> ```shell
> System:
>     OS: macOS 14.5
>     CPU: (10) arm64 Apple M1 Pro
>     Memory: 110.84 MB / 16.00 GB
>     Shell: 5.9 - /bin/zsh
>   Binaries:
>     Node: 20.17.0 - ~/.local/state/fnm_multishells/40146_1728685539617/bin/node
>     npm: 10.8.2 - ~/.local/state/fnm_multishells/40146_1728685539617/bin/npm
>     pnpm: 9.12.0 - /opt/homebrew/bin/pnpm
>     bun: 1.1.30 - ~/.bun/bin/bun
>   Browsers:
>     Chrome: 129.0.6668.100
>     Safari: 17.5
>   npmPackages:
>     svelte: ^5.0.0-next.262 => 5.0.0-next.262
> ```
> 
> ### Severity
> annoyance

_Originally posted by @Rock1raw in https://github.com/sveltejs/language-tools/issues/2536#issuecomment-2450218865_

**Comment by jasonlyu123** [comment]
We'll get to it please be patient.
