### ISSUE TITLE
CSS autocomplete/intellisense not working in Sapper routes folder

### ISSUE THREAD

**Issue by ignatiusmb** [sveltejs/language-tools#257]
**Describe the bug**
There's no CSS intellisense or autocomplete in the `<style>` tag in `routes` folder for Sapper project. It works for svelte files inside `components` folder.

**To Reproduce**
- degit a Sapper project
- type any CSS code in `.svelte` files inside `routes` folder
For example a code snippet that is treated in a way you don't expect.

**Expected behavior**
Expected to have basic CSS intellisense for route pages/files.

**Screenshots**
Inside routes
![image](https://user-images.githubusercontent.com/8156777/86225906-12f8ee80-bbb5-11ea-9bc6-b791806c0a7c.png)

Inside folders other than routes
![image](https://user-images.githubusercontent.com/8156777/86226026-4176c980-bbb5-11ea-8065-3821db2247e2.png)

**System (please complete the following information):**
 - OS: Windows 10
 - IDE: VSCode
 - Plugin/Package: "Svelte for VSCode"

**Additional context**

**Comment by dummdidumm** [comment]
Could you please share the whole code where the autocompletion does not work, or a minimum reproducible snippet?

Possibly related: #254 
Which version of Svelte for VSCode do you have installed? Latest is 100.1.0, which might have a fix for this.

**Comment by ignatiusmb** [comment]
100.1.0 fixed this! It was released an hour ago so it's not yet updated automatically, I'll close this then. Thanks for the awesome work!

---

I don't know if a snippet could help because it affects all the svelte files inside `routes` folder but not the other folders in `src`. Here's the layout, all svelte files works except those in `routes`.
![image](https://user-images.githubusercontent.com/8156777/86228182-48eba200-bbb8-11ea-8949-d6d571a1b39d.png)
