### ISSUE TITLE
svelte 5 props not recogonised by vscode

### ISSUE THREAD

**Issue by vishnuc** [sveltejs/language-tools#2581]
### Describe the bug

Why is that even though i have installed everything props are giving error in vscode.. but output is fine in browser. I dont want to use typescript.
 
<img width="1097" alt="Screenshot 2024-11-12 at 1 56 02 AM" src="https://github.com/user-attachments/assets/8d2c529d-7e73-4037-b2b5-a9c3ac49e126">

### Reproduction

Just trying to use let { data, header, row } = $props(); from parent

### Expected behaviour

no error 

### System Info

mac , vscode

**Comment by jasonlyu123** [comment]
There is a `checkJs` config in your tsconfig.json/jsconfig.json. If you don't want type-checking, turn it off. Next time you create a project, choose the no type check option, not the JSDoc option.

**Comment by vishnuc** [comment]
But doing that disable all errors , even below code is being without any error , even though buttonx does not exist.

<script>
	let { button, content } = $props();
</script>

{@render buttonx()}

**Comment by jasonlyu123** [comment]
If you want Typescript to check if the props exist, you type the whole props. https://svelte.dev/docs/svelte/typescript#Typing-$props. Or you can use eslint https://github.com/sveltejs/eslint-plugin-svelte.

**Comment by vishnuc** [comment]
No , I mean I dont want typescript to check , just basic javascript check . Any way below code is working fine , if people dont use typescript , give basic checks.

```
<script>
	let { button = () => {}, content = () => {} } = $props();
</script>

{@render button()}
{@render content()}

```
above code works fine , and below code show error correctly without any type check 

<img width="481" alt="Screenshot 2024-11-12 at 12 43 57 PM" src="https://github.com/user-attachments/assets/5403a617-75fe-4305-bea6-3217f0dfdbe7">

**Comment by jasonlyu123** [comment]
As I said. If you don't know typescript but want a linter to help you find undefined variables. Use ESLint. We're not going to reinvent the wheel. ESLint has a wide range of configurable options, you can tweak it to whatever levels of "basic checking" you want.
