### ISSUE TITLE
Cannot find name 'svelteHTML' / Cannot find name '__sveltets_2_any', ....

### ISSUE THREAD

**Issue by mysolo** [sveltejs/language-tools#2584]
### Describe the bug

bug on a version 109.2.2 , 109.2.1. 
no bug on a version 109.2.0 

use "svelte": "3.52.0" in a project.

VSCode return a multiple error on a 
<div> => Cannot find name 'svelteHTML' 
on a each => Cannot find name '__sveltets_2_ensureArray'
on a component =>  Cannot find name '__sveltets_2_any'

etc...

### Reproduction

simple <div></div>

<img width="178" alt="Screenshot 2024-11-13 at 15 59 21" src="https://github.com/user-attachments/assets/53779250-2d43-45ca-82d8-2fe06e7dd039">
<img width="318" alt="Screenshot 2024-11-13 at 15 59 29" src="https://github.com/user-attachments/assets/12a23883-f8a1-434f-8dd1-4432949ee7aa">

### Expected behaviour

No error on a code

### System Info

- OS: Mac os X
- IDE: VSCode Version: 1.95.2
- Svelte for VS Code v109.2.2

### Which package is the issue about?

Svelte for VS Code extension, svelte-language-server

**Comment by dummdidumm** [comment]
I am unable to reproduce this. Please provide a reproduction repository.

**Comment by mysolo** [comment]
[git@github.com:mysolo/vsc-svelte-debug.git](url)

I replace version for svelte/sveltekit/typescript.

clone repos
cd repos
vsc .

open page.svelte

**Comment by anders-hard** [comment]
I also got this after some upgrade sometimes over the last week
<img width="317" alt="image" src="https://github.com/user-attachments/assets/72c021a2-2982-444c-96ef-eb61a1dc96ac">

**Comment by dummdidumm** [comment]
I am unable to reproduce this. Wondering if this is OS-dependent; I'm on Windows.

I suspect this came in as a result of #2561. Can you check whether or not there's a `.svelte2tsx-language-server-files` folder inside your `node_modules`, and if yes what files it contains, and if there are some what their contents are?

**Comment by anders-hard** [comment]
Yes, I have three files. The svelte-html.d.ts is empty, the others are not.

<img width="285" alt="image" src="https://github.com/user-attachments/assets/7e683d53-8b88-4f93-bd06-4c9545b27cf4">

**Comment by anders-hard** [comment]
I managed to get rid of the error by removing the node_modules folder, upgrading svelte and re-installing node modules. That removes the `svelte-html.d.ts file` (it would re-create if I deleted it before).

**Comment by dummdidumm** [comment]
I was able to reproduce this for the early Svelte 4 versions and fixed the bug related to that. Still not able to reproduce this for Svelte 3, but added some extra checks. @mysolo could you try with the latest version of the extension?

**Comment by mysolo** [comment]
> @mysolo could you try with the latest version of the extension?

I still have the problem with version 109.2.3

**Comment by mysolo** [comment]
> I am unable to reproduce this. Wondering if this is OS-dependent; I'm on Windows.
> 
> I suspect this came in as a result of #2561. Can you check
> 
>     * whether or not there's a `.svelte2tsx-language-server-files` folder inside your `node_modules`?
> 
 yes 

>     * if yes what files does it contain?

ls -al  node_modules/.svelte2tsx-language-server-files                                                                                                                                                                                                                                                                                                   git:(feat/posthog|…12⚑13 
total 168
drwxr-xr-x   5 mysolo  staff    160 Nov  9 01:39 .
drwxr-xr-x  82 mysolo  staff   2624 Nov  9 01:39 ..
-rw-r--r--   1 mysolo  staff  64575 Nov 15 15:29 svelte-jsx.d.ts
-rw-r--r--   1 mysolo  staff    964 Nov  9 01:39 svelte-native-jsx.d.ts
-rw-r--r--   1 mysolo  staff  14526 Nov 15 15:29 svelte-shims.d.ts

>     * if yes what are the file contents? (they should _not_ be empty)
they not be empty

**Comment by dummdidumm** [comment]
This is truly strange. This means they are properly copied over into the hidden folder, but then not actually loaded or picked up, for whatever reason. I'm not sure how to investigate this further. @jasonlyu123 do you have any ideas how to help @mysolo debug this / any ideas why this could happen?

**Comment by dummdidumm** [comment]
@reskume mentioned this happens on case sensitive file systems, which may hint at what the problem is

**Comment by jasonlyu123** [comment]
So it might be something to do with inconsistent case sensitivity handling. Is the extension installed in the case-insensitive part of the system, while the project directory is in the case-sensitive part? But why is the write file work but read file doesn't? And why isn't that affecting normal files in the project?

@mysolo, can you confirm if you formatted part of your file system as case-sensitive? Though we are still not sure how this happened at least we can confirm if it's the same issue.

**Comment by mysolo** [comment]
> @mysolo, can you confirm if you formatted part of your file system as case-sensitive? Though we are still not sure how this happened at least we can confirm if it's the same issue.

yes, all my dev projects are on a case-sensitive partition. Applications are on the standard os x partition.

**Comment by dummdidumm** [comment]
@mysolo  / @reskume can you check if this still happens with the latest version of the extension?

**Comment by reskume** [comment]
I can confirm that in VSCode with extension Svelte v109.3.0 this has been
resolved. Thanks a lot!

Am Fr., 22. Nov. 2024 um 19:26 Uhr schrieb Simon H ***@***.***

**Comment by mysolo** [comment]
it's ok for me :)

**Comment by Alex6357** [comment]
I still encountered this issue with extension v109.5.2, but it was resolved after restarting VSCode. Just a report.

**Comment by blaine** [comment]
I've also seen this issue intermittently. Restarting the Svelte language server seems to resolve the issue, but it seems to creep back. I've only noticed this in a svelte 5 project, not in my legacy svelte 4 projects.

**Comment by Oliver-Piorun** [comment]
Can confirm. The issue still exists 👍

**Comment by dummdidumm** [comment]
Please provide a reproduction repository along with steps how to reproduce

**Comment by Oliver-Piorun** [comment]
So today:

- Opened the project -> No error
- Deleted the `node_modules` folder and the `pnpm-lock.yaml` file
- Ran `pnpm install`
- Navigated to a `*.svelte` file
- Mentioned error is back again
  - The `.svelte2tsx-language-service-files` folder is missing

-> Restarting the Svelte LSP fixed this particular issue. It kicked in and created the mentioned folder.

^ Is this by design? If yes: I would love to not having to restart the LSP/VSCode when performing the mentioned steps.

I am not sure if this issue is related to the ones we observed in the past.


Thanks for your help 😊

**Comment by jasonlyu123** [comment]
I would recommend you always close the editor before deleting and reinstalling. There are all sorts of things that might get cached in different extensions. If you're reinstalling you obviously don't want some cache not being invalidated. It also doesn't make sense to trigger lots of file-watcher events in a short time reflecting changes that might be a total waste of time and might even slow down the reinstalling.

**Comment by wonderkid-web** [comment]
just close and reopen your vscode dude,

**Comment by ceifa** [comment]
This error is still happening when trying to run svelte-check with --tsgo and --incremental.

**Comment by jasonlyu123** [comment]
@ceifa please open a new issue with a reproduction.

**Comment by mattpilott** [comment]
I get this issue `Cannot find name 'svelteHTML'.` when i run `rm -rf node_modules` in cursor, and I have to run `svelte: Restart Svelte Language Server` to fix it
