### ISSUE TITLE
`{#snippet}` is treated the same as `{@render}`

### ISSUE THREAD

**Issue by huntabyte** [sveltejs/language-tools#2587]
### Describe the bug

When a snippet has required props, I expect TypeScript to warn me if I attempt to `{@render MySnippet()}` without the required props. However, when consuming a snippet provided by a parent component, I shouldn't need to destructure every snippet prop.

Here's an example of a snippet provided by the parent component which includes the following structure:

```ts
type SnippetProps = {
	props: Record<string, unknown>
	open: boolean
}
```

![CleanShot 2024-11-14 at 11 49 07@2x](https://github.com/user-attachments/assets/97d17751-9551-4f4c-a060-c8f61b220616)

TypeScript is telling me I need to pull out `open`, which doesn't make any sense considering I am consuming the snippet rather than invoking it via `@render`.

When I pull all the required props out, the error goes away:

![CleanShot 2024-11-14 at 11 51 22@2x](https://github.com/user-attachments/assets/9cbf4c70-85da-4366-a87f-37e2547ecd1b)

### Reproduction

```svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	let { child }: { child: Snippet<[{ props: Record<string, unknown>; open: boolean }]> = $props()


	let open = $state(false)
	let myProps = $state({})
</script>

<div>
	{@render child({ props: myProps, open })}
</div>
```

And then consume that component

### Expected behaviour

I would expect it to require me to provide the required snippet props only when using the snippet with `{@render}` and not with `{#snippet}`.

### System Info

- OS: Mac
- IDE: VSCode

### Which package is the issue about?

svelte2tsx, svelte-check

**Comment by dummdidumm** [comment]
I don't fully understand the problem. Could you provide the code snippet that uses the component in a way that errors? I'm not able to make it error.

**Comment by huntabyte** [comment]
After updating all the deps I'm unable to reproduce it anymore either. I probably had some mismatched versions of check->svelte->etc.
