### ISSUE TITLE
Regression on VSCode Ext v109.2.3

### ISSUE THREAD

**Issue by huntabyte** [sveltejs/language-tools#2589]
### Describe the bug

After updating to the latest Svelte for VSCode extension (v109.2.3), generic types are broken.

Here's a video of the issue I'm experiencing with the latest version. It goes away when I downgrade.

https://github.com/user-attachments/assets/9f9cac81-65e0-4ba2-803a-4b8718adc7c0

More minimal reproduction than that linked below.

### Reproduction

https://github.com/huntabyte/svelte-vscode-generics

Clone the repo, ensure you're running the latest version of the extension, check `component.svelte`.

Downgrade the extension and observe the errors go away.

### Expected behaviour

Expect it to work the same as it does in v109.2.2

### System Info

- OS: Mac
- IDE: VSCode

### Which package is the issue about?

Svelte for VS Code extension

**Comment by dummdidumm** [comment]
Likely because of  #2571

**Comment by huntabyte** [comment]
While we're on the topic of discussions, is it on the roadmap to eventually not _have_ to explicitly declare the

```ts
type T = unknown
type U = unknown
```

In the `module` script tag for TS to properly recognize that these types do exist and that they're generic or is this a strict limitation of the language tools?

**Comment by dummdidumm** [comment]
What do you mean by that? This shouldn't be necessary - infact, it's what's causing this bug to appear. If you remove it, your code will work fine (there's still a bug though we need to fix)

**Comment by huntabyte** [comment]
Ah it's actually an eslint rule `eslint(no-undef)` that throws a fit about it!
