### ISSUE TITLE
Auto import produces a warning

### ISSUE THREAD

**Issue by sacrosanctic** [sveltejs/language-tools#2603]
### Describe the bug

There's a typescript type error when I use `browser` in a `.svelte` file's template:

```svelte
<p>{browser.runtime.id}</p>
```

```sh
$ pnpm svelte-check

====================================
Loading svelte-check in workspace: /Users/aklinker1/Development/local/wxt-issue-911
Getting Svelte diagnostics...

/Users/aklinker1/Development/local/wxt-issue-911/src/entrypoints/popup/App.svelte:6:5
Warn: 'browser' is not defined (svelte)

<p>{browser.runtime.id}</p>
<main>
====================================
svelte-check found 0 errors and 1 warning in 1 file
```

### Reproduction

[repro.zip](https://github.com/user-attachments/files/16599723/repro.zip)

### Steps to reproduce

```sh
pnpm i
pnpm svelte-check
```

### System Info

- OS: Windows
- IDE: VSCode

### Additional Information, eg. Screenshots

I am forwarding this issue from https://github.com/wxt-dev/wxt/issues/911

**Comment by dummdidumm** [comment]
This is a known limitation of the Svelte 4 compiler which tries to be helpful by spitting out warnings for globals it doesn't know about. The solution is to either upgrade to Svelte 5 which doesn't so this anymore, or to ignore it via `--compiler-warnings ` (explained in the readme in https://www.npmjs.com/package/svelte-check)
