### ISSUE TITLE
Script tag in string breaks highlighting

### ISSUE THREAD

**Issue by cnolte** [sveltejs/language-tools#2625]
### Describe the bug

Syntax highlighting breaks when I use a script tag in a string. Svelte itself still works as expected. I'm writing a library and want to use example code in the docs.

### Reproduction

```html
<script lang="ts">
	const foo = "<script>let foo = 'bla'</script>";
</script>
```

### Expected behaviour

String is not parsed by syntax highlighter

### System Info

- OS: Mac
- IDE: VSCode

**Comment by jasonlyu123** [comment]
I am not sure if I understand your problem correctly because this **should not** work. Script parsing will take the first `</script>` tag as the end. You have to use string concat or escape. See https://github.com/sveltejs/svelte/issues/3039. 

The syntax highlights on GitHub are correct. The VSCode one might be wrong, but there isn't much we can do because TextMate grammar can be quite limited.

**Comment by cnolte** [comment]
But even outside <script> it doesn't work e.g.:
```html
<script>
let foo=0;
</script>
<Code value={`<script>const demo = $state()</script>`} />
```

Escaping leads to a eslint error: Unnecessary escape character

**Comment by jasonlyu123** [comment]
> But even outside <script> it doesn't work 

Can you elaborate on what you expect and what doesn't work? Is there any error message or the outcome isn't what you want?

**Comment by cnolte** [comment]
I use a Code component to format strings similar like markdown to formatted code. You can see it running here: https://noph.dev/components/snackbar . A simplified example:

```html
<script lang="ts">
	import Code from '../../Code.svelte'
</script>

<Code value={`<script>const demo = $state()</script>`} />
```

This runs in the browser but the highlighter throws the error: Cannot find name 'script'. If I escape the script tag Eslint throws the error: Unnecessary escape character.

**Comment by jasonlyu123** [comment]
What highlighter? Can you take a screenshot?

**Comment by cnolte** [comment]
<img width="751" alt="Bildschirmfoto 2024-12-10 um 08 21 25" src="https://github.com/user-attachments/assets/3cc9446c-2e6a-4755-a2c0-c88d424e0521">
<img width="736" alt="Bildschirmfoto 2024-12-10 um 08 21 55" src="https://github.com/user-attachments/assets/d39b82f7-4714-4025-9d86-cc6e16ff69b4">

**Comment by dummdidumm** [comment]
Make sure to escape the closing tag, this is a general/known HTML spec weirdness, where the opening/closing tag is taken literally, no matter where its put.

So to fix it do something like this
```svelte
<script>
let foo=0;
</script>
<Code value={`<script>const demo = $state()</` + `script>`} />
```
