### ISSUE TITLE
slot props type when reference block scope variable

### ISSUE THREAD

**Issue by jasonlyu123** [sveltejs/language-tools#263]
**Describe the bug**
when `slot props` is referencing a block scope variable it would have any type in the consumer

**To Reproduce**

Component.svelte 
```svelte
<script>
    let list = ['']
</script>

{#each list as value}
  <slot props={value} />
{/each}
```

consumer
```svelte
<Component let:name></Component>
```
where `name` has a type of any

**Expected behavior**
have correct type

**Screenshots**
![圖片](https://user-images.githubusercontent.com/36730922/86375422-3789bf00-bcb8-11ea-9123-e46209a41c94.png)
![圖片](https://user-images.githubusercontent.com/36730922/86375477-50927000-bcb8-11ea-96a7-6311212e16e6.png)

**System (please complete the following information):**
 - OS: Windows
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode, svelte2tsx

**Additional context**
got transform to
```tsx
<></>;function render() { 
 let list = [''];
 ; <>
 
 {(list).map((value) => <>
 
 <slot props={value} />
 </>)}</> return { props: {}, slots: {default: {props:value}} }} export default class { $$prop_def = __sveltets_partial(render().props) $$slot_def = render().slots }
```

**Comment by jasonlyu123** [comment]
The blocks where the variable is declared probably has to return the props definition. And it has to pass through multiple bocks. like this:
```tsx
declare function unwrap<T>(value: Promise<T>| T[]): T
const __$$_default_0_prop = unwrap((list).map((value) =>{ <>
 
 <slot props={value} />
</>; return { props: value }}));<></>; return { props: {}, slots: { default: { ...__$$_default_0_prop }}}
```
 But the biggest problem is it needs to be moved up until it's not nested in an element or component

**Comment by jasonlyu123** [comment]
And we also need to check if the expression references another slot props. The whole process it's so tedious I think it's better off just don't support it and provide a way to let the user manually defined its type.

**Comment by dummdidumm** [comment]
Maybe something like

```ts
interface ComponentDef {
   props?: ... // optional
   slots?: ... // optional
}
```

That way you could define props explicitely while at the same time define connections between props and slots like wanted in #273 : 

```ts
interface ComponentDef<T>{
   props: { items: T[]; };
   slots: { item: T };
}
```

`svelte2tsx` would check if an interface definition called `ComponentDef` exists and if yes would use that instead of constructing its own props/slots definition.

One thing that's left: How to use that generic type inside the rest of the component?

```ts
interface ComponentDef<T>{
   props: { items: T[]; };
   slots: { item: T };
}

export let items: T[]; // <<-- ???
```

**Comment by PatrickG** [comment]
> The blocks where the variable is declared probably has to return the props definition. And it has to pass through multiple bocks. like this:
> 
> ```tsx
> declare function unwrap<T>(value: Promise<T>| T[]): T
> const __$$_default_0_prop = unwrap((list).map((value) =>{ <>
>  
>  <slot props={value} />
> </>; return { props: value }}));<></>; return { props: {}, slots: { default: { ...__$$_default_0_prop }}}
> ```
> 
> But the biggest problem is it needs to be moved up until it's not nested in an element or component so that we could event declare any variable.

Why do allow `Promise<T>`?
Im not aware that `{#each promise as value}` is a thing.

Wouldn't that work?
```tsx
declare function unwrap<T>(value:  T[]): T
function render() {
    let list = ['', 123];

    <>
        {(list).map((item) => {
            return <>
                <slot item={item} />
            </>;
        })}
    </>;

    return {
        props: {},
        slots: {
            default: { item: unwrap(list) }
        }
    };
}
```

If i hover over unwrap(list) it shows the type `string | number`.

**Comment by PatrickG** [comment]
@dummdidumm then you have to specify the prop types two times 🤔

**Comment by dummdidumm** [comment]
I know, but how else to define the relationship between them?

**Comment by PatrickG** [comment]
I was thinking about something like that:
```tsx
declare function unwrap<T>(value:  T[]): T
function render<T>() {
    let list: T[];

    <>
        {(list).map((item) => {
            return <>
                <slot item={item} />
            </>;
        })}
    </>;

    return {
        props: {},
        slots: {
            default: { item: unwrap(list) }
        }
    };
}
```

But then, you would have to call the render function with the type from the thing you pass to the component.
I have not found where this is called yet. Is it in svelte-check? Or has the render function to stay like it is, because of tsx?

**Comment by dummdidumm** [comment]
It's called nowhere and that is part of the problem.

**Comment by jasonlyu123** [comment]
I think we can still provide the way to manually type components even if @PatrickG's solution is easier to implement. It can serve as a fallback for edge-case, bug, or even manually type the event.

**Comment by dummdidumm** [comment]
If we go with the interface definition solution this is quite a change. Do others have opinions on this?

**Comment by jasonlyu123** [comment]
As for Patrick's solution, I think we'll need to track the variable scope when walking the AST. Whenever we found the slot props referencing a block scope variable we'll have to add the variable and the variable's initializer to a `Map`. And then in an upper scope. check if the variable initializer and their initializers reference a block scope variable. 

for example:
```svelte
<script>
	export let keys = [];
	export let items = [];
</script>

<table>
{#each items as item}
	<tr>
		{#each keys as key}
			<slot value={item[key]}></slot>
		{/each}
	</tr>
{/each}
</table>
```
1. `keys` each block
the key would be `key` and the value would be `unwrap(keys)`
2. `items` each block
the key would be `item` and the value would be `unwrap(items)` 

```svelte
<script>
	export let items = [ [ ] ];
</script>

<table>
{#each items as item}
	<tr>
		{#each item as innerItem}
			<slot value={innerItem}></slot>
		{/each}
	</tr>
{/each}
</table>
1. `item` each block
the key would be `innerItem` and the value would be `unwrap(innerItem)`
2. `items` each block
the key would be `item` and the value would be `unwrap(items)`, `unwrap(innerItem)` became `unwrap(unwrap(items))`

**Comment by dummdidumm** [comment]
There are also type narrowing cases which would need to be considered:

```html
<script lang="ts">
   export let bla: string | null;
</script>
{#if bla !== null}
   <slot value={bla}></slot> // <--- bla is now of type string
{/if}
```

---> I think these cases are just too hard to infer dynamically for us / it takes too much work for too little benefit. I think letting the user explicitely type slots/props in this case is better.

**Comment by PatrickG** [comment]
We don't need a Map of the variables itself, just the type of the variable at the time it is used in the `<slot />`.

**Comment by jasonlyu123** [comment]
By the time of walking through Htmlx AST, there's no information on the type of a variable. Even if it's a typescript AST there's no type information only the type node associate with it.

**Comment by jasonlyu123** [comment]
A crazy way to transform so that we don't have to care about destructuring 
```tsx
function render<T>() {
    let list: T[];

    <>
        {(list).map(({ a }) => {
            return <>
                <slot props={a} />
            </>;
        })}
    </>;

    return {
        props: {},
        slots: {
            default: { props: (({ a }) => a)(__sveltets_unwrapArr(list)) }
        }
    };
}
```

**Comment by dummdidumm** [comment]
Maybe this could really work in a generic way:

- If you enter a `#each`, do `(__svelte_ts_unwrappAttr(list))`
- If you enter a `#await`, do the same but with `__svelte_ts_unwrapPromiseLike(promise)`
- If they use destructuring, wrap it with that immediately invoked function @jasonlyu123 proposed
- Do this is recursivly if needed
