### ISSUE TITLE
VS code without TS: non defined object property marked as error

### ISSUE THREAD

**Issue by dm-de** [sveltejs/language-tools#2632]
### Describe the bug

VS code display errors, if here is an object without known property.

### Reproduction

```
<script>
	let form = $state({})
	form.pass = ''
</script>

{form.mail}
```

### Expected behaviour

no errors

### System Info

newest VS code addon

### Additional Information, eg. Screenshots

![sv12](https://github.com/user-attachments/assets/aa043a9b-500a-4128-b161-ba8cd1bba60a)

**Comment by jasonlyu123** [comment]
There is a `checkJs` option in your jsconfig.json. Turn it off if you don't want type-check. Next time you create the project choose the no type-check option, not the JSDoc option.

**Comment by dm-de** [comment]
I hope for solution like here:
https://github.com/sveltejs/language-tools/issues/2556#issuecomment-2457102354

@dummdidumm
is this doable?
