### ISSUE TITLE
Error: Could not find a declaration file for module

### ISSUE THREAD

**Issue by Bilge** [sveltejs/language-tools#2634]
### Describe the bug

Since Svelte v5, one (and only one) of my components gives this error. I cannot determine what is special about this one component, other than it declares no `<script>` block (but adding one does not fix the error).

* This same file is unchanged since before the v5 migration, where svelte-check detected no error.
* There are no errors with my webpack build.
* The same file importing the problematic component also imports other components without problems.

This combination of circumstances makes me strongly suspect this is a bug. 

### Reproduction

```ts
import WatchListButton from '../component/WatchListButton.svelte';
```

>Error: Could not find a declaration file for module '../component/WatchListButton.svelte'. 'component/WatchListButton.svelte' implicitly has an 'any' type. 
import TooltipPage from './tooltip page';
import WatchListButton from '../component/WatchListButton.svelte';
import { mount } from 'svelte';

### Expected behaviour

Components don't need declaration files, or such declarations are derived from the component source files.

### System Info

- OS: Windows
- IDE: PhpStorm

### Which package is the issue about?

svelte-check

**Comment by Bilge** [comment]
Actually, adding `script` tags does fix it, but only if you also set `lang=ts`.

```svelte
<!-- svelte-check workaround -->
<script lang="ts"></script>

<!-- NOT a svelte-check workaround -->
<script></script>
```

**Comment by jasonlyu123** [comment]
Since svelte-check v4 and extension 109, the [allowJs](https://www.typescriptlang.org/tsconfig/#allowJs) typescript compiler option is respected. It was `false` by default and was previously overridden by the language-server/svelte-check as `true`. The issue is likely you need to set `allowJs` to be true to allow module resolution to find js components in your project.

**Comment by Bilge** [comment]
Can confirm: for reasons I don't yet understand, setting `"allowJs": true,` also resolves the issue.
