### ISSUE TITLE
Grave accent replacing instead of wrapping

### ISSUE THREAD

**Issue by subz390** [sveltejs/language-tools#264]
### ` The Grave Accent
The editing actions of a [Grave accent](https://theasciicode.com.ar/ascii-printable-characters/grave-accent-ascii-code-96.html) in Javascript sections of `.svelte` files within `VSCode` are not implemented.
By comparison the actions of single quotes `''` and double quotes `""`, the grave accent is non-functioning.

Grave accents are required when working with [Template Literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) and an integral part of modern Javascript Svelte workflow.

### There are two editing scenarios:
**Expect:** type the cymbol, it should print two and move the cursor between the two.
**Actual** one cymbol is printed

**Expect** select a range of code, type the cymbol, two cymbols are printed and the range moved between them.
![grave accent - expected](https://user-images.githubusercontent.com/11546815/86389795-d13c7680-bc8e-11ea-866b-65390684ae3b.gif)

**Actual** the range is deleted and one cymbol is printed
![grave accent - actual](https://user-images.githubusercontent.com/11546815/86389763-c2ee5a80-bc8e-11ea-9c85-544bdfb8ec3f.gif)

### Environment
- OS:  Windows 10
- IDE: VSCode
- Plugin/Package: "Svelte for VSCode"

### History
This is an old issue that was never address in the [svelte-vscode](https://github.com/UnwrittenFun/svelte-vscode/issues/71) plugin.

**Comment by subz390** [comment]
Thanks @dummdidumm when can we expect to see this filter through to `Svelte for VS Code` extension?

**Comment by dummdidumm** [comment]
Released just now.
