### ISSUE TITLE
Svelte + Typescript = some error

### ISSUE THREAD

**Issue by pruginkin** [sveltejs/language-tools#265]
```
<script lang="ts"> let w: any </script>
<svelte:window bind:innerWidth={w} />
```
Typescript error - Type '{ innerWidth: any }' is not assignable to type 'HTMLProps'.
Property 'innerWidth' does not exist on type 'HTMLProps'.ts(2322)
![Screenshot_20200702_155243](https://user-images.githubusercontent.com/51276573/86411161-e6cc9300-bcc4-11ea-9c61-6e388501f8dc.png)

**Comment by pruginkin** [comment]
![Screenshot_20200702_155243](https://user-images.githubusercontent.com/51276573/86411118-cd2b4b80-bcc4-11ea-8e80-bc1fe1563da3.png)

**Comment by pruginkin** [comment]
svelte:body bind has the same error

**Comment by jasonlyu123** [comment]
I think that would be correct. Svelte doc doesn't mention you could do that and I tried it in REPL it only gets undefined.

**Comment by pruginkin** [comment]
Yes, sorry, the documentation says so
