### ISSUE TITLE
Svelte typescript: Props with default values cause Type error of missing props

### ISSUE THREAD

**Issue by Dulanjala007** [sveltejs/language-tools#276]
//component code
```
<script lang="typescript">
  export let name= '';
</script>
```

when component is added without providing the Prop "name", vs code shows this error
_component = Service_

```
Type '{ service: Service; }' is not assignable to type 'IntrinsicAttributes & { service: Service; className: string; }'.
  Property 'name' is missing in type '{ service: Service; }' but required in type '{ service: Service; name: string; }'
```

Currently I'm getting rid of this by adding explicit types 
```
<script lang="typescript">
  export let name: string | undefined = '';
</script>
```

we shouldn't have to do this right, can't we infer the type from the default value assignment?
or are there any other syntax (like '?') to make this more cleaner....
or am I doing something wrong?

**Comment by jasonlyu123** [comment]
A proposal of this has been discussed here https://github.com/sveltejs/language-tools/issues/214#issuecomment-650884827

**Comment by dummdidumm** [comment]
We did originally not do this because it seemed very hard to track down if the initializer itself is initialized.

Example:
```ts
let a: string;
export let b = a;
```

@jasonlyu123  Or is this no longer relevant / did you find a way to deal with this?

**Comment by jasonlyu123** [comment]
Oh! That's an issue. No. I don't have any solution for this.

**Comment by dummdidumm** [comment]
Maybe we could at least relax and fix it for 90% of the cases like this: If initializer is not a variable, mark it as optional.

**Comment by jasonlyu123** [comment]
Svelte dev build actually has required props checking. It only checks if the variable declaration has initialized.
REPL: https://svelte.dev/repl/cf729f684c904678915c52eaf97788b9?version=3.23.2

this is how it checks: 

https://github.com/sveltejs/svelte/blob/38de3b2e9f46925be12ce43f55c424b49ddfb0af/src/compiler/compile/render_dom/index.ts#L173

https://github.com/sveltejs/svelte/blob/0e2bc352dfeeacf1bdba8c43dacceac15a85f337/src/compiler/compile/Component.ts#L616

https://github.com/sveltejs/svelte/blob/bad7443eb3c9e9e6f6b3c53ba255bab95c10f087/src/compiler/compile/utils/scope.ts#L4

https://github.com/Rich-Harris/periscopic/blob/d7a820b04e1f88b452313ab3e54771b352f0defb/src/index.ts#L125

**Comment by dummdidumm** [comment]
Thought about this some more: I think we should mark props as optional as soon as any kind of initializer is given. Typescript itself will make sure that usages are correct, so this is safe to do.

**Comment by PatrickG** [comment]
> Thought about this some more: I think we should mark props as optional as soon as any kind of initializer is given. Typescript itself will make sure that usages are correct, so this is safe to do.

Sounds reasonable.
I could rebase my branch and create a PR with my changes.

**Comment by dummdidumm** [comment]
Sounds good! One thing about your changes: you removed the `undefined` check. I think this is still needed because else it is marked as required even if the user types `export let bla: string | undefined` .

**Comment by PatrickG** [comment]
That's true, like I explained in https://github.com/sveltejs/language-tools/issues/214#issuecomment-650884827, this is the correct behavior in my opinion.
Also, if a variable has no initializer and you do not pass the prop to the component, Svelte will log a warning.

**Comment by dummdidumm** [comment]
Mhm, that's true, it's more in line with how the svelte compiler treats it. Also it's a difference in strict mode if you type a prop as undefined or optional I think. You convinced me 😄

**Comment by abart27** [comment]
Seems like this has regressed

ComponentA.svelte
```html
<script lang="ts">
    const { onclick, enabled = true }: { onclick: () => void; enabled: boolean } = $props();
</script>
```

ComponentB.svelte
```html
<!-- Property 'enabled' is missing in type '{ onclick: () => void; }' but required in type '$$ComponentProps'.ts(2741) -->
<ComponentA onclick={() => {}}/>
```

**Comment by jasonlyu123** [comment]
@Aurumaker72 in Svelte 5, you need to mark the props as optional yourself. 

```svelte
<script lang="ts">
    const { onclick, enabled = true }: { onclick?: () => void; enabled?: boolean } = $props();
</script>
```
