### ISSUE TITLE
Strange multiple export typing issue

### ISSUE THREAD

**Issue by dkzlv** [sveltejs/language-tools#277]
**Describe the bug**
It is by no means a severe bug, but a very strange one still.
If you define multiple props on the same line and divide them with a comma, all the props except the first one would raise an error, that they are not defined despite their type, but only in the template, not in the script.

**To Reproduce**
So JS/TS allows you to define as many `let`s, `const`s and `export`s in one line. I usually use this to save some keystrokes.
Here's the code that works fine and generates no errors:
```html
<script lang="ts">
  export let callback: () => void;
</script>

<button on:click={callback}>Click</button>
```
but this one raises an error in the template:
```html
<script lang="ts">
  export let name: string, callback: () => void;

  let wrappedCallback: () => void;
  // No error! Hover shows right type for `callback`
  $: wrappedCallback = () => callback();
</script>

<!-- Error: Variable 'callback' is used before being assigned. -->
<button on:click={callback}>{name}</button>
```

It is very strange, since semantically it's the same as 

```typescript
export let name: string;
export let callback: () => void;
```

Should also say that this code is treated well by the IDE:
```html
<script lang="ts">
  const check1 = 'qwerty',
    check2 = 'qwerty';
</script>

<p>{check1}, {check2}</p>
```

**Expected behavior**
It shouldn't raise any errors.

**System (please complete the following information):**
OS: Mac OS 10.15.3
IDE: VS Code
Plugin/Package: Svelte for VS Code (the new official one)

**Comment by dummdidumm** [comment]
Special case of #146, we need to adjust [the regex](https://github.com/sveltejs/language-tools/blob/master/packages/language-server/src/plugins/typescript/features/DiagnosticsProvider.ts#L83) to deal with this.

**Comment by dummdidumm** [comment]
Probably the better solution would be to return some kind of info from `svelte2tsx` about the props. This would remove the need for the regex and be more robust since `svelte2tsx` uses the typescript parser to get these infos.
