### ISSUE TITLE
Support external svelte module with component main entry (svelte key in package.json)

### ISSUE THREAD

**Issue by jasonlyu123** [sveltejs/language-tools#28]
```json
{
  "name": "@sveltech/routify",
  "version": "0.0.0-development",
  "description": "Routes for Svelte, automated by your filestructure",
  "main": "lib/index.js",
  "svelte": "runtime/index.js",
```

> The svelte key is what is being resolved within Svelte apps, but code completion doesn't work, since VSCode uses the main key.
```
Could not find a declaration file for module '@sveltech/routify'. '... routify/lib/index.js' implicitly has an 'any' type.
```

_Originally posted by @jakobrosenberg in https://github.com/sveltejs/language-tools/pull/9#issuecomment-612420470_

As @jakobrosenberg point out. The svelte key in external module's `package.json` is a special custom main entry for svelte component source. See [rollup-plugin-svelte](https://github.com/sveltejs/rollup-plugin-svelte/blob/master/README.md#pkgsvelte) for more info. This custom entry should be consider when resolving svelte module

**Comment by jasonlyu123** [comment]
Upon further study on how to implemented, I actually not so sure if this is needed to be implement. 
As this custom main field is used by bundler/ builder like webpack and rollup. But for the language-server, reading from source means it would have to recompile it every time, which is more inefficient. Also, as the doc of rollup-plugin-svelte said:
>if you're publishing a component to npm, you should ship the uncompiled source (together with the compiled distributable, for people who aren't using Svelte elsewhere in their app) and include the "svelte" property in your package.json

It seems to means the field isn't intended to be required to build. It's like the more commonly used 'source' field but a svelte version. Also typescript's module-resolving doesn't support custom entry too.

Maybe it could still be implemented but under some configuration with glob array to test for.

**Comment by btilford** [comment]
There really isn't a standard for source, module, types, or browser. Even main isn't super well-defined. Hopefully MS fixes it now that they have control of npm, GitHub, and Typescript. 

I wish more projects did package up source it makes debugging and figuring out things so much better. 

/rant

**Comment by sw-yx** [comment]
sounds like this is ok to close?

**Comment by jasonlyu123** [comment]
Since it's much easier to manual type a component now there is not much need for this any more. I'll close this

**Comment by YogliB** [comment]
> Since it's much easier to manual type a component now there is not much need for this any more. I'll close this

How can we manually type a component?

**Comment by dummdidumm** [comment]
I assume you talk about providing types as a library author.

There is nothing official yet. For now the best way is to copy the contents of [this class](https://github.com/sveltejs/language-tools/blob/master/packages/svelte2tsx/svelte-shims.d.ts#L5) into your types and make all components extend that like 

```ts
export class YourComponent extends Svelte2TsxComponent<{...props...}, {...events..}, {...slots...}> {}
```
