### ISSUE TITLE
Incorrect semicolon error before dollar label

### ISSUE THREAD

**Issue by BjornLuG** [sveltejs/language-tools#289]
**Describe the bug**
The svelte extension raises error of `';' expected` before the dollar label even if it's valid syntax. Inserting the semicolon before it did solve the issue, however the semicolon should be optional.

**To Reproduce**

```svelte
<script>
  let foo = 'bar'

  $: console.log(foo)
</script>
```

**Expected behavior**
No error raised.

**Screenshots**
The code above as in VSCode shows error:
![image](https://user-images.githubusercontent.com/34116392/86754702-ac237b80-c073-11ea-9cb0-c22879922902.png)

**System (please complete the following information):**
 - OS: Ubuntu
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode

**Additional context**
Issue appears in v101.0.0, but works fine in the previous version v100.1.0

**Comment by dummdidumm** [comment]
@jasonlyu123 possibly an error introduced in #259 ?

**Comment by jasonlyu123** [comment]
yeah forgot to put a semi before the wrapping arrow function
