### ISSUE TITLE
TypeScript doesn't realise when non svelte files have changed

### ISSUE THREAD

**Issue by jasonlyu123** [sveltejs/language-tools#29]
Copy from origin repo https://github.com/UnwrittenFun/svelte-language-server/issues/8, this issue still exists.

Vetur keep cache of ScriptSnapShot and document version of none vue files and update when file updated. 
https://github.com/vuejs/vetur/blob/master/server/src/services/typescriptService/serviceHost.ts

I tried to increase the version every time when ts host [request version](https://github.com/sveltejs/language-tools/blob/3871012209a2aa9e2460d0a63497f09feb5915c9/packages/language-server/src/plugins/typescript/service.ts#L77), the problem resolved but the performance is crippled by it. So this issue is related to document version and ts's incremental compilation. Due to performance issue we have to implement a similar incremental compilation solution like vetur does, keep cache of none svelte document and only update version when file actually changes.

**Comment by dummdidumm** [comment]
What we would need to do is to tell the language server to also react to typescript/javascript file events so we know when those files have changed. I think this has to be done on the client. One option is to add typescript and javascript to the configuration section in `svelte-vscode/src/extension.ts` like so:

```ts
let clientOptions: LanguageClientOptions = {
        documentSelector: [{ scheme: 'file', language: 'svelte' }, 'typescript', 'javascript'], // <<-
        // ...
    };
```
After I added this, the server started to get notified when something changed in ts/js files. The downside is that it also gets notified about all other events (hover, completions) inside ts/js files. We would need to filter out all events not related to svelte files and only react to documentopen/change/close events for ts/js.

I think vetur does it differently, my guess is they somehow do it with a file watcher. [At least this is in their code](https://github.com/vuejs/vetur/blob/d14ab6ab54dbb4f99497daf3b95893b7727ea2c7/client/client.ts#L53):

```ts
let clientOptions: LanguageClientOptions = {
        // ...
        synchronize: {
            configurationSection: ['svelte'],
            fileEvents: workspace.createFileSystemWatcher('{**/*.js,**/*.ts}', false, false, true), // <<-
        },
        // ...
    };
```

But I don't know how to react further to those events.

**Comment by jasonlyu123** [comment]
Thanks, I will try to implement this with `FileSystemWatcher`. I play around a bit and found that typescript-language-service needs some adjust to expose script snapshots and script versions for updates.
