### ISSUE TITLE
Pug syntax highlight

### ISSUE THREAD

**Issue by jasonlyu123** [sveltejs/language-tools#295]
**Is your feature request related to a problem? Please describe.**
Provide basic support for pug markup. Related: #106 

**Describe the solution you'd like**
VSCode's syntax highlight is done by Textmate grammar. Basically it's defining some regex pattern to tokenize the code. And we could include other languages' rules as long as vscode knows how to deal with the included language. 

I am not using pug so I don't know about pug syntax. It would be great if anyone with more experience with svelte-pug can help.

***General guide on how to implement it***
It's not hard to implement.  First, fork this repo and follow [the development instruction](https://github.com/sveltejs/language-tools#development). Follow the [vscode's official guide for syntax hightlight](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide). Add the patterns needed to the syntax file which is located in `packages/svelte-vscode/syntax`. 

It seems like syntax for the pug in svelte is similar to Vue's. So we could probably copy some code from vetur

This for defining a block to start and end identifying pug syntax:
https://github.com/vuejs/vetur/blob/master/syntaxes/vue.tmLanguage.json#L87

This for telling vscode that we have embedded pug code
https://github.com/vuejs/vetur/blob/master/package.json#L119

These two would add the basic syntax highlight. What's left would be adding svelte specific syntax like `+each('posts as post')` under pug patterns. Add more patterns and link them to the existing syntax token.
For example each block:
```json

        "svelte-pug-each": {
            "begin": "(\\+)(each)\\(",
            "beginCaptures": {
                "1": {
                    "name": "punctuation.definition.tag.begin.svelte"
                },
                "2": {
                    "name": "keyword.control.conditional"
                }
            },
            "end": "\\)",
            "endCaptures": {
                "0": {
                    "name": "punctuation.definition.tag.end.svelte"
                }
            },
            "patterns": [
                {
                    "begin": "'",
                    "end": "\\s(as)\\s+",
                    "endCaptures": {
                        "1": {
                            "name": "keyword.control"
                        }
                    },
                    "patterns": [
                        {
                            "include": "source.ts"
                        }
                    ]
                }
            ]
        }

```

**Comment by jasonlyu123** [comment]
It seems like the svelte-preprocess' pug syntax is using pug's existing syntax. So we could just copy the corresponding syntax from [vscode's pug syntax](https://github.com/microsoft/vscode/blob/master/extensions/pug/syntaxes/pug.tmLanguage.json) and modify it to suit our need

**Comment by dummdidumm** [comment]
Basic highlighting done through #371 . Maybe this is already enough? The svelte-specific syntax seems to highlight just fine.

**Comment by b1m1nd** [comment]
@dummdidumm YAY!! 
![image](https://user-images.githubusercontent.com/55322556/89113371-6c12a700-d42d-11ea-8dfc-34b05a8ebb47.png)

Seems to be working, not sure why but it seems partially break in the if params . Also the component coloring below the template element seems to change.

Super happy about seeing this progress, sorry I was late to test it.

**Comment by b1m1nd** [comment]
@dummdidumm I apprciate you working on this. So I am finally able to get back to my Svelte project and noticed something is def killing the highlighting. 

![image](https://user-images.githubusercontent.com/55322556/91758384-2c0a2580-eb8d-11ea-98ad-0b052a11162e.png)

it seems to break with the `"` when defining some things within ( )

**Comment by zamkevich** [comment]
JSDoc is't work for pug. 
For example It works on html tag inside pug template

![image](https://user-images.githubusercontent.com/13717428/92597367-a4d65380-f2ea-11ea-9668-cb5a6071c4bc.png)

Component
![image](https://user-images.githubusercontent.com/13717428/92597625-05659080-f2eb-11ea-867d-dc48e8d7c200.png)

**Comment by hoishing** [comment]
Thanks for the great work! btw, seems inline function is not supported at the moment, say `on:click="{ () => doSomething }"` will raise errors.

**Comment by dummdidumm** [comment]
Intellisense support is tracked in #106 .
