### ISSUE TITLE
Self closing textarea throws unexpected token

### ISSUE THREAD

**Issue by ejoflo** [sveltejs/language-tools#300]
After installing the Svelte for VS Code extension, one of my .svelte files is producing errors in the <style> section of the code.  The error is related to closing brackets in the CSS.

The following problems are reported:
_'}' expected._
_Unexpected token. Did you mean `{'}'}` or `&rbrace;`?_

My .svelte file works just fine and everything compiles without error so this is more of a minor annoyance. I am not sure how to reproduce this because like I mentioned, it was a previous file that I opened after installing the Svelte for VS Code extension. I have not seen this issue in my other files for the same project, just this one in particular. Screenshot below.

![Screen Shot 2020-07-09 at 10 53 53 AM](https://user-images.githubusercontent.com/51680874/87089681-806ad780-c1d2-11ea-9077-d90f13043ab9.png)

**Comment by jasonlyu123** [comment]
The problem is not style tag. It's something before it. Could you provide the code before or a minimum reproducible?

**Comment by ejoflo** [comment]
> The problem is not style tag. It's something before it. Could you provide the code before or a minimum reproducible?

Sure, code is below.

`<script>
  import DOMPurify from 'dompurify';
  import { timeout, isObjectEmpty } from '../helpers/_route_helpers';
  import { submitEmail } from '../helpers/_email_helpers';
  import { userAuth } from '../stores/_auth_store';
  import { userInfo } from '../stores/_user_store';
  import { popupMessage } from '../stores/_popup_store.js';
  import { scale } from 'svelte/transition';
  import { quartOut } from 'svelte/easing';
  import { currentPath } from '../stores/_location_store';
  import { goto } from '@sapper/app';
  import Loading from '../components/Loading.svelte';

  let isLoading = false;
  let contactEmail = isObjectEmpty($userInfo) === false ? $userInfo.email : '';
  let contactSubject;
  let contactMessage = '';

  let reasons = [
    { id: 1, text: `Feature Request` },
    { id: 2, text: `Business Inquiry` },
    { id: 3, text: `Problem with a Verse` },
    { id: 4, text: `Site Issues or Bugs` },
    { id: 5, text: `Submit Bandcamp Beats` },
    { id: 6, text: `Feedback & Other` }
  ];

  // Refresh page if user logs in
  $: if ($currentPath === 'contact' && isObjectEmpty($userAuth) === false) {
    $currentPath = window.location.pathname;
    goto('/refresh');
  }

  async function submitContact() {
    if (!contactSubject) {
      showPopup('SELECT A REASON.', 'warning', 2000);
      return;
    } else {
      isLoading = true;
      contactMessage = DOMPurify.sanitize(contactMessage);
      contactSubject = contactSubject.text;

      const submitEmailResponse = await submitEmail(
        contactEmail,
        contactSubject,
        contactMessage,
        $userAuth.token || ''
      );

      if (!submitEmailResponse.error && !submitEmailResponse.userErrorMessage) {
        showPopup('MESSAGE SENT.', 'success', 3000);
      } else {
        showPopup(
          submitEmailResponse.userErrorMessage
            ? submitEmailResponse.userErrorMessage.toUpperCase()
            : submitEmailResponse.message.toUpperCase(),
          'warning',
          3000
        );
        isLoading = false;
        return;
      }
    }
    contactEmail = isObjectEmpty($userInfo) === false ? $userInfo.email : '';
    contactSubject = '';
    contactMessage = '';
    isLoading = false;
  }

  async function showPopup(text, mode, duration) {
    $popupMessage.text = text;
    $popupMessage.mode = mode;
    await timeout(duration);
    $popupMessage.text = '';
    $popupMessage.mode = '';
  }
</script>

<div
  class="contact-us-container"
  in:scale={{ delay: 500, duration: 1200, easing: quartOut }}>

  <div class="contact-container">
    <h3>CONTACT</h3>
    <p>
      Got a question about something? Got beats on bandcamp you'd like to submit
      for Megaverse Radio? Got an idea for a daily topic? Hit us up. When
      reporting any bugs or site issues, please be descriptive by explaining how
      to reproduce the issue.
    </p>
    <form
      action="#"
      id="contact"
      type="submit"
      on:submit|preventDefault={submitContact}>

      <label for="email">E-MAIL ADDRESS</label>
      <input
        class="contact-email"
        type="email"
        name="email"
        bind:value={contactEmail}
        required />

      <label for="reason">REASON</label>
      <select
        class="contact-reason"
        name="reason"
        form="contact"
        bind:value={contactSubject}>
        {#each reasons as reason}
          <option value={reason}>{reason.text}</option>
        {/each}
      </select>

      <label for="message">MESSAGE</label>
      <textarea
        class="contact-message u-full-width"
        name="message"
        bind:value={contactMessage}
        required />

      {#if isLoading}
        <Loading translucent={false} />
      {:else}
        <button
          class="primary-button submit-button"
          type="submit"
          disabled={isLoading}>
          SUBMIT
        </button>
      {/if}

    </form>
  </div>
</div>

<style>
  .contact-us-container {
    display: grid;
    grid-template-columns:
      minmax(50px, 1fr) minmax(auto, 320px) minmax(auto, 320px)
      minmax(50px, 1fr);
    grid-template-areas: '..... contact contact .....';
    grid-gap: 0 1em;
    justify-content: center;
  }

  h3 {
    margin-bottom: 0.35em;
    color: #cccb79;
    font-weight: 700;
  }

  .contact-container {
    grid-area: contact;
  }

  input {
    border-radius: 0;
    -webkit-appearance: none;
    -webkit-border-radius: 0px;
  }

  label {
    margin-left: 0.25em;
    font-size: 1.2rem;
    font-weight: 700;
    color: #fffc6c;
    text-transform: uppercase;
  }

  .contact-email,
  .contact-reason {
    margin-left: 0.25em;
    width: 50%;
  }

  select {
    border-radius: 0;
    -webkit-appearance: none;
    -webkit-border-radius: 0px;
    cursor: pointer;
  }

  .contact-message {
    height: 200px;
    resize: none;
    background-color: #0000006e;
    border-radius: 10px;
    border-top-left-radius: 0;
    border-bottom-right-radius: 0;
    border-bottom: 0;
  }

  .contact-message:focus {
    border: 1px solid #fffc6c;
  }

  .submit-button {
    margin-left: auto;
    color: #21202c;
    background-color: rgba(87, 245, 153, 0.527);
    border: 0;
    transition: color 200ms, background-color 200ms,
      border-color 250ms ease-in-out;
  }

  .submit-button:hover,
  .submit-button:focus {
    color: #21202c;
    background-color: #57f59a;
  }

  @media (min-width: 320px) and (max-width: 480px) {
    .contact-us-container {
      grid-template-columns:
        1fr minmax(auto, 320px) minmax(auto, 320px)
        1fr;
      grid-template-areas: '..... contact contact .....';
    }
    .contact-email,
    .contact-reason {
      width: 97%;
    }
  }
</style>
`

**Comment by jasonlyu123** [comment]
similar to #251 but in a different package

**Comment by jasonlyu123** [comment]
The problem is the self-close textarea. The parser we use doesn't support it. We'll see what can we do to fix it. You can replace it with a close tag`<textarea></textarea>` the error will disappear.

**Comment by ejoflo** [comment]
> The problem is the self-close textarea. The parser we use doesn't support it. We'll see what can we do to fix it. You can replace it with a close tag`<textarea></textarea>` and the error will disappear.

Got it, thanks. When using Prettier extension it automatically creates a self-close tag <textarea /> so it would definitely be a nice addition to support self closing tags. Cheers.

**Comment by ignatiusmb** [comment]
Turns out it not just `<textarea>` but `<iframe>` too. Not sure why these 2 particular tags are throwing these errors but not others.

![image](https://user-images.githubusercontent.com/8156777/89710308-02a21380-d9ac-11ea-896d-8507ced21a63.png)

**Comment by jasonlyu123** [comment]
Every tag that can't self close in HTML would trigger it because we use an HTML parser. For now, the easiest way to avoid it is to put markup after script and style
