### ISSUE TITLE
Component event type check

### ISSUE THREAD

**Issue by jasonlyu123** [sveltejs/language-tools#304]
**Is your feature request related to a problem? Please describe.**
Current component type check can only check if it is `(e: Event) => any`

**Describe the solution you'd like**
1. Event forward like `<button on:click />` can have type check in consumer component
2. Can type check for event dispatched by event-dispatcher 

**Describe alternatives you've considered**
if the event dispatched by event-dispatcher can't be type-check or it is dispatched by an imported function provides a way to manually define the event's type. For example:
```ts
interface $$ComponentEventDef {
    'some-event': CustomEvent<number>
}
```

**Comment by dummdidumm** [comment]
Closing in favor of #424
