### ISSUE TITLE
VSCode Market Github link

### ISSUE THREAD

**Issue by icebr9** [sveltejs/language-tools#31]
If you go to [Svelte on VSCode Market](https://marketplace.visualstudio.com/publishers/svelte) you can see that Github link is leading to /svelte instead of /sveltejs
![image](https://user-images.githubusercontent.com/46702991/79858194-54a83480-83cf-11ea-998c-cbdc24fe383a.png)

**Comment by dummdidumm** [comment]
@orta how can we change this? Are you the owner of the publisher?

**Comment by orta** [comment]
I think I did this but forgot to come and close the issue

**Comment by orta** [comment]
I didn't then, but I have now and added some deployment docs so I can find it again more easily
