### ISSUE TITLE
svelte TSX-like highlighting

### ISSUE THREAD

**Issue by BlackFenix2** [sveltejs/language-tools#315]
**Is your feature request related to a problem? Please describe.**
I would like the svelte component tags to light up green to separate from the blue HTML tags in vscode

**Describe the solution you'd like**
Can we get the same syntax highlighting from .tsx and just put that into .svelte? the color would change only if the tag is capitalized. 

## Typescript React:
```tsx
import React from 'react';
import { observer } from 'mobx-react-lite';
import showStore from 'src/state/stores/showStore';
import ShowList from 'src/components/Views/Shows/ShowList';
import { Search } from '@material-ui/icons';
import TextInput from 'src/components/inputs';

const Shows = () => {
  const ShowStore = React.useContext(showStore);

  const setSearchTerm = (event) => {
    ShowStore.searchTerm = event.target.value;
  };

  return (
    <div>
<!-- different color, i can tell that is is a component rather than a HTML tag-->
      <TextInput
        label="Search Shows"
        value={ShowStore.searchTerm}
        changeEvent={setSearchTerm}
        Icon={Search}
      />

      <ShowList shows={ShowStore.shows} />
    </div>
  );
};

export default observer(Shows);
```

## Svelte:

```svelte
<script lang="typescript">
  import Nav from '../components/Nav.svelte';
</script>

<header>
 <!-- no diff color for the component, im having an identity crisis :( -->
  <Nav  />
</header>

```

**Describe alternatives you've considered**
i would try hacking vscode themes to get the color but why not have it in this library?

**Comment by BlackFenix2** [comment]
I'm determined but kind of noobish with language servers and syntax highlighting. I could make a PR with this feature if I knew how to change the color of text given a condition (<Capital> should be green)

**Comment by jasonlyu123** [comment]
Great! 
You can follow the [syntax highlight guide of vscode](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide) and the [textmate grammer](https://macromates.com/manual/en/language_grammars).  TLDR; it's a process of tokenizing and classifying code with a bunch of regexes. And you can use existing rules from other languages as long as vscode understands it.
The grammar file is located [here](https://github.com/sveltejs/language-tools/blob/master/packages/svelte-vscode/syntaxes/svelte.tmLanguage.json). You can follow the instruction on debugging [here](https://github.com/sveltejs/language-tools#running-the-dev-language-server-against-your-app)

**Comment by BlackFenix2** [comment]
i made a PR with the proposed change here:
https://github.com/sveltejs/language-tools/pull/318
