### ISSUE TITLE
Exclude sapper `src/node_module` svelte files from being processing?

### ISSUE THREAD

**Issue by sharifzadesina** [sveltejs/language-tools#316]
I am using Svelte+Sapper+TypeScript, the language server always checks svelte files inside `src/node_module/internal`, is there a way to exclude this directory completely?
I tried to add excludes to `tsconfig.json` file, but no chance.

**Comment by jasonlyu123** [comment]
We didn't set up the parsing of `tsconfig.json` to recognize `.svlete` extension so the language-server won't pick up any svelte file until it's opened in the editor or the file depended on it got opened. 
But it does still get pick up by svelte-check though, we can adjust this to ignore `src/node_module`.

**Comment by PatrickG** [comment]
If you do this, please only ignore `src/node_modules/sapper`.
I'm using this folder like Rich (e.g. `src/node_modules/@components`).

**Comment by sharifzadesina** [comment]
I think we need to support this exclude feature, sometimes I need to open auto-generated files and check the source, but it generates errors and I need to restart the editor.

**Comment by jasonlyu123** [comment]
Then we could just empty the diagnostic of closed file. The parsing of the exclude file config is hard for us. Typescript only has an API to parse the config file but not checking if a specific file should be excluded. So every opened file got processed. Even if we allow exclude and include of svelte files. It'll still not solved the problem for you. So I think we could just empty the diagnostic.

**Comment by sharifzadesina** [comment]
@jasonlyu123 so if it is also the behavior of typescript language I think you should also do that.
But why you are saying exclude will not solve the problem? you will check if the file is in exclude/include array of tsconfig or not.

**Comment by jasonlyu123** [comment]
Exclude and include is custom glob pattern. And it also involves relative path or absolute path, defaulting to include and exclude, the `files` config, etc. It's a lot of work needed to recreate it in our codebase. I did try it before and have no luck making it work. Besides, I don't think vscode typescript feature check the exclude and ignore processing it if it matches exclude. Otherwise, you won't have hover info.

**Comment by dummdidumm** [comment]
Regarding `svelte-check`: there will be a `--ignore` option available tomorrow #373
