### ISSUE TITLE
`export let` in plain js script tags breaks syntax highlighting

### ISSUE THREAD

**Issue by canadaduane** [sveltejs/language-tools#320]
**Describe the bug**
When adding an `export let` in plain javascript `<script>` tag, it breaks the rest of the syntax highlighting:

**To Reproduce**
Sample:
```
<script>
  import RightPanel from './RightPanel.svelte'

  export let start
</script>

<!-- a 'comment with dangling apostrophe -->
<RightPanel />
<PressTabHelp />
```

**Expected behavior**
The closing `</script>` tag should be recognized as the end of the javascript section.

**Screenshots**
![image](https://user-images.githubusercontent.com/129/87862501-15c24600-c90e-11ea-9cd3-b00058f19fa1.png)

**System (please complete the following information):**
 - OS: Mac OS 10.14.6
 - IDE: VSCode
 - Plugin/Package: "Svelte for VSCode" 101.3.0

**Comment by jasonlyu123** [comment]
Sorry. I can't reproduce this. Maybe this is an upstream issue, the syntax highlight within script tag was defined to be like "hey IDE, handle js for me". What is your VSCode version?

**Comment by canadaduane** [comment]
Hmm, interesting. I wonder what else I could look for. Here is my VS Code version info:

```
Version: 1.47.0
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:01:54.115Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```

**Comment by canadaduane** [comment]
Possible hint: when I use `lang="ts"` it parses correctly.

Is there a way I can discover what parser/ecmascript version Svelte is handing it off to?

**Comment by jasonlyu123** [comment]
Can you try to disable any extension except svelte for vscode and see if it persist? It might also be any other extension that alters the syntax highlight.

**Comment by canadaduane** [comment]
That was it! The `Babel Javascript` plugin (0.0.29) was the cause. Thanks.
