### ISSUE TITLE
prettier-plugin-svelte breaks correct formatting

### ISSUE THREAD

**Issue by vrde** [sveltejs/language-tools#323]
**Describe the bug**

`prettier-plugin-svelte` (that is enabled by default) constantly breaks my formatting. Code like

```html
<div>
  <a href="https://example.com/something-something">Something Something</a>,
  a project about <em>something</em>!
</div>
```

Is automatically formatted to:

```html
<div>
  <a href="https://example.com/something-something">Something Something</a>
  , a project about
  <em>something</em>
  !
</div>
```

That leads to render white-spaces before punctuation.

This makes my experience with this extension quite painful. This issue should be addressed in the `prettier-plugin-svelte` repository, but it seems to be ignored:

- https://github.com/sveltejs/prettier-plugin-svelte/issues/28
- https://github.com/sveltejs/prettier-plugin-svelte/issues/102
- https://github.com/sveltejs/prettier-plugin-svelte/issues/103

I'm writing here to ask if there is any alternative to that formatter.

**To Reproduce**

- Install the vscode extension
- Write some html
- Save it

**Expected behavior**

I expect the extension to not break my formatting.

**Screenshots**

Before and after saving:

![Peek 2020-07-19 23-54](https://user-images.githubusercontent.com/134680/87886188-50fe6b00-ca1b-11ea-9f60-93e9843b05d0.gif)

**System (please complete the following information):**
 - OS: GNU/Linux
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode

**Comment by jasonlyu123** [comment]
Sorry, Currently there are no other options. But you can use prettier ignore.

**Comment by dummdidumm** [comment]
You can also disable formatting completely through the corresponding setting.

**Comment by vrde** [comment]
Thanks for your answers.

If I understand correctly I can disable the HTML formatting only, right? I'm a bit confused, is it something I disable on `prettier` or on `prettier-plugin-svelte`?

**Comment by dummdidumm** [comment]
[It's a setting of the Svelte VSCode extension](https://github.com/sveltejs/language-tools/tree/master/packages/svelte-vscode#sveltepluginsvelteformatenable)

**Comment by vrde** [comment]
> [It's a setting of the Svelte VSCode extension](https://github.com/sveltejs/language-tools/tree/master/packages/svelte-vscode#sveltepluginsvelteformatenable)

I tried two things:

- Disable `svelte.plugin.svelte.format.enable` and it disable formatting for *everything*, while I'd like to keep formatting for `js` and `css`.
- Disable `svelte.plugin.html.enable` but it keeps formatting (I guess this option is used for something else).

So I'm not able to drop automatic formatting for HTML only :(

**Comment by dummdidumm** [comment]
Yes that is not possible.

**Comment by ehrencrona** [comment]
We should be able to close this now; sveltejs/prettier-plugin-svelte#120 fixes the bug mentioned.

**Comment by dummdidumm** [comment]
I'll keep it open until it's published and the extension is updated.

**Comment by dummdidumm** [comment]
This should be fixed with the latest `prettier-plugin-svelte` version (`1.2.0`) and the VSCode extension is updated to have this version built-in. If you still experience this issue, you might have a `prettier-plugin-svelte` in your workspace's `node_modules` and need to update that.
