### ISSUE TITLE
removing beginning `s` in text/html, with `<style />`

### ISSUE THREAD

**Issue by quangv** [sveltejs/language-tools#324]
**Describe the bug**
This or `prettier`, is removing starting works with beginning `s`, like `sweet`, `Sweet`, `sssweet`, after saving.

**To Reproduce**

`App.svelte`
```
<style>

</style>

sssweet
```

get's turned into: (after saving, see screenshot)

```
<style>

</style>

weet
```

**Expected behavior**
It should keep the `sssweet`

**Screenshots**
![2020-07-19_21-20-22](https://user-images.githubusercontent.com/1171187/87890977-7f258000-ca06-11ea-8c0e-ccb0bb71cdbd.gif)

**System (please complete the following information):**
 - OS: Windows 10
 - IDE: VSCode
 - Plugin/Package: "Svelte for VSCode", "Prettier"

**Additional context**
Strange.

**Comment by jasonlyu123** [comment]
https://github.com/sveltejs/prettier-plugin-svelte/blob/47becfaf50d4291df5ca8a93999d758d3718bea0/src/lib/snipTagContent.ts#L2

I think the problem is with this line in [prettier-plugin-svelte](https://github.com/sveltejs/prettier-plugin-svelte)

**Comment by dummdidumm** [comment]
@Conduitry could you transfer this issue to `prettier-plugin-svelte`? Thanks 😃
