### ISSUE TITLE
Extension crashes when cloning the repo locally

### ISSUE THREAD

**Issue by galkatz373** [sveltejs/language-tools#327]
**Describe the bug**
When I'm cloning the repo locally and debug it with "Run VSCode Extension", the extension crashes.

**To Reproduce**
I follow the instructions on the readme.
I tried to also remove the svelte extension, that I downloaded from the vscode "Extensions" section.

**Screenshots**
![image](https://user-images.githubusercontent.com/2151890/87984331-80c47600-cae2-11ea-9e06-d2cca82ec422.png)

**System (please complete the following information):**
 - OS: Windows 10
 - IDE: VSCode

**Comment by jasonlyu123** [comment]
You can open the output window of vscode to see if any error is logged. I would guess is that you didn't build `svelte2tsx`. We should update the doc to include that.

**Comment by dummdidumm** [comment]
If I remember correctly the bootstrap command does build it.

**Comment by jasonlyu123** [comment]
yeah, the bootstrap command does build svelte2tsx and this command is also in the doc.

**Comment by galkatz373** [comment]
I did run this command

**Comment by jasonlyu123** [comment]
Can you see if there are any errors logged? Another issue I experienced before is multiple language servers running at the same time, Vscode got a bug a few versions ago seems to cause the problem.

**Comment by galkatz373** [comment]
I can't seem to detect anything special
![image](https://user-images.githubusercontent.com/2151890/88098278-2db1f800-cba2-11ea-8a8f-bbd6fc900d9a.png)

**Comment by jasonlyu123** [comment]
What is your node version?

**Comment by galkatz373** [comment]
> What is your node version?

12.13.0

**Comment by jasonlyu123** [comment]
I running out of ideas of what might happened 😂. If the output window doesn't logged any useful info maybe you can check debug output, try to attach debugger to language server or even do a bunch of console logs 😝.

**Comment by galkatz373** [comment]
I tried it on another computer and it worked, I have no idea what's the problem with my pc

**Comment by galkatz373** [comment]
It was some other extension that messed everything up.
