### ISSUE TITLE
when Destructuring object that are props...  Error: Variable '*prop*' is used before being assigned.

### ISSUE THREAD

**Issue by Dulanjala007** [sveltejs/language-tools#329]
please check this :- [https://codesandbox.io/s/svelte-typescript-b5zzc?file=/src/Test.svelte](url)

in the `src/Test.svelte` has `export let service`. you can't destructure it, gives an error,
`Variable 'service' is used before being assigned.` (error shown in the terminal)
props basically can't be used for anything inside the script tag...

**Comment by jasonlyu123** [comment]
I think this error is from your one of your preprocessors. You could probably turn off the type-check in the build time and use `svelte-check` instead. This could remove some of the false-positive typescript errors.

**Comment by Dulanjala007** [comment]
I'm using vscode and svelte official extension and svelte-preprocess, there's no type checking at build time, 
just while coding, this error keep happening... same error is being logged in svelte plugin log in Output view.
I just found online example that gives the same error at build and in-editor...

**Comment by jasonlyu123** [comment]
The codepen you posted seems like a build error to me. We suppress the error if it's an `export let`. If you have a similar problem in svelte vscode maybe it's related to #277?

**Comment by dummdidumm** [comment]
You are most likely using `svelte-preprocess v3.x` without `transpileOnly: true` or another ts-preprocessor, which means your files are type-checked by `svelte-preprocess`. This shows many wrong errors. I recommend to update to `svelte-preprocess 4.x` or set `transpileOnly: true`. [Related docs](https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/typescript.md#how-do-i-import-interfaces-into-my-svelte-components-i-get-errors-after-transpilation). In general, what preprocessors report as errors is out of our hands, we just pass them through.
