### ISSUE TITLE
Bug: Commented out html is still extracted

### ISSUE THREAD

**Issue by dummdidumm** [sveltejs/language-tools#33]
You have this code:

```html
<p>bla</p>
<!--<style>h1{ color: blue; }</style>-->
<style>p{ color: blue; }</style>
```

Bug: [The extractor](https://github.com/sveltejs/language-tools/blob/d2e41cd7b7a41a14406791a815dbc8ee2a775f64/packages/language-server/src/lib/documents/utils.ts#L26) does not know the first style tag is commented out and still extracts it.

Solution: Enhance the regex to ignore styles/scripts that are commented out.

**Comment by jasonlyu123** [comment]
@jmhwang7's solution could fix this for now. 

But there are multiple edge cases related to this that need more sophisticated solutions. For example, I found out this is also a valid syntax:
```svelte
{#if name}

<script>
	console.log('a')
</script>

{/if}

<script>
	let name = 'world';
</script>
```
but only the top-level script should be treated as the instance script.

Also, these are other issues in the origin repo related to extracting tag
https://github.com/UnwrittenFun/svelte-language-server/issues/21
https://github.com/UnwrittenFun/svelte-language-server/issues/4

**Comment by dummdidumm** [comment]
Good find @jasonlyu123 , I will add new issues for those.
