### ISSUE TITLE
Example in the documentation of the vscode extension throws errors

### ISSUE THREAD

**Issue by UltraCakeBakery** [sveltejs/language-tools#332]
**Describe the bug**
When using `<style lang="text/scss">` as described in the documentation: `https://github.com/sveltejs/language-tools/blob/master/docs/README.md#generic-setup` the extension throws the following stack trace: *see screenshots*

**To Reproduce**
Create a project, follow the docs, create a `<style lang="text/scss">` element and the error should show up

**Expected behavior**
Not throw an error

**Screenshots**
![image](https://user-images.githubusercontent.com/12383587/88222122-c8bfd600-cc65-11ea-9b18-69e91bbf6679.png)

**System (please complete the following information):**
 - OS: Windows
 - IDE: VSCODE
 - Plugin/Package: `svelte.svelte-vscode`

**Comment by dummdidumm** [comment]
You either have to do `type="text/scss"` or `lang="scss"`, `lang="text/scss"` is invalid.
