### ISSUE TITLE
Svelte warning (unused export) displayed at wrong line since switching to typescript

### ISSUE THREAD

**Issue by dominic-simplan** [sveltejs/language-tools#333]
**Describe the bug**
I have just switched my svelte project from js to typescript. Since then, a warning about an unused export is displayed at the wrong line.

I don't actually know if this is caused by the language-tools or if I should open this somewhere else?

**Expected behavior**
Warning should be displayed for the correct line.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/22240239/88258561-b757e780-ccc0-11ea-997a-69bc33e60bfd.png)

First lines of the component:
```
<script lang="ts">
    import * as d3 from "d3";
    import * as formatDe from "d3-format/locale/de-DE.json";
    import { createEventDispatcher } from "svelte";

    export const NodeDetailsEvent = Object.freeze({
        LINK_EMPHASIZE: "linkEmphasize",
    });

    const dispatch = createEventDispatcher();

    export let width = "100%";
    export let height = "200px";
    export let responsive = false;
    export let selectedNode;
```

**System (please complete the following information):**
 - OS: Windows 10
 - IDE: VSCode 1.47.2
 - Plugin/Package: "Svelte for VSCode"
```
"svelte": "^3.22.3",
"svelte-check": "^0.1.55",
"svelte-loader": "^2.13.6",
"svelte-preprocess": "^4.0.8",
"typescript": "^3.9.7",
```

**Comment by jasonlyu123** [comment]
Can you check if your tsconfig has `sourcemap: false`?

**Comment by dominic-simplan** [comment]
No, this is my tsconfig.json:
```
{
    "extends": "@tsconfig/svelte/tsconfig.json",
    "include": [
        "src/**/*",
        "src/node_modules"
    ],
    "exclude": [
        "node_modules/*",
        "dist/*"
    ],
    "compilerOptions": {
        "strict": false,
        "resolveJsonModule": true
    }
}
```

**Comment by dominic-simplan** [comment]
After adding "sourceMap": true to my tsconfig, it seems that the correct line is underlined, even though I wonder why it doesn't underline the whole line.

![grafik](https://user-images.githubusercontent.com/22240239/88283404-96f15280-cceb-11ea-8870-5e6cbf083197.png)

So is this the expected behaviour? If yes, maybe the sourceMap option could be added to the tsconfig in the [blog post](https://svelte.dev/blog/svelte-and-typescript)?

**Comment by jasonlyu123** [comment]
The problem is that if the preprocessed script doesn't have a sourcemap the warning would be targeting the transpiled javascript. @orta what do you think, should it default in the `@tsconfig` module?

**Comment by orta** [comment]
We should!

**Comment by dummdidumm** [comment]
`"sourceMap": true` now part of the base config.
