### ISSUE TITLE
svelte-check reports type errors in static attributes

### ISSUE THREAD

**Issue by toby3d** [sveltejs/language-tools#336]
**Describe the bug**
![image](https://user-images.githubusercontent.com/5412322/88279333-669dba00-ccd3-11ea-9487-3a2187c8924f.png)

svelte-check complains about type errors in static (non-reactive) attributes of the input element.

**To Reproduce**
![image](https://user-images.githubusercontent.com/5412322/88279363-74ebd600-ccd3-11ea-826d-268024371fe1.png)

**Expected behavior**
svelte-check does not take these attributes as serious errors.

**System (please complete the following information):**
 - OS: Manjaro Linux
 - IDE: Sublime Text 3
 - Plugin/Package: `svelte-check`

**Comment by jasonlyu123** [comment]
Although this is quite annoying but I think this is should be the correct behavior. Like its DOM property counterpart:
```ts
const input = document.createElement('input');
input.size = '1'
```
https://www.typescriptlang.org/play/#code/MYewdgzgLgBAlmADgV1gXhgExMZBbAUzCgDpgAnAgQygIFEAbAw4gCgHIEUp2BKAbgBQgrqhJ4qADwAyRAOZQAFjAzsAjOyA

This works but typescript would complain about it. The main reason I think is that you can only set it with a numeric string. If it's only assignable with a number it could warn you accidental assign it with a string variable. Besides, fixing this is super easy. You only need to change the double quote to a mustache.

**Comment by dummdidumm** [comment]
Closing in favor of #366
