### ISSUE TITLE
svelte-check hangs for significant time on some specific .svelte module content

### ISSUE THREAD

**Issue by adamansky** [sveltejs/language-tools#337]
**Describe the bug**

Running `svelte-check` on project with the following `.svelte` module content:
```
<script lang="ts">
  ///
  ///
  /// A:
  ///

  import { onMount } from 'svelte';

</script>
```
causes `svelte-check`  eating 100% of CPU for 15 seconds on i7.

```
cd ./svelte-check-hangs

time  svelte-check 

real    0m14,159s
user    0m15,011s
sys     0m0,117s
```

**To Reproduce**
Create TypeScript project add `.svelte` module with content above.

**Expected behavior**
`svelte-check` should process this case within a 1-2 seconds

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - IDE: Any
 - Plugin/Package:  `svelte-check`

**Additional context**
Sample project attached
[svelte-check-hangs.tar.gz](https://github.com/sveltejs/language-tools/files/4966243/svelte-check-hangs.tar.gz)

*PS:*
If you add more leading comment slashes `///`  `svelte-check` *computation time will grow exponentially*. Lets try the following example:

```
<script lang="ts">

  ///
  ///
  ///
  ///
  /// A:
  ///

  import { onMount } from 'svelte';

</script>

```

**Comment by dummdidumm** [comment]
It's [this regex](https://github.com/sveltejs/language-tools/blob/4b1e1f879348eb5da8ca3c2b2ff7cab1952ccf0b/packages/language-server/src/plugins/typescript/DocumentSnapshot.ts#L342) causing heavy computation.

**Comment by mvolkmann** [comment]
Maybe there needs to be a step before the content of a file is processed where all comments are removed.

**Comment by mvolkmann** [comment]
@dummdidumm Thanks so much for this fix! The "Svelte for VS Code" extension is usable for me now!

**Comment by JohnnyFun** [comment]
fwiw, global replaces to files still gets chuggin pretty good because of formatter. In my case I did a find/replace across 369 files. I let it finish and told vscode to keep waiting. Probably took ~5-10min to finish.

I sometimes also see the formatter chugging on a single, fairly small file.

Btw, thanks for all your guys' recent work on this project!
