### ISSUE TITLE
Cannot start language server

### ISSUE THREAD

**Issue by repomaa** [sveltejs/language-tools#34]
I installed the `svelte-language-server` package and tried running it both without arguments:

 ```
$> node_modules/.bin/svelteserver
```

and with `--stdio`
 ```
$> node_modules/.bin/svelteserver --stdio
```

In both cases nothing happens. The command just exits immediately without any output. Exit code is also 0.

**Comment by jasonlyu123** [comment]
I assume you're referring this
https://github.com/sveltejs/language-tools/blob/d2e41cd7b7a41a14406791a815dbc8ee2a775f64/packages/language-server/src/server.ts#L24

This never gets release to npm. You would have to build from source to have this feature

**Comment by dummdidumm** [comment]
What are you trying to achieve?
If you want to use the extension, [install it from the extension marketplace](https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode) or from inside VSCode (it's called Svelte Beta).
If you want to participate in development of the extension, [follow these instructions](https://github.com/sveltejs/language-tools#development).

**Comment by repomaa** [comment]
I’m trying to use it with the vim plugin ale. It supports language server checkers/linters.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dummdidumm** [comment]
The `svelte-language-server` npm package is actually [from this repo](https://github.com/UnwrittenFun/svelte-language-server). This repo right here is the newer version of it, but we don't have an official npm package yet (@orta is that something we would want to do later?). How to run it from the command line - we don't know. There is another extension for Atom who uses the npm package [which does this](https://github.com/UnwrittenFun/svelte-atom/blob/master/lib/main.js):

```js
startServerProcess () {
    return super.spawnChildNode([require.resolve('svelte-language-server/bin/server.js')], {
      stdio: [null, null, null, 'ipc']
    })
  }
```

Maybe you have more luck with that. But apart from that, we cannot help you right now.

**Comment by davidroeca** [comment]
Another (neo)vim user here excited about the recent developments! A stable CLI released to npm would be awesome. I recently migrated my setup to [CoC](https://github.com/neoclide/coc.nvim) and there’s a [svelte extension](https://github.com/coc-extensions/coc-svelte) for it.

There’s also an [open issue](https://github.com/coc-extensions/coc-svelte/issues/4) which I assume will require something like this.

**Comment by dummdidumm** [comment]
Alright, I opened a new issue for the npm package topic. 

To answer the original question: This is not doable for this repo right now, only for the old. For the old one: From what I saw in the other IDE plugins so far, the command to starting the server is `svelte-language-server/bin/server.js`.

**Comment by jasonlyu123** [comment]
About the stdio support I mention before, you could refer to the original PR https://github.com/UnwrittenFun/svelte-language-server/pull/38 from origin repo. It's merged after the last release.

**Comment by orta** [comment]
We'll see how the deploy works tonight, but this might then be fixed

**Comment by dummdidumm** [comment]
`svelte-language-server` package now refers to this repo and is up to date.

Could you try some of the suggested solutions and tell us if it works?

**Comment by benmccann** [comment]
A CLI seems pretty easy to create if anyone wants to give it a shot: https://github.com/sveltejs/language-tools/issues/68

**Comment by orta** [comment]
The language-server is now regularly shipped 👍 and there's a svelte-check CLI
