### ISSUE TITLE
Go to definition on Svelte component from ts file takes you to SvelteComponentDev interface

### ISSUE THREAD

**Issue by opensas** [sveltejs/language-tools#342]
**Describe the bug**

When you ctrl-click or right-click - Go to definition on a Svelte Component from a ts file you are taken to source code of the SvelteComponentDev Interface

**To Reproduce**

Create a new ts project:

```shell
npx degit sveltejs/template svelte-typescript-app
cd svelte-typescript-app
node scripts/setupTypeScript.js
```

Open vscode

Open main.ts

in the `import App from './App.svelte';` line, ctrlk-click on `App` or on `./App.svelte`

**Expected behavior**
Take you to the App.Svelte file, like what happens when you do it from a .svelte file

**Screenshots**
![svelte-vscode-bug](https://user-images.githubusercontent.com/481687/88343313-83f47780-cd17-11ea-9289-26682a1f967a.gif)

**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - IDE: vscode
 - Plugin/Package: "Svelte for VSCode"

**Comment by jasonlyu123** [comment]
I don't know if this is possible. We currently don't provide any language feature on js/ts files. And the go to the definition is done by the typescript language feature of vscode. I don't know if there is any way to inject into their result.

**Comment by jasonlyu123** [comment]
Alternatively, anyone who wanted to quickly jump to the svelte file from any file. Use Ctrl+P to search the file.

**Comment by opensas** [comment]
I suppossed it wasn't going to be so easy to handle .ts files, just wanted to leave it here in case anybody finds out how to handle it.

BTW, great job, the plugin is marvellous!

**Comment by dummdidumm** [comment]
There exists a TypeScript plugin now which comes packaged with the VS Code extension and which you need to enable [through the settings](https://github.com/sveltejs/language-tools/tree/master/packages/svelte-vscode#svelteenable-ts-plugin). It also is [available standalone as a npm package](https://www.npmjs.com/package/typescript-svelte-plugin) if you need to use it outside of VS Code.
The plugin fixes this issue.

**Comment by CoolOppo** [comment]
I have it enabled in the settings and even added the standalone npm package as a plugin, but I still have the issue.
