### ISSUE TITLE
Autoimport from .svelte file breaks the script tag

### ISSUE THREAD

**Issue by opensas** [sveltejs/language-tools#343]
**Describe the bug**
When you auto-import a type from a svelte file, the import is added in the middle of the `<script>` tag

**To Reproduce**

Create a new ts project

```shell
npx degit sveltejs/template svelte-typescript-app
cd svelte-typescript-app
node scripts/setupTypeScript.js
```

Create a file src/helper.ts

```typescript
export class MyClass {
  name: string
}
```

create the file src/components/Label.svelte

```html
<script lang='ts'>
  import App from '../App.svelte'
  export let text = 'Hello'

  let myVar: MyClass

</script>

<h2>{text}</h2>
```

Go to `MyClass`, press click + . (quick fix), select `import MyClass from module "../helper"`

Result:

```html
<import { MyClass } from '../helper';
script lang='ts'>
  import App from '../App.svelte'
  export let text = 'Hello'

  let myVar: MyClass

</script>

<h2>{text}</h2>
```

**Expected behavior**
The import to be added inside the `<script>` tag, like this:

```html
<script lang='ts'>
  import { MyClass } from '../helper';
  import App from '../App.svelte'
  export let text = 'Hello'

  let myVar: MyClass

</script>

<h2>{text}</h2>
```

**Screenshots**
![vscode-bug-2020-07-23_19 12 34](https://user-images.githubusercontent.com/481687/88344173-67593f00-cd19-11ea-904f-5078842c50bf.gif)

**System (please complete the following information):**
 - OS: ubuntu 18.04
 - IDE: vscode
 - Plugin/Package: "Svelte for VSCode"

**Comment by jasonlyu123** [comment]
Needs to shared the logic from auto import completion.
