### ISSUE TITLE
Svelte for VS Code reports <svelte:window on:resize> as error

### ISSUE THREAD

**Issue by nilsroehrig** [sveltejs/language-tools#348]
**Describe the bug**

Given the following Svelte component written in TypeScript:

```
<script lang="ts">
  export let name: string;
</script>

<svelte:window on:resize={() => console.log('resize')} />

<h1>Hello {name}!</h1>
```

The `on:resize` part is marked as not-assignable by TS due to (supposedly?) missing property `onresize` on used type for that expression:

```
Type '{ onresize: () => void; }' is not assignable to type 'HTMLProps<Window> & SvelteWindowProps'.
  Property 'onresize' does not exist on type 'HTMLProps<Window> & SvelteWindowProps'.ts(2322)
```

**To Reproduce**

1. Setup new svelte / TS project as per instructions:
```
npx degit sveltejs/template svelte-typescript-app
cd svelte-typescript-app
node scripts/setupTypeScript.js
```
2. Open project in VS Code with 'Svelte for VS Code' extension installed and enabled
3. Edit `App.svelte` to include `<svelte:window on:resize={() => console.log('resize')} />`
4. Watch a red squiggly line appearing underneath with above mentioned error

**Expected behavior**
No error is appearing. The resize handler is accepted just as it is.

**Screenshots**
![svelte_vs_code_error](https://user-images.githubusercontent.com/1717688/88391243-16e5ee00-cdba-11ea-838e-a8ea25a9603e.png)

**System (please complete the following information):**
 - OS: Linux (elementary OS based on Ubuntu 18.04)
 - IDE: VSCode
 - Plugin/Package: "Svelte for VSCode", `svelte-language-server`, probably even type information in Svelte itself

**Additional context**
First appeared to me while tinkering with Typescript support in an existing Svelte project, reproduced in clean Svelte / TS project as described above.

**Comment by nilsroehrig** [comment]
Thank's for the quick response, great work!

**Comment by g-chandran** [comment]
Now `on:webkitfullscreenchange` also seems to be missing
