### ISSUE TITLE
Template Types: Infer truthyness in templates from {#if} blocks

### ISSUE THREAD

**Issue by AlexAegis** [sveltejs/language-tools#355]
> Pardon me if I submit this issue to the wrong repo.

```svelte
<script lang="ts">
	const foo: undefined | { bar: string } = undefined;
</script>

{#if foo}
	{foo.bar}
{/if}
```
Here there is a typescript error because foo could be `undefined` according to TS. But because of the `{#if}` block this isn't actually true, it should subtract every type from foo inside that block that wouldn't let the `if` render that part.

> While technically I could use `?.` optinal chaining here to keep TS at bay, `terser` does not support it currently and my build would fail if I did. Also it would only be a workaround.

**Comment by dummdidumm** [comment]
This is TypeScript's control flow correctly infering that, since `foo` is `const`, it can never be not undefined, so it throws an error, but not that it could be undefined but that `bar` does not exist on type `never`. If I replace `const` with `let` in your example, the error goes awy.

**Comment by AlexAegis** [comment]
Yes, you are right! Thank you
