### ISSUE TITLE
Strict types: Await block with Observables using the $ syntax, Property 'then' does not exist on ''

### ISSUE THREAD

**Issue by AlexAegis** [sveltejs/language-tools#358]
Based on this issue and this comment `rxjs` observables with `await` blocks are supported. https://github.com/sveltejs/svelte/issues/2571#issuecomment-571050281

And indeed this code snippet does the job and works (Except errors and the unresolved state but that a different issue), but it also produces a TypeScript error, and one more if `strict` settings (`noImplicitAny` to be precise) are enabled.

tsconfig.json
```json
{
	"compilerOptions": {
		"strict": true,
		"noImplicitAny": true, // set to `false` to avoid ts(7006)
	}
}
```

app.svelte
```svelte
<script lang="ts">
	import { interval, Subject } from 'rxjs';
	import { onMount } from 'svelte';

	const s$ = new Subject<number>();

	onMount(() => {
		interval(500).subscribe((i) => s$.next(i));
	});
</script>

{#await $s$}
	Loading...
{:then value} <!-- Property 'then' does not exist on type 'number'.ts(2339) -->
				<!-- Parameter 'value' implicitly has an 'any' type.ts(7006) -->
<!-- Both of these errors appear on the {:then block, but when hovering over
the `value` word in the `then` block it correctly shows the type as `number`,
while if I hover over the one below, it says `any` -->
	Value: {value}
{:catch e} <!-- Parameter 'e' implicitly has an 'any' type.ts(7006) -->
	Error: {e}
{/await}
```

`any` in a catch should always be allowed as you can't even specify types of errors in regular `catch` blocks either. TS knows this, of course, and the interesting part is when using `Promises` in the template, `e` in the 
 `:catch` block still has an `any` type but that does not produce an error, only with Observables.

**Comment by dummdidumm** [comment]
It's a svelte2tsx issue, the code assumes it's a promise. Honestly I did not even know this is possible.

**Comment by AlexAegis** [comment]
Well it seems it's just half-supported(?), and I opened another issue on the main repo https://github.com/sveltejs/svelte/issues/5206 because the await and error blocks never render with regular observables. There is timhall's https://github.com/timhall/svelte-observable lib which does solve this problem but the `Property 'then' does not exist on type 'number'.ts(2339)` error still stands with that too.

**Comment by jasonlyu123** [comment]
I look at the source of svelte's handle_promise, It seems like if the value awaiting is not a promise it will just pass the value to the block.
https://svelte.dev/repl/07ff97ba27a4403fa9e0f239cfc536e3?version=3.24.0

Along with the issue mention here
https://github.com/sveltejs/language-tools/issues/298#issuecomment-656203296
We should have a new helper function to handle then block and catch block. 

By the way, if it's an error it won't be handled. because it doesn't wrap it with a try-catch. but
```
PromiseLike.then(value => {}, error => {})
```

**Comment by AlexAegis** [comment]
> So technically you can await anything

And I believe this should be reflected by the types aswell, as I said the solution using that `observe` helper function from https://github.com/timhall/svelte-observable does make it work as expected (it wraps it in a svelte store), it's just `svelte-check` that complains about `Property 'then' does not exist on type 'number'.ts(2339)`

**Comment by jasonlyu123** [comment]
Yeah. it needs to be supported. Typescript also allow you to await on anything. But it also got me thinking what the point of this await anymore? You can't catch any errors even if svelte wrap a try catch in the generated code. Because it's similar to the following:

```ts
let a = 1
try {
  const value = await a;
} catch (error) {
  //Do something
}
```

**Comment by dummdidumm** [comment]
True, catching will never work, but the "show loading while no value, show then if there's a value" will work.
