### ISSUE TITLE
Types: Reactive fields are always `any`

### ISSUE THREAD

**Issue by AlexAegis** [sveltejs/language-tools#360]
Reactive fields (If thats that fields marked with `$:` are) are always `any` And this causes problems with `noImplicitAny` (And with regular intellisense)

tsconfig.json
```json
{
	"compilerOptions": {
		"noImplicitAny": true,
	}
}
```

app.svelte
```svelte
<script lang="ts">
	let value = 1;
	$: foo = value ? 'foo' : 'bar'; // foo is `any` here instead of the correct `string`
</script>

{#if value}{foo}{/if}
```

```sh
app.svelte:3:1
Error: Variable 'foo' implicitly has type 'any' in some locations where its type cannot be determined. (ts)
alue = 1;
        $: foo = 

app.svelte:6:13
Error: Variable 'foo' implicitly has an 'any' type. (ts)
if value}{foo}{/if}
```

Interestingly enough, any other reference made from the reactive field have a correct type again.

So this:

app2.svelte
```svelte
<script lang="ts">
	let value = 1;
	$: foo = value ? 'foo' : 'bar';
	let bar = foo;
</script>

{#if value}{bar}{/if}
```

Works! Svelte-check does not output any errors. (But it's not reactive)

**Comment by dummdidumm** [comment]
[At the moment this is known and intended](https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/typescript.md#how-do-i-type-reactive-assignments--i-get-an-implicitly-has-type-any-error), but there is a pending PR which will resolve this (#335)
