### ISSUE TITLE
Jetbrains support

### ISSUE THREAD

**Issue by maraisr** [sveltejs/language-tools#361]
**Is your feature request related to a problem? Please describe.**
I can see there is an official plugin for vscode, but not the Jetbrains?

**Describe the solution you'd like**
I can see that https://github.com/tomblachut/svelte-intellij already has a plugin, but this doesnt work. The plugin has been marked as broken, so when you install it—it specifically asks to opt into beta code. That and, if i do there is no TypeScript support.

**Describe alternatives you've considered**
Moving to vscode... But that is a much bigger ask.

**How important is this feature to you?**
Extremely. So much so that I'd try find some Java developers to help me with this.

**Additional context**
na

**Comment by dummdidumm** [comment]
Related #74

**Comment by lingster** [comment]
Hi, hope this will help, but you can get intellij support by installing the intellij-lsp from here:
https://plugins.jetbrains.com/plugin/10209-lsp-support
then in command line run:
`npm install -g svelte-language-server`
then in intellij preferences for the language server add the settings as follows:
note, you can run `which sveltesever` to find the full path of the server and replace, screenshot shows path on my mac, you milage may vary depending on your OS version: 

![Screenshot 2020-08-11 at 10 45 22](https://user-images.githubusercontent.com/850493/89883265-d19a2c80-dbbf-11ea-83c1-3c6ec508f3d3.png)

**Comment by g5becks** [comment]
@lingster This solution actually works on my end.

**Comment by vatro** [comment]
@lingster @g5becks @dummdidumm 

I just stumbled upon this thread and was very curious:
I can confirm @lingster's [solution](https://github.com/sveltejs/language-tools/issues/361#issuecomment-671846219) works on Windows10 + WebStorm 2020.3.3 + [LSP Support Plugin](https://plugins.jetbrains.com/plugin/10209-lsp-support) ! 👍

![image](https://user-images.githubusercontent.com/3778969/111541568-f3b8e600-8770-11eb-8999-a2c925ecd91b.png)
 
I quick'n'dirty tested it with this simple App created today for a ["Svelte for VSCode" issue](https://github.com/sveltejs/language-tools/issues/882#issue-833987029) and I see the **exact same autocomplete / typechecking behavior as with "Svelte for VS Code"**. The only things **missing** seems to be 👉 **syntax highlighting**! I'm very (positively) surprised by this! 😮

![image](https://user-images.githubusercontent.com/3778969/111543051-cb31eb80-8772-11eb-9e46-bbe68cc42efb.png)
![image](https://user-images.githubusercontent.com/3778969/111543072-d4bb5380-8772-11eb-8cdb-59b39d781ff8.png)
![image](https://user-images.githubusercontent.com/3778969/111543135-ef8dc800-8772-11eb-9a8e-4fef5dadcd5b.png)
![image](https://user-images.githubusercontent.com/3778969/111543223-08967900-8773-11eb-9f0e-c3e8203c6504.png)
