### ISSUE TITLE
Publish language-server to npm

### ISSUE THREAD

**Issue by dummdidumm** [sveltejs/language-tools#37]
There are some requests to use the language-server in other IDE environments (#34). We could have all plugins for these IDEs in this repo, but this might get cumbersome. So it would be better to provide the language server as a npm package.

Do we want to do this, and if yes, when?
If yes, what's the package name? (bikeshedding incoming)

**Comment by orta** [comment]
Yes, can't hurt - we can have the same automation check used for deploying to vscode, but for npm.

I'm open for us to take over the current dep if  @UnwrittenFun is into it (add @orta as an npm admin and I'll set it up on our site) ?

**Comment by dummdidumm** [comment]
Taking over the current dep sounds good!
About the deployments: If they are automatically, how do we do it with the version increase then? If I'm not mistaken, that must happen through `package.json`.

**Comment by UnwrittenFun** [comment]
@orta I have added you, lmk if theres anything else needed

**Comment by orta** [comment]
Thanks @UnwrittenFun 

I'll write a quick script to grab the current version from NPM and update the patch version

**Comment by orta** [comment]
OK, that's PR'd thanks
