### ISSUE TITLE
Is ignoring errors supported in VS code/svelte-check?

### ISSUE THREAD

**Issue by kwangure** [sveltejs/language-tools#374]
I have an expected error that I'd like the language server & svelte-check to ignore. I have `if (import.meta.env.NODE_ENV === "development")` where `import.meta.env.NODE_ENV` is replaced at build time by Vite.

I couldn't find how to ignore errors documented anywhere. If it's not supported, consider this a feature request. It'd nice to be able to use something like `// @svelte-ignore`. 

For my use-case, I could easily create a `svelte.config.js`, and use `rollup-plugin-replace` to help the language server out. The severity of this low. It's just more a bit more convenient.

**Comment by kwangure** [comment]
I've also noticed that It gives you a quick fix option to disable the error for unused variables but does nothing when you select it. 

![Screenshot 2020-07-27 at 11 48 28 pm](https://user-images.githubusercontent.com/20745107/88590748-e4f7b480-d063-11ea-8311-7f9741f61211.png)

Currently, ignoring errors should only be suggested in markup. Should I file this as a separate issue?

**Comment by jasonlyu123** [comment]
It depended on the error you want to ignore. There are three sources of error/warning now: 
1. vscode-css-language-service 
2. Svelte compiler 
3. typescript

Svelte error can't be suppressed. Only warning in the markup could, we have to remove the unused-export-let from code action.
I don't think the CSS warnings from vscode-css-language-service can be suppressed. And the typescript error, just use `//@ts-ignore`

**Comment by dummdidumm** [comment]
VS Code:
- You can [completely disable](https://github.com/sveltejs/language-tools/tree/master/packages/svelte-vscode#sveltepluginsveltediagnosticsenable) Svelte diagnostics or [set some of the warnings to ignored](https://github.com/sveltejs/language-tools/tree/master/packages/svelte-vscode#sveltepluginsveltecompilerwarnings)
- [You can disable css diagnostics](https://github.com/sveltejs/language-tools/tree/master/packages/svelte-vscode#svelteplugincssdiagnostics)
- [You can disable js/ts diagnostics](https://github.com/sveltejs/language-tools/tree/master/packages/svelte-vscode#svelteplugintypescriptdiagnostics)
- You can use `//@ts-ignore` to silence single errors
- You can use `//@ts-nocheck` to silence a whole file

`svelte-check`:
- You can [choose to ignore](https://github.com/sveltejs/language-tools/tree/master/packages/svelte-check#args) certain Svelte compiler warnings
- You can use `//@ts-ignore` to silence single errors
- You can use `//@ts-nocheck` to silence a whole file

For your specific case, do
```ts
  // @ts-ignore
  if (import.meta.env.NODE_ENV === "development") {
     ...
  }
```

**Comment by jacobmischka** [comment]
> You can use // @ts-ignore to silence single errors

Is this still true? `@ts-nocheck` seems to work fine for me, but I can't seem to get `@ts-ignore` to work.

Admittedly, I'm using the coc extension and not VS Code (https://github.com/coc-extensions/coc-svelte/issues/31), but I believe it's just directly handing off to `svelte-language-server`, which seems to otherwise be working perfectly.

Thanks!

**Comment by jacobmischka** [comment]
`svelte-check` is giving me the same issue, actually, so I'm convinced it has nothing to do with the fact that I'm using the coc extension:

```
====================================
Loading svelte-check in workspace: ...
Getting Svelte diagnostics...

.../src/components/ViewFilter.svelte:42:20
Error: An import path cannot end with a '.ts' extension. Consider importing '../wasm-wrapper.js' instead. (ts)
	// @ts-ignore
	import utils from '../wasm-wrapper.ts';

====================================
```

**Comment by dummdidumm** [comment]
That specific case could be a problem of us moving the code during transformation, which means ts-ignore is no longer above the import.

**Comment by jacobmischka** [comment]
I see. Is there a workaround you can think of?
