### ISSUE TITLE
Highlighting wrong line for unused props, when using TS

### ISSUE THREAD

**Issue by AhmedSayed77** [sveltejs/language-tools#375]
When using lang="ts" on a script tag, an unused prop warning is displayed, but on the line above the on containing said variable, if there's more than one prop. (see images below. the unused variable is "otherVar")

Running svelte-check also reports the wron line

**To Reproduce**
1- Create a new project and run setupTypescript
2- inside App.svelte, add a new prop  

**Expected behavior**
The yellow line highlighting the position of the unused prop will be correctly placed under the unused one

**Screenshots**
Using TS:
![Screenshot from 2020-07-28 02-24-12](https://user-images.githubusercontent.com/15085304/88605194-889f8f80-d079-11ea-9474-dbcd5411b4b3.png)

Not using TS:
![Screenshot from 2020-07-28 02-24-42](https://user-images.githubusercontent.com/15085304/88605202-8dfcda00-d079-11ea-9ac2-a5abaa270792.png)

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - IDE: VSCode
 - Plugin/Package: `Svelte for VSCode` and `svelte-check`

**Comment by jasonlyu123** [comment]
Duplicate of #333
