### ISSUE TITLE
Please add vsix bundle to releases

### ISSUE THREAD

**Issue by Murbal** [sveltejs/language-tools#382]
Please add the vsix bundle to your releases, so that the exension can be added to the [code-server](https://github.com/cdr/code-server) marketplace.

**Comment by dummdidumm** [comment]
You can always download it [from the marketplace](https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode) ("Download Extension" to the right). Would that be enough?

**Comment by dummdidumm** [comment]
Okay seems like you cannot do this since the terms and conditions prohibit this. But we also release to the [Open VSX registry](https://open-vsx.org/extension/svelte/svelte-vscode), could you grab it from there?

**Comment by dummdidumm** [comment]
Closing as you can download it from the [Open VSX registry](https://open-vsx.org/extension/svelte/svelte-vscode) and there seems to be willingness in the `code-server` repo to integrate that registry.
