### ISSUE TITLE
Disable the `@typescript-eslint/no-non-null-assertion` eslint rule or fix the (17) warnings

### ISSUE THREAD

**Issue by bfanger** [sveltejs/language-tools#389]
My PR failed the **CI / lint** step, but only because the current master branch contains eslint warnings.

I've looked at the warnings and some are not trivial to fix, imho.
```ts
// DocumentMapper.ts:305
 documentChanges: codeAction.edit!.documentChanges!.map((edit) =>
```

I suggest disabling the `@typescript-eslint/no-non-null-assertion` rule for the `language-server` package with an additional `.eslintrc.js` file.

**Comment by jasonlyu123** [comment]
I think your PR is just having some formatting issues like missing semi and trailing space. Running a yarn lint --fix can fix it

**Comment by dummdidumm** [comment]
You can ignore the warnings, only the errors have to be fixed, which in case of your PR are all "missing semicolon" errors which is easy to fix. We will not turn off this warning because, while we already have some, it's good to have that in mind and also see if that warning count increases.

**Comment by bfanger** [comment]
Ah, i didn't notice the scrollbar in the github action view and only the first 30 lines of `Run yarn lint` task where visible (showing only the warnings).

I've fixed the formatting issues. (  `yarn lint --fix` did the trick )
