### ISSUE TITLE
svelte-check: report also issues from .ts files, not only from .svelte components

### ISSUE THREAD

**Issue by opensas** [sveltejs/language-tools#390]
**Is your feature request related to a problem? Please describe.**

I'd like svelte-check to also check and report issues from .ts files, not only form .svelte components

**Comment by dominikg** [comment]
A workaround (or even a solution) might be `svelte-check && tsc --noEmit`

**Comment by opensas** [comment]
Thanks a lot @dominikg , that's pretty good indeed.

I had to `npm i -D watch` and then add a `"check": "watch 'svelte-check && tsc --noemit'"` to the scripts section of my package.json

Perhaps this could be integrated into svelte-check, so that we could run `svelte-check --ts-files --watch` to have that our of the box

**Comment by dominikg** [comment]
tsc has a watch mode integrated, but usually you would rely on your IDE to do live checking. spawning additional processes comes at a cost. 

unless you don't use an IDE and absolutely need the immediate Feedback, I recommend to run the check as a prebuild step

**Comment by opensas** [comment]
Yep ,I agree, it'is a good advice to leave live checking to the code editor (if using vscode it is already doing it) and reserve svelte-check for prebuild tasks.

**Comment by dummdidumm** [comment]
Starting with `svelte-check` 1.6.0, you can now pass the path to a tsconfig via the `--tsconfig` flag. This ensures only files included in that tsconfig/jsconfig are checked. TS/JS files are checked, too, then.
