### ISSUE TITLE
[Docs] Update docs to indicate that the Svelte Language Server will respect defaults and not require explicit "lang" or "type" tags.

### ISSUE THREAD

**Issue by shirakaba** [sveltejs/language-tools#398]
On each of these documentation pages, it is implied that hints such as `lang="ts"` or `lang="scss"` are required to infer the language inside a `<script>` or `<style>` tag.

* https://github.com/sveltejs/language-tools/tree/master/docs#using-with-preprocessors
* https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/typescript.md
* https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/scss-less.md

It is now clear (as confirmed by @dummdidumm on Discord) that the Svelte Language Server will respect any defaults specified in `svelte.config.js`, so it should be clarified that this is no longer a necessity as long as those defaults are defined.

**Comment by dummdidumm** [comment]
While this is true for the LSP, it is not 100% true for syntax highlighting. For this the `lang` attribute is still needed. I updated the docs accordingly.
