### ISSUE TITLE
SASS (not SCSS) Emmet completions doesn't appear or expand in VS Code or NVim

### ISSUE THREAD

**Issue by braindefender** [sveltejs/language-tools#399]
**Describe the bug**
Emmet completions doesn't appear or expand (via Tab or Expand Abbreviation command) in both VS Code and NVim.
Only syntax highlighting works.

Emmet abbreviations work in CSS, SCSS (`lang="scss"`) and PostCSS (`lang="postcss"`) but do not work with sass.

**To Reproduce**
Make `<style lang="sass"></style>` scope.
Type any abbreviation (i.e. `fz14` or `df`) and press Tab in VS Code.
Abbreviation doesn't expand and `Ctrl+Space` (show suggestions) also doesn't work.

**System**
 - OS: Windows
 - IDE: VSCode, NVim
 - Plugin/Package: Svelte for VSCode, `leafOfTree/vim-svelte-plugin`

**Comment by dummdidumm** [comment]
We use the `vscode-html-language-service` for the CSS intellisense, and that service does not support SASS unfortunately.

**Comment by braindefender** [comment]
> 
> 
> We use the `vscode-html-language-service` for the CSS intellisense, and that service does not support SASS unfortunately.

Any possibility to use something (as fallback, maybe) that Vetur use?

**Comment by dummdidumm** [comment]
While the language service does not support sass, luckily the emmet helper does, so emmet completions can be added.
