### ISSUE TITLE
Ref binds fail to understand element specific type

### ISSUE THREAD

**Issue by dkzlv** [sveltejs/language-tools#400]
**Describe the bug**
Currently, any ref binding assigns `HTMLElement` type instead of a specific element type.
I think it broke recently, because it used to work fine.

**To Reproduce**
```html
<script lang="ts">
  let ref: HTMLInputElement | undefined;
</script>

<!-- Type 'HTMLElement' is missing the following properties from type 'HTMLInputElement': accept, align, alt, autocomplete, and 49 more -->
<input bind:this={ref} />
```

**Expected behavior**
Should understand the type without help.

**System (please complete the following information):**
 - OS: Mac OS X latest
 - IDE: VSCode latest
 - Plugin/Package: Svelte for VS Code 101.7.0

**Comment by dummdidumm** [comment]
Came in through #363
