### ISSUE TITLE
Component documentation shown is not in markdown

### ISSUE THREAD

**Issue by TheComputerM** [sveltejs/language-tools#403]
I want to document my components as shown at https://svelte.dev/faq#how-do-i-document-my-components. It is said that it supports markdown yet my hover intellisense fails to show proper formatted comments.

```
<!--
  @component
  A simple material design button with ripple effect.
  - Usage:
    ```tsx
    <Button>Content</Button>
    ```
-->
```
![image](https://user-images.githubusercontent.com/24741538/89063589-10411300-d386-11ea-8592-ef3afcdf398b.png)


**System**
 - OS: Windows
 - IDE: VS Code
 - Plugin/Package: Svelte for VSCode

**Comment by jasonlyu123** [comment]
Weird. Mine works fine. The `(alias) class Button` part also has color.
Does markdown syntax highlight work fine in your vscode ?

**Comment by TheComputerM** [comment]
Syntax highlighting is perfect, is this a problem with my vs code theme?

**Comment by jasonlyu123** [comment]
Don't know why is your markdown doesn't get parsed. It probably is related to your theme. 
If you have this before a class in ts file does it work?
```js
/**
* 
* A simple material design button with ripple effect.
*  - Usage:
* ```tsx
* <Button></Button>
* ```
*/
```

**Comment by TheComputerM** [comment]
Syntax highlighting in typescript is working:

![image](https://user-images.githubusercontent.com/24741538/89098433-3e196c80-d405-11ea-91ba-3d5c25dd9610.png)

**Comment by dummdidumm** [comment]
I cannot reproduce this either (using default light theme). Is this reproducible for you with other themes?

**Comment by TheComputerM** [comment]
Changing the theme did not solve anything, but look at this
![image](https://user-images.githubusercontent.com/24741538/89184511-90e65600-d5b6-11ea-87b2-1912c4fd9f3e.png)

When I hover over the imported button, it is in markdown but when I hover over the component itself, it is not in markdown

**Comment by dummdidumm** [comment]
Ah now I get what you are talking about, it's the documentation appearing in the context of auto completions, not in the context of hovering with the mouse. I was looking in the wrong place. I can reproduce it now.

**Comment by TheComputerM** [comment]
Thanks @dummdidumm, very cool 👍.
