### ISSUE TITLE
Language server does not start properly with --stdio flag of svelteserver

### ISSUE THREAD

**Issue by yaegassy** [sveltejs/language-tools#404]
## Describe the bug

I mainly use `Vim` and am trying to use `svelteserver` using the LSP client plugin called `coc.nvim`.

coc.nvim has a very nice dedicated extension the `coc-svelte`.

coc.nvim can also be used to set up a language server without the need for a dedicated extension.

I found this when I set up svelteserver without a dedicated extension, and it starts fine with the `--node-ipc` flag, but `--stdio` can't start the server.

By the way, coc.nvim itself has a proven track record with many language servers, so there should be no problems.

## Screenshots

Sorry for the "coc.nvim example", but I've attached a screen capture.

**[NG] DEMO**

coc.nvim settings (coc-settings.json):

```json
    "svelte-language-server": {
      "command": "svelteserver",
      "args": ["--stdio"],
      "filetypes": ["svelte"]
    },
```

![svelte-language-server-issue-1](https://user-images.githubusercontent.com/188642/89078736-ea386480-d3bf-11ea-93fd-6706eed7cb5b.gif)

## Misc

Do you know of any other editors or IDEs that work properly with the `--stdio` flag?

If you have one, I'd appreciate it if you could let me know so I can reference it.

If the `--stdio` flag is not working properly, it may be difficult to integrate with other editors/IDEs.

**Comment by yaegassy** [comment]
@jasonlyu123 @dummdidumm 

This [PR](https://github.com/sveltejs/language-tools/pull/420) here confirmed that it works properly with `--stdio`. Thanks for the fix.

Please publish the latest version of `svelte-language-server` to npm so that installation is easy.

**Comment by jasonlyu123** [comment]
@yaegassy it'll be automatically update at around 4: 10 utc that about 30mins from now

**Comment by yaegassy** [comment]
@jasonlyu123 Thanks publish to npm!
