### ISSUE TITLE
`svelte-ignore` not respected for custom element tags

### ISSUE THREAD

**Issue by kwangure** [sveltejs/language-tools#409]
**Describe the bug**
`svelte-ignore` warning is not ignored in VS Code.

**To Reproduce**
Steps to reproduce the behaviour:

```html
<!-- svelte-ignore missing-custom-element-compile-options -->
<svelte:options tag="my-element"/>
```

**Expected behaviour**
The warning should not be displayed when svelte-ignore is present. 

**Screenshots**
![Screenshot 2020-08-01 at 8 54 23 pm](https://user-images.githubusercontent.com/20745107/89107409-9bc7ac00-d439-11ea-8d00-ace16f9e5c3d.png)
![Screenshot 2020-08-01 at 8 54 13 pm](https://user-images.githubusercontent.com/20745107/89107410-9d916f80-d439-11ea-9568-52f28fe8ca34.png)

**System (please complete the following information):**
 - OS: MacOS
 - IDE: VS Code
 - Plugin/Package: Svelte for VS Code

**Additional Context**
Ignoring works for other warnings such as `<!-- svelte-ignore a11y-missing-attribute -->` on an `img` without an `alt` attribute.

**Comment by jasonlyu123** [comment]
This means svelte compiler don't allow suppressing this warning. We'll have removed that from svelte-ignore code action.
