### ISSUE TITLE
`import type` results in "Unexpected token" error

### ISSUE THREAD

**Issue by s11k** [sveltejs/language-tools#417]
**Describe the bug**
Using TypeScript's `import type` syntax in a Svelte component results in a `Unexpected token: '=' expected` error.

**To Reproduce**

+ `npx degit sveltejs/template svelte-typescript-app`
+ `cd svelte-typescript-app`
+ `node scripts/setupTypeScript.js`
+ `echo "export interface Thing {};" > src/thing.ts`
+ Modify App.svelte:

```svelte
<script lang="ts">
    import type { Thing } from "./thing";
</script>
```

**Expected behavior**
The type should be imported as expected.

**Screenshots**
<img width="496" alt="image" src="https://user-images.githubusercontent.com/270691/89217946-f8ce7980-d581-11ea-9107-83c9e0c7722d.png">

**System (please complete the following information):**
 - OS: MacOS
 - IDE: VS Code
 - Plugin/Package: Svelte for VSCode 101.7.1

**Additional context**
#279 had the same issue, but was due to an array of pre-processors. The same issue appears when using sveltejs/template where only a single pre-processor is used.

Also, `import { Thing } from "./thing";` appears to silence the error, however when this is used in another Svelte+TypeScript project, I receive the error:

```
This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
```

I'm not sure why that error isn't generated in the sveltejs/template project.

Thank you!

**Comment by dummdidumm** [comment]
Very strange, I cannot reproduce this at all. I assume you ran `npm install` after running the node-script, but even without doing that I do not get the error.
From your message it seems that the language server thinks that this is a JavaScript file.

Some suggestions into the blue:
- Does this error persist if you restart VSCode?
- Did you install the old "Svelte" extension and not uninstall it? Maybe that one is still installed? You can find it when searching for `@installed` in the extensions window (searching Svelte won't work). You can also look into the "Output" tab and see if there are two "Svelte" entries. If yes, that also hints at an old installation.

**Comment by s11k** [comment]
Oh, shucks! I did end up having the old extension installed. Removing it fixed the issue. D'oh!

Thanks for the quick response and for your contributions to dev tooling for Svelte!

**Comment by Spenhouet** [comment]
I came here with an issue using storybooks and typescript. For me this was the solution: https://github.com/storybookjs/storybook/issues/12754#issuecomment-708884287

**Comment by turn-a-round** [comment]
I get the same issue and it persists even after VS Code restart or the Svelte extension re-installing. For me, when I checked the Svelte extension `Output` window, it was complaining about `No svelte.config.js found. Using https://github.com/sveltejs/svelte-preprocess as fallback`. Then I realize, I changed the file to svelte.config._**t**s_ a while ago. after I rename it back to svelte.config._**j**s_, it started working.

**Comment by fetimo** [comment]
Just in case anyone else comes across this issue I had a silly mistake where my type import was in `<script context="module">` instead of `<script lang="ts">`.

**Comment by rigu** [comment]
In case if help someone: on my side is happen because IntellijIdea editor set `<script **type**="ts">`. 
Changed to be `<script **lang**="ts">`, it started to work

**Comment by wmurphyrd** [comment]
Another case - was missing `svelte.ts` files in the eslint.config.js. Maybe fixed in newer templates, I ha created this while svelte 5 was in prerelease

```
  {
-     files: ['**/*.svelte'],
+     files: ['**/*.svelte', '**/*.svelte.ts'],
    languageOptions: {
      parserOptions: {
        parser: ts.parser,
      },
    },
  },
```
