### ISSUE TITLE
Support defaults: { script: 'typescript' } in svelte.config.js

### ISSUE THREAD

**Issue by miridius** [sveltejs/language-tools#422]
Svelte preprocess allows setting default languages for markup, script, and styles of svelte components (https://github.com/sveltejs/svelte-preprocess/blob/master/docs/getting-started.md#31-setting-default-languages). However, it seems that the svelte language tools do not respect setting the default language to typescript, because I get error highlighting in VS Code due to the scripts still being interpreted as vanilla JS. For example:

![image](https://user-images.githubusercontent.com/44704707/89280846-80cb8680-d649-11ea-965d-a10898410fea.png)

My svelte.config.js looks like this:
```js
import autoPreprocess from 'svelte-preprocess';
import postcssImport from 'postcss-import';

const production = !process.env.ROLLUP_WATCH;

export default {
  preprocess: [
    autoPreprocess({
      sourceMap: !production,
      postcss: { plugins: [postcssImport(), require('autoprefixer')()] },
      defaults: { script: 'typescript', style: 'postcss' },
    }),
  ],
};
```

Compilation (with rollup) works fine using the above config, it's just the IDE that complains about typescript in my <script> tags (incidentally though, the IDE seems to be happy with me using postcss directives in plain style tags). I have restarted the svelte language server as well as VS Code itself so I assume the issue is that this is a feature that is not yet implemented.

**Comment by dummdidumm** [comment]
This does work, but your `svelte.config.js` is invalid. [You cannot use the `import` and `export default` syntax in it](https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/in-general.md).
