### ISSUE TITLE
[svelte-check] show which css selector is unused

### ISSUE THREAD

**Issue by TheComputerM** [sveltejs/language-tools#434]
When showing the warning `Warn: Unused CSS selector (svelte)`, if this could also show which selector is unused would be very useful, especially for components with large CSS content

**Comment by dummdidumm** [comment]
Are you talking about svelte-check or the VSCode extension? In case of the extension the corresponding line is highlighted. In case of svelte-check (human mode) the surrounding characters at the position are printed.

**Comment by TheComputerM** [comment]
But when the style with src is used it highlights the style tag

**Comment by dummdidumm** [comment]
Oh okay, have not thought of this situation. Well then we definitely need the name from the compiler.

**Comment by sdwvit** [comment]
what a stupid f**ing 💩🤡💩 is this 
![image](https://user-images.githubusercontent.com/8777372/92628666-27cfbd80-f29b-11ea-9fc7-2bd6a9a0f2a6.png)

**Comment by dummdidumm** [comment]
Fixed with Svelte `3.25.0`.
