### ISSUE TITLE
ordering style-script-markup blocks

### ISSUE THREAD

**Issue by beebase** [sveltejs/language-tools#436]
Is there a setting to change the order of blocks?
<script..
<html...
<style...

**Comment by jasonlyu123** [comment]
if you mean format
https://github.com/sveltejs/prettier-plugin-svelte#configure-for-vs-code-and-atom

**Comment by asv1** [comment]
How to make it global? Not per project.

**Comment by dummdidumm** [comment]
There is no option to do so currently
