### ISSUE TITLE
VSCode auto formatter compresses each loop to single line

### ISSUE THREAD

**Issue by georgebzhang** [sveltejs/language-tools#451]
**Describe the bug**
{#each items as item}
  {item}
{/each}

gets automatically formatted (Option + Shift + F) in VSCode to

{#each items as item}{item}{/each}

Would much prefer if the auto formatter did not compress the each loop to a single line.

**To Reproduce**

For example a code snippet that is treated in a way you don't expect.

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: Macbook Pro 2018
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode

**Additional context**

**Comment by dummdidumm** [comment]
The source of this problem is [prettier-plugin-svelte](https://github.com/sveltejs/prettier-plugin-svelte) which does the formatting. Could you open the issue over there?

**Comment by georgebzhang** [comment]
Thank you, @dummdidumm, just opened the issue: https://github.com/sveltejs/prettier-plugin-svelte/issues/117

**Comment by dummdidumm** [comment]
`prettier-plugin-svelte 2.x` now keeps newlines if the user desires it. The extension now comes prepacked with the newest version. If you use `prettier-plugin-svelte` locally within your project, you need to bump that version.
