### ISSUE TITLE
Semicolon Inference

### ISSUE THREAD

**Issue by freethebit** [sveltejs/language-tools#456]
This issue still happening: https://github.com/UnwrittenFun/svelte-vscode/issues/93

`export` without semicolon, syntax highlighting breaks on the closing `</script>` tag

**Comment by jasonlyu123** [comment]
https://github.com/sveltejs/language-tools/issues/320
it's likely cause by the other extension.

**Comment by freethebit** [comment]
Thanks! Yes, it was `Babel Javascript` plugin (0.0.29) like mentioned in #320.
