### ISSUE TITLE
#each block breaks syntax highlighting

### ISSUE THREAD

**Issue by jmhwang7** [sveltejs/language-tools#47]
In VS code, an each block breaks syntax highlighting for that line and the rest of the file. It appears as a comment (I think due to `#`).

<img width="793" alt="Screen Shot 2020-04-28 at 4 49 54 PM" src="https://user-images.githubusercontent.com/2397765/80548678-51cdb680-8970-11ea-91f4-ebe7f27c71dc.png">

Test case (smaller version of https://svelte.dev/tutorial/keyed-each-blocks):
```
<script>
    import Thing from './Thing.svelte';
    let things = [
        { id: 1, color: '#0d0887' },
        { id: 2, color: '#6a00a8' }
   ];
</script>
{#each things as thing} 
	<Thing current={thing.color}/>
{/each}
```

Happy to take a stab at fixing this if someone can give me pointers.

**Comment by jasonlyu123** [comment]
I see the language mode has been set to HTML in your screenshot. Seems to because of that?

**Comment by jmhwang7** [comment]
@jasonlyu123 That's a really good observation! If I recall correctly, I think it's because I followed this: https://github.com/sveltejs/svelte/wiki/FAQ#how-can-i-get-vscode-to-syntax-highlight-my-svelte-files

Should I be setting it to JS instead?

**Comment by jasonlyu123** [comment]
If you have the svelte/svelte beta extension installed, there will be a 'svelte' option.

**Comment by jmhwang7** [comment]
oh man!! that's awesome! I'll go ahead and close this issue and file a ticket to update the documentation on the site. 

Thank you!
