### ISSUE TITLE
Add option to ignore/not show certain Svelte compiler warnings

### ISSUE THREAD

**Issue by dummdidumm** [sveltejs/language-tools#473]
**Is your feature request related to a problem? Please describe.**
People might feel annoyed by some Svelte compiler warnings. Some can be ignored through `svelte-ignore` (which might get cumbersome), some cannot at all be ignored.

**Describe the solution you'd like**
Add a setting to the extension and an arg to `svelte-check` through which you can declare a list of compiler warning ids which should be ignored.

Example for `svelte-check`: `svelte-check --ignore-svelte-compiler-warnings="bla,unused-css-selector"`

**Describe alternatives you've considered**
Leave it as is to make people aware they have problems in their code. But sometimes this may be wrong.

**Additional context**
We should not advokate this too much as my fear would be that people use this as a shortcut to just not care about accessibility-warnings anymore.

**Comment by dummdidumm** [comment]
Thats a good idea. I will add two options, one for ignoring errors, one for setting them to error.

Proposed names:
- `ignored-compiler-warnings`
- `compiler-warnings-as-errors`

**Comment by lgrahl** [comment]
So, here's a question to this feature which I think is essential: Where do I get the warning ID from? The output doesn't give me any clue whatsoever:

```
Warn: Unknown property: 'r' (scss)
      r: calc((40px - var(--cpc-t-thickness)) / 2);
```

**Comment by dummdidumm** [comment]
Only Svelte compiler warnings can be ignored, the one you pasted is a SCSS warning. Everything that has "svelte" as source can be ignored. Such warnings have a code in the info, like "unused-css-selector".

**Comment by lgrahl** [comment]
Okay, thanks for this clarification! Hope we can get this more refined in the future because right now I'll have to ignore all CSS warnings because of this false positive.
