### ISSUE TITLE
Syntax highlighting breaks in multi-line attributes

### ISSUE THREAD

**Issue by brunnerh** [sveltejs/language-tools#478]
**Describe the bug**
If an attribute value contains multiple lines and the first line has no interpolation, the syntax highlighting of interpolations in later lines will not be applied.

**To Reproduce**

Example component:

```svelte
<script>
	export let question = 'Really';
	export let flag = true;
</script>

<!-- Second line highlighted. -->
<div title="{question}?
	{flag ? 'Yes' : 'No'}"/>

<!-- Second line not highlighted. -->
<div title="Really?
	{flag ? 'Yes' : 'No'}"/>
```

(The same seems to be true for the highlighting on GitHub.)

**Expected behavior**
Syntax highlighting on all interpolations.

**Screenshots**

![image](https://user-images.githubusercontent.com/834235/91206229-1c12c180-e707-11ea-9aae-8d8cdd91cd5f.png)

**System (please complete the following information):**
 - OS: Windows 10, 64bit
 - IDE: VSCode 1.48.1
 - Plugin/Package: Svelte for VSCode (v101.10.0)

**Comment by dummdidumm** [comment]
If this is fixed, the syntax highlighting part of #381 is probably fixed, too.
