### ISSUE TITLE
Attribute draggable is not boolean 

### ISSUE THREAD

**Issue by brunnerh** [sveltejs/language-tools#481]
**Describe the bug**
[`draggable`](https://html.spec.whatwg.org/multipage/dnd.html#the-draggable-attribute) has three states, "true", "false" and auto (missing value). Currently that is flagged as an error when TypeScript checking/preprocessing is active.

```
(JSX attribute) svelte.JSX.HTMLAttributes<HTMLDivElement>.draggable?: boolean
Type 'string' is not assignable to type 'boolean'.ts(2322)
```

This might just require a type change in `svelte-jsx.d.ts` to something like the type of `contenteditable` (`"true" | "false" | boolean`).

**To Reproduce**

Example component:

```svelte
<script type="text/typescript">
</script>

<div draggable="true"/>
```

**Expected behavior**
Values "true" and "false" are accepted.

**System (please complete the following information):**
 - OS: Windows 10, 64bit
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode

**Workaround**

Interpolate boolean:

```svelte
<div draggable={true}/>
```

**Comment by dummdidumm** [comment]
Same reason as #366 , only for booleans instead of numbers.
