### ISSUE TITLE
Can't build with yarn v2

### ISSUE THREAD

**Issue by lyuha** [sveltejs/language-tools#498]
Can't build project using yarn v2.
I can't build workspace with any options like `pnpMode: loose` and `nodeLinker: node-modules`.

**Comment by dummdidumm** [comment]
A little more context please. What workspace? If you are talking about the workspace if this repo, then you need to use yarn 1.

**Comment by lyuha** [comment]
workspace means feature in yarn.
yarn 1 works. have no future plan to upgrade?
With yarn 2, `yarn bootstrap` emit error like `Required package: builtin-modules (via "builtin-modules")` in `packages/svelte2tsx`. yarn 2 needs to declare its dependencies explicitily.

**Comment by dummdidumm** [comment]
Ok so you are talking about this repository right here. We don't have any plans to update to Yarn 2 at the moment, please use Yarn 1.
