### ISSUE TITLE
#await :then support

### ISSUE THREAD

**Issue by Zerowalker** [sveltejs/language-tools#51]
**#await then** doesn't seem to be supported

Example code:

```
{#await foo()}
    .....
  {:then}
      async function completed successfully!
  {:catch err}
      async function failed:(
{/await}
```

**{:then}** will be showed with an error, but it shouldn't as far as i know

**Comment by Zerowalker** [comment]
Okay the error is from a plugin that uses this, so maybe i should write there instead:S
Not sure which part is responsible for what.

**Comment by dummdidumm** [comment]
What exactly is the error that is shown?

What do you mean by "plugin that uses this"?

**Comment by Zerowalker** [comment]
Sorry, the plugin (extension in vscode) that shows the error is:  https://github.com/halfnelson/svelte-type-checker-vscode

The error it shows is: 

`let _$$p: Promise<void>
',' expected.svelte-type-checker(1005)`

Hope that clears things up a bit.

**Comment by dummdidumm** [comment]
Thanks for the clarification. This is then actually a bug within said plugin, not this repo, so I'm going to close here. Still thank you for bringing this up since we are exploring using the same underlying mechanisms as said plugin, so we will have an eye out for this case.
