### ISSUE TITLE
the vscode 'problems' show css(unknownAtRules) on @tailwinds inside inline styling

### ISSUE THREAD

**Issue by eisenhaus335** [sveltejs/language-tools#515]
**Describe the bug**
I already disable css, scss, less lint from vscode. But its seems there is another svelte built in validation 'style' that keep warn me on 'unknownAtrules'. I using tailwind css for this. I kinda lack knowledge on scss so i might dont has precise word to describe it
Is there any guide to mitigate this issue? Or if its enough just how to ignore this warning... its kinda annoying
**Logs**
![image](https://user-images.githubusercontent.com/25275731/91937425-137c4580-ed1c-11ea-8bdc-b6f6be126f6e.png)

**Comment by dummdidumm** [comment]
This is a VSCode extension question, not Svelte core. [Have look at the docs](https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/other-css-preprocessors.md#tailwindcss) on how to setup support for TailwindCSS.
