### ISSUE TITLE
Go to definition inside yarn workspace doesn't work

### ISSUE THREAD

**Issue by krevativ** [sveltejs/language-tools#537]
**Describe the bug**
You can't jump to definition when the component is imported from a package inside of a yarn workspaces

**To Reproduce**
Clone https://github.com/lokhmakov/svite-monorepo and try to jump from apps/client/src/App.svelte to the Button definition.

**Expected behavior**
VSC is expected to jump to packages/screens/src/Button.svelte or at least packages/screens/src/index.js

**System:**
 - OS: Linux Mint 20
 - IDE: VSC 1.49.0
 - Node: v12.18.3
 - Plugin/Package: svelte.svelte-vscode 101.13.1

**Comment by jasonlyu123** [comment]
Create a `jsconfig.json` in your workspace root with the following config

```json
{
  "compilerOptions": {
    "paths": {
      "@svite-monorepo/screens": ["packages/screens/src"]
    },
    "baseUrl": "."
  }
}
```

This is a general config for typescript's language service, which also power the javascript language features in the svelte language server, so I am going to remove the bug label.
