### ISSUE TITLE
Svelte for VS Code is inserting 2 spaces at document formating, instead tab (with size 4), as is set in VS Code.

### ISSUE THREAD

**Issue by Mlocik97** [sveltejs/language-tools#539]
**To Reproduce**
install Svelte for VS Code
npx degit svelte/sapper-template#rollup
open for example _error.svelte
set "intend using tab size 4" and convert
ctrl+shift+i -> get two spaces.

```html
<svelte:head>
  <title>{status}</title>
</svelte:head>

<h1>{status}</h1>

<p>{error.message}</p>

{#if dev && error.stack}
  <pre>{error.stack}</pre>
{/if}
```

**Expected behavior**

**Screenshots**
![Snímka obrazovky z 2020-09-14 16-07-53](https://user-images.githubusercontent.com/34808350/93096278-79fe4d80-f6a4-11ea-925d-911227c3baf7.png)

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - IDE: VS Code
 - Plugin/Package: [Svelte for Code]

**Comment by dummdidumm** [comment]
Formatting is done with Prettier, but we do not fall back to the user settings if there is no prettier config. We should do something [similar to the Prettier VSCode Plugin](https://github.com/prettier/prettier-vscode/blob/main/src/ConfigResolver.ts).

**Comment by dummdidumm** [comment]
You will not be able to indent on a per-file level, so doing the indentation like that will not work even after we fix the settings bug. But the indentation in your user settings should be adhered to after the fix.

**Comment by dummdidumm** [comment]
Looks like we can use the `FormattingOptions` parameter of the LSP request to get the desired behavior - but we will only use it if no prettier config is found. I'll also have to check with the other maintainers if this is a change we want to make, because it's a breaking change.

**Comment by dummdidumm** [comment]
This will now work IF you don't have any prettier configuration in either your VSCode settings or through a config file.

**Comment by Mlocik97** [comment]
@dummdidumm 

https://www.youtube.com/watch?v=eHazE93BClo&feature=youtu.be&ab_channel=GabrielMlocik

**Comment by Mlocik97** [comment]
thanks so much, it's working now.
