### ISSUE TITLE
Disable CSS checking when using svelte-check

### ISSUE THREAD

**Issue by niftykins** [sveltejs/language-tools#541]
**Is your feature request related to a problem? Please describe.**
I use stylus for CSS and when running `svelte-check` it produces many `Error: { expected (css)`/`Error: media query expected (css)`. In vscode I've disabled css via `"svelte.plugin.css.enable": false` to ignore these errors in the editor.

**Describe the solution you'd like**
CLI option (or anything) that allows disabling the CSS plugin when running `svelte-check`

**Describe alternatives you've considered**
I've tried using `lang="postcss"` on the style tags after reading the docs but that ruins all syntax highlighting

**Comment by dummdidumm** [comment]
We should probably provide this behavior/option for all three categories: JS/TS, Svelte, CSS.

**Comment by dummdidumm** [comment]
You can use the new `diagnostic-sources` option to achieve this: `--diagnostic-sources "js,svelte"`
