### ISSUE TITLE
Aliased, auto-subscribed store import doesn't work along with reactive declaration

### ISSUE THREAD

**Issue by AlexGalays** [sveltejs/language-tools#549]
```svelte
<script>
  import {route as routeStore} from './routeStore'
  $: route = $routeStore
</script>
```
![image](https://user-images.githubusercontent.com/1375586/93586827-31e37180-f9a9-11ea-8cd4-79782f8856a3.png)

It's like the original name is reserved, even though the symbol shouldn't even be in scope.
FYI, this may seem like a weird thing to do but it's convenient to workaround https://github.com/sveltejs/language-tools/issues/493

**Comment by dummdidumm** [comment]
Our top variables tracker tracks both `route` and `routeStore` from `route as routeStore`, which is wrong.
