### ISSUE TITLE
TS: Named export from module script not recognized

### ISSUE THREAD

**Issue by IgnusG** [sveltejs/language-tools#550]
**Describe the bug**
Importing named exports from `<script context='module'>` returns an error saying:

Module '"*.svelte"' has no exported member ...

![image](https://user-images.githubusercontent.com/6438760/93609638-64529600-f9cc-11ea-95f9-ec8d23ab03e8.png) 

> The image is from a test file that imports both the component and the helper method

The svelte component looks like this:

```svelte
<script context="module" lang="ts">
export const reverseValue = (min: number, max: number) => (
  scale: number,
): number => max - scale + min;
</script>

...
```

<details>
<summary>Typescript Config</summary>
<pre>
{
  "extends": "@tsconfig/svelte/tsconfig.json",
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {"*": ["*", "typings/*"]},
    "noImplicitAny": true,
    "emitDecoratorMetadata": true,
    "skipLibCheck": true,
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "noImplicitReturns": true,
    "noUnusedParameters": true,
    "strictFunctionTypes": true,
    "strictNullChecks": true,
    "types": ["jest", "chrome", "node"],
    "allowJs": true,
    "isolatedModules": false,
    "target": "ESNext",
    "allowSyntheticDefaultImports": true
  },
  "include": ["src/**/*.ts", "src/**/*.tsx", "src/**/.svelte", "typings/*.d.ts", "test/*.ts"],
  "exclude": ["node_modules"]
}
</pre>
</details>

- Svelte: `3.24.1`
- Svelte Preprocess: `4.2.1`
- Svelte TS Config: `1.0.10`
- Typescript: `4.0.2`

**Expected behavior**
The exports should be recognized

**Severity**
Not severe. Just a small hindrance

**Comment by IgnusG** [comment]
I'm actually using this awesome plugin by @mrmckeb https://github.com/mrmckeb/typescript-plugin-css-modules :)  
It works very well at least within VS Code.

For the compilation step maybe it could be possible to add an option to the [typescript preprocessor for svelte-preprocess](https://github.com/sveltejs/svelte-preprocess/blob/master/src/transformers/typescript.ts) to generate the declaration for every svelte component while running. If I a tool uses svelte-preprocess it would then immediately get the correct typings

**Comment by jasonlyu123** [comment]
https://github.com/microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin

Seems like angular language service use the plugin technique. We could probably learn something from their code 😂.

**Comment by mrmckeb** [comment]
I'm not sure you want to learn from my code haha, but if you have any questions I'll do my best to answer. Thanks for the shout @IgnusG.

The only note I'll make is that Language Service plugins only run in IDEs, not during build-time. People have been asking for this change for a while, but the TypeScript team don't seem convinced that it's a good direction.

**Comment by dummdidumm** [comment]
There exists a TypeScript plugin now which comes packaged with the VS Code extension and which you need to enable [through the settings](https://github.com/sveltejs/language-tools/tree/master/packages/svelte-vscode#svelteenable-ts-plugin). It also is [available standalone as a npm package](https://www.npmjs.com/package/typescript-svelte-plugin) if you need to use it outside of VS Code.
The plugin fixes this issue.
