### ISSUE TITLE
Debugging with VS Code

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/language-tools#552]
Is there a way to debug with VS Code?

If I use this `launch.json`:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome against localhost",
      "url": "http://localhost:5000",
      "webRoot": "${workspaceFolder}"
    }
  ]
}
```

Chrome crashes every time it hit a breakpoint!

**Comment by dummdidumm** [comment]
What do you mean? The language-tools repo code itself, or a Svelte application?

**Comment by frederikhors** [comment]
Svelte apps.

**Comment by dummdidumm** [comment]
Debugging Svelte apps is a question unrelated to this repository. I suggest you do a quick Google search how others have done it and open a StackOverflow question if there's no solution to be found.
