### ISSUE TITLE
Expand selection in VS Code doesn’t work correctly while the language mode is svelte.

### ISSUE THREAD

**Issue by KocsisGabor** [sveltejs/language-tools#556]
[Expand selection](https://code.visualstudio.com/docs/editor/codebasics#_shrinkexpand-selection) is `Shift+Alt+Right` by default.  

The expected behavior is demonstrated in the second half of the gif below.   
It should expand the selection by tag/scope/bracket, etc…  but works only inline and as soon as the selection should grow into multiple lines it selects the whole document.  

No alternative solutions work with any of the extensions either (e.g.: expand-region).   

![This is what happens](https://user-images.githubusercontent.com/3774059/93962975-4c786a80-fd5c-11ea-9854-50034b19158e.gif)

**System:**
 - OS: Windows
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode

**Comment by jasonlyu123** [comment]
This is a feature request so I removed the bug label.

**Comment by jasonlyu123** [comment]
Wondering if we should do this with svelte AST or HTML. 

Downside of the former is it won't work when there's syntax errors. Or maybe somehow we could make it fallback to HTML.

**Comment by KocsisGabor** [comment]
Personally I don’t mind at all if it only works when there is no syntax error. 

This is not a real solution of course but until this issue is solved, we can use the “Emmet: Balance (outward)” command or a keyboard shortcut like this one:

```json
{
  "key": "shift+alt+right",
  "command": "editor.emmet.action.balanceOut",
  "when": "editorTextFocus && editorLangId == svelte"
}
```

This is not equivalent to “expand selection” but it is better than nothing.

**Comment by MartinBspheroid** [comment]
do we have any update on this? I used to use this a lot with React and Typescript and I guess some other people as well.
