### ISSUE TITLE
Syntax Error when using <h6> with inlines components

### ISSUE THREAD

**Issue by j3rem1e** [sveltejs/language-tools#560]
**Describe the bug**

I have two components: 

**Child.svelte**

```html
<slot {t}/>

<script>
  const t = '';
</script>
```

**Parent.svelte**

```html
<script>
import Child from './Child.svelte'
</script>

<h6><Child let:t>xx</Child><h6>
```

In VS Code, `</Child>` has the following errors: 
* Expected corresponding closing tag for JSX fragment
* ';' expected
* Identifier expected.
* Unexpected token. Did you mean `{'}'}`or `&rbrace;`?
* Expected corresponding JSX closing tag for 'Child'

svelte2tsx has generated this invalid code (the closure doesn't close correctly)

```jsx
<h6><Child >{() => { let {t} = __sveltets_instanceOf(Child).$$slot_def['default'];<>xx</Child></>}}</h6></>);
```

**To Reproduce**
See the components above

**Expected behavior**
No errors in vscode

**System (please complete the following information):**
 - OS: Windows 10
 - IDE: VSCode

**Comment by j3rem1e** [comment]
The bug is here : https://github.com/sveltejs/language-tools/blob/master/packages/svelte2tsx/src/htmlxtojsx/nodes/component.ts#L83

It should be 

```
const closeTagStart = htmlx.lastIndexOf('<', slotEl.end - 1);
```

**Comment by dummdidumm** [comment]
PR welcome if you solved it 🎉

**Comment by dummdidumm** [comment]
Thanks for the PR! I'll close when it's released.
