### ISSUE TITLE
VSCode: Implement reference browser command (editor.action.referenceSearch.trigger)

### ISSUE THREAD

**Issue by Ciantic** [sveltejs/language-tools#566]
**Is your feature request related to a problem? Please describe.**

VSCode has this command to list and browse references, command for that is called `editor.action.referenceSearch.trigger`

Example from JS file, it can be used to browse and navigate between references:

![image](https://user-images.githubusercontent.com/64731/94135808-a6685580-fe6c-11ea-89ff-9666e322d341.png)

I use it all the time in other languages to navigate. This is a missing feature from the language server I think. It could be added to the checkbox list in here: https://github.com/sveltejs/language-tools/issues/83

Thanks for considering.

**Comment by dummdidumm** [comment]
[LSP Spec](https://microsoft.github.io/language-server-protocol/specification#textDocument_references) which we would need to implement.

**Comment by dummdidumm** [comment]
Find references now works inside Svelte files. Note though that you will not find references of Svelte files when doing the "find references" search from a TS/JS file. This is tracked in #580 .
