### ISSUE TITLE
Exporting Typescript enums from components raises a warning

### ISSUE THREAD

**Issue by bencates** [sveltejs/language-tools#573]
**Describe the bug**
Exporting a typescript `enum` or `const enum` from a `<script context="module" lang="ts">` block raises a "svelte(unused-export-let)" warning.

**Expected behavior**
Exporting enums is allowed without warning.

**Screenshots**
![image](https://user-images.githubusercontent.com/431849/94292988-ebe35c00-ff1a-11ea-890a-385991093612.png)

**System (please complete the following information):**
 - OS: Linux
 - IDE: VSCode
 - Plugin/Package: ?

**Additional context**
Exporting a `type` or an `interface` does not raise this warning.

**Comment by dummdidumm** [comment]
`export enum` gets transpiled to `export var`. The Svelte parser picks this up and shows the - in his context - right warning. This is an edge case we need to silence.

**Comment by udayrajMT** [comment]
I know this is a bit out of context, but couldn't find the docs and this issue seemed most relevant
But I think you guys can help an eslint configuration to convert this warning into error... 

I've tried a configuration like this -

```js
  ...
  plugins: ["react", "svelte3"],
  overrides: [
    {
      files: ["**/*.svelte"],
      processor: "svelte3/svelte3",
      rules: {
        "unused-export-let": ["error"]
      }
    },
   ...
]
```
but it doesn't seem to fail even when running eslint manually.

Any help is appreciated @dummdidumm

**Comment by dummdidumm** [comment]
The warning does not come from ESLint, it comes from the Svelte compiler. You'll want to use [this setting](https://github.com/sveltejs/language-tools/tree/master/packages/svelte-vscode#sveltepluginsveltecompilerwarnings) for VS Code and the [--compiler-warnings setting](https://github.com/sveltejs/language-tools/tree/master/packages/svelte-check#args) for svelte-check.
