### ISSUE TITLE
Event handlers use incorrect assumption about `event.target`

### ISSUE THREAD

**Issue by scottgonzalez** [sveltejs/language-tools#579]
**Describe the bug**
The following event listener will assume that `event.target` will be of type `HTMLDivElement`:

```svelte
<div on:input={handleInputChange}>
    ...
</div>
```

However, the `target` of any bubbling event cannot be assumed. Trying to cast `target` to the appropriate type still causes a TypeScript error because `HTMLDivElement` and `HTMLInputElement` are not compatible.

```svelte
    function handleInputChange(event: InputEvent): void {
        const target = event.target as HTMLInputElement;
        ...
    }
```

**Expected behavior**
`event.target` can be used properly in TypeScript.

**Information about your Svelte project:**
- Svelte version: 3.26.0

**Severity**
Annoying as it prevents automated TypeScript checking from being part of our workflow.

**Comment by dummdidumm** [comment]
As a workaround you can cast to unknown or any first.

**Comment by scottgonzalez** [comment]
Thanks. That at least gives us a path to get type checking to work.

It also looks like the generic `Event` type is always used instead of the specific event type, i.e., `InputEvent`.

**Comment by dummdidumm** [comment]
`target` is fixed. About the event types: the more specific ones according to the MDN/TS typings are used; they don't use `InputEvent`.
