### ISSUE TITLE
Allow for Emmet customization

### ISSUE THREAD

**Issue by ysshah** [sveltejs/language-tools#591]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
It would be great if we could customize Emmet snippets, preferences, and syntax profiles: https://docs.emmet.io/customization. Specifically, I would like the ability to choose single quotes instead of double quotes for the generated HTML, but it seems I cannot do that since there is no ability to change Emmet's [syntax profiles](https://docs.emmet.io/customization/syntax-profiles).

**Describe alternatives you've considered**
None.

**Additional context**
What work would this require to implement? I might be able to contribute.

**Comment by dummdidumm** [comment]
We use `emmet-vscode-helper` to get the completions, [here](https://github.com/sveltejs/language-tools/blob/master/packages/language-server/src/plugins/html/HTMLPlugin.ts#L70) and [here](https://github.com/sveltejs/language-tools/blob/master/packages/language-server/src/plugins/css/CSSPlugin.ts#L108). We need to pass the emmet VS Code config to it which can be done in [extension.ts](https://github.com/sveltejs/language-tools/blob/master/packages/svelte-vscode/src/extension.ts#L94) and then passed on to the plugins.

**Comment by dummdidumm** [comment]
VS Code's emmet config is now used and should allow the customizations you wish for. Exception are commands like "expand abbreviation". More info on VS Code and emmet [here](https://code.visualstudio.com/docs/editor/emmet).

**Comment by ysshah** [comment]
Woohoo! Thanks!
