### ISSUE TITLE
Does not respect default language in svelte.config.js

### ISSUE THREAD

**Issue by TheComputerM** [sveltejs/language-tools#593]
**Describe the bug**
My `svelte.config.js` file looks like this:
```js
import sveltePreprocess from "svelte-preprocess";

module.exports = {
  preprocess: sveltePreprocess({
    defaults: {
      script: "typescript",
      style: "scss",
    },
    postcss: {
      plugins: [require("autoprefixer")()],
    },
  }),
};
```

**Expected behavior**
It is showing me that you have to add `lang='ts'` to svelte file that looks something like this:
```html
<script>
  export let segment: string;
</script>

{segment}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/24741538/95045690-2d84bb80-0700-11eb-9045-2733973b854c.png)

**System (please complete the following information):**
 - OS: Windows
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode

**Comment by jasonlyu123** [comment]
Did you restart the language server after altering the config? Because loading config is expensive in terms of performance so we make it only load once.

**Comment by TheComputerM** [comment]
yeah, even restarted vs code.

**Comment by TheComputerM** [comment]
Read the disclaimer part: https://github.com/sveltejs/svelte-preprocess/blob/master/docs/getting-started.md#31-setting-default-languages

Is this feature planned to be added to the language server?

**Comment by jasonlyu123** [comment]
This is supported. Don't know what's causing the problem on your end, Can you provide a minimal reproducible?

**Comment by TheComputerM** [comment]
@jasonlyu123 Can I share a gitpod repro now?

**Comment by ignatiusmb** [comment]
`svelte.config.js` doesn't support ES6 `import` syntax, AFAIK. Try changing the import to
```js
const sveltePreprocess = require('svelte-preprocess');
```
I tried to reproduce it using your config and it immediately complains with
![image](https://user-images.githubusercontent.com/8156777/95111411-a704c400-0769-11eb-8c74-b835f4fe06cc.png)

**Comment by jasonlyu123** [comment]
Oh yeah. That's the problem. Doesn't notice the mix of common js and es module

**Comment by TheComputerM** [comment]
Yeah, I forgot
Will need to fix [this](https://github.com/sveltejs/svelte-preprocess/blob/master/docs/usage.md#with-svelte-vs-code)

**Comment by samal-rasmussen** [comment]
The part I was missing was that the svelte language-tools doesn't read the defaultsfrom the rollup.config.js. I had to add a svelte.config.js file to the root of my project that includes the same config options for sveltePreprocess and in the rollup config.

This is documented in the documentation for svelte-preprocess:
https://github.com/sveltejs/svelte-preprocess/blob/master/docs/usage.md#with-svelte-vs-code

**Comment by jasonlyu123** [comment]
Sorry, the config passed into rollup-plugin-svelte is not visible from the outside of the function.

**Comment by nathanblair** [comment]
> 
> 
> `svelte.config.js` doesn't support ES6 `import` syntax, AFAIK. Try changing the import to
> 
> ```js
> const sveltePreprocess = require('svelte-preprocess');
> ```
> 
> I tried to reproduce it using your config and it immediately complains with
> ![image](https://user-images.githubusercontent.com/8156777/95111411-a704c400-0769-11eb-8c74-b835f4fe06cc.png)

> 
> 
> The part I was missing was that the svelte language-tools doesn't read the defaults from the rollup.config.js. I had to add a svelte.config.js file to the root of my project that includes the same config options for sveltePreprocess as in the rollup config.
> 
> This is documented in the documentation for svelte-preprocess:
> https://github.com/sveltejs/svelte-preprocess/blob/master/docs/usage.md#with-svelte-vs-code
> 
> Would reading the defaults from the rollup.config.js file be out of the question for the svelte language-tools? Because the onboarding experience for me on this one was a bit painful.

Importing `svelte.config.js` as an ES6 module should be something that is possible. Not being able to use svelte.config.js so we can have LSP support due to being limited to by CJS is a real pain point in adopting svelte, particularly when the rest of the ecosystem is moving forward with adopting ES6 so everything can stop being so fragmented.

Node recognizes `type: "module"` from package.json so CJS and module loading at that point become irreconcilable.

What would the blocker be? Is this a LSP issue? Or is it a `rollup` plugin issue (with the `svelte` rollup plugin or the `svelte-preprocess` rollup plugin)?

**Comment by dummdidumm** [comment]
So #509 for more info on this
