### ISSUE TITLE
VSCode doesn't highlight Svelte attribute values without double quotes

### ISSUE THREAD

**Issue by gengns** [sveltejs/language-tools#595]
I'm using Svelte in Visual Studio Code editor (1.49.3v)

After installing [Svelte for VS Code](https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode) extension I have noticed that Svelte html attribute's values without double quotes are not highlighted.

This is a screenshot of what I have in VSC. As you can see `number` is not highlighted.
![image](https://user-images.githubusercontent.com/13253926/95106688-19a97b80-0739-11eb-9f29-2ce0c7afcced.png)

This is the same code in an html block of code perfectly highlighted.

```html
<input type=number value={b} min=0 max=10>
```

Also you can check the highlighting[ in this example ](https://svelte.dev/tutorial/numeric-inputs)from the official basic tutorials.

Do we need another extension or extra configuration to highlight this properly in Visual Studio Code?

**Comment by dummdidumm** [comment]
What kind of highlight do you expect? The same color as if you would surround the value with double quotes (`type="number"`)?

**Comment by gengns** [comment]
Thank for your answerr and time @dummdidumm : ) I expect just the same we have in the tutorials (be able to differentiate attribute from value). The same color as if we would surround the value with double quotes. 

I can try to make pull request for that changing the file you linked.
