### ISSUE TITLE
Svelte for VS Code Nightly build CI

### ISSUE THREAD

**Issue by jasonlyu123** [sveltejs/language-tools#597]
**Describe the bug**
Svelte for VS Code Nightly doesn't works. Seems like something to do with CI. The extension folder doesn't install dependency

**To Reproduce**
Install Svelte for VS Code Nightly

**Expected behavior**
works

**Screenshots**
![圖片](https://user-images.githubusercontent.com/36730922/95405015-33211200-0949-11eb-86b0-26ebc50900d3.png)
(no node_modules)

**System (please complete the following information):**
 - OS: Windows
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode Nightly

**Comment by dummdidumm** [comment]
Seems like this has solved itself with a new deploy.
