### ISSUE TITLE
Numbers in components accessed from namespace is not highlighted

### ISSUE THREAD

**Issue by ignatiusmb** [sveltejs/language-tools#599]
**Describe the bug**
The number "2" in `<Feather.Share2 />` is not highlighted, but it works when used directly
![image](https://user-images.githubusercontent.com/8156777/95686846-aae18c00-0c2a-11eb-8aae-ca8087026202.png)

I'm still not sure if this is Svelte specific or just VS Code, feel free to close this if it isn't

**To Reproduce**

- Use a component with a number in its name directly from their namespace

**Expected behavior**
Numbers is highlighted correctly when accessed directly from a namespace

**System (please complete the following information):**
 - OS: Windows 10
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode v102.1.1

**Comment by dummdidumm** [comment]
Most likely something wrong in the tml file https://github.com/sveltejs/language-tools/blob/master/packages/svelte-vscode/syntaxes/svelte.tmLanguage.json
