### ISSUE TITLE
Feature list or Roadmap

### ISSUE THREAD

**Issue by Kingwl** [sveltejs/language-tools#6]
Maybe we need that to work with the community.

**Comment by orta** [comment]
I don't have either yet, I'll have a think 👍  but I'm very open to ideas! 

Right now I think it needs to be tested against some codebases, I updated all the deps and tests. Thinks are working, but some things are probably broken.

**Comment by joelmukuthu** [comment]
@orta how would one go about testing this against some codebase? I'm setting up a TS/Svelte monorepo and would be happy to try out a few different use-cases with this, but I don't know how to set up language servers. Do you have some links/info that can get me started in the right direction?

**Comment by orta** [comment]
Good thinking @joelmukuthu  - I've just shipped a PR which makes the docs a _lot_ more explicit about how to get up and running #10

**Comment by dummdidumm** [comment]
It would be great to have intellisense features:
- Autocomplete (like in .js/.ts-files)
- Go to definition (for components, variables, methods, also across svelte files)
- Hover information (about components, variables, methods, also across svelte files)

@alexprey has done foundations work for this by creating https://github.com/alexprey/sveltedoc-parser, a parser for svelte files which outputs infos about them in a readable json format. @ArdenIvanov has built a language server / VSCode extension on top of it https://github.com/ArdenIvanov/svelte-intellisense . Maybe we could integrate their works into this project.

**Comment by orta** [comment]
Yep, I'm open to migrating all of these sorts of features in - yep!

**Comment by dummdidumm** [comment]
A feature list with what's done and what's not is now available at #83
