### ISSUE TITLE
Imports are always relative to top level package

### ISSUE THREAD

**Issue by ehrencrona** [sveltejs/language-tools#601]
I have a file `src/routes/foo/lib.js` with the content `export default 1` and a file `src/routes/foo/bar.svelte` with the content

```
<script lang="ts">
  import foo from './lib';
</script>
```

This import will compile but the language server will complain that the module does not exist. If I instead reference the library as `import foo from './foo/lib'` the language server will be happy but the compiler will complain.

I'm in a `svelte-template` project that I've converted to TypeScript, Svelte for VSCode 102.1.1, sapper 0.28.10

**Comment by dummdidumm** [comment]
I cannot reproduce this. Moreover, `export default const foo = 1` errors at me, `export default 1` works though.

**Comment by ehrencrona** [comment]
Sorry, I'm confused. I had in fact imported from the wrong path but the compiler doesn't complain, which I interpreted to mean "there are no issues". But I guess the compiler just doesn't care about types. Sorry.
