### ISSUE TITLE
Random svelte-check error

### ISSUE THREAD

**Issue by AlexGalays** [sveltejs/language-tools#614]
I'm now using `svelte-check` to check for all TS errors during development. Trouble is, I've seen it report completely fake errors. Does it really read from `tsconfig` and use the same typings for svelte as the other tools?

Mac OS latest
`VS Code`: `1.50.1`
`svelte-check`: `1.0.59`
`Svelte for VS Code`: `v102.2.0`

This file compiles fine and typecheck fine directly in VSCode and when building with `@rollup/plugin-typescript` but gives some random error when running `svelte-check` (watch or regular): 

![image](https://user-images.githubusercontent.com/1375586/96255842-e0ce9980-0fb7-11eb-8ead-fa34210e31f1.png)

The errors are:

![image](https://user-images.githubusercontent.com/1375586/96256008-2ab77f80-0fb8-11eb-976e-18ef4c29d31c.png)

which makes zero sense if svelte-check was reading svelte's updated typings.

Cheers

**Comment by dummdidumm** [comment]
What's the version of `svelte-language-server` and `svelte2tsx` inside your `node_modules`? Is it the latest?

**Comment by AlexGalays** [comment]
I do not depend on these explicitely so I assumed they would be the latest;
They come as: 

![image](https://user-images.githubusercontent.com/1375586/96257166-30ae6000-0fba-11eb-99c2-1527482d6dea.png)

and

![image](https://user-images.githubusercontent.com/1375586/96257210-40c63f80-0fba-11eb-8a9b-f29aaccbdd10.png)

**Comment by dummdidumm** [comment]
The versions are out of date so I guess this is the reason. The problem is that we signal in the package json "just use the latest" through `*` but this does not always update the dependent packages. So for now you'd have to upgrade them yourself. I would like to package `svelte-check` and also treeshake it to get rid of all the unnecessary dependencies, then this problem will be solved.

**Comment by AlexGalays** [comment]
Yeah.. a heavy handed `rm -rf node_modules && rm yarn.lock  && yarn cache clean && yarn`  fixed it.

Thanks for the explanation, I'm glad it's not a problem with `svelte-check`. I think yarn decided to keep the dependencies as is even though we upgraded svelte-check :(
