### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by benmccann** [sveltejs/language-tools#63]
Hi, this looks like a really interesting project!

Does this project handle TypeScript in `.svelte` files currently or just JavaScript at the moment?

If it does handle TypeScript, can it run the TypeScript compiler and output JavaScript on to the file system or is it only meant to be used in Visual Studio?

If it's not yet supported, is handling TypeScript a goal someday and what would be required to compile TypeScript and output it to the file system? I potentially could help in this direction depending what's required. Most likely through testing and providing feedback, but maybe also writing tests or helping with some implementation details depending how much time I end up having

Thanks!

**Comment by jasonlyu123** [comment]
From what I understand
1. It doesn't fully support typescript yet, users would still need to setup preprocessor for the moment. 
2. It's not a build tool but a dev tool. The language server is meant to be used by clients that support language-server-protocol like vs code. 
The building still depends on the community preprocessor and the svelte compiler. But I think it would nice to have an official typescript build tool that can emit declaration files. 

The building step is like this:
1. Svelte detect what should be preprocessed and preprocess with provided preprocessor
2. Svelte compile with transpiled js. 

So as the current build steps. separate build and type check seems more reasonable. Based on this approach what I imagine an integrate ts build tool would be:
1. have a preprocessor to transpile ts in the script to js
2. analysis and type check script and template
3. emit declaration files

**Comment by dummdidumm** [comment]
@jasonlyu123 is right.
The Svelte Plugin will always just be a IDE Dev Tool to provide Intellisense for Svelte files. Right now Typescript is supported, but the support is still in early stages, so expect some inconveniences. But we are actively working on making the experience better!
Transpiling Typescript to Javascript and outputting this to the disk is done through preprocessors like https://github.com/kaisermann/svelte-preprocess .

Does this answer your question?

**Comment by benmccann** [comment]
Thank you!

Will this tool need to do the same preprocessing as a build tool would need to? I'm wondering if that part would be a shared library that would be collaborated on between this project and a build tool effort

**Comment by dummdidumm** [comment]
Yes, it needs to do the same preprocessing, but the preprocessors used are those defined by the user, which should be the same ones he also uses to build his project. The preprocessors are not part of this repo.

**Comment by benmccann** [comment]
Oh, that's super interesting and not what I expected as someone with little experience with language servers. Do you use source map output from the pre-processor then to figure out how to mark up issues in the IDE?

It's interesting to me that this project is under the sveltejs organization, but there isn't a preprocessor under the sveltejs organization. Do you have any idea if one might be chosen as the canonical implementation for the community to contribute to? There was an issue about TypeScript support in the main repo that was closed saying that this repo will be used, but it seems like there's still more that's necessary. Thanks for the pointer to that preprocessor, btw! It's different than the one I'd found and looks better supported. That's why I think there'd be value to doing a bit more to point to recommended solutions since I had a hard time finding that on my own

**Comment by benmccann** [comment]
Oh, I just noticed that preprocessor only appears to do the code part and not the template. Is there also a way to have the build tool typecheck the templates? I found https://github.com/halfnelson/svelte2tsx but wasn't sure if that was just meant to be used by language servers based off its readme

**Comment by dummdidumm** [comment]
There are only preprocessors for `script` / `style`. Template has no preprocessor because that's just the htmlx syntax Svelte uses. Adding intellisense to that like "x not assignable to y" or auto completion is not implemented yet, but we are working on it.

**Comment by orta** [comment]
re: preprocessors - for TS the goal is to get just that parsing upstream https://github.com/sveltejs/svelte/issues/4797

That is what gives out of the box support for TS, and should simplify getting the extension set up

**Comment by benmccann** [comment]
Thanks for all the clarifications! I've getting my head wrapped around the architecture much better now
