### ISSUE TITLE
Plain .ts files not getting compiled as TypeScript

### ISSUE THREAD

**Issue by Sidewinder1138** [sveltejs/language-tools#631]
I have recently created a fresh sveltejs project using `npx degit sveltejs/template svelte-typescript-app`, and then I ran the script to change it to TypeScript: `node scripts/setupTypeScript.js`.

Now, everything is working fine as far as putting <script lang="ts"> blicks in my .svelte files.

However, when I try and actually use TypeScript syntax in any plain .ts file, such as main.ts, like this:
`let x: string;`

I get this error: 
`[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
src\main.ts (3:5)
1: import App from './components/App.svelte';
2:
3: let x: string;`

The error is pointing at the ':', the type annotation...

So it looks like Svelte/rollup/whoever thinks this is just JavaScript, it isn't getting ran through TSC?

I don't even know where to begin to try and fix this. Any help greatly appreciated!

**Comment by Sidewinder1138** [comment]
After upgrading some packages and other development, this problem seems to have mysteriously gone away... 🤷

**Comment by jasonlyu123** [comment]
Maybe you could ask about it in the [discord server](https://svelte.dev/chat) see if anyone has a similar problem

**Comment by Sidewinder1138** [comment]
@jasonlyu123 Thanks yes, asked just now, no answers yet.

**Comment by Sidewinder1138** [comment]
I have realized that running 'npm run dev' inside of VSCode's terminal is working, but running in windows terminal is not, so it appears I have something funky going on in my system environment perhaps...
