### ISSUE TITLE
Missing `dist` folder in svelte-check v1.1.0

### ISSUE THREAD

**Issue by joshnuss** [sveltejs/language-tools#634]
**Describe the bug**
The command `svelte-check` throws error when invoked. 

**To Reproduce**

```
# install svelte-check
> yarn add svelte-check@1.1.0

# run svelte-check
> npx svelte-check
Cannot find module '../dist/src/index.js'
Require stack:
- /home/josh/Playground/svelte-check-test/node_modules/svelte-check/bin/svelte-check
```

**Expected behavior**
It should run without error

**System (please complete the following information):**
 - OS: N/A
 - IDE: N/A
 - Plugin/Package: `svelte-check`

**Comment by joshnuss** [comment]
The `dist` folder is not being included when publishing to npm registry

**Comment by dummdidumm** [comment]
Fixed, thanks.
