### ISSUE TITLE
VSCode rename extension setting

### ISSUE THREAD

**Issue by quoid** [sveltejs/language-tools#640]
I am trying to prevent, at least temporarily, the vscode extension from changing my imports when I move a file. From reading the [documentation](https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode), I assumed the option to do this would be `svelte.plugin.svelte.rename.enable`.

However, that option doesn't seem to have any effect on the behavior. It's also not present in the extension settings ui on version `v102.3.0`.

Is there a way to disable the plugin from changing code when files are moved and is the above mentioned setting functional at the moment?

**Comment by dummdidumm** [comment]
Strange, it should adhere to this setting ([see this code line](https://github.com/sveltejs/language-tools/blob/master/packages/language-server/src/plugins/typescript/TypeScriptPlugin.ts#L318)). Which files are affected by that? If it's files other than Svelte files, it's likely the TS language server integrated into VS Code which does this.

**Comment by dummdidumm** [comment]
This indeed is a bug, thanks for bringing it up.
