### ISSUE TITLE
add an option to suppress hints

### ISSUE THREAD

**Issue by jonathonadams** [sveltejs/language-tools#646]
**Is your feature request related to a problem? Please describe.**
When running `svelte-check`, hints are always reported. Not all the hints are helpful or desired.

**Describe the solution you'd like**
An options to set that will not output Hints when `svelte-check` runs.

**Describe alternatives you've considered**
I have tried using `/* svelte-ignore */` but appears to have not affect.

**Comment by dummdidumm** [comment]
This already exists, use '--threshold warning`. See the readme for more info.

**Comment by jonathonadams** [comment]
Apologies. I ‘thought’ I had read the docs thoroughly and couldn’t find said feature. 

Apparently not thorough enough.
