### ISSUE TITLE
Emmet shortcut doesn't work when <script> tag is not present

### ISSUE THREAD

**Issue by vinliao** [sveltejs/language-tools#651]
**Describe the bug**
Normally, I create a tag with `tagname + enter`. That works fine in `.svelte` file, but not when the `<script>` tag is removed.

**To Reproduce**
Create svelte file without a `<script>` tag and try typing `p + enter`. It doesn't create `<p><p/>`. If you put back the `<script>` tag, everything works fine.

**Expected behavior**
Emmet shortcut works even though without `<script>` tag.

**System (please complete the following information):**
 - OS: Linux
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode.

**Additional context**
To be quite honest, this is a pretty small and miniscule problem, but the behavior is unexpected nonetheless.

**Comment by jasonlyu123** [comment]
This is weird. it seems like the very first character(a-Z) you typed doesn't trigger completion for some reason. Maybe it's related to a lack of completion inside the multiline comment. As a workaround, if anyone encounter this you can use `Ctrl + Space` or `Ctrl + I` to manually trigger it.

**Comment by MichealPearce** [comment]
I am using v102.4.0 and not experiencing the issue, what version are you using?
![Peek 2020-11-05 14-25](https://user-images.githubusercontent.com/8726457/98287237-13deca00-1f73-11eb-9754-95987167a3c1.gif)

**Comment by jasonlyu123** [comment]
I guess it's the first few alphabet. Once you use backspace, delete or some special characters that can trigger the auto completion. It would be normal again. I think it's not related to script tag.

**Comment by vinliao** [comment]
An update: it seems like the bug is gone now. Everything is back to normal. Not sure what caused it yesterday, could be some problem on my end.
