### ISSUE TITLE
Can I use Component.SubComponent as tagName like this?

### ISSUE THREAD

**Issue by vaseala** [sveltejs/language-tools#652]
entry.svelte
```
<script lang="ts">
  import List from "./index";
</script>

<List>
  <List.Item>first item</List.Item>
  <List.Split>--</List.Split>
  <List.Item>last item</List.Item>
</List>
```
when I use like this, it can compiled, but in vscode editor, I get an error tip: Property 'Item' does not exist on type 'typeof List__SvelteComponent_'.ts

![image](https://user-images.githubusercontent.com/12792057/97953714-4e622e80-1ddc-11eb-9bf1-3db84e479870.png)

I want to know if the usage is correct?

other main file contents:

index.ts
```
import List from './list.svelte'
import Item from './item.svelte'
import Split from './split.svelte'

List['Item'] = Item;
List['Split'] = Split;

export default List
```

list.svelte
```
<div class="list">
  <slot />
</div>
```

item.svelte
```
<div class="item">
  <slot />
</div>
```

split.svelte
```
<slot>|</slot>
```

**Comment by dummdidumm** [comment]
This is a question unrelated to Svelte, what you want to do is to redefine the type. When you add `Item` to `List` like `List['Item']`, TypeScript cannot know that `List` is now enhanced, you need to manually type that. Your example will become roughly this:

```ts
import _List from './list.svelte'
import Item from './item.svelte'
import Split from './split.svelte'

_List['Item'] = Item;
_List['Split'] = Split;

const List: typeof _List & { Item: typeof Item, Split: typeof Split } = <any>_List;
export default List
```

In the future I suggest to ask such questions on StackOverflow.
