### ISSUE TITLE
Comment re-wrap is broken in `.svelte` files

### ISSUE THREAD

**Issue by websocket98765** [sveltejs/language-tools#663]
Let me know if this should be reported to VS Code instead.

**Describe the bug**

VS Code's comment re-wrapping does not work as expected in Svelte's javascript or HTML areas.

### Steps to Reproduce

JS:
1. In a `.svelte file`, add a comment within the script block.
2. `Cmd + shift + P` and "rewrap comment / text".  

HTML:
1. In a `.svelte file`, add a comment within the file (not in a script or style block).
2. `Cmd + shift + P` and "rewrap comment / text".  

### **JavaScript Comments**

**unwrapped (initial text)**

```js
// Anim aliqua pariatur laboris laboris do fugiat aliquip aliqua ut proident. Nostrud officia ex aliquip sunt ea ipsum velit culpa enim irure voluptate minim qui id. Eiusmod eiusmod minim occaecat eiusmod sit ut quis laborum qui exercitation officia voluptate.
```

**After current re-wrapping behavior**

No change. It doesn't wrap.

```js
// Anim aliqua pariatur laboris laboris do fugiat aliquip aliqua ut proident. Nostrud officia ex aliquip sunt ea ipsum velit culpa enim irure voluptate minim qui id. Eiusmod eiusmod minim occaecat eiusmod sit ut quis laborum qui exercitation officia voluptate.
```

**Expected**

Created by pasting the comment in a `.js` file in the same project and wrapping it there.

```js
// Anim aliqua pariatur laboris laboris do fugiat aliquip aliqua ut proident.
// Nostrud officia ex aliquip sunt ea ipsum velit culpa enim irure voluptate
// minim qui id. Eiusmod eiusmod minim occaecat eiusmod sit ut quis laborum qui
// exercitation officia voluptate.
```

### **HTML Comments**

**unwrapped (initial text)**

```html
<!--
  Magna minim aute incididunt reprehenderit. Magna Lorem eu consequat ex elit Lorem do culpa mollit deserunt amet consectetur ea exercitation. Aliquip est voluptate deserunt nostrud eu minim Lorem sit nulla aliquip incididunt deserunt commodo.
-->
```

**After current re-wrapping behavior (lines are longer than expected)**

Lines are longer than expected, expected being the length that they wrap in a `.html` file in the project.

```html
<!--
  Magna minim aute incididunt reprehenderit. Magna Lorem eu consequat ex elit Lorem do culpa mollit
  deserunt amet consectetur ea exercitation. Aliquip est voluptate deserunt nostrud eu minim Lorem
  sit nulla aliquip incididunt deserunt commodo.
-->
```

**Expected (proper length)**

Created by pasting the unwrapped comment into a `.html` file in the project and wrapping it there.

```html
<!--
  Magna minim aute incididunt reprehenderit. Magna Lorem eu consequat ex elit
  Lorem do culpa mollit deserunt amet consectetur ea exercitation. Aliquip est
  voluptate deserunt nostrud eu minim Lorem sit nulla aliquip incididunt
  deserunt commodo.
-->
```

**System:**

 - OS: Mac
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode  102.5.1

**Comment by jasonlyu123** [comment]
Seems like this is a feature of https://github.com/stkb/Rewrap or another extension. I don't have this command.

**Comment by websocket98765** [comment]
Ooop, you are right, I do have `stkb.rewrap`. Will move it. Thanks
