### ISSUE TITLE
typings: oncancel? should be EventHandler<Event,T> instead of EventHandler<T>

### ISSUE THREAD

**Issue by pschyska** [sveltejs/language-tools#672]
**Describe the bug**
I think the type of [oncancel](https://github.com/sveltejs/language-tools/blob/master/packages/svelte2tsx/svelte-jsx.d.ts#L213) is incorrect. For example on a `HTMLDialogElement` this resolves to `EventHandler<HTMLElement,HTMLElement>`. I think `oncancel` (and probably every other handler referencing `EventHandler<T>`) should be typed:
`oncancel?: EventHandler<Event,T>;`

**To Reproduce**
````
<script lang="ts">
function cancel(ev: Event)  {
    ev.stopImmediatePropagation();
    ev.preventDefault()
}
</script>

<main>
    <dialog on:cancel="{cancel}">
    </dialog>
</main>
````
This type errors like this:
````
Type '(ev: Event) => void' is not assignable to type 'EventHandler<HTMLElement, HTMLElement>'.
  Types of parameters 'ev' and 'event' are incompatible.
    Type 'HTMLElement & { currentTarget: EventTarget & HTMLElement; }' is missing the following properties from type 'Event': bubbles, cancelBubble, cancelable, composed, and 17 more.ts(2322)
````
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/oncancel#Value), this should be a legal handler.

**Expected behavior**
In this concrete example, I think the type should be `EventHandler<Event, HTMLDialogElement>`. Or `EventHandler<Event, HTMLElement>` if there is a reason to not type it as HTMLDialogElement that escapes me right now. (iow: why is [dialog]( https://github.com/sveltejs/language-tools/blob/master/packages/svelte2tsx/svelte-jsx.d.ts#L795) not a `HTMLProps<HTMLDialogElement>`)

**Comment by pschyska** [comment]
@jasonlyu123 What do you think about [dialog](https://github.com/sveltejs/language-tools/blob/master/packages/svelte2tsx/svelte-jsx.d.ts#L795) being typed as `HTMLProps<HTMLDialogElement>`, while we are at it :-)

**Comment by jasonlyu123** [comment]
It looks like there's plenty of them is typed as `HTMLProps<HTMLElement>`. I think we can change it to 
```typescript
type HTMLElementPropMap = {
    [k in keyof HTMLElementTagNameMap]: HTMLProps<HTMLElementTagNameMap[k]>
}
interface IntrinsicElements extends HTMLElementPropMap { }
```
and remove the overlaps.

**Comment by dummdidumm** [comment]
Sounds good, we just need to look very closely to not throw out tags that are present now by accident.

**Comment by dummdidumm** [comment]
Closing as the original issue has been resolved. For the other things, feel free to open a separate issue.
