### ISSUE TITLE
Request: Add ability to selectively turn off or specify priority of emmet auto suggestions in Svelte files

### ISSUE THREAD

**Issue by saikatdas0790** [sveltejs/language-tools#677]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm trying to write CSS in the style block of Svelte components and the CSS autosuggest comes up with two entries for the style I'm trying to write. The first one is from Emmet and the 2nd one is from autocomplete.

**Describe the solution you'd like**
I would like either or both if possible:
- A VSCode setting that disables emmet selectively in sections, for example, turn off emmet for CSS but keep it enabled for HTML
- A VSCode setting to specify the order of the autosuggest being suggested where I can prioritize autocomplete over emmet

**Describe alternatives you've considered**
I've tried to mess around with VSCode settings but these settings are specific to the Svelte VSCode extension

**Additional context**
Here's an example

![image](https://user-images.githubusercontent.com/7412443/99425285-a6df1300-2928-11eb-8366-df13de4fd6f8.png)

I want to use the 2nd "padding" autosuggest as compared to the first which comes from emmet

To clarify why this is a problem, when I write a style like "position" with "pos", I want to just have autosuggest autocomplete the "position" part but emmet also adds the "relative" value when completed. Check here

![image](https://user-images.githubusercontent.com/7412443/99425706-3684c180-2929-11eb-93b8-c844888e0af3.png)

**Comment by dummdidumm** [comment]
You can now turn off css emmet completions through [this setting](https://github.com/sveltejs/language-tools/tree/master/packages/svelte-vscode#svelteplugincsscompletionsemmet).
