### ISSUE TITLE
CLI for validating project

### ISSUE THREAD

**Issue by orta** [sveltejs/language-tools#68]
**Is your feature request related to a problem? Please describe.**

Add a new package to the mono-repo which could be something like `svelte-check`. Perhaps being extra verbose is good here, because I'm not certain that in the long term this module would be the place where it lives. (e.g. I think if there's a `svelte` cli, then this would be a subcommand in there.

**Describe the solution you'd like**

The package would use the LSP shipped in this repo to ping every Svelte file in the current directory, and to request diagnostics (a.k.a errors) for that file. This is effectively the equivalent of running TypeScript and/or other tools we support in the LSP over each file.

**Describe alternatives you've considered**
In theory this could be built without the LSP, but that abstraction is solid and already has [proven itself in vetur](https://github.com/vuejs/vetur/blob/master/vti/src/cli.ts)

**Additional context**
Came out of https://github.com/sveltejs/svelte/issues/4518#issuecomment-625345746

**Comment by benmccann** [comment]
Thanks @orta this is super helpful. So this would basically have type checking decoupled from building if I understand correctly. That gives you multiple ways to set things up, but one setup might look like:

* Setup a pre-processor (unless the functionality is merged into core https://github.com/sveltejs/svelte/issues/4797)
* Tell TypeScript to emit JS, but don't do type checking for faster building. That makes hot module reloading work faster in the browser and then you can rely on the IDE for errors
* If you're using a CI server, then you can run `svelte check` to fail the build if there are errors. You could also set this up to happen locally either while building or as a git precommit hook if you wanted

**Comment by orta** [comment]
I don't know enough about how people use Svelte to talk about that middle step, in my head all of that was happening at IDE level 

But yeah, that's basically the entire gist 👍

**Comment by halfnelson** [comment]
For some code to cut and paste or to use in the short term I had made one using svelte2tsx. https://github.com/halfnelson/svelte-type-checker maybe it can be ported to use language server

**Comment by benmccann** [comment]
It looks to me like the [vetur implementation](https://github.com/vuejs/vetur/blob/master/vti/src/cli.ts) could be copy-pasted and used almost directly for svelte. We'd just need to tell it to look at `.svelte` files instead of `.vue` files and set the `languageId` and `version` appropriately.

That part looks like it may require some changes in the language server first because [it looks like the server is using `{languageId: '', version: 0}`](https://github.com/sveltejs/language-tools/search?q=languageId&unscoped_q=languageId) and I'm guessing we should probably create a `'svelte'` `languageId` or something.

**Comment by dummdidumm** [comment]
Actually we don't need the `languageId` as far as I know. Inside `server.ts`, the `onDidOpenTextDocument` event just hands over the document to `DocumentManager` and there the `languageId` is of no concern.

**Comment by orta** [comment]
I think it might make sense then for us to maybe create two packages:

- one which could power both vetur's & svelte's CLI
- sveltes CLI

/cc @octref got an opinion?

**Comment by dummdidumm** [comment]
You mean like a "base package" which both then use?

**Comment by orta** [comment]
Yeah, exactly - a generic "run an LSP over a set of files" package

**Comment by benmccann** [comment]
That seems like it'd work. It'd save us a bit over 100 lines of code. I'm not sure if it's complicated enough to go through the work of creating a new package, but if there were a base package it'd certainly be worth using

One more question for you guys - how does the language server get downloaded and started in the CLI case? I'm assuming you shouldn't need VSCode installed to use the CLI. Can VSCode and the CLI share the same instance of the language server though?

**Comment by dummdidumm** [comment]
They cannot I think. They are separate processes, and I don't know if you can somehow detect "is there a VSCode Svelte Plugin process running" - I guess not.

**Comment by orta** [comment]
I've not read the code, but you can probably spin up your own language server using [the npm module](https://github.com/sveltejs/language-tools/tree/master/packages/language-server) and connect to it from the same process I think. You shouldn't need to connect to the one in the vscode extension

**Comment by dummdidumm** [comment]
Regarding the "extract into some common package" thing: I don't think we should do it. While `svelte-check` and `vti` share code that is common, there are some differences sprinkled here and there. Harmonizing them would probably cost more time than keeping it separate.

**Comment by dummdidumm** [comment]
Now live at https://www.npmjs.com/package/svelte-check

**Comment by octref** [comment]
I haven't had time to look at my notifications. Good work and I'm glad my code can be useful to svelte users.
However I'd appreciate it if you add a link to the original implementation either as inline comment or in the credit section.

**Comment by dummdidumm** [comment]
Sure thing!
