### ISSUE TITLE
TypeScript: global variable definitions override ambient declarations

### ISSUE THREAD

**Issue by cengels** [sveltejs/language-tools#683]
Given a project that is properly set up to use TypeScript (including rollup and svelte-preprocess): let's say I have a file `test.js` anywhere in the source tree with the following contents:

```js
const testVar = {};
```

And then I also have a file `test.d.ts` next to it that types `testVar`:

```ts
declare const testVar: { someProperty: string };
```

If I then try to use `testVar` in a .svelte file, the language server is unable to see the ambient declaration at all, which means `testVar` will always be typed as an empty object and I can't access `someProperty` without errors in both VSCode and svelte-check.

The build, however, will succeed with no problems. The resulting bundle is not malformed and runs perfectly fine.

Side note: trying to access `testVar` in the component itself (as opposed to a script tag) always results in the `testVar is not defined` warning and *will* break the build. Suppressing this warning using `svelte-ignore missing-declaration` will make the build succeed. But since that particular issue affects the build, it seems to be a problem with svelte itself, not with this repository.

![image](https://user-images.githubusercontent.com/31248098/99877721-7933eb80-2c00-11eb-8cbe-1c11bb275de6.png)

Note that this is not a problem with my TypeScript configuration, as attempting to access `testVar` in a standard `.ts` (non-svelte) file works without problems and is properly typed as `{ someProperty: string }`, so this has to be some kind of a problem with the language server.

Also note that, if there is no global variable definition in a `.js` file anywhere, an ambient declaration will work fine. So in the above example, if I only had a `test.d.ts` file and no `test.js` file, then the language server would properly type `testVar` as `{ someProperty: string }` in `.svelte` files.

**Expected behavior**
No errors should occur. The language server should use the correct type from the `d.ts` ambient declaration file instead of inferring a type from the `.js` file.

**System:**
 - OS: Windows
 - IDE: VSCode
 - Plugin/Package: "Svelte for VSCode:102.5.1", `svelte-language-server`, and `svelte-check:1.1.15` all report this as an error

I hope you have no problems reproducing this issue, but let me know if you do and I can post the contents of my config files as well.

**Comment by dummdidumm** [comment]
For me the Svelte and the TS file behave the same way (in a strange way, I must say this):
If I first declare the `.js` file and then the `d.ts` file, then use that inside a TS or Svelte file, the type will be that of the `.js` file.
If I reload afterwards however, or if I first declare the `d.ts` file, then the type both in the Svelte and TS file will be that of the `d.ts` file.

Moreover, I get a TypeScript error saying `Cannot redeclare block-scoped variable 'testVar'.` in both the `.js` and `d.ts` file because, well, they both declare the same variable.

About that side note: There is nothing you can do about this other than to silence the warning as you said, because the Svelte compiler cannot know that there's an ambient declaration.

**Comment by cengels** [comment]
I just tested it again in a standalone project and saw similar behavior as you: if I declared the `.js` file first, it wouldn't see the `d.ts` file until a reload window. `svelte-check` remained unaffected.

To be honest, I didn't see any of the other behavior you mentioned though. Specifically, using the global variable in a `.ts` file never produced an error for me and I also never got a `Cannot redeclare block-scoped variable` error which, according to everything I know about TypeScript, also shouldn't happen at all since one is just a type declaration and the other is an actual variable declaration. If you used `declare` in the `.d.ts` file, that error definitely shouldn't happen.

Regardless, I did some more digging and found out how to consistently reproduce the error regardless of the order of file creation or anything like that.

Basically, the `.js` and `.d.ts` files need to be named or organized in such a way that, when the file list is sorted alphabetically, **the `.js` file comes first`. Usually if both files are named the same (like `test.js` and `test.d.ts`) this won't happen: `d` comes before `j` in the alphabet, so the ambient declaration file comes first.

You can reproduce the error by either naming both files differently (for instance `test.js` and `zest.d.ts`) or by putting the declaration file in a different folder which is named in such a way as to come after the `test.js` file when sorted alphabetically, for instance by placing the `.js` file in a folder named `folderA` and the `.d.ts` file in a folder named `folderB` (note that the error won't happen if you put the `.js` file in `folderB` and `.d.ts` in `folderA`).

Again, let me know if you face any issues reproducing this problem with this new information. Like I said, I have a standalone project now in which I can consistently reproduce the error. I could upload that if necessary.

**Comment by dummdidumm** [comment]
Yeah I also wondered about the `cannot redeclare` error. It might be some `tsconfig.json` settings that produce this for me.

I can now reproduce this, too, but again, the behavior is consistent across Svelte and TS files. So for me this is "works as designed"/"works the same as TS". So to fix this, TS would need to change its behavior. We are constructing a virtual TS file from the Svelte file after all to do all this intellisense.

If there is nothing else that feels wrong from your side I'm going to close.

**Comment by cengels** [comment]
I'd request you leave this open for now until someone else can double-check this. For me TypeScript files still behave correctly in all cases, regardless of file ordering. Does the language service use a specific TypeScript version internally? I tested it with TypeScript 4.0.3 and 4.1.2, same behavior in both cases.

If anyone else would like to test this, I'm attaching a zip of the project folder [here](https://github.com/sveltejs/language-tools/files/5577923/svelte_test_683.zip) in which I can consistently reproduce the error (only in `.svelte` files). Just run `npm install` and check the type of `testVar` in first `main.ts` and then in `Component.svelte`. For me the type in `main.ts` is correctly inferred as `{ someProperty: string }`, but `Component.svelte` just shows `{}`.

**Comment by dummdidumm** [comment]
Given this repo I can reproduce this too, now, thanks.

**Comment by dummdidumm** [comment]
Found the issue. We force `allowJs` to `true`. If I set this to `true` in the `tsconfig.json` of the repo, then the compiler will load the js file first and said error happens for the TS file, too.

I honestly see no way how we can fix this without breaking everyone else. We need this to be true so that other Svelte files which do not have `lang="ts"`, which are transformed to virtual `.jsx` files, can be imported and used in Svelte files where `lang="ts"` is set, which are transformed to virtual `.tsx` files.

I now also know why I got the `cannot redeclare block scoped variable` error - because in my other `tsconfig.json` `checkJs` is `true`.

I suggest you remove the `js`/`d.ts` duplication and instead create a `.ts` file which will be transpiled to `.js` by TypeScript.

**Comment by cengels** [comment]
Unfortunately I can't do that since the `.js` file is a compiled resource. However, you can work around the problem by creating an exported TypeScript variable which simply contains the data from the `js` file cast to the desired type. Not optimal, but it works.

But if I understand this correctly, this means that it's not actually a svelte language tools issue at all, right? After all, the problem is not that you're forcing `allowJs` to `true`, it's that (apparently) with `allowJs` set to true, there's this bizarre file order problem going on completely independently of svelte. If that's the case, I may try to post an issue about this on the TypeScript repo instead (if I still feel strongly enough about it tomorrow).

In any case, thanks for looking into this.

**Comment by dummdidumm** [comment]
Yes you understood that correctly 👍
