### ISSUE TITLE
Auto imports default to `import type`

### ISSUE THREAD

**Issue by madeleineostoja** [sveltejs/language-tools#687]
**Describe the bug**
Auto imports for Typescript modules in Svelte components always default to `import type { thing } from './thing.ts'`, even though I'm not importing types.

**To Reproduce**
1. Create a typescript module
2. Auto-import it into a Svelte component from intellisense suggestions
3. See it gets imported as a type

**Expected behavior**
Auto imports should only be imported as a type if you are explicitly importing an eported type.

**System (please complete the following information):**
 - OS: MacOS Big Sur
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode

**Comment by jasonlyu123** [comment]
Can you provide more info? At what condition does it import it as type and what are you importing?

**Comment by seaneking** [comment]
@jasonlyu123 All non-Svelte Typescript imports (functions, constants, etc) are imported as types, and I'm importing from intellisense suggestions when writing a component.

Is that what you meant? Happy to provide any other details.

**Comment by jasonlyu123** [comment]
Yeah, that's what I meant, thanks. But I can't reproduce it. I only see the `import type` when annotating type.
```ts
// Component.svelte
import type { abc  } from './abc';
export let a: typeof abc;
```
```ts
// abc.ts
export function abc() { }
```

Can you try it on a fresh project and see if it exist? 
Also, you can try if adding this to the `compilerOptions` of your `tsconfig.json` and restart your language-server to see if it make any difference.
```
"importsNotUsedAsValues": "remove",
```

**Comment by seaneking** [comment]
Sorry I think I've narrowed it down more — seems to happen consistently when importing within an attribute string (eg: in `class`, for constants and CSS-in-JS).

Setting `importsNotUsedAsValues` to `remove` seems to fix it.

**Comment by dummdidumm** [comment]
I still can't reproduce this given your description. Please post a snippet with a Svelte file, `|` as the character where your cursor is, and the TS file snippet which the variable is imported from.

**Comment by mhatvan** [comment]
I also had this happening today for a simple `.ts` file.
