### ISSUE TITLE
Provide an option to disable jsx autocompletions

### ISSUE THREAD

**Issue by donnisnoni** [sveltejs/language-tools#689]
![Screenshot from 2020-11-30 08-36-13](https://user-images.githubusercontent.com/16399020/100558023-75325880-32e7-11eb-856f-7a58928aaceb.png)
I try to trigger emmet but this autocomplete from jsx is on the first. Maybe would be great if provide an option to disable this.

Or any solution guys??

**Comment by jasonlyu123** [comment]
Can you provide minimal reproducible? I think this has something to do with the code before it. Maybe something wrong with the parsing or transformation.

**Comment by donnisnoni** [comment]
Just type this
```html
<div class="flex justify-center items-center bg-gray-100 w-screen h-screen">
  <div
    class="flex flex-col bg-white p-3 shadow-sm rounded-sm"
    style="min-width: 360px">
    <h3 class="text-center text-lg my-6 font-bold">LOGIN</h3>

    div

  </div>
</div>
```

**Comment by donnisnoni** [comment]
Maybe because of there is no  `<script>` tag yet?

**Comment by donnisnoni** [comment]
Yeah... after add `<script>` tag, its work perfectly
