### ISSUE TITLE
<template> tag breaks VS Code highlighting

### ISSUE THREAD

**Issue by ShadowfeindX** [sveltejs/language-tools#694]
**Describe the bug**

Text on the same line as html closing tags breaks syntax highlighting in VS Code.

**To Reproduce**
- Include any template tag containing any html elements with text nodes in a Svelte file.

**Expected behavior**
```html
<template>
    <h1> Hello world
    </h1>
</template>
```
should highlight the same as 
```html
<template>
    <h1> Hello world </h1>
</template>
```

**Screenshots**
Expected highlighting: 
![Expected](https://i.imgur.com/k47S2Zs.png)

Actual Highlighting:
![Actual](https://i.imgur.com/YbMaOWR.png)

Highlighting with Svelte Block:
![Svelte](https://i.imgur.com/Es4Zmq8.png)

**System (please complete the following information):**
 - OS: [Windows]
 - IDE: [VSCode]
 - Plugin/Package: ["Svelte for VSCode"]

**Additional context**
I get no warnings, errors, or hints from `svelte-check`.

**Comment by dummdidumm** [comment]
@Monkatraz any idea? To me it seems like the tag-regex inside template eats up the rest of the document without stopping at `</h1`. I tried fiddling around a little, but no luck so far.

**Comment by Monkatraz** [comment]
I'll have to take a crack at it. I think the template 'inside' pattern is taking priority over the newly introduced scope tag patterns and ending prematurely at the first `</` it finds. Liberal usage of  `applyEndPatternLast: 1` might fix it.

**Comment by dummdidumm** [comment]
It seems it's something within the attribute definitions that causes this. If I remove this section, it works.

**Comment by Monkatraz** [comment]
Textmate grammars are... um, "hungry". A pattern starts with reckless disregard of the rest of the document, so its probably something with an attribute starting and eating all the characters until it finds a character matching `(?=/?>)` or something.

**Comment by dummdidumm** [comment]
Okay now I'm completely confused ... If I comment out all references to `#attributes`, it still does not work. But if I remove the definition, it works.

**Comment by Monkatraz** [comment]
okay that's cursed

If you don't figure out whatever is causing it, I'll take a crack at it later today.

**Comment by dummdidumm** [comment]
Some more food for thought: If I comment out usage of `tags-lang`, it works, too.

**Comment by dummdidumm** [comment]
After some more digging it seems to me that the culprit is the `begin` regex of [the injections part](https://github.com/sveltejs/language-tools/blob/master/packages/svelte-vscode/syntaxes/svelte.tmLanguage.src.yaml#L85). If I change it to `(?<=>)\s` everything's ok as long as there is one space after the `>` of `<template>` - which there will be in 99% of the case, and I'm inclined to use this as a fix because I cannot find a better regex that does not eat up a char of the inner scope.

**Comment by Monkatraz** [comment]
Go for it, sounds reasonable.

**Comment by GrygrFlzr** [comment]
Even if I follow the "have at least one space after the opening tag", this is not quite fixed:
![image](https://user-images.githubusercontent.com/1460917/107350979-a8217580-6afc-11eb-8ad3-db138644bc6f.png)

All closing tags inside the `<template>` block are missing syntax highlighting.
