### ISSUE TITLE
Turn off auto-import?

### ISSUE THREAD

**Issue by plmrry** [sveltejs/language-tools#695]
**Is your feature request related to a problem? Please describe.**
Svelte files will suggest auto-imports for certain undefined variables, despite auto-import being disabled for JS and TS files in VS Code settings.

**Describe the solution you'd like**
A setting that disables auto-import (without disabling suggestions).

**Additional context**
For example, here's the Suggestions box recommending that a variable called `group` be auto-imported from the global `console` (which is not great):

![Screen Shot 2020-12-03 at 1 31 58 PM](https://user-images.githubusercontent.com/688617/101072632-51337900-356c-11eb-9359-1dde49168abd.png)

**Comment by dummdidumm** [comment]
@jasonlyu123 could that be another enhancement of your "pass js/ts settings" PR? The things are already in place, we would just need to pass in the settings if I'm not mistaken.

**Comment by jasonlyu123** [comment]
We Will need more mapping, The auto-import is in the `javascript.suggest` config, that PR only addresses `javascript.preferences`. Though they all are part of the UserPreferences interface of typescript
