### ISSUE TITLE
VSCode reports errors, but the app runs fine

### ISSUE THREAD

**Issue by nailuj29gaming** [sveltejs/language-tools#699]
**Describe the bug**
VS Code reports the following error:
```
Error in svelte.config.js

SyntaxError: Cannot use import statement outside a module svelte
``` 
in every svelte file, but the project runs fine

**To Reproduce**
1. Fork https://github.com/nailuj29gaming/chip8-vis-ide
2. Open it in visual studio code

**Expected behavior**
No errors reported by VS Code

**Screenshots**
![image](https://user-images.githubusercontent.com/54189157/101394339-5a875300-3896-11eb-936e-74d230277f7a.png)

**System (please complete the following information):**
 - OS: Windows
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode

**Comment by dummdidumm** [comment]
You must use commonjs syntax inside `svelte.config.js`, [see here](https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/in-general.md#generic-setup) for an example.

**Comment by nailuj29gaming** [comment]
Thank you! The intellisense message had me thinking the error was in the Svelte components.

**Comment by nailuj29gaming** [comment]
This is still a bug. The screenshot was poorly cropped, but the underline was on the `script` tags in the components, not in `svelte.config.js`

**Comment by dummdidumm** [comment]
The IDE extension needs the config to preprocess the code so that compiler warnings can be shown. When the config file is invalid, the error appears inside a Svelte file because that's the only place we have control over. You config file is still invalid, `export default` has to be `module.exports =`.

**Comment by nailuj29gaming** [comment]
Yes, I fixed the error in the `svelte.config.js`. That clears up why the error was in the svelte file.
