### ISSUE TITLE
Making atom-svelte package official?

### ISSUE THREAD

**Issue by kahverengi001** [sveltejs/language-tools#70]
I love to use Atom but svelte package for it, so old, so like is there anyway to talk with the author and make it official package?
It would be better language supporting I guess..

**Comment by dummdidumm** [comment]
I guess you mean the [plugin from this repo](https://github.com/UnwrittenFun/svelte-atom)? @orta for me it seems pretty straight forward to add this, not much code. On the other hand, if we add official plugins for all IDEs this might get cumbersome at some point. Then again, Atom is a popular IDE. What do you think?

**Comment by kahverengi001** [comment]
> I guess you mean the plugin from this repo?

Yeah this is what I meant.

**Comment by robinloeffel** [comment]
I strongly second @kahverengi001. The only thing holding me back from really utilizing Svelte in private projects and maybe even pushing it at work is having no support at all for it in Atom—see https://github.com/UnwrittenFun/svelte-atom/issues/3 and https://github.com/UnwrittenFun/svelte-atom/issues/8.

**Comment by orta** [comment]
I'm not against it. I am hesitant though.

I'm happy to set up the deploy infra etc but it'll need its own contributors. Considering that the atom-svelte repo has been around for 2 years and has only received one PR. It doesn't look like something people are actively working to improve and own it. That is the real sign of whether we'd be able to handle it here.

Moving the extension into this repo could also just leave it unused but now with the expectation is that people who are working on the vscode infra will also need to support atom too, which isn't going to be the case.

@robinloeffel  / @kahverengi001  are you interested in actively working and maintaining it?

**Comment by dummdidumm** [comment]
As an alternative, we could make a PR in the current repo to simply update the dependency. This should be enough (I hope).

**Comment by kahverengi001** [comment]
>  @kahverengi001 are you interested in actively working and maintaining it?

Well, I want to help development for Atom extension but I just don't even know where to start honestly. I need to check what has done and what can I do and how can I do about it. I can just simply open pull requests for whatever I have done.

**Comment by RedHatter** [comment]
> I'm happy to set up the deploy infra etc but it'll need its own contributors. Considering that the atom-svelte repo has been around for 2 years and has only received one PR. It doesn't look like something people are actively working to improve and own it. 

I use atom as my daily editor as do some of my co-workers. Svelte is a large part of our code base and bad plugin support has been a thorn in our foot for a while. I had considered contributing in the past but was hesitant based my previous experience with the author. I didn't was to spend time working on it then have my PR sit there.

If the plugin was given I new home here and not ignored I would be happy to help.

**Comment by orta** [comment]
https://github.com/sveltejs/language-tools/pull/160 starts to move it into this repo

**Comment by rixo** [comment]
The Atom plugin repository is now owned by the Svelte org, and I have just published a new updated version of the plugin, so the Svelte org now appears as the maintainer of the plugin in the Atom registry. I believe this means that the Atom plugin is de facto officially supported by Svelte now.

I'm not sure it would be possible to move the Atom plugin repo into the language tools monorepo, though, and still be able to publish to the Atom registry. I strongly doubt it actually, even if I might be mistaken.

I think this issue can be closed, and work/feedback on the Atom plugin can carry on in the (official!) [svelte-atom](https://github.com/sveltejs/svelte-atom) repo.

**Comment by dummdidumm** [comment]
Great work @rixo 🎉 
Moving it into this monorepo doesn't work, it was tried before and apparently Atom can't deal with this type of repository (https://github.com/sveltejs/language-tools/pull/160#issuecomment-683879307).
