### ISSUE TITLE
SCSS module not found

### ISSUE THREAD

**Issue by ghostdevv** [sveltejs/language-tools#700]
**Describe the bug**
SCSS module not found

**To Reproduce**
1. Setup svelte to work with scss ( Use my template [here](https://github.com/ghostdevv/svelte-scss-template) if you are unsure how to do this, scss works fine so it's not a issue with that )
2. In a component file create a script tag and give it `lang="scss"`, there should be a error at the end of the script tag saying that it is unable to find the module sass or node-sass

**Expected behavior**
There should be no error there as node-sass is installed

**Screenshots**
https://i.imgur.com/WsVojOn.gif
(gif ^)

**System (please complete the following information):**
 - OS: Windows
 - IDE: VSCode
 - Plugin/Package: Svelte for VS Code

**Additional context**
This has happened on multiple occasions, I have also tried installing sass to debug this and to no luck, this is even present on templates made by other svelte users

**Comment by dummdidumm** [comment]
Sounds like you are running into [this issue](https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/scss-less.md#scss-using-node-sass-and-having-errors). Feel free to reopen if this does not solve it.

**Comment by ghostdevv** [comment]
This wouldn't explain why scss works fine, but gives a error? @dummdidumm

**Comment by ghostdevv** [comment]
Fixed in #700
