### ISSUE TITLE
SCSS module not found (reopen)

### ISSUE THREAD

**Issue by ghostdevv** [sveltejs/language-tools#701]
An effective reopen of #700
**SCSS works fine** but still gives that error

**Comment by ghostdevv** [comment]
The full error log is this:
```
Cannot find any of modules: sass,node-sass

Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (80)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v5.0.0

The file cannot be parsed because style requires a preprocessor that doesn't seem to be setup or failed during setup. Did you setup a `svelte.config.js`? If you use SCSS, it may be necessary to add the path to your NODE runtime to the setting `svelte.language-server.runtime`, or use `sass` instead of `node-sass`. 

See https://github.com/sveltejs/language-tools/tree/master/docs#using-with-preprocessors for more info.
```

But I can confirm scss works, so it can't be these things?

**Comment by dummdidumm** [comment]
Please read the FAQ entry I linked in the original issue. TLDR: set the node environment through the corresponding setting or use `sass` instead of `node-sass`.

PS: You could have reopened the original issue.

**Comment by ghostdevv** [comment]
> lease read the FAQ entry I linked in the original issue. TLDR: set the node environment through the corresponding setting or use sass instead of node-sass. That same advice is part of the error message.
I did read it, I will try editing the settings.

> PS: You could have reopened the original issue.
I am unable to reopen it

**Comment by ghostdevv** [comment]
@dummdidumm I switched to sass and did the `includePaths` thing and that fixed it, thank you
