### ISSUE TITLE
be able to out comment a property of an element

### ISSUE THREAD

**Issue by janwillemtulp** [sveltejs/language-tools#702]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When you have a line like this:
```
<line
                x1={10}
                x2={174}
                y1={cy(line)}
                y2={cy(line)}
                stroke="rgba(0, 0, 0, 0.1)" />
```
it would be nice if you could use `command-/` to out comment a single property, for instance, only out comment the `y2` property. Currently this is not possible and it results in invalid syntax. I know the Reactjs plugin for VSCode does allow you to do so, but maybe that's because it's JSX? So, maybe it's not possible, or not easy to do, but if you quickly want to try out things, being able to out comment a single property can save a lot of time

**Describe alternatives you've considered**
I have some workarounds, like copy-pasting the original property, put that on a new line, out comment that line, and add a new property for this element instead. This especially happens when there is a relatively more complex expression defined in my property and I don't want to lose that and be able to go back to that expression in case the new value does not satisfy my needs.

**Additional context**
No

**Comment by dummdidumm** [comment]
This is unfortunately not possible. Svelte expects valid HTML, and you cannot comment attributes in HTML. See https://stackoverflow.com/questions/4744353/how-to-comment-html-tag-attribute-in-html-source-code for more info.
