### ISSUE TITLE
Get svelte(css-syntax-error) when using dark: variant in @apply of Tailwind CSS

### ISSUE THREAD

**Issue by thaicodingdev** [sveltejs/language-tools#704]
**Describe the bug**
Cannot find a way to disable the css-syntax-error when using **dark:** variant in the `@apply` statement.

**To Reproduce**
```svelte
<style lang="postcss" global>
  @import 'tailwindcss/base';
  @import 'tailwindcss/components';
  @import 'tailwindcss/utilities';

  @layer base {
    body {
      @apply bg-white text-gray-900 dark:text-white dark:bg-gray-800;
    }
  }
</style>
```

The error will occur at **dark**:text-white in the `@apply` statement.

And it says that **Semicolon or block is expected.**

**Expected behavior**
No warnings or errors.

**Screenshots**
![Screen Shot 2563-12-09 at 13 29 58](https://user-images.githubusercontent.com/67307892/101594219-e37fc500-3a23-11eb-8fa0-239801d35f91.png)

**System (please complete the following information):**
 - OS: macOS Big Sur 11.0.1
 - IDE: VSCode
 - Plugin/Package: "Svelte for VSCode"

**Comment by jasonlyu123** [comment]
This is because the svelte compiler used in the IDE also needs to understand how to preprocess it. You can follow [this doc](https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/other-css-preprocessors.md#postcss) for more info.

**Comment by thaicodingdev** [comment]
> This is because the svelte compiler used in the IDE also needs to know how to preprocess it. You can follow [this doc](https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/other-css-preprocessors.md#postcss) for more info.

I followed the guide as you see in the screenshot but still got the error.
- lang="postcss" in script tag  -- checked
- Using the svelte-preprocess -- checked
```javascript
// rollup.config.js

import autoPreprocess from 'svelte-preprocess';

preprocess: [
        autoPreprocess({
          postcss: true,
          defaults: { style: 'postcss' },
        }),
      ],
```

**Comment by jasonlyu123** [comment]
you need to set up a `svelte.config.js` as the error message suggested. We can't read the config from `rollup.config.js` as the option passed into the svelte plugin is not visible from the outside.

**Comment by thaicodingdev** [comment]
> you need to set up a `svelte.config.js` as the error message suggested. We can't read the config from `rollup.config.js` as the option passed into the svelte plugin is not visible from the outside.

Thank you. I can solve it now.
