### ISSUE TITLE
Aliases point to location outside tsconfig.json not working properly

### ISSUE THREAD

**Issue by hgl** [sveltejs/language-tools#705]
**Describe the bug**
The VSCode extension works properly for file structure and `tsconfig.json` like this:

```
src
  |- Button.svelte (contains import name from "~/name")
  |- name.ts
tsconfig.json
```
```
{
  "compilerOptions": {
    "baseUrl": "src",
    "paths": {
      "~/*": ["*"]
    }
  },
  "include": ["src"]
}
```

But it fails if they are changed to this
```
src
  |- Button.svelte (contains import name from "~/name")
  |- tsconfig.json
name.ts
```
```
{
  "compilerOptions": {
    "baseUrl": "..",
    "paths": {
      "~/*": ["*"]
    }
  },
  "include": ["**/*", "../*"]
}
```
If I add a `src/person.ts` that contains `import name from "~/name"`, tsc can correctly find the file. Seems the problem is with svelte-check.

**To Reproduce**
As previously described.

**Expected behavior**
Correctly import name as tsc does.

**Screenshots**
![image](https://user-images.githubusercontent.com/7038035/101627676-aafade00-3a59-11eb-84da-a724d8deea64.png)

**System (please complete the following information):**
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode 102.70

**Additional context**

**Comment by dummdidumm** [comment]
I cannot reproduce this, works as expected for me. You need to restart the Svelte language server to pick up tsconfig changes.

**Comment by hgl** [comment]
Oh, restarting fixed it. Sorry for the noise.
