### ISSUE TITLE
Typescript type guards not working for deeply nested element directives

### ISSUE THREAD

**Issue by hgl** [sveltejs/language-tools#706]
**Describe the bug**
With `strict: true` enabled in `tsconfig.json`, the following code reports error:

```svelte
<script lang="ts">
    export let result: {
        items: number[]
    } | undefined
</script>

{#if result}
{#each result.items as item}
    {result.items.length}
{/each}
{/if}
```
![image](https://user-images.githubusercontent.com/7038035/101632356-c0273b00-3a60-11eb-8008-b253f424b344.png)

**Expected behavior**
No error

**System (please complete the following information):**
Svelte for VSCode 102.7.0

**Comment by hgl** [comment]
A related one:

```svelte
<script lang="ts">
    import Item from "./Item.svelte"
    import type {Writable} from "svelte/store"
    export let result: Writable<{
        items: number[]
    } | undefined>
</script>

{#if $result}
<Item result={$result} />
{/if}
```
Where `Item.svelte` is
```svelte
<script lang="ts">
    export let result: {
        items: number[]
    }
</script>

{result.items.length}
```
![image](https://user-images.githubusercontent.com/7038035/101634109-30cf5700-3a63-11eb-9cdf-3ba5005782fd.png)

**Comment by jasonlyu123** [comment]
These two are separate issues. The first one is more related to #619, the latter is related to #493.
But I don't know if the former can be "solved". It's similar to this in typescript. And the `a` inside the callback is possibly undefined
```ts
let a: string[] | undefined;

if (a) {
    a.map(() => {
        a
    })
}
```

**Comment by hgl** [comment]
Not sure if it's possible to translate to this, but this can narrow it:

```typescript
let a: string[] | undefined;

if (a) {
    const b = a
    a.map(() => {
        b
    })
}
```

**Comment by hgl** [comment]
Since it's a duplicate, I'll close first. Thanks for the links.
