### ISSUE TITLE
How to disable error "cannot find module" on modules served by webpack plugins?

### ISSUE THREAD

**Issue by CherryDT** [sveltejs/language-tools#707]
Following situation:

In my webpack config, an inline svg loader is configured for SVG files.

In my svelte file, I have code like this:

```html
<script>
  import logo from '../images/logo.svg'
</script>

{@html logo}
```

This works fine at runtime, but it shows an error in VSCode `Cannot find module '../images/logo.svg'. svelte-type-checker(2307)`.

I was looking at the plugin options and I already googled but I can't find a way to tell your plugin not to show this error. What is the recommended solution?

If there is none, take this issue as a feature request.

Thank you

**Comment by dummdidumm** [comment]
You need an ambient type definition in a `.d.ts` file:
```
declare module "*.svg";
```
The Sapper starter template has such a file which you can basically copypaste and put into your `src`: https://github.com/sveltejs/sapper-template/blob/master/src/ambient.d.ts

**Comment by CherryDT** [comment]
No I don't use TypeScript.

**Comment by CherryDT** [comment]
No I don't use TypeScript. And I put such a file there nonetheless, yet the error remains.

**Comment by dummdidumm** [comment]
Sorry for the initial confusion. I read the error more closely now. This error message is from the `svelte-type-checker` extension, not the Svelte for VS Code extension. I suggest you remove that extension because it's deprecated and the Svelte for VS Code extension has all the features that extension has.

**Comment by CherryDT** [comment]
Ah, thanks for checking. I was actually checking first if such an extension is installed, but it seems I missed it. I then assumed that the error comes from your extension and maybe sort of a "submodule" since the type checker extension has been integrated into this one...

Never mind then!
