### ISSUE TITLE
"Option" Component highlighted as "option" html element

### ISSUE THREAD

**Issue by pushkine** [sveltejs/language-tools#711]
![Code_2020-12-11_14-25-40](https://user-images.githubusercontent.com/30108880/101908825-f24daf80-3bbc-11eb-9828-649caa4950bc.png)
![Code_2020-12-11_14-25-16](https://user-images.githubusercontent.com/30108880/101908832-f4177300-3bbc-11eb-8583-fab393d92298.png)

**Comment by pushkine** [comment]
Unless the fix hasn't been published yet, It still occurs on my machine

**Comment by dummdidumm** [comment]
Yes, it's not published yet, the `Fixed` label marks it as fixed but not-yet-released, when it's closed it will be released.
