### ISSUE TITLE
Stable Emmet in VS Code?

### ISSUE THREAD

**Issue by MarkTanashchuk** [sveltejs/language-tools#716]
I would like to know if it is now possible to have a stable working Emmet in VS Code in `.svelte` files?

I have this VS Code config:
```
"emmet.includeLanguages": {
    "svelte": "html"
},
"emmet.showExpandedAbbreviation": "inMarkupAndStylesheetFilesOnly", 
```

But it does not help completely, for example, if I write `.fz` in html - it may turn into `.font-size:` (instead of `<div class="fz"></div>`), and if I write `aic`(`align-items: center`) between `<style></style>` - in emmet hints may appear borderAction (and other such things)

**Comment by dummdidumm** [comment]
I cannot really reproduce this - but you shouldn't need to add the `includeLanguages` anyway, the extension has built-in emmet support. What happens if you remove `svelte` from `includeLanguages`?

**Comment by MarkTanashchuk** [comment]
> I cannot really reproduce this - but you shouldn't need to add the `includeLanguages` anyway, the extension has built-in emmet support. What happens if you remove `svelte` from `includeLanguages`?

Then all abbreviations except js stop working (my `script` tag is at the top of file. If I put `style` at the top, the abbreviations for css start working)

**Comment by MarkTanashchuk** [comment]
Same if i remove `"emmet.showExpandedAbbreviation": "inMarkupAndStylesheetFilesOnly"`

**Comment by MarkTanashchuk** [comment]
Reinstalled Svelte for VS Code extension and I started getting a notification `Couldn't start client Svelte'

https://i.imgur.com/M9qTHPN.png

Could that be the problem?

**Comment by dummdidumm** [comment]
That's strange. If the extension can't be started obviously you won't see emmet completions - but you also shouldn't see any other completions, or hover info etc. . Strange. Did you change any settings of the Svelte for VS Code extension?

**Comment by MarkTanashchuk** [comment]
I removed all the svelte related settings and yes, I guess an error was because of `svelte.language-server.runtime` parameter with wrong path to node.exe. I removed it and it worked properly =)
