### ISSUE TITLE
organizeImports not working in vs-code

### ISSUE THREAD

**Issue by newtriks** [sveltejs/language-tools#72]
**Describe the bug**
There doesn't appear to be an option available to organize imports if currently within a svelte file.

**To Reproduce**
Hit shift cmd P and search for organize imports, it doesn't display any suggestion.

**Expected behavior**

**System (please complete the following information):**
 - OS: OS X
 - IDE VSCode
 - Plugin Svelte Beta

**Additional context**
Works on javascript files

**Comment by dummdidumm** [comment]
This simply is not supported yet, we have to add that to the code actions capabilities somehow.
