### ISSUE TITLE
Errors thrown about non-existent Tailwind config file in project with nested structure

### ISSUE THREAD

**Issue by mhatvan** [sveltejs/language-tools#720]
**Describe the bug**
I am working on a project where the root of the frontend application is nested a couple of levels. I don't think it is relevant but the frontend is also initialized as git submodule.

Every component in VSCode reports:
```
Error in svelte.config.js Error: Specified Tailwind config file "/home/markus/Applications/Webdevelopment/Freelancing/WebIgniter/Duplicheck/pageverify/tailwind.config.js" doesn't exist.
```
which is true, the actual path is: `/pageverify/frontend/webapp/tailwind.config.js`

Everything still works fine with Tailwind, it just spams my VSCode output with errors and I might oversee relevant errors that way.

**To Reproduce**

For example a code snippet that is treated in a way you don't expect.

**Expected behavior**
No errors reported.

**System (please complete the following information):**
 - OS: Ubuntu 20.10
 - IDE: VSCode

**Comment by mhatvan** [comment]
I am using the latest tailwindcss version (2.0.2) currently if that is relevant.

**Comment by dummdidumm** [comment]
I need a minimum reproducible, best in form of a github repo. From your description I cannot see where your tsconfig/rollup config/svelte config is and how it looks like.

**Comment by mhatvan** [comment]
Hey @dummdidumm, I created a repository for you where I was able to reproduce it: https://github.com/mhatvan/tailwind-svelte-config-issue

After running `yarn install` in `/frontend/webapp`, navigate to `/src/components` and open `AuthContainer.svelte`
The opening script tag should give you following error:

```
Error in svelte.config.js

Error: Specified Tailwind config file "<path>/tailwind-svelte-config-issue/tailwind.config.js" doesn't exist.
```

**Comment by dummdidumm** [comment]
The problem is within your `postcss.config.js`. You tell it that the config file is within `./tailwind.config.js`, which is read relative to the root of the repository, not relative to the directory the file is in. So either change it to `${__dirname}/tailwind.config.js` or try omitting it.

**Comment by mhatvan** [comment]
That did the trick, thanks ;)
