### ISSUE TITLE
code formatter breaks the syntax highlight of pug template

### ISSUE THREAD

**Issue by hoishing** [sveltejs/language-tools#721]
**Describe the bug**
When using Pug template, code formatter splits the `<template lang="pug">` into two lines, then the syntax highlight of Pug stop functioning.

**To Reproduce**
1. install svelte-preprocess and pug 
2. enable auto format on save and use Svelte extension as the default formatter
```
  "editor.formatOnSave": true,
  "[svelte]": {
    "editor.defaultFormatter": "svelte.svelte-vscode"
  },
```
3. create template using Pug, and save

**Expected behavior**
1. the Pug syntax highlight is intact even the the template tag split into 2 lines. 
2. the code formatter should not split the template tag, as its not longer then the Prettier default settings (80 chars)

**Screenshots**
before saving, syntax highlight is intact:
![before saving](https://i.imgur.com/MS6x1ij.png)

after saving, the formatter splits the template tag into 2 lines, no more syntax highlight
![after saving](https://i.imgur.com/sVSlCZC.png)

**System (please complete the following information):**
 - OS: Windows 10
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode, svelte-preprocess, pug

**Comment by dummdidumm** [comment]
In the meantime you can add `<!-- prettier-ignore -->` on top of the `<template`-line to prevent formatting.

**Comment by hoishing** [comment]
as Prettier doesn't support Pug at the moment, this work-around get the job done. thanks 👍

**Comment by dummdidumm** [comment]
With `prettier-plugin-svelte 2.x` which now comes prepackaged with the extension, this should be fixed. If you use `prettier-plugin-svelte` locally within your project, you need to bump it.
