### ISSUE TITLE
Emmet ! for creating boilerplate in svelte files

### ISSUE THREAD

**Issue by MarkTanashchuk** [sveltejs/language-tools#722]
When I was using vanilla HTML in development, I used to start with template creation - using `! + Tab` command

But in Svelte components I need to write `script+style + Tab` every time, which is getting annoying

It would be nice if I could also use `! + Tab` to create a template in Svelte files as well

Preferably:
1. When TS is installed (using `setupTypescript.js`), `lang="ts"` is set in script tags.
2. Order of tags could be defined in settings.
3. Cursor was in place where html markup should be when command is executed(
`script - new line - cursor there - new line - style`
)

**Comment by jasonlyu123** [comment]
One of the reasons I found it hard is that everyone might have their own taste. Either order, language, or indentation. If we have to consider all of this, It's a big work. If we don't consider this, this feature is just not that useful in my opinion.

For now, You can create your own snippet following this [doc](https://code.visualstudio.com/docs/editor/userdefinedsnippets). 
For example:
```json
{
	"scaffold": {
		"prefix": ["scaffold"],
		"body": [
			"<script lang=\"ts\">",
			"$1",
			"</script>",
			"",
			"",
			"<style>",
			"$2",
			"</style>"
		]
	}
}
```

**Comment by dummdidumm** [comment]
Good point. I'll close this issue since there's a good inbuilt-option of VS Code.
