### ISSUE TITLE
Export Svelte for VS Code API for other extensions.

### ISSUE THREAD

**Issue by kwangure** [sveltejs/language-tools#725]
I'd like to extend svelte-vscode via another extension, but svelte-vscode doesn't export its API.

More specifically, I'd like access to the svelte-vscode language server. I need to use the same version as svelte-vscode for consistency's sake, rather than packaging my own copy.

It should be as simple as returning an API object from the [`activate` entry function](https://github.com/sveltejs/language-tools/blob/master/packages/svelte-vscode/src/extension.ts#L38). See [docs here](https://code.visualstudio.com/api/references/vscode-api#extensions).

```
export function activate(context: vscode.ExtensionContext) {
	...
	// export API 
	return {
		languageServer: getLS(),
	}
}
```

I suppose exporting svelte-vscode's [command-palette commands](https://github.com/sveltejs/language-tools/blob/master/packages/svelte-vscode/package.json#L386) via the API might be applicable here.

**Comment by dummdidumm** [comment]
Out of curiosity, what's your use case? Could it be something that is also is worth adding to this extension?

**Comment by kwangure** [comment]
Nothing concrete yet, I'm experimenting. VS Code has added shiny APIs in the past several months (i.e WebView, Custom Editor, Notebook, New Debugger). I'm experimenting with how I can use these to render, view and edit Svelte components. I suppose if something sticks, it may be a candidate for adding to Svelte for VS Code.

**Comment by dummdidumm** [comment]
How would exporting the API help you in this case? In other words, what would you call to integrate with the extension? Right now the vs code extension is mostly glue code to connect to the `svelte-language-server` which has most of the smarts.

**Comment by kwangure** [comment]
I expect the boilerplate code would look something like this:
```js
const svelteExtension = vscode.extensions.getExtension("svelte.svelte-vscode");
if (!svelteExtension) {
	return vscode.window.showWarningMessage(
		"You need the 'Svelte for VS Code' extension to use 'My Awesome Extension'."
	);
}
if (!svelteExtension.isActive) {
	await svelteExtension.activate();
}

/*

As exported from 'Svelte for VS Code' as:
export function activate(context: vscode.ExtensionContext) {
	...
	// export API 
	return {
		languageServer: getLS(),
	}
}

*/

const { languageServer } = svelteExtension.exports;

languageServer.sendRequest('$/getCompiledCode', svelteCode);

```


It's currently not possible to run two instances of `svelte-language-server` since they register the same commands. I haven't looked to much into the SLS source code and why this is, but I've traced to [these commands](https://github.com/sveltejs/language-tools/blob/7069031013caf86d3d5a761e5052df83e2d2810c/packages/language-server/src/server.ts#L168) that leads to the error: `command 'function_scope_0' already exists` etc.

**Comment by kwangure** [comment]
That said, assuming the conflict didn't exist, if `Svelte for VS Code` is running language server 0.11.2 and `Awesome Extension` is running 0.11.0 it may have funky consequences in userland. It makes sense to have a consistent language server across extensions.
