### ISSUE TITLE
Using `noUncheckedIndexedAccess` in TS is not allowed

### ISSUE THREAD

**Issue by dkzlv** [sveltejs/language-tools#727]
**Describe the bug**
Currently if you add the said setting to `tsconfig.json`, you'll get a cryptic error: `[91merror[0m[90m TS5023: [0mUnknown compiler option 'noUncheckedIndexedAccess'.`
It's a rather new setting, it was introduced in [TS 4.1](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-1.html#checked-indexed-accesses---nouncheckedindexedaccess).

**To Reproduce**
Add `"noUncheckedIndexedAccess": true,` row in `tsconfig.json` under `compilerOptions`.

**Expected behavior**
Should work.

**System (please complete the following information):**
 - OS: Mac OS X
 - IDE: VS Code
 - Plugin/Package: "Svelte for VSCode", `svelte-check`

**Comment by jasonlyu123** [comment]
Where did you see the error? The latest version of Svelte for VSCode should be published with typescript 4.1.2

**Comment by dkzlv** [comment]
@jasonlyu123 Here's the screenshot for you!

![pic](https://user-images.githubusercontent.com/2846746/103925794-1acbb980-5129-11eb-8ec9-8fa675e6caa1.png)

**Comment by dummdidumm** [comment]
Did you bump the TS version in your `package.json` and run `npm i` afterwards? I get the same error when I'm using an older TS version, but not when I'm using the new one.

**Comment by dkzlv** [comment]
@dummdidumm Yes, you're right, I'm sorry! I missed the fact that this project for some reason didn't have the latest version of TS even though I only started it a week ago.
The issue does not happen in the project with current version of TS.
