### ISSUE TITLE
capture attribute type definition is incorrect

### ISSUE THREAD

**Issue by brunnerh** [sveltejs/language-tools#728]
**Describe the bug**
The `capture` attribute is typed as a flag (optional `boolean`), it can have values though.

**To Reproduce**
```html
<input type="file" capture="environment"/>
```

> Type 'string' is not assignable to type 'boolean | undefined'.

**Expected behavior**

Accept the three values [according to specification](https://w3c.github.io/html-media-capture/#dom-htmlinputelement-capture):

> The attribute's keywords are `user`, `environment`, and the empty string, which map to the user, environment, and the implementation-specific state respectively.

**System (please complete the following information):**
 - OS: Windows 10
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode

**Comment by jasonlyu123** [comment]
It's not exactly incorrect though. It was previously a Boolean attribute.
