### ISSUE TITLE
Inaccurate breakpoints in VS Code during debugging

### ISSUE THREAD

**Issue by geekox86** [sveltejs/language-tools#731]
**Describe the bug**
Breakpoints are inaccurate in VS Code.
Sometimes they take you to transpiled code by Svelte/TypeScript.
Other times they take you just after the breakpoint line.
They also may not be hit at all.
It seems related to source mapping.

**To Reproduce**
[Here is a repro link](https://github.com/geekox86/svelte-debugging)

Try setting breakpoints at lines 4 to 9 in `App.svelte`.

**Expected behavior**
A breakpoint should be consistently hit just before the line is executed anywhere in the script parts of svelte files.

**Information about your Svelte project:**
```
System:
    OS: macOS 11.1
    CPU: (4) x64 Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz
    Memory: 6.70 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.5.0 - /usr/local/bin/node
    yarn: 1.22.10 - /usr/local/bin/yarn
  Browsers:
    Chrome: 87.0.4280.88
    Firefox: 83.0
    Safari: 14.0.2
  npmPackages:
    rollup: ^2.35.1 => 2.35.1 
    svelte: ^3.31.1 => 3.31.1
  IDE: VS Code Insider v1.53.0-insider (with Svelte for VS Code v102.8.0) and also JetBrains Rider 2020.3
```

**Severity**
It is annoying not being able to debug and affects productivity.

**Comment by geekox86** [comment]
Anybody is looking into this guys?

**Comment by geekox86** [comment]
Thank you for taking the time to let us know.
A little feedback is definitely going to make me more grateful and patience.

**Comment by mithrendal** [comment]
Only .svelte files are affected😬, when debugging a svelte project and debugger hits a breakpoint in a pure ts file, then line is always accurate 😍. 

I also saw that each import or export line adds one line off ...🤔 maybe only these two  statements have to be treated differently in the source map ?

e.g. when having  five imports and  two exports you will be off by 7 lines ... 🤓

**Comment by dummdidumm** [comment]
Could you try again with latest versions of `svelte`, `svelte-preprocess` and `rollup-plugin-svelte`? This might work as expected now.

**Comment by mithrendal** [comment]
@dummdidumm so great 😍 ... did a npm update and guess what ... debugging works now !  In vscode and chrome it halts now exactly at the choosen breakpoint in vscode in a svelte component ... this fix is really great ! Thank you. 🎉

**Comment by dummdidumm** [comment]
🎉
