### ISSUE TITLE
Each Block Typing Issue

### ISSUE THREAD

**Issue by JAD3N** [sveltejs/language-tools#732]
I'm trying to iterate over a properties values by using {#each...}, and I have two typings (this is a TypeScript project) in my Svelte component.

```svelte
<script lang="ts">
    import Transition from './Transition/Transition.svelte';

    type Options = { text: string, value?: string }[];
    type OptionsGroup = Options[];

    export let options: Options | OptionsGroup = [];
</script>

{#each options as option}
    <div>example</div>
{/each}
```

I would expect the type of option in the each statement to be ```Options | OptionsGroup``` but VS Code is giving me an error saying:

>Argument of type 'Options | OptionsGroup' is not assignable to parameter of type 'ArrayLike<{ text: string; value?: string; }>'.

I'm unsure of what exactly is going wrong as the build and dev tasks are working fine with no errors at all, it only seems to be an issue with VS Code.

**System:**
- OS: Manjaro (Linux)
- IDE: VSCode
- Plugin/Package: Svelte for VSCode

**Comment by dkzlv** [comment]
I also found a strange bug with `{#each}`.

Smallest repro possible:

```svelte
<script lang="ts">
  let data: { name: string } | null = null,
    someArr = [1, 2, 3];
</script>

{#if data}
  <!-- Works fine -->
  {data.name}
  {#each someArr as _}
    <!-- Highlights an error! -->
    {data.name}
  {/each}
{/if}
```

Mac, VS Code, running the latest plugin. I have a gut feeling it is somewhat connected to this issue.

![Proof of bug](https://user-images.githubusercontent.com/2846746/103645148-96323d00-4f68-11eb-8771-325879cdfb58.png)

**Comment by dummdidumm** [comment]
@dkzlv that's #619

**Comment by dummdidumm** [comment]
I fear this is not possible to fix on our side, it seems it's a TypeScript issue. You would get the same error when you do this:

```

function each<T>(
    array: ArrayLike<T>, // or T[], doesnt matter for the error
    callbackfn: (value: T, index: number) => any
): any{ /* doesnt matter */ };

each(options, a => a); // The same TS error
```

**Comment by jasonlyu123** [comment]
You can do this instead. I think I have this typescript error before and got it works by trying some random combination lol
```svelte
<script lang="ts">
  type Option = { text: string, value?: string };
  type OptionsGroup = Option[];

  export let options: Array<Option | OptionsGroup> = [];
</script>

{#each options as option}
  <div>example</div>
{/each}
```

**Comment by JAD3N** [comment]
Thank you for the clarification, I've amended my typings as recommend and that has pretty much solved it.

**Comment by ITenthusiasm** [comment]
Awesome! @JAD3N if you ever want to go back to the previous syntax you were using, it's doable now. It's working for me on VS Code. 👌🏾
