### ISSUE TITLE
editor.codeActionsOnSave

### ISSUE THREAD

**Issue by pushkine** [sveltejs/language-tools#734]
I'm using this handy option in vscode that runs the "Organize imports" action on save 
```json
"[typescript]": {
    "editor.codeActionsOnSave": { "source.organizeImports": true }
},
```
Running the action manually through `F1 > Organize imports` does work in svelte files, but this option appears to get ignored

**Comment by jasonlyu123** [comment]
You'll have to use `[svelte]` instead of `[typescript]`
