### ISSUE TITLE
Should svelte-check support Prettier validation?

### ISSUE THREAD

**Issue by guidobouman** [sveltejs/language-tools#736]
With a project based on the default template, with TypeScript enabled, svele-check generates a great statusreport about the code. With typescript errors and everything. But format errors are not taken into account.

When Svelte-check runs, should it not also pick up un a `.prettierrc` or `prettier-plugin-svelte` dependency? If it detects a prettier setup, it could run something along the lines of `prettier -w ./src/*` to check if all formatting is according to style.

The `validate` script can of course be extended with the simple script, but this could make the svelte-check that much more valuable.

Maybe while this is looked at, `eslint` could also be considered?

**Comment by dummdidumm** [comment]
I would like to keep the scope of `svelte-check` seperated from formatting and eslint. It would add additional maintenace burden for no greater benefit, some may even explicitly not like it and then we would ship additional code which might break for no benefit from them. After all it's very easy to just call these commands one after the other through a npm script (like `npm run svelte-check && npm run format && npm run lint`). I think the better option is to enhance the template with another script which could add these commands for you.

**Comment by guidobouman** [comment]
Okay, that makes sense.

On the other hand: Where does the split between format & bugs lie? Because the ESLint recommended rules are nearly all designed to catch possible bugs. Should those not be part of the checks? Is the name svelte-check then not a little misleading?

**Comment by dummdidumm** [comment]
I agree that the name can be misleading.

While some eslint rules are there to catch possible bugs, it's still optional and many people wouldn't want it having shoved in their face. Also what would the default configuration be? If people want to use eslint they set it up their way, using the recommended eslint setup. I think it would be surprising to them if `svelte-check` then suddenly starts doing these things for them.

**Comment by guidobouman** [comment]
Yeah, I agree. It should not do any magic for the user. But if someone configures ESLint. What should then happen? `svelte-check` could pickup on a config file and run it for them.

Just like it also picks up on wether someone configured TypeScript or not. And it adheres to the TypeScript rules, right?

Actually in the codebase it looks like `-check` is just a CLI to the language server diagnostics. So it should probably live there, if this was ever to land. Which does not make a lot of sense, because Prettier, ESLint & TS have their own setups, right?

**Comment by dummdidumm** [comment]
Yes `svelte-check` is just a small cli wrapper for the language server. So it would need to be added there.
If we were to do it, what about configuration? Pass cli args meant for prettier/eslint through? How to document without it getting out of sync? I just think it's better stay focused on the use case it has right now. It's more flexible for users and they can just follow the official documentation of eslint/prettier to set things up.

**Comment by guidobouman** [comment]
About the configuration: What stance did the language server take for typescript? I guess it parses the .tsconfig file?

But yeah, you're right. This is already solved by ESLint and Prettier. My understanding of svelte-check was incomplete, it just provides CLI access to the language server.

Thanks that you took the time to think along, appreciated!

**Comment by dummdidumm** [comment]
> 
> 
> About the configuration: What stance did the language server take for typescript? I guess it parses the .tsconfig file?

That's correct
