### ISSUE TITLE
WebStorm / IntelliJ support?

### ISSUE THREAD

**Issue by shirotech** [sveltejs/language-tools#74]
It seems like there is a plugin for LSP https://plugins.jetbrains.com/plugin/10209-lsp-support
https://github.com/gtache/intellij-lsp

I tried running the executable `/usr/local/bin/svelteserver` but nothing happens, can anyone point me to the right direction? Thanks.

<img width="1091" alt="Screen Shot 2020-05-09 at 2 37 10 am" src="https://user-images.githubusercontent.com/1149825/81427337-069c7a80-919e-11ea-98a4-013336ea142c.png">

![Screen Shot 2020-05-09 at 2 48 00 am](https://user-images.githubusercontent.com/1149825/81429164-bf63b900-91a0-11ea-8076-5047c9b7736f.png)

**Comment by dummdidumm** [comment]
I honestly don't know if the IntelliJ plugin even uses this language-server right here. Since this is a question related to that plugin, please ask the question over there.

**Comment by shirotech** [comment]
I thought all LSP are standard, but anyways thanks for the quick response, I'll try asking over there. Cheers.

**Comment by dummdidumm** [comment]
Maybe related #34

**Comment by jasonlyu123** [comment]
I also tried it on vetur's vls. same result.

**Comment by benmccann** [comment]
> I thought all LSP are standard

I'm not sure, but the code seems to refer to VSCode specifically:

https://github.com/sveltejs/language-tools/blob/a14cf1b61b5958159e342f96a391b9ac94eb5aa1/packages/language-server/src/server.ts#L9

It's pretty confusing that the repo is generically named "language-tools" instead of something like "vscode". I don't know if there are plans for other plugins to live in this repo? If not, it might be worth renaming this one. I would think each should have their own repo.

**Comment by benmccann** [comment]
Actually, it does look like most IDEs support LSP. IDEA IntelliJ / WebStorm don't, but most others including Atom do.

https://microsoft.github.io/language-server-protocol/implementors/tools/

**Comment by orta** [comment]
This should conform to the standard LSP interface (so it should work), though I'm afraid I have no advice on how to run the module as a standalone CLI tool. I don't know, I'd recommend digging into the source and seeing how it works.

**Comment by dummdidumm** [comment]
[From this comment](https://github.com/sveltejs/language-tools/issues/361#issuecomment-671846219) it seems that it will work if you add the `stdio` flag.

**Comment by dummdidumm** [comment]
Closing in favor of #361
