### ISSUE TITLE
Autosave for svelte projects

### ISSUE THREAD

**Issue by oodavid** [sveltejs/language-tools#749]
**Is your feature request related to a problem? Please describe.**
There's an _emotional_ difference between coding with the REPL and using VSCode - the REPL compile-as-you-type really adds to the "magic" of the coding experience.

With VSCode, that extra `CTRL+S` definitely makes local dev feel slower.

**Describe the solution you'd like**
An optional save (& compile) as-you-type.

**Describe alternatives you've considered**
VSCode has an auto-save feature, but I don't want that for _all_ projects:
https://code.visualstudio.com/docs/editor/codebasics#_save-auto-save

**Comment by dummdidumm** [comment]
I'm not sure if it's worth the additional effort to implement this. There was an issue about this on VS Code's GitHub repo to make this setting configurable per language [but it received insufficient votes](https://github.com/microsoft/vscode/issues/42170) so it will not be implemented soon.
