### ISSUE TITLE
Action parameter type error

### ISSUE THREAD

**Issue by pushkine** [sveltejs/language-tools#754]
```svelte
<script lang="ts">
	function action<P extends Partial<{ border: "left" | "right" }>>(_, props: P) {}
	action(null, { border: "right" });
</script>

<div use:action={{ border: 'right' }} />

```
`use:action` throws `Type 'string' is not assignable to type '"left" | "right"'. ts(2345)`
Expected no error, as calling the action in the script block does not throw
`{ border: 'right' as const }` throws `Unexpected token ts(-1)`

**Comment by dummdidumm** [comment]
I am not able to reproduce this.

**Comment by pushkine** [comment]
<img width="1047" alt="Code_2021-01-16_02-25-35" src="https://user-images.githubusercontent.com/30108880/104793357-738ef800-57a2-11eb-8add-b616f68de525.png">


I get it in a blank file without any tsconfig, not sure what to say

**Comment by jasonlyu123** [comment]
I can reproduce it. My guess is that the type parameter of the action is inferred from the action parameter instead of the other way around. We might need to find another way to transform the action in svelte2tsx

**Comment by dummdidumm** [comment]
Have another transformation lying around somewhere, need to look it up.
