### ISSUE TITLE
VSCode: Semantic token range off by 1 in store accesses

### ISSUE THREAD

**Issue by Monkatraz** [sveltejs/language-tools#762]
![image](https://user-images.githubusercontent.com/34875062/104555384-03923d80-55fb-11eb-8be8-f6b9f435002e.png)

~~Looks like the `$` was not accounted for in the range offset.~~

**Comment by jasonlyu123** [comment]
$ Is because it's transformed into a function in `svelte2tsx` and `r` is a source mapping issue like the one in each block.

**Comment by Monkatraz** [comment]
Ah, that makes sense. Man, that source-mapping issue is a real thorn in the side. Feel free to close if you feel that this is a duplicate.

**Comment by dummdidumm** [comment]
I think there's no previous issue like this so I prefer to keep it open for visibility and to track it.

**Comment by jasonlyu123** [comment]
The semantic tokens feature doesn't use the `mapRangeToOriginal` function to source map so it's not fixed. reopen this
