### ISSUE TITLE
Svelte Beta vs JamesBirtles / UnwrittenFun

### ISSUE THREAD

**Issue by benmccann** [sveltejs/language-tools#77]
Are we ready to have people start using https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode ?

https://github.com/sveltejs/integrations points to the old plugin location at https://marketplace.visualstudio.com/items?itemName=JamesBirtles.svelte-vscode

The old plugin has about 90x as many installs. I'm wondering how we can notify these users that there's a new plugin. Some ideas in order of effectiveness:

* delete the new plugin. transfer the old plugin to sveltejs and make it the official one. now all users are using the new plugin
* push an update to the old plugin that spits out warnings somewhere that you're using the old plugin
* remove the old plugin from the marketplace and hope users eventually figure out they have the old one

**Comment by dhonx** [comment]
I prefer the second option

**Comment by dummdidumm** [comment]
I don't know where but I think @orta said something along the lines of "take over Svelte Plugin at some point". So this would mean the (currently old) Svelte Plugin would get an update.

As to when that is: In my opinion not yet, but soon. There is still lots of refactorings/groundwork going on so I think this repo is in a little too early state.

**Comment by orta** [comment]
Yeah, I was figuring we'd ship an update to the birtle version to recommend folks move over once it "Svelte Beta" got stable and comfy (which I don't know when that is, I figure someone will probably tell me, but it's not now for sure )

**Comment by benmccann** [comment]
I would guess the "Beta" one already works better than the non-beta one. Are there any known issues that make the "Beta" one less stable or a worse overall experience?

**Comment by dummdidumm** [comment]
The experience is definitely better, but it's not that stable yet, as in we add new code a lot and that may break some things along the way. For example we added `svelte2tsx` to get better typing not just inside `script` but also inside template, and that that brought in some new bugs which were reported.

**Comment by benmccann** [comment]
I guess even in the long-term it could be helpful to have a "beta" one and "stable" one. Then there'd be an extension that could be used to push out changes and get early feedback before giving it to all users

**Comment by sw-yx** [comment]
do we have publishing control over james birtles' one? does he want to hand it over?

**Comment by orta** [comment]
I don't think we do, but he's game to have it deprecated

**Comment by dummdidumm** [comment]
I think we can start pushing this, Svelte Beta is getting more stable every day and people are still way too often using the old version (almost 100k by now).

**Comment by orta** [comment]
Alright, agreed - OK, so the TODO IMO:

- Create GH workflow which uses tags, so anyone anyone with write access can deploy ( I do this in [make-monaco-builds](https://github.com/orta/make-monaco-builds/) )
  - It deploys svelte-vscode to `svelte.svelte-vscode` using the package json version
- Make the nightly CI push to a new identifier (`svelte.svelte-vscode-nightly`) which would be a new extension in the store
- https://github.com/UnwrittenFun/svelte-vscode is now read-only so we can't make PRs to it, but we can make a fork to make a final "move to this extension" popup, then persuade @UnwrittenFun  to publish it  ❤️ 

Reasoning:

- The current beta extension is `svelte.svelte-vscode`, we should keep that identifier for the prod version
- I forced our hand on semver a bit, so 1.0 = v100 :D

**Comment by dummdidumm** [comment]
Sounds good!

Just to clarify for myself:
- The GH workflow would be the same as our current one, with the difference that it only deploys the extension, and it runs on tags, not nightly, which means as soon as someone with write access creates a new tag, the action will run.
- The extension's version inside `package.json` will have some meaning now for the stable version, and it would start at 100.0.0 because IT'S AWESOME (and you forced it :P ).

Would you lead on this? You already had contact with @UnwrittenFun before and you know the extension deployment stuff very well.

**Comment by orta** [comment]
- 1, Yes. The prod deploy process would be "edit package.json to version number; git tag [number]; git push --tags"
- 2, Yes, because 100 is a perfectly nice round starting point.

Yeah, I'll take a shot at this 👍🏾

**Comment by dummdidumm** [comment]
@orta could you as a first step rename "Svelte Beta" to "Svelte (Official)" ? I think this would help getting more people to install this version.

**Comment by dummdidumm** [comment]
Birtle's extension is unpublished, so there will be no confusion about this anymore.
