### ISSUE TITLE
Syntax highlight incorrect when preceding component is self-closing

### ISSUE THREAD

**Issue by arxpoetica** [sveltejs/language-tools#773]
The syntax highlighting is incorrect when the preceding component is self-closing. (See screenshot below.)

You can copy the following code into a `*.svelte` file to see:

```svelte
<SelfClosingComponent/>
<div>stuff</div> <!-- highlight problem with opening tag -->
<div>stuff</div> <!-- no highlight problem -->

<SelfClosingComponent/>
<meta/> <!-- highlight problem -->

<SelfClosingComponent/>
<div/> <!-- highlight problem, but also not valid html, so...??? -->

<SelfClosingComponent/>
<!-- <Intro/> --> <!-- highlight problem -->
<!-- <Intro/> --> <!-- returns to normal after problem -->

<SelfClosingComponent></SelfClosingComponent>
<div>stuff</div> <!-- no highlight problem when component has ending tag -->
```

**Expected behavior**
Highlight should return to normal behavior following self-closing components such as `<SelfClosingComponent/>`.

**Screenshot**
![image](https://user-images.githubusercontent.com/111424/104949228-d7b8e400-597b-11eb-847c-91068d566cd2.png)

**System (please complete the following information):**
 - OS: MacOS Catalina v10.15.3
 - IDE: VSCode v1.52.1 Commit ea3859d4ba2f3e577a159bc91e3074c5d85c0523
 - Plugin/Package: Svelte for VSCode

**Comment by arxpoetica** [comment]
Potentially related: https://github.com/sveltejs/language-tools/issues/299

**Comment by pushkine** [comment]
A simpler example 
```svelte
<div/>
<div></div>
```
<img width="105" alt="Code_2021-01-22_18-04-16" src="https://user-images.githubusercontent.com/30108880/105521479-44194780-5cdc-11eb-9a23-53727cf8c7e9.png">

It only happens if there is no space before the closing part
<img width="103" alt="Code_2021-01-22_18-05-01" src="https://user-images.githubusercontent.com/30108880/105521574-64490680-5cdc-11eb-8414-a880b5ed224d.png">

**Comment by arxpoetica** [comment]
Woo hoo! Thanks @dummdidumm!
