### ISSUE TITLE
Wrong autocomplete for Components nested in objects

### ISSUE THREAD

**Issue by pushkine** [sveltejs/language-tools#776]
<img width="427" alt="Code_2021-01-22_18-09-46" src="https://user-images.githubusercontent.com/30108880/105522042-08cb4880-5cdd-11eb-931d-4d8bebaf8d35.png">
<img width="656" alt="Code_2021-01-22_18-09-07" src="https://user-images.githubusercontent.com/30108880/105522082-154fa100-5cdd-11eb-9f9f-8f5fee1315d8.png">
Expected autocomplete to show properties, got every global variable instead 

edit: actions nested in objects have the same issue (`use:object.action`)

**Comment by jasonlyu123** [comment]
This is the same cause of #538. One workaround is to self close it first like this.
```
<Slot />
```
or
```
<Slot. />
```
And then trigger completion

**Comment by dummdidumm** [comment]
Possible solution: Try to parse it with `svelte2tsx`. If that fails, get the position where the autocompletion should happen and backtrack up until specific delimiters like whitespace, `{` or `<`, take everything inbetween and append it to the fallback-document.
So this:
```svelte
<script>
   import { Hi } from './hi'
   let foo = 'bar';
</script>
<Hi.
```
becomes
```js
import { Hi } from './hi'
let foo = 'bar';
Hi.
```
(the `Hi.` part is new)

This could also solve other cases where intellisense is not working properly currently.
