### ISSUE TITLE
Add typescript support for sapper:prefetch attribute (sapper v0.29.0)

### ISSUE THREAD

**Issue by fivemru** [sveltejs/language-tools#778]
**Describe the bug**
TS error while adding `sapper:prefetch` attribute to <a> tag.

In version 0.29.0, the `rel="prefetch"` attribute should be replaced with `sapper:prefetch`
https://github.com/sveltejs/sapper/blob/master/CHANGELOG.md#0290

**To Reproduce**

```svelte
<a sapper:prefetch href=".">home</a>
```

**Expected behavior**
No TS error.

**Screenshots**
![image](https://user-images.githubusercontent.com/30273470/105577098-8b5d1200-5d88-11eb-8ee2-fe4f1e5d6872.png)

**Comment by jasonlyu123** [comment]
What's the version of the svelte extension you're using? The lastest one should have the support.

**Comment by fivemru** [comment]
I am using version v102.8.0.

![image](https://user-images.githubusercontent.com/30273470/105577744-7d10f500-5d8c-11eb-91c4-91491a6b1ec0.png)

**Comment by jasonlyu123** [comment]
The latest is actually 104.0. I guess your vscode is older than 1.52.0 so it's incompatible with the latest release

**Comment by fivemru** [comment]
For some reason vscode did not notify that there was a new version, reinstalled it, after which it was able to install the latest version 104.0, everything worked!
Thank you very much!
