### ISSUE TITLE
Specify typescript types in each block when using union types

### ISSUE THREAD

**Issue by SeanAllanMacKay** [sveltejs/language-tools#783]
I'm not sure if this would be considered a bug, enhancement, or whether I just don't know how this is done properly in Svelte + Typescript.

### Scenario

I have an array of objects that are 1 of 2 types using a union. It is used for a navigation menu, so order does matter and they need to exist in the same array. The types are something like this:
```typescript
type MenuItem = {
    text: string;
    href: string;
};

type SubMenu = {
    text: string;
    subMenu: SubMenuItem[]
};

type Menu = (MenuItem | SubMenu )[]
```

### Issue
When using an `#each` block to iterate over that array:
```svelte
{#each menuItems as { text, subMenu, href }}
   ...
{/each}
```

Typescript shows these warnings:
> Property 'subMenu' does not exist on type 'MenuItem | SubMenu'.
> Property 'href ' does not exist on type 'MenuItem | SubMenu'.

Resolving this within the script tag is easy, as I can use `as MenuItem` or `as SubMenu` to differentiate what properties are in fact present, but to the best of my knowledge Svelte doesn't let me do that within the each block.

**Comment by jasonlyu123** [comment]
You can have a type guard with an if block or logical expression
```svelte
{#each menuItems as menu}
  {#if 'href' in menu}
    {menu}
  {/if}
  {'href' in menu && menu.href}
{/each}
```
if the logic is too long or you want to reuse it, create a type guard function in the script
```ts
function isMenuItem(menu: MenuItem | SubMenu): menu is MenuItem {
}
```
