### ISSUE TITLE
Error: Expected 2 arguments, but got 1. (ts) for <div transition:fade >

### ISSUE THREAD

**Issue by bfanger** [sveltejs/language-tools#785]
Since svelte-check 1.1.29 the transition shorthand `<div transition:fade>` incorrectly reports the 
`Error: Expected 2 arguments, but got 1.` error.

When using the shorthand notation, svelte calls the fade (or any other function) with 2 arguments, the element and an empty object. [REPL](https://svelte.dev/repl/3dfed2eaa77a4ae9b5be415a22420d48?version=3.32.0)

**To Reproduce**

```html
<script lang="ts">
  import { fade } from "svelte/transition";

  let visible = true;

  function toggle() {
    visible = !visible;
  }
</script>

<button on:click={toggle}>Toggle</button>
{#if visible}
  <div transition:fade>Fades in and out</div>
{/if}
```

Demo: https://github.com/bfanger/svelte-check-transition-bug

The failed run: https://github.com/bfanger/svelte-check-transition-bug/runs/1783108223?check_suite_focus=true

**Comment by dummdidumm** [comment]
This is a result of #767 , transitions/animations/use directives are now transpiled differently. Looking at Svelte's [source code](https://github.com/sveltejs/svelte/blob/master/src/runtime/transition/index.ts), the error is actually correct, so Svelte's typings need to be adjusted. Right now they don't mark the second parameter as optional.

**Comment by jackwestmoretab** [comment]
I have also experienced this issue -- thanks @dummdidumm for looking into it!

**Comment by bfanger** [comment]
I think the svelte patch fixes the error when using fade (and the other build ins)  but svelte-check is still incorrect

Using the transition:fade shorthand behaves as if you'd written transition:fade={ {} } and fade is passed 2 params, not 1.

**Comment by dummdidumm** [comment]
What do you mean by that?
`transition:fade` currently is translated (by svelte2tsx) to `__sveltets_ensureTransition(__sveltets_ElementNode)` for intellisense purposes.  `transition:fade={ {} }` would be `__sveltets_ensureTransition(__sveltets_ElementNode, {})` which is correct.

**Comment by bfanger** [comment]
Both should be translated to __sveltets_ensureTransition(fade(__sveltets_ElementNode, {})) 

Check the repl https://svelte.dev/repl/3dfed2eaa77a4ae9b5be415a22420d48?version=3.32.0

**Comment by dummdidumm** [comment]
Yes it needs to be translated to that for the current Svelte version, but no longer once the second parameter becomes optional. For compatibility with earlier versions I created a PR which does what you suggest for the built-in transitions/animations.

**Comment by bfanger** [comment]
I can't predict what svelte compiler will do in the future, but right now it adds the {} iwhen there are no explicit parameters. 
Im not sure if that behavior is the same for all shorthands notations.

**Comment by dummdidumm** [comment]
A fallback for older Svelte versions is now available which should silence the error.
