### ISSUE TITLE
Feature request: Rename element in VSCode

### ISSUE THREAD

**Issue by duongdominhchau** [sveltejs/language-tools#791]
In VSCode, when the language is set to HTML, I can press `F2` (**Rename Symbol**) to rename an element. For example, when I have this code:
```html
<header>hello</header>
```
I can put the caret inside the word header, press `F2` and change the name, both `<header>` and `</header>` will be changed. The caret can be placed inside the start tag or end tag, both work.

Using the extension Svelte, this is not possible anymore.

**Comment by jasonlyu123** [comment]
One downside is that we have rename component feature. Would this confuse users? Component rename being rename the default import
```svelte
<script>
import Component from './Component.svelte'
</script>
<Component></Component>
```
to
```svelte
<script>
import Component2 from './Component.svelte'
</script>
<Component2></Component2>
```

but this only renames the tag pair.

```svelte
<header>hello</header>
```
to 
```svelte
<header2>hello</header2>
```

**Comment by duongdominhchau** [comment]
I didn't notice that there is a rename feature already. From what I see, current rename behavior is consistent with how the types are renamed in all other languages. This is a tough choice when both are consistent with how other extensions works. Can we show a menu to choose what to rename when user invokes **Rename symbol**? My imagined rename feature works like this:

1. Press **F2** to rename
2. A menu is shown with two choices, **1. Component** and **2. Tag pair**
3. User press the corresponding number (**1** or **2**) to choose what to rename.
4. The rename box appears

This will break workflow of existing users, we can provide a setting to set default choice for that menu. This way, old users know the behavior is changed but can still work in the old way, and new users know that there are two different rename features.

I don't have experience developing VSCode extension so I don't know if it is possible.

**Comment by dummdidumm** [comment]
To me it feels consistent if I can only rename the tag pair if it's a html element, and rename all occurences if it is not. I would say we just add it and see what users say. They can always turn that off.
