### ISSUE TITLE
Typescript project references error in svelte-check

### ISSUE THREAD

**Issue by yjp20** [sveltejs/language-tools#792]
**Describe the bug**
Typescript project references do not work as expected in `svelte-language-server` and `svelte-check`

**To Reproduce**
repo: https://github.com/yjp20/svelte-monorepo-ts-bug-demo
1. Run svelte-check in root
2. Prints error "... is not under 'rootDir'"

**Expected behavior**
Using project references, we would expect the rootDir error to not appear. Interestingly, it works as expected if the dependency is immediate `app/App -> library/Component` but doesn't if it is "nested" `app/App -> app/Nested -> library/Component`. The dependency graph is attached below as an example.

![Untitled drawing](https://user-images.githubusercontent.com/44457064/106378456-4ec49280-63e8-11eb-9760-44b21e3cceb9.png)

**System (please complete the following information):**
 - OS: macOS
 - Plugin/Package: [e.g. "Svelte for VSCode", or `svelte-language-server`, `svelte-check`, or `svelte2tsx` if you use one of the npm packages directly]

**Comment by dummdidumm** [comment]
I cannot reproduce the error, for me there are 0 errors. I got the rootDir error in the VS Code extension though, but not reliaebly. According to [TypeScript's chapter on project-references](https://www.typescriptlang.org/docs/handbook/project-references.html) you need to set the `rootDir` option in each `tsconfig.json` to a common root dir, which would be `"../../"` in this case.

**Comment by yjp20** [comment]
Sorry for the noise, I think I missed that last part within.
