### ISSUE TITLE
VScode-insiders mac M1 language-server crash

### ISSUE THREAD

**Issue by Valexr** [sveltejs/language-tools#797]
**Describe the bug**
Yesterday after update vscode-insiders svelte-language-server it crash

**To Reproduce**
Just run on Mac M1 vscode-insidrs arm64 with Svelte for Vscode plugin svelte-template & open anything File.svelte in editior window.

**Expected behavior**
Svelte-language-server CRASH

**Screenshots**
![svelte-language-server-crash](https://user-images.githubusercontent.com/5656366/106707103-befa3080-6601-11eb-8457-eb275423b00d.png)

**System (please complete the following information):**
Version: 1.53.0-insider
Commit: 8d779a4fadaadec06b44b8875a1d3c4adba8e380
Date: 2021-02-02T16:35:13.314Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin arm64 20.3.0

**Additional context**

**Comment by jasonlyu123** [comment]
See #794 and #724

**Comment by dummdidumm** [comment]
Closing as dublicate
