### ISSUE TITLE
Cannot read property 'length' of undefined error in VS Code with wc, and named slot with a binding directive

### ISSUE THREAD

**Issue by arackaf** [sveltejs/language-tools#803]
Is this about svelte@next? This project is currently in a pre-release stage and breaking changes may occur at any time. Please do not post any kind of bug reports or questions on GitHub about it.

No

**Describe the bug**

When compiling to custom elements, if you have a named slot with a binding directive, VS Code will emit a false error of `Cannot read property 'length' of undefined` in the VS Code console, even if you have a svelte config file with `customElement: true` in it.

**Logs**
Please include browser console and server logs around the time this bug occurred.

n/a

**To Reproduce**
To help us help you, if you've found a bug please consider the following:

Svelte Component:

```html
<div bind:this={rootEl} class="root">
  <h1 class="x">Hi there BEFORE SLOT</h1>
  <slot name="s" bind:this={s} />
  <h1>Hi there AFTER SLOT</h1>
</div>
```

svelte.config.js

```js
module.exports = {
  compilerOptions: {
    customElement: true
  }
};
```

Removing the bind:this={s} causes the error to disappear. 

With the necessary webpack config, this code all works properly, but the false error in the console is concerning. 

Occasionally, this won't be possible, and that's fine – we still appreciate you raising the issue. But please understand that Svelte is run by unpaid volunteers in their free time, and issues that follow these instructions will get fixed faster.

**Expected behavior**

No error.

**Stacktraces**
If you have a stack trace to include, we recommend putting inside a `<details>` block for the sake of the thread's readability:

<details>
  <summary>Stack trace</summary>

  Stack trace goes here...
</details>

**Information about your Svelte project:**
To make your life easier, just run `npx envinfo --system --npmPackages svelte,rollup,webpack --binaries --browsers` and paste the output here.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)

N/A

VS Code: latest

- Your operating system: (e.x. OS X 10, Ubuntu Linux 19.10, Windows XP, etc)

Mac

- Svelte version (Please check you can reproduce the issue with the latest release!)

3.32.1

- Whether your project uses Webpack or Rollup

webpack 

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Svelte entirely?

Moderate

Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Comment by dummdidumm** [comment]
It's a `svelte2tsx` issue unrelated to the web components target.

**Comment by arackaf** [comment]
@dummdidumm good to know - thank you kindly for replying. Is there currently any workaround, config or otherwise?

**Comment by dummdidumm** [comment]
I don't know if that would break other things in your code but you could wrap the slot with a div or another tag and bind on that. 

```
<div bind:this={rootEl} class="root">
  <h1 class="x">Hi there BEFORE SLOT</h1>
  <div bind:this={s}>
    <slot name="s" />
  </div>
  <h1>Hi there AFTER SLOT</h1>
</div>
```
This is also the way you'd have to do it if you don't target web components, because slots cannot have directives for the normal dom target.

**Comment by arackaf** [comment]
@dummdidumm sadly that doesn't work in this case. Yeah I know slot directives are invalid for non-wc. Fortunately I can just ignore the false errors until there's a fix. 

So I'm guessing there's no way to shut off certain Svelte errors in VS Code, like there is for warnings? Ie `a11y-missing-attribute` etc.

**Comment by dummdidumm** [comment]
There is not in this case because it's a crash/nullpointer while walking the AST, so unfortunately you'll have to live with it for the time being.

**Comment by arackaf** [comment]
@dummdidumm gotcha - thanks again for the info!

**Comment by arackaf** [comment]
@dummdidumm jesus that was fast - https://github.com/sveltejs/language-tools/pull/804

I know it's not done yet but thanks a ton! Svelte team is amazing.
