### ISSUE TITLE
Svelte for VSCode reports type mismatch when using optional types in component splat.

### ISSUE THREAD

**Issue by thislooksfun** [sveltejs/language-tools#805]
**Describe the bug**
Svelte for VSCode reports type mismatch when using optional types in component splat.

**To Reproduce**
```svelte
//////////////
// A.svelte //
//////////////

<script lang="ts">
  import B from "./B.svelte";

  interface MRE {
    name?: string;
  }

  let mre: MRE = { name: "hello!" };
</script>

<B {...mre} />
```

```svelte
//////////////
// B.svelte //
//////////////

<script lang="ts">
  export let name: string | undefined;
</script>

<span>Hello {name}!</span>
```

**Expected behavior**
The plugin / language server should not have an issue with the last line of `A.svelte`

**Actual behavior**
See screenshot below.

**Screenshots**
<img width="1015" alt="Screen Shot 2021-02-05 at 11 19 59 PM" src="https://user-images.githubusercontent.com/5367333/107109781-adcf4080-6808-11eb-8850-87215c7a0285.png">

**System (please complete the following information):**
 - OS: macOS 11.2 (20D64)
 - IDE: VSCode 1.53.0
 - Plugin/Package: Svelte for VSCode v104.3.0

**Additional context**
The problem boils down to the error `Property '<X>' is optional in type '<A>' but required in type '<B>'`, which is true, but in TypeScript making a property optional is just a nicer way of saying `| undefined`, and as such those two properties are in fact interchangeable, as evidenced by the fact that the following works just fine:
```ts
interface MRE {
  mre?: string;
}

function fn(): string | undefined {
  return "hello";
}
const obj1 = { mre: fn() };
const obj2: MRE = obj1;

console.log(obj2)
```

Additionally running `svelte-check` (v0.1.59) on the same code reports no errors.

**Comment by dummdidumm** [comment]
The TypeScript error is correct. It is a difference to TypeScript if the property is optional, or if it is required but could be set to undefined. This makes a difference for example for `Object.keys`.
Your TypeScript snippet is not correct. [This playground snippet](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgILIN7ILAChnIBGA-AFzIDOYUoA5sgD7ICuIAJhDKBGwNx4BfPHlCRYiFACFMeAoXJUaIek1YcuIHv1xDceBAHsQVIuWkBeTAO2HjYZHHLpLGa-qMm4AFQOSzySzhtPCA) shows the error.
```ts
interface A { 
  b?: string | undefined;
}

interface B {
  b: string | undefined;
}

const b: B = {}; // error
const a: A = {};
const aToB: B = a; // error <-- this is the situation in your Svelte code
```

To make the error go away, you need to provide an initializer to the exported property:

```svelte
//////////////
// B.svelte //
//////////////

<script lang="ts">
  export let name: string | undefined = undefined;
</script>

<span>Hello {name}!</span>
```

**Comment by thislooksfun** [comment]
Odd, I thought it worked when I tested it locally in a raw .ts file, but I guess I did it wrong. Thanks for the workaround!
