### ISSUE TITLE
VS Code freezes when the last character of a custom event handler is deleted

### ISSUE THREAD

**Issue by ProxyOxide** [sveltejs/language-tools#808]
**Describe the bug**

I noticed some strange behavior when using a component with custom events. If I have `<Foo on:bar={e => alert("hey")} />` and I start deleting from the end of the event handler, the VS code window hangs as soon as the body of the event handler becomes empty `<Foo on:bar={} />`

**To Reproduce**

Foo.svelte:
```
<script lang="ts">
    import { createEventDispatcher } from "svelte";
    const dispatch = createEventDispatcher();

    function func() {
        dispatch("bar", {abc: 123})
    }
</script>
```

App.svelte:
```
<script lang="ts">
	import Foo from "./Foo.svelte";
</script>

<Foo on:bar={e => alert("hey")} />
```

Place the cursor at the end of the event handler right before the closing `}`. Backspace until the event handler body becomes `{}`. 

**Expected behavior**

VSCode doesn't crash and I can continue editing the app component. 

**System (please complete the following information):**
 - OS: Windows 10 Home 2004 19041.746
 - IDE: VSCode 1.53.0 Remote on WSL2 (Ubuntu 20.04)
 - Plugin/Package: Svelte for VSCode 104.4.0

**Additional context**

Minimal project to reproduce the issue
[SvelteExample.tar.gz](https://github.com/sveltejs/language-tools/files/5948911/SvelteExample.tar.gz)

**Comment by jasonlyu123** [comment]
This is weird. I can see a high CPU usage on the main process of vscode, not extension host or language server. From my understanding, the extension can't block the UI thread. 

After some more digging, I found disabling `svelte.plugin.typescript.semanticTokens.enable` would prevent the problem. But I don't know why. It freezes before asking the language server to update semantic tokens.

**Comment by jasonlyu123** [comment]
Found the reason. There is a negative length in the semantic tokens result. We need to filter that out.
