### ISSUE TITLE
Slot prop not found on slot element itself

### ISSUE THREAD

**Issue by brunnerh** [sveltejs/language-tools#817]
**Describe the bug**
Slot properties are only found within the slot element, but not on the element itself. Svelte allows using the property on the element, so the error is simply a bit misleading. Possibly only surfaced as error when using TypeScript with sufficiently strict settings.

**To Reproduce**
Create a component with slot properties and use the property on the element declaring the property (here the error in on the `class` usage):

```svelte
<Component n={10}>
	<div slot="item" let:zebra class={zebra}>Hello {zebra}</div>
</Component>
```

[[REPL]](https://svelte.dev/repl/23849b31f2014f98abaa35d3116be1bc)

**Expected behavior**
Slot property is in scope and no error is raised.

**Screenshots**
![image](https://user-images.githubusercontent.com/834235/107882126-f7deb300-6ee7-11eb-8e72-8149ebd3e694.png)

**System (please complete the following information):**
 - OS: Windows 10 64bit
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode

**Comment by dummdidumm** [comment]
We need to pull the jsx-transformation on level up, surrounding the tag. So for example in [this test](https://github.com/sveltejs/language-tools/tree/master/packages/svelte2tsx/test/htmlx2jsx/samples/component-default-slot-let-destructure) it should become

```jsx
<>{() => { let {thing:{ a }} = __sveltets_instanceOf(Component).$$slot_def['default'];<><Component>
    <h1>Hello { a }</h1>
</Component></>}}</>
```

**Comment by brunnerh** [comment]
@dummdidumm Thank you for the fix

I just tested this and if the `let:prop` is after its usage, you still get a svelte warning instead of a type error:

> 'prop' is not defined [svelte(missing-declaration)]

Example screenshot:

![image](https://user-images.githubusercontent.com/834235/108622567-f0646000-7439-11eb-980f-1fa2bf838b81.png)

The generated output works regardless of the order, though. Of course i can just reorder the attributes to get rid of the error as a workaround.

**Comment by dummdidumm** [comment]
This is a Svelte compiler bug, I created https://github.com/sveltejs/svelte/issues/6009 for that.
