### ISSUE TITLE
Wrong syntax highlighting on closing angle brackets of opening script and style tags

### ISSUE THREAD

**Issue by scharpentier0** [sveltejs/language-tools#822]
the closing angle brackets `>` of my opening `<script>` and `<stlye>` tags is colored wrong and I clearly remember this not being the case a few weeks ago. 

**To Reproduce**
In VSCode:
1. Use a theme where the brackets are not white or grey. Native theme Monokai Dimmed makes this very visible.
2. Use Svelte for VSCode
3. Create a .svelte file and use a `<style>` or `<script>` tag
4. Look at the difference between opening and closing angle bracket of opening tag (`<style>/*<-- this one*/</style>`)

**Expected behavior**
The closing angle bracket of the opening `<style>` or `<script>` tag should be the same color as every other angle brackets.

**Screenshots**
Monokai Dimmed
![image](https://user-images.githubusercontent.com/16188226/108072397-d7703f00-7034-11eb-84ed-ef17c17e23e1.png)
![image](https://user-images.githubusercontent.com/16188226/108072413-de974d00-7034-11eb-864e-a94c18168274.png)
Mariana Pro (cool)
![image](https://user-images.githubusercontent.com/16188226/108072358-ca535000-7034-11eb-8099-283bd3c45569.png)
![image](https://user-images.githubusercontent.com/16188226/108072377-d0e1c780-7034-11eb-83d2-877915860896.png)

**System (please complete the following information):**
 - OS: Windows 10
 - IDE: VSCode
 - Plugin/Package: "Svelte for VSCode"

**Additional context**
I disabled every other plugin.

**Comment by AradAral** [comment]
Haha, I was just about to open an issue for this very same problem!

Will this be addressed? It's annoying. Not good for my OCD!
