### ISSUE TITLE
svelte2tsx svg image tag don't have attribute href

### ISSUE THREAD

**Issue by windwp** [sveltejs/language-tools#823]
svelte2tsx svg image tag don't have attribute href
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/image

![image](https://user-images.githubusercontent.com/7578110/108446752-38944e80-7291-11eb-89d7-7f4887ba1ca9.png)

**Comment by whataboutpereira** [comment]
Does svelte-check also need a new release for this fix to take effect? Thanks!

**Comment by dummdidumm** [comment]
A new version of `svelte-check` was released.

**Comment by whataboutpereira** [comment]
Thanks a bunch!
