### ISSUE TITLE
Svelte for VS Code doesn't wanna install.

### ISSUE THREAD

**Issue by tombohub** [sveltejs/language-tools#837]
**Describe the bug**
After clicking "install" in VScode, it says "installing" for a long time. I don't know how long because I didn't wait, but at least 5-10min.

**To Reproduce**
search for "Svelte" in VSCode extensions.
Find "Svelte for VS Code" by Svelte.
Click "Install"

**Expected behavior**
To install extension in reasonable time.

**Screenshots**
http://prntscr.com/10306li

**System (please complete the following information):**
 - OS: Windows 10, WSL1 Ubuntu 
 - IDE: VS Code
 - Plugin/Package: Svelte for VS Code

**Additional context**
No

**Comment by dummdidumm** [comment]
Does this happen for other extension, too, or just the Svelte extension?

**Comment by tombohub** [comment]
@dummdidumm only for "Svelte for VS Code" extension.

**Comment by dummdidumm** [comment]
I can install the extension without problems, Windows 10, latest VS Code.

**Comment by tombohub** [comment]
@ is it on WSL?

**Comment by dummdidumm** [comment]
No, no subsystem - may need try that out.
Which VS Code version do you use? Does the installation work with an older version of the extension?

**Comment by tombohub** [comment]
@dummdidumm VS Code version is 1.53.2. Here is 'about' screenshot: http://prntscr.com/10380ce

Is the old version called "Svelte Intellisense" by ardenivanov? If yes then that one is working. It took little bit longer than usual, maybe 10-15seconds , but installed eventually.

If not, what's the name of the old extension? I will try to install

**Comment by jasonlyu123** [comment]
@tombohub the older version number. You can choose to `install another version` in the context menu of the extension toolbar. 
About WSL, I can install it on my Ubuntu WSL.

**Comment by tombohub** [comment]
@jasonlyu123 thanks, did you try WSL1? 

Regarding older version, I have googled and it seems one can only choose if the extension is already installed. Since I couldn't install the extension I cannot choose the older version. Is that correct?

Update: I have tried install again. The extension is installed with an error:
```
[2021-02-21 22:12:18.088] [renderer1] [error] Error while installing 'svelte.svelte-vscode' extension in the remote server. Corrupt ZIP: end of central directory record signature not found
[2021-02-21 22:12:18.088] [renderer1] [info] Trying to download 'svelte.svelte-vscode' extension locally and install
[2021-02-21 22:12:45.374] [renderer1] [info] Successfully installed 'svelte.svelte-vscode' extension
```

But the behaviour is still unusual and I have to uninstall it 2 times. First time uninstall. It says "Uninstalled". I Reload Window. Then I can still see "Uninstall" so click second time. Reload Window. Now it looks like it's uninstalled.

**Comment by Mlocik97** [comment]
It seems that Your system or VS Code is corrupted, I don't think, installation at all has anything to do with extension itself.

**Comment by tombohub** [comment]
@Mlocik97 ok, thanks for trying to figure it out.
I will close it down with a note that it only happens with "Svelte for VS Code" extension. Hopefully it remains isolated case.

**Comment by dummdidumm** [comment]
You could try again and see if it works now, I just did another extension release. If it still does not work, I suspect something related to your specific setup.

**Comment by tombohub** [comment]
@dummdidumm Thanks, it installs way faster now. Still, I need to uninstall it 2 times. Acts like separate extension for remote WSL1 and for local. It's the only time I've seen this. I am ok with that, just saying in case you hear more about this. Thanks for the improvement!

**Comment by dummdidumm** [comment]
One reason could be that the extension is 18 mb packed and about 80mb (I think) unpacked. So it just takes a little longer to install than for others.
