### ISSUE TITLE
Why is a required prop's type "T | undefined" with strictNullChecks enabled?

### ISSUE THREAD

**Issue by AradAral** [sveltejs/language-tools#847]
Say you have the following component (it's using TypeScript, of course):

`MyComponent.svelte`:
```svelte
<script lang="ts">
    export let label: string;
</script>
...
```

As you can see, the `label` prop is required, I have not supplied a default value and thus it's considered a required prop.
Now, if I have [`strictNullChecks`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#--strictnullchecks) set to `true` in my `tsconfig.json` file, I expect a required component prop like `label` in this case to not be able to receive `null` or `undefined` unless I explicitly specify that in their type.

`tsconfig.json`:
```json
"compilerOptions": {
    "strictNullChecks": true
}
```

However, Svelte appears to make the type of the `label` prop `string | undefined` behind the scenes, and that means the consumer of this component could pass undefined as the value of `label`, which obviously defeats the whole purpose of enabling `strictNullChecks` in the first place.
```svelte
<MyComponent label={undefined} /> <!-- No error! Even though "strictNullChecks" is "true" + the type of "label" is "string" -->
```

**Comment by AradAral** [comment]
@dummdidumm Hi, are you sure this is related to Svelte language tools and not the Svelte compiler itself?

**Comment by dummdidumm** [comment]
This is a decision from the early days that bites us now. Essentially, we decided to make props optional if the `strict` compilerOption is not set. I'd very much like to revisit this decision and change it so that properties that have no initializer are treated as being required, which would make this work as expected for you (no `| undefined`).

**Comment by AradAral** [comment]
@dummdidumm 
> I'd very much like to revisit this decision and change it so that properties that have no initializer are treated as being required, which would make this work as expected for you (no | undefined).

I think that would be great and it makes MUCH more sense that way.

**Comment by dummdidumm** [comment]
Extension version 105 and `svelte-check` 2.0.0 now always mark uninitialized properties as required.
