### ISSUE TITLE
Bug: Using the auto-subscription syntax for a store that was defined in the context="module" script yields an error. 

### ISSUE THREAD

**Issue by AradAral** [sveltejs/language-tools#850]
Take a look at the `Test` component in the following REPL:
https://svelte.dev/repl/4859affa8c1c436783a9d9a6d537c903?version=3

A store is created in a `context="module"` script tag, and it's being used with a dollar sign `$` prepended to it, in the markup. It works as expected. However, the very same code in VS Code shows an error:

![image](https://user-images.githubusercontent.com/26527405/109713346-58434500-7bb6-11eb-9d30-96cdf51a33f1.png)

Note that it works and compiles properly, in other words, the compiler gives no errors; so it must be the Svelte VS Code extension that's the problem, basically it doesn't properly recognize any store that's been defined in the `context="module"` script, and as a result causing a red squiggly to appear under `$count` here.

Also, it's only when the `lang="ts"` attribute is present on the `<script>` tag that the red squiggly appears.

I'd appreciate it if this can be fixed soon.

**Comment by fivemru** [comment]
Faced the same problem: `Error: Cannot find name '$username'. Did you mean 'username'? (ts)` when `username` created in `context="module"`.

---

There is one more error when running svelte-check:
```
> svelte-check --ignore src/node_modules/@sapper

/src/routes/my/test.svelte:2:2
Hint: '$username' is declared but its value is never read. (ts)
<script lang="ts">
  import { username } from './_store';
```
Code:
![image](https://user-images.githubusercontent.com/30273470/109781629-23b4a500-7c19-11eb-8490-45312f602a92.png)

Version:
```
    "svelte": "^3.35.0",
    "svelte-check": "^1.2.0",
    "typescript": "^4.2.2"
```

**Comment by AradAral** [comment]
@fivemru Is the screenshot correct though? Because as it appears you're not defining `username` in the a `context="module"` script tag but in a separate file.

**Comment by fivemru** [comment]
> @fivemru Is the screenshot correct though? Because as it appears you're not defining `username` in the a `context="module"` script tag but in a separate file.

The screenshot is for the 2nd case. Added one more for the 1st.

**Comment by AradAral** [comment]
@fivemru Oh okay. Got it.

**Comment by bjon** [comment]
We got the same problem

**Comment by dummdidumm** [comment]
The second error is unrelated. I'd also argue it's correct because you only write to the store and never read it.  By doing `$username = ..` you tell Svelte to subscribe to that store but you never use it. In this case `username.set(..)` is the better option.

**Comment by dummdidumm** [comment]
Using the auto-subscription syntax for a store that was defined in the context="module" script should no longer yield an error as of VS Code extension 104.6.0 / `svelte-check` 1.2.1
