### ISSUE TITLE
Starting v104.4.4 lines of code above $storename cause "Type Foo has no call signatures" etc. errors (with latest dependencies)

### ISSUE THREAD

**Issue by vatro** [sveltejs/language-tools#859]
**Describe the bug**
With (since) v104.4.4 (incl., last ok: v104.4.3) I get **a lot** of `"Type Foo has no call signatures"` errors in my project mostly after creating instances of Classes `let foo = new Foo()`, simple assignments to boolean values or to undefined, at the end of ternaries etc., **yet not everywhere / always** 🤔.

👉 **Adding an (optional) semicolon after the certain expressions fixes the errors!**

EDIT: When using "Svelte for VSCode" 1.0.4.44 or above, **anything** written above the `$` prefixed store name causes errors (with currently latest versions of Svelte / Svelte ts-app template dependencies). Only lines above `$storename`-lines are affected. Lines above reactive statements' `$` are ok, see https://github.com/sveltejs/language-tools/issues/859#issuecomment-791701349

**To Reproduce**
Since the problem doesn't seem to occur everywhere / always (?), maybe: take a bigger existing `semi: true` Svelte/TS component and remove them with Prettier `semi: false` with "Svelte for VSCode" >= v104.4.4 installed.

EDIT: Meanwhile successfully reproduced, see https://github.com/sveltejs/language-tools/issues/859#issuecomment-791701349

**Expected behavior**
No errors as with <= v104.4.3

**System (please complete the following information):**
 - Windows 10
 - IDE: VSCode
 - "Svelte for VSCode" >= v104.4.4

**Additional context**
`tsconfig.js`
```
{
    "extends": "@tsconfig/svelte/tsconfig.json",
   
    "compilerOptions": {
        
        // tested, none of these have something to do with the errors
        "target": "ESNext",
        "strict": true,
        "strictNullChecks": false,
        "noImplicitAny": false,
        "strictFunctionTypes": true,

        // "Svelte for VSCode Problem": "no call signatures" etc. errors: 
        // v103.0.0: ok
        // v104.0.0: ok
        // v104.0.0: ok
        // v104.4.0: ok
        // v104.4.3: ok
        // v104.4.4: errors start

    },
    "include": [
        "src/**/*"
    ],
    "exclude": [
        "node_modules/*",
        "__sapper__/*",
        "public/*"
    ]
} 
```
Svelte 3.35.0
TypeScript 4.2.3

**Comment by dummdidumm** [comment]
Could you provide a code snippet where this occurs?

**Comment by vatro** [comment]
> Could you provide a code snippet where this occurs?

sorry, not atm, but they occur at many different places / cases + not always, mostly as I've described above. I couldn't figure out any "real" logic yet. Will take a look again at it later.

**Comment by dummdidumm** [comment]
As long as it's a reproducible code snippet I'm fine, you don't need to track down the logic

**Comment by vatro** [comment]
@dummdidumm Ok, I was able to reproduce it:

1. Create a fresh svelte-ts-app 
```
npx degit sveltejs/template svelte-typescript-app
cd svelte-typescript-app
node scripts/setupTypeScript.js
```
2. Update all dependecies
```
 "devDependencies": {
    "@rollup/plugin-commonjs": "^17.1.0",
    "@rollup/plugin-node-resolve": "^11.2.0",
    "@rollup/plugin-typescript": "^8.2.0",
    "@tsconfig/svelte": "^1.0.10",
    "rollup": "^2.40.0",
    "rollup-plugin-css-only": "^3.1.0",
    "rollup-plugin-livereload": "^2.0.0",
    "rollup-plugin-svelte": "^7.1.0",
    "rollup-plugin-terser": "^7.0.2",
    "svelte": "^3.35.0",
    "svelte-check": "^1.2.2",
    "svelte-preprocess": "^4.6.9",
    "tslib": "^2.1.0",
    "typescript": "^4.2.3"
  },
  "dependencies": {
    "sirv-cli": "^1.0.11"
  }
```

3. Create a simple app using a store

**BUG**: When using "Svelte for VSCode" 1.0.4.44 or above, **anything** written above the `$` prefixed store name causes errors. Only lines above `$storename`-lines are affected. Reactive statements' `$` are ok.
 
![image](https://user-images.githubusercontent.com/3778969/110172016-d6912880-7dfc-11eb-8716-85f700b67b6b.png)

**adding a semicolon** at the end of the affected lines, **fixes errors**:

![image](https://user-images.githubusercontent.com/3778969/110173543-0c371100-7dff-11eb-98e7-0f195ca0d355.png)
