### ISSUE TITLE
Get more robust/user friendly with preprocessors

### ISSUE THREAD

**Issue by dummdidumm** [sveltejs/language-tools#86]
**Is your feature request related to a problem? Please describe.**
Many people seem to have problems setting up preprocessors for the plugin - I guess partly because they install the extension and just expect it to work.

**Describe the solution you'd like**
Maybe we can get more robust/user friendly by doing the following things:
- If we don't detect a `svelte.config.js`, we just do a best guess by using https://github.com/kaisermann/svelte-preprocess
- If we detect that inside javascript "unexpected token"-errors occur, we enhance the error message with something like "have typed `lang="typescript"` in script? have you setup preprocessors correctly? see \<somelink\> for more info"

**Describe alternatives you've considered**
Make docs clearer.

**Comment by orta** [comment]
These are good calls 👍

**Comment by jasonlyu123** [comment]
Does the 'do a best guess' means:
1. adding `svelte-preprocess` as a dependency of language-server and make it the default preprocessor 

or

2. only try to import it from the user's workspace?

**Comment by dummdidumm** [comment]
It would mean adding it as a dependency and using it as the fallback preprocessor.

**Comment by dummdidumm** [comment]
As already stated in #87,  @jasonlyu123's second option could also be a good solution. Would save us from dependencies.

**Comment by benmccann** [comment]
I think just detecting if there are no preprocessors setup and telling them to add one with a helpful error message would be pretty helpful. It'd be a bit less magical and more explicit too, which I always think is nice
