### ISSUE TITLE
HTML tag renaming doesn't work

### ISSUE THREAD

**Issue by brgrz** [sveltejs/language-tools#861]
**Describe the bug**

Svelte blog mentions this here https://svelte.dev/blog/whats-new-in-svelte-march-2021 under Language tools and Language tools settings also mention it 

`svelte.plugin.html.renameTags.enable`

_Enable rename tags for the opening/closing tag pairs in HTML. Default: true_

However, this does not seem to work for me. Is there anything special to configure? 

I tried typing over the existing tag pair and the first part of the tag changes but nothing happens to the closing tag. The same if I start on the closing tag side. 

Since I know how this works in VS with other regular html files I would very much like this feature to work.

**To Reproduce**

Try to edit/rename/delete html tag pairs. Both opening and closing tag should change accordingly.

**Expected behavior**

Both opening and closing tag should change accordingly.

** System **

 - OS: Windows 10
 - IDE: VS Code 1.54.1
 - Svelte for VS Code v104.6.2

**Comment by dummdidumm** [comment]
Could you add a code snippet with instructions that reproduces this for you? For me it works.

**Comment by jasonlyu123** [comment]
This feature is done by rename-symbol on an HTML element. Or if you want to rename the tag on typing you can use `editor.linkedEditing` config to activate it. And our setting name for it is `svelte.plugin.html.linkedEditing.enable`

**Comment by brgrz** [comment]
After turning on `editor.linkedEditing` I can confirm editing HTML tags in pairs works. 

What is the `svelte.plugin.html.renameTags.enable` feature then?

**Comment by jasonlyu123** [comment]
Rename symbol. Like the one you rename variable. But only the start and end tags of the HTML element you chose.

**Comment by brgrz** [comment]
Hm, don't know how that looks in use. Also somewhat confusing naming and feature description.

**Comment by dummdidumm** [comment]
It's the same naming as in other contexts. When you rename a variable you press a key combination (in my case shift+f6) and are presented a little popover where you type in the new name, then press enter and all related variables are changed with it. What you want is linked editing, as the name says. The start tag is linked to the end tag and you change them both at once.
I'm going to close since this was a usage question which is now resolved.
