### ISSUE TITLE
Why is an exported function considered a prop?

### ISSUE THREAD

**Issue by aradalvand** [sveltejs/language-tools#873]
Say I have the following component:
`TextBox.svelte`:
```svelte
<script lang="ts">
    export function focus() {
        // ...
    }
</script>
```
I'm exporting this `focus` function so that when I get a reference to this component elsewhere using `bind:this={textbox}` I'd be able to do `textbox.focus()`.
That works. But when this component is being used, `focus` is being shown as a prop:

![image](https://user-images.githubusercontent.com/26527405/110736523-0f882d80-8241-11eb-85d5-c91475404a8a.png)

That's the case even if I export it as a const:
```svelte
<script lang="ts">
    export const focus = () => {
        // ...
    }
</script>
```

Note that in either case (whether `export const focus = () => { }` or `export function focus() { }`), even if I set the `focus` prop like this:
```svelte
<TextBox focus={() => { alert('Hi!'); }} />
```
**it doesn't actually alter the function.** So I don't think `focus()` should be shown in the list of props here, it's not really a prop.

**Comment by jasonlyu123** [comment]
This is because it can be extracted to a variable with `bind:` directive. As far as I know, it's not documented in the official doc. But it does work. And we currently can't find a way to distinguish these readonly ones in completion and diagnostic. So we made it props so that binding won't show a typing error.

**Comment by dummdidumm** [comment]
Svelte 5 runes mode no longer allows binding to exports directly to avoid confusion, i.e. you now have to use `bind:this` for these things:
```diff
<script>
- let foo;
+ let el;
// ...
-  foo();
+ el.foo();
</script>

- <Component bind:foo />
+ <Component bind:this={el} />
```
Intellisense will be adjusted accordingly, so the limitation is obsolete
