### ISSUE TITLE
Resolve types for "* .svelte" files from "* .svelte.d.ts" if they exist

### ISSUE THREAD

**Issue by trash-and-fire** [sveltejs/language-tools#878]
**Is your feature request related to a problem? Please describe.**

I want to publish some svelte modules initially written in typescript and preprocessed into "plain" `*.svelte`. Also I want to provide typings for those files. It is convenient to place `*.svelte.d.ts` files near original `*.svelte` file, but `svelte-language-server` ignores these definition files.

**Describe the solution you'd like**

For plain `*.svelte` file, which doesn't have `lang="ts"`, lang-server should use simple typescript node-module resolving rules as first attempt. It means that if `*.svelte.d.ts` file exists then it should be used.

**Additional context**

I made a sample project where we can ensure that two files are checked differently and manually typed `*.svelte` file is not properly checked. Just clone https://github.com/trash-and-fire/svelte-typings-demo and `npm install && npm run validate`. 

Errors should be the same between usages of `typed.svelte` and `manually-typed.svelte` components.

**Comment by dummdidumm** [comment]
Standard TS only looks at the file ending and prioritizes d.ts over .js . I think it's even technically impossible for TS to load both and then decide which one to use, because the internal program can only contain one definition for one file, not two. This means that it's not possible for Svelte files to change this behavior by actually looking into the file and determine if it has TS or not. This means we got to decide if we either always prioritize .svelte (current state) or always prioritize .svelte.d.ts . Since this only would really occur in the library case, I'm inclined to always prioritize svelte.d.ts . @jasonlyu123 @tomblachut thoughts?

**Comment by jasonlyu123** [comment]
One advantage being there are indeed some cases where it's not easy to type the component in the svelte file. Maybe allowing this would make it easier.

**Comment by dummdidumm** [comment]
The disadvantage is that if you rename props inside the `svelte.d.ts` file, it will not be reflected in the `.svelte` file. But that's the same behavior for `.d.ts` / `.js` files so I'd say this is expected behavior.

**Comment by non25** [comment]
There should be documented way to automatically generate `.svelte.d.ts` from `lang="ts"` svelte file. :thinking: 

And that would leave the need to write `.svelte.d.ts` manually only for non-TS users.

**Comment by trash-and-fire** [comment]
>  I think it's even technically impossible for TS to load both and then decide which one to use, because the internal program can only contain one definition for one file, not two.

I think it is possible but there may be some flaws. My pseudocode:
```
    function resolveModuleName(
        name: string,
        containingFile: string
    ): ts.ResolvedModule | undefined {
        const bySvelte = resolveUsingSvelteResolver(name, containingFile);
        const byTypescript = resolveUsingTypescriptResolver(name, containingFile);
        
        if (byTypescript && bySvelte) {
              // d.ts is possible
              if (isSveleteTS(name, containingFile, bySvelte)) {  // read this file and try to find lang="ts"
                   return bySvelte; // lang="ts" is more important than d.ts
              } else {
                   return byTypescript; // d.ts is more important plain *.svelte
              }
        }
        ...
    }
 ```
 
 I think `always prioritize .svelte.d.ts` is also a good option and can be easely implemented.

**Comment by dummdidumm** [comment]
@firefish5000 you might be interested in this upcoming change
