### ISSUE TITLE
/*Ωignore_startΩ*/ in .svelte files

### ISSUE THREAD

**Issue by PatrickG** [sveltejs/language-tools#879]
**Describe the bug**
When importing a store into a .svelte file, `/*Ωignore_startΩ*/` gets inserted after the import statement.

**To Reproduce**
```ts
// store.ts
import { writable } from 'svelte/store';
export const store = writable({});
```

```html
<script context="module" lang="ts">
  // Component.svelte
  import { store } from './store';
</script>
```

After saving the file, Component.svelte looks like this:
```html
<script context="module" lang="ts">
  // Component.svelte
  import { store } from './store'; /*Ωignore_startΩ*/
</script>
```

**Expected behavior**
`/*Ωignore_startΩ*/` should not be inserted

**Edit**
This only happens in `context="module"` script blocks.

**Comment by dummdidumm** [comment]
I'm not able to reproduce this. Could specify in more details how to import the store, for example by posting a snippet with `|` marking where the cursor is before doing the import (I'm assuming you are talking about auto-import?) and where it is before doing the save.

**Comment by PatrickG** [comment]
It has nothing to do with the cursor, it is the formatter I think.
I happens when I save the file (format on save is active)

![0IzcvPBHZ9](https://user-images.githubusercontent.com/196478/111524005-358b6180-875c-11eb-9de2-8a36fc058909.gif)

**Comment by dummdidumm** [comment]
Can reproduce this with the given snippet in the GIF and using the command "Organize Imports"
