### ISSUE TITLE
VSCode Import node_module Resolution

### ISSUE THREAD

**Issue by Jake13f** [sveltejs/language-tools#881]
**Describe the bug**
When importing node_modules (such as `npm i moment` ) or relative files into a `.svelte` file, the intellisense of installed node_modules doesn't display the module in the list.  The build will still compile and run fine however.  It seems as though the autocompletion is the only piece not working.

**To Reproduce**
1. Follow the `Getting Started` section on the official docs for sapper (same for svelte) https://sapper.svelte.dev/docs
2. *(Optional)* follow the setup typescript section. (the same issue occurs either way here.)
3. Run `npm i moment` in the project directory.
4. Attempt to `import moment from "moment"` (issue should appear)
5. Create a folder named `lib` for example and put a typescript file with an exported variable in it.
6. Try relatively importing the file (`import { test } from "./lib/test"`)

**Expected behavior**
It is expected that while typing the `from` portion that `moment` or the relative path would show up in the listings, however it does not.

**Screenshots**
<img width="847" alt="Screen Shot 2021-03-16 at 3 50 30 PM" src="https://user-images.githubusercontent.com/14061733/111371831-48c10300-8670-11eb-9ad2-521c290f63fb.png">
<img width="878" alt="Screen Shot 2021-03-16 at 4 05 05 PM" src="https://user-images.githubusercontent.com/14061733/111373072-dcdf9a00-8671-11eb-8304-e150420b7ba0.png">

**System (please complete the following information):**
 - OS: Mac OS 11.2.1, Ubuntu 20.04, and using the vscode remote ssh / wsl extension. (Tried different setups with all the OS's listed) (Probably occurs on windows too haven't tested though)
 - IDE: VSCode 1.54.3
 - Plugin/Package: Svelte for VSCode v104.6.4

**Comment by jasonlyu123** [comment]
Can't reproduce it. Someone did report a maybe-related issue on discord. But we also can't find out why.
Can you provide your `tsconfig.json` or `jsoconfig.json`? Maybe it has something to do with the include and exclude settings

**Comment by Jake13f** [comment]
@jasonlyu123 Here is the `tsconfig.json` I am using.  Again its just the one that was auto-generated from the setup script above.  If this isn't the issue I wonder if there could be some other extension in vscode maybe causing a conflict or something?  Idk just making a guess.
```json
{
	"extends": "@tsconfig/svelte/tsconfig.json",
	"compilerOptions": {
		"lib": [
			"DOM",
			"ES2017",
			"WebWorker"
		]
	},
	"include": [
		"src/**/*",
		"src/node_modules/**/*"
	],
	"exclude": [
		"node_modules/*",
		"__sapper__/*",
		"static/*"
	]
}
```

**Comment by jasonlyu123** [comment]
One thing in common is that both reacting to new files and path completion requires file system access. 
Probably this one
https://github.com/microsoft/TypeScript/blob/0cf834ceec96a820dd06742ce495a2fa9c50c44c/src/compiler/sys.ts#L1793
Maybe you can try cloning the language-tools reop and follow the development docs to debug. You can search this function in the typescript.js and set a breakpoint.

About other extensions, there's an option in the extension tab to disable all extensions. Maybe you can try to disable everything and only enable the svelte extension.

**Comment by Jake13f** [comment]
@jasonlyu123 I just tried disabling all extensions and only enabling the svelte for vscode extension but sadly still have the issue... So my guess is it isn't related to that.  As far as the other thing you wanted me to try, for some reason I can't get the break point to bind in the debugger.
<img width="1469" alt="image" src="https://user-images.githubusercontent.com/14061733/111662270-281ab980-87e6-11eb-8e6c-33c89a5a0893.png">

**Comment by Jake13f** [comment]
@jasonlyu123 So... after some more playing around, I realized that the issue seems to only arrise when using the sapper setup with typescript...?

**Comment by Jake13f** [comment]
@jasonlyu123 
I did an oopsies and hit the wrong button thinking it was discard comment lol... anyways reopening.

So after further testing on my mac here (will test later on my windows pc) it seems the issue is ONLY tied to the sapper build after converting it to typescript.  It appears to be working with the following combinations after following the official setup `npx degit` setups.

- `npx degit sveltejs/template my-svelte-project` (Imports working for both js and ts builds)
- `npx degit "sveltejs/sapper-template#rollup" my-app` (Imports working for `js` setup.  *NOT WORKING FOR TS SETUP*)

It seems as though something with the typescript setup in sapper is causing the issue.  My apologies for the confusion in the initial issue saying it affected the `js` build variant as well.  Again will report back if I get different results on my Windows PC.

**Comment by jasonlyu123** [comment]
>for some reason I can't get the break point to bind in the debugger.

You would have to attach a debugger to the server. it runs on a different process. Chose the attach option in the debugging panel after the extension debugging instance started.

**Comment by Jake13f** [comment]
@jasonlyu123 I swear to god I'm losing my mind testing this... I retested my mac environments again and now on windows and its working fine completely on my mac and windows.  The sapper js build and the sapper ts build as well.  Imports for local paths and node modules seem to be working fine.  In addition, I ran the project setup again on windows and both the js and ts setups are both working...

However, the issue remains when accessing the project using a WSL2 setup.  Both the js and ts versions of the project seem to not work with that.  I ran the debug extension with the language stuff like you said in the WSL2 setup and was debugging the breakpoint we spoke about.  Here are the results I found with that.

- When trying to access a directory, the parameters "seem" ok but there are just no results.
![nothing in pwd](https://user-images.githubusercontent.com/14061733/112066463-c25b6400-8b3c-11eb-8c08-7099393ced75.png)

- When trying to access a node_module, the breakpoint is hit multiple times as it recursively goes up the directory structure all the way to the root folder. (I only show a couple of pictures so you get the idea.) However, it never finds anything.  You can see by looking at the path watcher on the left.
> When doing the same debugging on my mac, the breakpoint never gets hit here when searching for node_modules.  I still can't get the debugger to attach on a windows only environment.  The debugger screenshots below are from the WSL2 issue.

![moment1](https://user-images.githubusercontent.com/14061733/112066588-0189b500-8b3d-11eb-8a2f-170b697ba95b.png)
![moment2](https://user-images.githubusercontent.com/14061733/112066589-02224b80-8b3d-11eb-9e72-614d4a3e6d83.png)
![moment3](https://user-images.githubusercontent.com/14061733/112066590-02bae200-8b3d-11eb-9d3e-73aafe7617a4.png)
![moment4](https://user-images.githubusercontent.com/14061733/112066591-02bae200-8b3d-11eb-87bb-070a449030cd.png)

**Comment by Jake13f** [comment]
@jasonlyu123 Nice job on finding the issue.  I didn't even think about the casing of the file path.  I tried moving the project to a directory without an uppercase folder and it appears to be working now so thanks again!
