### ISSUE TITLE
svelte2tsx outputs wrong invalid TSX (return value -> events)

### ISSUE THREAD

**Issue by hgiesel** [sveltejs/language-tools#886]
**Describe the bug**
`svelte2tsx` outputs invalid tsx given the example.

**To Reproduce**
Parse the following code with `svelte2tsx`:
```svelte
<script>
    import { createEventDispatcher } from "svelte";

    const dispatch = createEventDispatcher();
    dispatch("mount", { input });
</script>

<input on:focus />
```

It also works, if you do it in the [Svelte2tsx REPL](https://embed.plnkr.co/plunk/JPye9tlsqwMrWHGv). There is a comma missing in the return value, in the events property.

**Expected behavior**
Output valid tsx.

**System (please complete the following information):**
 - OS: macOS, Browser
 - Plugin/Package: `svelte2tsx`, I use the npm package directly

**Comment by dummdidumm** [comment]
Thanks for the report! Off topic question: What's your use case for using `svelte2tsx` directly?

**Comment by hgiesel** [comment]
The Ankitects team uses it for using Svelte + TypeScript with Bazel, usage [here](https://github.com/ankitects/rules_svelte/blob/ts-support/internal/svelte.js).
