### ISSUE TITLE
Hovering $store returns typeof store

### ISSUE THREAD

**Issue by pushkine** [sveltejs/language-tools#901]
```svelte
<script lang="ts">
    import { writable } from 'svelte/store';
    let foo = writable(1);
    $foo;
</script>
```
<img width="271" alt="Code_2021-03-21_19-53-55" src="https://user-images.githubusercontent.com/30108880/111917248-4818da00-8a7f-11eb-90a9-5589dedafad1.png">

**Comment by dummdidumm** [comment]
Idea: after converting to the generated position, check if it's part of store transformation (`(__sveltets_store_get(store),$store)` and if yes, get hover info of `$store` instead of `store` (current behavior).
