### ISSUE TITLE
Typescript and export { className as class } error

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/language-tools#911]
**Describe the bug**
I'm using Typescript (with `"strict": true`) and this code:

- Test.svelte

```svelte
<script lang="ts">
	let className: string | undefined = undefined;
	export { className as class };
</script>

<div class={className}>Hello</div>
```

- App.svelte:

```svelte
<Test class="red" />
```

TS error:

```
(JSX attribute) class?: undefined
Type 'string' is not assignable to type 'undefined'. ts(2322)
```

**Information about your Svelte project:**
System:
  OS: Windows 10
Binaries:
  Node: 14.16.0
npmPackages:
  rollup: 2.39.0 => 2.39.0
  svelte: 3.32.3 => 3.32.3

**Severity**
It blocks TS compilation.

**Comment by jasonlyu123** [comment]
To support it properly, we probably need to apply all the special processing with exported variables to export binding. In the meanwhile, you can workarounds this specific case by not having the `undefined` initializer. Or initialize it with an empty string.
