### ISSUE TITLE
When we have mentioned the default scrip to be "typescript" in the svelte.config.js file, then vs code still throws error when we don't mention lang="ts"

### ISSUE THREAD

**Issue by nateshmbhat** [sveltejs/language-tools#916]
My svelte.config.js file is : 

```js

module.exports = {
  preprocess: sveltePreprocess({
    defaults: {
      script: 'typescript',
    },
    scss: {
      includePaths: ['app/theme'],
    },
  }),
  hotReload: false,
}

```

When i am using svelte files , vs code still doesn't allow me to write typescript code even though i specified the default script to be 'typescript'.

I guess this is true for any other options. it's really important feature for language server to see through either this svelte.config.js file or the bundler files like webpack , rollup to see which preprocessor options we are using (at least for the standard ones)

**Comment by jasonlyu123** [comment]
What kind of error did you get? 

About read config from rollup.config.js. We can't do that because the config is not visible from the export.

**Comment by nateshmbhat** [comment]
The error is exactly what we get when we use ts code inside svelte component without Specifying the "lang" property

**Comment by dummdidumm** [comment]
I cannot reproduce this. Could you provide more details? Either a repository which reproduces the issue or a step-by-step guide.

**Comment by nateshmbhat** [comment]
The error i get in VScode is : 
`Type annotations can only be used in TypeScript files.js(8010)`

Here's my repo which contains the svelte.config.js file : 
https://github.com/nateshmbhat/tap-rpc

**Comment by nateshmbhat** [comment]
Ohh this is my bad. It looks like i hadn't properly restarted the svelte language server after adding the typescript config. Restarting it , fixed it for now.
