### ISSUE TITLE
console and Promise reported as not defined

### ISSUE THREAD

**Issue by mvolkmann** [sveltejs/language-tools#918]
**Describe the bug**
When editing a `.js` file in `src/lib`, if I use `console.log` or `Promise.all` they work, but VS Code reports `console` and `Promise` as not defined.

**To Reproduce**

Create the file `src/lib/demo.js` containing the following:

```js
console.log('demo');
const promises = [];
const p = Promise.all(promises);
```

Notice that `console` and `Promise` have squiggly red lines below them.

**Expected behavior**
VS Code should recognize these names as being defined.

**Screenshots**
![Screen Shot 2021-03-27 at 10 11 23 AM](https://user-images.githubusercontent.com/79312/112725175-dd372b00-8ee4-11eb-89e2-ac81d3865453.png)

**System (please complete the following information):**
 - OS: macOS
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode

**Comment by dummdidumm** [comment]
The Svelte for VS Code extension does not provide any form of diagnostics to JS/TS files. What are the error messages / codes exactly? What is the project type where you are getting this error (SvelteKit, ESLint yes/no, etc)?

**Comment by mvolkmann** [comment]
Ah, sorry. The error is from ESLint. An example message is "'console' is not defined. eslint(no-undef)".
This is a SvelteKit project. Maybe I need to modify the `.eslintrc.cjs` file it provides.
Ah ha! The errors go away if I add this:

```js
  env: {
    es6: true, // for Promise
    node: true // for console
  },
```

Perhaps these settings should be in `.eslintrc.cjs` by default for SvelteKit projects.
