### ISSUE TITLE
can't start with $ when sending on:event to child components

### ISSUE THREAD

**Issue by btrauma8** [sveltejs/language-tools#92]
vscode plugin  (svelte beta 99.0.18)

![image](https://user-images.githubusercontent.com/4399964/82127985-03485680-977d-11ea-983f-cd37462cc05f.png)

**Comment by dummdidumm** [comment]
@halfnelson could you have a look? This seems like something that needs to be fixed inside svelte2tsx

**Comment by halfnelson** [comment]
Yep certainly a case svelte2tsx is missing

**Comment by dummdidumm** [comment]
Should be fixed now.
