### ISSUE TITLE
Prettier: Allow to configure the path to the .prettierrc file

### ISSUE THREAD

**Issue by j3rem1e** [sveltejs/language-tools#931]
**Is your feature request related to a problem? Please describe.**

I sometime have to use a .prettierrc which is not on the root of the project. 

The "standard" prettier plugin (esbenp.prettier-vscode) allows me to configure where to search for the .prettierrc file, but I didn't find this option for the formatter of svelte filtes.

**Describe the solution you'd like**
I'd like to reuse the configuration of the prettier plugin, or at least, to be able to configure the path to this file.

**Comment by dummdidumm** [comment]
I'm wary of adding more prettier option to the extension. You can use `esbenp.prettier-vscode` for Svelte files as well as long as there's `prettier-plugin-svelte` in your `node_modules`.

**Comment by dummdidumm** [comment]
Closing for the reasons listed above. As mentioned, if you use `esbenp.prettier-vscode` and installed the `prettier-plugin-svelte` npm package, you are able to format Svelte files with the formatter extension - make sure to change your default formatter for Svelte files accordingly. This enables you to keep your configuration in one place/file/extension.
