### ISSUE TITLE
Component generic type inference issue

### ISSUE THREAD

**Issue by ryu-man** [sveltejs/language-tools#945]
**Describe the bug**
Svelte extension is unable to infer the generic type of a component (in .svelte file) from props 

**To Reproduce**

A.svelte
```
<script>
  export let prop
</script>
```

A.svelte.d.ts
`export default class A<T> extends SvelteComponentTyped<{prop:T}>`

App.svelte
```
<script>
    import A from './A.svelte'
</script>

// type inference work for prop but not for the component
<A  prop={3} />
```

**Expected behavior**
Component declared with generics should infer the types from props

**Screenshots**
![Untitled3](https://user-images.githubusercontent.com/25468773/114764728-2fd56b80-9d5c-11eb-9f16-e8c1a8cce2de.jpg)
![Untitled](https://user-images.githubusercontent.com/25468773/114764714-2cda7b00-9d5c-11eb-9ca1-610901bc9bed.jpg)

Type inference works fine when the component instantiated in a js file 
![Untitled1](https://user-images.githubusercontent.com/25468773/114764721-2e0ba800-9d5c-11eb-9abc-28b84a28be0a.jpg)

**System (please complete the following information):**
 - OS: Windows
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode

**Comment by dummdidumm** [comment]
`svelte2tsx` transformation:

```tsx
///<reference types="svelte" />
<></>;
import A from './A.svelte';
function render() {

  
;
() => (<>

<A prop={3} >{() => { let {prop} = __sveltets_instanceOf(A).$$slot_def['default'];<>
  {prop}
</>}}</A>
</>);
return { props: {}, slots: {}, getters: {}, events: {} }}

export default class extends createSvelte2TsxComponent(__sveltets_partial(__sveltets_with_any_event(render))) {
}
```

`__sveltets_instanceOf(A)` doesn't work here because the `$$slot` type is dictated by the props. It needs to be `new A({target: null, props: { prop: 3 }})` instead. Same for events probably. Not sure if this will also fix the hover bug, but I could live with that not getting inferred.
