### ISSUE TITLE
text/scss error sass,node-sass not found

### ISSUE THREAD

**Issue by SaintPepsi** [sveltejs/language-tools#946]
**Describe the bug**
Using preprocessor `svelte-preprocess` sass error in tooltip giving errors in different components

**To Reproduce**
Install `svelte-preprocess` and in a svelte component create a styled scss tag:
```
<style type="text/scss">
</style>
```

**Expected behavior**
Expect it not to give me a red scribble and errors

**Screenshots**
![image](https://user-images.githubusercontent.com/16056759/115091004-2f0f1780-9ecb-11eb-8120-b73e3b9cc793.png)

**System (please complete the following information):**
 - OS: Windows 10
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode

**Comment by jasonlyu123** [comment]
VS Code extension uses node version bundled with VS Code. And node-sass is sensitive to node version. 


You can set the `svelte.language-server.runtime` config. Since node-sass is deprecated now. I think you can save the hassle and just use dart-sass (sass module)

**Comment by SaintPepsi** [comment]
> VS Code extension uses node version bundled with VS Code. And node-sass is sensitive to node version.
> 
> You can set the `svelte.language-server.runtime` config. But since node-sass is deprecated now. I think you can save the hassle and just use dart-sass (the "sass" module)

thanks for taking the time to reply, I feel like a noob.
How do I use dart-sass instead? Just by uninstallinging node-sass and installing sass?

**Comment by dummdidumm** [comment]
Yes exactly

**Comment by SaintPepsi** [comment]
Thanks! :)
