### ISSUE TITLE
Basic setup of preprocessor results in an error in VS Code.

### ISSUE THREAD

**Issue by willnationsdev** [sveltejs/language-tools#949]
Can't find a duplicate (am I blind to it?), so...

**Describe the bug**
If a `svelte.config.js` file is present, any `.svelte` file that is opened in VS Code displays an error on the first line.

> The script element allows authors to include dynamic script and data blocks in their documents. The element does not represent content for the user.
> 
> Error in svelte.config.js
> 
> TypeError [ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING]: A dynamic import callback was not specified.svelte

**To Reproduce**

- Have VS Code installed.
- Install Svelte For VS Code 104.9.1 and Svelte Intellisense 0.7.1.
- Clone `sveltejs/template`.
- Run `npm install`
- Run `npm install -D svelte-preprocess`
- Create a `svelte.config.js` file in the root directory.
- Follow [general setup instructions to dedup preprocessor setup](https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/in-general.md#deduplicating-your-configs).
    - I specifically have no other changes aside from the template + the customizations in the dedup section. No addition of any preprocess plugins for any language yet.
- Open the `App.svelte` file. Observe red error line at top of file.
- Restart language server according to instructions. Error persists.

Naturally, doing `npm run dev` still properly builds and runs the static site.

Edit: I have found that the issue appears even before making any changes to the rollup. None of the following `svelte.config.js` contents work:

```js
// version 1
const sveltePreprocess = require('svelte-preprocess');

module.exports = {
    preprocess: sveltePreprocess({})
}

// version 2
module.exports = {
    preprocess: null
}

// version 3
module.exports = {}
```

**Expected behavior**
No errors appear during basic setup of preprocessor.

**System:**
 - OS: Windows 10
 - IDE: VS Code
 - Plugin/Package: "Svelte for VSCode"

**Comment by dummdidumm** [comment]
I am not able to reproduce this. To me this sounds like you did set the [path to the node executable](https://github.com/sveltejs/language-tools/tree/master/packages/svelte-vscode#sveltelanguage-serverruntime) in your user settings. If so, that node runtime needs to be at least 12.17 .

**Comment by willnationsdev** [comment]
@dummdidumm Thanks. Your guess helped me find the issue. It seems like there was a typo in the node executable path that was causing it to use an older version of node on my system (12.3). That then caused an issue with evaluating the `svelte.config.js`. Hopefully others who search for a similar error can resolve it without an Issue. 👍
