### ISSUE TITLE
vscode pug lint: All imports in import declaration are unused

### ISSUE THREAD

**Issue by basaran** [sveltejs/language-tools#958]
**Describe the bug**
When using pug template, linter is providing false notification on imports

**To Reproduce**

```
<script>
import {Accordion, AccordionItem} from 'carbon-components-svelte';
import {
    ContextMenu,
    ContextMenuDivider,
    ContextMenuGroup,
    ContextMenuOption,
} from 'carbon-components-svelte';
import CopyFile16 from 'carbon-icons-svelte/lib/CopyFile16';
import Cut16 from 'carbon-icons-svelte/lib/Cut16';
</script>

<template lang="pug">
main
    Accordion
        AccordionItem(title='Section 5') Content 1
        AccordionItem(title='Section 12') Content 2
        AccordionItem(title='Section 3') Content 3

    ContextMenu
        ContextMenuOption(
            icon='{CopyFile16}',
            indented,
            labelText='Copy',
            shortcutText='⌘C')
        ContextMenuOption(
            icon='{Cut16}',
            indented,
            labelText='Cut',
            shortcutText='⌘X')
        ContextMenuDivider
        ContextMenuOption(indented, kind='danger', labelText='Delete')
</template>
```

**Expected behavior**
Imported components are used and there should be no linting issues.

**Screenshots**

![image](https://user-images.githubusercontent.com/30809170/115701049-5afc2400-a335-11eb-9faa-fbb2b56c1566.png)

![image](https://user-images.githubusercontent.com/30809170/115701080-64858c00-a335-11eb-9837-933f3a001ed0.png)

**System (please complete the following information):**
 - OS: Winows
 - IDE: VsCode
 - Plugin/Package: Svelte for VSCode

**Additional context**

**Comment by 300code** [comment]
i have same issue but it not effect in code
