### ISSUE TITLE
VS Code displays an error on type annotation

### ISSUE THREAD

**Issue by maximedupre** [sveltejs/language-tools#96]
I have the Svelte Beta extension installed and have restarted the language server. My `svelte.config.js` is:

```
const sveltePreprocess = require('svelte-preprocess');

module.exports = {
    preprocess: sveltePreprocess(),
};
```

However, the extension does not seem to help VS Code understand that my code is Typescript, since it gives an error on type annotation: 

> Type annotations can only be used in TypeScript files. javascript

![Screen Shot 2020-05-19 at 8 24 24 PM](https://user-images.githubusercontent.com/5158181/82391204-c1364380-9a0e-11ea-9c57-11c1d0fd25fc.png)

Also interesting, if I change `lang="typescript"` to `type="text/typescript"`, the syntax colours completely go away, as well as the error:

![Screen Shot 2020-05-19 at 8 26 22 PM](https://user-images.githubusercontent.com/5158181/82391315-0490b200-9a0f-11ea-96f4-521de47c19c4.png)

**System (please complete the following information):**
 - OS: macOS Catalina 10.15.4
 - IDE: VS Code
 - Plugin: Svelte Beta

**Comment by jasonlyu123** [comment]
Can you post the entire file's code here, or a example repo? I can't reproduce it.

**Comment by maximedupre** [comment]
Here's a minimal reproduction:

```
<script lang="typescript">
	let countExcludingUser: number = 0;
</script>

<p>Hi</p>
```

![Screen Shot 2020-05-19 at 8 53 22 PM](https://user-images.githubusercontent.com/5158181/82392823-cf865e80-9a12-11ea-82ae-73819a55b93a.png)

I disabled all extensions except Svelte Beta and restarted VS Code, with no success.

**Comment by jasonlyu123** [comment]
I only managed to reproduce once and no luck after that. Can you try it again it the latest build 99.0.22? There is some update about preprocessing in this version. If it still persists can you make an example repo?

**Comment by dummdidumm** [comment]
From your description it seems that `SveltePlugin.ts` does get that it should preprocess with Typescript because there is no Svelte syntax error like "unexpected token". On the other hand `TypescriptPlugin.ts` does - for some reason - not recognize that you use Typescript but thinks it's Javascript instead. Really strange.. An example repo would certainly help.

**Comment by maximedupre** [comment]
Ah, so the problem was because I had this in my  VS Code "User" settings:

```
  "files.associations": {
    "*.svelte": "html"
  },
```

Now that I've removed it, everything seems to work fine.

**Comment by benwoodward** [comment]
Not sure if this is related but I'm getting the same error on a `number` annotation using Neovim:

![image](https://user-images.githubusercontent.com/1472981/154443100-5abca1af-24fd-4862-bf44-80b9d504ff91.png)

tsconfig:

```json
{
  "extends": "@tsconfig/svelte/tsconfig.json",
  "compilerOptions": {
    "moduleResolution": "node",
    "module": "esnext",
    "lib": ["esnext"],
    "target": "es2019",
    "strict": true,
    "noImplicitAny": false,
    /**
      svelte-preprocess cannot figure out whether you have a value or a type, so tell TypeScript
      to enforce using \`import type\` instead of \`import\` for Types.
      */
    "importsNotUsedAsValues": "error",
    "allowSyntheticDefaultImports": true,
    "isolatedModules": true,
    "resolveJsonModule": true,
    /**
      To have warnings/errors of the Svelte compiler at the correct position,
      enable source maps by default.
      */
    "sourceMap": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "baseUrl": ".",
    "allowJs": true,
    "checkJs": true,
    "paths": {
      "$lib": ["src/lib"],
      "$lib/*": ["src/lib/*"]
    }
  },
  "include": ["src/**/*.d.ts", "src/**/*.js", "src/**/*.ts", "src/**/*.svelte"],
  "exclude": ["node_modules/*"]
}
```

**Comment by wyhinton** [comment]
`<script language="typescript">` was causing an error for type annotations but when I changed it to `<script lang="ts">` it worked
