### ISSUE TITLE
Bracketed type assertions for <script context="module" lang="ts"> are not correctly highlighted

### ISSUE THREAD

**Issue by hgl** [sveltejs/language-tools#964]
**Describe the bug**
See the reproduction.

**To Reproduce**
```
<script context="module" lang="ts">
const a = <string>"b"
</script>
```

`string` will be be underlined, with a popup saying

```
JSX element 'string' has no corresponding closing tag.ts(17008)
```

**Expected behavior**
Highlight correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/7038035/115981817-45069180-a5c9-11eb-844e-24d823b6b10c.png)

**System (please complete the following information):**
 - OS: Mac
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode

**Additional context**
Bracketed type assertions work for regular `<script lang="ts">` though

**Comment by hgl** [comment]
Thanks for the quick fix.

However, syntax highlighting seems still broken.

**Comment by jasonlyu123** [comment]
Move the lang attribute to before the context should fix it. Don't know if we can make it work with every attribute order. But it probably won't be fixed soon.

**Comment by hgl** [comment]
You're absolutely right. Thanks for the tip.

**Comment by dummdidumm** [comment]
Highlighting should work now, too.
