### ISSUE TITLE
Rename breaks attribute shorthand/binding

### ISSUE THREAD

**Issue by pushkine** [sveltejs/language-tools#969]
```svelte
<script>
	let value = "";
</script>

<input bind:value />
<input {value} />
```
<img width="220" alt="Code_2021-04-26_16-36-26" src="https://user-images.githubusercontent.com/30108880/116100848-9ab46a00-a6ad-11eb-99e3-bfa7ec3b2d66.png">
<img width="140" alt="Code_2021-04-26_16-36-41" src="https://user-images.githubusercontent.com/30108880/116100854-9c7e2d80-a6ad-11eb-832f-a8815b7c82a7.png">

**Comment by dummdidumm** [comment]
@jasonlyu123 I saw you started implementing this, looking at the branch the approach seems promising. What's the status on that? If you don't have time to continue, I can take over if you want.

**Comment by jasonlyu123** [comment]
There's some edge case where edits would have overlapping ranges and cause a weird rename. I'll try again this week.
