### ISSUE TITLE
$store errors when used in #await

### ISSUE THREAD

**Issue by kesne** [sveltejs/language-tools#97]
**Describe the bug**
It appears that attempting to subscribe to a store (for example, if you had `Readable<Promise<T>>`) in an #await block produces an error in the IDE.

**To Reproduce**
```svelte
<script>
	import { readable } from 'svelte/store';
	const store = readable(Promise.resolve('test'), () => {});
</script>


{#await $store}
	<p>loading</p>
{:then data}
	{data}
{/await}
```

**Expected behavior**
The #await should work and correctly unwrap the store type.

**Screenshots**
<img width="805" alt="Screen Shot 2020-05-20 at 12 39 48 AM" src="https://user-images.githubusercontent.com/498479/82418948-8c3be800-9a32-11ea-9b72-ba99342c84b6.png">

**System (please complete the following information):**
 - OS: Mac
 - IDE: VSCode
 - Plugin: Svelte Beta

**Comment by orta** [comment]
reading the PR, this looks to be fixed and now is upstreamed into this repo
