### ISSUE TITLE
Handle custom properties in JSX

### ISSUE THREAD

**Issue by pushkine** [sveltejs/language-tools#974]
https://github.com/sveltejs/language-tools/blob/c676a77629107fa494fc12787a6d1dbe55ff495f/packages/svelte2tsx/src/htmlxtojsx/nodes/attribute.ts#L85-L89

Not particularly interested in having this issue fixed but with spreading I think pretty much any property name is valid

```tsx
function Component({ "--foo": foo }) {
  return <>{foo}</>;
}

function App() {
  return <Component {...{ "--foo": "this works" }} />;
}
```

**Comment by dummdidumm** [comment]
You can't define a property through `export let` with leading dashes. This means custom css properties are not part of the props interface of a component. Still with the upcoming RFC implementation you can pass custom css properties to any component. This means if we keep it as a property it might emit a wrong error that `-foo` is not a known property.
