### ISSUE TITLE
Can't import a type in both regular and module scripts

### ISSUE THREAD

**Issue by hgl** [sveltejs/language-tools#975]
**Describe the bug**
I'm not sure if this is a bug, but when a type in imported in both regular and module scripts, ts complains:
```
Duplicate identifier '...'
```
It seems they live in the same scope. Does it have something to do with the transpilation that happens under the hood?

**To Reproduce**
```svelte
<script lang="ts" context="module">
import type { Config } from "@sveltejs/kit";
</script>

<script lang="ts">
import type { Config } from "@sveltejs/kit";
</script>
```

**Expected behavior**
No error

**Screenshots**
![image](https://user-images.githubusercontent.com/7038035/116515403-d72ad480-a8fe-11eb-8376-8c9bfa1b087c.png)

**System (please complete the following information):**
 - OS: MacOS
 - IDE: VS Code
 - Plugin/Package: Svelte for VSCode"

**Additional context**

**Comment by dummdidumm** [comment]
This works as designed. Imports in both module and instance script are hoisted to the top of the file in the JS output (they can't appear anywhere else), so there can by only one import of a specific thing per file.
