### ISSUE TITLE
Errors from other files get reported in .svelte files

### ISSUE THREAD

**Issue by blaumeise20** [sveltejs/language-tools#976]
**Describe the bug**
I'm using Svelte with TypeScript and SCSS, and I get this weird thing where I write a syntax error in a SCSS file which I import with `@use` into my Svelte file, and the error gets reported in the Svelte file too:
![Bildschirmfoto 2021-04-29 um 16 37 12](https://user-images.githubusercontent.com/62756994/116573133-d6993a80-a90c-11eb-9c1e-cb9686c59f9d.png)
![Bildschirmfoto 2021-04-29 um 16 37 21](https://user-images.githubusercontent.com/62756994/116573155-da2cc180-a90c-11eb-911b-7d212bab0a70.png)

**To Reproduce**

- Create a new Svelte file in VSCode that is in a workspace with preprocessing SCSS.
- Add `includePaths` to the preprocessor config for SCSS
- Add a style to the Svelte file with `@use` and specify the name like in the picture above.
- Write some syntax errors into the SCSS file.

**Expected behavior**
Don't report errors in files they are not in.

**Screenshots**
Added above.

**System (please complete the following information):**
 - OS: Mac OS 10.15.7
 - IDE: VSCode
 - Plugin/Package: "Svelte for VSCode"

**Comment by jasonlyu123** [comment]
The error is probably a preprocess failure error. We're showing the error from preprocessing and the error from the svelte compiler. We could add a config to suppress it. But that would cause some confusion when the error from the svelte compiler doesn't show up because of preprocessing failure.

**Comment by dummdidumm** [comment]
Not showing preprocessing errors would hurt DX in other places - you wouldn't know what's going on. In this case I even argue it's good to see the error in Svelte file, too, to get notified of it earlier. The only thing that we could look into improving - and I don't know if that's possible - is to see if we somehow can know that the error is from an external file and prepend the error with a corresponding text (like "error in imported file").

**Comment by blaumeise20** [comment]
I think you should have an option to disable error reporting from other files in the Svelte file. Sometimes the error appears in a very unrelated place like 20 lines below the style tag end. So if you leave it like that, maybe show the error on the `@use` statement itself. That would definitely make the error more clear.

**Comment by dummdidumm** [comment]
We are at mercy of what information the preprocessors give us. It seems that SCSS has a `file` property which we can use to determine that the error is from another file, which we can use to make it clearer that the error is not from within the Svelte file. But this is only a heuristic so to speak for one specific preprocessor, so there will be no option.
