### ISSUE TITLE
vector-effect is treated as an unknown property

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/language-tools#977]
**Describe the bug**
When I use [`vector-effect`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/vector-effect) in CSS, I am warned that it's an unknown property:

![image](https://user-images.githubusercontent.com/1162160/116592363-ed7c6480-a8ed-11eb-96b5-53258b53410d.png)

**To Reproduce**
Just add a style block to any Svelte component that looks like this:

```svelte
<svg>
  <circle r=10 stroke=black/>
</svg>

<style>
  circle {
    vector-effect: non-scaling-stroke;
  }
</style>
```

**Expected behavior**
No warning.

**System (please complete the following information):**
 - OS: Catalina
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode

**Additional context**
The `unknownProperties` warning is tested for here... https://github.com/sveltejs/language-tools/blob/0ac9826befb647e6f0fafad706efa3752a768979/packages/language-server/test/plugins/css/CSSPlugin.test.ts#L172-L189 ...and `vector-effect` is listed as an SVG _attribute_ here... https://github.com/sveltejs/language-tools/blob/0b390a2556470b700935c0a7bd3f2128979faab5/packages/svelte2tsx/svelte-jsx.d.ts#L648 ...though presumably that's unrelated to CSS handling.

**Comment by dummdidumm** [comment]
Likely an upstream issue with vscode-css-languageservice

**Comment by dummdidumm** [comment]
Did some digging, if I read [the spec](https://www.w3.org/TR/SVG2/coords.html#VectorEffectProperty) correctly this attribute is not standard yet, which is why it does not appear in the list of known properties for the css language service yet.

**Comment by cuixiping** [comment]
Is there any way to config what css properties are allowed?

**Comment by dummdidumm** [comment]
No
