### ISSUE TITLE
💥 Virtual Memory leak

### ISSUE THREAD

**Issue by yassinrais** [sveltejs/language-tools#979]
Everything is expalin in this screenshot

![image](https://user-images.githubusercontent.com/25354731/117032536-d7addb80-ad01-11eb-9117-366a7811a416.png)

**Comment by dummdidumm** [comment]
I'm sorry, but no, nothing is explained in this screenshot. Please provide infos about your system and how to reproduce this.

**Comment by yassinrais** [comment]
_Im Using REMOTE SSH extension_

```
Linux dev.rais.me 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux
Node v14.16.0
NPM 6.14.11
```

Even the svelte dev  is using 21GB x Z process more then the extension svelte 😅

Im using latest version of sveltekit @next + tailwindcss
Without looking into my sveltekit project , this issue exist without the existant of the project (svelte extension) 


Example of a non svelte project , i just created a file svelte , it does not do anything, at the time i start writing code, its runing 
svelte language server and the process look like this 
![image](https://user-images.githubusercontent.com/25354731/117073813-be715300-ad32-11eb-9045-9c9a97d30f3c.png)
![image](https://user-images.githubusercontent.com/25354731/117073838-cb8e4200-ad32-11eb-9142-6675e0ce97fd.png)

**Comment by yassinrais** [comment]
_Im Using REMOTE SSH extension_

```
Linux dev.rais.me 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux
Node v14.16.0
NPM 6.14.11
```

Even the svelte dev  is using 21GB x Z process more then the extension svelte 😅

Im using latest version of sveltekit @next + tailwindcss
Without looking into my sveltekit project , this issue exist without the existant of the project (svelte extension) 


Example of a non svelte project , i just created a file svelte , it does not do anything, at the time i start writing code, its runing 
svelte language server and the process look like this 
![image](https://user-images.githubusercontent.com/25354731/117074903-4a37af00-ad34-11eb-8d1e-58418d480145.png)
![image](https://user-images.githubusercontent.com/25354731/117073838-cb8e4200-ad32-11eb-9142-6675e0ce97fd.png)

**Comment by yassinrais** [comment]
_Im Using REMOTE SSH extension_

```
Linux dev 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux
Node v14.16.0
NPM 6.14.11
```

Even the svelte dev  is using 21GB x Z process more then the extension svelte 😅

Im using latest version of `sveltekit@next` + tailwindcss
Without looking into my sveltekit project , this issue exist without the existant of the project (svelte extension) 


Example of a non svelte project , i just created a file svelte , it does not do anything, at the time i start writing code, its runing 
svelte language server and the process look like this 
![image](https://user-images.githubusercontent.com/25354731/117074903-4a37af00-ad34-11eb-8d1e-58418d480145.png)
![image](https://user-images.githubusercontent.com/25354731/117073838-cb8e4200-ad32-11eb-9142-6675e0ce97fd.png)

**Comment by Kapsonfire-DE** [comment]
VIRT also includes pages that have been allocated but not used for anything yet. Any page in this state is mapped to the kernel Zero Page (brilliant concept--you should look it up) so it shows up in VIRT but doesn't actually consume any memory.

>VIRT stands for the virtual size of a process, which is the sum of memory it is actually using, memory it has mapped into itself (for instance the video card’s RAM for the X server), files on disk that have been mapped into it (most notably shared libraries), and memory shared with other processes. VIRT represents how much memory the program is able to access at the present moment.

All in all, you can ignore the VIRT Ubducatir, important is the RES
Look more on Answers on https://serverfault.com/questions/138427/what-does-virtual-memory-size-in-top-mean

**Comment by yassinrais** [comment]
But the weird  things , why its does do this only for the svelte and not others type of extensions / project like vue and react etc . ?

**Comment by Kapsonfire-DE** [comment]
I guess svelte references internally more system libraries which are not directly needed or just in some cases. its possible to deep digger but as long as there is no real huge memory usage i dont see a reason to do this.

**Comment by yassinrais** [comment]
Im not sur but having that allocated size can damage the SSD 👀 ?

**Comment by Kapsonfire-DE** [comment]
Nope - thats Not swapped

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by dummdidumm** [comment]
I only understood half of this conversation, but it seems that there is no real issue here, so I'm going to close this.
