### ISSUE TITLE
"version" is a required argument.svelte warning

### ISSUE THREAD

**Issue by snorreks** [sveltejs/language-tools#987]
**Describe the bug**
VSCode gives me a warning "version is a required argument.svelte" at the top of every svelte file. Running svelte-check gives me no warnings.

**To Reproduce**
I am using typescript and did not have this issue yesterday (may 05). Maybe it is because of the newly added typescript-plugin?

**Expected behavior**
I don't expect the IDE to give me a warning.

**Screenshots**
![image](https://user-images.githubusercontent.com/36089469/117259910-cc1bfb00-ae4e-11eb-9fb7-131f5e1d4b75.png)

**System (please complete the following information):**
 - OS: Windows
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode, svelte-check(1.4.0), rollup-plugin-svelte(7.1.0), svelte-preprocess(4.7.2), svelte(3.37.0).

**Additional context**
- My svelte.config.js
```javascript
const sveltePreprocess = require('svelte-preprocess');

function createPreprocessors(sourceMap) {
  return sveltePreprocess({
    sourceMap,
    defaults: {
      script: 'typescript',
      style: 'scss'
    },
    postcss: {
      plugins: [require('autoprefixer')]
    },
  });
}

module.exports = {
  preprocess: createPreprocessors(true),
  createPreprocessors
};

```

**Comment by dummdidumm** [comment]
I think it's a result of #982
