### ISSUE TITLE
Autocompletion of attributes on HTML tags show JSX attributes after running TypeScript script

### ISSUE THREAD

**Issue by alok-mishra** [sveltejs/language-tools#989]
**Describe the bug**
Autocompletion of attributes on HTML tags show JSX attributes after running TypeScript script.  This is with new install of VSCode with Svelte for VS Code extension.

**To Reproduce**
1. Scaffold svelte using the recommended method:
`npx degit sveltejs/template svelteapp`
`cd svelteapp`
2. Setup TypeScript using the provided script:
`node scripts/setupTypeScript.js`
3. Clean install VSCode on Windows (also tried Insiders) with default, clean settings
4. Add "Svelte for VS Code" Extension (current version: 104.12.0)
5. Open svelteapp folder with VSCode, and start editing "App.svelte" file inside "src" folder.
6. Start typing `class` on any HTML tag.. (screenshot below) and see JSX attributes on top before the one needed.

**Expected behavior**
I would not like to see any JSX attributes as I don't use them, or have an option to disable them.
For example if I start typing `class` in a HTML tag, I would like the normal completion which I can tab into and the cursor is inside the quotes generated i.e. `class="|"`.

**Screenshots**
![image](https://user-images.githubusercontent.com/8043332/117347736-6c861580-ae77-11eb-8c74-dc9ecd4fd551.png)

**System:**
 - OS: Windows
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode

**Comment by dummdidumm** [comment]
The suggestions are right, it's just confusing that they are presented as JSX attributes. Also see #718 . What we can do though is at least deduplicate those suggestions.
