### ISSUE TITLE
PostCSS Syntax Highlighting

### ISSUE THREAD

**Issue by jameygleason** [sveltejs/language-tools#996]
Hello. Thank you for your hard work.

I'm wondering if there is any interest in syntax highlighting postcss like an scss block?

I'm currently using a vanilla style tag that is processed correctly by postcss, but nesting and other syntax highlighting is nicer when using lang="scss".

I looked through the code base to see if I could figure out a hack and came upon this:

https://github.com/sveltejs/language-tools/blob/a8fd8082f093afe3dc7c22e8d7a965ab7d28360f/packages/svelte-vscode/syntaxes/svelte.tmLanguage.src.yaml#L65

Not sure if I'm looking in the right place?

After reading the contributing guide it seems like there is some interesting stuff going with how things get processed. I would be open to making a PR with a little guidance.

Thank you.

<img width="212" alt="vanilla" src="https://user-images.githubusercontent.com/81653263/117558221-62b40c00-b049-11eb-9c3d-aa8ad6b25acd.PNG">

<img width="213" alt="postcss" src="https://user-images.githubusercontent.com/81653263/117558226-6a73b080-b049-11eb-9a6e-8dbc836275c0.PNG">

<img width="213" alt="scss" src="https://user-images.githubusercontent.com/81653263/117558228-6cd60a80-b049-11eb-9078-eba4428628fc.PNG">

**Comment by jasonlyu123** [comment]
We did define syntax-highlight for postcss but you would have to have another extension for it to work. In the syntax-highlight of VSCode, you can define a region in your scope to follow another scope. svelte-vscode chose to use [source.css.postcss](https://github.com/sveltejs/language-tools/blob/master/packages/svelte-vscode/syntaxes/svelte.tmLanguage.src.yaml) scope name for `<style lang="postcss"`. But doesn't come with a built-in highlight for this scope. It relies on another extension to provide the syntax highlight for the scope. So you would have to find the right extension to provide a highlight to postcss scope.

The main problem is that there aren't many extensions that use this scope name to provide syntax highlight for postcss. and they all didn't get updates for a while. For example, https://marketplace.visualstudio.com/items?itemName=mhmadhamster.postcss-language. 

The most recently maintained extension that provides syntax-highlight for postcss one doesn't use this scope. Instead, it overrides CSS with postcss syntax highlight. and let postcss files use CSS scope. And it also disables built-in CSS language features.

Another one providing syntax-highlight for this scope is [vetur](https://marketplace.visualstudio.com/items?itemName=octref.vetur). It's a language extension for vue. It would use more disk storage. If you don't mind the disk usage or you use vue, that's also an option. 

Right now I don't know how can we solve this. I think we won't want to maintain our own version. That would be a maintenance burden, and it requires someone with more knowledge of postcss. Besides the current solution, I guess the easiest solution is to set up a way to copy some syntax highlight from other repo and bundle it with svelte-vscode.

**Comment by jameygleason** [comment]
This is good information. Thank you.

I achieved the same results with [Vetur](https://marketplace.visualstudio.com/items?itemName=octref.vetur) and [postcss-sugarss-language](https://marketplace.visualstudio.com/items?itemName=mhmadhamster.postcss-language)

postcss before:
<img width="213" alt="postcss-before" src="https://user-images.githubusercontent.com/81653263/117566378-5c8f5100-b084-11eb-9f32-ec5926a1f79b.png">

postcss with syntax highlighting plugin:
<img width="205" alt="postcss" src="https://user-images.githubusercontent.com/81653263/117566391-67e27c80-b084-11eb-9503-517bc8a677ec.PNG">

scss:
<img width="207" alt="scss" src="https://user-images.githubusercontent.com/81653263/117566399-7466d500-b084-11eb-8c91-ce850a1f0dae.PNG">

It wasn't initially clear that a syntax highlighting plugin would be necessary. Since postcss uses the `.css` extension, you generally get css features for free. Although in hindsight it makes sense.

Not suggesting we create more of a maintenance burden, but would it be prudent to add a list item under [features](https://github.com/sveltejs/language-tools/tree/master/packages/svelte-vscode#features) with a link to these plugins?

**Comment by jasonlyu123** [comment]
I want to clarify that I don't know if we should recommend these two as the official solution. Vetur is too overkill for just postcss syntax highlight. And postcss-sugarss-language have been updated for a long time which I don't if that's a good recommendation. But until we have another conclusion. These are probably two valid options for now.

**Comment by dummdidumm** [comment]
For reference, [this is the grammar for postcss in vetur](https://github.com/vuejs/vetur/blob/master/syntaxes/vue-postcss.json) . Not sure if we should copy it over (with giving credit, of course).

**Comment by jameygleason** [comment]
I haven't had time to dig into how language services work yet, but for what it's worth I found the official Microsoft language tools. A naïve approach to get started could be to covert the SCSS code to handle PostCSS. Do you think that would work?

[cssLanguageService.ts](https://github.com/microsoft/vscode-css-languageservice/blob/main/src/cssLanguageService.ts)

[scssParser.ts](https://github.com/microsoft/vscode-css-languageservice/blob/main/src/parser/scssParser.ts)

**Comment by dummdidumm** [comment]
These are for dealing with autocompletion, error diagnostics etc and have nothing to do with syntax highlighting. The syntax highlighting files are probably somewhere in the VS Code repository.

**Comment by Monkatraz** [comment]
The way to handle this issue in the most generic, workaround-enabling way possible would be to provide an attribute that sets the scope of the language to be used.

Something like:

```html
<style lang="postcss" tm-scope="source.sugarss">
```

This is hacky, but it would work. It is maybe possibly to dynamically generate textmate grammars that extend/inject into the original - I have no idea if that sorta system could be dynamically loaded.

**Comment by jameygleason** [comment]
@Monkatraz Syntax highlighting works if you have either plugin installed and use Seems like my original issue was resolved by @jasonlyu123 's first comment.

`lang="scss"` is nicer aesthetically than `lang="postcss"` imo. I'm trying to figure out how to alias `lang="postcss"` to use `lang="scss"` highlighting.

Although leaving the lang attribute off altogether seems to work just fine. (Assuming you have your PostCSS config setup correctly.) Hard to know what the right thing to do here is. Just figuring out the best tradeoff for my personal taste at this point.

**Comment by jameygleason** [comment]
Yeah, it seems like there are deeper constraints here that I'm not privy to. Thank you for the responses.

**Comment by pikeas** [comment]
`<style lang="postcss">` sets the VS Code language (and scope?) to `svelte`, which is why there's no highlighting in that mode.

Can this extension pass through a language config setting? If not, perhaps it's worth cheating for now and setting the SCSS language when style tags are configured for PostCSS?

**Comment by jasonlyu123** [comment]
Because of the customizable nature of postcss. Treat postcss as SCSS would not be right in some cases. If your _build step allows_ and the style is valid SCSS. I would suggest just use `lang="scss"`. That's also the case for CSS. 

About config, the syntax highlight of vscode can't be dynamic. So we can't pass through a config. Maybe fallback is possible, but I don't know if that would cause other problems.

**Comment by takoyaro** [comment]
I'm just gonna leave this here, it might work for you or not but I personally just added another `style` to the tag. I.e.:
```html
<style style lang="postcss">
  .yourStylesHere{
    @apply coolstuff
  }
</style>
```

I can't explain why it works but it does and I didn't have to install any package or edit any config files.

**Comment by Monkatraz** [comment]
> I'm just gonna leave this here, it might work for you or not but I personally just added another `style` to the tag. I.e.:
> ```html
> <style style lang="postcss">
>   .yourStylesHere{
>     @apply coolstuff
>   }
> </style>
> ```
> 
> I can't explain why it works but it does and I didn't have to install any package or edit any config files.

It works because I guess `style` is a valid attribute, but most importantly the way that the grammar figures out what language to highlight with involves just a simple regex, basically. When you put style behind the lang attribute it doesn't match the postcss regex anymore. It's dumb and we're forced to use this because of the archaic grammar format.

**Comment by dummdidumm** [comment]
Right, and it won't work for much longer because I loosened the regex to fix #964

**Comment by jeremyswann** [comment]
Can confirm the current workaround is working thanks to this discussion and reading changes made in [docs/preprocessing.md](https://github.com/sveltejs/svelte-preprocess/blob/main/docs/preprocessing.md). Setting `sveltePreprocess({ defaults: { style: "postcss" }})` defaults all `<style>` tags to `lang="postcss"`. Example below shows nested css and tailwindcss @apply classes. I can confirm that the syntax highlighting works as well as the correct linting.
```html
<style>
  p {
    a {
      @apply bg-red-500;
    }
  }
</style>
```
Given the continuing mix of common modules in preprocessors and linters I don't think this will ever get resolved.

**Comment by dummdidumm** [comment]
I dug into this, turns out that Vetur also just copied its grammar from a now archieved repository. Since it seems to work out well for Vetur, I did the same. `lang="postcss"` will now have syntax highlighting.
